### ISSUE TITLE
Postgres SERIAL and BIGSERIAL are created as INT / BIGINT without auto increment

### ISSUE THREAD

**Issue by WellingR** [liquibase/liquibase#1009]
The following liquibase changeset does not work as expected

```xml
        <createTable tableName="test">
            <column name="id" type="SERIAL">
                <constraints nullable="false" primaryKey="true"/>
            </column>
        </createTable>
```

This changeset results in sql

```sql
CREATE TABLE test (id INTEGER NOT NULL, CONSTRAINT TEST_PKEY PRIMARY KEY (id));
```

In liquibase 3.6.3 and earlier the type `SERIAL` was used for the column which means that a sequence is automatically included.

This issue seems to be caused by #874
It appears that SERIAL columns are replaced by INT, however liquibase does reconize that this column type is an auto increment column.

It would be acceptible if the generated sql would be

```sql
CREATE TABLE test (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, CONSTRAINT TEST_PKEY PRIMARY KEY (id));
```

**Comment by SteveDonie** [comment]
I am looking into ways that this sort of comment with account ids from Jira shows up better here in github.

**Comment by BorzdeG** [comment]
I solved this problem for myself simply by explicitly adding `autoIncrement`

```xml
<column name="id" type="SERIAL" autoIncrement="true"/>
```

**Comment by WellingR** [comment]
While setting `autoIncrement="true"` works well for new changesets, it breaks existing changesets (the hash changes) and it also generates different sql.

**Comment by gkillough** [comment]
I ran into this problem in a couple of different projects. I'm not sure the `autoIncrement=true` is a good enough solution. When using Postgres with Java and Hibernate, generated id columns should have their "generation strategy" explicitly defined. The generation strategy that corresponds with `SERIAL` and `BIGSERIAL` Postgres types is `SEQUENCE`. This strategy tells Hibernate to get the underlying sequence from Postgres in order to get the correct value. If Liquibase and Hibernate are not using the same strategy, this can cause duplicate key violation constraints.

References: 
https://www.postgresql.org/docs/9.1/datatype-numeric.html#DATATYPE-SERIAL 
https://www.postgresqltutorial.com/postgresql-serial/ 
https://ntsim.uk/posts/how-to-use-hibernate-identifier-sequence-generators-properly#using-the-sequence-strategy
https://thoughts-on-java.org/hibernate-postgresql-5-things-need-know/

**Comment by molivasdat** [comment]
Hi @gkillough .  Is this still an issue in the latest stable version of liquibase?  As of this writing it's v3.8.9.

**Comment by gkillough** [comment]
I was using 3.8.0 at the time. I will see if this is fixed in 3.8.9.

**Comment by gkillough** [comment]
@molivasdat This is still a problem in v3.8.9. 

Test: 
1. I created a test table through liquibase with a BIGSERIAL column.
2. Connected to the postgres database and inspected the schema using `\dS test_table`.
3. Expected the default value of the column to look something like this: `nextval('test_table_test_column_seq'::regclass)`, but it was blank. 
4. No sequence existed.

**Comment by Trigve** [comment]
The 4.0 version is also affected.

**Comment by kristyldatical** [comment]
Hi @molivasdat & @kevin-at-datical  : I read up some more on this issue after @r2liquibase filed a similar issue under https://github.com/liquibase/liquibase/issues/1393. I also think (like some others are mentioning above) that the PR https://github.com/liquibase/liquibase/pull/1010/files does not actually fix this `type = smallserial/serial/bigserial` issue -- i.e. at least not by just returning an `autoIncrement = true` alone. If you look at the postgres docs via https://www.postgresql.org/docs/12/datatype-numeric.html, it mentions this : 
```
CREATE TABLE tablename (
    colname SERIAL
);
is equivalent to specifying:
CREATE SEQUENCE tablename_colname_seq AS integer;
CREATE TABLE tablename (
    colname integer NOT NULL DEFAULT nextval('tablename_colname_seq')
);
ALTER SEQUENCE tablename_colname_seq OWNED BY tablename.colname;
```
so I think we should be taking a closer look at the SQL we are currently generating for smallserial/serial/bigserial data types and address the discrepancy (which is really about the implied sequence it looks like?) if there is indeed one.

**Comment by Trigve** [comment]
Is there any news on this?

**Comment by Greenbones** [comment]
I ran into this issue on 3.7.0 just now and after upgrading to 3.10.3 it's gone.

So I think it's probably fixed, but wanted to note this in the meantime for anyone that's hitting it on 3.X.
