### ISSUE TITLE
How to disable dynamic substitution of parameters in a changelog?

### ISSUE THREAD

**Issue by uqix** [liquibase/liquibase#1023]
Because our sql contains string literals like '${someFreemarkerParam}'

## Environment
**Liquibase Version**:

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

**Operating System Type & Version**:

## Description
A clear and concise description of the issue being addressed.

* Describe the actual problematic behavior.
* Ensure private information is redacted.

## Steps To Reproduce
List the steps to reproduce the behavior.

* Please be precise and ensure private information is redacted
* Include things like
  * Files used - sql scripts, changelog file(s), property file(s), config files, POM Files
  * Exact commands used - CLI, maven, gradle, spring boot, servlet, etc.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-136) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
@uqix Thanks for writing this up.  Which version of liquibase were you using at the time?  I have updated the comments section with additional information needed.   At the current time, liquibase should not substitute ${param} if you have not set that as a substitution variable.

**Comment by molivasdat** [comment]
Hi @uqix Is this still an issue.  If so, can you please update the description section with the updates requested?  If not, I will close it because liquibase should not substitute if you have not set a substitution variable.
