### ISSUE TITLE
Rollback is broken

### ISSUE THREAD

**Issue by antonalechnovic** [liquibase/liquibase#1030]
**Description**
Rollback does not work, with tags or with count, doesn't respect rollback sql file. 

**To Reproduce**

```
    <changeSet id="5" author="ale">
        <tagDatabase tag="before_provisioning_1"/>
    </changeSet>

    <changeSet id="6" author="ale">
        <sqlFile path="add_two_columns_to_table_a_create_two_new_tables_add_foreign_key.sql" relativeToChangelogFile="true"/>

        <!-- this rollback is for reference only, liquibase rollback is broken , doesn't jump to previous changeset,
         doesn't undo changes  -->
        <rollback>
            <sqlFile path="some_rollback_script_which_works_against_db.sql" relativeToChangelogFile="true"/>
        </rollback>
    </changeSet>

```

    liquibase rollbackSQL before_provisioning_1  --changeLogFile liquibase.xml --url="jdbc:mysql://localhost:3306/credentials" --classpath="/home/ale/liquibase/src/java/mysql-connector-java-5.1.47.jar" --password=some --username=root 
    Liquibase Community 3.8.7 by Datical
    --  *********************************************************************
    --  Rollback to 'before_provisioning_1' Script
    --  *********************************************************************
    --  Change Log: liquibase.xml
    --  Ran at: 11/03/20 16:23
    --  Against: root@172.17.0.1@jdbc:mysql://localhost:3306/credentials
    --  Liquibase version: 3.8.7
    --  *********************************************************************
    
    --  Lock Database
    UPDATE credentials.DATABASECHANGELOGLOCK SET `LOCKED` = 1, LOCKEDBY = '172.17.0.1 (172.17.0.1)', LOCKGRANTED = '2020-03-11 16:23:18.432' WHERE ID = 1 AND `LOCKED` = 0;
    
    --  Release Database Lock
    UPDATE credentials.DATABASECHANGELOGLOCK SET `LOCKED` = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;
    As you can see the above is empty, it refuses to execute contents of mysql file.

**Comment by antonalechnovic** [comment]
exactly same with `rollbackCount`

**Comment by SteveDonie** [comment]
Thanks for the bug report! We do have extensive tests around rollback, so this is somewhat surprising. Quick question - had you previously run the `update` command to deploy all the changes to the database before running the rollback command? That is the one thing that comes to mind as a possible reason for this behavior.

**Comment by SteveDonie** [comment]
I just ran my own local test. I used the XML sample changelog that is installed when using the Liquibase installer. I added two changesets that were very similar to yours. I then ran `liquibase update` and checked the h2 database and saw that the changes had been deployed. I then ran `liquibase rollbackSQL before_provisioning_1` and got the expected SQL. I also ran `liquibase rollbackCountSQL 1` and got equivalent SQL. 

When Liquibase runs the rollback commands, it looks at the DATABASECHANGELOG for the database in question and will only roll back changes that have actually been deployed. I suspect that may be what you are seeing.

**Comment by antonalechnovic** [comment]
Hi Steve, for us the framework issues the command and I can see all the changeset in the changelog:

```
liquibase update --changeLogFile="db.changelog-master.xml" --url="jdbc:mysql://localhost:3306/credentials" --classpath="liquibase/src/java/mysql-connector-java-5.1.47.jar" --password=some --username=root 
Liquibase Community 3.8.7 by Datical
Errors:
  unexpected command parameters: [--changeLogFile=db.changelog-master.xml, --url=jdbc:mysql://localhost:3306/credentials, --classpath=liquibase/src/java/mysql-connector-java-5.1.47.jar, --password=rulezzz123, --username=root]
```


```
liquibase update
Liquibase Community 3.8.7 by Datical
Errors:
  The option --url is required.
  The option --changeLogFile is required
```

For cleanness of experiment I tried to run directly "update", but not sure how? This is tautology behavior of the command :-D. I used same parameters for rollback

**Comment by antonalechnovic** [comment]
(framework uses liquibase-core 3.6.2 , mysql db version is: 5.6.42-1.1.8)

**Comment by SteveDonie** [comment]
What I typically do when running from the command line is I create a file named `liquibase.properties` in the directory where I will be running the command, and in that file I put things like the changeLogFile, url, etc. This makes running commands much easier. This is described in more detail in the documentation at https://www.liquibase.org/documentation/config_properties.html

If you don't use a properties file, the correct format for the command line would be to have the parameters first, then the command. You have `liquibase <command> <global parameters>` but the command line expects `liquibase <global parameters> <command>`.

**Comment by antonalechnovic** [comment]
Managed to get it work with manual "update" , investigating Spring Boot.

**Comment by antonalechnovic** [comment]
found an article: https://forum.liquibase.org/topic/rollbacks-not-working-if-spring-starts-them-even-if-runintransaction-false

feels like simillar to what i experience

**Comment by antonalechnovic** [comment]
More info:

https://liquibase.jira.com/browse/CORE-3353?oldIssueView=true

this exactly same issue I have. I will try to manually change file path.

**Comment by antonalechnovic** [comment]
I can confirm that after removing prefix, it is all working as expected - but it is not satisfactory outcome, the only thing I don't understand is what the synergy between you guys and Pivotal? 

1. How the rollback flow should be working? 
2. There is something wrong with keeping core file and accessing it through file system?
3. How do you envision liquibase with microservices? Should the rollback action come from the application which execute changelog? 

I don't have answers to these myself, will dig further, but what surprises me **is that liquibase should crash dramatically in my face** if it can't find the file.

**Comment by Painyjames** [comment]
I don't know if this is the right place where to add a comment, but we've tried to rollback changes using liquibase and SpringBoot and only managed to keep the rollback SQL scripts on a file. It never rollback at all if the rollback file is not specified, and even with the file, there is no rollback, just a SQL file with the rollback SQL statements for you to run afterwards.

Now, we've checked and it seems that that's what it's intended as we can see on this line:
https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/integration/spring/SpringLiquibase.java#L269

Could someone confirm this?

**Comment by antonalechnovic** [comment]
> I don't know if this is the right place where to add a comment, but we've tried to rollback changes using liquibase and SpringBoot and only managed to keep the rollback SQL scripts on a file. It never rollback at all if the rollback file is not specified, and even with the file, there is no rollback, just a SQL file with the rollback SQL statements for you to run afterwards.
> 
> Now, we've checked and it seems that that's what it's intended as we can see on this line:
> https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/integration/spring/SpringLiquibase.java#L269
> 
> Could someone confirm this?

How do you rollback with springboot and liquibase?

I can confirm that I did succeed to rollback but I had to be in exact directory with CLI as from where Spring Boot starts (i.e. see issue I mentioned). 

What do you mean "it didn't rollback without file" you mean via xml syntax? or embedded rollback? With XML it is tricky as not every operation could be rolled back I think.

I think liquibase developers should seriously consider how their product integrates with Spring Boot and liase with devs. The way it is now is that liquibase is just a tracker of changes and db neutral language. In our use case rollback was the decider in favour of liquibase vs flyway , but as it doesn't integrate properly, I won't push for liquibase anymore.

**Comment by ro-rah** [comment]
Hey @antonalechnovic and others following this thread.  I believe pathing has been reworked to fix many of these SpringBoot/Liquibase issues since 4.0+, if you try doing an update and rollback with 4.0.0 it should work (note it won't work on older changesets already updated b/c the changelog will have the pre 4.0 pathing).

Could you try this with [liquibase](https://www.liquibase.org/download) 4.0.0? (scroll down to the bottom)

**Comment by molivasdat** [comment]
Hi @antonalechnovic As @ro-rah stated.  Because of the issues with the paths of how springboot, cli and others created the path in the changelogtable, we have fixed most if not all of those path issues in 4.x.  Can you try this with Liquibase 4.x?

**Comment by kataggart** [comment]
@antonalechnovic Thanks again for posting your issue. As this has been inactive for a while, I am going to close the issue. Please don't hesitate to open a new issue if you continue to face this issue. Thanks!
