### ISSUE TITLE
Liquibase schema XSD 3.5 not working since the last hour

### ISSUE THREAD

**Issue by federico-piazza** [liquibase/liquibase#1038]
Hi guys, 

We are using liquibase and suddenly our ci/cd process stopped working within the last hour.

Checking at the logs, the error displayed is:

```
Caused by: liquibase.exception.SetupException: Error parsing line 2 column 35 of liquibase/v-1.10/2017-07-26--01-metadata-tables-legacy.xml: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.
....
SEVERE 3/16/20 4:52 PM: liquibase: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.
liquibase.exception.ChangeLogParseException: Error parsing line 2 column 35 of liquibase/changelog-test.xml: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.
```

All the files we have older than 2 years that are using below schemas are failing:

```xml
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd">
```
However, when we change `dbchangelog-3.5.xsd` to `dbchangelog-3.1.xsd` in above files everything works fine.

This looks like something has changed on your end for the xsd 3.5.

We could change all our migration scripts to use 3.1 schemas, but this will make us to re-update all hashes in our db manually.

Can you please provide any feedback?

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-149) by [Unito](https://www.unito.io/learn-more)

**Comment by davidjgoss** [comment]
Also seeing this with `http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.3.xsd` - the server is 301 redirecting that to the https version of the same URL, which is good, but the sax parser used inside of Liquibase doesn't seem to be able to handle a redirect.

 @federico-piazza does changing the schema locations in your files to the https version work?

**Comment by nvoxland** [comment]
We switched the site to be https only, forgetting the xsd requests won't follow the redirects.

However, the xsd lookup code should generally not need network access to work. There were some older versions that did, but they should not recently.

What versions were you running?

**Comment by nvoxland** [comment]
We did disable the https-only setting, so everything should work now

**Comment by federico-piazza** [comment]
@nvoxland our project seems to have in some files 3.1 and also 3.5 (as stated in my first message). It seems that when the switch to https only happened all the 3.5 XSD have failed.

The version of liquibase this project has is:

```
"org.liquibase:liquibase-gradle-plugin:1.2.4",
```

Now that you disabled the https-only setting everything is working again.

I have tested using https in every liquibase url but I got this error:

```
> liquibase.exception.LiquibaseException: Unexpected error running Liquibase: TargetNamespace.1: Expecting namespace 'https://www.liquibase.org/xml/ns/dbchangelog', but the target namespace of the schema document is 'http://www.liquibase.org/xml/ns/dbchangelog'.
```

Not sure if I should close this ticket, but all is good now.

Thanks for the quick turnaround.

**Comment by nvoxland** [comment]
The xsd version should matter less than the liquibase version. Looks like the underlying liquibase version is 3.4.2. Thanks for letting me know.

**Comment by molivasdat** [comment]
We have resolved this issue.  Closing as fixed
