### ISSUE TITLE
addNotNullConstraint causes "Data too long" Exception for BIT(1) fields

### ISSUE THREAD

**Issue by philhinco** [liquibase/liquibase#1054]
**Description**
We forgot to add a not null constraint to a column that was added to a table in a previous changeset, so now we wanted to add that not-null constraint to said new column.
The data type of that column is BIT(1) (so basically a boolean).

Sidenote: We are using MySQL/MariaDB.

I used the following XML-changeset to add the constraint:

```
<changeSet id="XXX" author="XXX">
    <addNotNullConstraint tableName="XX" columnName="XX" defaultNullValue="1" columnDataType="BIT(1)"/>
</changeSet>
```

When we run the changeset, the following Exception is thrown:

```
Error setting up or running Liquibase: Migration failed for change set xxx.xml::xxxx::XXX:
[ERROR]      Reason: liquibase.exception.DatabaseException: (conn=28) Data too long for column 
```

I saw that a similar issue was already brought up in 2010 (!) on the Liquibase JIRA board [here](https://liquibase.jira.com/browse/CORE-721), but was apparently never fixed.

**To Reproduce**
Use a changeset like this:

```
<addColumn tableName="xxx">
   <column name="col_name" type="BIT(1)" defaultValue="1"></column>
</addColumn> 
```

After that, add a second changeset like this:

```
<changeSet id="XXX" author="XXX">
    <addNotNullConstraint tableName="xxx" columnName="col_name" defaultNullValue="1" columnDataType="BIT(1)"/>
</changeSet>
```

Then run the liquibase changeset and the mentioned Exception should be thrown.
Please specify the exact commands used, from CLI, from maven, etc.

Describe the actual problematic behavior. Include console outout if relevant, log files if available. Ensure private information is redacted.

**Expected behavior**
I expect the changeset to run through without issues, adding the not null constraint to the specified table and setting all NULL entries to the specified default in `defaultNullValue`.
As mentioned in the comment on the linked JIRA post above, adding attributes like `defaultNullValueBoolean` would also be helpful.

**Screenshots**
None

**Additional context**
None

**Comment by SteveDonie** [comment]
Thanks for the bug report! We are reviewing all the open issues and will try to get this addressed as soon as possible.

**Comment by RG9** [comment]
Hi, 
I have the same problem with `addNotNullConstraint` on MySQL:
```xml
<addNotNullConstraint tableName="FOO" columnName="BAR" columnDataType="BOOLEAN" defaultNullValue="false"/>
```
generates SQL:
```sql
 UPDATE FOO SET BAR = 'false' WHERE BAR IS NULL
 ```
 But `false` shouldn't be quoted with `'`.
