### ISSUE TITLE
addNotNullConstraint / dropNotNullConstraint not supported on Firebird

### ISSUE THREAD

**Issue by Wallaby1999** [liquibase/liquibase#1066]
**Description**
The change addNotNullConstraint and dropNotNullConstraint are not available for Firebird databases.

**To Reproduce**
Add the commands to a change set and run it against a Firebird database. As a result there will be the following error messages:
_addNotNullConstraint is not supported on firebird_
_dropNotNullConstraint is not supported on firebird_

**Expected behavior**
The commands should be available for Firebird databases as well.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-177) by [Unito](https://www.unito.io/learn-more)

**Comment by Wallaby1999** [comment]
Just added a pull request with what I think will implement these commands for Firebird.

But as the resulting SQL is different for Firebird 3 databases than for the smaller versions it might be a good idea to separate the tests. As I do not know what is the best way to achieve this, I did not make any proposal. But I am happy to help when needed and when I get some advice how to do it

**Comment by SteveDonie** [comment]
Thanks so much for the issue report and the pull request! We will take a look at the PR and make some testing suggestions over there.
