### ISSUE TITLE
constraint_name for PostgreSQL is not quoted

### ISSUE THREAD

**Issue by kryzha4ok** [liquibase/liquibase#1068]
https://github.com/liquibase/liquibase/blob/1cec0a95810ba881707e97cc989956511a7712e8/liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropPrimaryKeyGenerator.java#L64

I use PostgreSQL 12.2, liquibase 3.8.8 and I have a changeset with objectQuotingStrategy="QUOTE_ALL_OBJECTS" and `<dropPrimaryKey tableName="CardToken"/>` command (without constraintName). But when I run liquibase update, I get the following error: 

`Error: ERROR: constraint "cardtoken_pkey" of relation "CardToken" does not exist
  Where: SQL statement "alter table "public"."CardToken" drop constraint CARDTOKEN_PKEY"
PL/pgSQL function inline_code_block line 7 at EXECUTE [Failed SQL: (0) DO $$ DECLARE constraint_name varchar;
BEGIN
  SELECT tc.CONSTRAINT_NAME into strict constraint_name
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
    WHERE CONSTRAINT_TYPE = 'PRIMARY KEY'
      AND TABLE_NAME = 'CardToken' AND TABLE_SCHEMA = 'public';
    EXECUTE 'alter table "public"."CardToken" drop constraint ' || constraint_name;
END $$;]
;]`

Constraint CARDTOKEN_PKEY really exists. But in the code, it is substituted without quotes. I think this is the problem.

**Comment by SteveDonie** [comment]
Thanks for submitting this issue!

**Comment by molivasdat** [comment]
@kryzha4ok Thanks again for submitting this issue. We are taking a look at the issues and putting plans in place to solve them.

**Comment by AlexanderSashchenko** [comment]
Checked this issue with newer liquibase verision (4.3.1) against Postgresql 12 and 13 versions. Seems like the issue is not actual anymore. No error was thrown.
Example of the changeset:
<changeSet author="as" id="1" objectQuotingStrategy="QUOTE_ALL_OBJECTS">
        <dropPrimaryKey tableName="table_name"/>
</changeSet>

**Comment by adrian-sensioty** [comment]
Hi there,

I ran into the same problem when I upgraded to liquibase 4.4.3 from 3.10.2. 
I use postgresql 9.5 (but also tried with 12.8). 

My changeset looks like this:
`<changeSet id="8" author="authorX">
        <delete schemaName="${schemaName}" tableName="TABLE_X"/>

        <dropPrimaryKey schemaName="${schemaName}" tableName="TABLE_X"/>
        <dropColumn schemaName="${schemaName}" tableName="TABLE_X" columnName="ID"/>
        <dropColumn schemaName="${schemaName}" tableName="TABLE_X" columnName="CONTENT"/>
        <addPrimaryKey schemaName="${schemaName}"
                       columnNames="NAME"
                       constraintName="PK_TABLE_X"
                       tableName="TABLE_X"/>
        <addColumn schemaName="${schemaName}" tableName="TABLE_X">
            <column name="ETAG" type="NVARCHAR(255)">
                <constraints nullable="false"/>
            </column>
        </addColumn>
        <addColumn schemaName="${schemaName}" tableName="TABLE_X">
            <column name="BODY" type="VARBINARY(max)">
                <constraints nullable="false"/>
            </column>
        </addColumn>
    </changeSet>`

I tried to add `objectQuotingStrategy="QUOTE_ALL_OBJECTS"` but then the changeset already failed at the first <delete> statement.
