### ISSUE TITLE
Separate Firebird v3 from earlier Firebird versions

### ISSUE THREAD

**Issue by Wallaby1999** [liquibase/liquibase#1077]
**Description**
Firebird 3 has some differences with respect to the created SQL statements. Currently there is no way to distinguish versions prio v3 from v3 and onwards

**Expected behavior**
The Firebird 3 behaviour should get explictily available by using its own short name "firebird3" and by creating the necessary test cases.

**Additional context**
The Firebird3Database class should be extended and all test cases should be implemented for it as well.

**Comment by ro-rah** [comment]
Added Risk Medium Tag due the volume of code changes but Firebird v3 changes look pretty well isolated.  Nice use of integration tests!

**Comment by lbadam** [comment]
Closing this as this is not work we plan to implement. For anyone wanting to use Firebird with Liquibase, please [read our documentation](https://contribute.liquibase.com/extensions-integrations/directory/database-tutorials/firebird/).
