### ISSUE TITLE
dropAll fails on a non-lower case Function Object names

### ISSUE THREAD

**Issue by szandany** [liquibase/liquibase#1114]
## Environment
**Liquibase Version**:
4.0.0-beta1
**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
CLI
**Database Vendor & Version**:
PostgreSQL
**Operating System Type & Version**:
Windows, Linux

## Description
The Liquibase dropAll command fails on a non-lower case Function Object names

## Steps To Reproduce
1. Create a function that is not completely lower case in a PostgreSQL database (function name is camelCase).
`CREATE OR REPLACE FUNCTION public."plusOne"(val integer) RETURNS integer LANGUAGE plpgsqlAS $function$BEGINRETURN val + 1;END; $function$`
1. Run: `liquibase dropAll`

## Actual Behavior
Below the following error get produced:

`Unexpected error running Liquibase: ERROR: could not find a function named "public.plusone" [Failed SQL: (0) DROP FUNCTION "public".plusOne]For more information, please use the --logLevel flag`

## Expected/Desired Behavior
Liquibase should drop all objects in the database.

## Acceptance Criteria
1. Liquibase should be able to handle function and other stored logic objects in a case-sensitive manner.
1. While this ticket is written for dropAll, we should test all liquibase commands which touch functions and other stored logic objects

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-226) by [Unito](https://www.unito.io)
┆Fix Versions: Liquibase 4.x

**Comment by mariochampion** [comment]
hey @szandany -- do you think this issue https://github.com/liquibase/liquibase/pull/1001 is close enough to your issue to call them dupes (fixing one fixes the other) or do you want to keep this issue alive until after 1001 is merged and then check if this one remains a problem?

**Comment by Raibaz** [comment]
I really think this is due to the same issue being fixed by #1001.
