### ISSUE TITLE
context property in maven plugin does not tolerate spaces

### ISSUE THREAD

**Issue by gvwolf3d** [liquibase/liquibase#1121]
Sample:

`
<changeSet id="43765-1" author="gvw" context="(alvara or stest) and default">
`

works fine, but

`
<changeSet id="43765-1" author="gvw" context="( alvara or stest ) and default">
`

doesn't.

**Comment by molivasdat** [comment]
@gvwolf3d Thanks for adding this issue.  What version of Liquibase were you using at the time?

**Comment by gvwolf3d** [comment]
We are using version 3.5.3 of liquibase-maven-plugin

**Comment by FBurguer** [comment]
Looks like the issue has been fixed for the lastes version of liquibase-maven-plugin. If the issue continues to happen to you, please reach out and we will have a second look. Thanks for submitting this issue!
