### ISSUE TITLE
[PostgreSQL] Sequences are not being created correctly

### ISSUE THREAD

**Issue by r2liquibase** [liquibase/liquibase#1136]
## Environment
**Liquibase Version**: 3.8.9

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: none

**Database Vendor & Version**: PostgreSQL 12

**Operating System Type & Version**: Docker

## Description
It _appears_ that sequences are being created twice with the second having a 1 appeneded.

## Steps To Reproduce
Create a sequence using the Sakila schema.

```
CREATE SEQUENCE actor_actor_id_seq
    INCREMENT BY 1
    NO MAXVALUE
    NO MINVALUE
    CACHE 1;
```

generatechangelog will create the following changelog

```
    <changeSet author="r2 (generated)" id="1588785396440-12">
        <createSequence cacheSize="1" cycle="false" dataType="bigint" incrementBy="1" maxValue="9223372036854775807" minValue="1" sequenceName="actor_actor_id_seq" startValue="1"/>
    </changeSet>
```

## Actual Behavior
I have two sequences now: actor_actor_id_seq and actor_actor_id_seq1. I have no idea how actor_actor_id_seq1 was created.

## Expected/Desired Behavior
actor_actor_id_seq1 is not created

## Additional Notes
Intrestingly, this does not happen with address_address_id_seq or category_category_id_seq in the Sakila schema.

**Comment by molivasdat** [comment]
Thanks @r2datical. We will take a look at this one for processing into our queue.  Thanks again for the detailed recreation steps.

**Comment by jonathanmza** [comment]
I have the exact same problem with a Springboot application using Liquibase (latest) and Postgresql

**Comment by ecarneiro01** [comment]
I added the three Sakila sequences mentioned in the description to the database and after running the `generateChangeLog` command I didn't see a new one being created. @jonathanmza if you are still experiencing something similar could you please create a new issue for us? Thanks.

If you are still are having issues with this please reach out to us again.
