### ISSUE TITLE
Informix datetime reading error

### ISSUE THREAD

**Issue by LeeKevinCode** [liquibase/liquibase#1144]
## Environment
**Liquibase Version**: 3.8.9 

**Liquibase Integration & Version**: maven

**Liquibase Extension(s) & Version**: 3.8.9

**Database Vendor & Version**: Informix

**Operating System Type & Version**: Linux

## Description
Liquibase try to read datetime from informix, it follows the formula https://www.ibm.com/support/knowledgecenter/SSGU8G_11.50.0/com.ibm.sqlr.doc/ids_sqr_027.htm
However the formula is not applied to Informix.

Getting the following error:
`Caused by: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.DatabaseException: Encountered unknown firstQualifier code (1) for column 'informix.databasechangelog.dateexecuted', basic date type 'DATETIME', while trying to decipher information encoded in the column length (25)`

dateexecuted is YEAR TO FRACTION(5)

## Steps To Reproduce
Create a simple liquibase app and build it with informix.
Run the app with correct changelogs, the app runs without error
Rerun the app with other changelogs. The app runs with the error above

## Actual Behavior
After first run, the liquibase app with informix will have error

## Expected/Desired Behavior
Should not have any error

## Additional Context
The error is here
https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGeneratorInformix.java#L65

**Comment by LeeKevinCode** [comment]
I fixed it with the following code
```
package liquibase.snapshot.jvm;

import liquibase.database.Database;
import liquibase.database.core.InformixDatabase;
import liquibase.exception.DatabaseException;
import liquibase.snapshot.CachedRow;
import liquibase.snapshot.SnapshotGenerator;
import liquibase.structure.DatabaseObject;
import liquibase.structure.core.Column;
import liquibase.structure.core.DataType;

import java.util.HashMap;
import java.util.Map;

/**
 * Informix-specific parts of ColumnSnapshotGenerator to account for various quirks in IBM Informix.
 */
public class ColumnSnapshotGeneratorInformix extends ColumnSnapshotGenerator {

    private static final Map<Integer, String> qualifiers = new HashMap<>();

    static {
		qualifiers.put(8, "HOUR TO SECOND");
		qualifiers.put(5, "HOUR TO MINUTE");
		qualifiers.put(4, "YEAR TO YEAR");
		qualifiers.put(10, "YEAR TO DAY");
		qualifiers.put(16, "YEAR TO MINUTE");
		qualifiers.put(19, "YEAR TO SECOND");
		qualifiers.put(23, "YEAR TO FRACTION(3)");
		qualifiers.put(25, "YEAR TO FRACTION(5)");
    }


    @Override
    public int getPriority(Class<? extends DatabaseObject> objectType, Database database) {
        if (database instanceof InformixDatabase)
            return PRIORITY_DATABASE;
        else
            return PRIORITY_NONE; // Other DB? Let the generic handler do it.
    }

    @Override
    public Class<? extends SnapshotGenerator>[] replaces() {
        return new Class[]{ColumnSnapshotGenerator.class};
    }

    @Override
    protected DataType readDataType(CachedRow columnMetadataResultSet, Column column, Database database) throws DatabaseException {
        // For an explanation of the information encoded in the column length, please see
        // https://www.ibm.com/support/knowledgecenter/SSGU8G_11.50.0/com.ibm.sqlr.doc/ids_sqr_027.htm
        String typeName = columnMetadataResultSet.getString("TYPE_NAME").toUpperCase();
        if ("DATETIME".equals(typeName) || "INTERVAL".equals(typeName)) {
			int colLength = columnMetadataResultSet.getInt("COLUMN_SIZE");
			String type = "DATETIME".equals(typeName) ? "DATETIME" : "INTERVAL";
			String qualifier = qualifiers.get(colLength);

            DataType dataTypeMetaData = new DataType(type + " " + qualifier);
            dataTypeMetaData.setColumnSizeUnit(DataType.ColumnSizeUnit.BYTE);

            return dataTypeMetaData;
        } else {
            return super.readDataType(columnMetadataResultSet, column, database);
        }
    }

}

```

**Comment by molivasdat** [comment]
Thanks @LeeKevinCode for documenting this issue.  Can you please open a PR and  use the code you attached to fix it?

**Comment by kevin-atx** [comment]
@tati-qalified - Could you verify the issue? Once verified, could you submit the code in this issue as a PR and test again to see if it's fixed? I thought this would be an interesting exercise.
