### ISSUE TITLE
valueComputed does not work with valueBlobFile

### ISSUE THREAD

**Issue by mitasov-ra** [liquibase/liquibase#1149]
## Environment
**Liquibase Version**: 3.8.9

**Liquibase Integration & Version**: Gradle

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: PosgreSQL 10

**Operating System Type & Version**: Windows 10

## Description
If I put in `<insert>` change insert to table with two columns: `valueComputed` and `valueBlobFile`,
Liquibase always tries to insert `null` to `valueComputed` whatever I put in this attribute value.

## Steps To Reproduce
* Create table with columns of types `uuid` and `bytea`.
* Create migration with `<insert>` change.
* In that migration fill columns with `valueComputed="uuid_in(md5(random()::text || clock_timestamp()::text)::cstring)"` and `valueBlobFile="path/to/file"`

Changeset that reproduces the issue
`<changeSet author="mike" id="1">
		<createTable tableName="TABLE_WITH_CLOB">
			<column name="ID" type="java.sql.Types.BIGINT" autoIncrement="true">
				<constraints nullable="false" primaryKey="true" />
			</column>
			<column name="CONTENT" type="java.sql.Types.CLOB">
				<constraints nullable="false" />
			</column>
			<column name="UUIDCOL" type="uuid" />
		</createTable>
	</changeSet>
	<changeSet author="mike" id="2">
		<insert tableName="TABLE_WITH_CLOB">
			<column name="ID" valueNumeric="1" />
			<column name="CONTENT" valueClobFile="test-clob.txt" />
			<column name="UUIDCOL" valueComputed="uuid_in(md5(random()::text || clock_timestamp()::text)::cstring)" />
		</insert>
	</changeSet>
   <changeSet author="mike" id="3">
		<update tableName="TABLE_WITH_CLOB">
			<column name="UUIDCOL" valueComputed="uuid_in(md5(random()::text || clock_timestamp()::text)::cstring)" />
		</update>
	</changeSet>
`

## Actual Behavior
Liquibase migration crashes with message `null value in column "id" violates not-null constraint`

## Expected/Desired Behavior
Migration passes successfully.

## P.S.
I've found the related bug report [here](https://liquibase.jira.com/browse/CORE-3028)

**Comment by mitasov-ra** [comment]
#### UPD
If I change `valueComputed` to `value="6d4a4678-aaaa-aaaa-3b1e-d167ae063242"` (with some hardcoded uuid) migration works well.

**Comment by mitasov-ra** [comment]
I've just finished analysing source code.

In fact, `valueComputed` is not implemented at all.

[Here](https://github.com/liquibase/liquibase/blob/1345a12b57fc49ca13c0f90602798f320bcde523/liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java#L127) is the method, that applies values taken from migration to prepared SQL statement. As I can see, there's no `valueComputed`.

**Comment by mitasov-ra** [comment]
Seems like I won't get any feedback here 😕

**Comment by molivasdat** [comment]
Hi @mitasov-ra .  Thanks for taking the time to write up this issue.  And thanks for pointing to the section of code that might be the issue.  Do you have a fix that could be submitted as a pull request?

**Comment by mitasov-ra** [comment]
I don't really know, how it shold be done, but I suppose there must be another `if` clause for `valueComputed` attribute value.

I tried to find any use of `valueComputed` in source code, and failed in success.
So, I think I can't help you with exact solution without more deep analysis of sources.
Sorry, but I have not enough time for that.

**Comment by molivasdat** [comment]
Hi @mitasov-ra. Thanks for taking the time to look into this.  You are correct in that it is likely in the code you pointed at that needs to be updated.

**Comment by barkap** [comment]
I have found a similar (related?) bug when `valueBlobFile` and `valueDate="SYSDATE"` is used while inserting blob and current date in oracle db.

**Comment by MalloD12** [comment]
I cannot reproduce this issue on below environment: 

```
Liquibase Version: 4.15.0

Liquibase Integration & Version: Liquibase CLI

Database Vendor & Version: PosgreSQL 14

Operating System Type & Version: Mac OS 12.1 

```
With below changelog:

```
<changeSet author="daniel" id="1">
        <createTable tableName="TABLE_WITH_CLOB">
            <column name="ID" type="java.sql.Types.BIGINT" autoIncrement="true">
                <constraints nullable="false" primaryKey="true" />
            </column>
            <column name="CONTENT" type="java.sql.Types.CLOB">
                <constraints nullable="false" />
            </column>
            <column name="UUIDCOL" type="uuid" />
        </createTable>
    </changeSet>
    <changeSet author="daniel" id="2">
        <insert tableName="TABLE_WITH_CLOB">
            <column name="ID" valueNumeric="1" />
            <column name="CONTENT" valueClobFile="test-clob.txt" />
            <column name="UUIDCOL" valueComputed="uuid_in(md5(random()::text || clock_timestamp()::text)::cstring)" />
        </insert>
    </changeSet>
    <changeSet author="daniel" id="3">
        <update tableName="TABLE_WITH_CLOB">
            <column name="UUIDCOL" valueComputed="uuid_in(md5(random()::text || clock_timestamp()::text)::cstring)" />
        </update>
    </changeSet>
```

and cannot reproduce this issue. Changelog execution output is as displayed below:

```
Starting Liquibase at 14:04:45 (version 4.15.0 #4001 built at 2022-08-05 16:17+0000)
Liquibase Version: 4.15.0
Liquibase Community 4.15.0 by Liquibase
Running Changeset: issue1149.xml::1::daniel
Running Changeset: issue1149.xml::2::daniel
Running Changeset: issue1149.xml::3::daniel
Liquibase command 'update' was executed successfully.
```
