### ISSUE TITLE
liquibase returns false positive results for DiffChangeLog

### ISSUE THREAD

**Issue by shay-salomon** [liquibase/liquibase#1156]
## Environment
**Liquibase Version**: Community 3.8.9

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: PostgreSQL 9.6 and RDS Aurora PostgreSQL 11.4

**Operating System Type & Version**: RHL 64-bit

## Description
Hi, I am moving PostgreSQL 9.6 from on-prem to RDS Aurora PostgreSQL 11.4.
First step, used pg_dump to export database metadata (with over 700 schemas).
Next, wanted to verify I am not missing any constraints, objects and that source and database are aligned.
Using Liquibase with DiffChangeLog gives false positive results like:

1. Dropping constraints from target when they exists on both source and target with same syntax.
1. Create view when it exists with identical source code in source and target.

## Steps To Reproduce
Here is the Liquibase command for a single schema. I had to script over 700 for all schemas in the database:

c:\> liquibase.bat ^
--changeLogFile=d:\users\compare\changelog.postgresql.sql ^
--outputFile=d:\users\compare\Database_diff.txt ^
--classpath="D:\Program Files\liquibase\postgresql-42.2.12.jar" ^
--driver=org.postgresql.Driver ^
--url=jdbc:postgresql://<source_endpoint>:5432/<source_database> ^
--username=<source_username> ^
--password=<source_password> ^
--defaultSchemaName=<source_schema> ^
--includeSchema=true ^
DiffChangeLog ^
--referenceUrl=jdbc:postgresql://<target_endpoint>:5432/<target_databas> ^
--referenceUsername=<target_username> ^
--referencePassword=<target_password> ^
--referenceDefaultSchemaName=<target_schema>

## Actual Behavior
DiffChangeLog gives false positive results like:

1. Dropping constraints from target when they exists on source.
1. Create view when it exists with identical source code in source and target.

## Expected/Desired Behavior
n/a

## Screenshots (if appropriate)
n/a

## Additional Context
n/a

**Comment by molivasdat** [comment]
Thanks @shay-salomon for reporting this issue.  We are tagging and trying to process these as quickly as we can.  Are there certain types of constraints that are showing up in the false positives? Which types? Or is it all constraints? Same questions for the views?  Is it all views or just certain types and which types?
