### ISSUE TITLE
jre access problem in liquibase.bat

### ISSUE THREAD

**Issue by tomasotosolini** [liquibase/liquibase#1170]
## Environment

**Liquibase Version**: 3.9.0

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: not assigned

**Operating System Type & Version**: Windows Server 2012 R2 Std

## Description

liquibase.bat apparently does not handle correctly the new line in a set of instructions. 

## Steps To Reproduce

1. Download jre (now 1.8.0_251)
2. Install and set in env variables JAVA_HOME to its base path
3. Download zip containing liquibase 3.9.0 (not the windows installer)
4. Unpack it and set the env variables PATH its base path in order to find automatically the liquibase.bat
5. Open cmd and call liquibase.bat

## Actual Behavior
\liquibase-3.9.0\\jre was unexpected at this time.

## Expected/Desired Behavior
My team mate Cristian Clemente obtained the correct behaviour by modifying the following lines of liquibase.bat;

![2020-05-27 10_02_33-Window](https://user-images.githubusercontent.com/6538/82993736-5766fc80-a001-11ea-86d7-9e47a944464e.png)

like this

![2020-05-27 10_03_00-Window](https://user-images.githubusercontent.com/6538/82993750-5f26a100-a001-11ea-902d-ed6e90a17b99.png)

## Screenshots (if appropriate)
![liquibase](https://user-images.githubusercontent.com/6538/82992779-ea9f3280-9fff-11ea-87f5-bd20a5b0bba3.png)

## Additional Context

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-281) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
Hi @tomasotosolini Thanks for bringing this to our attention. Great job documenting and showing the fix. Can you create a pull request with your fix?

**Comment by molivasdat** [comment]
Hi @tomasotosolini Can you share all the environment variables you have set?  I cannot recreate this by the instructions in the reproduce section.

**Comment by molivasdat** [comment]
Closing as non - reproducible
