### ISSUE TITLE
 replaceIfExists createView Tag for MSSQL does not work

### ISSUE THREAD

**Issue by reza-sp** [liquibase/liquibase#1173]
## Environment
**Liquibase Version**: 3.8.8

**Liquibase Integration & Version**: run as jar File

**Liquibase Extension(s) & Version**: NO

**Database Vendor & Version**: Microsoft SQL Server 2016 (RTM-GDR) (KB4058560) - 13.0.1745.2 

**Operating System Type & Version**: Windows10

## Description
The following change set produced Exception because the generater sql syntax is invalid.
//it s working for db2 but doesn't work for MSSQL

## Steps To Reproduce
`<createView viewName="AC_COMFORT"
            fullDefinition="false"
            remarks="ZUGFeRD DB EDI interface"
            replaceIfExists="true">
            SELECT ACKEY,ACTYPE,ACREF,ACLFD,ACTACI,ACTACBA,ACTACRF
            FROM ZFINVOICAC WHERE ACTYPE = 0
 	</createView>`

## Expected/Desired Behavior
We expect that replaceIfExists="true" does not use the key word REPLACE, because it does not exist in MSSQL. Instead it should be two commands:

1. IF OBJECT_ID('AC_COMFORT ', 'V') IS NOT NULL  DROP VIEW AC_COMFORT ;
1. CREATE VIEW AC_COMFORT AS ...

Error: Incorrect syntax near the OR keyword. [Failed SQL: (156)] CREATE OR REPLACE VIEW AC_COMFORT

**Comment by molivasdat** [comment]
Hi @reza-sp Thanks for taking the time to write up this issue.  We will add it the list of MS SQL Server issues.

**Comment by FBurguer** [comment]
Looks like its already fixed for liquibase `4.16.1`
