### ISSUE TITLE
feat(cli): configuration though environment variable

### ISSUE THREAD

**Issue by davinkevin** [liquibase/liquibase#1179]
## Environment
**Liquibase Version**: 3.9.0, 4+

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: NONE

**Database Vendor & Version**: Everyone

**Operating System Type & Version**: Linux, Mac, Windows

## Description
We are using a lot liquibase, and we are using it through `initContainer` in Kuberentes world.
We would like to be able to run it in a minimal `container`, so we choose for security purpose `distroless/java` (https://github.com/GoogleContainerTools/distroless/blob/master/java/README.md).

The current important limitation is the configuration model which is only available through parameters or properties. 

Using `command line parameters` require at least a `shell`, which is not present inside `distroless/java` for security reason. 

Properties don't fit well too, because we have to have create a specific file for `liquibase` and we have to duplicate our parameters in two places. For example, URL will be injected in env var for the app and should be placed inside a property file too. This leads to duplication.

Liquibase should support environment variables, like `LIQUIBASE_URL=foo` to replace the `url` value. The format could be `LIQUIBASE_<PARAMETER>` with <PARAMETER> defined as `UPPER_SNAKE_CASE` of the `camelCase` cli parameter. 

## Expected/Desired Behavior
    export `LIQUIBASE_URL=jdbc:postgresql://foo:5432/db`
    export `LIQUIBASE_CHANGE_LOG=/database/changelog.xml`
    
    java -cp /lib/* -jar liquibase.jar## Additional ContextFYI, the https://github.com/flyway/flyway system already support it:  https://flywaydb.org/documentation/envvars

**Comment by molivasdat** [comment]
Hi @davinkevin Thanks for requesting this feature enhancement to Liquibase.  We will add it to our list of feature requests. According to twitter, you were going to create a small PR.  Did you already do that?

**Comment by davinkevin** [comment]
I just did, but this is just for information... 

I didn't have enough time and code is complicated at the CLI level, so I just try to do the job to see if this was possible. 

I think you'll be better at this than me 😊.

**Comment by filipelautert** [comment]
Hello @davinkevin - I think this is what you were looking for: https://www.liquibase.com/blog/liquibase-environment-variables-control-deployments . https://docs.liquibase.com/concepts/connections/liquibase-environment-variables.html 

It has been available since Liquibase 4.18.0 :+1: 

If it doesn't work please reopen the issue.
