### ISSUE TITLE
Confusing NOTICE file in liquibase-core JAR

### ISSUE THREAD

**Issue by tazle** [liquibase/liquibase#1191]
## Environment

**Liquibase Version**: 3.9.0

## Description

The liquibase-core JAR file (eg. at https://repo1.maven.org/maven2/org/liquibase/liquibase-core/3.9.0/liquibase-core-3.9.0.jar) contains META-INF/NOTICE which appears to include the Jackson NOTICE file contents. We could not find any artifacts in the JAR that would have been derived from Jackson.

Does the package contain something from Jackson, is it a case of the same NOTICe file being reused in the wider Liquibase project, or something else? 

## Steps To Reproduce

```
curl -O https://repo1.maven.org/maven2/org/liquibase/liquibase-core/3.9.0/liquibase-core-3.9.0.jar
unzip -c liquibase-core-3.9.0.jar META-INF/NOTICE
`` 

## Actual Behavior

Includes Jackson NOTICE.

## Expected/Desired Behavior

Did no expect to see Jackson NOTICE contents.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-302) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
Hi @tazle.  If you look under the META-INF/services directory there are 3 classes from jackson that are included in the jar file.

**Comment by molivasdat** [comment]
Issue #1051 describes the issues that some are having from including these files.

**Comment by molivasdat** [comment]
Hi @tazle Does this answer your question about expected results?

**Comment by tazle** [comment]
Hi, yes, thank you.
