### ISSUE TITLE
addAutoIncrement generated wrong sql

### ISSUE THREAD

**Issue by reza-sp** [liquibase/liquibase#1193]
## Environment
**Liquibase Version**:3.8.8

**Liquibase Integration & Version**: run as jar File

**Liquibase Extension(s) & Version**: NO

**Database Vendor & Version**:PostgreSQL 11.1 

**Operating System Type & Version**:Windows10

## Description
The following change set produced Exception because the generater sql syntax is invalid.
//it s working for db2 but doesn't work for POSTGRESQL

## Steps To Reproduce
```
<addAutoIncrement  tableName="MYTABEL"	columnName="ID" defaultOnNull="true" generationType="ALWAYS" incrementBy="1" startWith="1"/>
```

## Actual Behavior
CREATE SEQUENCE public.MYTABEL_id_seq AS null NO CACHE  NOORDER
liquibase.exception.MigrationFailedException: Migration failed for change set path-ignored::db-changelog-tables-1.0.0::Reza:
     Reason: liquibase.exception.DatabaseException: ERROR: syntax error at or near "null"

## Expected/Desired Behavior
ALTER TABLE MYTABEL DROP COLUMN ID;
ALTER TABLE MYTABEL
ADD COLUMN ID SERIAL PRIMARY KEY;
COMMENT ON COLUMN  MYTABEL.ID IS 'The entry ID';

**Comment by molivasdat** [comment]
Hi @reza-sp Thanks for writing up this issue.  We will add it to our list of issues to prioritize and update.

**Comment by MahatmaFatalError** [comment]
I stumbled over an issue that is probably tightly related.

```xml
<changeSet author="Me" id="switchToPKAutoIncrement">  
		<addAutoIncrement tableName="MyTable"
			columnName="id" 
			generationType="ALWAYS"
			incrementBy="1"  
			startWith="100"/>  
</changeSet>
```
The generated SQL, however, is missing the `startWith` and `generationType` information:
```SQL
CREATE SEQUENCE IF NOT EXISTS ltdegbdm.MyTable
ALTER SEQUENCE ltdegbdm.MyTable_id_seq OWNED BY ltdegbdm.MyTable.id
ALTER TABLE ltdegbdm.MyTable ALTER COLUMN id SET DEFAULT nextval('ltdegbdm.MyTable_id_seq')
```
I looked up the sequence DDL:
```SQL
CREATE SEQUENCE ltdegbdm.MyTable_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
```
which apparently uses default values. So the sequence starts at 1 and not at 100.

Liquibase 3.10.3, PostgreSQL 12

**Comment by molivasdat** [comment]
Hi @MahatmaFatalError Thanks for the additional context.  How were you able to get the generationType="ALWAYS" to get past the DTD errors?
This use case is still a problem but I couldn't recreate this with that attribute on the addAutoIncrement changetype
https://github.com/liquibase/liquibase/blob/54e3b592aa13221626d7ee704037345bfa9cabb6/liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.1.xsd#L551

**Comment by MahatmaFatalError** [comment]
in dbchangelog-3.8.xsd there is no dtd error, although I can't find `generationType` either 🤔

```xml
    <xsd:element name="addAutoIncrement">
        <xsd:complexType>
            <xsd:attributeGroup ref="changeAttributes"/>
            <xsd:attributeGroup ref="tableNameAttribute"/>
            <xsd:attribute name="columnName" type="xsd:string" use="required"/>
            <xsd:attribute name="columnDataType" type="xsd:string"/>
            <xsd:attribute name="startWith" type="xsd:long"/>
            <xsd:attribute name="incrementBy" type="xsd:long"/>
        </xsd:complexType>
    </xsd:element>
```

**Comment by nvoxland** [comment]
I think the original issue was resolved by a different fix at some point. There was a problem where we weren't handling the "sequence data type" setting correctly, and I think that's where the null came from. 

BUT, I'll keep this open for testing with #2588 because the generationType/defaultOnNull validation error is fixed there, and the example in the REPO steps use incrementBy/startWith on postgresql which were fixed by that PR also.

**Comment by kataggart** [comment]
@nvoxland moving this to code review since that is where the PR is living now. Thanks!
