### ISSUE TITLE
As a user, I would like to have a command to test my database connection with Liquibase

### ISSUE THREAD

**Issue by szandany** [liquibase/liquibase#1202]
## Description
Currently if there is a need to verify the connection to the database, it can only be done with commands that are associated with a changeLog like "status" and "generateChangeLog".

This command will conveniently allow the user to verify that the connection to the database is successful.

**For example:**
`liquibase test-connection`
**Console output:**

```java
Liquibase Pro 3.9.0 by Datical licensed to Liquibase Pro Customer until Tue Sep 22 19:00:00 CDT 2020
postgres@jdbc:postgresql://localhost:5432/MYDATABASE_DEV
Liquibase command 'test-connection' was executed successfully.
```

**Comment by filipelautert** [comment]
Now we have! https://docs.liquibase.com/commands/change-tracking/connect.html
