### ISSUE TITLE
LoadUpdateData with onlyUpdate=true is not working for Postgres database

### ISSUE THREAD

**Issue by ruslan-ryzhkov** [liquibase/liquibase#1205]
## Environment
**Liquibase Version**: 3.8.8

**Liquibase Integration & Version**: gradle (for a Spring Boot project)

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: PostgreSQL 9.6.12

**Operating System Type & Version**:  macOS Mojave 10.14.6

## Description
When creating a Liquibase changeset for a Postgres database, including the `loadUpdateData` change type with an attribute of `onlyUpdate=true` within the changeset will still insert any records that were not found. The `onlyUpdate=true` flag should prevent this behavior by only updating existing records.

## Steps To Reproduce
Simple steps to reproduce the problem would be to do the following:

1. Create a Postgres database with an empty table.
1. Create a Spring Boot project with Liquibase version 3.8.8.
1. Create a CSV file to import seed data into the table from step 1.
1. Create a changeset and use `loadUpdateData` with `onlyUpdate=true` to import the seed data from the CSV file into the Postgres table.

## Actual Behavior
Liquibase will insert **all** records from the CSV file into the table even though we specified `onlyUpdate=true`. If your CSV file did not include an `id` column, Liquibase will throw a database exception because id cannot be null.

## Expected/Desired Behavior
Liquibase should not insert any records into the table because we specified `onlyUpdate=true`.

## Additional Context
1. I did some research into this bug and the cause appears to be in the following file: https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorPostgres.java

    Specifically, the `generateSql` method is overriden for the Postgres case but there is no check for `onlyUpdate=true` inside the method. I would expect a conditional check around the `IF not found THEN` block of code to prevent the insert statement from being appended.1. The OS type should not matter for this issue since it's specific to Liquibase.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-316) by [Unito](https://www.unito.io)

**Comment by molivasdat** [comment]
Thanks @ruslan-ryzhkov for submitting such a detailed report.  Did you want to go ahead and submit a PR to add the conditional check just like in the super class?

**Comment by ruslan-ryzhkov** [comment]
Sure, @molivasdat . I opened https://github.com/liquibase/liquibase/pull/1213 to fix this issue.

**Comment by molivasdat** [comment]
Fixed in #1213
