### ISSUE TITLE
Liquibase do not fail when an already executed scripted is missing

### ISSUE THREAD

**Issue by fcappi** [liquibase/liquibase#1215]
## Environment

**Liquibase Version**: Community 3.8.7

**Liquibase Integration & Version**: CLI 3.8.7

**Database Vendor & Version**: MySQL 5.6 (AWS Managed)

**Operating System Type & Version**: Ubuntu 18.04

## Description

If someone deletes a script that was already executed in the DB, and keep its reference on the changelog, when the Liquibase update command is executed in the same DB, it will not fail.
The issue is that we will only find out that the file is missing when Liquibase is executed in another environment of my delivery pipeline (example: runs fine in STAGING environment but fails in PRODUCTION)

## Steps To Reproduce

- Create a changelog XML file and add a reference on it to an existing SQL script;
- Run the Liquibase update command in the DB;
- Delete the SQL script file that was executed, but keep its reference on the changelog XML file;
- Run the Liquibase update command again, in the same DB;

## Actual Behavior
Liquibase do not show any errors or warn messages about the missing file. So we can not identify the issue at this moment. You will see the error only when applying the same changelog to another DB.

## Expected/Desired Behavior
I would like to be informed by Liquibase that the file is missing, so I would fix that by either removing the script reference from changelog XML file or recreate it again.
This way I  would identify the issue earlier instead of only seeing it on the execution on the next environment.

## Additional Context
In my scenario,  I have a CD pipeline which applies the changes to UAT and then to PROD. during UAT, the script was accidentally removed after being executed. A few other executions of Liquibase update were done without errors. The Çiquibase update only failed when applied to PROD DB, finally reporting the missing file.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-326) by [Unito](https://www.unito.io/learn-more)

**Comment by r2liquibase** [comment]
We have no plans to fix this. Please include all necessary artifacts for your application, including Liquibase.
