### ISSUE TITLE
New ResourceAccessor not handling case insensitivity on filenames

### ISSUE THREAD

**Issue by nvoxland** [liquibase/liquibase#1218]
## Environment
**Liquibase Version**: Liquibase 4.0 beta2

**Liquibase Integration & Version**: any

**Liquibase Extension(s) & Version**: n/a

**Database Vendor & Version**: n/a

**Operating System Type & Version**: Windows

## Description
The new ResourceAccessor logic is not correctly handling files case insensitively on windows.
If you specify a changelog file with a case that doesn't match the actual file case, it fails with a ` Found 2 files that match your_file` error.

## Steps To Reproduce
List the steps to reproduce the behavior.

* Create a file named changeLogTest.xml
* Run `liquibase updateSql` with --changeLogFile=ChangeLogTest.xml

## Expected/Desired Behavior
Liquibase should recognize the file as being the "correct" changeLogTest.xml name

**Comment by nvoxland** [comment]
I'm not able to reproduce this anymore in the current 4.1.x branch. I'm thinking this got fixed earlier?

**Comment by FBurguer** [comment]
Looks like it got fixed.
