### ISSUE TITLE
liquibase.precondition.core.ViewExistsPrecondition@737bfc7f : String index out of range: -1 at [...]

### ISSUE THREAD

**Issue by martoncsukas** [liquibase/liquibase#1221]
## Environment
**Liquibase Version**: 3.6.2

**Liquibase Integration & Version**: maven

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: MySQL 5.7 Community

**Operating System Type & Version**: Windows Server 2012

## Description
This is similar to [CORE-3360](https://liquibase.jira.com/browse/CORE-3360) as I didn't find a resolution for that, and that project is closed.

`db_changelogs/changelog.xml : liquibase.precondition.core.ViewExistsPrecondition@737bfc7f : String index out of range: -1 at [...]`

After analysing the affected systems, we figured out that this relates to MySQLs automatic generation of the SECURITY DEFINER in all createView changeSets. In case the user trying to access the view is not covered by that specific definer, the above issue occurs. This can happen for example, if the database user was changed since a specific view required for the changeSet was created. In our case, the recreation of the views with a matching SECURITY DEFINER solved the issue.

/Comment by Christian Schwarz on [CORE-3360](https://liquibase.jira.com/browse/CORE-3360)/

**Comment by molivasdat** [comment]
Hi @martoncsukas.  Thanks for taking the time to write this up.  It does look similar to [CORE-3360](https://liquibase.jira.com/browse/CORE-3360).  We will add this to our queue of issues to fix.

**Comment by MalloD12** [comment]
I've tried to reproduced this issue on below environment without success:

```
Liquibase Version: 4.15.0

Liquibase Integration & Version: Maven (and CLI)

Liquibase Extension(s) & Version:

Database Vendor & Version: MySQL 5.7.39

Operating System Type & Version: Mac OS 12.1 
```

Deployed successfully below changesets through CLI and Maven and and changelog has beeen generated successfully:

```
<changeSet author="mallod" id="1">
    <createTable tableName="segments">
        <column name="name" type="varchar(255)">
            <constraints nullable="false" primaryKey="true" primaryKeyName="CONSTRAINT_1"/>
        </column>
    </createTable>
</changeSet>
<changeSet author="mallod" id="2">
    <insert tableName="segments">
        <column name="name" value="Daniel"/>
    </insert>
    <insert tableName="segments">
        <column name="name" value="Jhon"/>
    </insert>
    <insert tableName="segments">
        <column name="name" value="Test Daniel"/>
    </insert>
</changeSet>
<changeSet id="3" author="mallod">
    <createView replaceIfExists="true" viewName="TEST_DANIEL_VIEW">
        SELECT seg.name  FROM segments as seg
    </createView>
</changeSet>
<changeSet id="4" author="mallod">
    <comment>New Column Added</comment>
    <addColumn tableName="segments">
        <column name="country" type="varchar(2)"/>
    </addColumn>
</changeSet>
<changeSet id="5" author="mallod">
    <createView replaceIfExists="true" viewName="TEST_DANIEL_VIEW">
        SELECT seg.name, seg.country  FROM segments as seg
    </createView>
</changeSet>
```

Could you please try again with a 4.15.0 or at least 4.2.0 (or newer) version? If you can still reproduce this issue we would appreciate if you can share the steps to reproduce, as well as some log (if possible).

Thanks.
