### ISSUE TITLE
XMLChangeLogSerializer - missing filePath in ChangeSet

### ISSUE THREAD

**Issue by toastbot2** [liquibase/liquibase#1234]
## Environment
**Liquibase Version**: 3.10

## Description
```
 * Encapsulates a changeSet and all its associated changes.
 */
public class ChangeSet implements Conditional, ChangeLogChild {
...

    @Override
    public Set<String> getSerializableFields() {
        return new LinkedHashSet<>(
            Arrays.asList(
                "id", "author", "runAlways", "runOnChange", "failOnError", "context", "labels", "dbms",
                "objectQuotingStrategy", "comment", "preconditions", "changes", "rollback", "labels",
                "objectQuotingStrategy", "created"
            )
        );
    }
```

_objectQuotingStrategy_ is duplicate, but _filePath_ is missing.
Thats why _XMLChangeLogSerializer.createNode(LiquibaseSerializable object)_ ignores my _filePath_.
When using this XML file, Liquibase wants to make all changes again.

## QA Test Requirements
* None. Dev will cover fix with a unit test.

**Comment by molivasdat** [comment]
Hi @toastbot2 Thanks for writing up this issue.  Can you give a little more context in what you are trying to do?  Did you mean to attach an XML file when you said "When using this XML file..."?
How can I recreate the error that you are seeing?

**Comment by toastbot2** [comment]
Hi @molivasdat Thanks for your Feedback.


I combine different changelog files (for example [part1.txt](https://github.com/liquibase/liquibase/files/4830485/part1.txt) and [part2.txt](https://github.com/liquibase/liquibase/files/4830486/part2.txt)). Both files have a specific parameter “logicalFilePath”. In the aggregated changelog file, the individual changesets should get the “logicalFilePath” from the original changelog file as parameter “filePath” ([changelog.txt](https://github.com/liquibase/liquibase/files/4830488/changelog.txt)). When generating the XML file using the XMLChangeLogSerializer, this parameter is not set in the changesets, which means that the changesets can no longer be clearly identified.

Thanks for support!

[test class.txt](https://github.com/liquibase/liquibase/files/4830500/test.case.txt)

**Comment by nvoxland** [comment]
FilePath on the object stores the actual path, but that only exists in the in-memory object.

For XML, it's logicalFilePath that can be used to override what liquibase considers the path of the changeSet to be. 

We are missing logicalFilePath from the serializableFields too, but it should be that that is output to xml, not filePath.

**Comment by toastbot2** [comment]
Hi! Is there any news?

**Comment by nvoxland** [comment]
I just finished reviewing the associated PR and made some fixes to it. It is getting queued up for likely the 4.4.1 release.
