### ISSUE TITLE
generateChangeLog exports computed columns as normal columns

### ISSUE THREAD

**Issue by vladonemo** [liquibase/liquibase#1255]
## Environment
**Liquibase Version**: 3.10.1

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: none

**Database Vendor & Version**: Azure Sql Database

**Operating System Type & Version**: Windows

## Description
A table contains computed column. After running generateChangeLog command, the changeSet contains createTable elements with standard columns, no valueComputed attributes

## Steps To Reproduce
The minimum SQL to create MSSQL table:

```sql
CREATE TABLE [dbo].[SAMPLE_TABLE](
	[STANDARD_COLUMN] [nchar](10) NULL,
	[COMPUTED_COLUMN]  AS ([STANDARD_COLUMN])
) ON [PRIMARY]
GO
```

## Actual Behavior
The generated changelog is as follows:

```xml
  <changeSet author="(migrated)" id="1594155682424-80">
    <createTable tableName="SAMPLE_TABLE">
      <column name="STANDARD_COLUMN" type="nchar(10)"/>
      <column name="COMPUTED_COLUMN" type="nchar(10)"/>
    </createTable>
  </changeSet>
```

## Expected/Desired Behavior
The generated changelog should be something like:

```xml
  <changeSet author="(migrated)" id="1594155682424-80">
    <createTable tableName="SAMPLE_TABLE">
      <column name="STANDARD_COLUMN" type="nchar(10)"/>
      <column name="COMPUTED_COLUMN" type="COMPUTED" valueComputed="[STANDARD_COLUMN]"/>
    </createTable>
  </changeSet>
```

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-366) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 3.10.3

**Comment by molivasdat** [comment]
Hi @vladonemo Thanks for writing up this issue.  We will add it to the list of issues to research and see what can be done to fix this.
