### ISSUE TITLE
Index’s columns don’t get a snapshotId when one of them is marked as DESC

### ISSUE THREAD

**Issue by deci260** [liquibase/liquibase#1260]
#Environment
Java version: 11

**Liquibase Version**:
3.10.1

**Liquibase Integration & Version**: 
Spring liquibase version 3.10.1

**Database Vendor & Version**:
Postgresql 11

**Operating System Type & Version**:
Windows 10

## Description
Index's columns are left with a null snapshotId when the first one of them has an ordering attribute.

This behaviour is caused by the method `private void includeNestedObjects(DatabaseObject object)` in the `DatabaseSnapshot` class.

There are a couple of `if` statements that check if the current object is an Index, if the current field is `columns` and if the first one of those columns has an order. If these conditions match the `columns` field is skipped before the `private Object replaceObject(Object fieldValue)` method gets called, leaving the columns without a snapshotId.

Here's the code that does this:

```java
if ("columns".equals(field) && ((object.getClass() == PrimaryKey.class) || (object.getClass() == Index
    .class) || (object.getClass() == UniqueConstraint.class))) {
    if ((fieldValue != null) && !((Collection) fieldValue).isEmpty()) {
        final Column column = (Column) ((Collection) fieldValue).iterator().next();
        String columnName = column.getName();
        if (BooleanUtils.isTrue(column.getDescending()) || columnName.endsWith(" ASC") || columnName.endsWith(" DESC") || columnName.endsWith(" RANDOM")) {
            continue;
        }
    }
}
```

The lack of a snapshotId causes an `UnexpectedLiquibaseException` with the message `Found a null snapshotId for column <column>` while serializing the snapshot.

## Steps To Reproduce
To reproduce the null snapshot ID using a Postgres database, please follow these steps:

* Intall Liquibase 3.10.1
* [https://github.com/liquibase/liquibase/releases/tag/v3.10.1](https://github.com/liquibase/liquibase/releases/tag/v3.10.1|smart-link) 
* Create a table with two columns on the database.
* ```
CREATE TABLE IF NOT EXISTS payment_cards
(
   id  numeric(4)   NOT NULL,
   id2 numeric(4)   NOT NULL
);
```


* Create a unique, multi-column index for the table `payment_cards`
* `CREATE UNIQUE INDEX idx_v2 ON payment_cards(id DESC, id2);`
* Execute a Liquibase snapshot operation.
* `liquibase --logLevel=FINE --logFile=logout-LB373.txt --outputFile=snap.json snapshot --snapshotFormat JSON`

**Expected Results**

* The JSON snapshot operation completes without error.

**Actual Results**

* The JSON snapshot operation fails with the message `Found a null snapshotId for column goku.public.payment_cards.id2`
* The stack trace thrown (seen in the output file `logout-LB373.txt` is:
* ```
17:04:14.651 ERROR [liquibase.integration.commandline.Main]: Unexpected error running Liquibase: Found a null snapshotId for column goku.public.payment_cards.id2
17:04:14.651 ERROR [liquibase.integration.commandline.Main]: For more information, please use the --logLevel flag
17:04:14.652 ERROR [liquibase.integration.commandline.Main]: Unexpected error running Liquibase: Found a null snapshotId for column goku.public.payment_cards.id2
liquibase.exception.UnexpectedLiquibaseException: Found a null snapshotId for column goku.public.payment_cards.id2
	at liquibase.serializer.core.yaml.YamlSnapshotSerializer.toMap(YamlSnapshotSerializer.java:77)
	at liquibase.serializer.core.yaml.YamlSerializer.toMap(YamlSerializer.java:112)
	at liquibase.serializer.core.yaml.YamlSnapshotSerializer.toMap(YamlSnapshotSerializer.java:82)
	at liquibase.serializer.core.yaml.YamlSerializer.toMap(YamlSerializer.java:134)
	at liquibase.serializer.core.yaml.YamlSnapshotSerializer.toMap(YamlSnapshotSerializer.java:96)
	at liquibase.serializer.core.yaml.YamlSerializer.serialize(YamlSerializer.java:74)
	at liquibase.command.core.SnapshotCommand$SnapshotCommandResult.print(SnapshotCommand.java:148)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1460)
	at liquibase.integration.commandline.Main.run(Main.java:300)
	at liquibase.integration.commandline.Main.main(Main.java:159)
```

The bug reproduces in Liquibase 4.5.0 (has not been fixed between 3.10.1 and latest).

## Test Requirements (Liquibase Internal QA)
**Manual Test using CLI**

For this test, use the SQL provided above to configure the Postgres database.

* Verify the snapshot operation does not return a null snapshot ID for a multi-column, sorted index.
  * There is no error.
  * The snapshot file `snap.json` is produced
  * The snapshot file `snap.json` is not malformed (contains no #null nodes).

**Automated Test**

* TBD. If development has written a unit or integration test, no new functional tests are required.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-373) by [Unito](https://www.unito.io)

**Comment by molivasdat** [comment]
Hi @deci260. Thanks for opening this issue.  Since you found the code that does this, do you want to create a PR that fixes it?

**Comment by deci260** [comment]
Hi @molivasdat.
> Since you found the code that does this, do you want to create a PR that fixes it?

I don't really understand the logic behind that if statement, my guess is that the intention was to leave without a snapshotId only the columns with an ordering attribute and not every column of the index, but I may be wrong.

If you could confirm my guess I'll gladly open a PR that fixes this.

**Comment by molivasdat** [comment]
Hi @deci260 .  I'll check with development and get back to you.

**Comment by nvoxland** [comment]
The job of `includeNestedObjects` is to find the objects that are part of the object being snapshotted and make sure they are snapshotted as well. Like if you are snapshotting an index, we also make sure the columns are snapshotted as well so we know about them. 

What that "ignore if it's desc" logic is trying to handle, is that if you have an index defined on a "column" of `id desc`, it's not really a column called "id desc", it's just "id" and the index has more info. 

The problem trying to be fixed was if you create an index like: 

`CREATE UNIQUE NONCLUSTERED INDEX idx_v2OnSchema1 ON Schema1.test_viewOnSchema1(id DESC)` 

then the sql from a generated changeset looks like this:

`CREATE UNIQUE NONCLUSTERED INDEX idx_v2OnSchema1 ON Schema1.test_viewOnSchema1(id)`

without the desc.

The root problem is that we need to better separate columns from computed/extra information in index definitions in our snapshot model. We have a general overhaul of the snapshot process on our roadmap, but it will be a large job so we're trying to work around what we have for right now.

If you wanted to take a PR to fixing up the case you are seeing, that would be great. But, make sure that the flow through generateChangeLog I listed above still works.

**Comment by mariochampion** [comment]
hey @deci260 -- Do you think you might be able to provide a PR for your issue with the extra info provided by @nvoxland? As he mentions, it is likely this wont make it to StatusActive until late Q3 or Q4, but if you have some code to provide, that would certainly be welcome. Thanks and just let me know when you can.

**Comment by deci260** [comment]
> The job of `includeNestedObjects` is to find the objects that are part of the object being snapshotted and make sure they are snapshotted as well. Like if you are snapshotting an index, we also make sure the columns are snapshotted as well so we know about them.
> 
> What that "ignore if it's desc" logic is trying to handle, is that if you have an index defined on a "column" of `id desc`, it's not really a column called "id desc", it's just "id" and the index has more info.
> 
> The problem trying to be fixed was if you create an index like:
> 
> `CREATE UNIQUE NONCLUSTERED INDEX idx_v2OnSchema1 ON Schema1.test_viewOnSchema1(id DESC)`
> 
> then the sql from a generated changeset looks like this:
> 
> `CREATE UNIQUE NONCLUSTERED INDEX idx_v2OnSchema1 ON Schema1.test_viewOnSchema1(id)`
> 
> without the desc.
> 
> The root problem is that we need to better separate columns from computed/extra information in index definitions in our snapshot model. We have a general overhaul of the snapshot process on our roadmap, but it will be a large job so we're trying to work around what we have for right now.
> 
> If you wanted to take a PR to fixing up the case you are seeing, that would be great. But, make sure that the flow through generateChangeLog I listed above still works.

Thanks for your explanation! 

> hey @deci260 -- Do you think you might be able to provide a PR for your issue with the extra info provided by @nvoxland? As he mentions, it is likely this wont make it to StatusActive until late Q3 or Q4, but if you have some code to provide, that would certainly be welcome. Thanks and just let me know when you can.

Hello @mariochampion.
Yes, I'll gladly open a PR as soon as I have some time. Right now I'm a bit busy but I'll certainly work on it!
