### ISSUE TITLE
liquibase diff Informix db

### ISSUE THREAD

**Issue by arozehnal** [liquibase/liquibase#1264]
## Environment
 IBM Java 1.8

**Liquibase Version**: liquibase-3.10.1

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
CLI CE

## **Liquibase Extension(s) & Version**: 
**Database Vendor & Version**:
 Informix Db v.11.7

**Operating System Type & Version**:
AIX 7.1,

## Description
A clear and concise description of the issue being addressed.

* Describe the actual problematic behavior.
* Ensure private information is redacted.
liquibase diff two Informix databases ending after a few minutes - see debug log
I think the error occurred at the end of the comparison when sstem catalog of db enginy was examined
[debug.txt](https://github.com/liquibase/liquibase/files/4914788/debug.txt)

## Steps To Reproduce
List the steps to reproduce the behavior.

* Please be precise and ensure private information is redacted
* Include things like
  * Files used - sql scripts, changelog file(s), property file(s), config files, POM Files
  * Exact commands used - CLI, maven, gradle, spring boot, servlet, etc.

## Actual Behavior
A clear and concise description of what happens in the software **before** this pull request.

* Include console output if relevant
* Include log files if available.

## Expected/Desired Behavior
A clear and concise description of what happens in the software **after** this pull request.

## Additional Context

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-378) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
Hi @arozehnal Thanks for writing up this issue.  Can you try a couple of other things since I don't have an AIX Informix DB system readily available?  Can you run a **liquibase snapshot** on each one of the databases independently of each other to see if one of the snapshot commands is failing?  
Can you also run **liquibase generateChangeLog** to see if problem is with liquibase generating information about one of the databases?

**Comment by arozehnal** [comment]
I'm newbie to liquibase - I will provide the required files / information, but it will take me a while  :-(

**Comment by arozehnal** [comment]
I have only one database filled.
I tried to run snapshot and generateChangeLog - both end in error.
 For an empty database, the snapshot passes.


[crash_snapshot.txt](https://github.com/liquibase/liquibase/files/4941794/crash_snapshot.txt)
[crash_generateChangeLog.txt](https://github.com/liquibase/liquibase/files/4941795/crash_generateChangeLog.txt)

**Comment by arozehnal** [comment]
In the previous post, I inserted logs with only ERROR level.
I enclose another with logLevel=all.
Last run of liquibase (started 14:18:26.183 DEBUG) ends OK:

According to the log the liquibase crach on the column named 'case' in the syscolformats and syssvwformats tables.

These tables are not part of the Informix db system catalog, They were created using an IBM tool called NewEra a few years ago.
After removing these tables, the liquibase no longer crashes. Since we no longer use NewEra, I suggest to the project manager  permanently removed from the schema.
I don't know if you want to deal with this case further, but I say the issue can be closed.

[liquibase.zip](https://github.com/liquibase/liquibase/files/4943847/liquibase.zip)

**Comment by molivasdat** [comment]
Closing per above.
