### ISSUE TITLE
Linux OS: liquibase command failed to start: Unerwarteter Fehler bei der Ausführung von Liquibase: Unbekannter Parameter: 'angeLogFile'

### ISSUE THREAD

**Issue by Ralf63** [liquibase/liquibase#1267]
## Environment
**Liquibase Version**:

Liquibase Versions: 3.9.8, 4.0.0-beta2, maybe many more! 

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

all

**Operating System Type & Version**:

Ubuntu Linux 18.04

## Description
On Linux the liquibase command is not able to start, because it does incorrectly analyze the command line arguments. The liquibase command is stripping the first two characters off the option name and throws an error.

The same version on Windows works! Did you ever test it on linux?

Example: 
$ liquibase --changeLogFile=dbchangelog.xml generateChangeLog
Starte Liquibase am 07:57:04 (Version 4.0.0-beta2 #15, kompiliert am 2020-07-01 14:14+0000)
Bitte geben Sie '--help' auf der Kommandozeile an, um die Hilfe anzuzeigen.
Unerwarteter Fehler bei der Ausführung von Liquibase: Unbekannter Parameter: 'angeLogFile'
Bitte verwenden Sie die '--logLevel'-Option, um mehr Informationen zu erhalten.
Juli 15, 2020 7:57:04 VORM. liquibase.integration
SEVERE: Unerwarteter Fehler bei der Ausführung von Liquibase: Unbekannter Parameter: 'angeLogFile'
liquibase.exception.CommandLineParsingException: Unbekannter Parameter: 'angeLogFile'
	at liquibase.integration.commandline.Main.parsePropertiesFile(Main.java:916)
	at liquibase.integration.commandline.Main.parseDefaultPropertyFileFromFile(Main.java:652)
	at liquibase.integration.commandline.Main.parseDefaultPropertyFiles(Main.java:614)
	at liquibase.integration.commandline.Main.parseOptions(Main.java:1023)
	at liquibase.integration.commandline.Main$1.run(Main.java:232)
	at liquibase.integration.commandline.Main$1.run(Main.java:166)
	at liquibase.Scope.child(Scope.java:170)
	at liquibase.Scope.child(Scope.java:144)
	at liquibase.integration.commandline.Main.run(Main.java:166)
	at liquibase.integration.commandline.Main.main(Main.java:145)

## Steps To Reproduce
liquibase --changeLogFile=dbchangelog.xml generateChangeLog

## Actual Behavior
generateChangelog Command doesn't work!

## Additional Context

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-382) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
@Ralf63 Thanks for writing up this issue.  Not sure if there is something different about your environment.  We do test our code on Linux.  I will look to see if I can recreate this on my end.

**Comment by molivasdat** [comment]
Hi @Ralf63 .  I just tried to reproduce your issue.
I created a docker ubuntu image with 18.04, installed liquibase and JRE 8.
And ran generateChangeLog just as you did
```
root@ba59f30b6c3b:/lb400/examples/xml# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
root@ba59f30b6c3b:/lb400/examples/xml# liquibase --changeLogFile=mike.xml generateChangeLog
Liquibase Community 4.0.0 by Datical
Starting Liquibase at 21:22:15 (version 4.0.0 #19 built at 2020-07-13 19:45+0000)
Liquibase command 'generateChangeLog' was executed successfully.
root@ba59f30b6c3b:/lb400/examples/xml# 
```
and I could not recreate the issue you are seeing.

**Comment by Ralf63** [comment]
Sorry. You are right. I tried it on another machine with java8 and java11 and it works. On my development-vm liquibase does not run, neither with openjdk8 nor openjdk11.

**Comment by Ralf63** [comment]
Could you test it once more, please?

Install liquibase in $HOME/liquibase.
cd $HOME
Run: $HOME/liquibase  --changeLogFile=mike.xml generateChangeLog

The error occurs!

$ cd liquibase
$ ./liquibase  --changeLogFile=abc.xml generateChangeLog
Liquibase Community 4.0.0-beta2 by Datical
Starte Liquibase am 12:49:15 (Version 4.0.0-beta2 #15, kompiliert am 2020-07-01 14:14+0000)
Liquibase command 'generateChangeLog' was executed successfully.
$ cd ..
$ ./liquibase/liquibase  --changeLogFile=abc.xml generateChangeLog
Starte Liquibase am 12:49:27 (Version 4.0.0-beta2 #15, kompiliert am 2020-07-01 14:14+0000)
Bitte geben Sie '--help' auf der Kommandozeile an, um die Hilfe anzuzeigen.
Unerwarteter Fehler bei der AusfÃ¼hrung von Liquibase: Unbekannter Parameter: 'angeLogFile'
Bitte verwenden Sie die '--logLevel'-Option, um mehr Informationen zu erhalten.
Jul 17, 2020 12:49:27 PM liquibase.integration
SCHWERWIEGEND: Unerwarteter Fehler bei der AusfÃ¼hrung von Liquibase: Unbekannter Parameter: 'angeLogFile'
liquibase.exception.CommandLineParsingException: Unbekannter Parameter: 'angeLogFile'
	at liquibase.integration.commandline.Main.parsePropertiesFile(Main.java:916)
	at liquibase.integration.commandline.Main.parseDefaultPropertyFileFromFile(Main.java:652)
	at liquibase.integration.commandline.Main.parseDefaultPropertyFiles(Main.java:614)
	at liquibase.integration.commandline.Main.parseOptions(Main.java:1023)
	at liquibase.integration.commandline.Main$1.run(Main.java:232)
	at liquibase.integration.commandline.Main$1.run(Main.java:166)
	at liquibase.Scope.child(Scope.java:170)
	at liquibase.Scope.child(Scope.java:144)
	at liquibase.integration.commandline.Main.run(Main.java:166)
	at liquibase.integration.commandline.Main.main(Main.java:145)
