### ISSUE TITLE
Improve the documentation of `loadData` tag

### ISSUE THREAD

**Issue by YuryHrytsuk** [liquibase/liquibase#1271]
1. by default all CSV columns are used while generating SQL even if they aren't described in `Columns` property. This might be quite surprising therefore should be mentioned in the documentation explicitly;
1. another way to improve the documentation will be describing how to skip certain headers in CSV file by using `skip` value of `type` property attribute in `Column` property as it is described in [this stackoverflow answer](https://stackoverflow.com/questions/30884167/loadupdatedata-in-liquibase-select-only-some-columns-from-csv).

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-387) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
@YuryHrytsuk Thanks for writing this up.  I will have our docs team update the documentation to add the skip attribute added.

**Comment by YuryHrytsuk** [comment]
Now you can find a relevant section in [docs page](https://docs.liquibase.com/change-types/community/load-data.html)
