### ISSUE TITLE
Report as "Not a valid resource entry", when script file put at META-INF folder

### ISSUE THREAD

**Issue by bradwoo8621** [liquibase/liquibase#1273]
## Environment
**Liquibase Version**: 3.8.9

**Liquibase Integration & Version**: spring boot

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: N/A

**Operating System Type & Version**: N/A

## Description
When script files put at `META-INF` folder, and this module is the main module of spring boot jar, script file is reported as `Not a valid resource entry` on warning level, report by `SpringLiquibase.SpringResourceOpener#list`

## Steps To Reproduce
Here is my module structure

```
a-project
  |-- pom.xml
  |-- main
          |-- java
                  |-- some packages
                           |-- MyStarter.java
          |-- resources
                  |-- META-INF
                          |-- scripts
                                  |-- script-one.yml
```

Pom dependencies, boot in `2.3.0.RELEASE`,

```xml
		<!-- boot -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jdbc</artifactId>
		</dependency>
		<!-- liquibase -->
		<dependency>
			<groupId>org.liquibase</groupId>
			<artifactId>liquibase-core</artifactId>
		</dependency>
		<!-- mysql -->
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
		</dependency>
```

Starter class,

```java
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class MyStarter {
	public static void main(String[] args) {
		SpringApplication.run(MyStarter.class, args);
	}
}
```

## Expected/Desired Behavior
Don't report as invalid, it should be valid.

## Additional Context

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-388) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
Hi @bradwoo8621 Thanks for writing up this issue.
The META-INF is a special folder not intended for scripts according to the java spec.
https://docs.oracle.com/javase/7/docs/technotes/guides/jar/jar.html
Is there a special requirement that you need to use the META-INF folder for your scripts.  Would it be possible to put it into another folder outside of META-INF but still inside of resources?

**Comment by bradwoo8621** [comment]
@molivasdat Thanks for your explanation, never notice that before, then seems everything is OK now.  
And just in case, if script files are in `META-INF`, and not in main module, it works. Like the following structure:

```
a-project
  |-- pom.xml
  |-- main
          |-- java
                  |-- some packages
                           |-- MyStarter.java
b-project
  |-- pom.xml
  |-- main
          |-- resources
                  |-- META-INF
                          |-- scripts
                                  |-- script-one.yml

```

Project A depends on project B, it works. That really confuse.

**Comment by molivasdat** [comment]
Closing issue as special folder for java based apps.
