### ISSUE TITLE
Database changelog lock not released automatically when running liquibase cli against SQL Server 2019 in a container

### ISSUE THREAD

**Issue by ezloj** [liquibase/liquibase#1275]
**Liquibase Version**:
Either 3.10.0 or 4.0.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
CLI

**Liquibase Extension(s) & Version**: 
https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/8.2.2.jre13/mssql-jdbc-8.2.2.jre13.jar

**Database Vendor & Version**:
https://hub.docker.com/_/microsoft-mssql-server MS SQL Server 2019 (also tried with 2017 with same result)

**Operating System Type & Version**:
Liquibase ran on: Darwin 19.5.0 / MacOs 10.15.5

## Description
Basically this:
16:23:00.971 INFO  [liquibase.changelog.ChangeSet]: ChangeSet changelog.xml::sqlFile-example::liquibase-docs ran successfully in 16ms
...
...
16:23:00.999 INFO  [liquibase.lockservice.StandardLockService]: Successfully released change log lock
16:23:01.001 ERROR [liquibase.Liquibase]: Could not release lock

sqlFile contents for specific above log:
USE [arbitrary_existing_db_name];

However it seems neither:

* liquibase cli version(3.10.0/4.0.0);
* changelog format (XML/YAML);
* changelog tags (sql file/include).

seem to affect the outcome. Manual release or releaseLocks command work fine after which running liquibase update fails again on lock release.

## Steps To Reproduce
Take env and try to do anything (SQL Server 2019 + any liquibase cli)

## Actual Behavior
Lock not released

## Expected/Desired Behavior
Lock released automatically

**Comment by molivasdat** [comment]
Thanks @ezloj We will add this to the list of issues we are reviewing.

**Comment by ezloj** [comment]
@molivasdat thanks. I've managed to narrow the problem down to the SQL that is being executed (even though that probably shouldn't result in database changelog lock not being lifted).

Example SQL that works (first example from Google):

CREATE TABLE Persons (
    PersonID int,
    LastName varchar(255),
    FirstName varchar(255),
    Address varchar(255),
    City varchar(255) 
);

Example that doesn't work:
USE database_name
GO
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = N'schema_name')
EXEC sys.sp_executesql N'CREATE SCHEMA [schema_name]'
GO

Perhaps this will help. It also fails on 'GO' statement, but removing it, again, produces the successful changset application which is followed by a lock release failure.

**Comment by mariochampion** [comment]
hey @ezloj, @molivasdat, @r2liquibase -- have any of yall tried the non-workin code outside of a container. see if it is just the sql itself that chokes the releaselocks?
```
USE database_name
GO
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = N'schema_name')
EXEC sys.sp_executesql N'CREATE SCHEMA [schema_name]'
GO
```

**Comment by sf9251** [comment]
This could be caused by the very first statement in the proc sql - USE database_name if the database_name is different than what is specified in the connection string.
