### ISSUE TITLE
Liquibase should have a better logging with failOnError=false when error occurs

### ISSUE THREAD

**Issue by szandany** [liquibase/liquibase#1279]
## Description
Liquibase changeSets have an attribute "failOnError".   When set to "false", Liquibase will not fail execution and continue on to the next changeSet if the current one is failing.
This is the expected behavior.
However, in the event where some failing changeSets with "failOnError=false" during deployment, Liquibase will just output "_Liquibase: Update has been successful._" 

It will be more helpful to troubleshoot if Liquibase had a better output/logging specifying the errors during deployment. 

## Steps To Reproduce
1. Create a changeSet with failOnError:false and a bad syntax:

```
--liquibase formatted sql

--changeset SteveZ:45555-createTable_TABLE200 context:UAT labels:Jira-166 failOnError:false
CREATE TABLE TABLE200 
  (
    JOB_ID VARCHAR2(10 BYTE) NOT NULL, 
    MIN_SALARY NUMBERed(6, 0), 
    MAX_SALARY NUMBER(6, 0), 
    CONSTRAINT JOB_ID_PK200 PRIMARY KEY (JOB_ID)
  )
;
--rollback drop table TABLE200
```

1. run: liquibase update

## Actual Behavior
Liquibase: Update has been successful.

## Expected/Desired Behavior
It would be helpful is Liquibase had outputted/logged more information about what errors happened during deployment.

## Additional Context
Things can get even more complicated when there is a script with multiple statement being deployed, where some of the statements are successful and some are not.

For example, consider the following script:

```
 --changeset SteveZ:45555-createTable_TABLE200and201 context:UAT labels:Jira-166 failOnError:false
CREATE TABLE TABLE200 
  (
    JOB_ID VARCHAR2(10 BYTE) NOT NULL, 
    MIN_SALARY NUMBER(6, 0), 
    MAX_SALARY NUMBER(6, 0), 
    CONSTRAINT JOB_ID_PK200 PRIMARY KEY (JOB_ID)
  )
;

CREATE TABLE TABLE201 
  (
    JOB_ID VARCHAR2(10 BYTE) NOT NULL, 
    MIN_SALARY NUMBERed(6, 0), 
    MAX_SALARY NUMBER(6, 0), 
    CONSTRAINT JOB_ID_PK201 PRIMARY KEY (JOB_ID)
  )
;
```

Here there are two statements in one changeSet with the failOnError=false attribute.
When running: liquibase update

1. Liquibase will run this changeSet
1. The first statement will create the table "TABLE200"
1. The second statement will fail because of "NUMBERed" bad syntax.
1. Liquibase will fail on this changeSet and will NOT create a row in the DATABASECHANGELOG
This will result in an unexpected object TABLE200 in the database.
If Liquibase had a better logging, then the user could at least had seen what happened during the deployment.

## Acceptance Criteria
1. We need to respect the optional failOnError setting, but change the silent fail. That is, they do not need to stop on error (thus their optional setting) but still need to know on error
1. This notification can be missed in automation, but we can still make the information available to the user.
1. The following message should be output to the log at WARNING level

```java
TBD
```

**Comment by lbadam** [comment]
@tati-qalified can you test this to validate the issue? Thanks!

**Comment by tati-qalified** [comment]
Hi @szandany, sorry for the late response.
It seems like functionality has changed slightly, so now the problem you mentioned here:

> 1. Liquibase will run this changeSet
> 2. The first statement will create the table "TABLE200"
> 3. The second statement will fail because of "NUMBERed" bad syntax.
> 4. Liquibase will fail on this changeSet and will NOT create a row in the DATABASECHANGELOG
> 5. This will result in an unexpected object TABLE200 in the database.

Isn't an issue anymore.

I do agree that some type of message about changesets failing would be an improvement. However, it's also important to note that setting any `log-level` value will show the failures and the stack trace.

Would you be willing to submit a PR in order to add a better message to the logs in this scenario?

Thank you,
Tatiana

**Comment by lbadam** [comment]
We're working on this and hope to have it in a release soon. 

The output when TWO changesets marked `failOnError:false` fail will look like this:

```
UPDATE SUMMARY
Run:                          8
Previously run:               0
Filtered out:                 0
Failed deployment:            2
-------------------------------
Total change sets:           10
```

If you add `--show-summary=verbose` this will be the output when TWO changesets marked `failOnError:false` fail:

```
UPDATE SUMMARY
Run:                          8
Previously run:               0
Filtered out:                 0
Failed deployment:            2
-------------------------------
Total change sets:           10


+------------------------------------------------------+----------------------------+
| Changeset Info                                       | Reason Skipped             |
+------------------------------------------------------+----------------------------+
| mdc-changelog-cafe.sql::create-foods::mmc            | Changeset failed to deploy |
|                                                      | failOnError:false          |
+------------------------------------------------------+----------------------------+
| mdc-changelog-cafe.sql::create-staffers::mmc         | Update operation failed    |
|                                                      | failOnError:false          |
+------------------------------------------------------+----------------------------+
```

**Comment by filipelautert** [comment]
I'm proposing an OSS only fix for this at pr https://github.com/liquibase/liquibase/pull/6414 .
