### ISSUE TITLE
As a user I would like the modifySql property to prepend a single space when using the 'append' attribute by default

### ISSUE THREAD

**Issue by szandany** [liquibase/liquibase#1283]
**Liquibase Version**: All versions

## Description
Liquibase has the ability to append string values to a changeSet SQL with the **modifySql** property with the **append** attribute.  However, the default behavior is that the strings are added "as is".

It will be more user friendly if the modifySql property prepends a single space when using the **append** attribute by default.

## Steps To Reproduce
Run the following changeSet with the `liquibase updateSQL`

```xml
<changeSet author="bob" id="1">
  <createTable tableName="department1234">
      <column name="id" type="int"> 
        <constraints primaryKey="true" nullable="false"/>
      </column>
      <column name="firstname" type="varchar(50)"/>
      <column name="lastname" type="varchar(50)">
        <constraints notNullConstraintName="JOB_TITLE_NN1234" nullable="false"/>\ 
      </column>
      <column name="active" type="boolean" defaultValueBoolean="true"/>
  </createTable>
  <modifySql dbms="oracle">
    <append value="initrans 9999"/>
    <append value="pctfree 9999"/>
  </modifySql>  
</changeSet>
```

## Actual Behavior
For the following changeSet above the output is:

```sql
CREATE TABLE HR_DEV.department1234 (id INTEGER NOT NULL, firstname VARCHAR2(50), lastname VARCHAR2(50) CONSTRAINT JOB_TITLE_NN1234 NOT NULL, active NUMBER(1) DEFAULT 1, CONSTRAINT PK_DEPARTMENT1234 PRIMARY KEY (id))initrans 9999pctfree 9999;
```

## Expected/Desired Behavior
```sql
CREATE TABLE HR_DEV.department1234 (id INTEGER NOT NULL, firstname VARCHAR2(50), lastname VARCHAR2(50) CONSTRAINT JOB_TITLE_NN1234 NOT NULL, active NUMBER(1) DEFAULT 1, CONSTRAINT PK_DEPARTMENT1234 PRIMARY KEY (id)) initrans 9999 pctfree 9999;
```

## Suggestions
Here is a possible way the changeSet could look like if we add a **prependSpace** attribute.

```xml
<changeSet author="bob" id="1">
        <createTable tableName="department1234">
             <column name="id" type="int">
                  <constraints primaryKey="true" nullable="false"/>
         </column>
             <column name="firstname" type="varchar(50)"/>
             <column name="lastname" type="varchar(50)">
                  <constraints notNullConstraintName="JOB_TITLE_NN1234" nullable="false"/>
             </column>
             <column name="active" type="boolean" defaultValueBoolean="true"/>
        </createTable>
        <modifySql dbms="oracle" prependSpace="true">
            <append value="initrans 9999"/>
            <append value="pctfree 9999"/>
        </modifySql>
    </changeSet>
```

Of course when NOT using the "prependSpace" it will default to "true" but it will also have the option to set it to false as well when the prependSpace is not desired.

## Acceptance Criteria
1. A new attribute "prependSpace" is created and available for XML, YAML, JSON changelog formats, which adds ONE space between attribute/values placed via modifySql when "prependSpace=true"
  1. If there is already a space before the attribute/values, we do add an additional space, rather than try to out-smart or corrrect their light mis-usage, as an extra space is of no damaging impact.
1. The property is case-insensitive where processed in the code, altho for XML validation reasons we can require camelCasing as "prependSpace"
1. If not specified, "prependSpace" defaults to true
1. If "prependSpace=false" the string is presented as is.

**Comment by kataggart** [comment]
closing for now; can re-open/open a new one if it becomes priority again thanks
