### ISSUE TITLE
Forbid empty changeSet id and author

### ISSUE THREAD

**Issue by wobblycogs** [liquibase/liquibase#1290]
## Environment
**Liquibase Version**: 3.9.0

**Liquibase Integration & Version**: Spring Boot

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: MSSQL 

**Operating System Type & Version**: Windows

## Description
A changeSet with an empty id and or author is accepted as valid but this is undesirable behaviour. 

Autocomplete in many IDE's will automatically add required attributes to an element with empty values for example:

`<changeSet id="" author=""></changeSet>`

It's easy to complete the id and forget to fill in the author before moving on. If the id is unique the changeSet will be accepted as a valid update but from a change tracking point of view this is undesirable.

I would like to be able to indicate that the author and id must be non-empty as well as being required.

## Steps To Reproduce
Create a changeSet like this:

`<changeSet id="some_unique_id" author="">...</changeSet>`

## Actual Behavior
Change is accepted with an empty author

## Expected/Desired Behavior
Change is rejected because the author field is empty

**Comment by molivasdat** [comment]
Thanks @wobblycogs for taking the time to write up this issue.  We will take this into consideration with the other issues that have been queued.

**Comment by lbadam** [comment]
Closing this as fixed in recent versions of Liquibase. Using 4.29.1 I get the following error:

```
ERROR: Exception Details
ERROR: Exception Primary Class:  ValidationFailedException
ERROR: Exception Primary Reason:  Validation Failed:
     1 changes have validation failures
          ChangeSet Id and Author are empty, master.xml::::

ERROR: Exception Primary Source:  4.29.1

Unexpected error running Liquibase: Validation Failed:
     1 changes have validation failures
          ChangeSet Id and Author are empty, master.xml::::

For more information, please use the --log-level flag
```
