### ISSUE TITLE
insert command with valueSequenceNext uses default schema name

### ISSUE THREAD

**Issue by little-fish** [liquibase/liquibase#1304]
## Environment
**Liquibase Version**: 4.0.0

**Liquibase Integration & Version**: spring boot

**Database Vendor & Version**: Oracle 11g, PostgreSQL 8

## Description
I have a changelog with following changesets:

```xml
<changeSet id="0001" author="xxx">
    <createSequence sequenceName="my_sequence" startValue="1" incrementBy="1" schemaName="my_schema"/>
</changeSet>

...

<changeSet id="0003" author="xxx">
    <insert tableName="table_a" schemaName="my_schema">
         <column name="id" valueSequenceNext="my_sequence" />
    </insert>
</changeSet>
```

And Liquibase fails with:

```java
Caused by: liquibase.exception.DatabaseException: ORA-02289: sequence does not exist
 [Failed SQL: (2289) INSERT INTO my_schema.table_a (id) VALUES (LIQUIBASE.my_sequence.nextval)]
```

If I try ` <column name="id" valueSequenceNext="my_schema.my_sequence" />` it fails with:

```java
Caused by: liquibase.exception.DatabaseException: ORA-00904: "LIQUIBASE"."my_schema"."my_sequence"."NEXTVAL": invalid identifier
 [Failed SQL: (904) INSERT INTO my_schema.table_a (id) VALUES (LIQUIBASE."my_schema"."my_sequence".nextval)]
```

I have tried Oracle and PostgreSQL.

`LIQUIBASE` is the user used from JDBC connection.

Thank you.

**Comment by molivasdat** [comment]
Hi @little-fish Thanks for writing up this issue.  We will add it to list of issues that we are processing.
