### ISSUE TITLE
Postgres generated changeLog should not contain schema name for STOLO if includeSchema is turned off

### ISSUE THREAD

**Issue by szandany** [liquibase/liquibase#1315]
## Environment
**Liquibase Version**: 3.10.2

**Liquibase Integration & Version**: CLI.

**Operating System Type & Version**: Windows, Unix/Linux

## Description
When generating PostgreSQL changeLogs (any format - XML, Formatted SQL, JSON, YAML) with stored procedures without the flag `--includeSchema=true`

1. The changeLog **will have the schema name** included for **Stored Procedures objects**.
1. The changeLog **will NOT have the schema name** included for **all other objects**.

## Steps To Reproduce
Run the generateChangeLog command **without** the `--includeSchema=true` flag against a schema containing tables, views and functions with any changeLog format.

## Actual Behavior
Here is a sample generated changeLog.

```
--liquibase formatted sql

--changeset support.liquibase.net:1597074633585-1
CREATE VIEW "myView2" AS SELECT "execSales".id,
    "execSales".name
   FROM "execSales";;

--changeset support.liquibase.net:1597074633585-2
CREATE VIEW "newView" AS SELECT "execSales".id,
    "execSales".name
   FROM "execSales";;

--changeset support.liquibase.net:1597074633585-3
ALTER SESSION SET SEARCH_PATH=null;
CREATE OR REPLACE FUNCTION public.func_kunden()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
   BEGIN
      IF TG_OP = 'INSERT' THEN
        INSERT INTO  public."STD_Adressat" ("AdressatId", "Anrede", "Anzeigename", "Bemerkung")
           VALUES (new."AdressatId", new."Anrede", new."Anzeigename", new."Bemerkung");
        RETURN NEW;
      END IF;
      RETURN NEW;
    END;
$function$;

--changeset support.liquibase.net:1597074633585-4
ALTER SESSION SET SEARCH_PATH=null;
CREATE OR REPLACE FUNCTION public.plusone(val integer)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
BEGIN
RETURN val + 1;
END; $function$;
```

## Expected/Desired Behavior
The Function changeSets should not have the schema name specified.
For example:

```sql
--liquibase formatted sql

--changeset support.liquibase.net:1597074633585-1
CREATE VIEW "myView2" AS SELECT "execSales".id,
    "execSales".name
   FROM "execSales";;

--changeset support.liquibase.net:1597074633585-2
CREATE VIEW "newView" AS SELECT "execSales".id,
    "execSales".name
   FROM "execSales";;

--changeset support.liquibase.net:1597074633585-3
ALTER SESSION SET SEARCH_PATH=null;
CREATE OR REPLACE FUNCTION func_kunden()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
   BEGIN
      IF TG_OP = 'INSERT' THEN
        INSERT INTO "STD_Adressat" ("AdressatId", "Anrede", "Anzeigename", "Bemerkung")
           VALUES (new."AdressatId", new."Anrede", new."Anzeigename", new."Bemerkung");
        RETURN NEW;
      END IF;
      RETURN NEW;
    END;
$function$;

--changeset support.liquibase.net:1597074633585-4
ALTER SESSION SET SEARCH_PATH=null;
CREATE OR REPLACE FUNCTION plusone(val integer)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
BEGIN
RETURN val + 1;
END; $function$;
```

## Additional Context
The generated `ALTER SESSION SET SEARCH_PATH=null;` statements should not be included in the changeSets as they will cause a failure during an update.

This is related to ticket: [https://github.com/liquibase/liquibase/issues/1119](https://github.com/liquibase/liquibase/issues/1119)

**Comment by molivasdat** [comment]
Thanks @szandany for writing up this issue.  We are going to add it to our list of issues to process.

**Comment by nvoxland** [comment]
We avoid modifying SQL we snapshot from the database, so closing this issue.
