### ISSUE TITLE
Cannot Use includeAll with changeLogDirectory

### ISSUE THREAD

**Issue by mrgrew** [liquibase/liquibase#1331]
## Environment
**Liquibase Version**:
3.10.2

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
maven plugin 3.10.2

**Liquibase Extension(s) & Version**: 
N/A

**Database Vendor & Version**:
N/A

**Operating System Type & Version**:
N/A

## Description
The includeAll element cannot be used when changeLogDirectory is specified with the liquibase-maven-plugin.

## Steps To Reproduce
* Clone https://github.com/mrgrew/liquibase-includeAll-changeLogDirectory to a machine with Java 8+ installed
* Run mvnw liquibase:status

## Actual Behavior
Error "liquibase.exception.SetupException: File does not exist: file:/includeAll/sample.sql" is displayed

## Expected/Desired Behavior
The changeset is successfully processed

**Comment by molivasdat** [comment]
Hi @mrgrew .  Thanks for opening up this issue and thanks for the PR associated with it.  We will take a look and see about pulling in the PR to fix the issue as long as it doesn't break other functionality.

**Comment by mrgrew** [comment]
I see a `java.nio.file.NoSuchFileException` with liquibase `4.16.1` which is different than the `liquibase.exception.SetupException` this PR was intended to address.

No error occurs with liquibase `4.17.2` so there must have been another PR that fixed that issue.

**Comment by kevin-atx** [comment]
This issue was fixed in Liquibase 4.17.2. I'm closing this issue as a duplicate.
