### ISSUE TITLE
changeSetId & changeSetAuthor tags are not getting recognized by liquibase in rollback while using liquibase formatted sql.

### ISSUE THREAD

**Issue by salman-ud** [liquibase/liquibase#1335]
## Environment
**Liquibase Version**: 4.0.0

**Liquibase Integration & Version**: 4.0.0

**Liquibase Extension(s) & Version**:  4.0.0

**Database Vendor & Version**: MSSQL 2016

**Operating System Type & Version**: Windows

## Description
changeSetId & changeSetAuthor tags are not getting recognized by liquibase in rollback while using liquibase formatted sql.
But it is working properly if using xml based change set as mentioned in https://docs.liquibase.com/workflows/liquibase-community/using-rollback.html

Following is my **ChangeLog.xml**:- 
`<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
  xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
                      http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd">
<changeSet author="appuser" id="release_tag_3.20.09">
    <tagDatabase tag="release_tag_3.20.09" />
   </changeSet>
<include relativeToChangelogFile="true" file="1.sql" />
<changeSet author="appuser" id="release_tag_3.20.10">
        <tagDatabase tag="release_tag_3.20.10" />
</changeSet>
<include relativeToChangelogFile="true" file="2.sql" />
</databaseChangeLog>`

**1.sql** :-

--liquibase formatted sql
--changeset dhansal:1_sql
drop table if exists changeRollback
GO
create table changeRollback(id int)
GO
--rollback drop table changeRollback

**2.sql** :-

--liquibase formatted sql
--changeset dhansal:2_sql
alter table changeRollback add id2 int
GO
--rollback changeSetId:1_sql changeSetAuthor:dhansal

And I'm running rollback till tag version "release_tag_3.20.10" then it is giving me syntax error as it is considering "changeSetId:1_sql changeSetAuthor:dhansal" as a sql rather than referencing to previous changeSet.
.

**Comment by atzawada** [comment]
Wanted to add this doesn't work in 3.7.0 either, running the following rollback statement:
```sql
--rollback changeSetPath:EXAMPLE/test-params.sql changeSetAuthor:zawada1 changeSetId:test-params-table
```
Still try's to execute as a custom SQL statement.

**Comment by molivasdat** [comment]
Hi @salman-ud .  Thanks for writing up this issue.
`
--liquibase formatted sql
--changeset dhansal:2_sql
alter table changeRollback add id2 int
GO
--rollback changeSetId:1_sql changeSetAuthor:dhansal
`

You are correct in that this is not available in formatted sql.
There is not a way to reference a previous changeset as the rollback script.
You can write a PR to create the enhancement though.

**Comment by atzawada** [comment]
@molivasdat I may have time to take a look. Can you point me to where in the codebase I could jump in to this issue?

**Comment by awhitford-cip** [comment]
[I am interested in seeing this issue resolved](https://forum.liquibase.org/t/how-to-rollback-changesetid-using-sql-dialect/7081), and I see the PR already submitted.  _What is the hold up?_
