### ISSUE TITLE
DATABASECHANGELOGLOCK table cannot be created on Derby 10.5

### ISSUE THREAD

**Issue by ali-jrn** [liquibase/liquibase#1338]
## Environment
**Liquibase Version**:3.10.2

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: Apache Derby 10.5

**Operating System Type & Version**: Ubuntu 18.04

## Description
Apache Derby 10.5 does not support boolean data type, so it is not possible to create the DATABASECHANGELOGLOCK table which as Boolean data type in it.
So, the update command will fail in the first run with below message:
Unexpected error running Liquibase: Use of 'BOOLEAN' requires database to be upgraded from version 10.5 to version 10.7 or later. [Failed SQL: (20000) CREATE TABLE PS.DATABASECHANGELOGLOCK (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID))]

**Comment by molivasdat** [comment]
Hi @ali-jrn .  Thanks for writing up this issue.  We will process it and it to our list of issues.  If you have a suggested PR to fix it that will help move the process forward.

**Comment by ali-jrn** [comment]
> Hi @ali-jrn . Thanks for writing up this issue. We will process it and it to our list of issues. If you have a suggested PR to fix it that will help move the process forward.
We use Smallint instead of Boolean in our applications, I know it may be a big change and few people use old Derby these days, but I would be useful for us to have this feature.

**Comment by FBurguer** [comment]
Hi!  We will add this issue as an enhancement, its not at the prority at this moment, but we will look into it when we have the opportunity. Thank you for submitting this issue!

**Comment by lbadam** [comment]
Closing this issue as we do not plan to implement this change at this time.
