### ISSUE TITLE
Extraneous Output from liquibase-maven-plugin:4.0.0

### ISSUE THREAD

**Issue by mrgrew** [liquibase/liquibase#1339]
## Environment
**Liquibase Version**:
4.0.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
maven

**Liquibase Extension(s) & Version**: 
N/A

**Database Vendor & Version**:
N/A

**Operating System Type & Version**:
N/A

## Description
Version 4.0.0 of liquibase-maven-plugin displays warnings with Java stack traces. This extra output looks like errors that require investigation. In reality, it's just a warning.

## Steps To Reproduce
Follow the steps at https://github.com/mrgrew/liquibase-warnings

## Actual Behavior
See the "Output from Liquibase 4.0.0" at https://github.com/mrgrew/liquibase-warnings

## Expected/Desired Behavior
See the "Output from Liquibase 3.10.2" at https://github.com/mrgrew/liquibase-warnings

**Comment by molivasdat** [comment]
Hi @mrgrew Thanks for writing up this issue and providing a code repo test case.  We will add this to our list of issues to process.
