### ISSUE TITLE
Spacing after column in dynamic sql acts a junk character

### ISSUE THREAD

**Issue by saarchme** [liquibase/liquibase#1340]
## Environment
**Liquibase Version**:

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

**Operating System Type & Version**:

## Description
A clear and concise description of the issue being addressed.

* Describe the actual problematic behavior.
* Ensure private information is redacted.

## Steps To Reproduce
List the steps to reproduce the behavior.

* Please be precise and ensure private information is redacted
* Include things like
  * Files used - sql scripts, changelog file(s), property file(s), config files, POM Files
  * Exact commands used - CLI, maven, gradle, spring boot, servlet, etc.

## Actual Behavior
A clear and concise description of what happens in the software **before** this issue.

* Include console output if relevant
* Include log files if available.

## Expected/Desired Behavior
A clear and concise description of what happens in the software **after** a fix is completed.

Hello Team,

We are deploying some SP through Liquibase tools. These SPs have dynamic sql select query inside it. There is some spacing after some columns (can see it in the attachment picture) which when I copied to Notepad++ could see it as junk character. once these SPs are deployed, The execution of these SPs are failing.

The same SP deployed through SQL  server management studio is not having this issue. 
FYI, we are using xmlversion="1.0" with UTF-8 encoding format for all our script deployment. Kindly help to resolve this issue without changing the code.

![SpaceJunkCharacter](https://user-images.githubusercontent.com/18193449/91028024-74769000-e62f-11ea-8b72-5e66a3b5de4e.jpg)

Regards

**Comment by molivasdat** [comment]
Hi @saarchme Thank you for writing up this issue.  Can you add additional information into the description field, like the Liquibase version you are using , how you are using it and a sample testcase that shows the error occuring?
I have added the additional sections needed.
