### ISSUE TITLE
Liquibase 4.0.0 does not log the SQL-Error in case of an erroneous change set

### ISSUE THREAD

**Issue by pioneer2k** [liquibase/liquibase#1343]
## Environment
**Liquibase Version**: 4.0.0

**Liquibase Integration & Version**: Liquibase CDI 4.0.0

**Liquibase Extension(s) & Version**: Liquibase CDI 4.0.0

**Database Vendor & Version**: MySQL 5.7.12

**Operating System Type & Version**: Amazon Linux 2

## Description
We have just upgraded to Liquibase 4.0.0 from 3.10.2 and we are experiencing that Liquibase does not log the SQL-Error-Messages of a failing change set.
Example:
Log-Output of Liquibase 3.10.2:

08:55:33.182 [main] DEBUG liquibase.executor.jvm.JdbcExecutor - Executing with the 'jdbc' executor
08:55:33.183 [main] INFO  liquibase.executor.jvm.JdbcExecutor - INSERT INTO CLIENT VALUES (3,'CUSTOMER_CREDIT_MANAGER','Customer Credit Manager',1)
**08:55:33.268 [main] ERROR liquibase.changelog.ChangeSet - Change Set db/mysql/incrementalUpdates/00093_Client.sql::00093_Client::Thomas failed.  Error: Duplicate entry '3' for key 'PRIMARY' [Failed SQL: (1062) INSERT INTO CLIENT VALUES (3,'CUSTOMER_CREDIT_MANAGER','Customer Credit Manager',1)]**
08:55:33.268 [main] DEBUG liquibase.executor.jvm.JdbcExecutor - Release Database Lock

Log-Output of Liquibase 3.10.2:

FINE: Running Changeset:db/mysql/incrementalUpdates/00200_Client.sql::00200_Client::Thomas
FINE: Changeset db/mysql/incrementalUpdates/00200_Client.sql::00200_Client::Thomas
FINE: Reading ChangeSet: db/mysql/incrementalUpdates/00200_Client.sql::00200_Client::Thomas
FINE: Executing Statement: INSERT INTO CLIENT VALUES (3,'CUSTOMER_CREDIT_MANAGER','Customer Credit Manager',1)
FINE: Executing with the 'jdbc' executor
FINE: Release Database Lock
FINE: Executing with the 'jdbc' executor
INFO: Successfully released change log lock
SEVERE: Exception during lifecycle processing

As you can see the ERROR-line is missing. 

I had a quick look into the source code. In the class liquibase.changelog.ChangeSet the lines 654 and 655 in Version 3.10.2 are now missing in Liquibase 4.0.0. Maybe that causes the problem.

```
// just log the message, dont log the stacktrace by appending exception. Its logged anyway to stdout
log.severe(LogType.LOG, "Change Set " + toString(false) + " failed.  Error: " + e.getMessage());
```

## Steps To Reproduce
Add an errorneous change set to Liquibase and start Liquibase.

## Actual Behavior
see description

## Expected/Desired Behavior
see discription

**Comment by molivasdat** [comment]
Hi @pioneer2k Thanks for writing up this issue.  Can you create a PR that reverts that change and we can get it added to our list?

**Comment by pioneer2k** [comment]
Hi @molivasdat,
I just created PR 1352 - https://github.com/liquibase/liquibase/pull/1352

**Comment by nvoxland** [comment]
This has been fixed at some point. It is working correctly in 4.15.0.

Closing as "stale"
