### ISSUE TITLE
Liquibase 4.0.0 liquibase.exception. There is a problem with the Cyrillic

### ISSUE THREAD

**Issue by olegpolukhin** [liquibase/liquibase#1344]
## Environment
**Liquibase Version**: Liquibase Community 4.0.0 by Datical

**Liquibase Integration & Version**: CLI

**Database Vendor & Version**: PostgreSQL 12.3

**Operating System Type & Version**: Ubuntu 20.04

## Description
There is a problem with the Cyrillic alphabet. When I try to create a migration, I get an error and replaces Cyrillic characters with characters:? (question symbol). on version 3.7 there was no such problem.

Migration:
INSERT INTO segments (name) VALUES
    ('ССС'),
    ('ЗС СПД'),
    ('КС СПД');

ERROR:
Liquibase Community 4.0.0 by Datical
Starting Liquibase at 14:26:53 (version 4.0.0 #19 built at 2020-07-13 19:45+0000)
Unexpected error running Liquibase: Migration failed for change set dbchangelog.sql::4::userone:
     Reason: liquibase.exception.DatabaseException: ERROR: duplicate key value violates unique constraint "segments_name_key"
  Detail: Key (name)=(???? ??????) already exists. [Failed SQL: (0) INSERT INTO segments (name) VALUES
    ('????'),
    ('???? ??????'),
    ('???? ??????')]
For more information, please use the --logLevel flag

Before the update to version 4.0, everything worked fine for us. Now it doesn't work at all.

**Comment by molivasdat** [comment]
Hi @olegpolukhin Thanks for writing up this issue. We will add it to our list of issues to process.

**Comment by olegpolukhin** [comment]
> Hi @olegpolukhin Thanks for writing up this issue. We will add it to our list of issues to process.

Hello. This problem is check?

**Comment by n-dimens** [comment]
> > Hi @olegpolukhin Thanks for writing up this issue. We will add it to our list of issues to process.
> 
> Hello. This problem is check?

Check default encoding for collation in your database. This is not problem liquibase, i think. For me it was a solution to the same problem.

**Comment by olegpolukhin** [comment]
@n-dimens Everything is fine with encoding. This problem arose overnight. When switching from version 3 to 4. I played with different settings, but unfortunately I cannot accept the Cyrillic alphabet.

**Comment by MalloD12** [comment]
I cannot reproduce this issue on below environment: 

```
Liquibase Version: 4.15.0

Liquibase Integration & Version: CLI

Database Vendor & Version: PosgreSQL 14

Operating System Type & Version: Mac OS 12.1 
```

For below changelog:

```
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
    xmlns:pro="http://www.liquibase.org/xml/ns/pro"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-4.12.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">
    <changeSet author="mallod" id="1">
        <createTable tableName="segments">
            <column name="name" type="varchar(255)">
                <constraints nullable="false" primaryKey="true" primaryKeyName="CONSTRAINT_1"/>
            </column>
        </createTable>
    </changeSet>
    <changeSet author="mallod" id="2">
        <insert tableName="segments">
            <column name="name" value="ССС"/>
        </insert>
        <insert tableName="segments">
            <column name="name" value="ЗС СПД"/>
        </insert>
        <insert tableName="segments">
            <column name="name" value="КС СПД"/>
        </insert>
    </changeSet>
</databaseChangeLog>
```
And output obtained was:
```
Starting Liquibase at 16:20:15 (version 4.15.0 #4001 built at 2022-08-05 16:17+0000)
Liquibase Version: 4.15.0
Liquibase Community 4.15.0 by Liquibase
Running Changeset: issues/1344/changelog.xml::1::mallod
Running Changeset: issues/1344/changelog.xml::2::mallod
Liquibase command 'update' was executed successfully.
```

Which leaves tables in the below state:
```
name  |
------+
ССС   |
ЗС СПД|
КС СПД|
```
