### ISSUE TITLE
Liquibase does not enforce case (lowercase) when running changeset

### ISSUE THREAD

**Issue by robs-nice99** [liquibase/liquibase#1347]
## Environment
**Liquibase Version**: 3.8.0

**Liquibase Integration & Version**: CLI

**Database Vendor & Version**: Oracle 19.3.0

**Operating System Type & Version**: CentOS 7, running on docker

## Description
I created a changeset (xml format) by using the generateChangeLog command. All column names where lowercase. However, after applying the changeset, all column were created with uppercase names.

## Steps To Reproduce
* create a changeset with new tables and new columns, where the columns are lowercase (in xml format)
* apply the changeset to an Oracle DB
* verify the column names are in uppercase

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-597) by [Unito](https://www.unito.io/learn-more)

**Comment by robs-nice99** [comment]
This also happens with liquibase sql format, however it works correctly if the columns are quoted. So, I am not sure this is a liquibase issue or not. I am not deleting it right now, since this info can be useful for some one else.

**Comment by robs-nice99** [comment]
This was solved by using `objectQuotingStrategy="QUOTE_ALL_OBJECTS"` in the XML. Apparently this option is not available in Liquibase Formatted SQL.

**Comment by molivasdat** [comment]
Hi @robs-nice99 Thanks for writing up this issue.  The quoting strategy parameter is only available currently in XML format.
Glad you were able to solve your problem.
