### ISSUE TITLE
Allow bit column in postgresql 

### ISSUE THREAD

**Issue by DeyV** [liquibase/liquibase#1357]
## Environment
windows 10 
**Liquibase Version**:
Liquibase Community 4.0.0 by Datical
 Liquibase at 12:19:55 (version 4.0.0 #19 built at 2020-07-13 19:45+0000)

**Liquibase Extension(s) & Version**: 
postgresql-42.2.16.jar

**Database Vendor & Version**:
PostgreSQL 12.4 (Ubuntu 12.4-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit

## Description
I have table with column 
` ichmod bit(12) DEFAULT '111111111111'::"bit"`

`liquibase generateChangeLog`
generate error: 

`Unexpected error running Liquibase: java.lang.RuntimeException: java.lang.RuntimeException: liquibase.exception.UnexpectedLiquibaseException: Unknown boolean value: 111111111111`

## Steps To Reproduce
Create test database with table: 

```
CREATE TABLE public.test
(
    iid serial,
    ichmod bit(12) DEFAULT '111111111111'::"bit",
    CONSTRAINT test_pkey PRIMARY KEY (iid)
)
```

Run

```
 liquibase  --driver=org.postgresql.Driver --classpath=./postgresql-42.2.16.jar --url="jdbc:postgresql:// xxx" --changeLogFile=db.changelog-1.1.xml --username="xxx" --password="xxx"  generateChangeLog
```

**Comment by molivasdat** [comment]
Hi @DeyV Thanks for taking the time to write up this issue.  We will add it to the list of issues we are processing.
