### ISSUE TITLE
Unexpected error running Liquibase: Backup Server: 4.172.1.4: The value of 'allocated pages threshold' has been set to 40%.

### ISSUE THREAD

**Issue by sukhdevkhade** [liquibase/liquibase#1359]
Hi,

I am Currently using Liquibase Community 3.10.2 by Datical on local window machine . Currently i am using Sybase ASE 16.0 server. It's succesfuly connected to sybase but throws error  during sybase backup.

Error:
Unexpected error running Liquibase: Backup Server: 4.172.1.4: The value of 'allocated pages threshold' has been set to 40%.
[Failed SQL: (417201) dump database EQRMS to '/home/ec2-user/EQRMS.dump']

I am following below command :

liquibase --classpath=.\lib\jtds-1.3.1.jar --changeLogFile=.\examples\sql\samplechangelog.h2.sql --url="jdbc:jtds:sybase://34.244.126.123:5002/"  --username="sa" --password="sybase123"  update

My sql cmd

--liquibase formatted sql

--changeset bob:3
dump database EQRMS to '/home/ec2-user/EQRMS.dump'
go

please give solution.
I have attached output snip , please find 

thanks in advanced.
![LiqiErrorSnip](https://user-images.githubusercontent.com/49577440/91640158-1ab00480-ea39-11ea-91a9-c390c1b91f4d.PNG)

**Comment by sukhdevkhade** [comment]
Any solution ..

**Comment by molivasdat** [comment]
Hi @sukhdevkhade Thanks for writing up this issue.  This may belong in the SAP HANA extension.  Have you tried using the extension https://github.com/liquibase/liquibase-hanadb
If not, I think the issue may be better suited there.
Is this a command that can be executed via a jdbc connection or needs a sql type client connection?

**Comment by sukhdevkhade** [comment]
Hi @molivasdat 

Currently I am using Sybase ASE 16.0.

I have successfully connected to Sybase  DB using current jar.

Some operations are also successful, such as creation tables, databases etc.

But it throwing an error during backup sql statement.

My sql statement is : 

--liquibase formatted sql

--changeset bob:3

dump database EQRMS to '/home/ec2-user/EQRMS.dump'
go   

please let me know anything else.. 

Thanks.

**Comment by tati-qalified** [comment]
Hi @sukhdevkhade, sorry for the late response.
This issue is actually coming from SyBase, not from Liquibase. The SQL code in your changeset isn't being recognised as valid by SyBase.
I'd recommend checking the database logs in order to figure out the source of the problem.

Thank you
Tatiana
