### ISSUE TITLE
DateTimeType.java:38 NullPointerException (liquibase 4.0.0)

### ISSUE THREAD

**Issue by mironbalcerzak** [liquibase/liquibase#1366]
## Environment
**Liquibase Version**: 4.0.0

## Description
NPE in DateTimeType in 

```
java.lang.NullPointerException
        at liquibase.datatype.core.DateTimeType.toDatabaseDataType(DateTimeType.java:38)
```

## Steps To Reproduce
Generating SQL from changelog for Oracle DB is resulting in NPE

## Actual Behavior
NPE raised

## Expected/Desired Behavior
No NPE :)

## Additional Context

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-622) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
Hi @mironbalcerzak Thanks for writing up this issue and thanks for submitted a PR to fix it.  We will add this to our list of issues to process and merge as appropriate.

**Comment by mironbalcerzak** [comment]
Hi @molivasdat, no - I encountered that error in our environment, I don't have testcase.
