### ISSUE TITLE
liquibase-maven-plugin : blob/clob missing size when changelog generated from JPA

### ISSUE THREAD

**Issue by mironbalcerzak** [liquibase/liquibase#1373]
## Environment
**Liquibase Version**: 4.0.0

**Liquibase Integration & Version**: maven

**Liquibase Extension(s) & Version**: hibernate5-ext

**Operating System Type & Version**: windows 10

## Description
liquibase maven integration, while set to use ejb with hibernate5-ext, is missing "size" of blobs in generated changelog.

Sample JPA entity for reference

```
@Entity
@Table(name = "someblob")
public class SomeBlob {

    @Basic(fetch = FetchType.LAZY)
    @Column(name = "data", length = 12345)
    @Lob
    private byte[] blobdata;
}
```

## Steps To Reproduce
1. Create JPA entity
1. configure maven task with hibernate5-ext
1. generate changelog

## Actual Behavior
```
<createTable tableName="someblob">
	<column name="blobdata" type="BLOB"/>
</createTable>
```

## Expected/Desired Behavior
```
<createTable tableName="someblob">
	<column name="blobdata" type="BLOB(12345)"/>
</createTable>
```

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-632) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
Hi @mironbalcerzak Thanks for writing up this issue.  Can you move this to the [hibernate extension repository](https://github.com/liquibase/liquibase-hibernate) and we can manage it there.

**Comment by mironbalcerzak** [comment]
@molivasdat, sure thing
