### ISSUE TITLE
NullPointerException in LoadDataChange

### ISSUE THREAD

**Issue by cmayfield** [liquibase/liquibase#1374]
## Environment
In the process of upgrading from Java 8 to Java 11. This necessitated upgrading our Liquibase version from 3.5.5 due to changes in behavior with URLClassLoader causing FileSystemResourceAccessor to break.

**Liquibase Version**:
3.10.1-4.0.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
Gradle

**Database Vendor & Version**:
HSQL

**Operating System Type & Version**:
Windows 10

## Description
Trying to upgrade the version of Liquibase our project uses. When running our existing scripts (working under 3.5.5), we get a NullPointerException in LoadDataChange (line 336 in the 3.10.1 version) trying to load a CSV file. This happens because columnConfig is null; two lines later, the code checks to see if columnConfig is not null. Presumably the failing code should be moved inside the if branch.

**Comment by molivasdat** [comment]
Hi @cmayfield Thanks for writing up this issue.  Do you have a testcase that shows the error so that when we can fix it we know whether it's fixed or not.  If you have the code to fix it can you also create a PR?
