### ISSUE TITLE
Liquibase 4.0.0 core - DB2 error - SQLCODE=-542

### ISSUE THREAD

**Issue by mironbalcerzak** [liquibase/liquibase#1375]
## Environment
**Liquibase Version**: 4.0.0

**Liquibase Extension(s) & Version**: hibernate5-ext

**Database Vendor & Version**: DB2 11.1

## Description
Liquibase fails to create unique constraint for DB2, causing error:

```
DB2 SQL Error: SQLCODE=-542, SQLSTATE=42831, SQLERRMC=RANDOMPROPERTY, DRIVER=4.25.13
```

Long story short, the reason for that is one of the columns referenced within constraint is nullable, and constraint should not be created but unique index instead.

Let's consider following scenario:
JPA entity

```
@Entity
@Table(name = "entity",
        uniqueConstraints = {
                @UniqueConstraint(columnNames = "id,randomproperty")
        }
)
public class Entity {
	@Id
        private Long id;
	@Column(nullable=true, length=40)
	private String randomproperty;
}
```

Liquibase will create table definition and...

```
<addUniqueConstraint columnNames="id,randomproperty" constraintName="UK1234567890" tableName="entity"/>
```

While generation of SQL for constraints, there should be additional check validating whether all columns used within constraint are ``NOT NULL``, if any of them is nullable, constraint should be replaced by UNIQUE INDEX (that's what hibernate is doing during DDL generation).

## Steps To Reproduce
1. generate changelog for mentioned entity
1. generate SQL for DB2 
1. enjoy the disaster

**Comment by molivasdat** [comment]
Thanks @mironbalcerzak for writing up this issue.  We will add it to the list of issues that we are processing.  If you have a fix for the code you can submit a PR and will process that as well.

**Comment by raulsoledispa** [comment]
@molivasdat Do can You to assign me for to contribute in resolve issue?

**Comment by molivasdat** [comment]
I have assigned you to fix this issue @raulsoledispa

**Comment by raulsoledispa** [comment]
@molivasdat Thank.
Can you  update the label from **_Hacktoberfest_** to **_hacktoberfest_**?

**Comment by molivasdat** [comment]
Hi @raulsoledispa . Updated.

**Comment by raulsoledispa** [comment]
@molivasdat Thank

**Comment by mironbalcerzak** [comment]
Hey all, just checking - any updates here?

**Comment by tati-qalified** [comment]
Hello @mironbalcerzak, sorry for the late response.

This is actually not a Liquibase problem, but a conceptual/DB2 problem: DB2 won't allow you to create a unique or primary key index if one of the columns is nullable. Even if Liquibase and Hibernate created the correct SQL syntax, DB2 would raise an error.

I'll be closing this ticket as we can't do anything that would fix the problem.
