### ISSUE TITLE
.sql format changelog only executes the first changeset on sqlite database

### ISSUE THREAD

**Issue by Daniel-Bertagnolli** [liquibase/liquibase#1387]
## Environment
**Liquibase Version**: 3.10.2 (also happens on 4.0.0)

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**:  //

**Database Vendor & Version**: SQLite3 version 3.27.2

**Operating System Type & Version**: debian 10.3

## Description
When executing a changelog file in .sql format, only the first changeset in the file gets executed on the DB

## Steps To Reproduce
Install Liquibase via command line and install the sqlite JDBC.

Create your `changelog.sql` file: 

```
--liquibase formatted sql

--changeset your.name:1
create table person (
    id int primary key,
    name varchar(50) not null,
    address1 varchar(50),
    address2 varchar(50),
    city varchar(30)
);

--changeset your.name:2
create table company (
    id int primary key,
    name varchar(50) not null,
    address1 varchar(50),
    address2 varchar(50),
    city varchar(30)
);

--changeset other.dev:3
alter table person add column country varchar(2);
```

Configure your liquibase.properties file 

```
changeLogFile=test.sql
url=jdbc:sqlite://home/username/liquibase/examples/sqlite-test/testdb
```

launch `liquibase update`

## Actual Behavior
The update completes without errors, but when checking the database only the first changelog is executed. Keeping the above file the result in sqlite3 is this: 

```
sqlite> .tables
DATABASECHANGELOG      DATABASECHANGELOGLOCK  person

sqlite> .schema person
CREATE TABLE person (
    id int primary key,
    name varchar(50) not null,
    address1 varchar(50),
    address2 varchar(50),
    city varchar(30)
);
```

## Expected/Desired Behavior
All the changesets in the changelog have to be executed on the database

## Additional Context
So far the only workaround of this issue is to set a single changeset in each changelog file

**Comment by Daniel-Bertagnolli** [comment]
I think I might have an update on this bug report. I've kept working and trying to understand what is going on. Starting with trying to replicate my current production DB schema. So I've copied it into a temporary folder, created my `liquibase.properties` file
```
url=jdbc:sqlite://home/username/liquibase/examples/bugtesting/prodDB
```

and ran `liquibase --changeLogFile=createdFinal.sql generateChangeLog`

which returns me a few BEST PRACTICE lines and an error: 
```
Unexpected error running Liquibase: java.lang.RuntimeException: liquibase.exception.UnexpectedLiquibaseException: Serializing changelog as sql requires a file name in the format *.databaseType.sql. Example: changelog.h2.sql. Passed: productionSchema.sql
```
Which is telling me that I have to put the DB type in the filename, something that I've not found in the documentation. So I run `liquibase --changeLogFile=productionSchema.sqlite.sql generateChangeLog` and the changeLog file gets created correctly. 

```
--liquibase formatted sql

--changeset root:1599724913976-1
CREATE TABLE phone_numbers (quick_dial TEXT, full_number TEXT, name TEXT, surname TEXT);

--changeset root:1599724913976-2
CREATE TABLE phonebook_entry (name TEXT, surname TEXT, type TEXT, number TEXT, notes TEXT, searchString TEXT);

--changeset root:1599724913976-3
CREATE TABLE user_options (user_id INTEGER, max_records INTEGER, last_login TEXT, ari_available_phones TEXT);

--changeset root:1599724913976-4
CREATE TABLE users (username TEXT, password TEXT);

```

I then go into the `liquibase.properties` file and change the database name to `prodDB_new`, save it and run `liquibase --changeLogFile=productionSchema.sqlite.sql update` to recreate my production schema on the new database, it gets executed flawlessy.

```
sqlite> .tables
DATABASECHANGELOG      phone_numbers          user_options         
DATABASECHANGELOGLOCK  phonebook_entry        users                
sqlite> 
```
Now, if I go back to the schema sql file and remove the `--liquibase formatted sql` on top, delete the `prodDB_new` database and run again the above liquibase update command only the first sql statement gets executed on the DB 

```
sqlite> .tables
DATABASECHANGELOG      DATABASECHANGELOGLOCK  phone_numbers        
sqlite> 
```

Now, this could be a "minor" issue but then, when I tried to set up a single changelog master file and multiple .sql changelogs to be executed automatically ( [I used this guide](https://www.liquibase.org/blog/liquibase-without-changelogs) ) I've noticed that if the sql files have the `--liquibase formatted sql` they don't get executed at all, and if they don't have it, only the first statement of each file gets executed on the DB. I'm not sure if I should open another issue for this other problem, in case let me know

**Comment by molivasdat** [comment]
Hi @Daniel-Bertagnolli Thanks for writing up this issue.  From this updated comment it sounds like this is an issue to update the documentation to show that databasetype.sql should be in the name of the changelog file.  Will that fix your issue?

**Comment by Daniel-Bertagnolli** [comment]
Hi @molivasdat yes, that'll fix the issue, now with the correct filenames everything seems to run smoothly on my end, both Liquibase 3.10.2 and 4.0.0
