### ISSUE TITLE
Precision INT,BigInt in mysql

### ISSUE THREAD

**Issue by ajsobrinomin** [liquibase/liquibase#1398]
## Environment: WIndows
**Liquibase Version**: 4.0.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: mysql 8.0

**Operating System Type & Version**:

## Description
I have a problem, I write different precision for bigint or int in mysql, then I execute my changeset and always liquibase execute the same preccision 20 for bigint and 11 for int.

## Steps To Reproduce
List the steps to reproduce the behavior.

* Please be precise and ensure private information is redacted
* Include things like
  * Files used - sql scripts, changelog file(s), property file(s), config files, POM Files
  * Exact commands used - CLI, maven, gradle, spring boot, servlet, etc.

## Actual Behavior
A clear and concise description of what happens in the software **before** this pull request.

* Include console output if relevant
* Include log files if available.

## Expected/Desired Behavior
A clear and concise description of what happens in the software **after** this pull request.

**Comment by molivasdat** [comment]
Hi @ajsobrinomin 
Thanks for submitting your issue.  Can you add a sample changeset that is failing to the description section? and the expected behavior?

**Comment by ajsobrinomin** [comment]
Of Course, I attach in this comment a example of changeset.

<changeSet author="ajsobrino" id="V3.0.0-table-7">
		<createTable
			remarks="This entity saves the history of a questionnaire."
			tableName="DAT_QUESTIONNAIRE_HISTORY"
			tablespace ="${tablespaceTable}">
			<column name="IDX_ID" remarks="Primary key" type="BIGINT(9)">
				<constraints nullable="false" primaryKey="true"
					primaryKeyName="DAT_QUESTIONNAIRE_HIST_PK" />
			</column>
			<column name="DAT_NAME" type="varchar(50 BYTE)">
				<constraints nullable="false" />
			</column>
		</createTable>
	</changeSet>

For example in that example the primary of table have a bigint but Liquibase always take the same precision for BIGINT that is 18, the problem is the same with other number type in mysql for examlple smallint has six like precision.
Also I would like to participate in the project like developer that if you want.

**Comment by molivasdat** [comment]
Hi @ajsobrinomin .  BIGINT(18) is just a hint for zerofill.  It does nothing with regards to precision.
See

https://stackoverflow.com/questions/3135804/types-in-mysql-bigint20-vs-int20
and 
https://dev.mysql.com/doc/refman/8.0/en/integer-types.html

**Comment by ecarneiro01** [comment]
Hi @ajsobrinomin, I think the question you had is cleared in the previous comment. 

Anyways, integer display width is deprecated and will be removed in future MySQL releases, the same goes for zerofill. In case you need to store numbers in a certain format you can store them in a CHAR column or use the LPAD function to zero-pad numbers.

I'm closing this ticket but feel free to reach out to us if you have any issues.
