### ISSUE TITLE
ConcurrentModificationExecption when updating multiple schema's in parallel

### ISSUE THREAD

**Issue by robinvandenbogaard** [liquibase/liquibase#1402]
## Environment
Wildfly 20.0.1

**Liquibase Version**: 4.0.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
maven

**Liquibase Extension(s) & Version**: 
hibernate

**Database Vendor & Version**:
postgres

**Operating System Type & Version**:
various

## Description
We're updating multiple schema's in parallel as soon as two threads attempt to start updating their respective schema. A ConcurrentModificationExecption occurs.

```
! java.util.ConcurrentModificationException: null
! at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
! at liquibase.executor.ExecutorService.getExecutor(ExecutorService.java:93)
! at liquibase.database.AbstractJdbcDatabase.getConnectionSchemaName(AbstractJdbcDatabase.java:359)
! at liquibase.database.AbstractJdbcDatabase.getDefaultSchemaName(AbstractJdbcDatabase.java:324)
! at liquibase.changelog.ChangeLogParameters.<init>(ChangeLogParameters.java:61)
! at liquibase.Liquibase.<init>(Liquibase.java:109)
```

## Additional Context
Same problem reported on the forums:
https://forum.liquibase.org/t/liuibase-executor-executorservice-is-not-threadsafe/4472

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-671) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
Thanks @robinvandenbogaard for submitting this issue and the PR to fix it.  We will add it to our queue of issues to review.

**Comment by zhoujia1974** [comment]
@robinvandenbogaard I'm the one report the same bug in the forum. Thank you for helping to fix the bug. Could you please help to submit a PR against 3.10.x branch?

**Comment by robinvandenbogaard** [comment]
@zhoujia1974 someone else made a 3.10 PR here: https://github.com/liquibase/liquibase/issues/1456
