### ISSUE TITLE
liquibase.sqlplus.path line in liquibase/examples/xml/liquibase.sqlplus.conf should be commented out

### ISSUE THREAD

**Issue by szandany** [liquibase/liquibase#1416]
## Environment
Win, Unix
**Liquibase Version**:
3.10.2, 4.0.0
**Liquibase Integration & Version**: CLI

## Description
In the liquibase install folder the file liquibase/examples/xml/liquibase.sqlplus.conf contains a the line: "liquibase.sqlplus.path=/apps/app/12.2.0.1.0/oracle/product/12.2.0.1.0/client_1/bin/sqlplus" should be commented out to avoid getting an error indicating that sqlplus cannot be found in path...

## Steps To Reproduce
Run liquibase with a runWith changeSet from liquibase/examples/xml

## Actual Behavior
Error will occur indicating that sqlplus path cannot be found. 

## Expected/Desired Behavior
The line "liquibase.sqlplus.path" should be commented out, and another line example should be provided for windows example with the "//" escape characters as a comment.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-689) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Community 4.3.2,Liquibase 4.3.2

**Comment by malathit** [comment]
Please check the PR #1448 and see if the changes are okay.
