### ISSUE TITLE
IncludeAll documentation mysterious

### ISSUE THREAD

**Issue by ari** [liquibase/liquibase#1426]
Documentation here https://docs.liquibase.com/concepts/advanced/includeall.html suggests that include all will fail in mysterious ways when used like Rails with one changeset per file.

If includeAll is deprecated, then it should be marked as such. If it doesn't work in some situations, then this needs to be explained with less mystery. I'm not sure what danger I'm supposed to be avoiding here.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-700) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
Hi @ari Thanks for alerting us to this issue.  You can create an issue on our docs site and even make a PR and update the docs yourself there.  Please open an issue [here](https://github.com/Datical/liquibase-docs) instead.
