### ISSUE TITLE
Can I config my liquibase.properties with envionment variables

### ISSUE THREAD

**Issue by dazuimao1990** [liquibase/liquibase#1428]
## Environment
**Liquibase Version**:
4.0.0 
**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
docker
**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

**Operating System Type & Version**:

## Description
This is not a bug,But I don't know where to ask.

I wrote down the specific problem here

https://github.com/liquibase/docker/issues/36

Please pay attention to this suggestion.Tks

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-702) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
Hi @dazuimao1990 Thanks for asking the question.  There is a feature request to do that in  #1179 that has not been addressed yet.  Please add your vote to that one.
