### ISSUE TITLE
createSequence for PostgreSQL <10 doesn't work because [AS] syntax is not supported

### ISSUE THREAD

**Issue by KushnirykOleh** [liquibase/liquibase#1429]
## Environment
**Liquibase Version**: 4.0.0

**Liquibase Integration & Version**: maven

**Database Vendor & Version**: postgresql 9 running in docker container from dockerHub

**Operating System Type & Version**: macOS Catalina 10.15.6

## Description
for createSequence with xml changeLog file Liquibase uses [AS] syntax when generating SQL. This is not supported by PostgreSQL prior to 10th version
https://docs.liquibase.com/change-types/community/create-sequence.html
https://www.postgresql.org/docs/9.6/sql-createsequence.html vs https://www.postgresql.org/docs/10/sql-createsequence.html

## Steps To Reproduce
clone https://github.com/liquibase/liquibase-test-harness
run ChangeObjectsTest from IDE as JUnit test or from cmd

`mvn failsafe:integration-test -DchangeObjects=createSequence -DinputFormat=xml`
 however input in sql format without `AS int` works
`mvn failsafe:integration-test -DchangeObjects=createSequence -DinputFormat=sql`

or just create xml changeLog with following
`<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
         http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd">

```
<changeSet author="oleh" id="1">
    <createSequence dataType="int"
                    incrementBy="1"
                    minValue="1"
                    schemaName="public"
                    sequenceName="test_sequence"
                    startValue="1"/>
    <rollback>
        <dropSequence sequenceName="test_sequence"/>
    </rollback>
</changeSet>
```

</databaseChangeLog>`
and run it agains DB with enough access rights for creating sequences

## Actual Behavior
for postgreSQL <10 it is
`CREATE SEQUENCE  IF NOT EXISTS public.test_sequence AS int START WITH 1 INCREMENT BY 1 MINVALUE 1`

## Expected/Desired Behavior
`CREATE SEQUENCE  IF NOT EXISTS public.test_sequence START WITH 1 INCREMENT BY 1 MINVALUE 1`

**Comment by kristyldatical** [comment]
FYI @r2liquibase, this is another bug that was surfaced by the test-harness

**Comment by molivasdat** [comment]
Hi @KushnirykOleh Thanks for writing up this issue.  Since 9.5 and 9.6 are the only versions of 9 currently supported by Postgres this would apply to those versions only at this time.
Code change required here in CreateSequenceGenerator
```
if (database instanceof HsqlDatabase || database instanceof Db2zDatabase) {
            queryStringBuilder.append(" AS BIGINT ");
        } else if (statement.getDataType() != null) {
            queryStringBuilder.append(" AS " + statement.getDataType());
```
