### ISSUE TITLE
Status does not throw an error if 2 or more IDENTICAL changeSets exist in the same changeLog

### ISSUE THREAD

**Issue by szandany** [liquibase/liquibase#1432]
## Environment
**Liquibase Version**: 3.6.0, 3.6.2, 3.6.2, 3.7.0, 3.8.0, 3.8.1, 3.8.4, 3.8.7, 3.10.2, 4.0.0

**Liquibase Integration & Version**: CLI

**Database Vendor & Version**: Oracle, MySQL, PostgreSQL, SQL Server.

**Operating System Type & Version**: Windows, Linux, MacOS

## Description
1. If there are two or more identical changeSets in the same changeLog, then the first changeSet will be considered and the rest will be ignored.
1. If any of the other changeSets (besides the first one) checksum gets changed, then the error with the “multiple identifiers” will be thrown for that specific changeSet.

## Steps To Reproduce
1. Create a changeLog (any format) with two identical changeSets:
MySQL example: 
**Formatted SQL changeLog**

```
--liquibase formatted sql

--changeset SteveZ:45555-createtablecontacts context:tesing labels:sprint100
CREATE TABLE contacts (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,firstname VARCHAR(255),lastname VARCHAR(255));
--rollback drop table contacts;

--changeset SteveZ:45555-createtablecontacts context:tesing labels:sprint100
CREATE TABLE contacts (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,firstname VARCHAR(255),lastname VARCHAR(255));
--rollback drop table contacts;
```

1. Run: `liquibase status --verbose`
1. Run: `liquibase update`
1. Run: `liquibase status --verbose`

## Actual Behavior
1. After running the `liquibase status --verbose` command, liquibase will show only **1** "undeployed pending changeSet".  Also, the command will run successfully without any errors.
1. After running the `liquibase update` command, liquibase will show the message "Update has been successful."
1. After running the `liquibase status --verbose` command, Liquibase will show the message: "<JDBC connection string> is up to date.  Liquibase command 'status' was executed successfully."
1. The additional duplicate changeSet gets ignored.

## Expected/Desired Behavior
When running `liquibase status --verbose` for the first time, Liquibase should have thrown the following error: 

`"1 change sets had duplicate identifierschangelog.postgresql.sql::45555-createtablecontacts::SteveZ"`

## Additional Context
If the second duplicate changeSet's checksum gets changed, the following error gets triggered:

`Unexpected error running Liquibase: Validation Failed:1 change sets check sumchangelog.postgresql.sql::45555-createtablecontacts::SteveZ was: 8:762f4f2f9b31cb411865bace78aa42b3 but is now: 8:2c82bdbc04392afd252b4235a638237b1 change sets had duplicate identifierschangelog.postgresql.sql::45555-createtablecontacts::SteveZ`

**Comment by FBurguer** [comment]
Still an issue for liquibase `4.16.1`.

**Comment by lbadam** [comment]
I have tested this issue with 4.29.1 and duplicate changes will cause errors when running both `status` and `update`.

With `liquibase status`: 

```
Liquibase Version: 4.29.1
Liquibase Open Source 4.29.1 by Liquibase
ERROR: Exception Details
ERROR: Exception Primary Class:  ValidationFailedException
ERROR: Exception Primary Reason:  Validation Failed:
     1 changesets had duplicate identifiers
         example_changelog.sql::add-something::lbadam

ERROR: Exception Primary Source:  4.29.1

Unexpected error running Liquibase: Validation Failed:
     1 changesets had duplicate identifiers
          example_changelog.sql::add-something::lbadam

For more information, please use the --log-level flag
```

With `liquibase update`: 

```
Liquibase Version: 4.29.1
Liquibase Open Source 4.29.1 by Liquibase
ERROR: Exception Details
ERROR: Exception Primary Class:  ValidationFailedException
ERROR: Exception Primary Reason:  Validation Failed:
     1 changesets had duplicate identifiers
          example_changelog.sql::add-something::lbadam

ERROR: Exception Primary Source:  4.29.1

Unexpected error running Liquibase: Validation Failed:
     1 changesets had duplicate identifiers
          example_changelog.sql::add-something::lbadam

For more information, please use the --log-level flag
```
