### ISSUE TITLE
XML Export adds ',xxx' instead of ','

### ISSUE THREAD

**Issue by kuhjunge** [liquibase/liquibase#1438]
## Environment
**Liquibase Version**:  4.1

**Liquibase Integration & Version**: gradle

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: any 

**Operating System Type & Version**: Win10, Java8

## Description
If you add two dbms to a changeset, it seperates them with ',xxx' instead of ','. Therefore the second dbms will not be correctly recognized.

 `<changeSet  dbms="oracle,xxxmssql" ... >`

## Steps To Reproduce
JUnit-Test to reproduce: 

```
  @Test
  void testLiquibaseXmlBug() throws IOException {
    ByteArrayOutputStream stream = new ByteArrayOutputStream();
    DatabaseChangeLog log = new DatabaseChangeLog();
    ChangeLogSerializer serializer = new XMLChangeLogSerializer();
    ChangeSet set = new ChangeSet("Test", "test", Boolean.FALSE, Boolean.FALSE, null, "context", "oracle, mssql",log);
    List<ChangeLogChild> changes = new ArrayList<>();
    changes.add(set);
    serializer.write(changes, stream);
    assertEquals("<?xml version=\"1.1\" encoding=\"UTF-8\" standalone=\"no\"?>"
                 + "<databaseChangeLog xmlns=\"http://www.liquibase.org/xml/ns/dbchangelog\" xmlns:ext=\"http://www.liquibase.org/xml/ns/dbchangelog-ext\" xmlns:pro=\"http://www.liquibase.org/xml/ns/pro\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-4.1.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.1.xsd\">"
                 + "    <changeSet author=\"test\" context=\"context\" dbms=\"oracle,mssql\" id=\"Test\" objectQuotingStrategy=\"LEGACY\"/>"
                 + "</databaseChangeLog>", new String(stream.toByteArray()));
  }
```

## Expected/Desired Behavior
Changelog should look like: 
 `<changeSet  dbms="oracle,mssql" ... >`

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-733) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 4.2.0

**Comment by molivasdat** [comment]
Hi @kuhjunge Thanks for taking the time to write up this issue.  And the detailed reproduction steps are definitely helpful.  We will add it to our list of issues to process.

**Comment by p1729** [comment]
@molivasdat I would like to contribute on this

**Comment by molivasdat** [comment]
@p1729 Excellent.  I have assigned it to you to create a PR.  Thanks for the help.
