### ISSUE TITLE
IncludeAll missing important things when executing with jdbc

### ISSUE THREAD

**Issue by gonzalowtf** [liquibase/liquibase#1444]
Hello , I'm using liquibase in a spring boot project , and trying to run scripts with the includeAll option works fine , but there are couple of things that i think it will make it much better : 

1.  When you want to check a status of a database before running some sctipr , you may want to run a select "first" and then after the script execution run another select "Before" for example in the same execution.   there is some possibility to perfrom a select statement and see it results on jdbc ?
1. Another thing to mention , is the usefull option "failOnError" that may be false in ChageSets , which is excelent in the cases you don't want liquibase to stop executing when error in sql appears , saddly it seems that is no possible to add this option in the tag <includeAll  path="com/example/changelogs/"    failOnError=false   /> , is there any way to do this ?

Also , none of those are issues but i didn't find anything about them on the web , so please if this is inappropriate feel free to delete it.

Thank you.

**Comment by molivasdat** [comment]
Hi @gonzalowtf There are attributes called preconditions that may meet your needs.
[https://docs.liquibase.com/concepts/advanced/preconditions.html](https://docs.liquibase.com/concepts/advanced/preconditions.html)
For the second question, can you elaborate a little more?
If I understand correctly, you want to have an includeAll changeset that runs no matter what errors occur in the scripts?
This might have consequences on script ordering as well.
