### ISSUE TITLE
ExecutorService is not threadsafe - getExecutor can be called concurrently

### ISSUE THREAD

**Issue by tandr** [liquibase/liquibase#1455]
We are getting hit by the same issue this thread https://forum.liquibase.org/t/liuibase-executor-executorservice-is-not-threadsafe/4472 is describing, albeit only in flooding tests.

The line https://github.com/liquibase/liquibase/blob/4cd5bcb57e6963b9b18632d2b64bac9c33eb1e95/liquibase-core/src/main/java/liquibase/executor/ExecutorService.java#L15
should be using `ConcurrentHashMap<>`

We get crashes on concurrent test with just 8 threads.

Re: https://github.com/liquibase/liquibase/pull/866

I will try to add an one-liner (well, 2) PR

**Comment by molivasdat** [comment]
Thanks @tandr for writing up this issue and referencing the fix.  We will take a look at adding this to our list of issues to process.

**Comment by teob85** [comment]
We have the same issue, please merge the fixes

**Comment by kataggart** [comment]
This has been addressed via https://github.com/liquibase/liquibase/pull/1403. We do not have plans to backport it into older versions and recommend upgrading. Thanks.
