### ISSUE TITLE
ColumnSnapshotGeneratorInformix.readDataType() wrongly sets colLength value with column size (for informix DATETIME datatype)

### ISSUE THREAD

**Issue by ChairwaKKa** [liquibase/liquibase#1462]
## Environment
**Liquibase Version**: 4.1.0

**Liquibase Integration & Version**: apache-maven 3.3.9

**Liquibase Extension(s) & Version**: none

**Database Vendor & Version**: IBM Informix Dynamic Server Version 11.70.FC5W1GE

**Operating System Type & Version**: Red Hat Enterprise Linux Server release 7.8 (Maipo)

## Description
I run a jar on the target system which executes the update() method of the liquibase.Liquibase class on the Informix target database.
While validating the datatypes, the program stumbles over the datatype DATETIME.
When determining the qualifiers, as described at https://www.ibm.com/support/knowledgecenter/SSGU8G_11.50.0/com.ibm.sqlr.doc/ids_sqr_027.htm, an exception occurs.

To determine the qualifier the collength value of the respective column is needed.
In Informix databases this value is stored in the table 'syscolumns' in the column 'collength'.
The method ColumnSnapshotGeneratorInformix.readDataType() incorrectly sets the column size in the variable colLenght. 
In my case the column size 25 of the column with the datatype 'DATETIME YEAR TO FRACTION (5)' was used instead of the actual collength of 4879.

## Steps To Reproduce
I have integrated liquibase via maven dependency.
Then I wrote a test class to make use of the liquibase update method.

```
try(Connection connection = DriverManager.getConnection( informixURL, informixUser, informixPw )) {
			JdbcConnection jdbcConn = new JdbcConnection(connection);
			InformixDatabase database = (InformixDatabase)DatabaseFactory.getInstance().findCorrectDatabaseImplementation(new JdbcConnection(connection));
			database.setDefaultSchemaName("master");
			
			ResourceAccessor resourceAccessor = new ClassLoaderResourceAccessor();
		       Liquibase liquibase = new Liquibase( "path/to/changelog", resourceAccessor, database);                 	
		       liquibase.update(new Contexts());       
```

## Actual Behavior
When running the jar I get the following error message:
`liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.DatabaseException: Encountered unknown firstQualifier code (1) for column 'master.databasechangelog.dateexecuted', basic date type 'DATETIME', while trying to decipher information encoded in the column length (25)`

In line 56 of the java class ColumnSnapshotGeneratorInformix the columnMetadataResultSet.getInt("COLUMN_SIZE") is wrongly set to the colLength  variable which leads to the exception above,

## Expected/Desired Behavior
The colLength variable should be set with the actual collength value for the certain column.
This value can be found in the system table 'syscolumns'.
In my case for the 'dateexecuted' column of the table databasechangelog.
`SELECT collength FROM syscolumns WHERE tabid = (SELECT tabid FROM systables WHERE tabname = "databasechangelog") AND colname = "dateexecuted"; `

**Comment by molivasdat** [comment]
Hi @ChairwaKKa Thank you for creating this issue.  We are going to add it to our list of issues to process.

**Comment by kevin-atx** [comment]
@tati-qalified - could you use the Liquibase CLI to test the DATETIME datatype to see if it's supported?

**Comment by tati-qalified** [comment]
Hello @ChairwaKKa, sorry for the late reply.
This issue has been reported before, around the time when you reported it, with a similar Informix version. Neither of those versions are available anymore, as they've been deprecated and taken down by IBM. I haven't been able to reproduce this bug with any available Informix version, so I'll be closing the ticket.
If you or anyone else faces this problem again, feel free to let me know and I'll reopen it.
Thank you,
Tatiana

**Comment by alvescarlos** [comment]
Hello @tati-qalified 
I'm experiencing the exact some error on IBM Informix Dynamic Server Version 14.10.FC9. I first got the error using Liquibase 4.27.0 Maven plugin, but it also happens with the latest 5.0.3.
If I can be of any assistance, please feel free to get in touch.
Thanks.

UPDATE: Updating the IBM Informix JDBC driver to version 4.50.13.1 has solved the error. I was using version 4.10.JC1.
