### ISSUE TITLE
Consider alternative location for banner.txt

### ISSUE THREAD

**Issue by snicoll** [liquibase/liquibase#1476]
A maintenance release of liquibase added a `banner.txt` at the root of the classpath (see 5e557a5c7999a3c91fc635a82712427421ad845a). 

Could you please consider an alternative location for this resource? I am working on the Spring Boot project and we use this location for users that wants to use an alternative banner when starting their apps. Arguably, our default isn't great either and we should probably fix it.

Thank you.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-819) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 4.2.0

**Comment by nvoxland** [comment]
Thanks for the reminder. We'll move it

**Comment by r2liquibase** [comment]
Whoops. Stray click!!! Repopend.

**Comment by timurt** [comment]
Hello, I am first time here and I wanted to contribute to this project as part of `hacktoberfest` event. 

Scope of this issue is to move `banner.txt` to some subfolder inside `resources` folder and make sure that banner is being printed, am I right?

**Comment by molivasdat** [comment]
Hi @timurt Thanks for the signup.  I added you to the assignee list.  Thanks for contributing.

**Comment by marwin1991** [comment]
Hello, can you also fix it in 3.10.X ??
