### ISSUE TITLE
www.liquibase.org Domain has expired

### ISSUE THREAD

**Issue by AtulDwivedi** [liquibase/liquibase#1488]
## Description
www.liquibase.org Domain has expired. Please renew it.

## Steps To Reproduce
* Visit www.liquibase.org

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-834) by [Unito](https://www.unito.io/learn-more)

**Comment by mschaaf** [comment]
This is critical to our application because it fails to start with `Caused by: org.xml.sax.SAXParseException: Open quote is expected for attribute "data-adblockkey" associated with an  element type  "html".`

**Comment by pavleprica** [comment]
Standing in line as well, an issue such as this is very critical, even on Sunday. It seems it's only the domain renewal problem. Please advise on it and if something else is going on.

**Comment by atomitl** [comment]
It's failing to read 'pro' schemas on startup: ` xmlns:pro="http://www.liquibase.org/xml/ns/pro" http://www.liquibase.org/xml/ns/pro/liquibase-pro-3.8.xsd`

Gets a "Moved Permanently" redirect instead and parse fails. 

`[org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.ChangeLogParseException: liquibase.exception.SetupException: Error parsing line 1 column 93 of changelog/initial.xml: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw 'Moved Permanently'`

Other schemas and namespaces seem to be still working somehow.

**Comment by PawelBialek98** [comment]
Hi, I found a temporary solution xD
There was no `http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.9.xsd` file in our project, but i found it after changing from .org to .com -  then I downloaded the file and in the xml file I changed schemaLocation to a local path to the file. It worked for me

**Comment by Nourhan-Hesham** [comment]
you can download file from 
https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd

**Comment by Nourhan-Hesham** [comment]
you can download changelogs files version from here **https://github.com/liquibase/liquibase/tree/master/liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog**

and and referring to it locally (relative path)
```
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog **dbchangelog-3.1.xsd**">
</databaseChangeLog>
```

**Comment by molivasdat** [comment]
This has been resolved.

**Comment by ssserebrov** [comment]
http://www.liquibase.org/xml/ns/dbchangelog dbchangelog-3.1.xsd - **page not found**

**Comment by ssserebrov** [comment]
https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.0.xsd - **page not found**

**Comment by molivasdat** [comment]
Thanks for letting us know.  We have updated the domain registration to fix this issue.
