### ISSUE TITLE
CreateIndexGeneratorFirebird generates invalid SQL on computed field

### ISSUE THREAD

**Issue by Markus-Patt** [liquibase/liquibase#1490]
**Liquibase Version**:
4.1.1

**Database Vendor & Version**:
Firebird 2.5
Firebird 3

## Description
A clear and concise description of the issue being addressed.

* Adding an index on a "computed by" value generates invalid sql

## Steps To Reproduce
```xml
    <changeSet id="1" author="1">
        <createTable tableName="foo">
            <column name="id" type="INT">
                <constraints nullable="false" primaryKey="true" primaryKeyName="PK_foo" />
            </column>
            <column name="bar" type="INT" />
        </createTable>
    </changeSet>

    <changeSet id="2" author="2">
        <createIndex tableName="foo" indexName="idx_bar">
            <column name="bar + 1" computed="true" />
        </createIndex>
    </changeSet>
```

This creates the following sql:

```sql
CREATE INDEX idx_baz ON fooCOMPUTED BY (baz + 1)
```

which misses a space between the table name an the the keyword "computed"

**Comment by molivasdat** [comment]
Hi @Markus-Patt Thanks for writing up this issue.  And thanks for creating a PR to fix it as well.  We will look at incorporating it into a release soon.

**Comment by FBurguer** [comment]
Still an issue for liquibase `4.16.1`
