### ISSUE TITLE
Does liquibase java 11 support(with module-info.java)

### ISSUE THREAD

**Issue by bogomolov-a-a** [liquibase/liquibase#1505]
## Environment
**Liquibase Version**: 3.8.9

**Liquibase Integration & Version**: spring boot 2.3.4

**Liquibase Extension(s) & Version**:  no

**Database Vendor & Version**:  sqlite 3

**Operating System Type & Version**: ubuntu 20.04

## Description
I try to use  liquibase(3.8.9) & spring boot( 2.3.4) integration with modularity project structure. java 11.
I expect ordinary behavior (my changeset commit to db), but I obtain this error 

```
Error occurred during initialization of boot layer
java.lang.module.FindException: Unable to derive module descriptor for /home/artembogomolova/.m2/repository/org/liquibase/liquibase-core/3.8.9/liquibase-core-3.8.9.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Provider class com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule not in module

Process finished with exit code 1
```

Can I use my spring boot application with modularity project structure(with module-info) and liquibase?

## Steps To Reproduce
List the steps to reproduce the behavior.
project: https://github.com/bogomolov-a-a/demo-spring-simple-webapp-with-tls
branch: module-info-branch
mvn clean package -DskipTests=true
run jar.

## Actual Behavior
After run obtain error:

```
Error occurred during initialization of boot layer
java.lang.module.FindException: Unable to derive module descriptor for /home/artembogomolova/.m2/repository/org/liquibase/liquibase-core/3.8.9/liquibase-core-3.8.9.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Provider class com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule not in module

Process finished with exit code 1
```

## Expected/Desired Behavior
I expect ordinary behavior (my changeset commit to db).

## Screenshots (if appropriate)
no

## Additional Context
no

**Comment by molivasdat** [comment]
Hi @bogomolov-a-a Thanks for creating this issue.  Yes we do support java 11.  This may be something specific to java 11.  We will add it to the issues we are processing.

**Comment by nvoxland** [comment]
This has been fixed in newer versions of liquibase. Adding `<version>4.4.1</version>` to your pom.xml for the liquibase dependency makes the error go away.

It's just that the spring default version of liquibase is quite old. We'll work with them on getting it updated, but in the mean time you can force the newer liquibase version if you'd like.
