### ISSUE TITLE
Regression: StackOverflowError processing large Postgres SQL changeset

### ISSUE THREAD

**Issue by goostleek** [liquibase/liquibase#1507]
## Environment
**Liquibase Version**: `4.1.1`

**Liquibase Integration & Version**: Spring Boot

**Database Vendor & Version**: Postgres 12.3

**Operating System Type & Version**: Ubuntu 20.04

## Description
There's a regression after upgrading from `4.1.0` to `4.1.1` that is causing `StackOverflowError` while generating Postgres statement during processing a large SQL file-based changeset.  It seems to be a regression
introduced in #912  while trying to fix [CORE-3379](https://liquibase.jira.com/browse/CORE-3379).

## Steps To Reproduce
Create a changeset:

```xml
<changeSet id="StackOverflowError" author="goostleek">
    <sqlFile path="large.sql" relativeToChangelogFile="true"/>
</changeSet>
```

The `sqlFile` is ~200kb. It's been included in [the file](https://github.com/liquibase/liquibase/blob/2bb6acad174723e770f43411fbeae2a68e2af691/liquibase-core/src/test/resources/liquibase/change/long-statement.sql) in the PR #1508 which introduces a failing unit test presenting the error.

## Actual Behavior
`StackOverflowError` is thrown during SpringBoot application startup while applying the changest.

## Expected/Desired Behavior
The changeset is executed successfully like it was before upgrading to Liquibase 4.1.1.

## Additional Context
See #912, #1508

**Comment by molivasdat** [comment]
Hi @goostleek Thanks for bringing up this issue to our attention.  And thanks for recreation scenario and unit test.  It definitely helps.  We will add it to the list of issues that we are processing.

**Comment by chtibob69** [comment]
Hi,
I'm experiencing it too... while updating SpringBoot from 2.3.x (liquibase-core 3.8.9) to 2.4.7 (liquibase-core 3.10.3) or 2.5.1 (liquibase-core 4.3.5)

NOTE : If I downgrade liquibase-core to 3.10.2 with springboot 2.4.7 it works fine
It seem to impact liquibase-core versions **greather than 3.10.2** ... july 2020... 

Thanks fixing it... and I hope Spring Team will publish fix quickly too

**Comment by maksudsharif** [comment]
Any ETA on when this will be pushed out to repositories?

**Comment by molivasdat** [comment]
Hi @maksudsharif We are moving it through getting it into a release.  I don't have an ETA yet.  In the meantime, I would suggest using the workaround that @chtibob69 mentions.

**Comment by maksudsharif** [comment]
Just wanted to confirm that the solution by @chtibob69 resolves the issues for now. Cheers!
