### ISSUE TITLE
logFile doesn't have any logging content when used with 4.1.1

### ISSUE THREAD

**Issue by szandany** [liquibase/liquibase#1521]
## Environment
**Liquibase Version**:
4.1.1
**Liquibase Integration & Version**:
CLI
**Database Vendor & Version**:
Any
**Operating System Type & Version**:
Win/Linux

## Description
When the logFile property/flag is used with Liquibase 4.1.1, Liquibase will generate an empty file. 

## Steps To Reproduce
Run: 
"liquibase --logFile=myLog.log update"

## Actual Behavior
A new file will be created with no logging content.

## Expected/Desired Behavior
A new file will be created with logging content.

**Comment by XDelphiGrl** [comment]
@szandany , hello! If you specify --logLevel=FINE, do you get output to your log file then? Log level is off by default.

**Comment by szandany** [comment]
I think we need clarity as to what is the expected behavior when including the logFile property/flag with or without specifying the logLevel flag/property.

In previous versions of Liquibase, the logFile used to be by default on DEBUG verbosity level (without needing to include the logLevel flag/property).  
In 4.1.1 the log filelog is empty if we don't include --logLevel=FINE/DEBUG/INFO.
Also, logFile will be empty if we run it with --logLevel=SEVERE

**Comment by filipelautert** [comment]
After this discussion held in 2020 , new classes were introduced and now when you run "liquibase --help" you can find the following information:

```
      --log-level=PARAM
                             DEFAULT: Controls which logs get set to stderr AND
                               to any log file. The CLI defaults, if log file
                               set, to SEVERE. Others vary by integration. The
                               official log levels are: OFF, SEVERE, WARNING,
                               INFO, FINE
```

 @szandany , do you think this is enough to clarify liquibase behavior? If so we can close this issue.

**Comment by szandany** [comment]
Sure, I think that is much better now. I think that should suffice to resolve this issue.
