### ISSUE TITLE
Incorrect documentation link in the getting started guide for changelog files

### ISSUE THREAD

**Issue by rhowe** [liquibase/liquibase#1526]
## Description
In the [getting started guide](https://www.liquibase.org/get-started/how-liquibase-works), the link to `database changelog file` goes to the documentation for the [databasechangelog table](https://docs.liquibase.com/concepts/databasechangelog-table.html), but it should probably go to the documentation for the [changelog file formats](https://docs.liquibase.com/concepts/basic/changelog.html) instead.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-893) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
Thanks @rhowe Thanks for pointing this out.
This belongs in the docs repository.  Please reopen here:[https://github.com/Datical/liquibase-docs/issues](https://github.com/Datical/liquibase-docs/issues)

**Comment by rhowe** [comment]
Thanks - raised here https://github.com/Datical/liquibase-docs/issues/75
