### ISSUE TITLE
updateTestingRollback behaviour is different from doc

### ISSUE THREAD

**Issue by molleafauss** [liquibase/liquibase#1535]
## Environment
**Liquibase Version**: 3.8.9 (also observed on 3.5.3)
**Liquibase Integration & Version**: maven 3.6.3 and maven plugin 4.1.1
**Liquibase Extension(s) & Version**: 
**Database Vendor & Version**: MySQL 5.7 on Amazon Aurora
**Operating System Type & Version**: MacOs Catalina

## Description
[The documentaton for updateTestingRollback](https://docs.liquibase.com/tools-integrations/maven/commands/maven-updatetestingrollback.html) specifies that the changesets are tested in this order:

```
    update changeset1; rollback changeset1; update changeset1
    update changeset2; rollback changeset2; update changeset2
    update changeset3; rollback changeset3 update changeset3
```

Instead these are performed like:

* apply all migrations
* rollback all migration (in backward order w.r.t. how they were applied)
* apply all migrations

Execution log here:

```
[INFO] Executing on Database: jdbc:mysql:aurora://url/database
[INFO] Successfully acquired change log lock
[INFO] Creating database history table with name: DATABASECHANGELOG
[INFO] Reading from DATABASECHANGELOG
[INFO] Custom SQL executed
[INFO] ChangeSet src/main/resources/db/changelog/migrations/20201107_inital_schema.sql::20201107_01::name@email.com ran successfully in 143ms
[INFO] Custom SQL executed
[INFO] ChangeSet src/main/resources/db/changelog/migrations/20201113_migration.sql::20201113_01::name@email.com ran successfully in 90ms
[INFO] Successfully released change log lock
[INFO] Successfully acquired change log lock
[INFO] Reading from DATABASECHANGELOG
Rolling Back Changeset:src/main/resources/db/changelog/migrations/20201113_migration.sql::20201113_01::name@email.com
Rolling Back Changeset:src/main/resources/db/changelog/migrations/20201107_inital_schema.sql::20201107_01::name@email.com
[INFO] Successfully released change log lock
[INFO] Successfully acquired change log lock
[INFO] Reading from DATABASECHANGELOG
[INFO] Custom SQL executed
[INFO] ChangeSet src/main/resources/db/changelog/migrations/20201107_inital_schema.sql::20201107_01::name@email.com ran successfully in 345ms
[INFO] Custom SQL executed
[INFO] ChangeSet src/main/resources/db/changelog/migrations/20201113_migration.sql::20201113_01::name@email.com ran successfully in 85ms
[INFO] Successfully released change log lock
```

## Steps To Reproduce
Create a project with a changelog like this (we prefer using only SQL migrations) - YAML syntax

```
databaseChangeLog:
  - include: { relativeToChangelogFile: true, file: migrations/20201107_inital_schema.sql }
  - include: { relativeToChangelogFile: true, file: migrations/20201113_migration.sql }
```

## Actual Behavior
As shown above in Description.

## Expected/Desired Behavior
Either update documentation to reflect actual behaviour or update software to follow documentation.
Preferrable doing what documentation says, as multiple error in rollbacks are not easily discoverable this way and can cause trouble.

## Screenshots (if appropriate)
n/a

## Additional Context
n/a

**Comment by molivasdat** [comment]
Hi @molleafauss Thanks for writing up this issue.  I think this may be an issue with the documentation. 
We have a documentation repo here
[https://github.com/Datical/liquibase-docs/issues](https://github.com/Datical/liquibase-docs/issues)
Can you move the issue report over there?

**Comment by molleafauss** [comment]
Hi @molivasdat will do.
Although I was actually hoping that this would spark a conversation regarding the rollback testing, as I believe that the documentation is the correct way of applying and testing migrations and rollback.

Case in point: if during a run there are more than one migration with a wrong rollback, how liquibase is applying and rolling them back, it will cause this:
- only the last wrong rollback is discovered
- after fixing the wrong rollback and reapplying it, liquibase will see only the migrations from the last wrong rollback to apply, leaving the other wrong rollback lying in the code ready to break when you need to roll it back (say in staging or production?), causing also the added pain that the wrong rollback cannot be changed due to any change breaking the checksum.

Let me show you a real world example: imagine a set of 4 migrations: M_01, M_02, M_03, M_04.
M_02 and M_03 have a wrong rollback.
Running `upgradeTestingRollback` would do this:
1. apply - in order - M_01, M_02, M_03, M_04
1. rollback correctly M_04
1. fail to rollback M_03 and exit with an error.

the developer now fixes M_03, rolls it back manually, and then runs again `upgradeTestingRollback`, this is what liquibase does:
1. liquibase finds only M_03 and M_04 missing.
1. applies M_03 and M_04.
1. rolls back M_04 and M_03 (fine this time)
1. applies again M_03 and M_04
the wrong rollback of M_02 isn't discovered and will remain hanging in the code, potentially causing disruptions when an effetive rollback is needed.

If the documentation was followed, instead what would happen is:
1. liquibase would apply, rollback and apply M_01 fine
1. apply M_02 and fail rolling it back -> the developer will fix it first and make it apply
1. it will fail again at M_03, ensuring that all rollbacks are correct in the history.

**Comment by molivasdat** [comment]
Hi @molleafauss Thank you for the great explanation of why it should work that way.  This would be an enhancement request to change the way it works now.  I think the Enterprise version may work this way but I will have to check.

**Comment by FBurguer** [comment]
The documentation is having the same behavior as liquibase at this moment and we do think its useful as it is but the behavior @molleafauss explained in the comment sound like a good option for other cases. We will create a new issue to follow that behavior as a new option for the command. Thanks!
