### ISSUE TITLE
CockroachDatabase.isCorrectDatabaseImplementation has to check whether it is JdbcConnection otherwise fails with cast exception

### ISSUE THREAD

**Issue by alexandru-slobodcicov** [liquibase/liquibase#1536]
## Environment
**Liquibase Version**: 4.2.0

**Liquibase Integration & Version**: any

**Liquibase Extension(s) & Version**: liquibase-cosmosdb

**Database Vendor & Version**: Cosmos DB

**Operating System Type & Version**: Windows

## Description
By introducing the CockroachDatabase support

* isCorrectDatabaseImplementation method fails with cast exception when using a NoSql extension: java.lang.ClassCastException: liquibase.ext.cosmosdb.database.CosmosConnection cannot be cast to liquibase.database.jvm.JdbcConnection
* worth checking first that conn is instance of JdbcConnection and return false if not

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-918) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Community 4.2.1,Liquibase 4.2.1

**Comment by r2liquibase** [comment]
@nvoxland and @mariochampion, looks like some CDB changes impacted @alexandru-slobodcicov 's upcoming work on Cosmos.

**Comment by nvoxland** [comment]
Yeah, that needs to be fixed up. I have a fix in #1542 . Can you check that that branch fixes your issue?

**Comment by alexandru-slobodcicov** [comment]
Hi @nvoxland tested from branch with both liquibase-mongodb and liquibase-cosmosdb. 
All good, can be merged.
Thank you

**Comment by nvoxland** [comment]
Great! Thanks for the update
