### ISSUE TITLE
Encapsulate getTag, buildFullContext logic in changeSet so it can be reused in extensions

### ISSUE THREAD

**Issue by alexandru-slobodcicov** [liquibase/liquibase#1537]
## Environment
**Liquibase Version**: 4.1.1

**Liquibase Integration & Version**: spring boot

**Liquibase Extension(s) & Version**: liquibase-mongodb-4.1.1.2

**Database Vendor & Version**: Mongo DB 4.0

**Operating System Type & Version**: Windows

## Description
Currently the tag identification logic is in MarkChangeSetRanGenerator
`
String tag = null;
                for (Change change : changeSet.getChanges()) {
                    if (change instanceof TagDatabaseChange) {
                        TagDatabaseChange tagChange = (TagDatabaseChange) change;
                        tag = tagChange.getTag();
                    }
                }
`
would be better to have it somewhere in a common place in order to be reused and not copy/pasted each time in every extension
Could be a method in ChangeSet.pickTagDatabaseChange()

Same is for buildFullContext(changeSet))
Better to have a method in ChangeSet for all the logic: 
`((changeSet.getContexts() == null) || changeSet.getContexts()
                                .isEmpty()) ? null : buildFullContext(changeSet))`

For labels as well could b encapsulated: 
`((changeSet.getLabels() == null) || changeSet.getLabels().isEmpty()
                        ) ? null : changeSet.getLabels().toString())`

For liquibase version as well results into multiple copy/paste code that could be part of LiquibaseUtil: 
`StringUtil.limitSize(LiquibaseUtil.getBuildVersion()
                                                                                            .replaceAll("SNAPSHOT", "SNP")
                                                                                            .replaceAll("beta", "b")
                                                                                            .replaceAll("alpha", "b"), 20)`

**Comment by r2liquibase** [comment]
@nvoxland and @mariochampion , @alexandru-slobodcicov needs some help here for Cosmos. Thanks!

**Comment by nvoxland** [comment]
Yes, that does need to be improved. A general refactoring on the ChangeLogHistoryService interface and base classes has been on the short list of things to do for a while, but unfortunately hasn't made it to the top of the list yet. It will probably be something like we're doing in #1541 for LockService where we are trying to make it less reliant on the *Generators that assume something sql-related and better centralize the logic in the Service classes in a way that makes it easier to override just the pieces needed.

For now, it is probably best to just copy/paste the code (🤮 ) and we can clean it up better as the underlying interfaces improve.

**Comment by kevin-atx** [comment]
Hi @alexandru-slobodcicov. I'm following on Nathan's comment. Do you have the answer you need to move forward, or do you need additional guidance from us?

**Comment by tati-qalified** [comment]
As the last relevant comment was three years ago, and the reminder was 6 months ago, I'll be closing this ticket.
If anyone comes across this issue, feel free to leave a comment and I'll re-open it.
