### ISSUE TITLE
5 unique constraint limit

### ISSUE THREAD

**Issue by linuxninja39** [liquibase/liquibase#1547]
## Environment
**Liquibase Version**: 4.1.0

**Liquibase Integration & Version**: gradle-6.7

**Liquibase Extension(s) & Version**: liquibase-hibernate5-4.1.0

**Database Vendor & Version**:mariadb-10.3

**Operating System Type & Version**: ubuntu 20.20

## Description
A clear and concise description of the issue being addressed.
When I add a 6th unique constraint, diffChangeLog will keep creating the 6th+ constraint over and over.

## Steps To Reproduce
Create 5 entities with Entity and @Column(unique = true) or a Table annotation with a combined unique constraint. 
Do a generateChangeLog. 
Do an update, everything should work
Now create a 6th Entity with a unique constraint
Do diffChangeLog. Now if you look you'll see of of your unique constraints has been reproduced and your update will fail because of a duplicate key

## Actual Behavior
* changeSet:
    id: 1605725708662-2
    author: jacob (generated)
    changes:
  * addUniqueConstraint:
        columnNames: qool
        constraintName: UC_QOOLNESSQOOL_COL
        tableName: qoolness

and 

* changeSet:
    id: 1605725812015-1
    author: jacob (generated)
    changes:
  * addUniqueConstraint:
        columnNames: qool
        constraintName: UC_QOOLNESSQOOL_COL
        tableName: qoolness

## Expected/Desired Behavior
Should be able to have as many unique constraints in my schema as I'd like.

## Additional Context

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-951) by [Unito](https://www.unito.io/learn-more)

**Comment by nvoxland** [comment]
Thanks for the report. 
This will be fixed in 4.2.1 as #1477. 

Closing this as a duplicate
