### ISSUE TITLE
Add option/envvar to disable banner

### ISSUE THREAD

**Issue by fabiang** [liquibase/liquibase#1561]
## Environment
**Liquibase Version**: >=4.0

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: -

**Database Vendor & Version**: -

**Operating System Type & Version**: -

## Description
Add an global config option or environment variable to disable the banner when executing Liquibase on CLI. Polluting my buffer is annoying af. Thanks.

## User Story
As a CLI or automation user, i want control of the banner output, so that I dont see the liquibase logo banner if i dont want.

## Requirements
* enable true|false flag to show banner or not with default of true
  * ENV var: LIQUIBASE_BANNER=[true | false]
  * defaults file: liquibase.banner=[true | false]
  * CLI: --banner=[true | false] 

## Acceptance Criteria
* user can determine to see liquibase banner or not

**Comment by molivasdat** [comment]
Hi @fabiang Thanks for creating this request.  We will add it to the list of issues to process.

**Comment by piefel** [comment]
Using the Gradle plugin, thanks to `preLiquibaseRun`, `liquibaseRun` and `postLiquibaseRun`, I see that banner three times.

**Comment by petromir** [comment]
Hi, when do you expect to implement this

**Comment by molivasdat** [comment]
Hi @petromir It's on the list but not a high priority at the moment.

**Comment by ahaleiii** [comment]
As one who creates scripts and consumes their logs, +1 to this.

Created a PowerShell (7.1.4) function to strip the banner. Probably overkill. It handles `--log-level='debug'` cases when there is text before the banner.

```pwsh
# personal preference: do not assume constant number of lines in banner
function removeLiquibaseBanner($outputTextArray) {
    $bannerBorder = '####################################################'

    $preBannerTextArray = @()
    $inBanner = $false
    for ($i = 0; $i -lt $outputTextArray.Count; $i++) {
        $isBannerBorder = $outputTextArray[$i] -eq $bannerBorder
        if (-not $inBanner -and $isBannerBorder) {
            $inBanner = $true
        } elseif (-not $inBanner) {
            $preBannerTextArray += $outputTextArray[$i]
        } elseif ($isBannerBorder) {
            $lineAfterBanner = $i + 1
            break
        }
    }

    $lastLine = $outputTextArray.Count - 1
    $postBannerTextArray = $outputTextArray[$lineAfterBanner..$lastLine]
    return $preBannerTextArray + $postBannerTextArray
}
```

Running via the Docker image:

```
$❯ $output = Invoke-Expression "& docker run --rm liquibase/liquibase:latest --log-level='debug' --version 2>&1"
$❯ $outputNoBanner = removeLiquibaseBanner $output
```
Output with banner:
```
$❯ $output
[2021-08-29 19:35:41] FINE [liquibase.configuration] No configuration value for liquibase.hub.apiKey found
[2021-08-29 19:35:41] FINE [liquibase.configuration] No configuration value for liquibase.filterLogMessages found
[2021-08-29 19:35:41] FINE [liquibase.resource] Adding path /liquibase/. to resourceAccessor liquibase.resource.FileSystemResourceAccessor
[2021-08-29 19:35:41] FINE [liquibase.configuration] No configuration value for liquibase.shouldRun aka should.run found
[2021-08-29 19:35:41] FINE [liquibase.configuration] Configuration liquibase.shouldRun is using the default value of true
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ##
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ##
##  Free schema change activity reports at        ##
##      https://hub.liquibase.com                 ##
##                                                ##
####################################################
Starting Liquibase at 19:35:41 (version 4.4.3 #53 built at 2021-08-05 18:32+0000)
Running Java under /usr/local/openjdk-11 (Version 11.0.12)

Liquibase Version: 4.4.3
Liquibase Community 4.4.3 by Datical
```
Output without banner:
```
$❯ $outputNoBanner
[2021-08-29 19:35:41] FINE [liquibase.configuration] No configuration value for liquibase.hub.apiKey found
[2021-08-29 19:35:41] FINE [liquibase.configuration] No configuration value for liquibase.filterLogMessages found
[2021-08-29 19:35:41] FINE [liquibase.resource] Adding path /liquibase/. to resourceAccessor liquibase.resource.FileSystemResourceAccessor
[2021-08-29 19:35:41] FINE [liquibase.configuration] No configuration value for liquibase.shouldRun aka should.run found
[2021-08-29 19:35:41] FINE [liquibase.configuration] Configuration liquibase.shouldRun is using the default value of true
Starting Liquibase at 19:35:41 (version 4.4.3 #53 built at 2021-08-05 18:32+0000)
Running Java under /usr/local/openjdk-11 (Version 11.0.12)

Liquibase Version: 4.4.3
Liquibase Community 4.4.3 by Datical
```

Caveats:
- Using PowerShell
- Using `Invoke-Expression` which is not necessarily best practice
- Output is captured to variable rather than streamed to host
  - My script is most likely going to need to parse this text anyways, so it was inevitable either way.

**Comment by jimpriest** [comment]
Another vote for this feature. Scripting anything just results in all this noise that I don't care about :)  I know I'm running a Liquibase command LOL.

**Comment by ridicolos** [comment]
Would love to see this be implemented. After running several liquibase commands in a row, the terminal looks very cluttered which is quite annoying.

**Comment by kataggart** [comment]
@ridicolos GOOD NEWS! This is merged and will be included in the next release!

**Comment by kataggart** [comment]
For everyone following along, this is now released 

https://github.com/liquibase/liquibase/pull/2871

... also if you have five min to spare would love your [input!](https://bit.ly/lbcommsurvey)
