### ISSUE TITLE
add lifecycle support

### ISSUE THREAD

**Issue by liyunfei0302** [liquibase/liquibase#1564]
## Environment
**Liquibase Version**:3.6.3

**Liquibase Integration & Version**: spring boot

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:MySql, 5.7

**Operating System Type & Version**:mac OS, 11.0.1

## Description
I hope add lifecycle hook, I want to do something after the database is created, but I don't know how.

## Steps To Reproduce
none

## Actual Behavior
none

## Expected/Desired Behavior
none

## Screenshots (if appropriate)
none

## Additional Context
none

**Comment by molivasdat** [comment]
Hi @liyunfei0302 Not sure I understand the question.  Can you elaborate further and join discord [https://discord.gg/9yBwMtj](https://discord.gg/9yBwMtj )  to get more details?
