### ISSUE TITLE
Contents of migration file aren't getting executed

### ISSUE THREAD

**Issue by justin-dd** [liquibase/liquibase#1567]
## Environment
**Liquibase Version**: 4.2

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: CockroachDB 20.2.1

**Operating System Type & Version**: MacOS Catalina 10.15.7

## Description
A clear and concise description of the issue being addressed.

* I recently upgraded to liquibase 4.2 and `liquibase update` no longer seem to be working. The entries are written to the `databasechangelog` table, however, and if I move the migration file or intentionally misspell the hostname, I get an appropriate error. Similarly, `liquibase rollbackCount 1` will remove the entry from `databasechangelog` but will not actually execute the sql in the migration file. I tried to rollback to liquibase 4.1.1, but I'm getting a different java error, so I haven't been able to confirm if this is specific to 4.2 or if this has been happening on this particular machine for longer.

## Steps To Reproduce
List the steps to reproduce the behavior.

* Install liquibase with `brew install liquibase`
* Navigate to project directory
* Run the liquibase CLI with `liquibase --username username --url jdbc:postgresql://localhost:26257/database_name --changeLogFile "path/to/database_migrations.xml" update`
* `update` seems to pick up the changeset:

```xml
<?xml version="1.0" encoding="UTF-8"?>

<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:pro="http://www.liquibase.org/xml/ns/pro"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd
         http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-3.8.xsd">
    <changeSet author="justin-dd" id="v1_0_0">
        <sqlFile dbms="postgresql"
                 encoding="utf8"
                 endDelimiter="\nGO"
                 path="V1.0_drop_unnecessary_index.sql"
                 relativeToChangelogFile="true"
                 splitStatements="true"
                 stripComments="true"/>
        <rollback>
            <sqlFile dbms="postgresql"
                     encoding="utf8"
                     endDelimiter="\nGO"
                     path="V1.0_add_index.sql"
                     relativeToChangelogFile="true"
                     splitStatements="true"
                     stripComments="true"/>
        </rollback>
    </changeSet>
</databaseChangeLog>
```

* This points to the following files:

```sql
DROP INDEX table_name@index_name;
```

```
CREATE INDEX ON table_name (column_name);
```

* Output from CLI is

```
Starting Liquibase at 17:50:55 (version 4.2.0 #18 built at 2020-11-13 16:49+0000)
Liquibase: Update has been successful.
```

* Run sql `select * from databasechangelog;` - see v1_0_0
* Look at schema and no change
* Run `liquibase --username username --url jdbc:postgresql://localhost:26257/database_name --changeLogFile "path/to/database_migrations.xml" rollbackCount 1`
* Run sql `select * from databasechangelog;` - see v1_0_0 was removed
* Look at schema and no change
* Fill both files with garbage text expecting an error
* Re-run `update` and `rollbackCount 1` - both claim to succeed and update `databasechangelog`

## Actual Behavior
No matter what I put in my SQL files, `update` and `rollbackCount 1` both succeed, the entries get written or removed from `databasechangelog`

## Expected/Desired Behavior
The sql within the `.sql` files is executed.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-981) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
Hi @justin-dd Thanks for writing up this issue.  In your dbms string you are using postgresql, but running against a cockroach database.  Can you change that to cockroachdb?
The way it is looking to me is that the changeset has run but there is nothing to do on the database since it's a cockroach database.  So it marks it as having run on that database in the changelogtable so it does not have to evaluate it again.

**Comment by justin-dd** [comment]
@molivasdat - thanks for the response. I'll try that tomorrow and report back. I did manage to run the test again today with the `--logLevel 0` flag and noticed this in the output:

```
[2020-12-02 19:56:23] FINE [liquibase.changelog] Change sqlFile not included for database cockroachdb
```

**Comment by justin-dd** [comment]
@molivasdat apologies for not replying sooner, but changing the dbms string did fix the issue for me.

Thank you so much for following up and taking the time to respond with helpful feedback!

**Comment by molivasdat** [comment]
Closing issue as resolved.
