### ISSUE TITLE
dropAllForeignKeyConstraints performance/errors in liquibase 3.10.3, works perfect in liquibase 3.4.2

### ISSUE THREAD

**Issue by duronrulez** [liquibase/liquibase#1571]
## Environment
**Liquibase Version**: works fine on 3.4.2, broken on 3.10.3

**Liquibase Integration & Version**: CLI

**Database Vendor & Version**: MySql 5.6

**Operating System Type & Version**: centos 7

## Description
In 3.10.3 a dropAllForeignKeyConstraints change is incredibly slow (168087ms vs 55ms) and produces errors:

`14:52:17.216 INFO  [liquibase.util.SqlUtil]: Unknown default value: value 'XXX4' type SET('XXX1', 'XXX2', 'XXX3', 'XXX4') (SET('XXX1', 'XXX2', 'XXX3', 'XXX4')). Calling it a function so it's not additionally quoted`

The same command takes milliseconds to run on 3.4.2

## Steps To Reproduce
```
<changeSet id="1" author="XXX" context="XXX">
        <comment>Remove constrains</comment>
        <dropAllForeignKeyConstraints baseTableName="XXX"/>
    </changeSet>
```

Additionally in the general log i can see that liquibase is evaluating the whole server for FKs, with thousands of queries like this one:

```
SELECT A.REFERENCED_TABLE_SCHEMA AS PKTABLE_CAT,NULL AS PKTABLE_SCHEM,A.REFERENCED_TABLE_NAME AS PKTABLE_NAME,A.REFERENCED_COLUMN_NAME AS PKCOLUMN_NAME,A.TABLE_SCHEMA AS FKTABLE_CAT,NULL AS FKTABLE_SCHEM,A.TABLE_NAME AS FKTABLE_NAME, A.COLUMN_NAME AS FKCOLUMN_NAME, A.ORDINAL_POSITION AS KEY_SEQ,CASE WHEN R.UPDATE_RULE='CASCADE' THEN 0 WHEN R.UPDATE_RULE='SET NULL' THEN 2 WHEN R.UPDATE_RULE='SET DEFAULT' THEN 4 WHEN R.UPDATE_RULE='RESTRICT' THEN 1 WHEN R.UPDATE_RULE='NO ACTION' THEN 3 ELSE 3 END  AS UPDATE_RULE,CASE WHEN R.DELETE_RULE='CASCADE' THEN 0 WHEN R.DELETE_RULE='SET NULL' THEN 2 WHEN R.DELETE_RULE='SET DEFAULT' THEN 4 WHEN R.DELETE_RULE='RESTRICT' THEN 1 WHEN R.DELETE_RULE='NO ACTION' THEN 3 ELSE 3 END  AS DELETE_RULE,A.CONSTRAINT_NAME AS FK_NAME,(SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = A.REFERENCED_TABLE_SCHEMA AND TABLE_NAME = A.REFERENCED_TABLE_NAME AND CONSTRAINT_TYPE IN ('UNIQUE','PRIMARY KEY') LIMIT 1) AS PK_NAME,7 AS DEFERRABILITY FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE A JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS B USING (CONSTRAINT_NAME, TABLE_NAME) JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS R ON (R.CONSTRAINT_NAME = B.CONSTRAINT_NAME AND R.TABLE_NAME = B.TABLE_NAME AND R.CONSTRAINT_SCHEMA = B.TABLE_SCHEMA) WHERE B.CONSTRAINT_TYPE = 'FOREIGN KEY' AND A.TABLE_SCHEMA LIKE 'XXX' AND A.TABLE_NAME='XXX' AND A.REFERENCED_TABLE_SCHEMA IS NOT NULL ORDER BY A.REFERENCED_TABLE_SCHEMA, A.REFERENCED_TABLE_NAME, A.ORDINAL_POSITION
```

**Comment by molivasdat** [comment]
Hi @duronrulez Thanks for writing up this issue.  We will add this to our list of issues to process. If you have a suggested PR for a fix that would be great.

**Comment by FBurguer** [comment]
It looks like its still an issue on liquibase `4.15`. We need to investigate further to be sure. There is a PR that possible fix this. Looking more into it after the PR is validated.

**Comment by filipelautert** [comment]
Hi @FBurguer  - PR https://github.com/liquibase/liquibase/pull/2155 fixes it. I'm moving this issue to development to link it with the PR.
