### ISSUE TITLE
mvn liquibase:diff throws NPE

### ISSUE THREAD

**Issue by Robbilie** [liquibase/liquibase#1576]
## Environment
**Liquibase Version**: 4.2.1

**Liquibase Integration & Version**: maven

**Liquibase Extension(s) & Version**: 

spring boot 2.4.0
		<liquibase-hibernate5.version>4.1.1</liquibase-hibernate5.version>
		<validation-api.version>2.0.1.Final</validation-api.version>

**Database Vendor & Version**: h2

**Operating System Type & Version**: debian buster

## Description
When running mvn liquibase:diff the command fails with a NPE.

## Steps To Reproduce
[pom.txt](https://github.com/liquibase/liquibase/files/5660918/pom.txt)

Run mvn liquibase:diff

The changelog has no changes in it, liquibase:update runs smoothly.

## Actual Behavior
[logs.txt](https://github.com/liquibase/liquibase/files/5660924/logs.txt)

## Expected/Desired Behavior
A diff file was created…

## Additional Context

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1013) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 4.2.2

**Comment by Robbilie** [comment]
okay so i believe this might be a version incompatibility with liquibase-hibernate5?

https://github.com/liquibase/liquibase-hibernate/issues/282

**Comment by nvoxland** [comment]
Yeah, there was a similar bug we fixed for 4.2.1 but hibernate worked around that bugfix...  We'll have to get an updated Liquibase version to fix that.

**Comment by Robbilie** [comment]
ok thanks, guess ill have to revert some dependabot commits then :/
