### ISSUE TITLE
Fix XML example and documentation for onFail preconditions

### ISSUE THREAD

**Issue by vlsi** [liquibase/liquibase#1578]
## Environment
https://docs.liquibase.com/concepts/advanced/preconditions.html

The website suggests the following:

```xml
<changeSet  id="1"  author="Liquibase User">
    <preConditions  onFail="WARN">
    <sqlCheck  expectedResult="0">select count(*) from oldtable</sqlCheck>
    </preConditions>
    <comment>Comments should go after preCondition. If they are located before the precondition, then Liquibase usually gives error.</comment>
    <dropTable  tableName="oldtable"/>
    </changeSet>
</databaseChangeLog>
```

The comment below the sample reads:

> It will also **only** run dropTable if there are **no values in the oldtable**

However, `onFail="WARN"` makes the precondition be effectively be ignored.

In practice, `onFail="WARN"` just ignores the violation and executes the changeset anyway: https://github.com/liquibase/liquibase/blob/75bc150e4d7281008842d77c0d140c2244284475/liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java#L566-L578

## Expected behavior
The sample should be aligned with the comment.
For instance, use `onFail="HALT"` in the sample instead of `onFail="WARN"`

## Actual Behavior
A misleading pattern is suggested as the very first sample for preconditions.

The documentation of `WARN` is not really easy to understand:

> CONTINUE: Skips over the changeset. Execution of the changeset will be attempted again on the next update. Continues with the changelog.
> WARN: Outputs a warning and continue executing the changeset / changelog as normal. WARN can be put outside a changeset (e.g. at the beginning of the changelog).

It is hard to tell how CONTINUE differs from WARN. It would be nice if the wording for WARN was improved.

**Comment by molivasdat** [comment]
Hi @vlsi Thanks for writing up this issue.  We have a doc site where you can suggest a fix for the documentation.  Please open an [issue](https://github.com/Datical/liquibase-docs/issues) or a [PR](https://github.com/Datical/liquibase-docs/pulls) to fix the documentation.

**Comment by FBurguer** [comment]
Looks like the doc page has been fixed. Now it says:
`Also, it will run the changeset with the sqlCheck precondition and dropTable`
 Closing this issue. Thanks!
