### ISSUE TITLE
Maven Plugin Displays "[project, pluginDescriptor]"

### ISSUE THREAD

**Issue by mrgrew** [liquibase/liquibase#1585]
Starting with version 4.1.0, the liquibase-maven-plugin displays "[project, pluginDescriptor]".

I did some analysis and this appears to be left-over debug code. I'll be submitting a pull request to remove that code.

**Comment by molivasdat** [comment]
Hi @mrgrew Thanks for adding this issue to our attention and thanks for creating a PR to fix it.  We will add this to our list of issues to process.

**Comment by kataggart** [comment]
This looks like it has been resolved; closing
