### ISSUE TITLE
Liquibase Maven Plugin throws an error with a diff goal requiring a changelogFile referenced

### ISSUE THREAD

**Issue by szandany** [liquibase/liquibase#1586]
## Environment
**Liquibase Integration & Version**:  liquibase-maven-plugin - 4.1.1

**Liquibase Extension(s) & Version**: Any

**Database Vendor & Version**: Any

**Operating System Type & Version**: Windows or Linux.

## Description
When running Liquibase diff goal, without including a changeLogFile, Liquibase will throw an error asking to reference a changelog with the changeLogFile property.  This is not an issue with CLI.

## Steps To Reproduce
Run the diff goal without referencing a changeLogFile: 
For example:
`mvn liquibase:diff`

## Actual Behavior
This will produce the following error:
`[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:4.1.1:diff (default-cli) on project liquibase-project: The changeLogFile must be specified. -> [Help 1]`

## Expected/Desired Behavior
The diff goal should run successfully just like the CLI diff command.

**Comment by FBurguer** [comment]
Looks like this issue has been solved for the latest version of liquibase-maven-plugin. If the issue continues to happen to you, please re-open the issue and we will have a second look! Thanks
