### ISSUE TITLE
Add documentation on how to register a changelog from the liquibase docker images

### ISSUE THREAD

**Issue by molivasdat** [liquibase/liquibase#1594]
## Environment
**Liquibase Version**:docker latest and docker 4.2.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>CLI docker

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**:All

**Operating System Type & Version**:Mac OS

## Description
Need to add documentation on how to use the docker image to register a changelog so that docker liquibase can use hub

## Steps To Reproduce
run something like

```
docker run --rm \
                -v /Users/molivas/Documents/SE/code/props/lms_postgresql:/liquibase/project \
                 liquibase/liquibase \
                 --defaultsFile=project/liquibase.properties \
                 --changeLogFile=project/changelogupdateddemo.xml \
                 --classpath=/liquibase/project/postgresql-42.2.11.jar \
                 registerChangeLog
```

As the examples show on how to run a liquibase command

## Actual Behavior
Error occurs
Unexpected error running Liquibase: No console available
For more information, please use the --logLevel flag

## Expected/Desired Behavior
docker liquibase is able to register a changelog file and use it.

## Additional Context
something like
docker run --rm **-it** \
                -v /Users/molivas/Documents/SE/code/props/lms_postgresql:/liquibase/project \
                 liquibase/liquibase \
                 --defaultsFile=project/liquibase.properties \
                 --changeLogFile=project/changelogupdateddemo.xml \
                 --classpath=/liquibase/project/postgresql-42.2.11.jar \
                 registerChangeLog

might work

**Comment by lbadam** [comment]
Closing this as we have deprecated Hub. If this still needs to be documented, please reopen.
