### ISSUE TITLE
Extra backslash added in the column values in the genarated sql

### ISSUE THREAD

**Issue by zamani84** [liquibase/liquibase#1598]
## We make a liquibase database export from oracle DB. In some columns the value "\b08.*" is saved. When I execute "mvn liquibase:generateChangeLog" command then the value is exported in a insert statment like this:
```
<insert tableName="xyz">
           ...
            <column name="KURZ_TEXT" value="\\b08.*"/>
            <column name="LANG_TEXT" value="\\b08.*"/>
    ...


</insert>
```

We use liquibase 3.6.2.

Please, I don't know how the exporter changes the value of the exported column values. How can I prevent this? I want exactly the value as it is in the column. 

## This is my liquibase maven export profile:
- - -
```
<profile>
      <!-- DB Auszug von DATEN aus KONFIG SCHEMA - ACHTUNG: ES WERDEN ALLE KONFIG DATEN VON ALLEN TABELLEN EXPORTIERT -->
      <id>export_konfig_data</id>
      <build>
        <pluginManagement>
          <plugins>
            <plugin>
              <groupId>org.liquibase</groupId>
              <artifactId>liquibase-maven-plugin</artifactId>
              <configuration>
                <changeSetAuthor>MELDEPORTAL ${parent.version} KONFIG DATA</changeSetAuthor>
                <diffTypes>data</diffTypes>
                <outputChangeLogFile>${project.basedir}/changelogs/initial/initial_konfig_data.xml</outputChangeLogFile>
                <changeSetContext>konfig</changeSetContext>
                <driver>oracle.jdbc.OracleDriver</driver>
                <promptOnNonLocalDatabase>false</promptOnNonLocalDatabase>
                <logging>INFO</logging>
                <url>${database.urls}</url>
                <username>xxxxx</username>
                <password>xxxxx</password>
                <contexts>xxxxx,${context}</contexts>
              </configuration>
            </plugin>
          </plugins>
</pluginManagement>
 </build>
    </profile>
```

- - -
This is the exact command I execute:  mvn liquibase:generateChangeLog -Pexport_konfig_data

This issue should be same like mentioned here: https://forum.liquibase.org/t/extra-backslash-added-in-the-column-values-in-the-genarated-sql-file-from-generatechangelog-using-maven-liquibase/3663

**Comment by molivasdat** [comment]
Hi @zamani84 Thanks for writing up this issue.  Do you have a simple use case that you can attach or create a repo that recreates the issue so that we can have the community take a look at fixing it?

**Comment by zamani84** [comment]
Hallo,
thanks very much for answering. 

We use oracle 12c database. 

Create following table as oracle user KONFIG:
---------------
CREATE TABLE KONFIG.MY_TABLE
   (	
	A_TXT CHAR(24 CHAR)
	);
-------------------
Then include following into the table:
----------------
Insert into KONFIG.MY_TABLE (A_TXT) values ('\b08.*                  ');
---------------

Now make a data liquibase export of the Tablle KONFIG.MY_TABLE. It should work with this pom.xml :

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
    <groupId>de.dzbw.meldeportal</groupId>
    <version>8.8.0-SNAPSHOT</version>
  <artifactId>datenbank</artifactId>
  <packaging>pom</packaging>

  <properties>

     <database.urls>jdbc:oracle:thin:@dns-name:1521:mitv1db7139</database.urls>

    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <context>initial,cleanup</context>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.oracle</groupId>
      <artifactId>ojdbc7_g</artifactId>
      <version>12.1.0.1</version>
    </dependency>
  </dependencies>

  <profiles>

    <profile>
      <id>export_konfig_datas</id>
      <build>
        <pluginManagement>
          <plugins>
            <plugin>
              <groupId>org.liquibase</groupId>
              <artifactId>liquibase-maven-plugin</artifactId>
              <configuration>
                <outputFileEncoding>UTF-8</outputFileEncoding>
                <changeSetAuthor>MELDEPORTAL ${parent.version} KONFIG DATA</changeSetAuthor>
                <diffTypes>data</diffTypes>
                <diffIncludeObjects>MY_TABLE</diffIncludeObjects>
                <outputChangeLogFile>${project.basedir}/konfig-export.oracle.xml</outputChangeLogFile>
                <changeSetContext>konfig</changeSetContext>
                <driver>oracle.jdbc.OracleDriver</driver>
                <promptOnNonLocalDatabase>false</promptOnNonLocalDatabase>
                <logging>INFO</logging>
                <url>${database.urls}</url>
                <username>konfig</username>
                <password>konfig</password>
                <contexts>konfig,${context}</contexts>
              </configuration>
            </plugin>
          </plugins>
        </pluginManagement>

        <plugins>
          <plugin>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-maven-plugin</artifactId>
            <executions>
              <execution>
                <phase>process-resources</phase>
                <goals>
                  <goal>generateChangeLog</goal>
                </goals>
              </execution>
            </executions>
          </plugin>

        </plugins>
      </build>
    </profile>


  </profiles>
</project>
`

**Comment by zamani84** [comment]
Here the files:

pom.xml , export file : konfig-export.oracle.xml and the sql file to generate table and insert one dataset into it (all in zip file database-export-test.zip)
[database-export-test.zip](https://github.com/liquibase/liquibase/files/5751894/database-export-test.zip)
