### ISSUE TITLE
spring-boot-autoconfigure-2.1.17.RELEASE Cannot resolve classpath  

### ISSUE THREAD

**Issue by EDOUP** [liquibase/liquibase#1599]
## Environment
**Liquibase Version**: 4.0.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
 spring-boot-starter-parent  2.1.17.RELEASE

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

**Operating System Type & Version**:

## Description
A clear and concise description of the issue being addressed.

* Describe the actual problematic behavior.
* Ensure private information is redacted.
* 
* spring-boot-autoconfigure-2.1.17.RELEASE-sources.jar!\org\springframework\boot\autoconfigure\liquibase\LiquibaseAutoConfiguration.java
Unable to resolve the "classpath" in the "spring.liquibase.rollback-file" parameter

 cause  new FileOutputStream(rollbackFile)  is error
 but  - spring-boot-autoconfigure-2.2.x   no problem

## Steps To Reproduce
List the steps to reproduce the behavior.

* Please be precise and ensure private information is redacted
* Include things like
  * Files used - sql scripts, changelog file(s), property file(s), config files, POM Files
  * Exact commands used - CLI, maven, gradle, spring boot, servlet, etc.

## Actual Behavior
A clear and concise description of what happens in the software **before** this pull request.

* Include console output if relevant
* Include log files if available.

## Expected/Desired Behavior
A clear and concise description of what happens in the software **after** this pull request.

## Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/34361805/102765078-15dfd980-43b7-11eb-8203-8b42e5d2d8da.png)
![image](https://user-images.githubusercontent.com/34361805/102765608-c817a100-43b7-11eb-83cf-f0337cb67e6e.png)

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1067) by [Unito](https://www.unito.io/learn-more)

**Comment by EDOUP** [comment]
Has anyone encountered it before? Is this a problem?

**Comment by molivasdat** [comment]
Hi @EDOUP Thanks for writing up this issue.  We typically do not go back and retro fit fixes available in newer releases.  Is there a reason that you need 2.1.17 instead of 2.2.x?

**Comment by EDOUP** [comment]
Thanks , because i use it in company . Upgrading is a bit of a hassle, I'll try something else

**Comment by molivasdat** [comment]
Ok.  Closing as fixed in newer version.
