### ISSUE TITLE
CLI doesn't work with Spring Boot Classloader on Windows

### ISSUE THREAD

**Issue by javastu** [liquibase/liquibase#1600]
Windows 10

**Liquibase Version**: 3.6.3

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: H2

**Operating System Type & Version**: Windows

## Description
We use liquibase.integration.commandline.Main to invoke Liquibase programmatically in the startup routine of our application.

We have been building our application with the maven shaded plugin to create an Uber (fat) jar. This has worked for us for years.

We are now switching to Spring Boot and using the Spring Boot Maven Plugin to repackage our application as a fat jar instead of using the shaded plugin.

We are getting an IllegalArgumentException on Windows

Main.parseOptions calls Main.parseDefaultPropertyFiles looking for the default liquibase.properties file. Because the file does not exist, it tries to open it as a resource, calling getAbsolutePath on the File object. On Windows this resolves to something like this:
C:\liquibase.properties. When a string like this passed to getResourceAsStream to the Spring Boot class loader, a IllegalArgumentException is thrown.

**Comment by molivasdat** [comment]
Hi @javastu Thanks for alerting us to this issue.  We will add it to our list of issues to process.

**Comment by nvoxland** [comment]
We have been working on improving this lately.

There is a new liquibase.integration.commandline.LiquibaseCommandLine class as the new version of the Main class you were using before which shifts stuff around a bit. As part of that, there is refactored ConfigurationValueProvider system that allows you to register where you want configuration options to come from. 

From your external code, you can call `final LiquibaseConfiguration liquibaseConfiguration = Scope.getCurrentScope().getSingleton(LiquibaseConfiguration.class);
` to get the LiquibaseConfiguration system, then something like `liquibaseConfiguration.registerProvider(new DefaultsFileValueProvider(...));` with however you want your file looked up.

As an alternative, 4.4.0 introduced a new "command framework" which is designed to allow code like yours to work more easily with the underlying commands, without having to route through something like the LiquibaseCommandLine class which is built around how the CLI expects to work.

It allows you to call something like:
```
final CommandScope commandScope = new CommandScope("update");
commandScope.addArgumentValue("url", "...");
.....
commandScope.execute()
```

which may simplify things significantly for you.

Does that help?

**Comment by nvoxland** [comment]
Re-open this if it continues to be a problem.
