### ISSUE TITLE
Liquibase rollback by tag can work unexpectedly when more than one changelog files are used

### ISSUE THREAD

**Issue by ro-rah** [liquibase/liquibase#1605]
## Environment
Mac OS

**Liquibase Version**:
4.2.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
CLI

**Liquibase Extension(s) & Version**: 
n/a

**Database Vendor & Version**:
postgres from dockercontainer: docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d -p 5432:5432 postgres

**Operating System Type & Version**:
Docker image:
docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d -p 5432:5432 postgres

## Description
Liquibase rollback by tag can work unexpectedly when more than one changelog files are used.  Let's say 2 changelogs are being used to update a database:
teamA.xml
teamB.xml
Both teams tag their releases.  Problem occors when TeamB rollsback by tag using a TeamA created tag.  Team B's tag in the repro below gets deleted.  This may confuse teams, maybe we should not allow rollback to a tag that was not created in the changelog specified by --changeLogFile

## Steps To Reproduce
Create teamA.xml with the following contents:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.1.xsd
        http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd" changeLogId="1d273e3c-0ea5-4c65-bb5d-f93b34aec5bc">

  <changeSet author="ronak (generated)" id="1595879345576-1">
    <createTable tableName="tableA1">
      <column name="child" type="CHAR(20)"/>
      <column name="rec_num" type="INT"/>
    </createTable>
  </changeSet>
</databaseChangeLog>
```

run: liquibase --changeLogFile=**teamA**.xml update
create teamB.xml with the following contents:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.1.xsd
        http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd" changeLogId="1d273e3c-0ea5-4c65-bb5d-f93b34aec5bc">

  <changeSet author="ronak (generated)" id="2595879345576-1">
    <createTable tableName="tableB1">
      <column name="child" type="CHAR(20)"/>
      <column name="rec_num" type="INT"/>
    </createTable>
  </changeSet>
</databaseChangeLog>
```

run: liquibase --changeLogFile=**teamB**.xml update
add the following changeset to teamA.xml

```xml
<changeSet  author="liquibase"  id="21">
     <tagDatabase  tag="teamArelease1"/>
  </changeSet>
```

run: liquibase --changeLogFile=**teamA**.xml update
add the following changeset to teamB.xml

```xml
<changeSet  author="liquibase"  id="B21">
    <tagDatabase  tag="teamBrelease1"/>
  </changeSet>
```

run: liquibase --changeLogFile=**teamB**.xml update
add the following changeset to teamA.xml

```xml
<changeSet author="ronak (generated)" id="1595879345576-2">
    <createTable tableName="tableA2">
      <column name="child" type="CHAR(20)"/>
      <column name="rec_num" type="INT"/>
    </createTable>
  </changeSet>
```

run: liquibase --changeLogFile=**teamA**.xml update
add the following changeset to teamB.xml

```xml
  <changeSet author="ronak (generated)" id="2595879345576-2">
     <createTable tableName="tableB2">
       <column name="child" type="CHAR(20)"/>
       <column name="rec_num" type="INT"/>
     </createTable>
   </changeSet>
```

run: liquibase --changeLogFile=**teamB**.xml update
run: liquibase --changeLogFile=**teamB**.xml rollback **teamArelease1**

## Actual Behavior
Here's the output:

> Starting Liquibase at 10:35:38 (version 4.2.0 #18 built at 2020-11-13 16:49+0000)
> Rolling Back Changeset:teamB.xml::2595879345576-2::ronak (generated)
> Rolling Back Changeset:teamB.xml::B21::liquibase
> Liquibase: Rollback has been successful.

You can see that the tag for B is being rolled back as well.

## Expected/Desired Behavior
Even though the command was using teamB's xml, it referenced a tag created outside its own changelog.  In this case, it deleted a tag created by teamB.  This is confusing behavior, maybe we should say teamB does not have a tag called teamArelease1.

## Screenshots (if appropriate)
Before rollback:
![BFC2A248-7824-44BC-BA8F-64BE31C2B51E](https://user-images.githubusercontent.com/52418001/103300967-d53f1c00-49c5-11eb-95d8-70f4c4a42ff1.png)

After rollback:
![BEF5A9EA-C908-47CF-A2E6-57FA87C85B23](https://user-images.githubusercontent.com/52418001/103300980-de2fed80-49c5-11eb-9220-fb9ce8f83816.png)

## Additional Context
Its an edge case for sure, but I was keeping my activity xml files separated by activity while completing the Liquibase LMS.  Others may run into this issue.  Also, we should define what the correct behavior is.

**Comment by nvoxland** [comment]
I see what you are getting at. I think it helps to remember that even though there is a tagDatabase function that can be used in a changelog, it's not like that tag belongs to that changelog. The tag really exists on the database history, regardless of how it got there. 

When it comes time to roll back to a spot in that history using a tag, liquibase doesn't know or care how that tag got applied, it just knows what point in time that applies to and will roll back to there. In your case, it can't revert all the changes because they aren't in your active changelog file, but it is still just going back to the point in time it recognizes. 

While there are cases like this which may surprise people, I'm not sure there is any other behavior we can support?

**Comment by ro-rah** [comment]
Perhaps we should disable the use of the --changeLogFile option, since it is only based on the target's databasechangelog table, the acceptance of that argument seems confusing.  How's that sound?  I'm just looking for a way to steer the user from doing something unexpected.  If there is not changelogfile option, then user will hopefully think, I wonder what is in the changelog table?

**Comment by nvoxland** [comment]
We need the changelog file, though, because that has the actual logic of what to roll back and how. The history table doesn't include enough to actually do the roll back.

**Comment by mariochampion** [comment]
perhaps this is, then, a place where we need extra documentation. If users understand the issue, because we optionally can make them aware of what WILL be rolled back to tag, before doing the rollback, then the edge case exists, but is less surprising. perhaps this would be acceptable @ro-rah ?

**Comment by ro-rah** [comment]
@nmelny and I are working on this, we will paste in documentation link when it is complete and then we can close this issue.
