### ISSUE TITLE
CORE-3198 Regression - prefer internal XSD usage

### ISSUE THREAD

**Issue by dm-ion** [liquibase/liquibase#1609]
## Environment
**Liquibase Version**:
4.0.0 -> current (I'm testing on 4.2.2)

**Liquibase Integration & Version**: 
Java

**Liquibase Extension(s) & Version**: 
None

**Database Vendor & Version**:
ALL / not really relevant

**Operating System Type & Version**:
ALL / not really relevant

## Description
Regression of https://liquibase.jira.com/browse/CORE-3198, when merging 3.10 to 4.0 looks like this flag was accidentally wiped out.

## Steps To Reproduce
List the steps to reproduce the behavior.

1. Set property "liquibase.prefer.internal.xsd"
1. Disconnect internet, or open WireShark or similar tool
1. Run any XML changeset

## Actual Behavior
Running the changeset fails with

`Failed to read schema document 'http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.2.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>`

## Expected/Desired Behavior
It should use the XSD out of the jar

## Additional Context
Broken: ee233bd4c082f7e58de7ce5f7a2e6910a67f9f59

To fix add this code to the constructor of XMLChangeLogSAXParser (as in previous versions, eg: https://github.com/liquibase/liquibase/blob/a8b11044a571a11a7b904dfc7dce364fd0d49f37/liquibase-core/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java )
`
if (PREFER_INTERNAL_XSD) {
            InputStream xsdInputStream = XMLChangeLogSAXParser.class.getResourceAsStream(XSD_FILE);
            if (xsdInputStream != null) {
                try {
                    SchemaFactory schemaFactory = SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);
                    Schema schema = schemaFactory.newSchema(new StreamSource(xsdInputStream));
                    saxParserFactory.setSchema(schema);
                    saxParserFactory.setValidating(false);
                } catch (SAXException e) {
                    LogService.getLog(XMLChangeLogSAXParser.class).warning("Could not load " + XSD_FILE + ", enabling parser validator", e);
                }
            }
        }
`

**Comment by molivasdat** [comment]
Hi @dm-ion Thanks for bringing this to our attention.  I'm checking with development to see what happened.

**Comment by dm-ion** [comment]
Sure sounds good, also it appears your servers don't like this behaviour very much.

I've seen some 429 responses from your servers recently due to this as well.

java.io.IOException: Server returned HTTP response code: 429 for URL: http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.2.xsd

**Comment by nvoxland** [comment]
That block of code should no longer be needed in the 4.0+ releases becauuse of how we updated the LiquibaseEntityResolver. 

I'm not able to replicate the problem of pulling from the network. But, I could maybe see it not working if your ResourceAccessor does not include  include the liquibase.jar? How are you running liquibase? And can you post logLevel=fine logs?

**Comment by nvoxland** [comment]
Actually, however you are running liquibase, we need to make sure that however the ResourceAccessor gets configured, Liquibase will check the classpath as well.

I made a PR that should fix this in #1621. Are you able to test that branch/change in your environment?

**Comment by dm-ion** [comment]
I agree that is certainly a more robust fix, I was just being lazy with my suggested fix.

I can give your solution a test tomorrow morning / afternoon.

**Comment by dm-ion** [comment]
How I'm invocating liquibase is from Java, using the following command:

`return new liquibase.Liquibase(changeLogPath.getFileName().toString(), new FileSystemResourceAccessor(changeLogPath.getParent().toFile()), database);`

After I test your PR, I'll also test on the existing version using a CompositeResourceAccessor in place of my second argument there. I would expect that could work for the current version for my situation.

**Comment by dm-ion** [comment]
Brilliant, works great when I ran a schema upgrade. Also what I said above works for the current version as well.

Thanks!

Also while I've got your attention thanks for liquibase, it's a nice product. :)

**Comment by kataggart** [comment]
@dm-ion So happy Liquibase is working for you!

If you feel so moved, we would appreciate a review over here: [https://www.g2.com/products/liquibase/take_survey](https://www.g2.com/products/liquibase/take_survey )

Thanks again!!
