### ISSUE TITLE
diffChangelog command is not respecting the changeSetAuthor option

### ISSUE THREAD

**Issue by unlimitedsola** [liquibase/liquibase#1610]
## Environment
**Liquibase Version**:
3.10.3

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
Any

**Liquibase Extension(s) & Version**: 
Any

**Database Vendor & Version**:
Any

**Operating System Type & Version**:
Any

## Description
since the `diffChangelog` command has the potential to write to an external changelog file,
I think we should also respect the `changeSetAuthor` option as what `generateChangelog` command did.

## Steps To Reproduce
execute `diffChangelog` command with `--changeSetAuthor` option

**Comment by molivasdat** [comment]
Thanks @unlimitedsola for submitting this issue.  We will add it to the list of issues that we are processing.

**Comment by changemyminds** [comment]
Any update news? Still wrong with version  4.15.0.
