### ISSUE TITLE
Addition of liquibase.update()

### ISSUE THREAD

**Issue by Betlista** [liquibase/liquibase#1614]
## Environment
**Liquibase Version**: 4.2.2

**Liquibase Integration & Version**: Spring Boot 2.2.2

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: HSQLDB

**Operating System Type & Version**: Win 10

## Description
This is a request for enahancement.

I tried to implement liquibase update programatically in Spring Boot application and I found that `liquibase.Liquibase.update()` requires a parameter(s), but it is accepting `""` as well as `null`, so I believe there should be version without parameter provided. It's confusing that context is required, while from command line for example it is not.

## Steps To Reproduce
```java
File file = changelogResource.getFile();
File parentFile = file.getParentFile();
Liquibase liquibase = new Liquibase(file.getName(), new FileSystemResourceAccessor(parentFile), getDatabase());
liquibase.update((String)null);
```

## Actual Behavior
`liquibase.Liquibase.update()` requires a parameter(s)

## Expected/Desired Behavior
There will be `liquibase.Liquibase.update()` version without a parameter in API.

## Screenshots (if appropriate)
N/A

## Additional Context
N/A

**Comment by molivasdat** [comment]
Hi @Betlista Thanks for adding this issue.  We will add it to the list of enhancements we are processing.

**Comment by tabbyf00** [comment]
Thanks for your PR submission! We just finished reviewing and merging it into the [4.17.0 release](https://github.com/liquibase/liquibase/releases/tag/v4.17.0) on October 10, 2022. We appreciate your contribution!
