### ISSUE TITLE
Outdated snakeyaml version in documentation

### ISSUE THREAD

**Issue by lukaseder** [liquibase/liquibase#1618]
## Environment
The documentation

## Description
The documentation about using YAML mentions the requirement to use snakeyaml-1.12.jar:
https://docs.liquibase.com/concepts/basic/yaml-format.html

The pom.xml references version 1.24:
https://github.com/liquibase/liquibase/blob/75bc150e4d7281008842d77c0d140c2244284475/base.pom.xml#L77-L82

## Expected/Desired Behavior
I don't think the version number is relevant to the docs. I suggest just removing it.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1095) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
Hi @lukaseder Thanks for writing this up.  Can you move this to our docs repo? [https://github.com/Datical/liquibase-docs/issues](https://github.com/Datical/liquibase-docs/issues
)

**Comment by lukaseder** [comment]
Sure: https://github.com/Datical/liquibase-docs/issues/86
