### ISSUE TITLE
preConditions onSqlOutput TEST configuration does not work for nested changelogs

### ISSUE THREAD

**Issue by dewa-actico** [liquibase/liquibase#1624]
**Liquibase Version**:
3.6.3 (but same code on master)

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
maven

## Description
`onSqlOutput` does not work, if it is used in a nested changelog.

## Steps To Reproduce
* Create a config with changelog A importing changelog B.
* Add a changeset in B with a PreCondition which will always fail.
* Use the `update-sql` command

## Actual Behavior
No error, and any SQL in B will be printed, although the condition failed

## Expected/Desired Behavior
The command stopping/not outputing the SQL in B.

## Workaround
Add an empty `preCondition` config to all "parent" changelogs, with the setting `onSqlOutput: TEST`

## Cause
`liquibase.precondition.core.PreconditionContainer#check` processes preConditions in a top-down way.
Nested Containers will _only_ be evaluated, if the parent's `testPrecondtion` is true:

```
if (testPrecondition) {
    super.check(database, changeLog, changeSet, changeExecListener);
}
```

As soon as one does not or is missing (and defaults to IGNORE), all nested preconditions will not be tested and _all_ SQL will be printed.

**Comment by molivasdat** [comment]
Hi @dewa-actico Thanks for bringing this issue to our attention.  We will add this to the list of issues to process.

**Comment by nvoxland** [comment]
It appears to be working for me. Unless I'm mis-understanding the issue.

I have a root changelog like this:
```
<?xml version="1.0" encoding="UTF-8"?>


<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.4.xsd">

     <include file="com/example/changelog.demo2.xml"/>
</databaseChangeLog>
```

and then  com/example/changelog.demo2.xml like:
```<?xml version="1.0" encoding="UTF-8"?>


<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.4.xsd">


    <changeSet author="author" id="some-id">
        <preConditions onSqlOutput="TEST">
            <tableExists tableName="x"/>
        </preConditions>
        <output>Ran changeset</output>
    </changeSet>

</databaseChangeLog>
```
and running `liquibase update-sql`  gives:
```
Unexpected error running Liquibase: Migration failed for change set com/example/changelog.demo2.xml::some-id::author:
     Reason: 
          com/example/changelog.demo.xml : Table PUBLIC.x does not exist
```


which is correct because onSqlOuput="TEST" 

It may have been fixed since 3.6.3. Or am I setting up the issue incorrectly?

**Comment by dewa-actico** [comment]
Sorry for not providing an example. I'll use the 4.4 example. A precondition inside a changelog seems to work, but defined on a changeset, it does not:

sample.changelog: (parent)
```xml
<?xml version="1.0" encoding="UTF-8"?>

<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:pro="http://www.liquibase.org/xml/ns/pro"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.4.xsd
    http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-4.4.xsd ">

	<include file="blank.changelog.xml"/>

</databaseChangeLog>
```

blank.changelog: (not so blank, included above):
```xml
<?xml version="1.0" encoding="UTF-8"?>

<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:pro="http://www.liquibase.org/xml/ns/pro"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.4.xsd
    http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-4.4.xsd ">
<preConditions onSqlOutput="TEST">
	<tableExists tableName="x"/>
</preConditions>

<changeSet id="1" author="author name">
	<!--Insert XML changes objects here https://www.liquibase.org/documentation/xml_format.html-->
</changeSet>


</databaseChangeLog>
```
Then running
`liquibase.bat update-sql`

Leads to
```sql
-- Create Database Lock Table
CREATE TABLE PUBLIC.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID));

-- Initialize Database Lock Table
DELETE FROM PUBLIC.DATABASECHANGELO...
```

NOW, add a precondition to the sample.changelog (parent) like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:pro="http://www.liquibase.org/xml/ns/pro"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.4.xsd
    http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-4.4.xsd ">

<preConditions onSqlOutput="TEST">
</preConditions>
	<include file="blank.changelog.xml"/>

</databaseChangeLog>
```

As you can see, it is just an empty precondtion, but running
`liquibase.bat update-sql`

will now result in:
```
Unexpected error running Liquibase: Unerwarteter Fehler bei der AusfÃ¼hrung von Liquibase: Validierung war nicht erfolgreich:
     1 Vorbedingungen (PreConditions) sind gescheitert
     sample.changelog.xml : Table PUBLIC.x does not exist
```
Its in german, but it is the same error you got in your `changelog.demo.xml`.

Which is the result I would have expected in the first place. Maybe my assumption is incorrect and this is intentional?

**Comment by nvoxland** [comment]
I added a PR to fix the issue.

Your new example helped a lot, thanks

**Comment by NSC-nwest** [comment]
Hello, I ran into this issue as well. Will this allow me to generate SQL with updateSQL that *ignores* the failures?

parent changelog.yaml:
  - include:
      file: child-changelog.yaml
      relativeToChangelogFile: true

child-changelog,yaml:
databaseChangeLog:
  - preConditions:
    - onSqlOutput: TEST
    - onFail: CONTINUE
    - onFailMessage: "Mocks will not be created."
    - changeLogPropertyDefined:
        property: create-mocks
    
My goal here is to generate the SQL *only* if the create-mocks property is defined, when using the updateSql command. Currently this seems to blow up no matter what I do in the parent changelog (adding onSqlOutput: TEST & onFail: CONTINUE, etc).

The reason I am doing this is for our sandboxes where rebuilding the entire database every time for developers is *time consuming* so we generate the SQL, clean it up, and then run it as a big blob.
