### ISSUE TITLE
indexExists precondition not working for function index in MySQL 8

### ISSUE THREAD

**Issue by eldadko** [liquibase/liquibase#1626]
## Environment
**Liquibase Version**: 3.5.3

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: MySQL 8.0.21

**Operating System Type & Version**: CentOS Linux release 7.8.2003

## Description
When using indexExists precondition on function basked index in MySQL 8 
the precondition return false even when index exists.

## Steps To Reproduce
1. create function index on varchar column in MySQL v8
create index cpe_serial_lower_idx on eldad.cpe ((lower(`serial`)));
1. run liquibase with precondition to check if it exists.
<changeSet id="1.1" author="eldad" dbms="mysql">

```
<preConditions onFail="CONTINUE" onError="CONTINUE" onFailMessage="index already exists">

    <not>
	    <indexExists indexName="cpe_serial_lower_idx" schemaName="eldad"/>
    </not>
			    
</preConditions>
	    
<createIndex tableName="cpe" schemaName="eldad" indexName="cpe_serial_lower_idx">
	    <column name="(lower(serial))"/>
</createIndex>
```

</changeSet>

## Actual Behavior
precondition indexExists return false even when index exists.
for same condition on regular index without function its working fine

## Expected/Desired Behavior
precondition indexExists should be able to verify function index and return true if it exists.

## Additional Context
Just to verify I created cpe_serial_lower_idx as normal index on same table and column and it worked fine.

**Comment by molivasdat** [comment]
Hi @eldadko Thanks for writing up this issue.  I just wanted to clarify.  Is the index a function or is the column name a function?  The reason I am asking is because in the example you have this
`
<column name="(lower(serial))"/>
`
Which means the column name is a function.

**Comment by eldadko** [comment]
Hi @molivasdat ,
The column is a simple column of varchar(64).
The index is function index which is a new functionality for indexes in MySQL 8.
The SQL to create it is - "create index cpe_serial_lower_idx on eldad.cpe ((lower(serial)));"
This syntax <column name="(lower(serial))"/> will make liquibase generate it correctly.

The problem is in the indexExists precondition.

Regards,
Eldad

**Comment by molivasdat** [comment]
Thanks for this @eldadko Knowing that this is new functionality in MySQL v8 helps.  We will add this to list of issues we are processing.
