### ISSUE TITLE
Error reading changelog files from classpath

### ISSUE THREAD

**Issue by AMathew77** [liquibase/liquibase#1635]
I am using Liquibase 4.2.2. When the changelog files are in a jar, it gets executed. But when they are executed directly from eclipse runtime, the absolute path of the files are used. And the `getURI()` invoked on the absolute file path 
throws FileNotFoundException from Liquibase’s SpringResourceAccessor. 
This is because following code from ClassPathResource file returns null for such files
      `Nullable
       protected URL resolveURL() {
             if (this.clazz != null) {
                    return this.clazz.getResource(this.path);
             }
             else if (this.classLoader != null) {
                    return this.classLoader.getResource(this.path);
             }
             else {
                    return ClassLoader.getSystemResource(this.path);
             }
       }`

![Liquibase](https://user-images.githubusercontent.com/30714681/104883549-f2468980-598a-11eb-988b-34fbc16216b7.png)

**Comment by molivasdat** [comment]
Thanks @AMathew77 for writing up this issue.  We will add this to the list of issues we are processing.

**Comment by FBurguer** [comment]
This issue might be solved with the introduction of searchpath. Im closing this issue based on that asumption and time t has pased from the creation of this issue. If someone still has this issue, feel free to re-open it.
