### ISSUE TITLE
Wrong checksum validation for included sql changelog

### ISSUE THREAD

**Issue by Betlista** [liquibase/liquibase#1637]
## Environment
**Liquibase Version**: 4.2.2

**Liquibase Integration & Version**: Spring Boot 2.2.2

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: HSQLDB

**Operating System Type & Version**: Win 10

## Description
Included sql changelog is failing on a checksum validation.

## Steps To Reproduce
I have a changelog.xml, that includes 01-initial.sql.

`changelog.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.2.xsd">

    <include file="01-initial.sql" relativeToChangelogFile="true" />

</databaseChangeLog>
```

`01-initial.sql`

```sql
--liquibase formatted sql

--changeset betlista:1
create table person (
    id int primary key,
    name varchar(50) not null,
    address1 varchar(50),
    address2 varchar(50),
    city varchar(30)
);
--rollback drop table person;

--changeset betlista:2
create table company (
     id int primary key,
     name varchar(50) not null,
     address1 varchar(50),
     address2 varchar(50),
     city varchar(30)
);
--rollback drop table company;

--changeset betlista:3
alter table person add column country varchar(2)
--rollback alter table person drop column country;
```

## Actual Behavior
When `01-initial.sql` is modified - new changeset is added like this

```sql
--liquibase formatted sql

--...same as before...

--changeset betlista:4
insert into company(id, name, city)
values(1, 'Company', 'City');
--rollback delete from company where id = 1;
```

The result is:
liquibase.exception.ValidationFailedException: Validation Failed:
     1 change sets check sum
          01-initial.sql::3::betlistawas: 8:4e145fe322ee57e6be22adf5269bdd22 but is now: 8:99038ad7341567b362588b33dd7a8ec2

## Expected/Desired Behavior
It should be identified, that changeset `betlista:4` is missing and it should be executed.

If the included file is XML changelog, it worked as expected.

## Screenshots (if appropriate)
N/A

## Additional Context
N/A

**Comment by molivasdat** [comment]
Hi @Betlista Thanks for bringing this issue to our attention.  We will add it to the list of issues that we are processing.
