### ISSUE TITLE
ChangeExecListener-API cannot be used due to HubChangeExecListener

### ISSUE THREAD

**Issue by ckulenkampff** [liquibase/liquibase#1651]
## Environment
**Liquibase Version**: 4.2.2

**Liquibase Integration & Version**: Java 1.8

## Description
The API for providing a custom `ChangeExecListener` is broken, because the internal `HubChangeExecListener` is now obligatory.

## Steps To Reproduce
* Implement a custom `ChangeExecListener`
* Provide it to `Liquibase` through `Liquibase.setChangeExecListener(ChangeExecListener)`
* Perform an update like `Liquibase.update(String)` that directly accesses the database

## Actual Behavior
A `RuntimeException` _ChangeExecListener already defined_ is thrown.

## Expected/Desired Behavior
The provided `ChangeExecListener` is used without an exception. Being able to add multiple `ChangeExecListener` would be optimal.

## Additional Context
Currently I use the `ChangeExecListener` for adding database specific setup commands when the first changeset is actually executed.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1151) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 4.3.1,Community 4.3.1

**Comment by molivasdat** [comment]
Hi @ckulenkampff Thanks for reporting this error.  We are looking to have a fix pretty soon on this issue. Stay tuned.
