### ISSUE TITLE
Liquibase Diff/Changelog generating unique constraints that have columns repeated multiple times

### ISSUE THREAD

**Issue by srikarncino** [liquibase/liquibase#1654]
## Environment
**Liquibase Version**:
4.2.1
**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
Maven Pluging, 4.2.1
**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
Maria DB Source - 10.3.18-MariaDB
Maria DB Targer 10.3.27-MariaDB

**Operating System Type & Version**:
Mac OS 10.15.7

## Description
Liquibase Diff/Changelog generating unique constraints that have columns repeated multiple times
e.g.
`ALTER TABLE tableName ADD CONSTRAINT id UNIQUE (id, id, id, id, id, id, id, id, name, name);`

## Steps To Reproduce
`mvn resources:resources liquibase:diff -Dliquibase.diffChangeLogFile=diff.mariadb.sql -Dliquibase.username=<username> -Dliquibase.password=<pass> -Dliquibase.referenceUrl="<prod url>" -Dliquibase.referenceUsername=<prod username> -Dliquibase.referencePassword=<prod password>`

## Actual Behavior
columns are included multiple times in the unique constraint

## Expected/Desired Behavior
columns should only be included once
`ALTER TABLE tableName ADD CONSTRAINT id UNIQUE (id, name);`

**Comment by molivasdat** [comment]
Thanks @srikarncino for reporting this issue.  We will add this to the list of issues that we are processing.
