### ISSUE TITLE
Update (or any other command) with label also include changelogs without labels.

### ISSUE THREAD

**Issue by amarjeetkapoor1** [liquibase/liquibase#1660]
If I issue an update command with the label "a". It also applies a changelog without any label.

e.g.

```
<changeSet author="amarjeetkapoor" id="1" labels="a">
     <createIndex ....</createIndex>
 </changeSet>
 <changeSet author="amarjeetkapoor" id="2" >
     <createIndex ....</createIndex>
 </changeSet>
```

and I ` liquibase.changeLogSync(new Contexts(this.getContexts()), new LabelExpression("a"));` or ` liquibase.update(new Contexts(this.getContexts()), new LabelExpression("a"));`

changelog with id 2 is also getting logged in DB, when It should be just changelog with id ="1" as that only have been labeled "a"

Plus, there is no way to mention label expression to say not to include changelogs without a label.

Version of liquibase: 4.0.0

**Comment by molivasdat** [comment]
Hi @amarjeetkapoor1 Yes that is how Liquibase works.  If there is no label, it is eligible to be deployed to the database.
https://docs.liquibase.com/concepts/advanced/labels.html
If you run the liquibase --labels=release3 update command, it will deploy all changesets with the label release3 and all changesets without any label.

**Comment by FBurguer** [comment]
As Mike said, this is how liquibase is designed. I dont belive we are changing that behavior any time soon.
