### ISSUE TITLE
read configuration file variables

### ISSUE THREAD

**Issue by lixiaolei-zoya** [liquibase/liquibase#1666]
Does it support updating data when executing scripts and reading variables from configuration files？

**Comment by molivasdat** [comment]
Hi @lixiaolei-zoya 
You can update data using the following.
https://docs.liquibase.com/change-types/community/load-data.html
You can also read variables from the liquibase.properties file.
https://docs.liquibase.com/workflows/liquibase-community/creating-config-properties.html
You can also check out the getting started guide for further info.
https://www.liquibase.org/get-started

**Comment by FBurguer** [comment]
This is issue is stale. Closing it for now.
