### ISSUE TITLE
sqlFile ignores encoding parameter

### ISSUE THREAD

**Issue by osobolev** [liquibase/liquibase#1670]
## Environment
**Liquibase Version**: 4.2.2 (seems like all 4.x versions have this behaviour)

**Liquibase Integration & Version**: CLI

**Database Vendor & Version**: PostgreSQL 12.4

**Operating System Type & Version**: Windows 10

## Description
sqlFile always uses system encoding instead of encoding specified by change parameter.

## Additional Context
Look at the source code of SQLFileChange: `encoding` field is not used when reading SQL source code:
`                String content = StreamUtil.readStreamAsString(sqlStream);`

In fact, `encoding` field is not used anywhere.

This problem manifests only when default encoding is not UTF-8. There are other suspicious calls of StreamUtil.readStreamAsString without encoding parameter, which can lead to other bugs.

**Comment by d37h** [comment]
+ 1 on this

**Comment by molivasdat** [comment]
Hi @osobolev Thanks for writing about this issue.  If you have a suggested fix for adding encoding, it would be great if you could add a PR with the fix and we will process add it to the list of issues to process.

**Comment by EGlaznev** [comment]
duplicated by https://github.com/liquibase/liquibase/issues/1760
'encoding' was used in 3.x - just see history

**Comment by MarcusGrahm** [comment]
Hi all.

Still waiting for a fix to have encoding managed when sqlFile is used.
With last version 4.5.0 it is still not fixed.
Very bad news for applications having accents to be displayed, or managed
It is planned to be fixed or not ?
Thanks
Regards

**Comment by FBurguer** [comment]
Looks like its no longer an issue on `4.14`.  The way I verified this was:
Having a `ñ` on my sqlfile, using `encoding="ascii"` and it failed (because `ñ` is not in ascii table). 
If you still have the same issue as before, please repon the issue with the changeset that is failing if possible. Thanks!
