### ISSUE TITLE
addColumn ignores deleteCascade

### ISSUE THREAD

**Issue by rsaccoccio** [liquibase/liquibase#1671]
addColumn ignores deleteCascade:

* addColumn:
    tableName: run_data
    columns:
  * column:
          name: PARENT_RUN_ID
          type: VARCHAR(36)
          constraints:
            foreignKeyName: RUN_DATA_FK02
            references: RUN_DATA(RUN_ID)
            deleteCascade: true

generates:

"ALTER TABLE x.run_data ADD PARENT_RUN_ID VARCHAR(36)"
"ALTER TABLE x.run_data ADD CONSTRAINT RUN_DATA_FK02 FOREIGN KEY (PARENT_RUN_ID) REFERENCES x.RUN_DATA (RUN_ID)"

deleteCascade from inside addTable and addForeignKeyConstraint generate the correct SQL, e.g.: 

* addForeignKeyConstraint:
    baseColumnNames: parent_run_id
    baseTableName: run_data
    constraintName: run_data_fk02
    onDelete: CASCADE
    referencedColumnNames: run_id
    referencedTableName: run_data

generates:

"ALTER TABLE x.RUN_DATA ADD CONSTRAINT RUN_DATA_FK02 FOREIGN KEY (PARENT_RUN_ID) REFERENCES x.RUN_DATA (RUN_ID) ON DELETE CASCADE"

**Comment by molivasdat** [comment]
Hi @rsaccoccio Thanks for writing up this issue.  There is not attribute deleteCascade on a column type in liquibase.
https://docs.liquibase.com/change-types/community/add-column.html?Highlight=add%20column#Informa

**Comment by nvoxland** [comment]
I have a fix in #1970 for this
