### ISSUE TITLE
ClassLoaderResourceAccessor non-functional in Maven-like SetUp

### ISSUE THREAD

**Issue by EliasHeydrich** [liquibase/liquibase#1673]
## Environment
**Liquibase Version**: 4.2.2
**Liquibase Integration & Version**: Maven

## Description
I have a schema-file (XML) which I want to load using the _Resource_-Functionality, that means by classpath, so that JAR-compatiblity is ensured. After struggling with the `ClassLoaderResourceAccessor` for a while now, I believe it is currently non-functional in certain cases, as it refuses to find the schema-file while loading the resource using plain Java works.

I believe this might be an unintended side-effect of the attempt to remove absolute paths in 4.0.0, even if that error message is still used inflationary in the current implementation.
Details follow below:

## Steps To Reproduce
In the example below, my schema-file is named _my_schema.xml_ and is located in _main/resources/dbschema_, that is a subfolder of the Maven-managed resources folder.
The overall inconsistency can be demonstrated by actually asking the _accessor_ about what is present in said subfolder:

```
    var accessor = new ClassLoaderResourceAccessor(Thread.currentThread().getContextClassLoader()); //just to be explicit

    //instead of an hard-coded access, let's ask the accessor what resources we have (and there is only one file in that folder):
    var set = accessor.list(null, "dbschema", true, true, true);
    if (set.size() != 1) throw new RuntimeException("TEST SETUP BROKEN!");
    var mySchemaFile = set.first(); //resolves to 'dbschema/my_schema.xml'

    return new Liquibase(mySchemaFile, accessor, db); //the file is not found *despite* reporting its presence
```

To date, I have not managed to load any of my resources using `ClassLoaderResourceAccessor`.

Note that variable `db` is not relevant, use any database you want.

## Additional Context
The `ClassLoaderResourceAccessor` is functional for all the Liquibase-internal resources, hence an ugly workaround, inspired by the Mock-Accessor, is successful:

```
var stream = getClass().getResourceAsStream("/dbschema/my_schema.xml"); //note the use of an absolute path here
var reader = new BufferedReader(new InputStreamReader(stream));
var content = reader.lines().collect(Collectors.joining());
reader.close();
return new Liquibase( LiquibaseSchemaContentInjector.MAGIC_STR, new LiquibaseSchemaContentInjector( content ), db);

//(...)

/** Acts like a {@link liquibase.resource.ClassLoaderResourceAccessor} but injects a custom Schema if asked for one. */
public class LiquibaseSchemaContentInjector extends AbstractResourceAccessor {

    public static String MAGIC_STR = "my_schema.xml";
    private final byte[] changeLog;
    private final AbstractResourceAccessor forwardTo;

    public LiquibaseSchemaContentInjector( String changelogContent ){
        try {
            changeLog = changelogContent.getBytes(LiquibaseConfiguration.getInstance().getConfiguration(GlobalConfiguration.class).getOutputEncoding());
        } catch (Exception e){
            throw new RuntimeException(e);
        }
        forwardTo= new ClassLoaderResourceAccessor();
    }

    @Override
    public InputStreamList openStreams(String relativeTo, String streamPath) throws IOException {
        if (streamPath.equals(MAGIC_STR)) {
            InputStream stream = new ByteArrayInputStream(changeLog);
            InputStreamList list = new InputStreamList();
            list.add(URI.create(streamPath), stream);
            return list;
        } else return forwardTo.openStreams(relativeTo, streamPath);
    }

    //the other methods just "forward" as well
}
```

**Comment by molivasdat** [comment]
Hi @EliasHeydrich Thanks for your explanation of the problem.  We have just made a bunch of adjustments to loading of files in 4.3.1 and will be adding one additional fix in 4.3.2.  Please try that and see if it resolves your issue.  Can you also update the version of Liquibase that you found this.  I think there may be a typo in the version in the description section.  (4.4.2)

**Comment by EliasHeydrich** [comment]
You are correct, I had a **typo** in the version.

 I was using 4.2.2, however I can now **confirm that the issue is still reproducable with 4.3.1** using the method above.

**Comment by FBurguer** [comment]
This issue got stale. Closing it for now. You are welcome to reopen it you still have the same issue. Thanks!

**Comment by jpincz** [comment]
I've encountered the same issue while working on a Maven project, specifically when attempting to use an XML changelog file situated at the root of the classpath. Although the resource accessor successfully lists the file, it is subsequently reported as "not found."

```
Liquibase liquibase = new Liquibase("someChangelogFile.xml", new ClassLoaderResourceAccessor(Thread.currentThread().getContextClassLoader()), database);
liquibase.update("test");
```

Upon debugging, I was able to trace the problem back to these lines inside the parseToNode method of the XMLChangeLogSAXParser class:

```
LiquibaseEntityResolver resolver = new LiquibaseEntityResolver(this);
resolver.useResoureAccessor(resourceAccessor, FilenameUtils.getFullPath(physicalChangeLogLocation));
```

I performed testing across the following versions, all of which exhibited the same behavior:

4.22.0
4.17.2
4.16.0
4.2.2
3.8.6
