### ISSUE TITLE
Liquibase doesn't validate bad formatted SQL changesets

### ISSUE THREAD

**Issue by szandany** [liquibase/liquibase#1675]
## Environment
Formatted SQL changelogs

**Liquibase Version**:
Any

**Liquibase Integration & Version**: 
CLI

**Database Vendor & Version**:
Any supported database

**Operating System Type & Version**:
Win, Linux

## Description
When running the `validate` or `status` or `update` commands, Liquibase should go over the changesets in the target changelog (Formatted SQL, XML, JSON and YAML) and check for any **Liquibase related syntax errors**.

However, it appears that the case is inconsistent for Formatted SQL changelogs.
If the structure of a Formatted changeset is **incorrect** or have **bad syntax**, Liquibase **will just skip that changeset**.

## Steps To Reproduce
1. Run the below changesets.  Notice that the first changeset starts with a single “-“ instead of double “--“.  Also notice that the second changeset is missing a unique ID (only has an author "SteveZ").

```
--liquibase formatted sql
-changeset SteveZ:45555-createtablecontacts labels:onlytest
CREATE TABLE contacts (
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
firstname VARCHAR(255),
lastname VARCHAR(255)
);
--rollback drop table contacts;
```

```
--changeset SteveZ
CREATE TABLE actor (
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
firstname VARCHAR(255),
lastname VARCHAR(255)
);
--rollback drop table actor;
```

## Actual Behavior
After running the update command the changesets will be skipped.

## Expected/Desired Behavior
Liquibase should throw an error indicating the there is something wrong with the changesets.

**Comment by XDelphiGrl** [comment]
I also reproduced this issue using a formatted SQL changelog; in my case, I tried both with a duplicated changeset and by changing SQL in deployed changesets. As you found, @szandany, this feature does not work as expected. 

Thanks for writing this up!
