### ISSUE TITLE
Increase minimum java version from 8 to 11

### ISSUE THREAD

**Issue by nvoxland** [liquibase/liquibase#1677]
## Description
Currently, Liquibase is compiled and tested with Java 8, in order to support people running it in environments running against that version. We don't ship Java 8 ourselves, we just compile against it and therefore support it.

It is getting more difficult to get build images to compile with 8, and tools such as Sonarcloud are dropping support for scanning builds using it. Compiling against 8 also limits the Java syntax and functionality we can take advantage of in the code.

Java 8 no longer receives public updates, but does have "premier" support until March 2022. https://www.oracle.com/java/technologies/java-se-support-roadmap.html

## Impact
**If we change our build process to build with/for Java 11, it will block anyone using a Java 8, 9, or 10 from using new Liquibase versions.**

## Questions
* At what point do we drop Java 8 support?

**Comment by molivasdat** [comment]
Java 9, and 10 are non-issues since they no longer have support. So it would be supporting 8 that would be the main question for people.

**Comment by nvoxland** [comment]
I'm going to close this issue.

Numbers vary depending on survey methods, but no matter how you slice it, still a lot of java 8 usage still in 2022 and likely long-term:
- 46% of users https://newrelic.com/resources/report/2022-state-of-java-ecosystem 
- 37% of users https://www.infoworld.com/article/3652408/java-8-still-dominates-but-java-17-wave-is-coming-survey.html
- 60% of users https://snyk.io/jvm-ecosystem-report-2021/ 
- 16% of users https://www.continuum.be/en/blog/the-java-ecosystem-2022-survey-results/

As we work on our build process, we are starting to build with java 17 and just target java 8 and test with java 8. But we can't stop dropping 8 support completely unfortunately or we'll limit access to a still-large portion of users.
