### ISSUE TITLE
Add support for Indexes with Included Columns

### ISSUE THREAD

**Issue by olegtaranenko** [liquibase/liquibase#1697]
Liquibase doesn't support "Indexes with Included Columns". See https://docs.microsoft.com/en-us/sql/relational-databases/indexes/create-indexes-with-included-columns?view=sql-server-ver15 for more info
Currently, this kind of new Indexing is using on MS-SQL, Postgres, and others

Possible Format

```
<createIndex indexName="index_one" tableName="department">
      <column name="col_1"/>
      <column name="col_2" includedColumn="true"/>
      <column name="col_3"/>
  </createIndex>
```

which should produce 

```
create index index_one
	on department ( col_1, col_3) include ( col_2)

```

Of course, it also should be supported by `generateChangeLog ` command, which required more investigation on system catalog information.

PS. Interesting article with basics: https://use-the-index-luke.com/blog/2019-04/include-columns-in-btree-indexes

**Comment by molivasdat** [comment]
Hi @olegtaranenko Thanks for adding this suggestion.  We will add it to our list of issues that we are processing.

**Comment by Emmanuel312** [comment]
Any update?

**Comment by amolpednekar** [comment]
Is there still no support for this feature in liquibase?
