### ISSUE TITLE
logicalFilePath is case insensitive but the update on databasechangelog is case sensitive

### ISSUE THREAD

**Issue by herbinator** [liquibase/liquibase#1707]
## Environment
**Liquibase Version**: 3.10.2

**Liquibase Integration & Version**: maven spring boot

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: postgress 11

**Operating System Type & Version**: centos 7

## Description
I have a changeset with: runOnChange="true" logicalFilePath="changelog.xml"
In the databasechangelog there is already a  record with filename='changeLog.xml'   (with uppercase L)
when the runonchange takes effect liquibase updates the change but the update statement is_> and FILENAME = 'changelog.xml'  So in the end the update does nothing end liquibase status keeps saying: 1 change sets have not been applied to

The update should be case insensitive

## Steps To Reproduce
List the steps to reproduce the behavior.
changeset with: runOnChange="true" logicalFilePath="changeLog.xml"
run it.
change it to changeset with: runOnChange="true" logicalFilePath="changelog.xml" and make sure the sqlfile is changed

## Actual Behavior
the update is case sensitive for FILENAME column in the where clause

## Expected/Desired Behavior
Do the update with FILENAME case insensitive or liquibase should fail if the update statement updates 0 rows

**Comment by molivasdat** [comment]
Hi @herbinator Thanks for writing up this issue.  I agree we need to be consistent with our documentation.  As far as is changelog and changeLog the same I will have to do more analysis on how it works today.

**Comment by FBurguer** [comment]
liquibase `4.14` is case insensitive, liquibase is going to consider changelog.xml and changeLog.xml as the same changelog, if there isnt any changes, liquibase is not going to do anything. If you continue to have the same issue, please open this issue again!
Thanks!

**Comment by Qub1** [comment]
It seems like one of the latest updates in Liquibase has caused a regression for this functionality, as we are now running into the same issue on version 4.31.1. The `filename` column in the database has a capital letter, the `logicalFilePath` does not, causing a changelog to be re-applied when it already was which breaks deployment. Changing the `logicalFilePath` to match what is in the database fixes the issue.

Is this intended behavior with the latest release? I noticed the changelog mentioning changes to the `logicalFilePath` attribute but I don't see mention of it now being case-sensitive.
