### ISSUE TITLE
IBM DB2z Database - INFORMATION_SCHEMA.CONSTRAINTS table not found Exception

### ISSUE THREAD

**Issue by dileepan91** [liquibase/liquibase#1730]
## Environment
**Liquibase Version**: 4.2.2

**Liquibase Integration & Version**: Maven

**Liquibase Extension(s) & Version**: NA

**Database Vendor & Version**: com.ibm.db2:db2jcc_license_cisuz & 9.7.5

**Operating System Type & Version**: Windows 7 Enterprise

## Description
I tried to implement Liquibase for my IBM DB2 zos database and when i run liquibase:generateChangeLog command, I’m getting the following error.

Error setting up or running Liquibase: liquibase.command.CommandExcecutionExceptoin: liquibase.exception.DatabaseException: Error executing SQL select CONSTRAINT_NAME, COLUMN_LIST as COLUMN_NAME, constraint_schema as CONSTRAINT_CONTAINER from information_schema.constraints where constraint_type=‘UNIQUE’ and …; DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=INFORMATION_SCHEMA.CONSTRAINTS, DRIVER=4.25.13

SQLCODE=-204, object not found, Basically the table/schema is not found.

When I ran the same command in debug mode, I could see that in the following class, liquibase/UniqueConstraintSnapshotGenerator.java at master · liquibase/liquibase · GitHub there is no logic to handle DB2z and hence it is considering no specific handler for RDBMS was provided and assuming INFORMATION_SCHEMA.

We do have logic for DB2Database, but not DB2ZDatabase .

## Steps To Reproduce
1. Create a maven project
1. Add the following dependencies in pom.xml
  * com.jbm.db2:db2jcc4 & 4.25.13
  * com.ibm.db2:db2jcc_license_cisuz & 9.7.5
1. Add the following plugin to pom.xml
  * org.liquibase:liquibase-maven-plugin & 4.2.2
  * in the <configuration> tag, add <propertyFile> and specify the property file liquibase-dev.properties to run
1. In the property file liquibase-dev.properties, I specified the follwoing
  * url(jdbc:db2://<hostname>:<port>/currentSchema=<schemaName>;) , username, password, ouputChangeLogFile, driver(com.ibm.db2.jcc.DB2Driver).
1. Run mvn clean and run mvn liquibase:generateChangeLog

## Actual Behavior
When I run mvn liquibase:genereateChangeLog, I'm getting the below error,

Error setting up or running Liquibase: liquibase.command.CommandExcecutionExceptoin: liquibase.exception.DatabaseException: Error executing SQL select CONSTRAINT_NAME, COLUMN_LIST as COLUMN_NAME, constraint_schema as CONSTRAINT_CONTAINER from information_schema.constraints where constraint_type=‘UNIQUE’ and …; DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=INFORMATION_SCHEMA.CONSTRAINTS, DRIVER=4.25.13

## Expected/Desired Behavior
mvn liquibase:generateChangeLog should generate the change log for IBM DB2z based on the current specified database schema.

**Comment by molivasdat** [comment]
Hi @dileepan91 Thanks for writing up the issue.  We will add this to the list of issues to process.  In the meantime if you have the code to fix it, please submit a PR so that we can incorporate the fix.

**Comment by dileepan91** [comment]
Hi @molivasdat , Thank you. I have raised an PR (https://github.com/liquibase/liquibase/pull/1771) for this fix.

**Comment by nvoxland** [comment]
This was fixed in #1771 in 4.5.0
