### ISSUE TITLE
The XSD misses the message attribute for the <stop> change

### ISSUE THREAD

**Issue by Vampire** [liquibase/liquibase#1734]
## Environment
**Liquibase Version**: 4.3.1

**Liquibase Integration & Version**: n/a

**Liquibase Extension(s) & Version**: n/a 

**Database Vendor & Version**: n/a

**Operating System Type & Version**: n/a

## Description
The XSD misses the `message` attribute for the `<stop>` change

**Comment by nvoxland** [comment]
It's maybe more of a doc issue? 

In XML, the message for "stop" is the body of the element. Like `<stop>testing this out</stop>`.

But, for yaml and json, there is nothing that corresponds to "the element body" so we have a "message" attribute, like:
```
stop:
    message: testing this output
```

We certainly could support both a message attribute and the text body in XML, but that opens up questions on "what if you specify both a message and a body?" so I'm not sure if the consistency with yaml/json is better or worse.

We have the same sort of thing with `<sql>my sql here</sql>` vs an "sql" attribute inside it for yaml/json.

I'll open a doc ticket to fix the docs at least. What do people think on also adding a "message" attribute to the XML?

**Comment by FBurguer** [comment]
Open a discussion on [Liquibase forum](https://forum.liquibase.org/t/stop-changetype-message-attribute/7316)

**Comment by FBurguer** [comment]
Now that the liquibase forum discussion is open, Im closing this issue, becasue is how it was designed, but if you want the change the behavior, please go ot the forum post above and share your opinion. Thanks!
