### ISSUE TITLE
addForeignKeyConstraint documentation is inconsistent regarding SQLite

### ISSUE THREAD

**Issue by Vampire** [liquibase/liquibase#1735]
On https://docs.liquibase.com/change-types/community/add-foreign-key-constraint.html SQLite is listed as not supported because in SQLite you can only add foreign keys on table creation but not later.
But for the attributes `deferrable` and `initiallyDeferred` the `Supports` column shows SQLite which is of course wrong and just confusing as the whole change is not supported.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1310) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
Hi @Vampire Thanks for reporting this issue.  Can you close this and move it over to our [docs repo](https://github.com/Datical/liquibase-docs) to get fixed?

**Comment by Vampire** [comment]
Datical/liquibase-docs#105
