### ISSUE TITLE
deleteCascade="true" on addForeignKeyConstraint is simply ignored

### ISSUE THREAD

**Issue by Vampire** [liquibase/liquibase#1736]
## Environment
**Liquibase Version**: 4.3.1

**Liquibase Integration & Version**: n/a

**Liquibase Extension(s) & Version**: n/a 

**Database Vendor & Version**: Oracle and MSSQL

**Operating System Type & Version**: n/a

## Description
If you have an `addForeignKeyConstraint` change with attribute `deleteCascade="true"` it is simply ignored.
This code: https://github.com/liquibase/liquibase/blob/43ed0e54adedc5f12c7933b998550e777d9b683d/liquibase-core/src/main/java/liquibase/change/core/AddForeignKeyConstraintChange.java#L195-L199 suggests that it should be automatically translated to `onDelete="CASCADE"` which would make sense, but it is not.
It currently is simply ignored.

**Comment by molivasdat** [comment]
Hi @Vampire Thanks for creating this issue.  Do you have an example changeset that we can use to reproduce this issue?

**Comment by Vampire** [comment]
```xml
   <changeSet id="xxx" author="n/a">
      <addForeignKeyConstraint baseTableName="BASE_TABLE" baseColumnNames="BASE_COLUMN" referencedTableName="OTHER_TABLE" referencedColumnNames="OTHER_COLUMN" constraintName="FK_BASE_OTHER" deleteCascade="true"/>
   </changeSet>
```
