### ISSUE TITLE
Documentation mistake - quotes in yaml for dbms

### ISSUE THREAD

**Issue by vs-slavchev** [liquibase/liquibase#1753]
## Environment
**Liquibase Version**: 3.6.2

**Liquibase Integration & Version**: maven

**Operating System Type & Version**: ubuntu 20.04

## Description
In the documentation it is said that for the sql change type the dbms needs to be spicified with quotes, but does not work. It actually works fine without quotes. Just an update of the documentation is needed.

## Steps To Reproduce
Use `dbms: 'postgresql'` and the migration will not be executed and no errors will be thrown.

## Expected/Desired Behavior
Software should behave as it is, just documentation needs updating

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1337) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
Hi @vs-slavchev Thanks for writing up this issue.  Please close this and add an issue to update the documentation here.
https://github.com/Datical/liquibase-docs/issues
You can also submit a PR to fix it too.
https://github.com/Datical/liquibase-docs/pulls
