### ISSUE TITLE
<sqlFile> change does not respect encoding attribute as mentioned in the documentation

### ISSUE THREAD

**Issue by ckulenkampff** [liquibase/liquibase#1760]
## Environment
**Liquibase Version**: 4.3.1

**Liquibase Integration & Version**: Java 1.8 (custom Gradle plugin)

**Operating System Type & Version**: Windows 10

## Description
The documentation (https://docs.liquibase.com/change-types/community/sql-file.html) describes a very useful attribute for the &lt;sqlFile&gt; change: _encoding - Specifies encoding used in the file defined in the `path` attribute._

This attribute is not processed by the &lt;sqlFile&gt; change implementation and thus does not work.

## Steps To Reproduce
1. Create a changelog with a changeset containing a &lt;sqlFile&gt; change that refers to some SQL file with UTF-8 encoded special characters.
1. Set encoding attribute to UTF-8 (which is an example value directly from the XSD schema)
1. Generate SQL with Liquibase while using a default file encoding for the JVM other than UTF-8.

## Actual Behavior
The generated SQL contains wrongly rendered characters.

## Expected/Desired Behavior
The generated SQL contains characters as given in the provided SQL file referred by the &lt;sqlFile&gt; change.

**Comment by ckulenkampff** [comment]
I think it's really simple to fix. In `liquibase.util.StreamUtil.readStreamAsString(InputStream)` use `StreamUtil.readStreamAsString(sqlStream, getEncoding())` instead of `StreamUtil.readStreamAsString(sqlStream)`.

**Comment by molivasdat** [comment]
Hi @ckulenkampff Thanks for writing up this issue and the suggestion for the fix.  We will add this to the list of issues to process.  If you want to create a PR with your fix that may speed up the process.

**Comment by henrikthuesen** [comment]
Just to save others some work; I used the following workarounds:

For the CLI, one can simply set the system property `file.encoding` to the encoding of the SQL files (they must all have the same encoding).

When using the Java API, one can use the following:

```
Scope.child(Scope.Attr.fileEncoding, Charset.forName(fileEncoding), () -> liquiBase.update(new Contexts()));
```

**Comment by EGlaznev** [comment]
this issue totally blocks changeSets with different encoding in the sql-files. which is usual practice for multilingual projects. 'ImpactLow' - I'm not sure... :)
and 'the fix' is recorded in source of 3.x versions already - just see diff 3.9.x/4.0.x

**Comment by molivasdat** [comment]
Hi @EGlaznev Thanks for the update. We will add this to the list of issues to process.
In the meantime, you can take the artifact from https://github.com/liquibase/liquibase/pull/1941 as an interim fix and use that to get past your blocked changeSets.
