### ISSUE TITLE
Postgres Functions and Question Marks

### ISSUE THREAD

**Issue by juszczakn** [liquibase/liquibase#1764]
## Environment
**Liquibase Version**: 4.3.1

**Liquibase Integration & Version**: maven + CLI

**Liquibase Extension(s) & Version**:  NA

**Database Vendor & Version**: Postgresql 11

**Operating System Type & Version**: Ubuntu 18.04

## Description
Encountered this bug today, as described in this forum post:
[https://forum.liquibase.org/t/postgres-functions-and-question-marks/4947](https://forum.liquibase.org/t/postgres-functions-and-question-marks/4947)

In essence, SQL changeSets are transforming the Postgres `?` JSON operator into `??`, causing function definitions using this operator to become invalid.

## Steps To Reproduce
Copying the example from the forum post, as it seems identical to the situation I was seeing:

```java
<databaseChangeLog 
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.10.xsd ">

    <changeSet  author="test"  id="1">  
        <sql endDelimiter="/">
CREATE FUNCTION public.x()
    RETURNS void
    LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
INSERT INTO test (results)
SELECT '{"a":1, "b":2}'::jsonb ? 'b';
END;
$BODY$;
/
        </sql>
    </changeSet>
</databaseChangeLog>
```

The line `SELECT '{"a":1, "b":2}'::jsonb ? 'b';` will be transformed into `SELECT '{"a":1, "b":2}'::jsonb ?? 'b';` when ran, which is invalid.

This appears to have been caused by [https://github.com/liquibase/liquibase/pull/912](https://github.com/liquibase/liquibase/pull/912) as far as I can tell. I haven't been able to test and confirm this, however.

```java
if (database instanceof PostgresDatabase) {
                statement = statement.replaceAll("(^|[^\\?])\\?(?!\\?)(?=([^']*'[^']*')*[^']*$)", "$1??");
            }
```

## Actual Behavior
A clear and concise description of what happens in the software **before** this pull request.

* Include console output if relevant
* Include log files if available.

## Expected/Desired Behavior
A clear and concise description of what happens in the software **after** this pull request.

## Test Requirements (Internal Liquibase QA)
* No new automated functional tests are required for this fix.

**Manual Test Requirements**

* Use the attached lb-1350.xml changelog for testing.

_Verify update-sql does not include double question marks in the SELECT statement._

_Verify update is successful._
_Verify on database that the SQL for function x does not include double question marks in the SELECT._

_Verify generate-changelog does not include double question marks in the SELECT._

┆Issue is synchronized with this [Jiraserver Bug](https://datical.atlassian.net/browse/LB-1350) by [Unito](https://www.unito.io)

**Comment by molivasdat** [comment]
Hi @juszczakn Thanks for alerting us to this issue.  We will add this to the list of issues we are processing.
Thanks for the changeset that show the errors.  It is really helpful to have an example scenario to help fix the issue.

**Comment by marcjay** [comment]
Hitting this issue as well on 4.3.5 with an `<sqlFile></sqlFile>` that has a PostgreSQL function that concatenates a string that contains a ? in order to build a URL:
```
foo || '?k=' || bar
```
This is being transformed incorrectly to
```
foo || '??k=' || bar
```
Would be great too see this bug fixed otherwise we're stuck at 3.10.2 which is the last version before this change

**Comment by marcjay** [comment]
@molivasdat please would you consider re-assessing the severity/impact of this issue. I would argue at least one of these should be higher, given Liquibase is mangling SQL when it runs, resulting in creating invalid functions in our case. This seems like a particularly pernicious bug. Thank you

**Comment by molivasdat** [comment]
Hi @marcjay We can take a look again at the impact.  Would be curious to see if there are other community members seeing this issue too, if you could upvote the description section.

**Comment by nvoxland** [comment]
Hunting through the bug history and postgresql logic, I'm not finding a reason for the problem code.

JDBC can try to treat ?'s as parameters, but it also understands when it is being used as an operator too so there should be no need to 2nd guess what SQL the user is giving us. I tried a variety of statements with ?'s in them and they worked fine with the problem code taken out.

The original CORE-3379 issue was talking primarily about oracle as well, so there was no information in there as to what required the escaping in the first place either.

So, since I could find no reasons for the escaping and only problems caused by it, I took it out in #1877

**Comment by rzozmann** [comment]
With the update 4.4.2 -> 4.4.3 we become the problem, that our  SQL statement are not longer working if they contain checks for postgres JSON functionality. Example:
CREATE TABLE "example" (
    name JSONB NOT NULL CHECK(name?'de'),
);
The '?' will be replaced by liquibase with an $1 and ends with an sql error
