### ISSUE TITLE
Liquibase loadUpdateData doesn't properly insert H2 column text 'scale values mean'

### ISSUE THREAD

**Issue by ro-rah** [liquibase/liquibase#1767]
## Environment
**Liquibase Version**: 4.3

**Liquibase Integration & Version**: maven (but reproduces on CLI too)

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: H2

**Operating System Type & Version**:

## Description
Here is the description with a workaround:
https://forum.liquibase.org/t/cant-insert-the-string-scale-values-mean-without-it-being-changed/5121

## Steps To Reproduce
* Have Liquibase installed in the commandline (latest is fine, 4.3 as of this issue)
* git clone: https://github.com/MAYarbrough/LiquibaseH2Issue
* do a liquibase update SQL 

## Actual Behavior
Changeset rendered:
-- Changeset db.changelog-master.yaml::1595012255439-41::myarbrou
-- WARNING The following SQL may change each run and therefore is possibly incorrect and/or invalid:
MERGE INTO PUBLIC.usage_agreement_terms (version, text, start_date) VALUES ('v1.0', **'scale KEY(version) values mean',** '2021-02-12');

## Expected/Desired Behavior
Changeset should be:
-- Changeset db.changelog-master.yaml::1595012255439-41::myarbrou
-- WARNING The following SQL may change each run and therefore is possibly incorrect and/or invalid:
MERGE INTO PUBLIC.usage_agreement_terms (version, text, start_date) VALUES ('v1.0', **'scale values mean'**, '2021-02-12');

**Comment by molivasdat** [comment]
Hi @ro-rah Thanks for creating this issue and for the excellent steps to help show the error.  It really helps to have a failing scenario defined and easy to recreate.  We will add it to the list of issues that we are processing.
