### ISSUE TITLE
ObjectQuotingStrategy doesn't qoute value from insert statement

### ISSUE THREAD

**Issue by kuhjunge** [liquibase/liquibase#1769]
## Environment
**Liquibase Version**: 3.8 &  4.3.0 

**Liquibase Integration & Version**: gradle

**Liquibase Extension(s) & Version**: -

**Database Vendor & Version**:  mssql server:2017-latest

**Operating System Type & Version**: Linux / Fedora

## Description
I use the objectQuotingStrategy="QUOTE_ALL_OBJECTS", but liquibase generates following insert statement:
`INSERT INTO TestTable (TestRow) VALUES (NULL);`
where NULL will not be interpreted as nvarchar and fail in certain situations (
"Cannot insert the value NULL into column 'TestRow', table 'demo.dbo.TestTable'; column does not allow nulls. INSERT fails.").

## Steps To Reproduce
Changelog:

```
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:pro="http://www.liquibase.org/xml/ns/pro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-3.8.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd">
    <changeSet author="test" context="context" dbms="mssql" id="Test" objectQuotingStrategy="QUOTE_ALL_OBJECTS">
        <createTable tableName="TestTable">
            <column name="TestRow" type="nvarchar(20)">
                <constraints primaryKey="true"/>
            </column>
        </createTable>
        <insert tableName="TestTable">
            <column name="TestRow" value="Null"/>
        </insert>
    </changeSet>
</databaseChangeLog>
```

generates following SQL:

```
--liquibase formatted sql

--changeset test:Test
CREATE TABLE TestTable (TestRow nvarchar(20) NOT NULL, CONSTRAINT PK_TESTTABLE PRIMARY KEY (TestRow));
INSERT INTO TestTable (TestRow) VALUES (NULL);
```

## Actual Behavior
A INSERT INTO Statement is generated, which does not quotes the Value.
Which can lead to following SQL Error:
" Cannot insert the value NULL into column 'TestRow', table 'demo.dbo.TestTable'; column does not allow nulls. INSERT fails."

## Expected/Desired Behavior
A INSERT INTO Statement, which quotes the Value.

## Additional Context
Unit Test:

```
  void testLiquibaseQuoting() throws IOException {
    DatabaseChangeLog log = new DatabaseChangeLog();
    ChangeSet set = new ChangeSet("Test", "test", Boolean.FALSE, Boolean.FALSE, null,
                                  "context", "mssql", ObjectQuotingStrategy.QUOTE_ALL_OBJECTS, log);
    CreateTableChange inserTable = new CreateTableChange();
    inserTable.setTableName("TestTable");
    ColumnConfig column = new ColumnConfig();
    column.setName("TestRow");
    ConstraintsConfig xpk = new ConstraintsConfig();
    xpk.setPrimaryKey(true);
    column.setConstraints(xpk);
    column.setType("nvarchar(20)");
    inserTable.addColumn(column);
    set.addChange(inserTable);
    InsertDataChange insertData = new InsertDataChange();
    insertData.setTableName("TestTable");
    ColumnConfig datacolumn = new ColumnConfig();
    datacolumn.setName("TestRow");
    datacolumn.setValue("Null");
    insertData.addColumn(datacolumn);
    set.addChange(insertData);
    assertEquals("--liquibase formatted sql\n" + "\n" + "--changeset test:Test\n"
                 + "CREATE TABLE TestTable (TestRow nvarchar(20) NOT NULL, CONSTRAINT PK_TESTTABLE PRIMARY KEY (TestRow));\n"
                 + "INSERT INTO TestTable (TestRow) VALUES ('NULL');\n" + "\n", getLiquiSql("mssql", set));
  }

  private String getLiquiSql(String dbms, ChangeSet set) throws IOException {
    ByteArrayOutputStream stream = new ByteArrayOutputStream();
    ChangeLogSerializer serializer = new FormattedSqlChangeLogSerializer();
    set.setFilePath("export." + dbms + ".sql");
    List<ChangeLogChild> changes = new ArrayList<>();
    changes.add(set);
    serializer.write(changes, stream);
    return stream.toString();
  }
```

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1360) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
Hi @kuhjunge Thanks for writing up this issue and thanks for the excellent description on how the problem occurs.  Can you give a little more context into what you are trying to do?  You are creating a column as the primary key in the table and making the column not null and then inserting a string NULL into the column.  I'm trying to see if there is an alternative to what you are trying to accomplish.

**Comment by kuhjunge** [comment]
I have multiple automatic generated CSV Files, which contain data from tables of a Firebird database. I am parsing these files with a Java Tool and generate InsertDataChange statements from it. Some of the rows of a table contain the string value `Null` (only the first letter is a capital letter). That table has a primary key over multiple columns. The tool also generates a datamodel from another csv file and puts this into a liquibase script which will then executed on a MS SQL Server (and soon an Oracle SQL Server).

**Comment by kuhjunge** [comment]
I solved the problem by removing the value 'Null' from my database.
