### ISSUE TITLE
SQL Generator bug. Arguments for TIME and INTERVAL datatypes.

### ISSUE THREAD

**Issue by AlexanderSashchenko** [liquibase/liquibase#1774]
## Environment
**Liquibase Version**: 4.3.1

**Liquibase Integration & Version**: CLI via test-harness

**Liquibase Extension(s) & Version**:  na

**Database Vendor & Version**: Postgres from 9 to 13

**Operating System Type & Version**: windows 10

## Description
 When trying to pass tests at liquibase harness framework I get these errors:

1) TIME datatype. Changelog file name is datatypes.datetime.xml. Changeset looks like this:

`...        <column name="time" type="time"/>
            <column name="timeewtz" type="time with time zone"/><column name="time0" type="time [ 0 ]"/>
            <column name="timee0wtz" type="time [ 0 ] with time zone"/>
            <column name="time1" type="time [ 1 ]"/>
            <column name="time1wtz" type="time [ 1 ] with time zone"/> ...
`
The sql generated from this changeset doesn't have precision argument at all:
 ... time TIME WITHOUT TIME ZONE, timeewtz TIME WITH TIME ZONE, time0 TIME WITHOUT TIME ZONE, timee0wtz TIME WITH TIME ZONE, time1 TIME WITHOUT TIME ZONE, time1wtz TIME WITH TIME ZONE, ...

2) INTERVAL datatype. Changelog file name is datatypes.datetime.xml. Changeset looks like this:

`...        <column name="interval_year0" type="interval [ YEAR ] [ 0 ]" />
            <column name="interval_month0" type="interval [ MONTH ] [ 0 ]" />
            <column name="interval_day0" type="interval [ DAY ] [ 0 ]" /> ...
`
The sql generated from this changeset has duplicated field and precision arguments:
... interval_year0 INTERVAL [ YEAR ] [ 0 ] [ YEAR ] [ 0 ], interval_month0 INTERVAL [ MONTH ] [ 0 ] [ MONTH ] [ 0 ], interval_day0 INTERVAL [ DAY ] [ 0 ] [ DAY ] [ 0 ], ...

Same duplication bug happes when there's only field or precision argument is set up for INTERVAL.

**Comment by molivasdat** [comment]
HI @AlexanderSashchenko Thanks for writing up this issue.  Not sure if this belongs on the [test-harness repo](https://github.com/liquibase/liquibase-test-harness/issues) or if the bug is in Liquibase.  @kristyldatical is this an issue with Liquibase or the test-harness, I can't tell.

**Comment by AlexanderSashchenko** [comment]
Hi Mike. It seems like the bug is not on the test-harness but in Liquibase. I actually tried different ways to place the arguments for TIME and INTERVAL but the bug reproduces any way. For instance I tried round brackets for placing precision argument for TIME (as it should be according to specifications) but as a result generated sql didn't have those arguments in place. And for INTERVAL datatype we have like vice versa situation when the arguments stated in the changeset become duplicated in the generated sql.

**Comment by molivasdat** [comment]
Thanks team!  I will add this to the list of issues we are processing.

**Comment by KushnirykOleh** [comment]
Chatted with @nvoxland about this issue.  Fix for interval datatype should be more complex, so to merge fix for time datatype quicker @kristyldatical advised to split those into 2 issues. Fix for time gonna be implemented in scope of this one, for interval i created #1886

**Comment by XDelphiGrl** [comment]
The precision of `time` and `time with timezone` Postgres datatypes is correctly handled by [PR 1894](https://github.com/liquibase/liquibase/pull/1894).  The `interval` Postgres datatype bug is _not_ fixed; this portion of the bug is tracked in [Issue 1886](https://github.com/liquibase/liquibase/issues/1886).
