### ISSUE TITLE
createView change type doesn't work for SQLite

### ISSUE THREAD

**Issue by AlexanderSashchenko** [liquibase/liquibase#1786]
## Environment
**Liquibase Version**: 4.3.1

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: na

**Database Vendor & Version**: SQLite 3.34.0

**Operating System Type & Version**: windows 10

## Description
CreateView Liquibase change type doesn't work for SQLite db when deployed via CLI. 

## Steps To Reproduce
List the steps to reproduce the behavior.

* initialize Liquibase connection to SQLite db;
* create a test table and fill it with test data in order to be able to create view on this table;
* create createView changeset according to documentation: https://docs.liquibase.com/change-types/community/create-view.html;
* deploy changes via CLI;

## Actual Behavior
* liquibase response within the CLI states changes are successfully deployed. No errors are thrown;
* databasechangelog table has a record about successfull createView deployment;
* the view that should have been created is absent in the db though;

## Expected/Desired Behavior
* the view is actually created and present in the database;

**Comment by molivasdat** [comment]
Hi @AlexanderSashchenko Thanks for creating this issue.  We will add this to the list of issues that we are processing.

**Comment by AlexanderSashchenko** [comment]
The issue is not actual anymore. Create_view change type works fine.

**Comment by kataggart** [comment]
Thanks @AlexanderSashchenko for updating!
