### ISSUE TITLE
Data loaded from CLOB type columns is not loaded properly into Postgres

### ISSUE THREAD

**Issue by jidma** [liquibase/liquibase#1790]
## Environment
**Liquibase Version**:
Liquibase version 4.4.0
But the problem can be reproduced in previous versions (since 3.10.3).

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
Tested with CLI and Spring Boot

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
PostgreSQL 9.2-1002.jdbc4

**Operating System Type & Version**:
Windows 10

## Description
Data loaded from CLOB type columns is not loaded properly into PostgreSQL.
Instead of loading the content of the CLOB file, the filename is loaded.

## Steps To Reproduce
* create a `dbchangelog.xml` that creates a table with a CLOB column and loads data into it

<details>
  <summary>dbchangelog.xml</summary>

```xml
<databaseChangeLog  
  xmlns="http://www.liquibase.org/xml/ns/dbchangelog"  
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
  xmlns:pro="http://www.liquibase.org/xml/ns/pro"  
  xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.2.xsd
      http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-4.2.xsd">
    
    <!-- TABLE1 with CLOB -->
    <changeSet id="change1" author="test-liquibase">
        <createTable tableName="table1">
            <column name="id" type="bigint">
                <constraints primaryKey="true" nullable="false"/>
            </column>
            <column name="name" type="varchar(255)">
                <constraints nullable="true" />
            </column>
            <column name="details" type="clob">
                <constraints nullable="true" />
            </column>
        </createTable>
    </changeSet>

    <!-- Loading data into TABLE1 with CLOB -->
    <changeSet id="change1-data" author="test-liquibase" context="faker">
        <loadData
                  file="table1.csv"
                  separator=";"
                  tableName="table1">
            <column name="id" type="numeric"/>
            <column name="name" type="string"/>
            <column name="details" type="clob"/>
        </loadData>
    </changeSet>

</databaseChangeLog>
```

</details>

<details>
  <summary>table1.csv</summary>

```csv
id;name;details
1;name value;fake-data.txt
```

</details>

<details>
  <summary>fake-data.txt</summary>

```
this is some fake data in the file 'fake-data'.txt
```

</details>

* update the Postgres Database with the previous changeset:

```
liquibase update
```

## Actual Behavior
The table is created and the data is loaded incorrectly:
The column details contains the filename 'fake-data.txt'

![image](https://user-images.githubusercontent.com/2295247/113881009-8ca8b300-97ab-11eb-9437-a6a6692546de.png)

## Expected/Desired Behavior
The table is created and the data is loaded correctly:
The column details should contain the content of the file 'fake-data.txt' instead of the filename.

![image](https://user-images.githubusercontent.com/2295247/113881430-f1fca400-97ab-11eb-9d5e-6d7366629d6e.png)

## Additional Context
This bug is related to the following jhipster [issue/14463](https://github.com/jhipster/generator-jhipster/issues/14463)

**Comment by molivasdat** [comment]
Hi @jidma Thanks for writing up this issue.  We will add it to the list of issues to process.
