### ISSUE TITLE
"dbms" attribute doesn't validate input

### ISSUE THREAD

**Issue by AlexanderSashchenko** [liquibase/liquibase#1795]
## Environment
**Liquibase Version**: 4.3.1

**Liquibase Integration & Version**: CLI & test-harness

**Liquibase Extension(s) & Version**: na

**Database Vendor & Version**: any

**Operating System Type & Version**: windows 10

## Description
When I try to deploy createProcedure change type using "dbms" attribute to set the exact db vendor and do a typo at the attribue value (e.g. 'postgres' instead of 'postgresql') the database changelog table receives a new appropriate record and no errors are thrown but actual deployment fails and no changes are made to the db structure. Checked that both with liquibase cli and test-harness, the result is the same.
Please note this one may not be related only to createProcedure change type but any where "dbms" attribute is used.

## Steps To Reproduce
* create createProcedure changelog using "dbms" attribute filled with mistaken value;
* deploy the changes;

## Actual Behavior
* no errors are thrown during deployment;
* databasechangelog table has a record about deployment, the 'exectype' value is 'EXECUTED';
* the stored procedure we wanted to add is not present at the db structure;

## Expected/Desired Behavior
* validation error about 'not supported db vendor or possible typo at the "dbms" attribute' is thrown;

**Comment by devurandom** [comment]
This also affects the `preConditions.dbms` (in YAML), which should have a `type` attribute, but Liquibase happily takes a string instead and then evaluates the precondition as `null`.

See e.g. this bug that could have been detected by Liquibase: https://github.com/metabase/metabase/pull/16095/files#diff-241462177925c37373615bb7d440f151756dc4e629f4fbd5a6ac26bf6a688d4f

**Comment by FBurguer** [comment]
Still an issue for liquibase `4.15`.
