### ISSUE TITLE
Type change with renameColumn inconsistent

### ISSUE THREAD

**Issue by bjoernmartin** [liquibase/liquibase#1807]
## Environment
**Liquibase Version**: 3.8.9

**Liquibase Integration & Version**: spring boot 2.3.7

**Liquibase Extension(s) & Version**: -

**Database Vendor & Version**: MariaDB 10.3.25 + H2 1.4.200

**Operating System Type & Version**: Ubuntu 20.04 LTS

## Description
Let's assume we have a table `TABLE` with the column `OLD` of type `VARCHAR(32)`. This column is to be renamed to `NEW` and its type changed to `CLOB`. We'd create a change set with the following rename request:

```
<renameColumn tableName="TABLE" oldColumnName="OLD" newColumnName="NEW" columnDataType="CLOB" />
```

This will work fine with MariaDB, which does the rename and type change in a single statement. It is actually **required** to specify `columnDataType="CLOB"` for MariaDB, otherwise Liquibase will refuse the change.

On H2, however, the `columnDataType="CLOB"` entry is completely ignored. We end up with a column named `NEW` that still has the type `VARCHAR(32)` set for itself. The workaround is to specify an explicit `modifyDataType` that will be a no-op for MariaDB but makes H2 work:

```
<modifyDataType tableName="TABLE" columnName="NEW" newDataType="CLOB" />
```

## Steps To Reproduce
See above. A full change would look like this:

```
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd">
    <changeSet id="enlarge-to-order-ids-on-invoice" author="martin@synyx.de">
        <renameColumn tableName="TABLE" oldColumnName="OLD" newColumnName="NEW" columnDataType="CLOB" />
        <modifyDataType tableName="TABLE" columnName="NEW" newDataType="CLOB" />
    </changeSet>
</databaseChangeLog>
```

## Actual Behavior
MariaDB and H2 interpret the `renameColumn` syntax in different ways with regard to the `columnDataType` (whether it is respected if specified).

## Expected/Desired Behavior
MariaDB and H2 interpret the `renameColumn` syntax identical with regard to the `columnDataType` (both respect it if specified).

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1489) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
Hi @bjoernmartin Thanks for writing up this issue.  It looks like H2 has a set data type as part of the alter table statement
https://h2database.com/html/commands.html#alter_table_alter_column
Looks like we need to implement that and test if that statement is valid in h2.  We will add this to the list of issues we process.

**Comment by molivasdat** [comment]
Hi @bjoernmartin After additional research, there is not a single H2 alter command that does both a rename and a change of data type like there is in MySQL and MariaDB.
In H2, there is only
ALTER TABLE PUBLIC.TABLE1 ALTER COLUMN OLD RENAME TO NEW;
ALTER TABLE PUBLIC.TABLE1 ALTER COLUMN NEW SET DATA TYPE CLOB;

in MySQL and MariaDB there is a single alter statement that does both
ALTER TABLE TABLE1 CHANGE OLD NEW CLOB;

**Comment by bjoernmartin** [comment]
Hi @molivasdat 

Sorry for the late answer, totally forgot to reply :-/

As I see it, H2 does not support renaming a column and changing its type in one statement, while MySQL and MariaDB do not support renaming a column without specification of its (current or new) type / the type to set. Since you also don't offer the solution to apply the `<renameColumn ..>` entry via two SQL statements instead of just one for H2, I assume it's architecturally not possible for Liquibase to do so. AFAIR this could be a problem because DDL statements cannot be rolled back in some DBMS, meaning if the first statement works but the second fails, Liquibase would be left with a half-executed `<renameColumn ..>` entry it can neither finish nor roll back.

In that case I think this issue can be closed, as it can not be fixed. Which is not too tragic, as there is the workaround of specifying a `<renameColumn ..>` entry, followed by a `<modifyDataType ..>`, leading to the same result on both (or maybe even all supported?) DBMS.

**Comment by molivasdat** [comment]
Closing issue.  Using workaround to support databases that don't support rename and change column type in one sql statement.
