### ISSUE TITLE
Warning about Hub while hubMode is "off" during execution of dropAll command.

### ISSUE THREAD

**Issue by mgiorgino** [liquibase/liquibase#1820]
## Environment
**Liquibase Version**: 4.3.2

**Liquibase Integration & Version**: Maven

**Liquibase Extension(s) & Version**: None

**Database Vendor & Version**: hsqldb 2.5.1 / mariadb 10.3.20-MariaDB-0ubuntu0.19.04.1 / Oracle Release 11.2.0.2.0

**Operating System Type & Version**: Ubuntu 19.04

## Description
Running command `dropAll` warns about the changelog not being registered with any Liquibase Hub project, even though `hubMode` is `off`:

> WARNING: The changelog file specified is not registered with any Liquibase Hub project,
> so the results will not be recorded in Liquibase Hub.
> To register the changelog with your Hub Project run 'liquibase registerchangelog'.
> Learn more at https://hub.liquibase.com.

## Steps To Reproduce
* Download and unzip provided maven project archive: [drop-all-warning-hub.zip](https://github.com/liquibase/liquibase/files/6414889/drop-all-warning-hub.zip)
* Run `mvn verify`.

## Actual Behavior
The warning appears during the `dropAll` execution (but not in the `update` one, for example).

## Expected/Desired Behavior
The warning should not appear during any command execution as long as `hubMode` is `off`.

## Additional Context
This warning does not appear with my installed version of liquibase 4.1.1 (when run directly with CLI and `liquibase.properties` file).

**Comment by molivasdat** [comment]
Thanks @mgiorgino for creating this issue.  And thank you for sharing a reproducible test case that shows the problem.  It makes it much easier for us to reproduce and know when we have it fixed.  As @mariochampion stated we are adding it to the list of issues we are processing.

**Comment by FBurguer** [comment]
Still an issue on liquibase `4.15`. Its DB independant.

**Comment by lbadam** [comment]
I have tested this with 4.29.2 and can confirm that this is not an issue anymore.
