### ISSUE TITLE
PostgreSQL: cannot use an extension from the public schema without prefix (search_path is overriden by liquibase)

### ISSUE THREAD

**Issue by mleguevel** [liquibase/liquibase#1821]
## Environment
**Liquibase Version**: 4.3.4

**Liquibase Integration & Version**: CLI

**Database Vendor & Version**: PostgreSQL 12

**Operating System Type & Version**: Ubuntu 20.04

## Description
Hello,

I'm facing the same problem that's described in [this forum thread](https://forum.liquibase.org/t/access-postgis-from-different-schema/4708/3) (I did not reply in the forum because the number of links in a comment is restricted for new users). I'm using postgis as well but I guess it's the same for any extension that you would install on the public schema. The problem is that liquibase sets the search_path to only the default schema.

In the code, this is done in [DatabaseUtils#initializeDatabase](https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/database/core/DatabaseUtils.java#L36), which is called from [PostgresDatabase#rollback](https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java#L421) and the rollback function seems to be called for each changeset, after the preconditions are checked, in [ChangeSet#execute](https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java#L614).

I think that the problem was introduced with this commit: https://github.com/liquibase/liquibase/commit/feb2412. Before that, the search_path was not forced for each changeset, and there was no problem using an extension from the public schema without using prefixes.

I guess that there was a good reason to force the search_path, but I think that there should be an option to override the default behavior and to allow the user to set a custom search_path.

## Steps To Reproduce
With postgis:

* Add the postgis extension to the public schema: `CREATE EXTENSION postgis;`
* Run liquibase on another schema (`my_schema`) with the following changeset:

```
create table my_schema.test_table (
     a_box        Box2D
)
```

Liquibase will fail with the following error:

```
ERROR: type "box2d" does not exist
```

Thanks.

**Comment by hylkevds** [comment]
We have the same issue, though our database is initialised properly, the application breaks because liquibase overrides the search_path that we set in our connection string.

I'm not sure it was caused by the above mentioned commit, since the offending line was not changed by that commit, only moved to a different class. 
The problem already exists in 3.10, since we're stuck on that version due to another Liquibase bug.

The best fix is probably to check if the search_path already contains the schema that liquibase wants to add, do nothing if it is already there and if Liquibase does change the search_path, _revert that change afterwards_.

**Comment by ro-rah** [comment]
Currently Liquibase is working as designed regarding this feature request.  One workaround you may try (a good suggestions from @wwillard7800 ):

> One way to handle that sort of thing would be to set the schema name in the change attribute.  They could even flex on that by making it be a changeLog property value.

Please let us know if that works for solving you issue.

**Comment by elecaude** [comment]
This is a workaround, but as
an app can be deployed on several different environments, with different schema names in databases, i don't think that fixes the problem. The search_path should not be managed by liquibase but by the database itself.

**Comment by molivasdat** [comment]
Thanks @mleguevel for documenting this issue.  We will add it to the list of issues that we are processing.  We definitely going to look at the search_path and see what we can do. I like the idea of @hylkevds change but that possible change is not a simple fix.

**Comment by Bludwarf** [comment]
We have the same problem. It seems that it has not been fixed yet. Here is our workaround :

1. Store SEARCH_PATH externaly in a liquibase parameter named `search-path`, for instance
2. Add a migration that will `runAlways` before all others
3. Manualy set SEARCH_PATH in this migration

YAML migration :

```xml
databaseChangeLog:
  - changeSet:
      id: set-search-path
      author: bludwarf
      runAlways: true
      changes:
        - sql:
            sql: SET SEARCH_PATH TO ${search-path};
```
