### ISSUE TITLE
PostgreSQL 12.4: diffChangeLog generates error for functions having paranthesis in function definition parameters

### ISSUE THREAD

**Issue by RajarsiGit** [liquibase/liquibase#1822]
## Environment
**Liquibase Version**: 4.3.5

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: PostgreSQL 12.4

**Operating System Type & Version**: Windows Server 2016

## Description
Hi Liquibase Team,
I and my fellow developers have been using Liquibase for quite a while now and recently we have been facing an issue while generating diffchangelogs.
When we try to generate diffChangeLog for two databases, we see that it generates all but generates error for those functions that have a default value in their function definition. Particularly, this has been with functions having a function defition where the default value has to be type casted to a particular type. The output function defition generated by postgresql shows paranthesis around the default value to be type casted to a particular type. Therefore, Liquibase while generating DiffChangeLogs generates error because it is unable to correctly parse those inner paranthesis inside the function parameters. The following steps will help you reproduce the issue.

## Steps To Reproduce
List the steps to reproduce the behavior.

* Create function having def as:

```
CREATE OR REPLACE FUNCTION dbo.fn_test(p_id bigint, p_test bit DEFAULT (0)::bit(1))
 RETURNS VOID
 LANGUAGE plpgsql
AS $function$
BEGIN
END ;
$function$
;
```

* Run liquibase **diffChangeLog** against the database which contains this and one which doesn't

## Actual Behavior
Liquibase produces the following error:
    objects-162010817xxxx\function\fn_test(p_id bigint, p_test bit DEFAULT (0)::bit-xxxxxxxx.sql (The filename, directory name, or volume label syntax is incorrect)

## Expected/Desired Behavior
Liquibase should not generate error. It should generate diffChangeLog for the function smoothly
Please look into this.

Thanks

**Comment by molivasdat** [comment]
Hi @RajarsiGit Thanks for creating this issue and the documented recreation steps and thank you for using Liquibase for a while.
When you state 
"I and my fellow developers have been using Liquibase for quite a while now and recently we have been facing an issue while generating diffchangelogs."
Does this mean that it was once working and is no longer working or are functions with parenthesis in the definition something new to the project?
I'm trying to get a sense whether the code was working at one point and we broke it or it has been there for a while and we are just now seeing it.

**Comment by RajarsiGit** [comment]
> Hi @RajarsiGit Thanks for creating this issue and the documented recreation steps and thank you for using Liquibase for a while.
> When you state
> "I and my fellow developers have been using Liquibase for quite a while now and recently we have been facing an issue while generating diffchangelogs."
> Does this mean that it was once working and is no longer working or are functions with parenthesis in the definition something new to the project?
> I'm trying to get a sense whether the code was working at one point and we broke it or it has been there for a while and we are just now seeing it.

Hi @molivasdat thanks for the reply, yes we are using Liquibase for quite some time now, but it's only now that we fell onto this specific case where we had to generate diffchangelogs. So, it will be pretty hard for me to tell if this was there for a while or it has started after an update from you guys. Before this we didn't need to use the command or let's say we didn't need to use this command on a database containing such above mentioned functions.
Hope, I could be as helpful as possible.
Thanks

**Comment by RajarsiGit** [comment]
Hi, @molivasdat any update on this? Do you see a fix for this within the next couple of days or will it be kept for later review? We got this error twice within the past week. This is becoming a bit of a concern for us.
Thanks.

**Comment by molivasdat** [comment]
This is not a plan to put this into the latest version.  If you have a PR to fix it, we have an automated build now that will create a temp version that you could use in the meantime.

**Comment by FBurguer** [comment]
Tried Using the function on the description, folowing the steps provided on liquibase `4.14` and didnt have the same issue. If you still have the same issue please re-open the issue. Thanks!
