### ISSUE TITLE
MS SQL Server statement with '\' gives error with in Liquibase

### ISSUE THREAD

**Issue by gralexander719** [liquibase/liquibase#1828]
## Environment
**Liquibase Version**: liquibase-4.3.4

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: liquibase-4.3.4

**Database Vendor & Version**: Microsoft SQL Server 2016 (SP2-CU8) (KB4505830) - 13.0.5426.0 (X64)

**Operating System Type & Version**: Windows 10 Enterprise

## Description
Sql script that contains a backslash is failing with error:
Reason: liquibase.exception.DatabaseException: Incorrect syntax near 'GO'. [Failed SQL: (102) 

## Here is the sql
DECLARE FIELD1 VARCHAR(500) = NULL 
DECLARE FILEID VARCHAR(255)= NULL 
SELECT FILEID = 'XYZ\2021\202102\20210208020254274\SYSTEM.20210208.020254.399.301a2882-b100-40c7-9fa2-8e99b0e40995.pdf'

SELECT FIELD1 = 
CASE 
	WHEN	CHARINDEX('/', @FILEID) > 0 THEN	RIGHT(@FILEID, CHARINDEX('/', REVERSE(@FILEID))-1)	
	WHEN	CHARINDEX('\\', @FILEID) > 0 THEN	RIGHT(@FILEID, CHARINDEX('\\', REVERSE(@FILEID))-1)
ELSE FILEID	
END
SELECT FIELD1

The error occurs because of the first '\\' at CHARINDEX('\\', @FILEID). Seems to take everything after the '\\' as a string.

NOTE: it works ok in Sql Server Management studio. Thus not an SQL bug. WE have several scripts with such syntax and there are no errors. Errors only occur when we use Liquibase to run the scripts.

## Steps To Reproduce
List the steps to reproduce the behavior.
Put the above sql into a file, for example - as part of a stored procedure.
Run liquibase update - java -jar C:\Liquibase\liquibase-4.3.4\liquibase.jar --logLevel=debug update

## Actual Behavior
Error is generated

## Expected/Desired Behavior
Sql should run without error - as it does in Sql Server Management studio

## Screenshots (if appropriate)
[Luibase backslash issue.docx](https://github.com/liquibase/liquibase/files/6438032/Luibase.backslash.issue.docx)

**Comment by molivasdat** [comment]
Thanks @gralexander719 for writing up this issue.  We will add it to the list of issues that we are processing.
It is odd that even the github description sees the \ as a special character.  Thanks for the screenshot of the error.  It definitely helps show that this code is part of a stored procedure and gives more context to where the error is occurring.

**Comment by gralexander719** [comment]
Hi @molivasdat any idea when this issue will be resolved?

**Comment by smith-xyz** [comment]
Could the changeset xml be posted here as well? 

e.g.
<changeSet id="1" author="ssmith">
        <sqlFile path="db.testchangelog.mssql.sql"
                 encoding="UTF-8"
                 endDelimiter="\nGO"
                 relativeToChangelogFile="true"
                 splitStatements="true"
                 stripComments="true"/>
    </changeSet>

**Comment by gralexander719** [comment]
Here is the changeset xml

<?xml version="1.0" encoding="UTF-8"?>  
<databaseChangeLog  
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"  
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
    http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd"> 
	<changeSet  id="SQL-Package_DDL_scripts"  author="Liquibase Automation" failOnError="true" runInTransaction="true">  
        <sqlFile path="DDL-DB-PACKAGE-With-Backslash.sql"
			encoding="UTF-8"
			endDelimiter="\nGO"
			relativeToChangelogFile="true"
			splitStatements="true" 
			stripComments="true"
			dbms="mssql"/>  
   </changeSet>
</databaseChangeLog>

**Comment by gralexander719** [comment]
<?xml version="1.0" encoding="UTF-8"?>  
<databaseChangeLog  
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"  
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
    http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd"> 
	<changeSet  id="SQL-Package_DDL_scripts"  author="Liquibase Automation" failOnError="true" runInTransaction="true">  
        <sqlFile path="DDL-DB-PACKAGE-With-Backslash.sql"
			encoding="UTF-8"
			endDelimiter="\nGO"
			relativeToChangelogFile="true"
			splitStatements="true" 
			stripComments="true"
			dbms="mssql"/>  
   </changeSet>
</databaseChangeLog>

**Comment by gralexander719** [comment]
<?xml version="1.0" encoding="UTF-8"?>  
<databaseChangeLog  
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"  
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
    http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd"> 
	<changeSet  id="SQL-Package_DDL_scripts"  author="Liquibase Automation" failOnError="true" runInTransaction="true">  
        <sqlFile path="DDL-DB-PACKAGE-With-Backslash.sql"
			encoding="UTF-8"
			endDelimiter="\nGO"
			relativeToChangelogFile="true"
			splitStatements="true" 
			stripComments="true"
			dbms="mssql"/>  
   </changeSet>
</databaseChangeLog>

**Comment by gralexander719** [comment]
<?xml version="1.0" encoding="UTF-8"?>  
<databaseChangeLog  
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"  
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
    http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd"> 
	<changeSet  id="SQL-Package_DDL_scripts"  author="Liquibase Automation" failOnError="true" runInTransaction="true">  
        <sqlFile path="DDL-DB-PACKAGE-With-Backslash.sql"
			encoding="UTF-8"
			endDelimiter="\nGO"
			relativeToChangelogFile="true"
			splitStatements="true" 
			stripComments="true"
			dbms="mssql"/>  
   </changeSet>
</databaseChangeLog>

**Comment by gralexander719** [comment]
<?xml version="1.0" encoding="UTF-8"?>  
<databaseChangeLog  
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"  
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
    http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd"> 
	<changeSet  id="SQL-Package_DDL_scripts"  author="Liquibase Automation" failOnError="true" runInTransaction="true">  
        <sqlFile path="DDL-DB-PACKAGE-With-Backslash.sql"
			encoding="UTF-8"
			endDelimiter="\nGO"
			relativeToChangelogFile="true"
			splitStatements="true" 
			stripComments="true"
			dbms="mssql"/>  
   </changeSet>
</databaseChangeLog>

**Comment by gralexander719** [comment]
Testing

**Comment by gralexander719** [comment]
<changeSet  id="SQL-Package_DDL_scripts"  author="Liquibase Automation" failOnError="true" runInTransaction="true">  
        <sqlFile path="DDL-DB-PACKAGE-With-Backslash.sql"
			encoding="UTF-8"
			endDelimiter="\nGO"
			relativeToChangelogFile="true"
			splitStatements="true" 
			stripComments="true"
			dbms="mssql"/>

**Comment by molivasdat** [comment]
@gralexander719 I updated the comment to show the file.

**Comment by gralexander719** [comment]
> @gralexander719 I updated the comment to show the file.

Thanks. What did you change to make it show?

**Comment by molivasdat** [comment]
Hi @gralexander719 I added 3 back ticks at the beginning and the end of the comment.  You can go back and click on edit for your comment and see them.   3 of these characters `

**Comment by smith-xyz** [comment]
Thanks @gralexander719 and @molivasdat! I tested in sql server 2017 and 2019 without issue, but see you're using 2016 so I'm seeing about setting up a 2016 sql server instance. @gralexander719 could you also run the updateSql command to see the sql that is printed out, which should be the sql executed. Curious to see if anything looks odd in what is generated.

**Comment by gralexander719** [comment]
```
@smith-xyz in addition to SQL Serve 2016 we also have an instance running SQL Server 2014 (SP3-CU4)
Here are the results from the updateSQL command
[updateSQL_Results.txt](https://github.com/liquibase/liquibase/files/6599396/updateSQL_Results.txt)

Here are the results from the update command with logLevel=Debug
[update_Debug_Results.txt](https://github.com/liquibase/liquibase/files/6599402/update_Debug_Results.txt)

Note I have masked company specific info
```

**Comment by nvoxland** [comment]
I some time looking at it. Like @smith-xyz I could not replicate it, but also don't have 2016 yet. Perhaps it is that, or perhaps it is an escape char setting you have?

I could not find any special handling of backslashes in what we send to sqlserver, especially limited to 2016. And it appears to be splitting correctly and sending the correct SQL based on your error messages. By "correctly" I mean "sending it as `'\\'` rather than something different.

Looking around the internet, all I can see is "don't have to escape backslashes in sqlserver" which is for sure seems true for 2017+ based on my/@smith-xyz's testing. 

I'm wondering if sqlserver 2016 has a bug/feature/option of treating `\\'` as an escaped quote like mysql and the database is by default doing that but management studio is either silently disabling that or doing some sort of client-side translation?? I can't find any docs on a setting for that, though.

Out of curiosity: If you change the sql to `'\\'` does it work?

Can anyone find any docs on when/why sqlserver would be treating `\\'` as an escaped quote?

**Comment by nvoxland** [comment]
This appears to be an issue with SQLServer 2016 and not liquibase. So closing
