### ISSUE TITLE
mvn liqui:diff with jpa does not follow hibernate naming strategy

### ISSUE THREAD

**Issue by MohammadToficMohammad** [liquibase/liquibase#1832]
## Environment
**Liquibase Version**:latest liquibase-maven-plugin

**Database Vendor & Version**: h2 

**Operating System Type & Version**: winddws

 liqui:diff with jpa does not follow naming strategy of jpa hibernate with the changeset for example if hibernate call
table CAR on changeset it will be Car ,for props of entities also CAR_ID vs carId 
that will make diff see more differences that exits in reality

this is liqui props:
changeLogFile=src/main/resources/db/changelog/dbchangelog.xml
url=jdbc:h2:file:C:/Users/Mohammad/Desktop/spring-boot-h2-db-2
username=sa
password=password
driver=org.h2.Driver
outputChangeLogFile=src/main/resources/db/liquiplugin/liquibase-outputChangeLog.xml
referenceUrl=hibernate:spring:com.test.liquibase?dialect=liquibase.ext.hibernate.database.HibernateGenericDialect
referenceDriver=liquibase.ext.hibernate.database.connection.HibernateDriver
diffChangeLogFile=src/main/resources/db/liquiplugin/liquibase-diff-changeLog.xml

this is  app props:
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:C:/Users/Mohammad/Desktop/spring-boot-h2-db-2;DB_CLOSE_ON_EXIT=FALSE
server.port=8081
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.liquibase.change-log=classpath:db/changelog/dbchangelog.xml
spring.liquibase.enabled=true

this is pom

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.5</version>
		<relativePath/> 
	</parent>

```
<groupId>com.test</groupId>
<artifactId>liquibase</artifactId>
<version>0.0.1-SNAPSHOT</version>
<name>liquibase</name>
<description>Demo project for Spring Boot</description>
<properties>
	<java.version>11</java.version>
</properties>
<dependencies>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-data-jpa</artifactId>
	</dependency>
```

```
	<dependency>
		<groupId>org.liquibase</groupId>
		<artifactId>liquibase-core</artifactId>
		<version>3.8.7</version>
	</dependency>
```

```
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-web</artifactId>
	</dependency>
```

```
	<dependency>
		<groupId>com.h2database</groupId>
		<artifactId>h2</artifactId>
		<scope>runtime</scope>
	</dependency>
```

```
	<dependency>
		<groupId>org.projectlombok</groupId>
		<artifactId>lombok</artifactId>
		<optional>true</optional>
	</dependency>
```

```
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-test</artifactId>
		<scope>test</scope>
	</dependency>
```

```
</dependencies>
```

```
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
		</plugin>
```

```
		<plugin>
			<groupId>org.liquibase</groupId>
			<artifactId>liquibase-maven-plugin</artifactId>
			<version>3.5.3</version>
			<configuration>
				<propertyFile>src/main/resources/db/liquiplugin/liquibase.properties</propertyFile>
			</configuration>
```

```
			<dependencies>
				<dependency>
					<groupId>org.liquibase.ext</groupId>
					<artifactId>liquibase-hibernate5</artifactId>
					<version>3.6</version>
				</dependency>
				<dependency>
					<groupId>org.springframework</groupId>
					<artifactId>spring-beans</artifactId>
					<version>4.1.7.RELEASE</version>
				</dependency>
				<dependency>
					<groupId>org.springframework.data</groupId>
					<artifactId>spring-data-jpa</artifactId>
					<version>2.5.0</version>
				</dependency>
```

```
				<dependency>
					<groupId>org.springframework</groupId>
					<artifactId>spring-jdbc</artifactId>
					<version>2.0.6</version>
				</dependency>
```

```
				<dependency>
					<groupId>javax.xml.bind</groupId>
					<artifactId>jaxb-api</artifactId>
					<version>2.2.11</version>
				</dependency>
				<dependency>
					<groupId>org.yaml</groupId>
					<artifactId>snakeyaml</artifactId>
					<version>1.19</version>
				</dependency>
			</dependencies>
		</plugin>
	</plugins>
</build>
```

</project>

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1600) by [Unito](https://www.unito.io)

**Comment by MohammadToficMohammad** [comment]
i tried 
&hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy 
but i got error class not found ,and when i add starter jpa  i got another exception

**Comment by molivasdat** [comment]
Hi @MohammadToficMohammad Thanks for creating the issue and the detailed information on the recreation steps.  I think this may belong in the hibernate [repository](https://github.com/liquibase/liquibase-hibernate/issues).

**Comment by MohammadToficMohammad** [comment]
i hope there would be an easy method to define the naming strategy because the old method is not working:
hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNaming
