### ISSUE TITLE
createView replaceIfExists doens't work if using replace function in view definition

### ISSUE THREAD

**Issue by cravennathan** [liquibase/liquibase#1849]
## Environment
**Liquibase Version**: 4.3

**Database Vendor & Version**: Oracle

## Description
`createView` tag `replaceIfExists` attribute will not generate `CREATE OR REPLACE` if the string 'replace' is anywhere in the view definition.

## Steps To Reproduce
create a changeSet (I used xml) to create a view that uses replace

```
<createView replaceIfExists="true" viewName="test_vw">
    SELECT REPLACE('The quick brown dog', 'dog', 'fox') FROM DUAL
</createView>
```

run `liquibase updateSql` and view the output

## Actual Behavior
A clear and concise description of what happens in the software **before** this pull request.
`CREATE VIEW test_vw AS SELECT REPLACE('The quick brown dog', 'dog', 'fox') FROM DUAL;`

## Expected/Desired Behavior
A clear and concise description of what happens in the software **after** this pull request.
`CREATE OR REPLACE VIEW test_vw AS SELECT REPLACE('The quick brown dog', 'dog', 'fox') FROM DUAL;`

## Additional Context
It looks like the issue stems from line 105 in the [CreateViewGenerator.java](https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateViewGenerator.java). I believe that potentially we could improve the if condition in one of the following ways (or a better solution):

* see if the replace isn't followed by `(` 
* that replace is followed by `view`
* `!viewDefinitoin.contains("create or replace")`

```
if (!viewDefinition.contains("replace")) {
     viewDefinition.replace("CREATE", "CREATE OR REPLACE");
}
```

**Comment by cravennathan** [comment]
For a work around I just did
```
<createView viewName="test_vw" fullDefinition>
    CREATE OR REPLACE VIEW test_vw AS SELECT REPLACE('The quick brown dog', 'dog', 'fox') FROM DUAL
</createView>
```

**Comment by FBurguer** [comment]
Still an issue for liquibase `4.15`.
