### ISSUE TITLE
Optimize updates

### ISSUE THREAD

**Issue by paplorinc** [liquibase/liquibase#1856]
Based on some profiling data we did for a client, it seemed that Liquibase was recompiling a lot of often used regexes, e.g.:
![image](https://user-images.githubusercontent.com/1841944/119014286-1bf2da00-b998-11eb-8100-bd3c79dcb906.png)

The latest code also seems to contain lots of them, e.g. https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java#L645-L650, resulting in a horrible performance.

Extracting every regex on the critical path shouldn't be difficult. Creating fewer Strings may be more difficult, but would be worth it.
I'd gladly help, but I don't have the reproducer code available, our client does.

**Comment by molivasdat** [comment]
Hi @paplorinc Thanks for the chart and pointer to There will always be ways we can increase performance.  Can you provide a little more context?  What version were you using?
The code that you pointed to in your link deals with files in the classpath.  How many files are in the application that is running Liquibase?  How big is the classpath?

The image you show has RanChangeSet.isSameAs - 
How many changesets are in the changelog?
What type of changesets are being used?
Are changesets inlined as part of the changelog or are they pointers to the files?

There are a bunch of different factors that can affect performance and there are also things outside the code that can be done to help as well.

**Comment by harshSE** [comment]
Hi @molivasdat,

Liquibase version is 4.3.5

 We have more than 40K class files from the project. The application classpath is quite big

We have more than 3k changesets in the changelog
We are using SQL format for changesets and all changesets are inlined.

**Comment by harshSE** [comment]
@molivasdat , please let me know if any other information required.

**Comment by molivasdat** [comment]
Hi @harshSE If you have a recreate-able test case, I can bump the priority of this and move it along faster.  A GH repo that shows the error is way easier to consume and move through the process.
