### ISSUE TITLE
HubUpdater releases lock even though registration is skipped

### ISSUE THREAD

**Issue by filiphr** [liquibase/liquibase#1865]
This is slightly linked #1741. 

In 
https://github.com/liquibase/liquibase/blob/10a0c509c59401e9351cf7d134b4bc671b5d500f/liquibase-core/src/main/java/liquibase/hub/HubUpdater.java#L364-L383

The currently held lock is released and then reacquired again. However, when using Liquibase programatically as a library the prompt is always disabled and therefore releasing and then acquiring the lock is entirely not needed.

Can I propose a change that will do

```
if (!Scope.getCurrentScope().getUI().getAllowPrompt()) {
    return;
}
```

This will solve the problem with the polluting of the logging with "Skipping auto-registration" since registering is anyways not possible when using it as a library.

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-1748) by [Unito](https://www.unito.io)

**Comment by nvoxland** [comment]
Yes, that seems like a good change. I can open a PR for that

**Comment by filiphr** [comment]
Thanks @nvoxland this is much appreciated.

**Comment by kataggart** [comment]
closing; associated PR merged several versions ago
