### ISSUE TITLE
Postgres diff doesn't include partitions?

### ISSUE THREAD

**Issue by cyraid** [liquibase/liquibase#1874]
**Liquibase Version**:
4.3.5

**Liquibase Integration & Version**: Maven, Spring Boot

**Liquibase Extension(s) & Version**:  4.3.5

**Database Vendor & Version**: Postgres 13.2

**Operating System Type & Version**: Windows 10

## Description
Using: mvn liquibase:diff generates a diff, and works fine for most tables, but does not include partitioned tables.

## Steps To Reproduce
* Create a partitioned table on one server
* Create a diff
* Notice the diff doesn't have partition information?

## Actual Behavior
Does not include partitioned tables.

## Expected/Desired Behavior
Include partitioned tables.

**Comment by molivasdat** [comment]
Hi @cyraid Thanks for creating this issue. 
I tried to reproduce this and failed.
Here is what I did to try and reproduce this.
Create postgres database
docker run --name posgtres132 -e POSTGRES_PASSWORD=mysupersecret -p 5432:5432 -d postgres:13.2
Create 2 databases with pgadmin
model1 database
model2 database

Use this changelog file and run liquibase update against model2
**liquibase update**
```
--liquibase formatted sql

-- changeset mikeo:partitioned-table
create table ptable (
    id bigserial,
    thisdate timestamp with time zone NOT NULL
)  PARTITION BY RANGE (thisdate);
--rollback drop table ptable
```
Run liquibase diff against model1
**liquibase diff**

Here is the liquibase.properties file I used
```
changeLogFile=gh1874.postgres.sql
url: jdbc:postgresql://localhost:5432/model2
username: postgres
password: mysupersecret
classpath: ./postgresql-42.2.11.jar
referenceUrl: jdbc:postgresql://localhost:5432/model1
referenceUsername: postgres
referencePassword: mysupersecret
```
I also tried the same configuration
with this pom.xml file as a simple example and ran 
**mvn liquibase:update**
to add the partitioned table
OR if you previously ran with the CLI run 
**mvn liquibase:diff**


Output from the diff (shortened for brevity)
```
Unexpected Table(s): 
     databasechangelog
     databasechangeloglock
     ptable
```

**Comment by cyraid** [comment]
This is the showstopper for us, so if it doesn't include the partitions our company can't move forward with liquibase. Sorry.

**Comment by molivasdat** [comment]
Hi @cyraid Thanks for the feedback.  Can you provide a re-createable scenario that shows the error?  I put in the comments how I tried to recreate this issue and could not recreate.  We also found that an older driver of postgresql was not returning information about partitioned tables.  What postgres jdbc driver version are you using?

**Comment by cyraid** [comment]
It's possible, but I'll maybe see if we can try it again in the future. But for the short term it doesn't look likely. You can close if you like. I'll try to remember that we need a new postgres jdbc version in the future if we go down this path :) Take care guys.
