### ISSUE TITLE
Maven updateTestingRollback delete tags

### ISSUE THREAD

**Issue by sakisoft** [liquibase/liquibase#1876]
I am working in a CI/CD pipeline to oracle db with jenkins and maven-liquibase. 
I have configured maven-liquibase-plugin 4.3.5 in our pom.xml
Im using a changelog_master.xml with an include_all clausule in order to excecute all the changelogs in an existing folder called scripts/ (this changelogs are in .sql format)

We are testing the maven updateTestingRollback and then the maven tag comand
When add another changelog.sql and execute again updateTestingRollback and then the maven tag comand the last tag appears, but the previous ones disappear from databasechangelog table.

This not happens in desktop version where updateTestingRollback dont delete the previous tags of changelogs executed, so we dont know if its a bug of maven-liquibase or we are doing something in a wrong way.

Please, could you help with this issue?

**Comment by molivasdat** [comment]
Hi @sakisoft This type of question is probably best handled through the forum.
https://forum.liquibase.org
