### ISSUE TITLE
Add uniqueConstraintExists precondition

### ISSUE THREAD

**Issue by nvoxland** [liquibase/liquibase#1881]
## Overview
There are indexExists and foreignKeyExists preconditions, but no uniqueConstraintExists. 

Some databases use the same name for backing indexes for unique constraints so indexExists happens to work, but we need something more robust.

**Comment by crizzis** [comment]
@nvoxland In the PR I can see failed stability checks for Liquibase PRO. Is any action required from me in this regard?

**Comment by FBurguer** [comment]
Looks like it got added but we didnt close this issue (https://docs.liquibase.com/concepts/changelogs/preconditions.html)
