### ISSUE TITLE
Precondition Processing Does not Seem to Work as Documented

### ISSUE THREAD

**Issue by brennydoogles** [liquibase/liquibase#1889]
## Environment
**Liquibase Version**: 4.3.1

**Liquibase Integration & Version**: Gradle

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: PostgreSQL 13.2

**Operating System Type & Version**: Mac OS 10.15.7 

## Description
The [Liquibase Documentation on Preconditions](https://docs.liquibase.com/concepts/advanced/preconditions.html) contains the following note:
 > Note: Preconditions are checked at the beginning of the execution of a particular changelog. If you use the include tag 
 > and only have preconditions on the child changelog, those preconditions will not be checked until the migrator reaches 
 > that file. However, this behavior may change in future releases.

I have encountered a situation in which this is not the case.

## Steps To Reproduce
1. Create an empty databaseChangeLog in a file called database-changelog-master.yml
1. Create a new databaseChangeLog in a file called add_version_table.yml
1. Update add_version_table.yml to define the structure for a very simple table called 'version'
1. Using the include tag, include add_version_table.yml to database-changelog-master.yml
1. Create a new databaseChangeLog in a file called rename_version_table.yml
1. Update rename_version_table.yml to rename the 'version' table to 'version_legacy'
1. Using the include tag, include rename_version_table.yml to the end of database-changelog-master.yml
1. Create a new databaseChangeLog in a file called remove_version_legacy_table.yml
1. Update remove_version_legacy_table.yml to drop the 'version_legacy' table
1. Add a precondition to remove_version_legacy_table.yml which performs a sqlCheck to ensure that the 'version_legacy' table is empty before dropping.
1. Using the include tag, include remove_version_legacy_table.yml to the end of database-changelog-master.yml

## Actual Behavior
If liquibase update is run every time a new file is included in 'database-changelog-master.yml' (which would be after steps 4, 7, and 11 above) everything works as expected. If liquibase is run against a fresh database or a database which already has a version table (at any step in the process above prior to step 7) the above process fails with the following error:

 > [2021-06-07 12:43:45] SEVERE [liquibase.integration] Unexpected error running Liquibase: Validation Failed:
 >      1 preconditions generated an error
 >      src/main/resources/database-changelog-master.yml : liquibase.precondition.core.SqlPrecondition4e28bdd1 :   > ERROR: relation "version_legacy" does not exist
 >   Position: 32

## Expected/Desired Behavior
The behavior which is documented should be restored. Alternately, if this change was intentional, the documentation should be updated and preconditions should be updated to allow users to specify that a precondition should not be checked until the migrator reaches that file.

## Additional Context
The case illustrated above is a simplified version of what I am attempting to accomplish in real life. I have an existing table, and new functionality requires me to refactor that table to have a subset of its data residing in related tables. In order to do this with the lowest possible risk of data loss I am first renaming the table, then creating the tables that will replace it, then migrating the data, and only once I have checked that the new table has the same number of rows as the old table (using a sqlCheck precondition) do I want to delete the old table.

**Comment by molivasdat** [comment]
Hi @brennydoogles Thanks for writing up this issue.  We will add this to the issues we are processing.

**Comment by tati-qalified** [comment]
With liquibase version 4.23.0, this isn't an issue any more.
@brennydoogles I'll be closing this ticket, but feel free to reopen it if the problem persists.
