### ISSUE TITLE
Command updateTestingRollback

### ISSUE THREAD

**Issue by chornota** [liquibase/liquibase#1909]
## Environment
macOS Big-sur
**Liquibase Version**:
4.4.0
**Liquibase Integration & Version**:
CLI
**Operating System Type & Version**:
macOS big sur

## Description
After i had installed liquibase **4.4.0** from [official site](https://www.liquibase.org/download)  installer for mac os
i found out that command **updateTestingRollback** not working error was something like Unexpected token  `updateTestingRollback` (don't worry i had setted up uri, username and password parameters). Than i went to documentation and it was not marked as deprecated.
After that i typed `liquibase updateTestingRollback --help` in my terminal and the command was not in list of commands.

## Steps To Reproduce
List the steps to reproduce the behavior.

1. Download installer with version 4.4.0 from [official site](https://www.liquibase.org/download).
1. Install liquibase.
1. run `liquibase updateTestingRollback --help` in terminal and see there is no command in list of available commands.

**Comment by molivasdat** [comment]
Hi @chornota Thanks for alerting us to this issue.  Looks like we missed a command with the new CLI refactoring.  We will add it to the list of issues to process.
