### ISSUE TITLE
Classpath scan time lapse for every included changelog file

### ISSUE THREAD

**Issue by purpleloop** [liquibase/liquibase#1913]
## Environment
**Liquibase Version**: 4.3.5

**Liquibase Integration & Version**: Maven 3.2.5

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: PostgreSql 10.8.1

**Operating System Type & Version**: Windows 7

## Description
Hello,

While ugrading an app from SpringBoot 2.4.6 to 2.5.1, Liquibase dependency was updated from 3.10.3 to 4.3.5, the database management startup time increased from 4 seconds to 33 seconds.

For my changlog, I use an inclusion for each applicative version (32 times).

`<include file="major/minor/version-number.xml" relativeToChangelogFile="true" />`

With a profiling (see joined capture), it appears that with Liquibase 4.3.5, the classpath is scanned for each of the 32 resource files, which leads to an increase of the whole process duration. This behaviour did not occur in previous versions (Liquibase 3.10.3).

Regards,

## Before upgrade Liquibase 3.10.3 (SpringBoot 2.4)
<pre>
15/06/2021 10:51:21.234 INFO  [main] xx - Starting xx<br>
15/06/2021 10:51:21.294 INFO  [main] xx - No active profile set, falling back to default profiles: default<br>
15/06/2021 10:51:21.894 INFO  [main] hikari.HikariDataSource - HikariPool-1 - Starting...<br>
15/06/2021 10:51:22.034 INFO  [main] hikari.HikariDataSource - HikariPool-1 - Start completed.<br>
15/06/2021 10:51:24.328 INFO  [main] lockservice.StandardLockService - Successfully acquired change log lock<br>
15/06/2021 10:51:24.931 INFO  [main] changelog.StandardChangeLogHistoryService - Reading from xxx<br>
15/06/2021 10:51:24.971 INFO  [main] lockservice.StandardLockService - Successfully released change log lock<br>
15/06/2021 10:51:25.131 INFO  [main] xx - Started xx in 4.534 seconds (JVM running for 5.289)<br>
15/06/2021 10:51:25.141 INFO  [SpringContextShutdownHook] hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...<br>
15/06/2021 10:51:25.161 INFO  [SpringContextShutdownHook] hikari.HikariDataSource - HikariPool-1 - Shutdown completed.<br>
</pre>

## After upgrade Liquibase 4.3.5 (SpringBoot 2.5)
<pre>
15/06/2021 10:37:18.615 INFO  [main] xx - Starting xx<br>
15/06/2021 10:37:18.695 INFO  [main] xx - No active profile set, falling back to default profiles: default<br>
15/06/2021 10:37:19.316 INFO  [main] hikari.HikariDataSource - HikariPool-1 - Starting...<br>
15/06/2021 10:37:19.487 INFO  [main] hikari.HikariDataSource - HikariPool-1 - Start completed.<br>
15/06/2021 10:37:19.979 INFO  [main] liquibase.lockservice - Successfully acquired change log lock<br>
15/06/2021 10:37:51.364 INFO  [main] liquibase.changelog - Reading from xxx<br>
15/06/2021 10:37:51.455 INFO  [main] liquibase.lockservice - Successfully released change log lock<br>
15/06/2021 10:37:51.455 INFO  [main] liquibase.lockservice - Successfully acquired change log lock<br>
Skipping auto-registration<br>
15/06/2021 10:37:51.455 WARN  [main] liquibase.hub - Skipping auto-registration<br>
15/06/2021 10:37:51.465 INFO  [main] liquibase.lockservice - Successfully released change log lock<br>
15/06/2021 10:37:51.637 INFO  [main] xx - Started xx in 33.61 seconds (JVM running for 34.551)<br>
15/06/2021 10:37:51.647 INFO  [SpringApplicationShutdownHook] hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...<br>
15/06/2021 10:37:51.657 INFO  [SpringApplicationShutdownHook] hikari.HikariDataSource - HikariPool-1 - Shutdown completed.<br>
</pre>

The following profiling capture shows execution times for the ClassLoaderResourceAccessor.loadRootPaths method.

![Liquibase-4 3 5-times](https://user-images.githubusercontent.com/38167219/122247720-da3a4e00-cec7-11eb-9a73-c53e5fa50c7a.jpg)

**Comment by molivasdat** [comment]
Hi @purpleloop Thanks for writing up this issue.  We will add it to the list of issues that we are processing.

**Comment by nvoxland** [comment]
This should be handled by the in-progress #1860 PR. 

Are you able to try the build from that PR and see if it improves performance for you?

**Comment by purpleloop** [comment]
Hello,
Thanks for your returns.
After various tests, the performances seem relative to the operating system.
I will try for the PR.

**Comment by purpleloop** [comment]
I tested the #1860 PR on the 4.3.x branch to have only this change with regard to the version I use.

This really improved the changeset loading times 👍 😃 

For instance, I made a test with 100 includes of a changeset that inserts a row in a table :
* Before applying the fix : 52.971 seconds 
* After applying the fix : 2.539 seconds

Great, this solves my problem, thanks !

**Comment by nvoxland** [comment]
Thanks for the update. I'm going to keep this ticket open until we get the PR merged down so it doesn't get lost.
