### ISSUE TITLE
Support for BigQuery

### ISSUE THREAD

**Issue by parthdesai21google** [liquibase/liquibase#1942]
One of my strategic customers would like to use Liquibase for version control of Schemas on BigQuery. I see cloud Spanner is a supported DB on the website but I don't see BigQuery. So, I creating this issue to add support for BigQuery

**Comment by molivasdat** [comment]
Hi @parthdesai21google Thanks for your suggestion.

**Comment by ismailsimsek** [comment]
there is a project [liquibase/liquibase-bigquery](https://github.com/liquibase/liquibase-bigquery) is it maintained ?

**Comment by molivasdat** [comment]
Hi @ismailsimsek. The only item in the repo is the JDBC driver for BigQuery.  You are welcome to expand the extension and check in your code.

**Comment by ismailsimsek** [comment]
got it working with with BigQuery https://github.com/liquibase/liquibase-bigquery/pull/1
its also released here https://github.com/ismailsimsek/liquibase-bigquery

**Comment by andreacostantini** [comment]
Hi, I have a problem with running a github action to run Liquibase on BigQuery.
I get the following error:
Unexpected error running Liquibase: java.lang.RuntimeException: Driver class was not specified and could not be determined from the url
Who can help me?

**Comment by kataggart** [comment]
Work on BigQuery is currently active; stay tuned all. Updates to come.

**Comment by lbadam** [comment]
I'm going to close this issue as we now have a BigQuery extension. Documentation for install and usage can be found [here](https://contribute.liquibase.com/extensions-integrations/directory/database-tutorials/bigquery/).
