### ISSUE TITLE
Performance regression between 4.4.0 and 4.3.5

### ISSUE THREAD

**Issue by stuartwdouglas** [liquibase/liquibase#1945]
## Environment
**Liquibase Version**: 4.4.0

**Liquibase Integration & Version**: Quarkus

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: H2

**Operating System Type & Version**: Fedora

## Description
I have noticed a large performance degradation between 4.4.0 and 4.3.5. When running the test for https://github.com/jhipster/jhipster-sample-app-quarkus using version 4.4.0 instead of 4.3.5 adds around 90s to the total testsuite runtime.

This appears to be due to `liquibase.configuration.pro.EnvironmentValueProvider` it seems to be used a lot to look for:

[liquibase.filterLogMessages]
[liquibase.pro.licenseKey]
[liquibase.hub.apiKey]

these same values are looked up repeatedly, and the iteration over all the env vars and then calling `StringUtil.toKabobCase` ends up being really expensive.

## Steps To Reproduce
Build build and test https://github.com/jhipster/jhipster-sample-app-quarkus, note the total build time, change to version 4.4.0 and build, locally I see an extra 2m total time.

## Actual Behavior
It is much slower than it used to be.

## Expected/Desired Behavior
Performance will be comparable to 4.3.5

**Comment by nvoxland** [comment]
Thanks for the report. I'll take a look

**Comment by nvoxland** [comment]
I improved the performance to toKabobCase and also added some higher-up caching which significantly improved the performance in #1952

**Comment by stuartwdouglas** [comment]
Awesome, thanks
