### ISSUE TITLE
UpdateTestingRollback not working with Liquibase 4.4.0

### ISSUE THREAD

**Issue by chanpreetkaurv** [liquibase/liquibase#1961]
## Environment

**Liquibase Version**: 4.4.0

**Liquibase Integration & Version**: gradle

**Database Vendor & Version**: RDS Postgres

## Description

UpdateTestingRollback not working with Liquibase 4.4.0

    
**[Container] 2021/06/29 21:04:35 Running command export migrate_status_temp=$(docker run --rm -v $CODEBUILD_SRC_DIR/Database/liquibase/migration/:/liquibase/changelog liquibase/liquibase --defaultsFile=/liquibase/changelog/liquibase.properties --username=$USERNAME --password=$PASSWORD --defaultSchemaName=$SCHEMA --url=$TEMP_DB_URL updateTestingRollback)
Unexpected argument(s): updateTestingRollback

For detailed help, try 'liquibase --help' or 'liquibase <command-name> --help'

Did you mean: rollback-one-update or rollback-to-date or update?**

## Actual Behavior
UpdateTestingRollback works with Liquibase 4.3.5. It should work on 4.4.0

**Comment by molivasdat** [comment]
Hi @chanpreetkaurv Thanks for alerting us to this issue.  We will add it to the list of issues that were are processing.

**Comment by nvoxland** [comment]
This is a duplicate of #1909. I'll close this one to keep discussion centralized. Thanks for the report
