### ISSUE TITLE
Liquibase-core includes a shaded jackson-databind

### ISSUE THREAD

**Issue by kmurthy0** [liquibase/liquibase#1965]
## Environment

**Liquibase Version**: 4.4.0

**Liquibase Integration & Version**: spring boot 2.4.5

**Liquibase Extension(s) & Version**: 4.4.0

**Database Vendor & Version**: Postgres 10.6

**Operating System Type & Version**: Linux (container)

## Description
We use liquibase-core as part of a Java spring boot application and it's working fine functionally. We run Black Duck SCA scans to check for vulnerabilities in third party/open source software included in our application. This scan identified that liquibase-core jar includes a shaded copy of jackson-databind (possibly jackson 2.2.3). See attached screenshots. It seems to be inside `liquibase/pro/packaged" package.

The problem with shaded dependencies is that if a vulnerability is identified, we cannot force a newer version by explicitly declaring it in our build.gradle to mitigate the vulnerability. We operate in regulated environments and have mandates for fixing vulnerabilities very quickly. We don't have the luxury of waiting for third party components to update dependencies.

I would like to request that a variant of liquibase-core be published that doesn't include shaded jackson but simply declares the dependency in maven pom. 

## Steps To Reproduce
Run Synopsis Black Duck SCA analysis on liquibase-core-4.4.0.jar.

## Actual Behavior
liquibase-core contains shaded dependency jackson-databind

## Expected/Desired Behavior
liquibase-core doesn't contain shaded dependency. Dependencies are declared in maven pom

## Screenshots (if appropriate)
![Screen Shot 2021-07-02 at 9 44 04 AM](https://user-images.githubusercontent.com/35911435/124305819-71371500-db1a-11eb-8c09-1fe2db78a9d6.png)
-----
![Screen Shot 2021-07-02 at 9 06 36 AM](https://user-images.githubusercontent.com/35911435/124305878-8613a880-db1a-11eb-8b56-757be2021d6a.png)

## Additional Context
N/A

**Comment by molivasdat** [comment]
Hi @kmurthy0 Thanks for alerting us to this issue.  We will add it to the list of issues we are processing.

**Comment by nvoxland** [comment]
We have a couple options we're looking into.

**Comment by nvoxland** [comment]
We need jackson-databind for the library we use for liquibase pro license key management. Longer term, we may use something different but for now we need to keep the jackson-databind dependency. We have it shaded in, since it's a commonly used library and we don't want our version to be conflicting with what else may be in an application.

We've updated the version we use so that it's not something that gets flagged as an insecure version as of around 4.5.0.

**Comment by JosephCen** [comment]
@nvoxland May I know the detail version of jackson-databind used in liquibase-core v4.4.0? With the detail version, we can add some comment in relevant scan result.
