### ISSUE TITLE
objectQuotingStrategy QUOTE_ALL_OBJECTS not working as intended

### ISSUE THREAD

**Issue by shenbaga-murugan** [liquibase/liquibase#1982]
I have used "**objectQuotingStrategy: QUOTE_ALL_OBJECTS**" in my changeset. So the table is created with name "table_one" and column "id". But when Liquibase tries to create another table with a foreign key reference to a column in "table_one" table, then the generated script is 

**FOREIGN KEY ("table_one_id") REFERENCES "SA".table_one(id))**

Due to the above, the DB tries to find the uppercase table name "TABLE_ONE" instead of "table_one". Ideally, Liquibase should be generating **FOREIGN KEY ("table_one_id") REFERENCES "SA"."table_one"("id"))**

## Environment

**Liquibase Version**:

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

**Operating System Type & Version**:

## Description

A clear and concise description of the issue being addressed.
- Describe the actual problematic behavior.
- Ensure private information is redacted.

## Steps To Reproduce

List the steps to reproduce the behavior.
- Please be precise and ensure private information is redacted
- Include things like
  - Files used - sql scripts, changelog file(s), property file(s), config files, POM Files
  - Exact commands used - CLI, maven, gradle, spring boot, servlet, etc.

## Actual Behavior
A clear and concise description of what happens in the software with the **version used**.
- Include console output if relevant
- Include log files if available.

## Expected/Desired Behavior
A clear and concise description of what happens in the software **after** a fix is created and merged.

**Comment by molivasdat** [comment]
Hi @shenbaga-murugan Thanks for adding this.  Can you share a little more context?  I have added the additional information needed in order to process this issue in the description below your original description.

**Comment by vladkabat** [comment]
`<changeSet id="1">
        <sql dbms="cassandra">
            DELETE
            FROM schema."TableName"
            WHERE "fieldName" IN ('a1', 'a2')
        </sql>
    </changeSet>`
    
    Error - Field 'filename' not found.

**Comment by molivasdat** [comment]
Hi @vladkabat Not sure if this is cassandra specific error, if so , please open an issue in the cassandra extension as I just tried a similar mixed case delete on PostgreSQL and was successful with the changeset.  I believe for the most part <sql> changetypes from liquibase are taken as is.  You may be able to strip comments or define boundaries but it typically leaves it alone.

**Comment by vladkabat** [comment]
@molivasdat Hi, This error occurs because the field `fieldName` was not wrapped in quotation marks.

**Comment by camsaul** [comment]
I think this is the offending code

https://github.com/liquibase/liquibase/blob/d4f80c33124e850695e248437a91a0bb8e3a9e52/liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java#L274-L291

If `fkConstraint.getReferences()` returns `null` then it generates column references and calls `escapeColumnNameList`:

https://github.com/liquibase/liquibase/blob/d4f80c33124e850695e248437a91a0bb8e3a9e52/liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java#L287-L289

if it doesn't return `null`, no escaping happens:

https://github.com/liquibase/liquibase/blob/d4f80c33124e850695e248437a91a0bb8e3a9e52/liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java#L279-L284

`getReferences` itself doesn't escape anything:

https://github.com/liquibase/liquibase/blob/256675bca43a089e32c940e10ed8ed7a5f9d66f6/liquibase-core/src/main/java/liquibase/statement/ForeignKeyConstraint.java#L61-L63

and in places where a `ForeignKeyConstraint` is created it's not escaped either: 

https://github.com/liquibase/liquibase/blob/d4f80c33124e850695e248437a91a0bb8e3a9e52/liquibase-core/src/main/java/liquibase/change/core/AddColumnChange.java#L127

https://github.com/liquibase/liquibase/blob/d4f80c33124e850695e248437a91a0bb8e3a9e52/liquibase-core/src/main/java/liquibase/change/core/CreateTableChange.java#L105-L106

**Comment by nvoxland** [comment]
It looks like this ticket is covering a couple different cases where there is an unexpected lack of escaping:

```
<sql>SOME SQL HERE</sql>
```
and
```
<constraints foreignKeyName="fk_test" references="test_table(id)"/>
```

But in both those cases it is by design. It's too hard for us to know all the strange SQL syntax databases will support, so the QUOTE_ALL_OBJECTS setting is really just for attributes that are simply object names. Anything that can be arbitrary SQL subsets is not something we're able to figure out how to quote and so we don't try.

I'll open up a doc ticket to better explain that. But, if you are using `<sql>` or `references` you can include the quoting you need within the sql you are giving us.
