### ISSUE TITLE
loadData performance degredation between v4.0.0 and 4.4.0

### ISSUE THREAD

**Issue by davey-e** [liquibase/liquibase#1984]
## Environment

**Liquibase Version**: Community 4.0.0 and Community 4.4.0

**Liquibase Integration & Version**: maven

**Database Vendor & Version**: MySql 8.0 running in a Docker container

## Description

We currently use Liquibase 4.0.0 and we would like to upgrade to the latest version 4.4.0, but we have noticed some performance degradation and we're reluctant to upgrade because of this.

When running loadData changesets with csv files we have noticed a significant performance degradation between Liquibase 4.0.0 and newer versions of Liquibase (specifically 4.4.0, but could also affect other versions above 4.0.0.)

## Steps To Reproduce

[liquibase_upgrade_test.zip](https://github.com/liquibase/liquibase/files/6816679/liquibase_upgrade_test.zip)

Using the attached sample project, run mvn liquibase:update with Liquibase 4.0.0 to create a new mySql schema with 3 tables and with data loaded into the tables from csv files.

Repeat the same mvn liquibase:update command to create another new schema (don't use the same schema that was used for 4.0.0) but this time with Liquibase 4.4.0. (update the pom.xml file in the project)

## Actual Behavior
The time taken to run the loadData changesets significantly increases.

## Expected/Desired Behavior
The time taken to run the loadData changesets should not be any longer than when running with 4.0.0

## Screenshots (if appropriate)
Running with Liquibase 4.0.0:

![image](https://user-images.githubusercontent.com/32623360/125634016-a11fd2c2-11d3-40f3-9234-385327835236.png)

Total time taken = 2.728s, loadData changesets only take a few ms to run

Running with Liquibase 4.4.0:

![image](https://user-images.githubusercontent.com/32623360/125634257-167a5013-8f29-4696-b37b-5b4a586c9488.png)

Total time taken = 9.031s, loadData changesets can take several seconds to run.

## Additional Context
Although running loadData changesets going from taking a few ms to a few seconds may not seem significant, we have a lot of seed data that we run for our database so the total time to create a new schema from scratch with all of our current liquibase changes has gone from approx 4 mins with Liquibase 4.0.0 to approx 10 mins with Liquibase 4.4.0, which is a significant increase. We also use Liquibase to load test data for our development environments and although we haven't tested running our test data changes with Liquibase 4.4.0 we can see from the time increase that it will take much longer to run (current time to create a new schema from scratch and populate with our test data is about 14 mins).

The main reason that this increase is an issue for us is that we use our test data changesets as part of our CI/CD process and so every pull request build would end up taking at least twice as long to run.

**Comment by molivasdat** [comment]
Hi @davey-e Thanks for writing up this issue.  We did add a performance update in v4.4.1.  Can you try that one and see if it resolves your issue?

**Comment by davey-e** [comment]
Hi @molivasdat, thanks for your reply.

I've done some further testing using 4.4.2 (the current latest version) and I can see that the load time for csv files has definitely improved since 4.4.0. One of the csv files that I had originally tested with had 100 rows of data and the load time for that has gone from 3683ms for 4.4.0 to 286ms for 4.4.2, so this is definitely an improvement.

However there is still a difference between 4.0.0 and 4.4.2 and for larger files the difference becomes even more significant. I've tested with a few files with different number of rows and as the number of rows increases the time taken for 4.4.2 increases exponentially compared with 4.0.0

I've attached a spreadsheet with a comparison of the time taken for 4.0.0 and 4.4.2 so that you can see the difference. If it helps I can also provide the source files that I used to run these comparisons.

[liquibase_csv_load_time_comparison.xlsx](https://github.com/liquibase/liquibase/files/6908148/liquibase_csv_load_time_comparison.xlsx)

**Comment by molivasdat** [comment]
Hi @davey-e .  Thanks for the feedback.  Yes if you could provide the source for the tests that would be great.

**Comment by davey-e** [comment]
Hi @molivasdat, zip file attached with the source files for the test.

If you look in table3_seed_data.xml you'll see that it points to table3_seed_data_10.csv, this file has 10 rows of data in it. So its a case of running that with 4.0.0 and 4.4.2 to compare the times to load the data for that file (starting with a blank schema each time), then change to table3_seed_data_50.csv and run again with 4.0.0 and 4.4.2, then go through all the other table3 csv files all the way up to table3_seed_data_256000.csv

[liquibase_upgrade_test_different_csv_sizes.zip](https://github.com/liquibase/liquibase/files/6915443/liquibase_upgrade_test_different_csv_sizes.zip)

**Comment by molivasdat** [comment]
Hi @davey-e Thanks for your upload.  We will add it the list of issues in the queue that we are processing.

**Comment by nvoxland** [comment]
@davey-e we did some additional performance work with 4.5.0 based on your examples. 

Can you see how that version is performing for you? It's looking good from my side.

**Comment by davey-e** [comment]
Hi @nvoxland thanks for the feedback.

I've just done some testing again using the same test data that I had used before (I just jumped straight to the csv file with 256000 rows this time rather than running all of the different sized csv's) and although there has been some improvement with 4.5 compared with 4.4.0 and 4.4.2, unfortunately the time it takes with 4.5.0 is still significantly longer than 4.0.0, as you can see here:

Liquibase Version	Time take to run loadData for 256000 row csv
4.0.0				19577ms (19.5 seconds)
4.4.2				607290ms (~10 minutes)
4.5.0				285319ms (~5 minutes)

Is there anything that can be done to return the performance back to what it was with 4.0.0?

We do load a lot of seed and test data through Liquibase and even the increase in time taken between 4.0.0 and 4.5.0 is still significant enough that it would prevent us from upgrading.

Cheers,
Dave

**Comment by nvoxland** [comment]
Thanks for the update, I'll do a bit more profiling. 

There is a 4.6.1 release as well now too. I don't remember a change which should have impacted the loadData performance in there, though.

Based on the profiling results, I'll let you know if there is a work-around to improve performance until a better fix gets released.
