### ISSUE TITLE
Getting error by using unexpectedChangeSets command.

### ISSUE THREAD

**Issue by obovsunivskyii** [liquibase/liquibase#1987]
## Environment

**Liquibase Version**: 4.4.1-SNAPSHOT

## Steps To Reproduce

1. update any changelog file.
2. use a command

`liquibase unexpectedChangeSets`

## Actual Behavior

Getting errors

`liquibase unexpectedChangeSets`

> Error parsing command line: Invalid argument '--verbose': missing required argument
> For detailed help, try 'liquibase --help' or 'liquibase <command-name> --help'

`liquibase unexpectedChangeSets --verbose`

> Error parsing command line: Missing required parameter for option '--verbose' (PARAM)
> For detailed help, try 'liquibase --help' or 'liquibase <command-name> --help' 

## Expected/Desired Behavior

The command should be executable without a problem.
[unexpectedChangeSets Documentation](https://docs.liquibase.com/commands/community/unexpectedchangesets.html)

## Workaround:

Using

`liquibase unexpectedChangeSets --verbose=true`

**Comment by molivasdat** [comment]
Hi @bolingbrook Thanks for writing this up.  Can you add an example changelog and the update to the changelog along with the exact steps it took to get this error.  Thanks in advance.

**Comment by nvoxland** [comment]
The changelog shouldn't matter. I think I know what the problem is, we just need to let the CLI know that --verbose can be a stand-alone argument

**Comment by StevenMassaro** [comment]
This change possibly caused this regression, due to the introduction of the `Required()` flag: https://github.com/liquibase/liquibase/commit/658dd31e915a888214eb5f8d66b076c9ea7bd2d9#diff-6bfcc2d7ae730973b09b88f1f6ad07973def342d8ca2eb748380d46f26b6feaa
