### ISSUE TITLE
Invalid Yaml throws ClassCastExceptions

### ISSUE THREAD

**Issue by gilles-gosuin** [liquibase/liquibase#1988]
## Environment

**Liquibase Version**: 4.3.5

## Description

An invalid YAML changelog was causing a ClassCastException; what I found in the code makes no sense whatsoever:

`liquibase.parser.core.yaml.YamlChangeLogParser`

```java

48      if (obj instanceof Map) {
            // ...
68      } 
69      else if (((Map) obj).containsKey("changeLogId")) {
            // ...
72      }

```

Sure enough, a ClassCastException is thrown from line 69 when obj is not a Map.

## Steps To Reproduce

Loading a changelog such as this one should do it:

```yaml
databaseChangeLog:
  - - logicalFilePath: "myFilePath"
```

**Comment by nvoxland** [comment]
Thanks, we'll get that branch cleared out. We checked the functionality it was trying to handle, and it doesn't even need that branch there.

The error is triggered from having that empty `- changeSet: {}` object. If you removed that line to have your minimal changelog just be:

```
databaseChangeLog:
  - logicalFilePath: "myFilePath"
```
it should avoid the problem until we can get the parsing error improved.
