### ISSUE TITLE
PostgreSQL NUMERIC[] datatype is not generated properly with the generateChangeLog command

### ISSUE THREAD

**Issue by szandany** [liquibase/liquibase#1995]
## Environment
**Liquibase Version**:
4.4.1
**Liquibase Integration & Version**: 
Any
**Database Vendor & Version**:
PostgreSQL
**Operating System Type & Version**:
Windows, Linux, MacOS

## Description
PostgreSQL NUMERIC\[ ] datatype in not generated properly with the generateChangeLog command.

## Steps To Reproduce
1. Run the following changeset to create a NUMERIC \[ ] array type with the Liquibase update command against a Postgres Database.

```
--changeset TsviZ:45555-createtablecontacts 
CREATE TABLE contacts (
id serial PRIMARY KEY,
name VARCHAR (100),
phones TEXT [],
po_box NUMERIC []
);
```

run the generateChangeLog command against the same Postgres database to retrieve the table "contacts" changeset.
For example:
`liquibase --changeLogFile=newChangelog.postgresql.sql generateChangeLog`

## Actual Behavior
The resulting changeset appears to have an improper syntax for the NUMERIC \[ ] array type.
For example:

```
changeset Datical:1626818266975-1
CREATE TABLE "public"."contacts2" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(100), "phones" TEXT[], "po_box" NUMERIC[131089], CONSTRAINT "contacts2_pkey" PRIMARY KEY ("id"));
Expected/Desired Behavior
```

Notice that syntax looks like the following NUMERIC[](131089).  This will cause a failure when attempted to deploy.

## Expected Behavior
The changeset should look like the following:

```
changeset Datical:1626818266975-1
CREATE TABLE "public"."contacts2" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(100), "phones" TEXT[], "po_box" NUMERIC[], CONSTRAINT "contacts2_pkey" PRIMARY KEY ("id"));
```

## Test Requirements (Internal Liquibase QA)
* Verify generate-changelog has the correct syntax for the column ‘po_box’ numeric.
  * `liquibase --log-level INFO generate-changelog <changelog>`
  * Formatted SQL changelog specifies `"po_box" NUMERIC[]`
  * XML changelog specifies the column `<column name="po_box" type="NUMERIC[]"/>`
  * JSON changelog specifies the column 
```
                "column": {
                  "name": "po_box",
                  "type": "NUMERIC[]"
                }
```

  * YML changelog specifies the column
  * ```
        - column:
            name: po_box
            type: NUMERIC[]
```


* Verify update-sql produces correctly specified SQL to create the NUMERIC \[ ] column.
  * `liquibase --log-level INFO update-sql --changelog-file <changelog>`
  * Formatted SQL changelog
  * XML changelog
  * JSON changelog
  * YML changelog
* Verify update using the generated changelog is successful.
  * `liquibase --log-level INFO update --changelog-file <changelog>

**Automated Test Requirements**

* No new functional automated tests required. 
* A liquibase/liquibase-test-harness test is required. 
  * Add an XML changelog with the changeset to create table `contacts`
    * liquibase-test-harness/src/main/resources/liquibase/harness/change/changelogs/postgresql. 
  * Add the JSON snapshot for test validation:
    * src/main/resources/liquibase/harness/change/expectedSnapshot/ 
  * Add the generated SQL for test validation:
    * src/main/resources/liquibase/harness/change/expectedSql/ 
  * Validate that having a column with datatype `NUMERIC[]` does not fail due to incorrect datatype definition.



┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-2110) by [Unito](https://www.unito.io)

**Comment by andrulban** [comment]
Fix for NUMERIC[] is merged, test harness PR will be merged after the release is done, so closing the issue.
