### ISSUE TITLE
setColumnRemarks change type is not working for MySQL and MariaDB

### ISSUE THREAD

**Issue by AlexanderSashchenko** [liquibase/liquibase#2003]
## Environment

**Liquibase Version**: any up to 4.4.2

**Liquibase Integration & Version**: CLI, test-harness

**Liquibase Extension(s) & Version**: na

**Database Vendor & Version**: MySQL of any version, MariaDB of any Version

**Operating System Type & Version**: Windows 10

## Description

setColumnRemarks change type is not working for MySQL and MariaDB databases because of a bug with 'columnDataType' attribute which is [required for above databases according to documentation](https://docs.liquibase.com/change-types/community/set-column-remarks.html). However when one tries to run Liquibase update command for setColumnRemarks change type with columnDataType attribute against above named databases the error is thrown: _**Unexpected error running Liquibase: Error parsing line 11 column 44 of myChangeLog.xml: cvc-complex-type.3.2.2: Attribute 'columnDataType' is not allowed to appear in element 'setColumnRemarks'.**_ On the other hand if one tries not to use 'columnDataType' for specified changeset the NullPointerException is thrown because SetColumnRemarksGenerator expects to obtain column data type from statement. The attribute is added to src/main/resources/www.liquibase.org/xml/ns/dbchangelog .xsd file so the problem might be in a XML parser.

Screenshot of the error and changelog is
![C__Users_osashc_liquibase_maven_myChangeLog xml - ](https://user-images.githubusercontent.com/58402322/126962466-c2042dea-0f2f-4578-8597-bd831155c246.png)
 attached

## Steps To Reproduce

Run Liquibase (any version) update command for setColumnRemarks change type with columnDataType attribute against MySQL or MariaDB of any version. columnDataType is not allowed for setColumnRemarks change type.

## Actual Behavior
Described above error is thrown. 

## Expected/Desired Behavior
Liquibase update command is executed successfully. A remark (comment) is added to a scpecified column.

**Comment by molivasdat** [comment]
Hi @AlexanderSashchenko Can you change your xsd line 6 to use 4.3 or above for the columnDataType change and see if that allows you to use the columnDataType attribute?

**Comment by AlexanderSashchenko** [comment]
Need to use XSD of newest version
