### ISSUE TITLE
foreignKeyConstraintExists fails with CS collation MSSQL Server DB

### ISSUE THREAD

**Issue by Lonzak** [liquibase/liquibase#2009]
## Environment

**Liquibase Version**: 3.5.3 and 3.5.4

**Liquibase Integration & Version**: maven

**Database Vendor & Version**: MSSQL Server 2014

## Description

---Created a DB with CS collation
CREATE DATABASE CRDB_CS_NEW_CRDB COLLATE SQL_Latin1_General_CP1_CS_AS;

--Start liquibase updates
```
<changeSet author="${default.author}"  id="Drop_LP_Contraint">
  <validCheckSum>ANY</validCheckSum>
  <preConditions onFail="MARK_RAN" >
    <foreignKeyConstraintExists  foreignKeyName="FK_LP_device"/>
  </preConditions>
  <dropForeignKeyConstraint baseTableName="Employee_Devices" constraintName="FK_LP_device"/>
</changeSet>
```

> Error while executing Liquibase updates:
> liquibase.exception.MigrationFailedException: Migration failed for change set _liquibase/11.0/employee_devices-ddl.xml:: Drop_LP_Contraint::Test DA:
> Reason:
> liquibase/changelog-master.xml : liquibase.precondition.core.ForeignKeyExistsPrecondition@3c952a33 : Invalid object name 'SYS.INDEXES'._

Tested following queries 
select * from SYS.INDEXES;
--No Result

select * from sys.indexes;
--Result exists

**Tried the same in CI Collation DB and all worked as charm.**

Disclaimer: This is a copy of saikat sarkar's issue however everything was moved to github and nobody seems to work on the old jira anymore...

**Comment by molivasdat** [comment]
Hi @Lonzak Thanks for writing up this issue.  Quick question, does this still fail on Liquibase 4.x, because we are not planning on releasing any updates on the 3.x branches.

**Comment by Lonzak** [comment]
Good question - didn't test it with version 4.X so I can't tell. I forwarded the question to saikat sarkar maybe he can anwer...

**Comment by molivasdat** [comment]
Hi @Lonzak Were you able to contact saikat sarkar to find out if 4.x works for you or not.
