### ISSUE TITLE
Create ThreadLocal ScopeManager

### ISSUE THREAD

**Issue by nvoxland** [liquibase/liquibase#2018]
## Overview

The current imlementation of ScopeManager is based around a singleton instance. Sometimes that works well, sometimes not. Alternative ScopeManager implementations are left as an exercise for the user (such as in#1768).

A ThreadLocalScopeManager would allow liquibase to run concurrently in separate threads.

## Requirements

Liquibase should continue to use the SingletonScopeManager as the default, but provide a way to optionally activate the separate ThreadLocalScopeManager. Not sure the best way off hand, the LiquibaseConfiguration system is too late in the process. May need to depend on a system property or even a registered subclass of ThreadLocalScopeManager? _Maybe other ideas?_

Will need to add tests to ensure that the threading is working correctly, and that there is nothing else in liquibase that conflicts in a multi-threaded environment. The work will be as much about ensuring Liquibase overall works in concurrent threads as that the Scope object supports it.

## Implementation

The example in #1768 is a good start.

**Comment by jamey-clari** [comment]
I'd actually argue that the thread-local implementation should likely be the preferred default as most users of Liquibase are in an enterprise type environment and it's not unlikely that multiple threads might be using Liquibase tooling against multiple databases concurrently.  Aside from this a pluggable thread-safe alternative to the default is a big step in the right direction.  Thanks to all for getting this going as we will definitely be able to make use of it.
