### ISSUE TITLE
`onDelete` property ignored for MySQL

### ISSUE THREAD

**Issue by nsobadzhiev** [liquibase/liquibase#2022]
## Environment

**Liquibase Version**:
4.3.5

**Liquibase Integration & Version**: 
Maven

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
MySQL (connector version 8.0.26) (db engine 8.0.25)

**Operating System Type & Version**:
MacOS, Docker image `openjdk:11-jre-slim`

## Description

If I create a table with a field that's a foreign key to another table, and I specify an `onDelete` property (DELETE in my case, but the same happens for other options too).

This doesn't reproduce for every field, but there's something with particular tables and fields that makes it not work. In the DB schema, I can clearly see in the SQL that the foreign key is created, but it's missing the `ON DELETE CASCADE`.

## Steps To Reproduce

I created a demo Spring Boot app reproducing this: https://github.com/nsobadzhiev/liquibase-cascade-demo. Just run it, having MySQL running. You can change the connection settings in `application.yml`.

## Actual Behavior

The resulting relationship has `onDelete: RESTRICT` - the default value

## Expected/Desired Behavior

I want to have these records cascade

**Comment by molivasdat** [comment]
Hi @nsobadzhiev Thanks for creating this and creating a repo to show how this fails. It is much appreciated.  We are adding this to the list of issues we are processing.

**Comment by nvoxland** [comment]
For the constraint setup in createTable, there is no onDelete attribute, it is deleteCascade=true|false (https://docs.liquibase.com/change-types/community/create-table.html).

We do need to improve the error handling when unknown attributes are given in yaml to better catch setups like yours, but if you change your changelog to `deleteCascade: true` it will work as you expect.
