### ISSUE TITLE
setDefaultSchema does not work . All changesets getting executed against public schema.

### ISSUE THREAD

**Issue by p-muluk** [liquibase/liquibase#2030]
## Environment

**Liquibase Version**: 4.4.1

**Liquibase Integration & Version**: spring boot 2.5.2

**Liquibase Extension(s) & Version**:  N/A

**Database Vendor & Version**: MySql 8.0

**Operating System Type & Version**: Windows 10

## Description

I am creating Schema-Based Multi Tenant application with spring boot(2.5.2) , mySQL 8.0 and Liquibae 4.4.1.

I expect that all my tenant tables and liquibase internal tables should be created inside a tenant schema which I specify before running the migration.

liquibase.setDefaultSchema(tenantSchema); --sets the schema for changesets
liquibase.setLiquibaseSchema(tenantSchema); -- sets schema for liquibase internal tables

I can see that liquibase internal tables are getting created inside tenant schema correctly .

But liquibase is always executing my changesets against public schema. Looks like setting the deafult schema prior to liquibase migration has no effect. I am using sql-based changesets and I don't want to switch to xml

## Steps To Reproduce

1. create multiple schemas in MySql database.
2. disable liquibase auto config in spring boot and manually create Spring Liquibase objeect.
3. create a simple create table sql script .
4. now try to run this sql against all schemas one by one. Before running the migration , set the target schema lke-liquibase.setDefaultSchema(schema)
5. You will get 'table already exists ' error.

## Actual Behavior
All changesets are getting executed against public schema eve if I specify the target schema before running migration.

## Expected/Desired Behavior
All changesets should be executed against the schema which is specified by calling setDefaultSchema on liquibase object.

**Comment by molivasdat** [comment]
Hi @p-muluk Thanks for creating this issue.  We will add this to the list of issues that we are processing.

**Comment by FBurguer** [comment]
If this is a still an issue for you, please try to reopen the issue and we will look into it again. Thanks!
