### ISSUE TITLE
generateChangeLog does not output schema name on Postgres.

### ISSUE THREAD

**Issue by calvinthomas** [liquibase/liquibase#2035]
## Environment

**Liquibase Version**: 4.4.3

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**:  None

**Database Vendor & Version**: Postgres 11

**Operating System Type & Version**: Windows 10

## Description

A clear and concise description of the issue being addressed.
- When attempting to use generateChangeLog on a Postgres database, schema names are not included when --includeSchema or --includeCatalog are specified

## Steps To Reproduce

List the steps to reproduce the behavior.
- Create a database that uses multiple database schemas in postgres, 
- Use a simple liquibase.properties file, e.g.

```
changeLogFile:dbchangelog.postgresql.sql
url:  jdbc:postgresql:/pgdb/:5432/db
username:  postgres  
password:  [PASSWORD]
classpath:  postgresql-42.2.23.jar
schemas=testschema
```
Call liquibase as follows:

```
liquibase --changeLogFile=dbchangelog.postgresql.sql --includeSchema=true generateChangeLog
```

## Actual Behavior
All tables within testschema are created in the changeset, however they are all created in the public schema.

## Expected/Desired Behavior
Schema name should be preserved in the change set, e.g. create table public.test_table... should be create_table testschema.test_table.

**Comment by molivasdat** [comment]
Hi @calvinthomas Thanks for creating this issue.  We will add it to the list of issues to process.

**Comment by rleinfellner** [comment]
It seems to partially work as the schema is included when the FK's are made, but not for the tables. So the FK's reference the schema name. This of course means even if the tables were in public, the FK's wont work.
ie the schema is called **sbtest**

I.E. <createTable tableName="UserRegistrations"> (missing)
but
        <addForeignKeyConstraint baseColumnNames="userID" baseTableName="UserLogins" constraintName="userID_IsUsedBy_UserRegistrations_fk" deferrable="false" initiallyDeferred="false" onDelete="CASCADE" onUpdate="CASCADE" referencedColumnNames="userID" referencedTableName="UserRegistrations" referencedTableSchemaName="**sbtest**" validate="true"/> (present)

**Comment by FBurguer** [comment]
on `4.14` (maybe this was available before) you can add currentSchema=*schemaName* to your URL, this is the way to tell liquibase what schema to use.
