### ISSUE TITLE
Liquibase generateChangeLog with --includeSchema=schema1,schema2 and --schemas doesn't prefix schema names for Postgres 

### ISSUE THREAD

**Issue by szandany** [liquibase/liquibase#2046]
## Environment

**Liquibase Version**:
4.4.3
**Liquibase Integration & Version**: 
CLI
**Operating System Type & Version**:
Linux, Windows

## Description
When attempting to run the generate

## Steps To Reproduce
Run the generateChagneLog against multiple schemas
For example:
`$ liquibase --includeSchema=true --schemas=public,crops --changeLogFile=changeLogWithPrefixedSchemaName.postgresql.xml generateChangeLog`

## Actual Behavior
The resulting changelog will have all schema changes from both schemas, but will miss the prefixed schema name. 

## Expected/Desired Behavior
The resulting changelog will have all schema changes from both schemas, and the prefixed schema name.

**Comment by nvoxland** [comment]
@szandany verified that this was resolved as of 4.8.0 at least.

**Comment by pakmans** [comment]
I works when used directly, but it doesn't work when used with maven plugin (4.15.0).

**Comment by kataggart** [comment]
@pakmans Can you submit a new issue with the details please? Want to make sure your issue doesn't get lost on a currently closed one. Thanks.

**Comment by pakmans** [comment]
@kataggart  Done: https://github.com/liquibase/liquibase/issues/3174
