### ISSUE TITLE
Exception during dropAll on a custom DB2 Database implementation

### ISSUE THREAD

**Issue by wardvijf** [liquibase/liquibase#2058]
**Liquibase Version**:
4.4.3

**Database Vendor & Version**:
DB2i

## Description
We extended DB2Database to do some tweaks to make it work on DB2i (similar to what they do in https://github.com/liquibase/liquibase-db2i). 

An exception occurs when executing the dropAll command.
I attached a PR to fix this. 

## Steps To Reproduce
- Register your own custom DB2iDatabase (which extends DB2Database and overrides supportsBooleanDataType)
- execute a dropAll against a DB2i database

## Actual Behavior
An exception occurs with the stacktrace mentioned below.

## Expected/Desired Behavior
No exception occurs and the dropAll executes normally

## Additional information
During a dropAll we get the following exception while liquibase tries to create the databasechangeloglock table:

`Caused by: liquibase.exception.LockException: liquibase.exception.DatabaseException: [SQL0204] BOOLEAN in *LIBL type *SQLUDT not found. [Failed SQL: (-204) CREATE TABLE "RICUSTOMER".DATABASECHANGELOGLOCK (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DBCHGLOGLOCK PRIMARY KEY (ID))]
        at liquibase.core@4.5.0-local-SNAPSHOT/liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:293)
        at liquibase.core@4.5.0-local-SNAPSHOT/liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:211)`

DB2i does not support boolean types, and thus we specified this in our custom DB2iDatabase by overriding the existing DB2Database.supportsBooleanDataType.

The implementation in liquibase.datatype.core.BooleanType however is not correct, it does not take this into consideration because of a bug. It uses an incorrect isAssignableFrom:
`if (database.getClass().isAssignableFrom(DB2Database.class)) {
			if (((DB2Database) database).supportsBooleanDataType())
				return new DatabaseDataType("BOOLEAN");
			else
				return new DatabaseDataType("SMALLINT");
        }`

**Comment by molivasdat** [comment]
Hi @wardvijf Thanks for creating this issue.  We will add it to the list of issues that we are processing.  In addition, is there a reason you are creating this issue here and not in the DB2i extension?

**Comment by ducatier** [comment]
Hi @molivasdat, the issue occurs icm with the liquibase-dbi2 plugin. However the actual bug is in the liquibase-core. See #2067

**Comment by consultantleon** [comment]
The issue is in liquibase-core , once again highlighting that liquibase code style does not comply with the S.O.L.I.D. principles :-)
https://en.wikipedia.org/wiki/SOLID
I major refactor/rewrite would be needed to achieve SOLID ...
Is anyone going to pickup this tiny simple but important fix or can I create a PR to do so?

**Comment by nvoxland** [comment]
There is a PR to fix it (#2059) that is working it's way through. 

You are right that we need to refactor the code to better rely on the subclasses vs. dealing with instanceof checks. It's something we are working on, but you're also right that it is a major change so will take some time to finish up in a way that we know doesn't break things and continues to stay API-compatible.

**Comment by consultantleon** [comment]
Thanks Nathan!
