### ISSUE TITLE
Child of #1277: Error loading relative file when logicalFilePath is set (Breaks migration from 3.x to 4.x)

### ISSUE THREAD

**Issue by smainz** [liquibase/liquibase#2074]
## Environment

**Liquibase Version**: 4.4.3 (and all 4.x, not in 3.x)

**Liquibase Integration & Version**: any

**Liquibase Extension(s) & Version**:  liquibase-core

**Database Vendor & Version**: H2 (and all others)

**Operating System Type & Version**: Windows 10 (and all others)

## Description

In https://github.com/liquibase/liquibase/issues/1277 @darkcamper reported an error about loading sql scripts relative to a change log file whicht has a 'logicalFilePath' set.

This has been fixed in https://github.com/liquibase/liquibase/pull/1798 but it has been overlooked that the same error is present in
- `LoadDataChange`,
- `CreateProcedureChange` and 
- `CreateViewChange`

A PR to fix this can be found here: https://github.com/liquibase/liquibase/pull/2073

## Steps To Reproduce

See https://github.com/liquibase/liquibase/pull/2073

## Actual Behavior

See https://github.com/liquibase/liquibase/pull/2073

## Expected/Desired Behavior

See https://github.com/liquibase/liquibase/pull/2073

**Comment by molivasdat** [comment]
Hi @smainz Thanks for creating this issue.  We will add this and the PR to the list of issues we are processing.
