### ISSUE TITLE
loadUpdateData fails for HSQL

### ISSUE THREAD

**Issue by KushnirykOleh** [liquibase/liquibase#2077]
## Environment

**Liquibase Version**:
4.4.3
**Liquibase Integration & Version**: 
Maven

**Database Vendor & Version**:
HSQL 2.4.0
**Operating System Type & Version**:
Windows 10

## Description

LoadUpdateData changeType doesn't work correctly for HSQL, query is generated wrong and fails during `update` phase

## Steps To Reproduce
- run HSQLDB, connect and run DB init script from [test-harness](https://github.com/liquibase/liquibase-test-harness/blob/DAT-6831/src/test/resources/docker/hsqldb-init.sql) to have table with data
- create XML changeSet` loadUpdateData.xml `and `loadUpdateData.csv` data file similar to these
```
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
         http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.3.xsd">
    <changeSet id="1" author="as">
        <loadUpdateData file="loadUpdateData.csv"
                        relativeToChangelogFile="true"
                        quotchar="'"
                        separator=";"
                        tableName="authors"
                        primaryKey="id">
        </loadUpdateData>
        <rollback>
            <sql splitStatements="true">
                DELETE FROM authors WHERE id = 1;
                INSERT INTO authors VALUES ('1','Eileen','Lubowitz','ppaucek@example.org','1991-03-04','2004-05-30 02:08:25');
                DELETE FROM authors WHERE id = 7;
                DELETE FROM authors WHERE id = 8;
            </sql>
        </rollback>
    </changeSet>
</databaseChangeLog>
```

```
id;first_name;last_name;email;birthdate;added
1;Adam;Gods;test1@example.com;1000-02-27;2000-02-04T02:32:00
7;Noah;Lamekhs;test2@example.com;2000-02-27;1994-12-10T01:00:00
8;Muhammad;Ibn Abdullah;test3@example.com;3000-02-27;2000-12-10T01:00:00
```
- run Liquibase `updateSQL`, observe query `MERGE INTO authors USING (VALUES (1)) ON id = 1 
    WHEN NOT MATCHED THEN INSERT (id,first_name,last_name,email,birthdate,added) VALUES (1,'Adam','Gods','test1@example.com','1000-02-27','2000-02-04 02:32:00.000') 
WHEN MATCHED THEN UPDATE authors SET id = 1,first_name = 'Adam',last_name = 'Gods',email = 'test1@example.com',birthdate = '1000-02-27',added = '2000-02-04 02:32:00.000' WHERE id = 1;`

## Actual Behavior
Query is not working, trying to run `update` command exception like this is thrown
```
liquibase.exception.MigrationFailedException: Migration failed for change set liquibase/harness/data/changelogs/hsqldb/loadUpdateData.xml::1::as:
     Reason: liquibase.exception.DatabaseException: unexpected token: AUTHORS required: SET [Failed SQL: (-5581) MERGE INTO authors USING (VALUES (1)) ON id = 1 WHEN NOT MATCHED THEN INSERT (id,first_name,last_name,email,birthdate,added) VALUES (1,'Adam','Gods','test1@example.com','1000-02-27','2000-02-04 02:32:00.000') WHEN MATCHED THEN UPDATE authors SET id = 1,first_name = 'Adam',last_name = 'Gods',email = 'test1@example.com',birthdate = '1000-02-27',added = '2000-02-04 02:32:00.000' WHERE id = 1]
```

## Expected/Desired Behavior
Query should be like `MERGE INTO AUTHORS USING (VALUES (1)) ON id = 1
    WHEN NOT MATCHED THEN INSERT (id,first_name,last_name,email,birthdate,added) VALUES (1,'Adam','Gods','test1@example.com','1000-02-27','2000-02-04 02:32:00.000')
WHEN MATCHED THEN UPDATE SET id = 1,first_name = 'Adam',last_name = 'Gods', email = 'test1@example.com',birthdate = '1000-02-27', added = '2000-02-04 02:32:00.000';
` to work with HSQLDB

## Additional Context
found with test-harness

**Comment by FBurguer** [comment]
Looks like it got fixed for liquibase `4.16.1`. Let us know if it conitnues to happen to you. Thanks!
