### ISSUE TITLE
databasechangelog* table creation not thread/multiprocess safe

### ISSUE THREAD

**Issue by jamey-clari** [liquibase/liquibase#2083]
## Environment
**Liquibase Version**: 3.5.4 through 4.3.x

**Liquibase Integration & Version**: Direct calling of Java APIs

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: Postgres 10.14 (AWS Aurora)

**Operating System Type & Version**: Ubuntu / various

## Description
We, like many applications, have multiple hosts running services connecting to the same databases.  When a new customer or service is established we may see effectively concurrent requests to our cluster of application servers trigger the creation of a new DB for this service.  This creation operation may be triggered concurrently on multiple servers and our code for DB creation and initialization is idempotent and/or thread safe...except for Liquibase which we use to install an initial schema.  Once issues 1768 & 2018 are corrected most of the problems we have with the 4.x library will be resolved but there remains an issue with the creation of the databasechangelog* tables.  The creation of these is not idempotent or thread safe and can result in two processes or threads attempting to trigger Liquibase on the same, formerly uninitialized database concurrently and experiencing errors like "table already exists" when Liquibase tries to create databasechangelog.  Once these tables exist Liquibase does a good job of serializing application of change sets using DB-driven locking but prior to the table(s) existing there is no protection from concurrent operations.

One approach here might be to update the Liquibase code to be idempotent.  Perhaps it could create the simpler (and less likely to change) `databasechangeloglock` table first using a `CREATE TABLE IF NOT EXISTS` statement (not sure how universal across DB vendors this is) and then lock on this as normal before proceeding to create or update the `databasechangelog` table.

Another approach would be to employ some other form of DB locking during Liquibase schema creation to avoid concurrent operations.  Postgres provides advisory locks which I'm using as a work around for this problem currently but these are not a feature of all DBs or even particularly standard.

## Steps To Reproduce
List the steps to reproduce the behavior.

1) Start with an empty DB
2) Have multiple concurrent threads and/or processes attempt to execute Liquibase API commands which may side-effect create the databasechangelog* tables.
3) Observe errors like table creation failures due to tables already existing.

## Actual Behavior
Caused by: liquibase.exception.DatabaseException: ERROR: relation "databasechangelog" already exists [Failed SQL: CREATE TABLE public.databasechangelog (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED TIMESTAMP WITHOUT TIME ZONE NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10))]
at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:309)
at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:113)
at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:103)
at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:240)
at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1124)
at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1186)
at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1176)
... 74 more
Caused by: org.postgresql.util.PSQLException: ERROR: relation "databasechangelog" already exists
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:307)
... 85 more

## Expected/Desired Behavior
If Liquibase schema creation can be made idempotent then no such errors should arise and all threads/processes should then get serialized via the normal `databasechangeloglock` mechanism following schema creation.

## Implementation Details
There are multiple possible solutions to this problem, with varying degrees of difficulty and time investment. There are likely other additional solutions to this problem in addition to the ones below.

* Retry logic - attempt to create the databasechangelog table multiple times with a wait between each attempt, and only “fail” once all of the retries have been exhausted. This is a relatively primitive solution.
* Attempt to gain a lock on the entire database - some database providers might allow obtaining a lock on the entire database (perhaps single user mode). This is a somewhat less primitive solution, but does require exclusive access to the database which almost certainly cannot be guaranteed on production applications.
* Only create table if it does not exist - this is perhaps the best solution, but will require the largest dev and test time investment, since each platform has its syntax for these types of statements. Some platforms do not support the IF EXISTS logic at all (SQL Server, for example).

## Test Requirements (Internal Liquibase QA)
The bug is a race condition when multiple Liquibase updates are running at the same time. 

* The bug triggers when the DATABASECHANGELOGLOCK table is being created.
* When two or more update operations attempt to create the DATABASECHANGELOGLOCK table at the same time, one or more update operations fails because the DATABASECHANGELOGLOCK table already exists. 

The fix allows update operations to continue if the DATABASECHANGELOGLOCK table already exists.

The scripts attached to reproduce this bug are Windows-specific files; batch script (.cmd) and powershell (ps1). _If you are not on Windows, please do not take this ticket;_  duplicating effort to rewrite scripts in bash just isn’t where we want to spend our test time. The powershell script runs 3 concurrent Liquibase operations. I have found 3 concurrent Liquibase operations is sufficient to get into the race condition. However, to increase the number of concurrent Liquibase operations, change the `$list = 1..3` to `$list = 1..n`, where n is the new maximum concurrent operations. The powershell script calls a batch script that does the job of setting up and running Liquibase update. 

When the powershell script runs, you will see three CLI prompts show up. 

Logging is enabled in the batch script. The execution will output three log files: lb1555-log.txt, lb1555-log.txt1, lb1555-log.txt2. I’ll attach an example of the log produced when the race condition is encountered. You’ll notice that Liquibase exits/fails in older builds, and does not exit/fail when using the fix build.

To test this fix, you will need:

* Windows OS 
* SQL Server 17
* The attached changelog, properties file and scripts
  * **You will need to update the paths and database connection properties for your environment.**

**Manual Tests**

_Prior to starting the test, ensure your database instance does not have the DATABASECHANGELOGLOCK in the catalog or schema you’re connecting to; do this by running_ `liquibase drop-all`. 

_Verify Liquibase update does not exit when DATABASECHANGELOGLOCK exists._

* In Powershell ISE or Powershell CLI,  run `.\parallell-foreach.ps1`
* The update should continue when the DATABASECHANGELOGLOCK table already exists.
* Execute test against the following platforms:
  * SQL Server
  * Oracle
  * Postgres
  * MariaDB
  * MySQL

**Automated Tests**

* None required for this ticket; it is a multi-threaded issue and not suitable for our functional test framework.

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-2131) by [Unito](https://www.unito.io)

**Comment by molivasdat** [comment]
Hi @jamey-clari Thanks for creating this issue.  We will add it to the list of issues that we are processing.  This will most likely require a little more thought than just a bug fix/enhancement.

**Comment by StevenMassaro** [comment]
This can be reproduced with a shell script that calls the liquibase command line multiple times concurrently, when run against a database that does not already contain the databasechangelog table:

```
liquibase update --changelogfile sql.sql &
liquibase update --changelogfile sql.sql &
liquibase update --changelogfile sql.sql &
wait
```

**Comment by jmatterngbg** [comment]
Still and issue with 4.30
