### ISSUE TITLE
<loadData> cannot load columns of type "time" into PostgreSQL

### ISSUE THREAD

**Issue by Marcel2603** [liquibase/liquibase#2088]
## Environment

**Liquibase Version**: 4.4.3

**Liquibase Integration & Version**: maven with spring-boot

**Liquibase Extension(s) & Version**:  -

**Database Vendor & Version**: postgres:13.3

**Operating System Type & Version**: -

## Description

After upgrading to 4.4.3, liquibase dont load data from CSV-files, where a  `time` column exists. If throws following exception: 
```
column "start_time" is of type time without time zone but expression is of type date
  Hinweis: You will need to rewrite or cast the expression
```

There was everything fine with version 4.4.2

## Steps To Reproduce

Changeset:
 ``` XML
<changeSet id="20210913_job" author="Marcel">
        <createTable tableName="job">
            <column name="id" type="bigint" autoIncrement="true">
                <constraints primaryKey="true" primaryKeyName="job_id_pk"/>
            </column>
            <column name="start_time" type="time"/>
        </createTable>
    </changeSet>
``` 

CSV-file:
```CSV
start_time
"CURRENT_TIME"
```

## Actual Behavior
See Steps to Reproduce. As the application starts, liquibase create the table but fails to load the data. 

## Expected/Desired Behavior
Current-Time can be loaded via loadData

## Additional Context
Maybe it has something todo with #2068

**Comment by molivasdat** [comment]
Hi @Marcel2603 Yes, thanks for writing up this issue.  We will add it to the list of issues that we are processing and also see if it is related to #2068
