### ISSUE TITLE
NetUtils.getLocalHostName() takes 30s 

### ISSUE THREAD

**Issue by dominik42** [liquibase/liquibase#2098]
## Environment

**Liquibase Version**: 4.3.5

**Liquibase Integration & Version**: maven

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

**Operating System Type & Version**: MacOS 11.5.2 Big Sur

## Description

During liquibase startup, the call `database.getDefaultSchemaName();` in `liquibase.changelog.ChangeLogParameters.java:61` leads to resolving the current hostname by `liquibase.util.NetUtil.getLocalHostName` in `NetUtil.java:71`. The subsequent line 75 takes 30s to resolve the hostname for the IP given by line 73. Interestingly, line 73 doesn't return 127.0.0.1 (from network interface eth0) but another IP taken from another network interface (eth1 / company internal network IP, here '/192.168.254.80' - yes starting with the slash. This IP can't resolved as fast as normally done by java vm.

`liquibase.util.NetUtil.getLocalHostName()`
```java
InetAddress localhost = getLocalHost(); // => '/192.168.254.80' ... yes with the leading slash
if (localhost != null) {
    return localhost.getHostName(); // needs 30s
}
```

## Expected/Desired Behavior
Same as normal JVM resolution, tested by the follwing:
```java
    @Test
    void testResolveLocalhost() throws UnknownHostException {
        InetAddress ia = InetAddress.getLocalHost();
        String hostname = ia.getHostName(); // 6ms
    }

    @Test
    void testResolveLiquibase() throws UnknownHostException, SocketException {
        String ia = NetUtil.getLocalHostAddress(); //30s
    }
```

## Additional Context
There are solution on Stackoverflow for the general host resolving problem in JVM. ( https://stackoverflow.com/questions/39636792/jvm-takes-a-long-time-to-resolve-ip-address-for-localhost/39698914#39698914 ) But the solutiuons given there didn't work.

**Comment by molivasdat** [comment]
Thanks for the suggestion @dominik42 We will add this to the list of issues that we are processing.

**Comment by eEQK** [comment]
In my case resolving was taking a lot of time because I had ZeroTier One running (p2p virtual network, works like Hamachi)

Simply disconnect from the virtual network and it should work quickly again
