### ISSUE TITLE
Can't modify logging level in liquibase-maven-plugin

### ISSUE THREAD

**Issue by giacgbj** [liquibase/liquibase#2113]
## Environment

**Liquibase Version**: 4.4.3

**Liquibase Integration & Version**:  Maven

## Description

Can't change logging level using liquibase-maven-plugin.

How "logging" property is supposed to work when this [line](https://github.com/liquibase/liquibase/blob/f10ba7497160521cb8e2659edf39becd6201d598/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java#L410) is commented out?

## Steps To Reproduce

Set the plugin like this:
```
<plugin>     
   <groupId>org.liquibase</groupId>     
   <artifactId>liquibase-maven-plugin</artifactId>    
   <configuration>         
     <logging>WARNING</logging> 
   </configuration>
...
</plugin>
```

Run whatever command you want and you'll still see "[INFO] ..." logs. 

## Actual Behavior

Can't change log level.

## Expected/Desired Behavior

Log level changeable using the aforementioned property.

**Comment by molivasdat** [comment]
Hi @giacgbj Thanks for bringing this issue to our attention.  We will add this to the list of issues that we are processing.

**Comment by nvoxland** [comment]
With 4.0 we switch the maven plugin to respect the standard maven logging logic vs. something custom of our own. So you can use the -q, -X or -e flags or the setup in https://maven.apache.org/maven-logging.html

But, I created #2261 to better tell people that are using the logging configuration that it is now deprecated.
