### ISSUE TITLE
liquibase.properties not read from classpath

### ISSUE THREAD

**Issue by liefke** [liquibase/liquibase#2121]
## Environment

**Liquibase Version**: 4.5.0
**Liquibase Integration & Version**: CLI

## Description

If I include a `liquibase.properties` in the classpath, that file is not read when starting Liquibase from the command line.

## Steps To Reproduce

* Create a `liquibase.properties` file with the required configuration options, especially `changeLogFile` and `url`.
* Package that file into a liquibase-configuration.jar
* Call liquibase with that liquibase-configuration.jar on the classpath (e.g. put it in the lib folder)

## Actual Behavior
Liquibase is complaining about the missing required options.

## Expected/Desired Behavior
Liquibase runs with the provided configuration options.

**Comment by molivasdat** [comment]
Hi @liefke Thanks for creating this issue.  We will add this to the list of issues that we are processing.  And thanks for creating the PR.  Does the use path instead of absolutePath break other scenarios of using Liquibase that are not in the classpath?

**Comment by liefke** [comment]
No, this won't break anything, as I changed only `parseDefaultPropertyFileFromResource` - which, as I explained, didn't work anyway, while the working scenarios are using `parseDefaultPropertyFileFromFile`, which I didn't change.
