### ISSUE TITLE
Liquibase endDelimiter does not work after upgrading from 3.10.x to 4.x

### ISSUE THREAD

**Issue by mkobylarz** [liquibase/liquibase#2133]
## Environment

**Liquibase Version**: 4.3.5, 4.5.0

**Liquibase Integration & Version** spring boot 2.5.5

**Liquibase Extension(s) & Version**: none

**Database Vendor & Version**: oracle 19

This is a copy of closed and unsolved issue https://github.com/liquibase/liquibase/issues/1458

## Description

After bumping liquibase from 3.10.3 to 4.3.5 (together with springboot) old changeset with `endDelimiter` property set to `/` is no longer working as it did before.

## Steps To Reproduce

Consider this changeset:

```
-- changeset abcd:1 runOnChange:true endDelimiter:/
CREATE OR REPLACE PROCEDURE any_procedure_name is
BEGIN
    DBMS_MVIEW.REFRESH('LEAD_INST_FOS_MV', method => '?', atomic_refresh => FALSE, out_of_place => true);
END reany_procedure_name;
/

grant execute on any_procedure_name to ANY_USER1/
grant execute on any_procedure_name to ANY_USER2/
grant execute on any_procedure_name to ANY_USER3/
-- rollback drop PROCEDURE refresh_all_fos_permission_views/
```

## Actual Behavior
With liquibase 3.10.3 this works with flawlessly.

With liquibase 4.3.5 we get

```
Reason: liquibase.exception.DatabaseException: ORA-00933: SQL command not properly ended
 [Failed SQL: (933) grant execute on any_procedure_name to ANY_USER1/
grant execute on any_procedure_name to ANY_USER2/
grant execute on any_procedure_name to ANY_USER3]
```
As one can see liquibase no longer splits  `grant execute` statements by `endDelimiter`   and  flushes it as one big query which upsets the database.

## Expected/Desired Behavior
This changeset should simply pass on both versions.

## Additional Context

As stated in https://github.com/liquibase/liquibase/issues/1458 changes were made to method `isDelimiter` (`liquibase.util.StringUtil`) which broke compatibility. 
3.10.1
```
if (endDelimiter.length() == 1) { return piece.toLowerCase().equalsIgnoreCase(endDelimiter.toLowerCase()); }
```

4.1.0
```
if (endDelimiter.length() == 1) { if ("/".equals(endDelimiter)) { if (previousPiece != null && !previousPiece.endsWith("\n")) { return false; } } return piece.toLowerCase().equalsIgnoreCase(endDelimiter.toLowerCase()); }
```

If you have some long running databases where this changeset has already been run (so you don't want to make any changes to this changeset) and new environments (which are now unable to setup without changing this changset) this makes you stuck.

**Comment by Saucistophe** [comment]
I've reproduced the problem in a unit test; I'm checking out the problem.

**Comment by Saucistophe** [comment]
Looks like it was introduced due to #854!

**Comment by molivasdat** [comment]
Hi @mkobylarz Thanks for creating this issue.  We will add to the list of issues that we are processing.  Hi @Saucistophe thanks for providing a fix for the issue.

**Comment by XDelphiGrl** [comment]
This PR addresses two issues. The first issue is that `endDelimiter` was not being respected during liquibase `update`. The second issue is to ensure the fix for `endDelimiter` does not break handling of trailing comments in SQL statements; i.e. `/*comment*/`.

---
* Verify changesets with endDelimiter deploy without error.
  * formatted SQL changelog **PASS**
  * JSON changelog **PASS**
  * YAML changelog **PASS**
  * XML changelog **Mostly PASS**
    * The createProcedure changetype does not support the endDelimiter property. However, Liquibase still tries to split statements based on an end delimiter and does not do it correctly (truncates the last statement in the SQL). If you use an XML changelog, I suggest using either the sql or sqlFile changetypes to explicitly set an end delimeter and split statement properties.

* Verify with a trailing comment deploy without error.
  * formatted SQL changelog **PASS**
  * JSON changelog **PASS**
  * YAML changelog **PASS**
  * XML changelog **PASS**

---
#### Test Files
**Formatted SQL**
```
--liquibase formatted sql

-- changeset pr2135:endDelim runOnChange:true endDelimiter:/
CREATE OR REPLACE PROCEDURE proschema.pr2135_proc is
BEGIN
    SELECT * FROM DATABASECHANGELOGLOCK;
END pr2135_proc;
/

grant execute on pr2135_proc to CUKE_ADMIN/
grant execute on pr2135_proc to CUKE_ADMIN/
grant execute on pr2135_proc to CUKE_ADMIN/
-- rollback drop PROCEDURE pr2135_proc/

--changeset pr2135:trailingcomment stripComments:false

CREATE VIEW proschema.v_test AS

SELECT 1 x FROM dual /*test view*/
```
**JSON**
```
{ "databaseChangeLog": [
  {
    "changeSet": {
      "id": "1646318526286-1",
      "author": "erz (generated)",
      "changes": [
        {
          "createView": {
            "fullDefinition": true,
            "selectQuery": "CREATE OR REPLACE FORCE VIEW \"V_TEST\" (\"X\") AS SELECT 1 x FROM dual /*test view*/",
            "viewName": "V_TEST"
          }
        }]
      
    }
  },
  
  {
    "changeSet": {
      "id": "1646318526286-2",
      "author": "erz (generated)",
      "changes": [
        {
          "createProcedure": {
            "path": "objects/storedprocedure/PR2135_PROC.sql",
            "procedureName": "PR2135_PROC",
            "relativeToChangelogFile": true,
            "endDelimiter": "/"
          }
        }]
      
    }
  }
  
]}
```

**YML**

```
databaseChangeLog:
- changeSet:
    id: 1646318590509-1
    author: erz (generated)
    changes:
    - createView:
        fullDefinition: true
        selectQuery: CREATE OR REPLACE FORCE VIEW "V_TEST" ("X") AS SELECT 1 x FROM
          dual /*test view*/
        viewName: V_TEST
- changeSet:
    id: 1646318590509-2
    author: erz (generated)
    changes:
    - createProcedure:
        path: objects/storedprocedure/PR2135_PROC.sql
        procedureName: PR2135_PROC
        relativeToChangelogFile: true
        endDelimiter: /

```
**XML**
```
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:pro="http://www.liquibase.org/xml/ns/pro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-4.1.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.1.xsd">
    <changeSet author="erz (generated)" id="1646318372076-1">
        <createView fullDefinition="true" viewName="V_TEST">CREATE OR REPLACE FORCE VIEW "V_TEST" ("X") AS SELECT 1 x FROM dual /*test view*/</createView>
    </changeSet>
    <changeSet author="erz (generated)" id="1646318372076-2">
        <createProcedure path="objects/storedprocedure/PR2135_PROC.sql" procedureName="PR2135_PROC" relativeToChangelogFile="true"/>
    </changeSet>
</databaseChangeLog>
```

**SQL File PR2135_PROC.sql**
```
CREATE OR REPLACE PROCEDURE proschema.pr2135_proc is
BEGIN
    SELECT * FROM DATABASECHANGELOGLOCK;
END pr2135_proc;/

grant execute on pr2135_proc to CUKE_ADMIN/
grant execute on pr2135_proc to CUKE_ADMIN/
grant execute on pr2135_proc to CUKE_ADMIN/
```
---
**Test Environment**
Liquibase Core: handle_slash_delimiter_and_comments/957/b949f0, Pro: master/216/2fa6e0
Oracle 12.2.1
[Passing Functional Tests](https://github.com/liquibase/liquibase-pro-tests/actions/runs/1560504418)
* Note: The Oracle proxy tests did not run due to an environmental issue; I deem this acceptable due to the limited scope of those tests and their lack of relation to the current fix.
