### ISSUE TITLE
war files in classpath not read correctly

### ISSUE THREAD

**Issue by tukak** [liquibase/liquibase#2137]
## Environment

**Liquibase Version**: 4.4.3

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**:  none

**Database Vendor & Version**: oracle 19

**Operating System Type & Version**: Windows 10, Debian

## Description

When running liquibase 4.4.3 with war file in classpath, it  doesn't use files in WEB-INF/libs and WEB-INF/classes.
It was working in 4.3.5.

## Steps To Reproduce

Attached zip containts war file that contains ojdbc driver in WEB-INF/libs and changelog in WEB-INF/classes.
Extract zip.
[liquibase_test.zip](https://github.com/liquibase/liquibase/files/7279113/liquibase_test.zip)

```
liquibase --classpath=liquibase_test.war --changeLogFile=db/changelog/changelog-master.xml --driver=oracle.jdbc.OracleDriver --url=jdbc:oracle:thin:@localhost:1521:xe updateSql
```
or providing ojdbc
```
liquibase --classpath=liquibase_test.war;ojdbc8-12.2.0.1.jar --changeLogFile=db/changelog/changelog-master.xml --driver=oracle.jdbc.OracleDriver --url=jdbc:oracle:thin:@localhost:1521:xe updateSql
```
## Actual Behavior
Not using libs in WEB-INF/libs and changelog in WEB-INF/classes :
```
Liquibase Community 4.4.3 by Datical
Unexpected error running Liquibase: java.lang.RuntimeException: Cannot find database driver: oracle.jdbc.OracleDriver
```

When provided ojdbc:
```
Liquibase Community 4.4.3 by Datical
Unexpected error running Liquibase: The file db/changelog/changelog-master.xml was not found in
    - C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\access-bridge-64.jar
    - C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\cldrdata.jar
    - C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\dnsns.jar
    - C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\jaccess.jar
    - C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\localedata.jar
    - C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\nashorn.jar
    - C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\sunec.jar
    - C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\sunjce_provider.jar
    - C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\sunmscapi.jar
    - C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\sunpkcs11.jar
    - C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\zipfs.jar
    - C:\ProgramData\chocolatey\lib\liquibase\content\lib
    - C:\ProgramData\chocolatey\lib\liquibase\content\lib\commons-cli-1.4.jar
    - C:\ProgramData\chocolatey\lib\liquibase\content\lib\h2-1.4.200.jar
    - C:\ProgramData\chocolatey\lib\liquibase\content\lib\jaxb-api-2.3.0.jar
    - C:\ProgramData\chocolatey\lib\liquibase\content\lib\jaxb-core-2.3.0.jar
    - C:\ProgramData\chocolatey\lib\liquibase\content\lib\jaxb-impl-2.3.0.jar
    - C:\ProgramData\chocolatey\lib\liquibase\content\lib\picocli-4.6.1.jar
    - C:\ProgramData\chocolatey\lib\liquibase\content\lib\snakeyaml-1.27.jar
    - C:\ProgramData\chocolatey\lib\liquibase\content\liquibase.jar
    - C:\Users\username\Downloads
    - C:\Users\username\Downloads\.
    - C:\Users\username\Downloads\liquibase_test.war
    - C:\Users\username\Downloads\ojdbc8-12.2.0.1.jar
```
## Expected/Desired Behavior
Running the same commands works with 4.3.5

**Comment by molivasdat** [comment]
Hi @tukak Thanks for alerting us to this issue.  We will add it to the list of issues that we are processing.

**Comment by kataggart** [comment]
@tukak checking in to see if you have been able to try this out with a more recent version?

**Comment by tukak** [comment]
@kataggart Hi, sorry, I'm no longer at the job where I encountered it. I will try to test locally this week.

**Comment by kataggart** [comment]
Thanks! @tukak we super appreciate your help. Hope your new job is exciting (and you also get to use liquibase!)

**Comment by tukak** [comment]
@kataggart I've reproduced the bug with 4.4.3 (on mac this time) and the bug is gone in the latest version (4.15.0).
Thanks for fixing it.
And yes, my new job is very exciting and there is a fight among devs using liquibase and flyway - liquibase seems to be winning ;-)

**Comment by kataggart** [comment]
@tukak ooohhhh!!! Please let us know if you need anything from anyone over here to help with the fight. We are here for the engineers! :)
