### ISSUE TITLE
Slow initialization in Spring Boot

### ISSUE THREAD

**Issue by twh270** [liquibase/liquibase#2148]
## Environment

**Liquibase Version**: 4.4.3

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.> maven

**Liquibase Extension(s) & Version**: --

**Database Vendor & Version**: PostgreSQL 12

**Operating System Type & Version**: Windows 10

## Description
Liquibase takes longer to run as more libraries are added to the project (pom.xml).

## Steps To Reproduce
Create a project with a lot of dependencies. Add at least a few changelogs to liquibase.

## Actual Behavior
Each changelog takes multiple seconds to execute, regardless of whether it needs to be applied. (I.e., database operations are not the cause of the slowdown.)

## Expected/Desired Behavior
Non-database execution per changelog takes less than a second.

**Comment by nvoxland** [comment]
Thanks for the update. I'll close this ticket.

It's also a good reminder that we need to get the default liquibase version better up to date in spring boot, we are working on that too.
