### ISSUE TITLE
Liquibase is very slow against snowflake during startup

### ISSUE THREAD

**Issue by sadhnamanohar** [liquibase/liquibase#2160]
**Description:**
The reason seems to be that it is running the following query 8 times during startup, and so takes 3 minutes before the changes start to get applied:

show /* JDBC:DatabaseMetaData.getColumns() */ columns in database "DEV"

In my DEV db, this query returns around. 100000 rows.

**Environment:**
Liquibase version: 4.5.0
Driver: snowflake-jdbc-3.13.9.jar
Liquibase extension: liquibase-snowflake-4.5.0.jar
OS: MacOS

**Expected/Desired Behavior:**
I believe the query could be:
show /* JDBC:DatabaseMetaData.getColumns() */ columns in **_schema_** DEV.defaultSchemaName

Thanks

<img width="1149" alt="Screen Shot 2021-10-26 at 2 17 50 PM" src="https://user-images.githubusercontent.com/14222298/138937673-e6cf5fc2-359d-422c-8f09-84fc063f9309.png">

**Comment by molivasdat** [comment]
Hi @sadhnamanohar Thanks for letting us know about this issue.  This may belong on the [snowflake](https://github.com/liquibase/liquibase-snowflake/issues) repository.

**Comment by KushnirykOleh** [comment]
Hi @sadhnamanohar. Snowflake support has been moved from extension to liquibase-core, along with this bunch of issues were fixed, including performance issue where schema was ignored for getMetadata() calls.
Can you check with newest versions of Liquibase if issue still reproduces for you?
