### ISSUE TITLE
BIGSERIAL column type does not result in column having auto-generated value from sequence. Sequence is also not created.

### ISSUE THREAD

**Issue by swav** [liquibase/liquibase#2163]
## Environment
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

**Liquibase Version**:
This issue is present in liquibase-core:3.10.3 . Previous released version: 3.10.1 works correctly (see description)

**Database Vendor & Version**: Postesql:9.6.15

**Operating System Type & Version**:
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

## Description
Using liquibase-core:3.10.3 the following column definition does not create sequence and set correct column default value:

<changeSet author="xyz (generated)" id="1634673337019-2">
     <createTable tableName="resource_entry_event">
     <column name="id" type="UUID">
        <constraints nullable="false" primaryKey="true" primaryKeyName="resource_entry_event_pkey"/>
     </column>
     <column name="sequence_identifier" type="BIGSERIAL">
        <constraints nullable="false"/>
   </column>
</createTable>
</changeSet>
The resulting SQL Create script will be:
CREATE TABLE IF NOT EXISTS harvester.resource_entry_event
(
    id uuid NOT NULL,
    sequence_identifier bigint NOT NULL
)
Going back to prior version: 3.10.1 the above column definition will be created correctly. The SQL to create the table will be:
CREATE TABLE IF NOT EXISTS harvester.resource_entry_event
(
    id uuid NOT NULL,
    sequence_identifier bigint NOT NULL DEFAULT nextval('harvester.resource_entry_event_sequence_identifier_seq'::regclass)
)
...and sequence will be created.

It looks like this fix from 3.10.3 has no effect: https://github.com/liquibase/liquibase/pull/1010

**Comment by molivasdat** [comment]
Hi @swav Thanks for creating this issue.  Can you share the changeset that you are using that shows the issue?

**Comment by swav** [comment]
@molivasdat , I've attached the entire table definition changelog. I've used liquibase 3.10.3 and postgesql 9.6.15 . Thanks for looking into this :)

**Comment by FBurguer** [comment]
We dont expect to create a sequence, so this behavior its correct.
