### ISSUE TITLE
CreateIndex with index prefix length

### ISSUE THREAD

**Issue by adangel** [liquibase/liquibase#2191]
## Environment

**Liquibase Version**: any

**Liquibase Integration & Version**: any

**Liquibase Extension(s) & Version**: none

**Database Vendor & Version**: MySQL 5.7 and later

**Operating System Type & Version**: any

## Description

MySQL createIndex statement supports to specify an index prefix length, e.g.

```
ALTER TABLE some_table ADD INDEX some_table_index (column1 (300),column2);
```

This is documented here: https://dev.mysql.com/doc/refman/8.0/en/create-index.html#create-index-column-prefixes
and https://dev.mysql.com/doc/refman/5.7/en/create-index.html#create-index-column-prefixes

Currently there is no way in liquibase to specify this with the `createIndex` change (https://docs.liquibase.com/change-types/community/create-index.html).

## Steps To Reproduce

There are two possible ways to specify the index prefix length while adding an index:

a)

```xml
<createIndex tableName="some_table" indexName="some_table_index">
        <column name="column1(300)"/>
        <column name="column2"/>
</createIndex>
```

b)

```xml
<createIndex tableName="some_table" indexName="some_table_index">
        <column name="column1" type="varchar(300)"/>
        <column name="column2"/>
</createIndex>
```

## Actual Behavior

a) The index prefix length leads to "unknown column" error.
b) The index prefix length of "300" is ignored

## Expected/Desired Behavior

Either a) or b) should be supported for MySQL.

## Additional Context
There exists a workaround by using `modifySql` to change the SQL statement from `... ADD INDEX some_table_index (column1,column2);` to `... ADD INDEX some_table_index (column1 (300),column2);`, but it would be better to support this directly by liquibase.

Note: This feature request was first reported as https://github.com/liquibase/liquibase-percona/issues/148

**Comment by adangel** [comment]
Ok, it turns out that variant a) is working.

Could you confirm, that this solution is correct? I want to avoid that this feature is just accidentally working...
It seems, that the documentation maybe should be updated for createIndex to mention this case as well.
From the code, it currently works, because the parenthesis are detected and then the whole column name is not escaped:

https://github.com/liquibase/liquibase/blob/3b0834b4bf4bc8e23a033991aa22211cfa9511ff/liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateIndexGenerator.java#L126

This calls the deprecated `database.escapeColumnName` method with the last parameter set to `false`.
If "computed" is set to false explicitly (`<column name="column1(300)" computed="false"/>`), I guess, it won't work.

**Comment by molivasdat** [comment]
@adangel So it sounds like this is actually working?

**Comment by adangel** [comment]
It works, yes, but I'm afraid, it only works by accident: In the above mention code snippet, the deprecated method `database.escapeColumnName` is used - if replaced with the non-deprecated variant, then it will stop working. The deprecated method tries to determine automagically whether the column name is a column name or a function name. It does this by looking for parenthesis - which in this case is indeed contained in the "column name" parameter. But it's really *not* a function call we have here, it is a column name with a explicitly specified prefix length.
Furthermore, this usage in createIndex is not documented. Looking at the documentation at https://docs.liquibase.com/change-types/community/create-index.html I actually would expect an additional attribute like "prefixLength" - then you can also easily document for which dbms it works. I only know about MySQL...

**Comment by molivasdat** [comment]
Thanks @adangel for the feedback.  We will add this to the list of issues to process.

**Comment by nvoxland** [comment]
@adangel it is "accidentally" working. Semantically, the "name" attribute should be the name of the column and since we just pass that along into the SQL we create having the parentheses in there happens to work now. But future features and fixes may change the implementation enough that it will not break.

The built-in change functions like createIndex aren't trying to be a SQL replacement, but a cross-database abstraction that covers the common features. Specifying the prefix length is getting into uncommon enough functionality that it isn't something we can add to createIndex.

For cases like this, modifySql is there to provide that easy "customize and extend" support like you mention. Or you can always just fall back to <sql> and specify the SQL you want yourself.
