### ISSUE TITLE
[MySQL]Mysql JSON Type is failed with syntax error

### ISSUE THREAD

**Issue by Venus-WXP** [liquibase/liquibase#2208]
## Environment

**Liquibase Version**: 4.6.1

**Liquibase Integration & Version**: 4.6.1

**Liquibase Extension(s) & Version**: 4.6.1

**Database Vendor & Version**: MySQL8.0.27

**Operating System Type & Version**: MacOS Monterey 12.0.1

## Description

When I use liquibase diff 2 mysql 8.x database to generate changelog.mysql.sql with mysql connector 8.0.27 version. The JSON type is mapped to JSON(1073741824). When I try to apply this changelog.mysql.sql to mysql and got syntax error since JSON(1073741824) is not valid syntax.

## Steps To Reproduce

Execute below command:
```shell
./liquibase diffChangeLog \
--url="jdbc:mysql://ip:3306/exchange" \
--username=root \
--password=root \
--referenceUrl="jdbc:mysql://ip2:3306/exchange" \
--referenceUsername=root \
--referencePassword=root \
--driver="com.mysql.cj.jdbc.Driver" \
--changelog-file="changelog.mysql.sql"
```

sql generated from generateChangeLog produces this sql fragment for the JSON field

```sql
CREATE TABLE rbt_message (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, type VARCHAR(64) NOT NULL, content JSON(1073741824) NOT NULL, created_datetime timestamp DEFAULT NOW() NULL, CONSTRAINT PK_RBT_MESSAGE PRIMARY KEY (id));
```

## Actual Behavior
When the above SQL statement is executed, the MySQL server will report a syntax error
If you manually edit to the below it works

```sql
CREATE TABLE rbt_message (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, type VARCHAR(64) NOT NULL, content JSON NOT NULL, created_datetime timestamp DEFAULT NOW() NULL, CONSTRAINT PK_RBT_MESSAGE PRIMARY KEY (id));
```

## Expected/Desired Behavior
The liquibase can produce correct sql like below:
```sql
CREATE TABLE rbt_message (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, type VARCHAR(64) NOT NULL, content JSON NOT NULL, created_datetime timestamp DEFAULT NOW() NULL, CONSTRAINT PK_RBT_MESSAGE PRIMARY KEY (id));
```

**Comment by molivasdat** [comment]
Hi @Venus-WXP Thanks for creating this issue.  Do you have an example table that is in the database that shows the error?
We will add this to the list of issues to process.

**Comment by Venus-WXP** [comment]
> ```sql
> CREATE 
> ```

There is a table structure in our prod env can be used:
```mysql
create table exchange.rbt_message
(
    id               bigint unsigned auto_increment comment 'primary key'
        primary key,
    type             varchar(64)                         not null comment 'message type',
    content          json                                not null comment 'message content',
    created_datetime timestamp default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP
);
```

**Comment by molivasdat** [comment]
Hi @Venus-WXP Thanks for the table!

**Comment by ekkizogloy** [comment]
I also ran into this issue when running `liquibase generate-changelog` then `liquibase update` on a new target. 
The `generate-changelog` command generates an output that includes the size for the JSON type. This apparently is invalid SQL and our changelog is in SQL format. When we run the update on a new server, the JSON(###) statement fails. I then manually remove the "(####)" and the statements succeed. 

This is with MySQL server 5.7 and 8.0. 

To recreate this issue: 
run the `generate-changelog` command into a SQL formatted changelog. 
Then run the changelog on a new database using the `update` command. 

```
mysql> CREATE TABLE t1 (jdoc JSON);
Query OK, 0 rows affected (0.02 sec)
```

That worked however including a size after does not work.
```
mysql> CREATE TABLE t2 (jdoc JSON(10000));
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(10000))' at line 1
mysql>
```

**Comment by FBurguer** [comment]
Still an issue on liquibase `4.15`.

**Comment by nwcm** [comment]
I have a PR which seems to fix this 

https://github.com/liquibase/liquibase/pull/3849
