### ISSUE TITLE
normalizePath super slow?

### ISSUE THREAD

**Issue by maurociancio** [liquibase/liquibase#2221]
## Environment

**Liquibase Version**: 4.3.5
**Liquibase Integration & Version**: spring boot
**Database Vendor & Version**: mysql
**Operating System Type & Version**: linux

## Description

Super slow run after liquibase upgrade. It takes 5~10 minutes to run. In previous versiones it took < 30 seconds.

## Steps To Reproduce

I have a change set xml file with more than 500 xml includes, like this:

`<include file="another.xml" relativeToChangelogFile="true" />`

## Actual Behavior
Takes a lot of time to run command

## Expected/Desired Behavior
Similar run time than previous versions

## Screenshots (if appropriate)
I've run with profiler, and got this:

![screenshot2021-11-17T11:51:46-03:00](https://user-images.githubusercontent.com/155789/142223506-b893fb71-e71c-4450-97f1-9307dd07a725.png)

liquibase.changelog.DatabaseChangeLog#normalizePath
this method takes a lot of time.
i suspect that precompiling the regexp will help.

## Additional Context
if it looks good, i can provide a patch.

**Comment by molivasdat** [comment]
Hi @maurociancio Thanks for writing up this issue. Which version did you upgrade from to get to 4.3.5?
If you would like to provide a patch that helps in your situation, we would appreciate the change.
For now we will add it to the list of issues that we process.

**Comment by maurociancio** [comment]
I'm upgrading from an old version: 2.0.5.
I found a workaround: i deleted all the changesets and generated a new one, haha
