### ISSUE TITLE
insert dynamic value

### ISSUE THREAD

**Issue by ChristianSuperman** [liquibase/liquibase#2266]
## Environment

**Liquibase Version**: 3.6.3

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

description：
I was trying to insert some data into two tables when we upgrade our system, the first table is **_main_table, the second table is **_sub_table
there is a column in the second table named ***_id which is related to the first table called id
so I try to insert data into these two tables , when I operate second table, I don't know how to valued the column ***_id in the second table because this id column is PRIMARY KEY  in the first table , it is AUTO_INCREMENT.
I can use subquery if I write sql， but we need to adapte some databases together, so we had to use label to init data like below:
<insert dbms="all" tableName="**_sub_table">
<column name="***_id" value="I don't know how to express it"/>https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
***
***
 </insert>

**Comment by kataggart** [comment]
Thanks for submitting your issue @ChristianSuperman. Since what you are noting seems to be more of a question for support/how to, I recommend you post your question over in the [Liquibase Forum ](https://forum.liquibase.org/)-- there are a lot of super users over there who can help out. Thanks!
