### ISSUE TITLE
Does it support the application scenario of sub-database and sub-table?

### ISSUE THREAD

**Issue by alexpassionate** [liquibase/liquibase#2294]
## Environment

**Liquibase Version**: Liquibase Community 4.6.2

**Database Vendor & Version**: MySQL 8.0  and   apache shardingsphere  4.1.1

## Feature Request

Does it support the application scenario of sub-database and sub-table?

Please Help answer this question, Thanks!

**Comment by alexpassionate** [comment]
when I see the official document does not explain ，Does it support integrated  apache shardingsphere ?

**Comment by kataggart** [comment]
@alexpassionate Can you provide a bit more detail regarding your use case and how you are looking to use apache shardingspehere to resolve? Thanks!

Also, there is a related discussion happening in the [forum](https://forum.liquibase.org/t/have-liquibase-issue-sql-statements-without-prefixed-schema/5834) right now that you might want to contribute to.

**Comment by kataggart** [comment]
Closing issue due to non-response. Please submit a new one if you continue to need assistance. Thanks!
