### ISSUE TITLE
DATABASECHANGELOGLOCK created multiple times in updateSQL mode

### ISSUE THREAD

**Issue by zederisch** [liquibase/liquibase#2295]
**Environment**
Liquibase Version: 4.6.2
Database Vendor & Version: Microsoft SQL Server 15.0.2080
Operating System Type & Version: Windows 10 Enterprise 21H1

**Description**
When running hte Liquibase configuration against a clean database in updateSQL to create a full database model deployment script, the "CREATE TABLE DATABASECHANGELOGLOCK" is generated in total 20 times. This only happens since 4.6.2, with 4.6.1 everything was fine regarding this issue.

**Steps to reproduce**
**_Liquibase configuration:_**
databaseChangeLog:
- changeSet:  
    id: createTable-1  
    author: test
    changes:  
    - createTable:
        tableName: table1
        columns:
        - column:
            name: test  
            type: int

**_Batch file used for compiling:_**
@ECHO OFF

CALL runLiquibase.bat ^
  --defaultsFile=./test_sqlserver.properties ^
  --changeLogFile=./test.yml ^
  --outputFile=./test.sql ^
  --logLevel=ERROR ^
  updateSQL

PAUSE

**_Properties file structure:_**
url: jdbc:sqlserver://localhost:1433;databaseName=<DB NAME>
username: <DB USERNAME>
password: <DB PASSWORD>
driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
classpath: <DB DRIVER BASE PATH>/mssql-jdbc-9.4.0.jre8.jar
outputDefaultCatalog: false
liquibase.hub.mode=off

**_Result:_**
-- Create Database Lock Table
CREATE TABLE DATABASECHANGELOGLOCK (ID int NOT NULL, LOCKED bit NOT NULL, LOCKGRANTED datetime2(3), LOCKEDBY nvarchar(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID))
GO

-- Initialize Database Lock Table
DELETE FROM DATABASECHANGELOGLOCK
GO

INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, 0)
GO

-- Create Database Lock Table
CREATE TABLE DATABASECHANGELOGLOCK (ID int NOT NULL, LOCKED bit NOT NULL, LOCKGRANTED datetime2(3), LOCKEDBY nvarchar(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID))
GO

-- Initialize Database Lock Table
DELETE FROM DATABASECHANGELOGLOCK
GO

INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, 0)
GO

[...]

You can find the used test setup here:
[test.zip](https://github.com/liquibase/liquibase/files/7768441/test.zip)

**Comment by Axinet** [comment]
Yes, I also fall in this issue. 
This bad behavior has been introduced with https://github.com/liquibase/liquibase/pull/2198 
which was planned to fix https://github.com/liquibase/liquibase/issues/2083 

I found the issue while using `liquibase.Liquibase#update(liquibase.Contexts, liquibase.LabelExpression, java.io.Writer, boolean)` (update method with output send to provided writer).

Issue suggested creating table if not exist, but current codebase just tries to create table 10 times (from two different places, which results in total of 20 create statements), which results in errors when executing such script on the real database.

**Comment by kataggart** [comment]
Thanks @zederisch and @Axinet for the details you provided here.  We will review this and move forward towards resolution. Especially appreciate the inclusion of the test set up details as well as the links to the related previous issues/PRs.

Hope to see both of you over at [https://forum.liquibase.org/](url) -- I am sure some newer community members could benefit from your expertise.

**Comment by nvoxland** [comment]
This should be fixed in #2335
