### ISSUE TITLE
CLI snapshot command does not accept 'schemas' attribute

### ISSUE THREAD

**Issue by nvoxland** [liquibase/liquibase#2297]
## Environment

**Liquibase Version**: 4.6.2

**Liquibase Integration & Version**: CLI

## Description

Running `liquibase snapshot --schemas=dbo,hr,app` generates an "unexpected argument", and `liquibase snapshot --help` does not include schemas in the command list.

The argument existed prior to the CLI refactoring work

**Comment by FBurguer** [comment]
Looks like this issue doesnt happen on version 4.11
Test Environment:
OS: WIndows 10
Java 11
MsSQL 2022
