### ISSUE TITLE
sql syntax error 'grant view database performance state to role_xx'

### ISSUE THREAD

**Issue by Freia3** [liquibase/liquibase#2328]
## Environment

**Liquibase Version**:
Liquibase version 4.3.2 and 4.5.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
maven

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
MSSQL 2019 and Azure SQL Database

**Operating System Type & Version**:
Used Docker running on Linux virtual machine

## Description
When running liquibase update, I'm getting a syntax error when running `GRANT VIEW DATABASE PERFORMANCE STATE to xx` (GRANT VIEW DATABASE STATE to xx works fine). This sql command works fine when we test it on a database with a user account.

## Steps To Reproduce
```xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" 
  xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:pro="http://www.liquibase.org/xml/ns/pro" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext 
  http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro 
  http://www.liquibase.org/xml/ns/pro/liquibase-pro-3.9.xsd http://www.liquibase.org/xml/ns/dbchangelog 
  http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.9.xsd">
    <preConditions>
        <dbms type="mssql" />
    </preConditions>
    <changeSet id="idname" author="xx.xx@xx.com">
        <sql dbms="mssql" endDelimiter=";">
             GRANT VIEW DATABASE state to xx;
             GRANT VIEW DATABASE PERFORMANCE state to xx;
        </sql>
    </changeSet>
</databaseChangeLog>
```

## Actual Behavior
[ERROR] Error setting up or running Liquibase:
[ERROR] liquibase.exception.MigrationFailedException: Migration failed for change set ./v60/diff.changelog.xml::idname::xx.xx@xx.com:
[ERROR]      Reason: liquibase.exception.DatabaseException: Incorrect syntax near 'VIEW'. [Failed SQL: (102) GRANT VIEW DATABASE PERFORMANCE state to xx]

**Comment by kataggart** [comment]
Thanks @Freia3 for submitting this. We we will review and get back to you!

**Comment by Freia3** [comment]
Discovered issue is related to sql server container, not to liquibase.
