### ISSUE TITLE
liquibase.exception.UnexpectedLiquibaseException: java.lang.ClassCastException: liquibase.database.DatabaseFactory cannot be cast to liquibase.SingletonObject

### ISSUE THREAD

**Issue by oleksii-syromolotov** [liquibase/liquibase#2349]
## Environment

Gradle 5.6.4
Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          1.8.0_242 (Amazon.com Inc. 25.242-b08)
OS:           Windows 10 10.0 amd64

**Liquibase Version**:
org.liquibase:liquibase-core:4.6.2

**Liquibase Integration & Version**: 
org.liquibase:liquibase-gradle-plugin:2.1.0

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
PostgreSQL 12
**Operating System Type & Version**:
Windows 10

## Description

One of the upgrade steps at [Liquibase 4.0 Extension Upgrade Guide](https://docs.liquibase.com/tools-integrations/extensions/extension-upgrade-guides/lb-4.0-upgrade-guide.html) is to change a `DatabaseFactory.getInstance()` to the `Scope.getCurrentScope().getSingleton(DatabaseFactory.class)` as far as `getInstance()` was marked as depricated.

`Scope.getCurrentScope().getSingleton(DatabaseFactory.class)` returns instance of `<T extends SingletonObject> T`. 
SingletonObject is a marker interface added in version 4.
But DatabaseFactory does not extend any classes and does not implement any interfaces.
As a result when we try to get the instance of DatabaseFactory in a way described in the Guide we faced an exception (see Actual Behaviour).

## Steps To Reproduce

The issue is reproduced in any situation when `Scope.getCurrentScope().getSingleton(DatabaseFactory.class)` was called.

## Actual Behavior
> Caused by: liquibase.exception.UnexpectedLiquibaseException: java.lang.ClassCastException: liquibase.database.DatabaseFactory cannot be cast to liquibase.SingletonObject
>         at liquibase.Scope.getSingleton(Scope.java:326)
>         at liquibase.Scope$getSingleton$0.call(Unknown Source)
>         ...
>         ...
>         at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
>         at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
>         at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
>         at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
>         at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:717)
>         at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:684)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
>         at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
>         at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
>         at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
>         at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
>         at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
>         at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
>         at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
>         at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
>         at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
>         at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
>         at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
>         at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
>         at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
>         at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
>         at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
>         at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
>         at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
>         at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
>         at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
>         at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
>         at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
>         at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
>         at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
>         at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
>         at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
>         at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
>         at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
>         at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
>         at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
>         at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
>         at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
>         at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
>         at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
>         at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
>         at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
>         at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
>         ... 34 more
> Caused by: java.lang.ClassCastException: liquibase.database.DatabaseFactory cannot be cast to liquibase.SingletonObject
>         at liquibase.Scope.getSingleton(Scope.java:323)
>         ... 91 more

**Comment by oleksii-syromolotov** [comment]
@kataggart hi,
may I ask is there any result of this issue?
As I can see it was closed but I cannot see any changes in documentation or PR. Was the issue irrelevant or smth else?

**Comment by nvoxland** [comment]
It seems like it should still be open and unresolved

**Comment by kataggart** [comment]
@oleksii-syromolotov 100% my error! apologies.. I shouldn't have closed. Thanks for pointing it out.. reopening

**Comment by npreisner** [comment]
Hi @kataggart,
We need to upgrade our liquibase-core version due to security issues and we are blocked on this issue.
Any updates?

Thanks
Natan

**Comment by yairogen** [comment]
we also need this ASAP. should we create PR to add tagging interface on DatabaseFactory?

**Comment by igreenfield** [comment]
What is the status of that? I also need that!!!

**Comment by filipelautert** [comment]
The fix is planed to be included in the next release later in January.

**Comment by filipelautert** [comment]
Close by PR https://github.com/liquibase/liquibase/pull/3624 merged just now.

**Comment by yairogen** [comment]
@filipelautert thanks for the merge. Is there a way to get a release candidate in Maven repo so we can check it out and verify on our end our usage of liquibase will work?

**Comment by filipelautert** [comment]
Hi @yairogen - usually we don't do release candidates, but you can get the build artifacts from master here: https://github.com/liquibase/liquibase/suites/10205393148/artifacts/499783593 . It's a zip file that contains the liquibase-core-0-snapshot.jar file, you can use it to run your tests. It also has all the other required files by maven so if you prefer you can just copy them to your .m2/repository/org/liquibase/liquibase-core/0-SNAPSHOT directory and use this version to test.
