### ISSUE TITLE
Liquibase diffChangeLog fails with NullPointerException

### ISSUE THREAD

**Issue by bglazyrin** [liquibase/liquibase#2373]
## Environment

**Liquibase Version**: 4.6.2 #886

**Liquibase Integration & Version**: CLI ( I start Liquibase from command prompt)

**Liquibase Extension(s) & Version**:  no extensions/default installation

**Database Vendor & Version**: Oracle DB 12.2.0.4

**Operating System Type & Version**: Microsoft Windows [Version 10.0.19043.985]

## Description

I am trying to use liquibase in our project in Oracle 12.1 database.
We have relatively big schema with more then 3000 objects.
So, I installed liquibase 4.6.2
then,
1. I run liquibase generateChangeLog
2. I then I issued changeLogSync
3. then I created snapshot:
4. liquibase --outputFile=mySnapshot.json snapshot --snapshotFormat=json
5. then I added few changes directly in my schema (added new test table)
6. then I run diffChangeLog to check, that it will detect these changes in schema.
liquibase --referenceUrl=jdbc:oracle:thin:@my-server:1521/MY_SID --referenceUsername=MY_SCHEMA --referencePassword=MY_PASSWORD --url=offline:oracle?snapshot=mySnapshot.json --changeLogFile=mydiffchangelog.xml diffChangeLog --log-level=DEBUG --logFile=out.txt
But it fails with exception:
Caused by: java.lang.NullPointerException
	at liquibase.diff.output.changelog.core.ChangedIndexChangeGenerator$1.toString(ChangedIndexChangeGenerator.java:117)
	at liquibase.diff.output.changelog.core.ChangedIndexChangeGenerator$1.toString(ChangedIndexChangeGenerator.java:114)
	at liquibase.util.StringUtil.join(StringUtil.java:319)

Unfortunate log file doesn't contain information what actually caused problem

## Steps To Reproduce

Se above

## Actual Behavior
I've attached log file out.txt

## Expected/Desired Behavior
diffChangeLog should finish successfully and contains all changes made directly in schema

**Comment by bglazyrin** [comment]
[out.txt](https://github.com/liquibase/liquibase/files/7873144/out.txt)

**Comment by dwieland** [comment]
I don't know if `obj` should ever be null in that situation, but the immediate problem is the missing null-check in:
https://github.com/liquibase/liquibase/blob/256675bca43a089e32c940e10ed8ed7a5f9d66f6/liquibase-core/src/main/java/liquibase/diff/output/changelog/core/ChangedIndexChangeGenerator.java#L114-L119
Should probably changed to
```java
return (obj == null) ? null : obj.toString(false);
```
The calling site seems to handle null values fine (stuffing it into a `StringBuilder` which will just write `null` into the string).

**Comment by FBurguer** [comment]
Hi! We have https://github.com/liquibase/liquibase/issues/1966 with the same issue but more details, so Im closing this one, we are going to keep working on this, so if you want more updates about, go ahead and follow issue #1966.
Thanks
