### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by JamieSlome** [liquibase/liquibase#2378]
Hey there!

I belong to an open source security research community, and a member (@ready-research) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by kataggart** [comment]
Thanks @JamieSlome @huntr-helper . We will definitely get back to you directly with specific instructions and add the file as well so others can use it. Thanks!

**Comment by kataggart** [comment]
@JamieSlome we are in the process of setting up a system for security researchers and I will definitely create the SECURITY.md file with those instructions once it is complete.

While this is in progress, any of your team can email me directly at ktaggart@liquibase.com and I will get the potential vulnerability s into the right pipelines over here. 

Thanks again!

**Comment by JamieSlome** [comment]
@kataggart - thanks for your response!

I mistakenly sent an e-mail to your organization's e-mail, but just sent it directly to your e-mail instead.

Let me know if you have any questions! 👍

**Comment by kataggart** [comment]
@JamieSlome got it! We are using that to possibly move the issue forward. Thanks!

**Comment by ready-research** [comment]
@kataggart Can you please validate the report using `Mark as Valid` and also `Confirm the fix`. Thanks.
https://www.huntr.dev/bounties/f1ae5779-b406-4594-a8a3-d089c68d6e70/

**Comment by kataggart** [comment]
@ready-research I left a question via the issue in your app. Thanks.

**Comment by ready-research** [comment]
You can also confirm the fix so that whoever (maintainer/reporter) fixes the issue they will also get fix bounty. Thanks again for validation.
