### ISSUE TITLE
Liquibase generateChangelog outputDefaultSchema :  generated view scripts does not contain schema

### ISSUE THREAD

**Issue by shilpagupta-axtria** [liquibase/liquibase#2379]
## Environment

**Liquibase Version**: 4.7.0

**Liquibase Integration & Version**: jenkins cli

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: postgresql-42.2.15.jar

**Operating System Type & Version**: 

## Description

Liquibase generateChangelog outputDefaultSchema :  generated view scripts does not contain schema
-- changeset jenkins:1642489198576-52
CREATE VIEW schema1."permission_data" AS SELECT *
   FROM profile;

## Expected/Desired Behavior
CREATE VIEW schema1."permission_data" AS SELECT *
   FROM **schema1.**profile;

**Comment by nvoxland** [comment]
Unfortunately postgresql doesn't preserve the default schema in the view definition and it is not something we can add back in. You can see what is available to us by running `select definition from pg_views where viewname=?` and we simply use that as the definition. 

There is so much complexity in all the queries across all the database platforms that we can't attempt to parse the definition and modify it.

Generated changesets should always be viewed as a "best attempt but not perfect" capture of the schema and should be inspected and possibly modified prior to use. This is one of the reasons why you may need to make changes to what got generated.
