### ISSUE TITLE
💡 Add Liquibase to SDKMAN!

### ISSUE THREAD

**Issue by adriens** [liquibase/liquibase#2381]
# 💡 Context

> SDKMAN! is a tool for managing parallel versions of multiple Software Development Kits 

Among its SDK we can find java runtime as well as build tools and a lot of [JVM based CLIs](https://sdkman.io/sdks) like : 

- [ant](https://sdkman.io/sdks#ant)
- [hadoop](https://sdkman.io/sdks#hadoop)
- [jbang](https://sdkman.io/sdks#jbang)
- [jreleaser](https://sdkman.io/sdks#jreleaser)
- [kcctl](https://sdkman.io/sdks#kcctl)
- [maven](https://sdkman.io/sdks#maven)
- [visualvm](https://sdkman.io/sdks#visualvm)
- [tomcat](https://sdkman.io/sdks#tomcat)

It really makes install process a breeze. I even do use it on windows from git bash.

The main idea is that it would be really exciting to be able to install liquibase from SDKMAN. So the end user can manage multiple versions, get version upgraded as broadcasts, etc...

# 🚀 Ressources

As you are the owner and maintainer I think that you would make sense if you were doing the publis by yourself if you find it convenient.

![image](https://user-images.githubusercontent.com/5235127/150084580-cc398ac0-e60a-4f8c-9be8-0aa5f3f47196.png)

Here is the [onboardning process
](https://github.com/sdkman/sdkman-cli/wiki/Vendor-onboarding-process).

Maybe will you have to provided a dedicated archive in your CI...by not modifying it too much 🤞

**Comment by adriens** [comment]
🐦 https://twitter.com/rastadidi/status/1483705488575725568

**Comment by aalmiray** [comment]
Might be worth considering JReleaser for making this happen, as well as publishing packages to Scoop, Chocolatey, Snap, Homebrew.

**Comment by kataggart** [comment]
thanks @kataggart we will take a look

**Comment by adriens** [comment]
> Might be worth considering JReleaser for making this happen, as well as publishing packages to Scoop, Chocolatey, Snap, Homebrew.

also getting `rpm` and `deb` btw 😸

**Comment by aalmiray** [comment]
`rpm` and `deb` can be produced with `jpackage` if the idea is to bundle a Java Runtime. Otherwise these files may be created using the corresponding Maven plugin.

JReleaser supports assembling jpackage distributions however if you feel like using an external script or some other means to create such packages then you can also do that.

**Comment by nvoxland** [comment]
I've looked a bit a JReleaser in the past. Enough to know it's there anyway...

We'll be looking at adding to our packaging & distribution over the next few months and I'll make sure to re-look at jpackager as an option, and sdkman as a distribution regardless.

**Comment by aalmiray** [comment]
Happy to help with any questions you may have with `jpackage`, `sdkman`, and/or `jreleaser`.

**Comment by nvoxland** [comment]
Thanks, @aalmiray . I'll reach out as this gets closer to the top of our list.

**Comment by adriens** [comment]
>  this gets closer to the top of our list.

These are great news :heavy_heart_exclamation:

**Comment by adriens** [comment]
Hi guys, are there any good new around `liquibase` integration with `SDKMAN!` :grey_question: 

![image](https://user-images.githubusercontent.com/5235127/211131864-be35b96b-5f5a-4761-b8ab-e5f5d5239a62.png)

**Comment by polarfish** [comment]
Any updates on this issue?

(I have just found myself playing with different versions of liquibase because of the changes in behaviour between 4.15.x - 4.23.x and I think it would have been much easier to be able to run `sdk use liquibase 4.18.0` and see `Using liquibase version 4.18.0 in this shell.`)

**Comment by adriens** [comment]
> Hi guys, are there any new?

[Tweet](https://twitter.com/liquibase/status/1736805116512993348)

![image](https://github.com/liquibase/liquibase/assets/5235127/1b01c04b-0d17-41de-b3d2-f9a6f81751f5)

**Comment by adriens** [comment]
:partying_face: 

![image](https://github.com/liquibase/liquibase/assets/5235127/60c0882e-dda7-4f78-a5bc-6178aa4bcd50)


![image](https://github.com/liquibase/liquibase/assets/5235127/7cd48242-aa94-492d-9eb4-7631523262e2)

![image](https://github.com/liquibase/liquibase/assets/5235127/a4c889f7-ff76-49a1-a071-ab01c0708e90)

![image](https://github.com/liquibase/liquibase/assets/5235127/e8a5646a-3397-424b-83f3-f7962abde152)

![image](https://github.com/liquibase/liquibase/assets/5235127/65d01c66-c088-42c6-b894-443765a1c10a)

**Comment by adriens** [comment]
:raised_hands: :clap: :sunglasses:  @jandroav 

![image](https://github.com/liquibase/liquibase/assets/5235127/f6e93b1e-b0d3-4f53-b685-ef0b19809221)

**Comment by adriens** [comment]
[Tweet](https://twitter.com/rastadidi/status/1768766892263821431)

![image](https://github.com/liquibase/liquibase/assets/5235127/d292d1a0-abbf-4775-9b97-3ff75af56751)
