### ISSUE TITLE
LoadDataChange.LOAD_DATA_TYPE enum type does not contain DATETIME, TIME OR TIMESTAMP which "breaks" NowAndTodayUtil

### ISSUE THREAD

**Issue by Jenson3210** [liquibase/liquibase#2383]
## Environment

**Liquibase Version**: 4.3.5 -> 4.4 -> 4.7

**Liquibase Integration & Version**: spring boot

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: ORACLE/H2

**Operating System Type & Version**: TOMCAT/LOCALHOST/MAC/WINDOWS

## Description

The NowAndTodayUtil checks for the specified column type to determine wether to return a Date, Timestamp, Time... 
https://github.com/liquibase/liquibase/blob/v4.7.0/liquibase-core/src/main/java/liquibase/util/NowAndTodayUtil.java#L83

The columnConfig was edited from v3.5.5 to v3.4.0 ad received a getTypeEnum() method which returns UNKNOWN if the value from the config is not in the list of values
Method: https://github.com/liquibase/liquibase/blob/v4.4.0/liquibase-core/src/main/java/liquibase/change/core/LoadDataColumnConfig.java#L61
List: https://github.com/liquibase/liquibase/blob/v4.4.0/liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java#L865

Since the method now returns UNKNOWN for any of the types except for date (datetime, time, timestamp), the value "now" is set as value and we do not come in the parsing anymore. 
https://github.com/liquibase/liquibase/blob/v4.4.0/liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java#L363

Date/Time is the only value where we do not have an enum possible: 
https://github.com/liquibase/liquibase/blob/v4.4.0/liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java#L363

## Steps To Reproduce
in tests add test code in LoadDataChangeTest.groovy
```groovy 
    def "temporal values work for DATE, DATETIME and TIME column configs"() {
        when:
        LoadDataChange change = new LoadDataChange()

        change.load(new liquibase.parser.core.ParsedNode(null, "loadData").addChildren([
                file     : "liquibase/change/core/sample.data.temporal.csv",
                tableName: "table.name"
        ]).setValue([
                [column: [name: "id", type: "NUMERIC"]],
                [column: [name: "date", type: "DATE"]],
                [column: [name: "datetime", type: "DATETIME"]],
                [column: [name: "time", type: "TIME"]],
        ]), new ClassLoaderResourceAccessor())

        SnapshotGeneratorFactory.instance = new MockSnapshotGeneratorFactory()

        LocalTime beforeGeneration = LocalTime.now().withNano(0)
        SqlStatement[] sqlStatements = change.generateStatements(mockDB)
        LocalTime afterGeneration = LocalTime.now().withNano(0).plusSeconds(1)

        LocalDate today = LocalDate.now()
        LocalDate date = LocalDate.of(2022, 9, 13)
        LocalTime time = LocalTime.of(12,34, 56, 789123000)
        then:
        //NULLS
        columnValue(sqlStatements[0], Col.id) == 1
        columnValue(sqlStatements[0], Col.date) == "NULL"
        columnValue(sqlStatements[0], Col.datetime) == "NULL"
        columnValue(sqlStatements[0], Col.time) == "NULL"

        //NOWANDTODAYUTIL used
        columnValue(sqlStatements[1], Col.id) == 2
        ((Date) columnValue(sqlStatements[1], Col.date)).toLocalDate() == today
        ((Timestamp) columnValue(sqlStatements[1], Col.datetime)).toLocalDateTime() <= LocalDateTime.of(today, afterGeneration)
        ((Timestamp) columnValue(sqlStatements[1], Col.datetime)).toLocalDateTime() >= LocalDateTime.of(today, beforeGeneration)
        ((Time) columnValue(sqlStatements[1], Col.time)).toLocalTime() <= afterGeneration
        ((Time) columnValue(sqlStatements[1], Col.time)).toLocalTime() >= beforeGeneration

        //VALUE PARSED
        columnValue(sqlStatements[2], Col.id) == 3
        ((Date) columnValue(sqlStatements[2], Col.date)).toLocalDate() == date
        ((Timestamp)columnValue(sqlStatements[2], Col.datetime)).toLocalDateTime() == LocalDateTime.of(date, time)
        ((DatabaseFunction) columnValue(sqlStatements[2], Col.time)).value == time.toString()
    }
```
In same file edit code enum col to contain datetime and time column
```groovy
    enum Col {
        name, num, date, bool, id, datetime, time

        String s() {
            return name();
        }
    }
```

## Actual Behavior

Test will fail because "now" is the columnValue (ico Now/today) and  no java.sql/databaseFunction type is set (ico timestamp, datetime)

## Expected/Desired Behavior

Move the block regarding LOAD_DATA_TYPE.UNKNOWN to the last (which makes sense because that's the _default_?)

```java
    else if (columnConfig.getTypeEnum() == LOAD_DATA_TYPE.UNKNOWN) {
        // columnConfig did not match a specific type
        valueConfig.setValue(value);
    }
```

OR

add the _missing_ LOAD_DATA_TYPES which might impact other code.

```java
else if ( columnConfig.getTypeEnum() == LOAD_DATA_TYPE.DATE ||
              columnConfig.getTypeEnum() == LOAD_DATA_TYPE.DATETIME ||
              columnConfig.getTypeEnum() == LOAD_DATA_TYPE.TIMESTAMP) {
```
```java
@SuppressWarnings("HardCodedStringLiteral")
    public enum LOAD_DATA_TYPE {
        BOOLEAN, NUMERIC, DATE, DATETIME, TIMESTAMP, STRING, COMPUTED, SEQUENCE, BLOB, CLOB, SKIP,UUID, OTHER, UNKNOWN
    }
```

**Comment by kataggart** [comment]
@Jenson3210 thanks for all the detail and the PR. We are reviewing.

**Comment by kflorian** [comment]
This is still not working for columns of type "timestamp" (event without timezone, which is a separate issue).
The fix is introducing support for "date", "time" and "datetime", but column type "timestamp" is still missing.
