### ISSUE TITLE
generateChangelog failed message typo is wrong

### ISSUE THREAD

**Issue by atlanboa** [liquibase/liquibase#2399]
## Environment

**Liquibase Version**:
    liquibaseRuntime("org.liquibase:liquibase-core:3.8.1")
    liquibaseRuntime("org.liquibase:liquibase-groovy-dsl:2.1.1")
    liquibaseRuntime("org.postgresql:postgresql")
    liquibaseRuntime("org.liquibase.ext:liquibase-hibernate5:4.3.5")
    liquibaseRuntime(sourceSets.getByName("main").compileClasspath)
    liquibaseRuntime(sourceSets.getByName("main").runtimeClasspath)
    liquibaseRuntime(sourceSets.getByName("main").output)
## Description

A clear and concise description of the issue being addressed.
- Describe the actual problematic behavior.
- Ensure private information is redacted.

## Steps To Reproduce

List the steps to reproduce the behavior.
1. create liquibase.properties file
`classpath=src/main/resources
changeLogFile=src/main/resources/db/changelog/version-0.0.1/changelog.postgres.sql
url=jdbc:postgresql://localhost:5432/liquibase_test
username=liquibase
password=liquibase
driver=org.postgresql.Driver
referenceUrl=hibernate:spring:com.example?dialect=org.hibernate.dialect.PostgreSQL95Dialect&hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
referenceDriver=liquibase.ext.hibernate.database.connection.HibernateDriver
defaultSchemaName=public
liquibaseProLicenseKey=ABwwGgQUzh+adIj/2kN9Spk6Brqtcdk2ZwcCAgQApMhre/dkZYmXMmFff/f3Ui8EHgiZ6dbC7IlLve0kbNrazyEh+zbkk1XC5k/2QRLmsPtPraLtajiOSwhc5oqxX2dKA0LB5javRhaLDvR/girG0H/fQpUG7/N1YrgmgAmnTZ3CFv4CKfE5uDstDLfrUFC6wUjWw1kg81q6msBndtMeqdvlPO3nqzgXnrnRjgAoBJm74tbXMRFPloWNEVxLlSetkZbJ47q0ZUOVD29moadQtKePPG5qJp/SIaR4t6dj5VUoFN7qbJZ8/5gzF/fMGaf66dQubCFXhRkeQBchzLrW/x+YJeghxQi3hn4NsC1WBO0rIvPS7IFXFdvs+A8yWEXB00i3bPRUMCiX5b0eohhJYbF8uBGsw7lmN5DZb44ZAdoKgwv0u4bd8MoUW6dJZ3v3339RTSiEqm8XrJnM9Jb4s6KscY2cOmydvPE5PPxSk14iZQ53wAi/vKYUGGWHL379tgn8nPAWeA7ardcqH4+/PWgD7K2zg0omXid8jJiDErMrFhi0ZJH16hlQoA/BVEapdpthUBcj2bUPj9pe2OKbpnqi3Ps0mQOFGcQoiYCyA0wAtE8poEJMCAL1VQ9VSt51DvDIhTpN9wCt418Ej58N5a6LexM7GsgwnGg8wytGP5i1WrE1DxYVmOdB6viEMA==`
2. run generateChangelog

## Screenshots (if appropriate)
the error output is like this
`Caused by: liquibase.command.CommandExecutionException: java.lang.RuntimeException: liquibase.exception.UnexpectedLiquibaseException: Serializing changelog as sql requires a file name in the format *.databaseType.sql. Example: changelog.h2.sql. Unknown **databaes** type: postgres
`

## Additional Context
databaes should be database

**Comment by kataggart** [comment]
@atlanboa it looks like this typo was resolved in version 3.8.2 (https://github.com/liquibase/liquibase/commit/ca2686ce8d0bf52e962d6eb2d447e60599f9fa8c#diff-54c6e6c40892e7db1e7dd9416211b36de889ad58e42ddb894058f8612c0ab5ce)

Thanks
