### ISSUE TITLE
PostgreSQL: Procedure execution not working with newer release

### ISSUE THREAD

**Issue by SantoshBharadwaj** [liquibase/liquibase#2400]
Dear team,
I'm seeing an issue while trying to execute a stored procedure through liquibase. I'm using PostgreSQL as the database implementation.

**Below is the summary of the issue.**
My application is Spring Boot based and it supports multi tenancy. I loop through the tenants and each tenant runs through the below two changesets.

**1st change set :** 
Creates a stored procedure as below:
![image](https://user-images.githubusercontent.com/41522930/150947158-d5a27f88-6325-47ac-af34-0bcc418b763c.png)

**2nd change set:**
Executes the above created stored procedure as below:
![image](https://user-images.githubusercontent.com/41522930/150947294-55fea33c-86e2-4ed7-9543-0f1a8d8f7bb3.png)

With liquibase version 4.4.1, I can see both the changesets have been executed successfully. No issue there.
But when I upgrade the version to 4.6.2, I see the below error.

_liquibase.exception.DatabaseException: ERROR: function my_custom_function() does not exist
Hint: No function matches the given name and argument types. You might need to add explicit type casts.
Position: 8 [Failed SQL: (0) SELECT my_custom_function()]
at liquibase.changelog.ChangeSet.execute(ChangeSet.java:695)
at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:49)
at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:111)
at liquibase.Scope.lambda$child$0(Scope.java:177)
at liquibase.Scope.child(Scope.java:186)
at liquibase.Scope.child(Scope.java:176)
at liquibase.Scope.child(Scope.java:155)
at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator..._

My doubt is how is the same code working well with 4.4.1 but not with the newer 4.6.2.
I'm not sure if it is already addressed. If so, would appreciate if you can point me to the solution.

Thanks in advance!

**Comment by kataggart** [comment]
Thanks @SantoshBharadwaj for all the details; we are reviewing.

**Comment by SantoshBharadwaj** [comment]
Hi team,
Is there any update on this please.. ?

**Comment by FBurguer** [comment]
It looks like the issue got fix on `4.14`. After following the steps provided, couldnt reproduce the bug. Do you mind checking it out again with `4.14` and see if it got fixed. If its not, let us know and we will look into it again! Thanks
