### ISSUE TITLE
https://github.com/liquibase/liquibase/issues/2342 Resurfaced ???

### ISSUE THREAD

**Issue by marcusnye** [liquibase/liquibase#2442]
Has the HTTP issue resurfaced at all from issue 2342.

Weve started to get the same issue again (we use an older version of liquibase that gets XSD's externally)

https://github.com/liquibase/liquibase/issues/2342

**Comment by Alex-Marshman** [comment]
Looks likely, I'm seeing the same issue again.

**Comment by VictorStatko** [comment]
+

**Comment by VictorStatko** [comment]
Same

**Comment by m0sk1t** [comment]
same

**Comment by jriderbc** [comment]
We are also seeing the issue.

**Comment by kataggart** [comment]
Thanks all for reporting this. We are looking into it; you can also track viahttps://github.com/liquibase/liquibase/issues/2449 
https://github.com/liquibase/liquibase/issues/2448

**Comment by molivasdat** [comment]
Hi @marcusnye @Alex-Marshman @VictorStatko @m0sk1t @jriderbc The issue has been fixed.  Can you please try again?

**Also can you let us know which version of Liquibase you are using?**

Later versions of Liquibase should not have this issue as they look for the XSDs locally.
