### ISSUE TITLE
YAML Example in "Substituting Properties" doc is formated wrong

### ISSUE THREAD

**Issue by dve** [liquibase/liquibase#2450]
## Environment

https://docs.liquibase.com/concepts/changelogs/property-substitution.html

## Description
The YAML example leads to NullPointerExecptions when running it

## Steps To Reproduce

Copy and Paste the example to a changelog file and use it

## Actual Behavior

The YAML parser crashes

## Expected/Desired Behavior

Liquibase can parse the example

## Additional Context

The whitespaces are wrong after copy and paste

**Comment by kataggart** [comment]
Thanks for this! We will follow up and fix.

**Comment by molivasdat** [comment]
Hi @dve If you want to move this to our documentation repository we can cover this.
https://github.com/Datical/liquibase-docs/issues

**Comment by dve** [comment]
Created https://github.com/Datical/liquibase-docs/issues/132
