### ISSUE TITLE
Simplify start-h2 usage and code

### ISSUE THREAD

**Issue by nvoxland** [liquibase/liquibase#2481]
## Description

Now that we have introduced `liquibase init start-h2` as a command, there is no need to have the start-h2/start-h2.bat scripts which are sensitive to h2 driver upgrades. This will require updating documentation talking about start-h2 as a separate command in favor of `liquibase init start-h2`

As part of that change, do three minor bugfixes as well:
1. Refactor the StartH2Main code so it lives in StartH2CommandStep instead of being a separate class
2. Update the error message about `the h2-<version>.jar file in liquibase/lib` to be `the h2 jar file in liquibase/lib` to avoid the filename that looks like it has `<version>` in it and better describe what version will run (since users can change it).
3. Force the http url shown and opened to be "localhost" rather than whatever "what is the server's IP address" logic h2 uses. We've seen VPN setups that confuse h2's logic

## Acceptance Criteria

1. Retain start-h2 files in the examples directory, but they call `liquibase init start-h2` and not `StartH2Main`
2. No documentation references to start-h2, only `liquibase init start-h2`
3. No more StartH2Main class
4. If you run `liquibase init start-h2` with no h2 jar file in your liquibase/lib dir, the error message is valid
5. Browser opens to "localhost" not an IP address
6. URLs shown in the console output are "localhost" and not an IP address
7. Tests for the refactored StartH2CommandStep

**Comment by kataggart** [comment]
Need to consider how this might impact docker, other scripts that might exist for people using the older command

**Comment by nvoxland** [comment]
While I think we want to update our docs to point to `liquibase init start-h2` regardless, I think the only main question was `should we delete the start-h2 script?` which seemed answered with "No, not now".

So I think this is something we get moving on?
