### ISSUE TITLE
Regression in Liquibase 4 - Improper value in NOW

### ISSUE THREAD

**Issue by tmuldoon** [liquibase/liquibase#2482]
## Environment

**Liquibase Version**: 4.6.2

**Liquibase Integration & Version**: Gradle 5.6.4

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: PostgreSQL 12.5

**Operating System Type & Version**: Windows 10

## Description

After upgrading from Liquibase 3.6.1 to 4.6.2, we’re seeing what we believe is a regression in the interpretation of the “now() + interval” expression, to PostgreSQL 12.5, in the following changeset…

```
insert(schemaName: 'apps', tableName: 'foo') {
    column(name: 'id', value: "1")
    column(name: 'updated_datetime', valueDate: "now() + interval '-4 days'")
}
```

In Liquibase 3.6.1, the expression is interpreted as expected…

```
INSERT INTO apps.foo(id, updated_datetime) VALUES ('1', now() + interval '-4 days')
```

In Liquibase 4.6.2, Liquibase reports the following...
```
Improper value in 'NOW' value: now() + interval '-4 days'. 'NOW' must be followed by + or -, then numeric offset, then units (h{our{s}}, m{inute{s}}, d{ay{s}}, or y{ears}
```

After changing the changeset in which we removed the left and right parenthesis from the now function call (as the Liquibase message seemed to indicate that we should), we discovered that PostgreSQL doesn't support "now" without the parenthesis...

```
Caused by: org.postgresql.util.PSQLException: ERROR: invalid input syntax for type timestamp with time zone: "now+4days"
```

For what it's worth, we are working around this issue (for now) by using the sql operation...
```
sql("insert into apps.foo (id, updated_datetime) values(1, now() - interval '4 days');")
```

**Comment by tmuldoon** [comment]
FYI - We now believe that this issue is bigger than we originally thought in that it affects all uses of the now() function in all insert statements' columns which use the ```valueDate``` attribute (regardless of now() being part of an expression).

e.g. #1
```
insert(schemaName: 'apps', tableName: 'foo') {
    column(name: 'id', value: "1")
    column(name: 'updated_datetime', valueDate: "now()")
}
```

For what it's worth, we noticed that the issue does not occur if we change valueDate to valueComputed (which we believe will result in a checksum change, which we would like to avoid, if at all possible).

**Comment by tmuldoon** [comment]
UPDATE - We changed valueDate to valueComputed, as we suggested in our previous comment, and discovered that the checksum did NOT change (for previously executed changesets).

**Comment by tmuldoon** [comment]
After thinking about this more, we have come to the conclusion that valueDate should NOT be used with the now() function (or any other function for that matter) and that valueComputed should be used AND that this is "by design". Is that right?

**Comment by nvoxland** [comment]
Yes, that is right. `valueComputed` is for any sort of function (including now`()` ) whereas valueDate is for "this is a string that should be parsed as a date" which now() is not.
