### ISSUE TITLE
Validate updates to MANIFEST.MF in 4.8.0 release.

### ISSUE THREAD

**Issue by kataggart** [liquibase/liquibase#2511]
[The PR to bump manifest versions for OSGI](https://github.com/liquibase/liquibase/issues/2361) could not be tested prior to merge. This is due to the fact that the changes to the MANIFEST.MF occur only during an official release draft or official release build. This ticket is to ensure Liquibase Internal QA validates the version updates.

**Comment by XDelphiGrl** [comment]
Our change in build systems and philosophy resulted in the unintentional mis-versioning in the MANIFEST.MF. This fix addresses that mis-versioning. @nvoxland added a script that validates there are no `0-SNAPSHOT` or `0.0.0-SNAPSHOT` versions in the MANIFEST.MF. This will run at the end of release (internally by Liquibase engineering). 

---

Verify there are no references to 0-SNAPSHOT in MANIFEST.MF  **PASS**
Verify there are no references to 0.0.0-SNAPSHOT in MANIFEST.MF  **PASS**
Verify Bundle-Version in MANIFEST.MF is 4.8.0. **PASS**

---
**Test Environment**
liquibase-4.8.0.jar
