### ISSUE TITLE
XSDs are not resolved from the jar when referenced via HTTPS (liquibase 3.x)

### ISSUE THREAD

**Issue by polarfish** [liquibase/liquibase#2520]
## Environment

**Liquibase Version**: 
3.10.3

**Liquibase Integration & Version**: 
Spring Boot 2.5.1, java 11

**Liquibase Extension(s) & Version**:  
N/A

**Database Vendor & Version**: 
MySql 5.7

**Operating System Type & Version**:
MacOS BigSur 11.6.3

## Description

Liquibase 3.x fails to resolve local XSD referenced via HTTPS when being run offline (without internet access).

> The problem is also explained in https://github.com/liquibase/liquibase/issues/1153, but the mentioned issue has been already closed and the problem is still present.

## Steps To Reproduce

- Run liquibase SQL generation from an XML changelog file referencing XSD schema as `https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd` and without internet access

## Actual Behavior
It fails with an error
```
"Error parsing line X column Y of changelog.xml: schema_reference.4: Failed to read schema document
'https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd', because 1) could not find the 
document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>."
```

## Expected/Desired Behavior
The SQL generation process is successful.

## Additional Context
When I use HTTP (http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd) then it's working fine.

This is the different combinations I tried (liquibase 3.10.3 in the classpath, working offline by disabling Wi-Fi) :
```
http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd -> OK
https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd -> FAIL

http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.10.xsd -> OK
https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.10.xsd -> FAIL

http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.5.xsd -> FAIL (this is expected because dbchangelog-4.5.xsd is not bundled into liquibase-3.10.3.jar)
https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.5.xsd -> FAIL
```

**Comment by kataggart** [comment]
@polarfish Are you able to upgrade to a more recent version? Or is there a limiting factor on your end that prevents this? Thanks!

**Comment by polarfish** [comment]
@kataggart We updated to the new version of Liquibase, but we still support existing versions of our product that were released with Liquibase 3.10.

**Comment by nvoxland** [comment]
I'm not sure how you are using Liquibase, but for most usage going from 3.x to 4.x shouldn't be a major change. There are some larger changes in the APIs and some problematic defaults were changed, but perhaps even in your old versions you could upgrade to the latest 4.x version?

If not, the problem logic is likely in XMLChangeLogSAXParser and how it sets up the resolver which we have implemented in LIquibaseEntityResolver.

You can create an extension subclass of XMLChangeLogSAXParser with a higher getPriority() result to use your class instead of the default, and override how it creates and uses that resolver field even if you need to use reflection to force a different value for it since it's private.

**Comment by polarfish** [comment]
@kataggart @nvoxland Thanks for the suggestions. We can address this in out product. I thought to create this issue to have it addressed in 3.x, but if the recommended solution is to upgrade to version 4, you can close this issue as Won't Fix.

**Comment by nvoxland** [comment]
Thanks for the follow-up. I'll close this issue
