### ISSUE TITLE
ORDER keyword for sequences is not supported by mssql

### ISSUE THREAD

**Issue by jenhae** [liquibase/liquibase#2528]
## Environment

**Liquibase Version**: 4.5.0

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: Microsoft SQL Server 2017 (RTM-CU12) (KB4464082) - 14.0.3045.24 (X64)

**Operating System Type & Version**: Windows 10

## Description
The documentation states at https://docs.liquibase.com/change-types/create-sequence.html that 
the ````ordered```` attribute of createSequence entitiy is supported for mssql. But when running the generated SQL or the changeSet against a MS SQL Server 
I get an Error 'Incorrect syntax near the keyword 'ORDER'.', without ORDER the statemant works as expected.

## Steps To Reproduce

List the steps to reproduce the behavior.
- use createSequence entity with ordered="true" to generate a sequence as doen here:
````xml
<databaseChangeLog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.6.xsd">

  <changeSet id="Test" author="Me">
    <createSequence sequenceName="MY_DUMMY_SEQUENCE" startValue="1" incrementBy="1" ordered="true" />
  </changeSet>
</databaseChangeLog>
````
- run against MSSQL 

## Actual Behavior
Execution of createSequence fails.

## Expected/Desired Behavior
Documentation is adjusted.

**Comment by yodzhubeiskyi** [comment]
Fixed by [#2549](https://app.zenhub.com/workspaces/liquibase-56e1fd58266d3caa6f35a5fb/issues/liquibase/liquibase/2549)
