### ISSUE TITLE
Using xsd schema url with https makes start up really slow

### ISSUE THREAD

**Issue by firatkucuk** [liquibase/liquibase#2564]
## Environment

**Liquibase Version**: 3.8.9

**Liquibase Integration & Version**: spring-boot

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: postgresql 12.2

**Operating System Type & Version**: Linux

## Description

Intellij IDEA suggested to use https in xsd schema definition then we have changed URL in all our files:

```xml
<databaseChangeLog
  xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
    https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd">
```

After a while we have noticed a huge slowness on application startup. Debug showed us cannot find xsd file
and tries to download for every single liquibase file in `LiquibaseSchemaResolver.getInputSourceFromXsd` method

## Steps To Reproduce

change the xsd url from `http` to `https`

## Actual Behavior

Liquibase should match it with internal xsd file in the package

**Comment by kataggart** [comment]
@firatkucuk Thanks for submitting this. Would you be able to upgrade to the current version?

**Comment by nvoxland** [comment]
The current code should be using the local copy of the XSD for both http and https now, so wanting to make sure you are not still seeing slowness with https for a different reason

**Comment by firatkucuk** [comment]
Ok I've created a sample application:

https://github.com/firatkucuk/liquibase-https-test

So those are the results:

Version 4.8
- http: 2.389 seconds
- https: 2.557 seconds

version 3.8.9
- http: 2.994 seconds
- https: 20.678 seconds

so seems somehow resolved in newer releases. I guess, we can close it.
