### ISSUE TITLE
handling of changeset filenames with special characters (e.g. german umlauts) fails in (at least) command line since v4

### ISSUE THREAD

**Issue by McNetic** [liquibase/liquibase#2620]
## Environment

**Liquibase Version**: 4.8.0, also tested with 4.0.0 (working in 3.10.3)

**Liquibase Integration & Version**: CLI (others not tested)

**Liquibase Extension(s) & Version**: -

**Database Vendor & Version**: irrelevant

**Operating System Type & Version**: Windows 10 German

## Description

When using a datebase changelog xml file referencing sql files for changesets, since v4 it is no longer possible that the sql filenames contain special characters (e.g. german umlauts ÄÜÖöäü). Running liquibase update produces an error like:
`Unexpected error running Liquibase: Unable to read file 'changesetwith▒.sql'`
When run with log level debug, the actual error is reported as 
```
Caused by: java.io.IOException: Found 2 files that match changesetwith▒.sql: file:/[...]/liquibase/bugreport/changesetwith▒.sql, file:/...]/liquibase/bugreport/changesetwith%c3%96.sql
        at liquibase.resource.AbstractResourceAccessor.openStream(AbstractResourceAccessor.java:25)
        at liquibase.change.core.SQLFileChange.openSqlStream(SQLFileChange.java:123)
        ... 55 more
```
With versions 3.10.3 and earlier, this worked without errors.

## Steps To Reproduce

- create a minimal liquibase project for example with liquibase init
- replace the changelog with an xml changelog like 
```
<?xml version="1.0" encoding="UTF-8"?>

<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
        http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">

    <changeSet id="changesetwithä" author="nicolai.ehemann">
        <sqlFile path="changesetwithä.sql" />
    </changeSet>

</databaseChangeLog>
```
- update liquibase.properties accordingly
- create a changeset file "changesetwithä.sql" (contents irrelevant)
- run `liquibase init start-h2`
- run `liquibase update`

## Actual Behavior
- liquibase exits with an error

## Expected/Desired Behavior
- changeset file should be found

**Comment by FBurguer** [comment]
Looks like it got fixed on 4.14 or the changeset file content is relevant.
```
Running Changeset: newchangelog.postgresSQL.xml::changesetwithä::nicolai.ehemann
Liquibase command 'update' was executed successfully.
```
