### ISSUE TITLE
ReNameView does not produce correct rollback if using a non-default schema.

### ISSUE THREAD

**Issue by damonsutherland** [liquibase/liquibase#2626]
## Environment

**Liquibase Version**: 4.7.1 (Although I believe the bug has existed since the inception of renameView)

**Database Vendor & Version**: Postgres 13

**Operating System Type & Version**: MacOS 12.1

## Description

Rollback of RenameViewChange does not include the schema.  This is possibly due to not setting the schemaName in the [createInverses](https://github.com/liquibase/liquibase/blob/v4.8.0/liquibase-core/src/main/java/liquibase/change/core/RenameViewChange.java#L62) method in RenameViewChange.

## Steps To Reproduce

1. Create a new schema in v0
2. Create a View in the new schema in a v1 tag.
3. Rename the View, specifying the schema, in a v2 tag
4. Rollback to the v1 tag

## Actual Behavior
Error is thrown: ERROR: relation "public.view_name" does not exist

## Expected/Desired Behavior
No error.  The correct schema should be set.

**Comment by FBurguer** [comment]
Looks like the issue has been fixed for liquibase `4.15`. If the issue continues to happen to you, please reach out and we will have a second look. Thanks!
