### ISSUE TITLE
Default logger does not handle null package names

### ISSUE THREAD

**Issue by nvoxland** [liquibase/liquibase#2633]
## Description

From https://clojurians.slack.com/archives/C03S1KBA2/p1646949527191689

Class.getPackage() does not always return a value and can return null too, and when it does, it throws NPE here: https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/logging/core/JavaLogService.java#L45

Newer jdk versions have a getPackageName() method, but jdk 8 only has .getPackage() which could return null. https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getPackage--

This likely impacts many non-java languages on the JVM besides Clojure

**Comment by camsaul** [comment]
I'm the one who originally ran in to this issue, if it helps anyone out I worked around it by using reflection to define the package at runtime like this: 

https://github.com/metabase/metabase/pull/20611/files#diff-e88407a2a9e37e54f364b56ce07163320a2861af463684af40099ad9d8b60e73R21-R43

You probably only need to do this in environments that define classes at runtime e.g. Clojure `proxy` and `reify`
