### ISSUE TITLE
Changesets containing plain sql-scripts are executed in postgres public schema but not in the configured liquibase default schema since 4.5.0

### ISSUE THREAD

**Issue by Chr3is** [liquibase/liquibase#2640]
## Environment

**Liquibase Version**: 4.5.0 - latest version

**Liquibase Integration & Version**:  spring boot

**Database Vendor & Version**: Postgres 13.2 with 42.3.3 (driver)

**Operating System Type & Version**: Windows 10

## Description
With Liquibase v4.5.0 changesets which were written in plain sql are executed in the public schema but not in the configured liquibase default schema. 

## Steps To Reproduce
Run ApplicationTest in demo project. The test will fail because hibernate searches in the configured schema 'testschema' and not in the public schema which leads to an unknown table 'table_two' which were created with a sql-changeset. Table 'table_one' was created through yaml-config and is found by hibernate in the correct schema.

## Actual Behavior
Tables which are created through sql-scripts are created in the postgres public schema.

## Expected/Desired Behavior
Tables which are created through sql-scripts are created in the configured liquibase default-schema like tables which were written 
with yaml.

Last working version was 4.4.0

[demo.zip](https://github.com/liquibase/liquibase/files/8246547/demo.zip)

**Comment by Chr3is** [comment]
Probably the same as https://github.com/liquibase/liquibase/issues/2234

**Comment by nvoxland** [comment]
I created a PR that should address this
