### ISSUE TITLE
Multi Line incompatibility between versions 3 and 4

### ISSUE THREAD

**Issue by abelom** [liquibase/liquibase#2647]
I am trying to migrate from version 3 to version 4 and hitting a difference in how multiline is handled - what used to be properly split into two statements in version 3 is no longer split into two statements in version 4

I was able to isolate the difference in behavior to different handling of
```
StringUtils.processMutliLineSQL(   "ALTER TABLE/\nCREATE INDEX/",   false, true, "/")
```
which seems to be caused by https://github.com/liquibase/liquibase/commit/0c7c94529cb98e42e13a993e405e35c191759979 commit - especially the new special handling of "/" in ``if ("/".equals(endDelimiter)) {``

unfortunately that commit comment does not provide any details on the reason on the change, it looks like branch merge but I am unable to find corresponding change in 3.8 branch

Question: is there any documentation on the change to multiline handling? Any migration manual material to cover the change in multi line handling?

**Comment by nvoxland** [comment]
In v3, were you using a trailing `/` at the end of the line as an end delimiter? 

Like was your changeset
```
<sql>
ALTER TABLE/
CREATE INDEX/
</sql>
```
?

Or did you have the / on the newline like this:

```
<sql>
ALTER TABLE
/
CREATE INDEX
/
</sql>
```
?

**Comment by rusefillc** [comment]
Well, on top level I have
```
<sql endDelimiter=";">
   ALTER TABLE INS ADD (SUS VARCHAR2(100 CHAR), SSID VARCHAR2(100 CHAR) UNIQUE);
   CREATE INDEX idx_sus
   ON ins(SUS) tablespace i_;
</sql>
```
above works with v3 but does not work with v4 for me. While debugging v3 and v4 next to each other I've learned that internally it ends up referring "/" delimiter and "ALTER TABLE/\nCREATE INDEX/" is a simplified version which illustrates difference of handling, I have a one line unit test illustrating the difference. While I know where the difference happens I am not sure what's the reason for the change thus no hints on how I should convert my changesets.

i see special handling ``if ("/".equals(endDelimiter)) {`` added by the commit I was referencing. How "/" delimiter turns to be while processing my ``endDelimiter=";"`` I have no idea I am not that deep in understanding (yet), that's why I was looking for any migration notes or comments on that change.

**Comment by abelom** [comment]
Well, on top level I have
```
<sql endDelimiter=";">
   ALTER TABLE INS ADD (SUS VARCHAR2(100 CHAR), SSID VARCHAR2(100 CHAR) UNIQUE);
   CREATE INDEX idx_sus
   ON ins(SUS) tablespace i_;
</sql>
```
above works with v3 but does not work with v4 for me. While debugging v3 and v4 next to each other I've learned that internally it ends up referring "/" delimiter and ``"ALTER TABLE/\nCREATE INDEX/"`` is a simplified version which illustrates difference of handling, I have a one line unit test illustrating the difference. While I know where the difference happens I am not sure what's the reason for the change thus no hints on how I should convert my changesets.

i see special handling ``if ("/".equals(endDelimiter)) {`` added by the commit I was referencing. How "/" delimiter turns to be while processing my ``endDelimiter=";"`` I have no idea I am not that deep in understanding (yet), that's why I was looking for any migration notes or comments on that change.

**Comment by dwieland** [comment]
Cross-checked with 3.10, 4.3, 4.6 and 4.8. The behavior is exactly the same except for a single case:
`endDelimiter="/"` and having trailing `/` instead of separate lines. Liquibase 4.x does not detect the end delimiter in that case anymore.

Introduced by: #853
Fixed by: #2135 (probably 4.9?)

**Comment by rusefillc** [comment]
https://github.com/liquibase/liquibase/issues/2647#issuecomment-1069566372 definitely has ``endDelimiter=";"``

is stuff converted into ``endDelimiter="/"`` somewhere internally?

**Comment by dwieland** [comment]
I used the following quite minimal changeLog:
```yaml
databaseChangeLog:
  - changeSet:
      id: 1
      author: dev
      changes:
        - createTable:
            tableName: INS
            columns:
              - column:
                  name: PRIM
                  type: INT
        - sql:
            endDelimiter: "/"
            sql: |
              ALTER TABLE INS ADD (SUS VARCHAR2(100 CHAR), SSID VARCHAR2(100 CHAR) UNIQUE)/
              CREATE INDEX idx_sus
              ON ins(SUS)/
```
and tried different delimiters (`;`, `/` and `GO`) as well as different `endDelimiter` configurations.
Except for the above case I never saw any different result from 3.10.

**Comment by abelom** [comment]
our tests pass with 4.9.0 thank you!
