### ISSUE TITLE
Failed to read schema document 'dbchangelog-3.8.xsd', because 'file' access is not allowed due to restriction set by the accessExternalSchema property

### ISSUE THREAD

**Issue by kirillka415** [liquibase/liquibase#2654]
Hi 
I have faced an issue with reading  local schema file  in  liquibase  version 4.8 and 4.9

``` Starting Liquibase at 14:19:54 (version 4.9.0 #1885 built at 2022-03-16 16:58+0000)
Liquibase Version: 4.9.0
Liquibase Community 4.9.0 by Liquibase

Unexpected error running Liquibase: Error parsing line 3 column 55 of ./db.changelog.xml: schema_reference: Failed to read schema document 'dbchangelog-3.8.xsd', because 'file' access is not allowed due to restriction set by the accessExternalSchema property.

For more information, please use the --log-level flag 
```
We store schema file locally  (XMLSchema\dbchangelog-3.8.xsd) to be able run liquibase "update" without internet access
and in change log we reference to this location 
Here is example of changeLog
```
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog XMLSchema/dbchangelog-3.8.xsd"
    logicalFilePath="db.changelog.xml">
	
    <include file="changelog_db.xml" relativeToChangelogFile="true"/>

</databaseChangeLog>
```
There is no such issue in version 4.7.1.
Could you have a look?

**Comment by kataggart** [comment]
Hi @kirillka415,

In 4.8 we introduced a new `liquibase.secureParsing` parameter. You can read a bit more about it in in the [docs](https://docs.liquibase.com/concepts/changelogs/xml-format.html), also a good description in the [release notes](https://docs.liquibase.com/release-notes/home.html) for https://github.com/liquibase/liquibase/pull/2558.

Let me know if this doesn't resolve things on your end.

Thanks much!

**Comment by kirillka415** [comment]
Thank you, @kataggart 
It works for me.

I added liquibase.secureParsing parameter to the property file
liquibase.secureParsing=false

**Comment by giancarloromeo** [comment]
Is there a way to disable it programmatically? (Java)

**Comment by envious** [comment]
How do you set liquibase.secureParsing in a Spring Boot project?

**Comment by kataggart** [comment]
Since this issue is closed, we are no longer actively monitoring it.[ I opened a thread on the forum so community](url) folks can help you all out.

**Comment by mukundajvcs** [comment]
> How do you set liquibase.secureParsing in a Spring Boot project?

Did you get where to set liquibase.secureParsing in a Spring Boot project?

**Comment by adam-bodrogi-epam** [comment]
Actually I tried it with 4.9.1 and it didn't pick up the parameter seemingly, didn't solve the issue. Increased liquibase version to 4.25.0 and it works now. 
@mukundajvcs I guess I'm late, but you have to provide it as VM argument: 
`bash gradlew bootRun  -Dliquibase.secureParsing=false` or in idea set it in "VM Options" or "Program arguments" in the run config.
