### ISSUE TITLE
Precondition tableExists crashes on H2 with objectQuotingStrategy=LEGACY, if a camelCaseView already exists.

### ISSUE THREAD

**Issue by mm65de** [liquibase/liquibase#2659]
## Environment

**Liquibase Version**: 4.9.0

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**:  -

**Database Vendor & Version**: H2 Database, 2.1.210

**Operating System Type & Version**: Microsoft Windows [Version 10.0.19044.1586]

## Description

Preconditions (e.g. `tableExists`) crash on H2 database, if the db schema already contains a view, whose name uses camelCase (i.e. it was created with `objectQuotingStrategy="QUOTE_ALL_OBJECTS"` before), but the changeSet that contains the precondition (or the complete changelog file) uses `objectQuotingStrategy="LEGACY"`.

Here comes the example `changelog.xml`:
```
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog 
                                       http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.9.xsd"
                   objectQuotingStrategy="LEGACY">
    
    <changeSet id="1 Create MyView" author="mamue" objectQuotingStrategy="QUOTE_ALL_OBJECTS">
        <createView  viewName="MyView" replaceIfExists="true">select 1</createView>
    </changeSet>

    <changeSet id="2 Drop NOT_EXISTENT_TABLE" author="mamue">
        <preConditions onFail="MARK_RAN"><tableExists tableName="NOT_EXISTENT_TABLE"/></preConditions>
        <dropTable tableName="NOT_EXISTENT_TABLE"/>
    </changeSet>

</databaseChangeLog>
```

The first changeSet is executed without problems.
The evaluation of the precondition of the second changeSet crashes with this error message: `Unexpected error running Liquibase: Expected single row from liquibase.statement.core.GetViewDefinitionStatement@9255c05 but got 0`

I used the following `liquibase.properties` file:
```
changeLogFile: changelog.xml
driver: org.h2.Driver
url: jdbc:h2:mem:
username: sa
password: 
liquibase.secureParsing: false
```

## Steps To Reproduce

* Download `liquibase-4.9.0.zip` and extract it to a new folder.
* Place the `changelog.xml` and `liquibase.properties` files mentioned above in the root folder of the extracted archive.
* Start the `liquibase.bat` with the argument `update`.
* Watch the output. It should be something like this:

> Running Changeset: changelog.xml::1 Create MyView::mamue
> Running Changeset: changelog.xml::2 Drop NOT_EXISTENT_TABLE::mamue
> 
> Unexpected error running Liquibase: Expected single row from liquibase.statement.core.GetViewDefinitionStatement@9255c05 but got 0
> 
> For more information, please use the --log-level flag

## Actual Behavior
The evaluation of the precondition of the second changeSet of the example `changelog.xml` runs into the already mentioned error. The execution of the `changelog.xml` is stopped prematurely.

## Expected/Desired Behavior
The execution of the precondition of the second changeSet detects that the table  `NOT_EXISTENT_TABLE`  does not exist and therefore skips the execution of the action of the second changeSet and marks that changeSet RUN in the table `DATABASECHANGELOG`. The execution of the `changelog.xml` finishes without error.

## Additional Context
I found that also other preconditions fail, that check for the existence of some database object. The error message was the same. The error also happens with file based H2 databases.

**Comment by FBurguer** [comment]
I reproduce the issue with the steps provided. If on the second changset exists or the second changeset uses `objectQuotingStrategy="QUOTE_ALL_OBJECTS"` it run succesfully.
