### ISSUE TITLE
NullPointerException on startup /w whitespace system environment variable

### ISSUE THREAD

**Issue by ThomGeG** [liquibase/liquibase#2664]
## Environment

**Liquibase Version**: 4.9.0

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: N/A

**Operating System Type & Version**: Alpine 3.15.4

## Description

While looking at the system environment variables to grab the default configurations at startup, the `EnvironmentValueProvider.keyMatches(String, String)` does `storedKey = StringUtil.trimToNull(storedKey)` before calling the super. The super however (`liquibase.configuration.AbstractMapConfigurationValueProvider.keyMatches(String, String)`) doesn't then access the `storedKey` in a null-safe way:

```
    protected boolean keyMatches(String wantedKey, String storedKey) {
        if (storedKey.equalsIgnoreCase(wantedKey)) {
            return true;
        }
        ...
```

This will cause a NullPointerException when the system scans for the pro-license or any other keys among the system environment variables if one of them is only whitespace.

## Steps To Reproduce

- Add a system environment variable with a key of only whitespace and some arbitrary value
- Run any command you want via the CLI

## Actual Behavior
The aforementioned code triggers an NPE, crashes, and leaves you with a very vague error message due to the exception happening before the logging is turned back on by the `--log-level` flag (might also be something to look at changing, had to hook up the remote debugger to get the stack trace).
```
Unexpected error running Liquibase: java.lang.NullPointerException

For more information, please use the --log-level flag
```

## Expected/Desired Behavior
No NPE is triggered and your command succeeds

## Screenshots (if appropriate)
N/A

## Additional Context
Stack trace on startup while looking for `liquibase.pro.licenseKey`:
```
Thread [main] (Suspended (breakpoint at line 60 in NullPointerException))	
	NullPointerException.<init>() line: 60	
	EnvironmentValueProvider(AbstractMapConfigurationValueProvider).keyMatches(String, String) line: 140	
	EnvironmentValueProvider.keyMatches(String, String) line: not available	
	EnvironmentValueProvider(AbstractMapConfigurationValueProvider).lookupProvidedValue(String...) line: 105	
	EnvironmentValueProvider.lookupProvidedValue(String...) line: not available	
	EnvironmentValueProvider(AbstractMapConfigurationValueProvider).getProvidedValue(String...) line: 52	
	LiquibaseConfiguration.getCurrentConfiguredValue(ConfigurationValueConverter<DataType>, ConfigurationValueObfuscator<DataType>, String...) line: 123	
	ConfigurationDefinition<DataType>.getCurrentConfiguredValue() line: 93	
	DaticalTrueLicenseService.licenseIsInstalled() line: not available	
	DaticalTrueLicenseService.licenseIsValid(String) line: not available	
	EnvironmentValueProvider.lookupProvidedValue(String...) line: not available	
	EnvironmentValueProvider(AbstractMapConfigurationValueProvider).getProvidedValue(String...) line: 52	
	LiquibaseConfiguration.getCurrentConfiguredValue(ConfigurationValueConverter<DataType>, ConfigurationValueObfuscator<DataType>, String...) line: 123	
	ConfigurationDefinition<DataType>.getCurrentConfiguredValue() line: 93	
	LiquibaseCommandLine.registerValueProviders(String[]) line: 435	
	LiquibaseCommandLine.execute(String[]) line: 289	
	LiquibaseCommandLine.main(String[]) line: 80	
```

**Comment by kataggart** [comment]
Thanks @ThomGeG we have https://github.com/liquibase/liquibase/pull/2636 moving through that should address this.
