### ISSUE TITLE
SpringResourceAccessor.getCompletePath resolves sql resources incorrectly when changelog is in root

### ISSUE THREAD

**Issue by jurgendl** [liquibase/liquibase#2668]
## Environment

**Liquibase Version**: 4.9.0

**Liquibase Integration & Version**: maven

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: apache derby 0.14.2.0

**Operating System Type & Version**: Win 10

## Description

proble resolving resource path in class/method:
SpringResourceAccessor.getCompletePath(String relativeTo, String path)

code line: 
searchPath = relativeTo.replaceFirst("/[^/]+$", "") + "/" + path;

worked in 3.10.1, does not work in 4.9.0

## Steps To Reproduce

SpringLiquibase liquibase = new SpringLiquibase();
liquibase.setChangeLog("liquibase-changeLog.xml");
liquibase.setDataSource(dataSource);

changelog
<changeSet ...>
	<sqlFile path="liquibase-scripts/000-setup.sql" ...>
</changeSet>

files in classpath
liquibase-changeLog.xml
liquibase-scripts/000-setup.sql

## Actual Behavior

searchPath = relativeTo.replaceFirst("/[^/]+$", "") + "/" + path;

is not OK whe changelog is on root:
relativeTo = "liquibase-changeLog.xml"
relativeIsFile = true
relativeTo.replaceFirst("/[^/]+$", "")  = "liquibase-changeLog.xml"
searchPath = "liquibase-changeLog.xml/liquibase-scripts/000-setup.sql"

is OK whe changelog is in a folder:
relativeTo = "somefolder/liquibase-changeLog.xml"
relativeIsFile = true
relativeTo.replaceFirst("/[^/]+$", "")  = "somefolder" 
searchPath = "somefolder/liquibase-scripts/000-setup.sql"

## Expected/Desired Behavior

relativeTo should be "" and probably no "/" should be added
searchPath should be "liquibase-scripts/000-setup.sql"

**Comment by nvoxland** [comment]
This should be fixed in #3064 since the problem method is getting removed
