### ISSUE TITLE
Migration from 3.3.2 on 3.6.3. Changed sqlFile from old changeSet was re-run without errors.

### ISSUE THREAD

**Issue by Muerti** [liquibase/liquibase#2673]
## Environment

**3.6.3**:

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Oracle 12c**:

**Linux**:

## Description
I have a changeset with sqlFile. This sqlFile contains "create or replace if exists" package and its body.This changeset has been already executed with liquibase 3.3.2 .
After that sqlFile from this changeset was changed (just added few spaces). We migrated on liquibase 3.6.3. In process of installment with new liquibase it doesn't fail on differences as expected. The sql script from changeset was re-run.  
There is no runOnchange option in this changeset. 

I guess there is no errors since in new liquibase version checksums are different. But at least, it was promised, that  sqlFiles from old changeset will not be re-run. 

## Steps To Reproduce

List the steps to reproduce the behavior.

1) Data:
```
<changeSet id="000" author="autor">
        <sqlFile path="pkg1.sql" relativeToChangelogFile="true" endDelimiter="\n/\s*\n|\n/\s*$"
                 splitStatements="true"/>
        <rollback>
            <sqlFile path="sql0.sql" relativeToChangelogFile="true" endDelimiter="\n/\s*\n|\n/\s*$"
                     splitStatements="true"/>
        </rollback>
</changeSet>
```
pkg1.sql contains any create or replace package and body.
2) install with liquibase 3.3.2
3)change some way pkg1.sql 
4)install with liquibase 3.6.3

## Actual Behavior
script from changed pkg1.sql was executed

## Expected/Desired Behavior
error or at least script from changed pkg1.sql was not executed

**Comment by kataggart** [comment]
@Muerti  Can you tell if the prefix number before the ':' in the checksums are different between the two versions? Thanks!
