### ISSUE TITLE
Liquibase stripping trailing 0 characters from changset identitiers

### ISSUE THREAD

**Issue by stephen-elves** [liquibase/liquibase#2689]
## Environment

**4.8.0**:

**CLI**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Redshift 4.90**: 

**AWS Redshift**:

**Windows 10 Pro**:

## Description

A clear and concise description of the issue being addressed.
- Describe the actual problematic behavior.
- Ensure private information is redacted.

## Steps To Reproduce

I don’t know if it’s relevant but I am using YAML for my by changelogs and LQ 4.8.0.

So I’m using a convention for my changeset identifiers (or I was going to!) where I have seperate changelogs for various parts of my system with each change being identified with a number corresponding to the changelog file a dot and then a number for the changset itself so 1.1, 1.2, 1.3 would be changsets within one file and 2.1, 2.2, 2.3 would be changsets in an another file. Each file being brought in by a master changelog that includes them.

However, I started to run into complaints about duplicate identifiers, as far as I could make out LQ was seeing 2.3 and 2.30 as the identifier, that is it was stripping the trailing ‘0’ from the identifier.

## Actual Behavior
Create changeset with a trailing 0 for instance:
- changeSet:
    id: **1.10**
    author: stephen.elves  

Output is:

Running Changeset: dbchangelog.yml::**1.1**::stephen.elves
Liquibase command 'update' was executed successfully.

## Expected/Desired Behavior
Changeset is correctly identfied as 1.10

**Comment by StevenMassaro** [comment]
This issue comes from this forum post: https://forum.liquibase.org/t/liquibase-stripping-trailing-0-characters-from-changset-identitiers/6632

**Comment by StevenMassaro** [comment]
Closing this as it was resolved by wrapping the ID in double quotes, thus causing the YAML interpreter to read it as a string, rather than a number.
