### ISSUE TITLE
Need to suppress extra space generated in resulting scripts of changelog after we ran the changelog against MS SQL Server

### ISSUE THREAD

**Issue by ramchenna** [liquibase/liquibase#2713]
## Environment
Windows 2019

**Liquibase Version**:

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
N/A

**Liquibase Extension(s) & Version**: 
N/A

**Database Vendor & Version**:
MS SQL Server 2019

**Operating System Type & Version**:
Windows 2017

## Description
Hi everyone,

We ran the changelog against our MS SQL Server database and after it ran we checked the scripts that it generated.

Liquibase generated ALTER statements for all the changed Stored Procedure but as there were commented code in the original Stored Procedure in the MS SQL Stored Procedure, the result script did not pickup the commented code and left huge amount of space in the final script generated.

could you please let us know how to SUPPRESS the extra space generated in the generated script during changelot in the generated scripts.

tHANKS
RAM

**Comment by FBurguer** [comment]
Hi! Do you continue to have this issue, if you do, can you share the liquibase command you are using? Thanks

**Comment by FBurguer** [comment]
This issue got stale, closing it for now. Feel free to re-open.
