### ISSUE TITLE
Migration from 3.10.3 to 4.* failed

### ISSUE THREAD

**Issue by peterpivarnik** [liquibase/liquibase#2716]
## Environment

**Liquibase Version**: 4.0.0 - 4.9.1

**Liquibase Integration & Version**:  Spring Boot version 2.5.12, maven version 3.6.3

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: Oracle 19.10.0.0

**Operating System Type & Version**: Linux Mint 20.3 Cinnamon

## Description
After update of Spring Boot from version 2.4.13 (liquibase version 3.10.3) to version 2.5.12 (liquibase version4.3.5), liquibase is failing with exception:
`Failed Liquibase execution for datasource with cause: Validation Failed:
     63 change sets check sum`

Examle of the changeSet:
> 
    <changeSet author="author" id="1551134330735-2">
        <createTable tableName="BRAND">
            <column name="ID" type="BIGINT">
                <constraints primaryKey="true" primaryKeyName="SYS_C0027517"/>
            </column>
            <column name="NUMBER" type="VARCHAR2(255 ${charUnit})"/>
            <column name="SITE_UID" type="VARCHAR2(255 ${charUnit})"/>
            <column name="DELETED" type="BOOLEAN"/>
            <column name="UUID" type="VARCHAR2(255 ${charUnit})"/>
            <column name="VERSION" type="INT"/>
            <column name="DESIGNATION" type="VARCHAR2(255 ${charUnit})"/>
        </createTable>
    </changeSet>

I tried to update to all versions from 4.0.0 to 4.9.1. With all of them there was the same issue.

## Steps To Reproduce
Increase version of spring boot

## Actual Behavior
Failed Liquibase execution for datasource with cause: Validation Failed:
     63 change sets check sum

## Expected/Desired Behavior
Checksum are the same and liquibase update should run with no issue.

**Comment by kataggart** [comment]
Hi @peterpivarnik - Do you have a general estimate of the total number of checksums you have? Is 63 a small number compared to your total or is it a majority/all? Thanks!

**Comment by peterpivarnik** [comment]
Hi @kataggart in total we have 76 changeSets. From this number 63 changeSets have wrong checksum in db. And this is only one microservice. In other microsevices it will be different number.

**Comment by kataggart** [comment]
@peterpivarnik thanks much -- I am guessing you already tested another one of those microservices and are seeing similar behavior? (I am going to work over her a bit with people who know the system better as well to see what we can find out).

**Comment by peterpivarnik** [comment]
@kataggart yes I did tested it on twomicroservices and the behaviour is the same

**Comment by nvoxland** [comment]
Are you able to run with FINE/DEBUG level logging on both versions? Part of the log output should include the string that is being used to compute the checksum.

Looking at your example changeset, I see you have changeset parameters in there. I don't remember if we've had bugfixes around changelog parameters not being correctly expanded for the checksums in the version range you're looking at. If you find the differences in strings being checksummed in the logs, is the difference in the parameter expansion?

**Comment by peterpivarnik** [comment]
Hello @nvoxland ,
I setup the debug logs for the liquibase in my logback.xml in this way:
`    <logger name="liquibase" level="DEBUG"/>`

And then I run application with liquibase version 3.10.3 and after with liquibase version 4.9.1
After that I took informations from log regarding this changeSet:

>     <changeSet author="gros" id="1551134330735-44">
>         <createTable tableName="STORING_ID">
>             <column name="SITE_UID" type="VARCHAR2(255 ${charUnit})">
>                 <constraints primaryKey="true" primaryKeyName="SYS_C0027551"/>
>             </column>
>             <column name="STORING_NUMBER" type="BIGINT"/>
>         </createTable>
>     </changeSet>

Here is the log from running app with liquibase version 3.10.3
```
2022-04-07 16:06:12.633 DEBUG 62846 [//]  [pool-3-thread-1] liquibase.util.MD5Util                   : Computed checksum for createTable:[
    columns=[
        [
            [
                nullable="false"
            ]
            defaultValue="SYS_CONTEXT('POICOVPD#ENV', 'VPDID')"
            name="VPDID"
            type="NUMBER(5,0)"
        ],
        [
            [
                primaryKey="true"
                primaryKeyName="SYS_C0027551"
            ]
            name="SITE_UID"
            type="VARCHAR2(255  char)"
        ],
        [
            name="STORING_NUMBER"
            type="BIGINT"
    ... [truncated in log] as f2d5a36e15ca754079f80df412bb16a5
```

Here is the log from running app with liquibase version 4.9.1
```
2022-04-07 15:55:56.726 DEBUG 57734 [//]  [pool-3-thread-1] liquibase.util                           : Computed checksum for createTable:[
    columns=[
        [
            [
                primaryKey="true"
                primaryKeyName="SYS_C0027551"
            ]
            name="SITE_UID"
            type="VARCHAR2(255  char)"
        ],
        [
            name="STORING_NUMBER"
            type="BIGINT"
        ]
    ]
    tableName="STORING_ID"
] as 94179f14064aa455a251ae117bf7809a
```
I'm running Spring boot application with spring-boot-starter-parent version 2.5.12
Hope this will help, because other tables have more columns and they are truncated in logs.

**Comment by peterpivarnik** [comment]
Hi @nvoxland, @kataggart 
I just found out that we have an extension on our project which was not adapted to liquibase versions highier than 4.0.0. With update of this extension everyhing works as expected. No more validation errors. Thanks for your support. Closing the issue.

**Comment by kataggart** [comment]
@peterpivarnik PHEW!! We were talking on this end a bit about what might be causing that, since others in similar configurations haven't seen it.. thanks for following up! Curious about your extension... it's purpose and your use case. If you had 20 min to chat in the next few weeks? email ktaggart@liquibase.com or https://meetings.hubspot.com/karen-taggart
