### ISSUE TITLE
Liquibase Version 4.9+ not respecting the --schemas flag when generating diffChangeLog

### ISSUE THREAD

**Issue by Cnidarias** [liquibase/liquibase#2717]
## Environment

**Liquibase Version 4.9**:

Databse version:

Tested with both PostgreSQL and MSSQL

## Description

When trying to generate a diff the `--schemas` flag is not being respected. The only schema that is used for generating the diff is the default schema of the login user.

However - when the login's user default schema is something like "schemaA" and the flags doesn't contain "schemaA" then no diff is generated.

## Steps To Reproduce

- Create DB with several schemas
- Create ChangeLog File for all schemas using the `--schemas` flag

## Actual Behavior

- The ChangeLog is only generated for the default scheme of the login user

## Expected/Desired Behavior

- The ChangeLog should include all changes for all schemas specified

**Comment by prashil-sophos** [comment]
We are seeing similar where database.schema property in application.properties in springboot microservice isnt working

**Comment by ecarneiro01** [comment]
@prashil-g This looks like a separate issue, would you mind checking if this still a problem in version 4.11 and open a new issue if it is? Thanks.

**Comment by ecarneiro01** [comment]
The issue persist on PostgreSQL (tested on 14.2). What I noticed is that changing a user's `search_path` doesn't change the behaviour of the diffChangelog command (just generating changesets for the objects in the default schema `public`).

I couldn't reproduce it on MSSQLS 2019 (15.0.4198.2).
