### ISSUE TITLE
Change max value of @Size generates an empty changelog

### ISSUE THREAD

**Issue by Erd89** [liquibase/liquibase#2736]
## Environment

- Liquibase Version: `4.7.1`
- Liquibase Integration & Version: liquibase-maven-plugin `4.7.1`
- Spring boot version: `2.6.3`
- Maven version: `3.8.4`
- Java version: `17`
- Docker image mssql: `2019-CU12-ubuntu-20.04`
- OS: `Manjaro Linux`
- Kernel: `5.16.14-1-MANJARO`

## Description
When I change the `max` property of `@Size`, liquibase does not generate a changelog to increase the size of that type. 

For example, if the type is `String` and the max size is changed from 50 to 100, I expected that the database type changes from `VARCHAR(50)` to `VARCHAR(100)`.

## Steps To Reproduce
1. Create an Entity `House` class with `address` having size `50`.

```java
@Getter
@Setter
@Entity
@Table(name = "house")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class House {

      @Id
      @GeneratedValue(strategy = GenerationType.IDENTITY)
      private long id;
      
      @Size(max = 50)
      @Column(name = "address")
      private String address;

}
```
2. Execute this command
```bash
mvn compile liquibase:diff
```

3. Generate changelog of class `House` :

```xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:pro="http://www.liquibase.org/xml/ns/pro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-4.6.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.6.xsd">
    <changeSet author="exampleuser (generated)" id="1647535634996-1">
        <createTable tableName="house">
            <column name="address" type="varchar(50)"/>
            <column name="id" type="bigint">
                <constraints nullable="false" primaryKey="true" primaryKeyName="housePK"/>
            </column>
        </createTable>
    </changeSet>
</databaseChangeLog>
```

4. Execute the Spring Application in order to create the table 
5. Change the `max size` from 50 to 100:

```java
@Getter
@Setter
@Entity
@Table(name = "house")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class House {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    
    @Size(max = 100)
    @Column(name = "address")
    private String address;
}
```

6. Execute this command
```bash
mvn compile liquibase:diff
```

## Actual Behavior
The generated changelog is empty.

## Expected/Desired Behavior
The changelog contains `modifyDataType`in order to increase the size of `varchar` from 50 to 100
```xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:pro="http://www.liquibase.org/xml/ns/pro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-4.6.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.6.xsd">
    <changeSet author="exampleuser (generated)" id="1645619135834-1">
        <modifyDataType
                columnName="address"
                newDataType="varchar(100)"
                tableName="house"/>
    </changeSet>
</databaseChangeLog>
```

**Comment by kataggart** [comment]
@Erd89 thanks for the excellent detail here! We are reviewing and I will move this through the resolution process. Thanks!

**Comment by TroubleTravis** [comment]
@kataggart Are there any updates on this? Is the suggested method to just manually create the modifyDataType entry in the changelog for now? Thank you for looking into this.

**Comment by frascu** [comment]
It seems that @kataggart no longer works in liquibase.
@StevenMassaro I saw that you are a reviewer in other pull requests. 
Could you help us by tagging someone who can give us news about this issue?

**Comment by StevenMassaro** [comment]
Am I correct in thinking that this is related to [liquibase-hibernate](https://github.com/liquibase/liquibase-hibernate)?

**Comment by frascu** [comment]
Yes, you are

**Comment by StevenMassaro** [comment]
Looks like similar issues have been reported in the hibernate extension for some time:

https://github.com/liquibase/liquibase-hibernate/issues/163

https://github.com/liquibase/liquibase-hibernate/issues/48

I am going to close this issue and merge it with https://github.com/liquibase/liquibase-hibernate/issues/163 in liquibase-hibernate. The hibernate extension is community supported, so a fix would be welcomed for these issues from the community!
