### ISSUE TITLE
Performance regression in liquibase versions greater than 4.3.5

### ISSUE THREAD

**Issue by menacher** [liquibase/liquibase#2756]
## Environment
JDK 17, Mac OS as well as Alpine Docker
**Liquibase Version**:4.9.1

**Liquibase Integration & Version**: spring-boot 2.6.6 version.

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: Postgres

**Operating System Type & Version**: Mac OS and Docker(Azul alpine jdk 11 and 17)

## Description

I start from a clean postgresql database and run my change sets with liquibase version specifically set to 4.3.5, it finishes in less than 40 seconds.
For versions above it including 4.9.1 it takes ~240 seconds to run the same changes against the same clean database.

## Steps To Reproduce

With both versions the spring boot jar is started with `java -jar jar-name.jar` command. The application has *no* other logic, it is only used for initializing the db.

I am attaching an html flame graph html file which profiles the version with 4.9.1. It looks to be taking a lot of time in the logger of all places with the later version.
[out7.html.zip](https://github.com/liquibase/liquibase/files/8485960/out7.html.zip)

**Comment by kataggart** [comment]
Thanks for the details here @menacher - we will take a look

**Comment by nvoxland** [comment]
It looks like the problem is from a second "double check" layer of filtering we have on the log messages to make sure any secure information is filtered out.

In reviewing how well that has worked and the impact it causes, we decided it's not worth the overhead and are taking it out in #2777

**Comment by menacher** [comment]
Thanks for promptly looking into this!

**Comment by artragis** [comment]
Hello,

As we had to upgrade from 3.x branch to 4.10 I also faced the performance issue and even if the logging has a true impact (using a custom logger helps a lot) the main performance issue comes from the memory consumption that has clearly increased. For some of my job, a  bitbucket runner that was taking 5 minutes now takes 1h or failed due to lack of memory.
