### ISSUE TITLE
Schema name not resolved when using sequence in defaultValueComputed

### ISSUE THREAD

**Issue by phlechev** [liquibase/liquibase#2786]
## Environment

**Liquibase Version**:
4.5.0 and above
**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
spring boot
**Database Vendor & Version**:
PostgreSQL

## Description

Since version 4.5.0 the following changeset does not work anymore

```
<createSequence cacheSize="1" cycle="false" dataType="bigint" incrementBy="100" maxValue="9223372036854775807" minValue="1" sequenceName="my_sequence" startValue="10000"/>

<createTable tableName="my_table">
	<column name="id" type="bigint" defaultValueComputed="nextval('my_sequence')">
		<constraints nullable="false" primaryKey="true" primaryKeyName="my_pk"/>
	</column>
</createTable>
```

The following error occurs during table creation: ERROR: relation "my_sequence" does not exist

The sequence is created but it looks like the schema name is not resolved in the expression `nextval('my_sequence')`. 

This works fine in versions 4.4.3 and below

**Comment by phlechev** [comment]
Probably related to #2640 and #2234

**Comment by FBurguer** [comment]
Looks like the issue has been fixed. Prob by this PR  https://github.com/liquibase/liquibase/pull/2812.
