### ISSUE TITLE
Update JDBC drivers to latest releases

### ISSUE THREAD

**Issue by kevin-at-datical** [liquibase/liquibase#2788]
## Description

Upgrade the following JDBC drivers:

- #2797  
- #2464
- #2412
- #2769 
- #2740
- #2790 
- #2421
- #2791 
- #2789 

## Expected/Desired Behavior

Snyk and dependabot do not return any vulnerabilities at any level of severity for the shipped drivers.

**Comment by nvoxland** [comment]
All PRs have been merged
