### ISSUE TITLE
[PostgreSQL] generateChangeLog command generates prefixed schema name with includeSchema flag set to false for Formatted SQL

### ISSUE THREAD

**Issue by szandany** [liquibase/liquibase#2794]
## Environment

**Liquibase Version**: 4.9.1

**Liquibase Integration & Version**: CLI

**Database Vendor & Version**: PostgreSQL

**Operating System Type & Version**: Linux/Unix/Windows

## Description
When running the generateChangeLog command against a PostgreSQL database with includeSchema flag set to false it appears that the resulting generated changeLog contains prefixed schema names in the SQL statements.
This issue only persists with formatted SQL. 

## Steps To Reproduce
Run the `liquibase generateChangeLog` against a PostgreSQL database that contains some objects.
For example:
```sql
liquibase --url=jdbc:postgresql://hostname:5432/mydb?currentSchema=mySchema --username=username --password=password --changeLogFile=myNewChagneLog.postgresql.sql --includeSchema=false generateChangeLog
```

## Actual Behavior
The resulting changeLog contains prefixed schema name in the SQL statements.

## Expected/Desired Behavior
The resulting changelog should not contain any prefixed schema names. 

## Additional context
Here is the original issue from the [Liquibase Community Forum](https://forum.liquibase.org/t/postgresql-generatechangelog-includeschema/6775).

**Comment by kataggart** [comment]
possibly related/duplicate = https://github.com/liquibase/liquibase/issues/2547

**Comment by kataggart** [comment]
possibly related/duplicate https://github.com/liquibase/liquibase/issues/2776
