### ISSUE TITLE
Change set always failed with `preConditions` contained `- foreignKeyConstraintExists` check

### ISSUE THREAD

**Issue by KeyrisXdSnow** [liquibase/liquibase#2796]
## Environment

**Liquibase Version**: 3.9.1 / 3.8.0 (tested for the both version)

**Database Vendor & Version**: mariaDB 2.7.4/ 3.4.0  (tested for the both version)

**Operating System Type & Version**: macOs Monterey ubuntu-18.04 / 12.0.1  (tested for the both version)

## Description
Hi team, 
We recently upgraded our project from version 4.1.0 to 4.9.1 to support changeSets fails logs. 
It's cool feature but in new version changeSets always failed with `preConditions` contained `- foreignKeyConstraintExists` check. Without this check, changeSets are ran successfully. However, this is a big problem for us, since there are quite a lot old changeSets in the system with this check. Now they failed. 

## Steps To Reproduce

List the steps to reproduce the behavior.
- Create database Table **Owner** = [id, name] and  **Dog** =  [id, name, ownerId] by changeSet 1
- Create index  **fk_Dog_Owner_id** for **ownerId** to Owner by changeSet 2
- Create foreignKey  **fk_Dog_Owner_id** for **ownerId** to Owner by changeSet 3
- Try drop foreignKey by changeSet  4 contained
```
      preConditions:
        - onFail: MARK_RAN
        - foreignKeyConstraintExists:
            indexName: fk_Dog_Owner_id
```
- ChangeSet failed

Also to reproduce problem you can clone project [https://github.com/KeyrisXdSnow/LiquibaseForeignKeyError](https://github.com/KeyrisXdSnow/LiquibaseForeignKeyError)

## Actual Behavior
Change set always failed with `preConditions` contained `- foreignKeyConstraintExists` check:
```
apr. 26, 2022 11:46:26 AM liquibase.changelog
INFO: Marking ChangeSet: 2.dropKey.yaml::dropIndex::keyris ran despite precondition failure due to onFail='MARK_RAN': 
          2.dropKey.yaml : Index fk_Dog_Owner_id does not exist
```

## Expected/Desired Behavior
 ChangeSet with tested with -` foreignKeyConstraintExists` check run successfully.
 
```
 Running Changeset: 2.dropKeyWithoutPreCondition.yaml::dropKeyWithoutPreCondition::keyris
apr. 26, 2022 11:48:01 AM liquibase.changelog
INFO: Foreign key fk_Dog_Owner_id dropped
apr. 26, 2022 11:48:01 AM liquibase.changelog
INFO: ChangeSet 2.dropKeyWithoutPreCondition.yaml::dropKeyWithoutPreCondition::keyris ran successfully in 205ms
Running Changeset: 2.dropKeyWithoutPreCondition.yaml::dropIndexWithoutPreCondition.yaml::keyris
apr. 26, 2022 11:48:01 AM liquibase.changelog
INFO: Index fk_Dog_Owner_id dropped from table Dog
apr. 26, 2022 11:48:01 AM liquibase.changelog
INFO: ChangeSet 2.dropKeyWithoutPreCondition.yaml::dropIndexWithoutPreCondition.yaml::keyris ran successfully in 248ms
apr. 26, 2022 11:48:01 AM liquibase.lockservice
INFO: Successfully released change log lock
apr. 26, 2022 11:48:01 AM liquibase.lockservice
INFO: Successfully released change log lock
```

**Comment by HoneyBadgerSeeker** [comment]
Hi, we have the same issue with MariaDB and Liquibase 4.9.1. Even if this was fixed here https://github.com/liquibase/liquibase/issues/2389 it still didn't work. You will find a workaround that worked for us in the thread over here https://github.com/liquibase/liquibase/issues/2389#issuecomment-1088953881. You have to specify the table name in the precondition:

> 
> databaseChangeLog:
> - changeSet:
>     id: changeSetId
>     author: author
>     preConditions:
>       - onFail: MARK_RAN
>       - not:
>         - foreignKeyConstraintExists:
>             foreignKeyName: FK_NAME
>             foreignKeyTableName: TABLENAME <-- here

**Comment by MalloD12** [comment]
Hi @KeyrisXdSnow  I have tried to reproduce this issue, but I couldn't. I tried with on below environment:

## Environment

**Liquibase Version**: 4.17.0

**Database Vendor & Version**: mariaDB 10.2.44

**Operating System Type & Version**: macOS Monterey 12.1

I used changelogs provided on this issue:

- [0.createSchema.yaml](https://github.com/KeyrisXdSnow/LiquibaseForeignKeyError/blob/master/src/main/resources/0.createSchema.yaml)
- [2.dropKey.yaml](https://github.com/KeyrisXdSnow/LiquibaseForeignKeyError/blob/master/src/main/resources/2.dropKey.yaml)

Could you please try again, and share any other detail which can help us to recreate this scenario? In the meantime, I'll close this issue. 

Thanks,
Daniel.
