### ISSUE TITLE
Getting Errror in Liquibase 4.7.1

### ISSUE THREAD

**Issue by vinayr-sharma** [liquibase/liquibase#2811]
## Environment
Windows 10
**Liquibase Version**:
4.7.1
**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
CLI
**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
MySQL 8.0.28
**Operating System Type & Version**:
Windows

## Description

When I am trying to run the Liquibase 4.7.1 I am getting following error
Unexpected error running Liquibase: ALGORITHM=COPY is not supported. Reason: Columns participating in a foreign key are renamed. Try ALGORITHM=INPLACE. 

My Peers who have liquibase version 4.5.0 are not getting this issue. 

Please let me know if you have any questions about this Issue.

## Steps To Reproduce

List the steps to reproduce the behavior.
- Please be precise and ensure private information is redacted
- Include things like
  - Files used - sql scripts, changelog file(s), property file(s), config files, POM Files
  - Exact commands used - CLI, maven, gradle, spring boot, servlet, etc.

## Actual Behavior
A clear and concise description of what happens in the software with the **version used**.
- Include console output if relevant
- Include log files if available.

## Expected/Desired Behavior
A clear and concise description of what happens in the software **after** a fix is created and merged.

**Comment by vinayr-sharma** [comment]
After downgrading to Liquibase 4.5.0 my scripts works fine. Just wanted to provide this information.

**Comment by kataggart** [comment]
@vinayr-sharma Do you know which changeset is causing the issue? Would it be possible for you to run `update-sql` using 4.5 and the higher version that is causing the error and attach? Thanks!

**Comment by kataggart** [comment]
please re-open if needed and you are able to provide the above requested information. Thanks.
