### ISSUE TITLE
Upgrade lock not working correctly due to cache of `ranChangeSetList`

### ISSUE THREAD

**Issue by joggeli34** [liquibase/liquibase#2816]
## Environment

**Liquibase Version**: 4.9.0

**Liquibase Integration & Version**: Quarkus 2.8.1

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: PSQL

**Operating System Type & Version**:

## Description

When creating a liquibase instance and use them for two commands, the lock is not working correctly.

We have following code:

```java
  try (Liquibase liquibase = liquibaseFactory.createLiquibase()) {
          liquibase.validate();
          liquibase.update(liquibaseFactory.createContexts(), liquibaseFactory.createLabels());
  }
```

Following happens:
* Inside the `validate()` method, the `ranChangeSetList` (from `StandardChangeLogHistoryService`) is created and filled with the values from the change log table
* in the `update()` a lock on the table is created
  * the content on the table is not read again, the cached `ranChangeSetList` is used. -> so both services that loaded the `ranChangeSetList` before any change, will try to run the new changesets.
  * So the changesets are run twice

## Steps To Reproduce

Create following code: 

```java
  try (Liquibase liquibase = liquibaseFactory.createLiquibase()) {
          liquibase.validate();
          Thread.sleep(1000);
          liquibase.update(liquibaseFactory.createContexts(), liquibaseFactory.createLabels());
  }
```

Run the code twice in parallel. 

## Actual Behavior

The new changesets will be applied twice.

## Expected/Desired Behavior

The `ranChangeSetList` is revalidated during the duration of the lock, and so the changes are applied only once

**Comment by filipelautert** [comment]
Hi @joggeli34 - just a note that this error only happens when executing 2 processes: if you run 2 threads you get the following error:
Exception in thread "Thread-13" Exception in thread "Thread-12" java.lang.RuntimeException: liquibase.exception.LiquibaseException: java.lang.RuntimeException: Cannot end scope nvazcrkxnr when currently at scope awqeyfxdhb
	at liquibase.dbtest.pgsql.RunnableProblem.run(PostgreSQLIntegrationTest.java:234)
	at java.base/java.lang.Thread.run(Thread.java:829)

Anyway I'm working on that, thanks for the report.

**Comment by filipelautert** [comment]
Hello @joggeli34 

PR https://github.com/liquibase/liquibase/pull/3396 adresses this issue and will fix your scenario. But as you aim for performance, I would suggest another approach as using the current code you will be querying the table twice (one to validate and the second to update). My suggestion would be to manage the lock within your codem thus keeping the cache in memory:

LockService lockService = LockServiceFactory.getInstance().getLockService(liquibase.getDatabase());
try {
	lockService.waitForLock();
	liquibase.validate();
	liquibase.update("test, context-b");
} finally {
	lockService.releaseLock();
}

By holding the lock you will prevent Liquibase from reloading the caches. This code works with current versions of Liquibase, you don't need to wait for the next release with the associated PR to start using it.

**Comment by joggeli34** [comment]
Thanks a lot.

Yes we are using two separate processes (actually multiple docker container starting at the same time), this is when it happened. 

I will add the lock to our custom code, thanks for this suggestion.
