### ISSUE TITLE
include labels attribute is not propagating labels

### ISSUE THREAD

**Issue by blyefd** [liquibase/liquibase#2824]
## Environment
XML

**Liquibase Version**:
4.9.1

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
Postgresql 

**Operating System Type & Version**:
Windows 10

## Description

When using a master changeset and using `<include>` tag with `labels` attribute, the labels are not propagated to the included changesets' `databasechangelog` rows .

## steps to reproduce:
Using three changelog files, a master and two included files.
master.xml:
`<include labels="a" file="include_a.xml"/>`
`<include labels="b" file="include_b.xml"/>`
include_a.xml:
`<changeSet ... />`
include_b.xml:
`<changeSet labels="x" ... />`

sql: `delete * from databasechangelog;`
cli: `liquibase changelog-sync`
sql: `select * from databasechangelog order by orderexecuted;` 

## actual behaviour observed in  `databasechangelog`:
changeset rows from include_a have labels ""
changeset rows from include_b have labels "x"

## expected behaviour:
changeset rows from include_a should have labels "a"
changeset rows from include_b should have labels "b, x"

Related issue: https://github.com/liquibase/liquibase/issues/1813

**Comment by kataggart** [comment]
@blyefd Thanks for the detail. Right now we don't have inheritance in labels, but we are considering it, so this is helpful.

I am curious as well how you are using the labels in the DATABASECHANGELOG -- what problem are they solving for you?

**Comment by blyefd** [comment]
@kataggart  I'm just going by the documentation for the `<include>` tag:
https://docs.liquibase.com/concepts/changelogs/attributes/include.html

Available Attributes
<html>
<body>


labels | `Appends a label to all contained changesets.Note: Labels only work with the <include> tag when referencing non-SQL files.Example: <include file="dbchangelog_roll-forward.xml" labels="rollback_version1"/>` | Optional
-- | -- | --



</body>
</html>

Perhaps I have misunderstood what this attribute means.

**Comment by kataggart** [comment]
You are absolutely correct @blyefd  -- that documentation is not clear - and after talking with a few more people over here I have learned that the include labels inheritance is working functionally, but as you mention above, those labels on the include are not propagating to the DATABASECHANGELOG table.  We will look into the bet way to resolve this -- stay tuned.

I am still curious to learn more about the use case that leads you to need these labels in the DATABAECHANGELOG. I assume it has to do with auditing requirements of some type? Thanks!

**Comment by blyefd** [comment]
@kataggart  Thanks for the update.  I dont have a strong use case for this, other than to use the labels to keep track of features/issues (eg: Jira issue IDs) which necessitated the database schema changes.
