### ISSUE TITLE
Remove version from filenames in LIQUIBASE_HOME/lib

### ISSUE THREAD

**Issue by nvoxland** [liquibase/liquibase#2845]
## Description

Currently, the files in the CLI's lib directory include the version number. That makes it easy to see what version of a JDBC driver or whatever we are shipping, but when users upgrade by unzipping the new liquibase version with a new jdbc driver over the top of an existing installation they end up with two copies.

While long-term we need a more robust solution yet, to handle cases like:
- there is a jar we no longer want to ship
- a library has been renamed
- the user wants to lock to a specific driver version (besides relying on a local `liquibase_libs` dir)

an easy step that solves the majority of the problems is to remove the versioning from the jar files.

## Expected changes

1. No version information on any files in LIQUIBASE_HOME/internal/lib
  a. Example: `h2.jar` instead of `h2-2.0.103.jar`
2. No jars shipped in `LIQUIBASE_HOME/lib`
3. Running `liquibase --version` will output the versions of all the used by Liquibase
  a. Including the correct precedence version if multiple versions are in different locations

**Comment by mcred** [comment]
@nvoxland As a heads up, this will break the ability for LPM to manage these jar files in the `LIQUIBASE_HOME/lib` path, which is can do today. 

```
➜  ~ lpm ls -g
/usr/local/opt/liquibase/libexec/lib/
     Package                                Category
├──  postgresql@42.3.2                      driver
├──  mariadb@2.7.0                          driver
├──  h2@2.1.210                             driver
├──  db2@11.5.6.0                           driver
└──  sqlite@3.34.0                          driver
```

It seem like the better solution when upgrading is to unzip and overwrite existing files. This is how most other CLI utils are upgraded.

**Comment by nvoxland** [comment]
After internal discussion, we decided to move the shipped (now unversioned in the filename) jars to `LIQUIBASE_HOME/shipped/lib`. I updated the description accordingly
