### ISSUE TITLE
Make the "status" command set to verbose by default

### ISSUE THREAD

**Issue by szandany** [liquibase/liquibase#2847]
## Environment

**Liquibase Version**: Any

**Liquibase Integration & Version**: CLI

**Database Vendor & Version**: Any

**Operating System Type & Version**: Any

## Description
Currently, when a user runs the `status` command, they will be able to see if there are any number of undeployed changes if any.
For example:
```bash
liquibase status
Starting Liquibase at 16:43:14 (version 4.10.0 #2501 built at 2022-05-04 14:27+0000)
Liquibase Version: 4.10.0

1 change sets have not been applied to postgres@jdbc:postgresql://tsvi.datical.net:5432/test
Liquibase command 'status' was executed successfully.
```

However, it appears that the user cannot see what changes are currently pending unless they add the `--verbose` option.
For example:
```bash
liquibase status --verbose
Starting Liquibase at 16:43:14 (version 4.10.0 #2501 built at 2022-05-04 14:27+0000)
Liquibase Version: 4.10.0

1 change sets have not been applied to postgres@jdbc:postgresql://tsvi.datical.net:5432/test
         changelog.postgresql.sql::45679-createfunction_get_film_count::SteveZ
Liquibase command 'status' was executed successfully.
```

However, that makes the command become more complex. 
Liquibase support and documentation do advise/encourage users to run the (status)[https://docs.liquibase.com/commands/status/status.html] command with the `--verbose` option for best practices.

## Desired Behavior
It would be beneficial to make the `status` command set to `verbose` by default.  This way users can run the command without having to add the `--verbose` option.  There should probably be an option to disable the `verbose` option if necessary.

**Comment by lbadam** [comment]
@szandany I've tested this on 4.29.1 and I can see the specific changesets that have not been run yet. This is also documented in the `status` [command docs](https://docs.liquibase.com/commands/change-tracking/status.html).
