### ISSUE TITLE
Postgres autoIncrementInformation in snapshot is not correct

### ISSUE THREAD

**Issue by KushnirykOleh** [liquibase/liquibase#2867]
## Environment

**Liquibase Version**: 4.10

**Database Vendor & Version**: [all tested by test-harness](https://github.com/liquibase/liquibase-test-harness#test-harness-support-matrix)

**Operating System Type & Version**: windows 10

## Description
Regardless of what is actually configured for auto increment values for column, snapshot always shows 
```
...
            "autoIncrementInformation": {
              "incrementBy": "1!{java.math.BigInteger}",
              "startWith": "1!{java.math.BigInteger}"
            },
...
```

## Steps To Reproduce
PostgreSQL example:
run SQL similar to what Liquibase generates for [addAutoIncrement test](https://github.com/liquibase/liquibase-test-harness/blob/cc8a0007bb2410f0292113a1def112cae43a289e/src/main/resources/liquibase/harness/change/changelogs/addAutoIncrement.xml#L22-L23) in test harness
```
CREATE TABLE public.autoincrement_test ("intColumn" INTEGER NOT NULL, "dateColumn" date, CONSTRAINT autoincrement_test_pkey PRIMARY KEY ("intColumn"));
CREATE SEQUENCE  IF NOT EXISTS public."autoincrement_test_intColumn_seq" START WITH 100 INCREMENT BY 2;
ALTER TABLE public.autoincrement_test ALTER COLUMN  "intColumn" SET NOT NULL;
ALTER TABLE public.autoincrement_test ALTER COLUMN  "intColumn" SET DEFAULT nextval('public."autoincrement_test_intColumn_seq"');
ALTER SEQUENCE public."autoincrement_test_intColumn_seq" OWNED BY public.autoincrement_test."intColumn";
```
insert few values into the table
```
insert into PUBLIC.autoincrement_test ("dateColumn") values ('2010-07-28');
insert into PUBLIC.autoincrement_test ("dateColumn") values ('2010-07-28');
insert into PUBLIC.autoincrement_test ("dateColumn") values ('2010-07-28');
```
run `select * from PUBLIC.autoincrement_test` and observe values for `intcolumn` are 100, 102, 104. This shows that autoincrement works.
run `liquibase --output-file=mySnapshot.json snapshot --snapshotFormat=json` command against this DB

## Actual Behavior
mySnapshot.json contains 
```
            "autoIncrementInformation": {
              "incrementBy": "1!{java.math.BigInteger}",
              "startWith": "1!{java.math.BigInteger}"
            },
```
for intColumn 

## Expected/Desired Behavior
mySnapshot.json contains incrementBy=2 startWith=100 (106 in case insert queries were ran)

## Additional Context
Discovered in test-harness where [expected json](https://github.com/liquibase/liquibase-test-harness/blob/main/src/main/resources/liquibase/harness/change/expectedSnapshot/addAutoIncrement.json) across all platforms contains   `incrementBy`=1 and `startsWith`=1 even if values in input changelog were different.  Observed for all platforms from [Test-Harness Support Matrix](https://github.com/liquibase/liquibase-test-harness#test-harness-support-matrix) that support `incrementBy` and `startWith` attributes for addAutoIncrement changeType

**Comment by filipelautert** [comment]
Also PR https://github.com/liquibase/liquibase-test-harness/pull/377 adds specific tests for Postgresql.
The refactoring on PR https://github.com/liquibase/liquibase/pull/3361 makes it easier to find out where and how sqls for different databases need to be inserted.
