### ISSUE TITLE
Context from databaseChangeLog is not added to DATABASECHANGELOG

### ISSUE THREAD

**Issue by borisal** [liquibase/liquibase#2883]
## Environment
any (onboarding stage)

**Liquibase Version**:
4.10 and 4.11

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
CLI

**Liquibase Extension(s) & Version**: 
n/a

**Database Vendor & Version**:
MS SQL 2019 1(5.0.4153.1)

**Operating System Type & Version**:
Windows Server 2016/Windows 10

## Description

We want to have a single master change log xml that has <includeAll path="some_folder"/> (so it includes all the change log files from a particular folder, each file has databaseChangeLog element with a context="release-xyz"). Here's an example of a changelog file from that folder (note the use of context). When we run Liquibase with --contexts="Release-2022.3,patch", the file with the correct context is selected but only the change that had patch will have context="Release-2022.3 AND patch" while the rest of the change will have contexts=null. 

<databaseChangeLog context="Release-2022.3"
  xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"  
  xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
		http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.11.xsd
		http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd">

A clear and concise description of the issue being addressed.
- Describe the actual problematic behavior.
- 
The default context from databaseChangeLog is not persisted to DATABASECHANGELOG unless changeSet specifies its own context (so then both the default and the particular context is saves to the table). 

- Ensure private information is redacted.

## Steps To Reproduce
Using CLI:

liquibase update --contexts="XYZ-2022.3,patch"

Master changeset: 
<?xml version="1.0" encoding="UTF-8"?>

<databaseChangeLog changeLogId="master-change-log"
  xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"  
  xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
		http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.11.xsd
		http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd">

				<includeAll path="changelogs"/>	
</databaseChangeLog>

Individual change log file:

<databaseChangeLog context="XYZ-2022.3"
  xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"  
  xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
		http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.11.xsd
		http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd">

	
		
	<changeSet id="XYZ-9866" author="xyzz.zz" runOnChange="false">
		<comment>initial table creation, the default context wont show up in the DATABASECHANGELOG table</comment>
		<sqlFile 
			encoding="utf8"
			path="sql/XYZ-9866_create db.sql"
			relativeToChangelogFile="false"
			splitStatements="true"
			stripComments="true"
		/>		
	</changeSet>

	<changeSet id="zzzz-9867-patch-example" author="zzz.zz" runAlways="false" context="patch" >
		<comment>MPL-2022.3.1 patch this will actually get the default context and the specified context</comment>			
		<sqlFile 
			encoding="utf8"
			path="sql/zzz-9867.sql"
			relativeToChangelogFile="false"
			splitStatements="true"
			stripComments="true"
		/>		
	</changeSet>
	
	
</databaseChangeLog>

## Actual Behavior

Only "zzzz-9867-patch-example" change will have contexts="XYZ-2022.3 AND patch", the other change will have contexts=null but contexts=XYZ-2022.3 should be written to DATABASECHANGELOG table.

**Comment by borisal** [comment]
This will be solved if https://github.com/liquibase/liquibase/pull/2870 is approved and merged.

**Comment by kataggart** [comment]
FYI @nvoxland I moved this directly to code review since it looks like https://github.com/liquibase/liquibase/pull/2870 will likely resolve it.
