### ISSUE TITLE
foreignKeyConstraintExists precondition does not work in Oracle

### ISSUE THREAD

**Issue by dsoneira** [liquibase/liquibase#2893]
## Environment

**Liquibase Version**: 4.9.0

**Liquibase Integration & Version**: Spring Boot

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: Oracle EE 19.3.0

**Operating System Type & Version**: 

## Description

Changesets that use `foreignKeyConstraintExists` as a precondition don't drop the constraint in **Oracle**.
PostgreSQL works fine.

## Steps To Reproduce

```
<changeSet id="create_users_table" author="some_user">
    <createTable tableName="users">
         <column name="id" type="bigint">
            <constraints primaryKey="true" nullable="false" />
        </column>
        <column name="user_id" type="varchar(255)">
            <constraints nullable="false" unique="true" />
        </column>
    </createTable>
    <createSequence sequenceName="sequence_users" startValue="1" incrementBy="1" />
</changeSet>

<changeSet id="create_contacts_table" author="some_user">
    <createTable tableName="contacts">
        <column name="id" type="bigint">
            <constraints primaryKey="true" nullable="false" />
        </column>
        <column name="user_id" type="varchar(50)">
            <constraints nullable="false" referencedTableName="users" referencedColumnNames="user_id" foreignKeyName="fk_contact_user_id" />
        </column>
    </createTable>
    <createSequence sequenceName="sequence_contacts" startValue="1" incrementBy="1" />
</changeSet>

<changeSet id="drop_user_id_fk_constraint_on_contacts" author="some_user">
    <preConditions onFail="MARK_RAN">
        <foreignKeyConstraintExists foreignKeyTableName="contacts" foreignKeyName="fk_contact_user_id"/>
    </preConditions>
    <dropForeignKeyConstraint baseTableName="contacts" constraintName="fk_contact_user_id" />
</changeSet>
```

## Actual Behavior
The precondition fails although the constraint exists, marks the changeSet as RAN and does not drop the foreign key constraint.

## Expected/Desired Behavior
The foreign key should be dropped.

## Additional Context
The problem arose after upgrading Liquibase from `4.6.2` to `4.9.0`

**Comment by FBurguer** [comment]
Following the steps provided, Liquibase droped the foreign key constraint in `4.14`. Myabe upgrading it could fix it? If it does not fix it, let us know and will look into it again. Thanks!

**Comment by alexandru-prigoreanu** [comment]
hello @FBurguer! this issue is still valid in liquibase version 4.22. can you please reopen it? thank you!

**Comment by mammadyahyayev** [comment]
Hello, same for me.

Liquibase version:  4.27.0 
Oracle DB: express:21.3.0-xe
