### ISSUE TITLE
Liquibase-core not able to create snapshot of small  case username/schema name for case-sensitive databases like Oracle

### ISSUE THREAD

**Issue by aayushi095** [liquibase/liquibase#2896]
## Environment
liquibase-core and Oracle Database.
**Liquibase Version**:
From version 3.5.3 to 4.11.0
**Liquibase Integration & Version**: 
spring boot 5.3.19, spring boot 5.3.20
**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
Oracle 12c Windows
**Operating System Type & Version**:
Windows 10

## Description

The issue is with small case database username.
Create a small case user in Oracle using below command:-
`create user "demo" identified by <password> default tablespace users quota unlimited to users.`
By enclosing the username in double-quotes, database will not create it in upper-case.
Give this username in the connection url so that the database will use it as a default catalog name.
After this our code is calling createSnapshot method as described below :-
`SnapshotGeneratorFactory.getInstance().createSnapshot(compareControl.getSchemas(CompareControl.DatabaseRole.REFERENCE), getDatabase(), snapshotControl);`
Inside this function, **getDefaultCatalogName()** method, implemented in **liquibase.database.core.OracleDatabase**, is called which return catalog name in upper case.
`@Override
    public String getDefaultCatalogName() {//NOPMD
        return (super.getDefaultCatalogName() == null) ? null : super.getDefaultCatalogName().toUpperCase(Locale.US);
    }`
And this DBUser in upper-case  doesnot actually exists in database due to which DatabaseChangeLog.getChangeSets() is null.

## Expected/Desired Behavior
getDefaultCatalogName() method implementation should not convert catalog name to upper case. It should make use of isCaseSensitive() method defined in AbstractJdbcDatabase class and return accordingly.

**Comment by aayushi095** [comment]
I have set case-sensitive to true
`((AbstractJdbcDatabase)database).setCaseSensitive(true);`

**Comment by kataggart** [comment]
@aayushi095 We have some folks internally here at Liquibase working on some fixes related to case sensitivity. I will let you know once that gets released. Thanks!

**Comment by kataggart** [comment]
@aayushi095 we do have plans to address this, but unfortunately I am not able to provide a timeline right now.

**Comment by filipelautert** [comment]
Hi @aayushi095 - you may be able to set this parameter using some approaches, but so far none is documented.... Some options would be: 

- Setting ```System.setProperty(GlobalConfiguration.PRESERVE_SCHEMA_CASE.getKey(), "true");```

- Enclosing your code: 
```
  Scope.child(GlobalConfiguration.PRESERVE_SCHEMA_CASE.getKey(), true, () -> {
    //                ...code that wants this true
            });
```

Does that works for you?

**Comment by aayushi095** [comment]
I will check and update.
I really appreciate your help.
Thanks for your response.

**Comment by achoukri47** [comment]
this is still an issue for me ! can anyone explain to me where I can put this code : 

`System.setProperty(GlobalConfiguration.PRESERVE_SCHEMA_CASE.getKey(), "true");`
