### ISSUE TITLE
Introduce "searchPath" setting separate from "classpath"

### ISSUE THREAD

**Issue by nvoxland** [liquibase/liquibase#2916]
## Description

Currently in the CLI (and other places) we have a single argument of "classpath" which we use to configure BOTH the classpath for looking up java drivers and extensions AND the root locations to search for "resources" (changelog files, csv files, etc.). This is not clear to users and causes consternation and confusion. This ticket, along with a doc and --help effort, will work to clear that up with a new option:
- searchPath is used to look up files, to set the base/root for relative pathing to resources, like changelogs.
- classpath is used to look up classes.

The use of "classpath" for both of those brings confusion to end users because even java users don't think of classpath as including where changelogs are searched from and non-java users just get scared and confused of the term classpath.

As part of 4.0, we did the 90% of the code-side work of splitting the two concepts apart but we've not gotten the chance to expose that improvement to end users yet.

We need to work on the integrations to make his available to all of them.

## Requirements

- Add a new searchPath option in defaults files, poms, and other config locations
- official usage is namespaced (liquibase.searchPath) but we silently allow searchPath as well for  consistency with existing properties usages, like url and classpath
- specify these places for testing:
  - liquibase.properties
  - POM.xml
  - ENV vars
  - JAVA system property
- there can be multiple roots to be searched
  - Multiple directories can be separated with `,`
- Allow users to optionally specify the searchPath separately from the classpath. 
- Allow backward compatibility, by not requiring asearchPath
  - if not searchPath provided, use classpath's value for both properties.
- Note: We do allow / as a option as we do with classpath.
- create DOC ticket to explain this property and its specifications

DAT-6806

**Comment by nvoxland** [comment]
In manually testing this, I felt like the "resourcepath" name originally specified felt overly confusing. Why is it not camel cased like one would expect? Why just singular if multiple can be specified? "Path" felt like it specified the resources themselves, not the base/root directories.

So I updated the code and the description to "resourceRoots". If anyone feels strongly that they don't like that term, let me know.

**Comment by kataggart** [comment]
@nvoxland naming as searchPath is agreed name so go forth and conquer!
