### ISSUE TITLE
redshift does not work with 4.11 release

### ISSUE THREAD

**Issue by tooptoop4** [liquibase/liquibase#2928]
see https://stackoverflow.com/a/72447000/8874837 and https://github.com/liquibase/liquibase/pull/2812#issuecomment-1148469330

**Comment by kataggart** [comment]
also from stackoverflow

"
0

Looks like the issue is related to Liquibase version 4.11.0, just use Liquibase v4.10.0
"

**Comment by Tostino** [comment]
I am also getting hit by this with Postgres and 4.11

When running with no --defaultSchemaName I get this in my update-sql:
`-- Changeset baseline/baseline.xml::baseline.global_ext_other::baseline
SET SEARCH_PATH TO global, "$user", global, public;`

When running with --defaultSchemaName=public I get this:
`-- Changeset baseline/baseline.xml::baseline.global_ext_other::baseline
SET SEARCH_PATH TO public, "$user", global, public;`

**Comment by Tostino** [comment]
In your case @akhil-ghatiki, it's erroring because your $user isn't properly quoted. I wonder if that is caused by the representation returned to liquibase, or liquibase changing things on you.

You using Postgres? What does a SHOW search_path; when you open a connection to that database show?

**Comment by akhil-ghatiki** [comment]
@Tostino We are not directly dealing with `$user` in our code. Seems like liquibase is doing it

`Show search_path` return me `$user, public` and we are using redshift

**Comment by adamnmcc** [comment]
yes, getting the same issue on Redshift deployments after upgrading. 

And Brew doesn't have older versions.. will be reverting to 4.10 manually until this is fixed. 

is there no testing on these releases for Redshift?

**Comment by BenGiese22** [comment]
Getting the same issue on Redshift deployments while using the latest image on Dockerhub ( I believe 4.12). 
Upon reverting to 4.10 it worked.

**Comment by kataggart** [comment]
Please see the pr associated with this issue :) We are getting ready to merge it and it will be out in the next release. Thanks!
