### ISSUE TITLE
Offline UpdateSQL for mariadb with csv doesn't handle boolean values correctly ?

### ISSUE THREAD

**Issue by djeanprost** [liquibase/liquibase#2951]
## Environment

**Liquibase Version**: 4.11.0

**Liquibase Integration & Version**: maven

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: MariaDb

**Operating System Type & Version**:

**Infrastructure Type/Provider**: 

## Description

I use maven liquibase plugin to generate SQL from changeset for mariadb.
A couple of changesets use `loadUpdateData` with csv data as input.
The table I try to update contains `boolean `values, which are declared as `'bit'` in mariadb.
The CSV I have contains `'true'` or `'false'` value for values for these columns.
When I generate the SQL in **offline mode** with `mvn liquibase:updateSQL`, I get insert statement with `'true'` or `'false'` values instead of `1` or `0`.

I had a look at [stackoverflow](https://stackoverflow.com/questions/31252711/liquibase-inserting-into-bit-column-mysql-data-too-long-for-column#comment86512560_31252816) where they say that I should add a `column` element with `valueBoolean="true"`, but it doesn't change anything in the offline mode I'm in: I still get `'true'` or `'false'` values for bit column, which are incorrect values.
```
<loadData encoding="UTF-8"
          file="path/to/file.csv"
          separator=","
          tableName="MY_TABLE">
    <!-- specify that values in my_boolean_column should be interpreted as Boolean values -->
    <column name="my_boolean_column" type="BOOLEAN" />
</loadData>
```
```
<plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <configuration>
                    <changeLogFile>${liquibase.dir}/changelog-master.xml</changeLogFile>
                    <url>offline:mariadb?outputLiquibaseSql=true&amp;changeLogFile=${liquibase.offline.dir}/databasechangelog.csv</url>
                    <migrationSqlOutputFile>${liquibase.offline.dir}/upgrade-toto-${project.version}.sql</migrationSqlOutputFile>
                </configuration>
            </plugin>
```

Thank you for your help :)

**Comment by djeanprost** [comment]
I also tried to change the csv data to replace true/false by 1/0, but the generated sql now has '1' or '0' in sql statement instead of 'int' values. It's still not ok.
I tried to add a column element in the loadUpdateData to tell that the column is somehow an interger, it stilldoesn't change anything.
I'm wondering if the online mode is not the problem.

**Comment by kataggart** [comment]
Thanks @djeanprost we are taking a look

if you have five min to spare would love your [input!](https://bit.ly/lbcommsurvey)

**Comment by molivasdat** [comment]
Hi @djeanprost Are you saying that both loadData and loadUpdateData are both broken? 
You reference loadUpdateData in the text but the example you shared has loadData.
Can you share an example set of files that fail for you?

**Comment by djeanprost** [comment]
Hello @molivasdat Indeed the example I gave used loadData, but for my case, I use loadUpdateData. From my point of view I made the hypothesis that the two features work in the same way.
I'll try to give you a sample projet that replicates the problem so that it's easier for you to understand.

**Comment by djeanprost** [comment]
[liquibase-issue-2951.zip](https://github.com/liquibase/liquibase/files/8929048/liquibase-issue-2951.zip)
`If you execute mvn liquibase:updateSQL --Dliquibase.contexts=prod` you will get a generated sql files with 'true'/false values instead of 1/0 values.
