### ISSUE TITLE
Version 4.4.2 Creates Error When Running 'generateChangeLog' Command

### ISSUE THREAD

**Issue by jah-mann** [liquibase/liquibase#2954]
Hello,

I'm using Liquibase as a tool for our DB migration from mssql to postgres, but we're running into a problem. Previously I was using 4.4.0, but tried to upgrade to 4.5.0 due to a bug fix in that release which allows you to create clustered primary keys. This fixed the bug, but now using 4.5.0 (or any later version, including the latest one) I cannot generate a changelog successfully for certain a certain schema in one of my databases. In 4.5.0 in some other versions afterward, I start to get this error:
_Unexpected error running Liquibase: java.lang.NullPointerException_

And in the latest version, 4.11.0, the error looks like this:
_Unexpected error running Liquibase: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because the return value of liquibase.structure.core.StoredDatabaseLogic.getName() is null_

This is happening with the "dbo" schema in one of my SQL Server databases (but not all dbo schemas). The error begins with version 4.4.2. There is one Liquibase Pro issue that was supposedly fixed during this release:
_DAT-6799 Added the ability to handle special characters in procedures when using the generateChangeLog command._

Could DAT-6799 be responsible for something going wrong with generating a changelog when upgrading to that version? There are a lot of stored procedures in that dbo schema, so it seems very possible. Thanks!!

**Comment by kataggart** [comment]
@jah-mann thanks for the details here -- you mention Pro here, wanted to confirm if you are a Pro user using Pro license at this time? Thanks!

**Comment by jah-mann** [comment]
@kataggart thanks for your response! yes, I am a Pro user using a Pro license. the sooner we are able to figure this out for my organization, the better.

**Comment by kataggart** [comment]
@jah-mann great thanks, please submit this via support@liquibase.com as well. I have notified pro support team as well regarding this issue, but sending that email will make sure you get the support based on your subscription. Thanks!

**Comment by jah-mann** [comment]
@kataggart appreciate the help! will do.

**Comment by grh303** [comment]
What was the solution? We have same issue (testing Pro license)
