### ISSUE TITLE
Liquibase 4.7.0 does not quote (some ?) reserved H2 keywords in SQL changeset or where section of update changeset

### ISSUE THREAD

**Issue by sabrasosimis** [liquibase/liquibase#2965]
## Environment

**Liquibase Version**: since 4.7.0, still present in 4.11.0

**Liquibase Integration & Version**:gradle

**Database Vendor & Version**: H2 1.4.200

**Operating System Type & Version**: Linux

## Description
We have some tables who contain fields of type string named 'key' and 'value'.

On liquibase 4.6.2 (and previous ones), the following change sets work correctly

```
 <update tableName="api_step">
      <column name="name" value="Upload"/>
      <where>key = 'upload' and task_id in (select task.id from api_task task where task.definition_key = 'transfer')
      </where>
 </update>

<sql>
      INSERT INTO api_workflow_trigger_parameter(name, value, workflow_trigger_id)
      SELECT 'InstanceUid', 'ppp://InstanceUID', id
      FROM api_workflow_trigger
</sql>
```

After upgrading to liquibase 4.7.0, we get these errors :

```
Column "KEY" not found; SQL statement:
UPDATE PUBLIC.api_step SET name = 'Upload' WHERE key = 'uploadStep' and task_id in (select task.id from api_task task where task.definition_key = 'transfer'

Column "VALUE" not found; SQL statement:
INSERT INTO api_workflow_trigger_parameter(name, value, workflow_trigger_id)
      SELECT 'InstanceUid', 'ppp://InstanceUID', id
      FROM api_workflow_trigger
```

The same change sets work when targeting a PostgreSQL database.

**Comment by kataggart** [comment]
We added KEY and VALUE as reserved words in H2, now that H2 2.0 is out, where those are reserved words. Therefore we are quoting them in your create table statements, which makes them case sensitive. When using them in raw sql, you need to double quote them and use the casing that matches what you have in your database. Please try that and let us know if that works. Thanks

**Comment by consultantleon** [comment]
Since I upgraded from liquibase 4.5.3 to 4.8.0 I notice that column "Value" gets created case sensitive as "Value" column where in the past "Name", "Value" were created as NAME,VALUE not case sensitive.
Does that have to do with this change?
It breaks upwards compatibility for us, is there an advised way to deal with this?
