### ISSUE TITLE
Liquibase Distribution distinction between OSS vs commerical

### ISSUE THREAD

**Issue by sadhasivam** [liquibase/liquibase#3005]
Liquibase Version: 4.12.0
Database Vendor & Version: ALL

## Description

Liquibase product contains both the commercial components as well as the OSS components. The commercial components contain the prohibited AGPL License through some scanners.  

Would there be any choice to have two different release.?

liquibase-oss-4.12.0.tar.gz
liquibase-cc-4.12.0.tar.gz

**Comment by kataggart** [comment]
we are in the process of making this happen... stay tuned!

**Comment by kataggart** [comment]
going to close this issue and will use https://github.com/liquibase/liquibase/issues/2629 to represent the work; will make sure to use that issue to notify back when all the splits are done and available
