### ISSUE TITLE
Trigger Change Types return incorrect error message for CockroachDB 

### ISSUE THREAD

**Issue by alistair-roacher** [liquibase/liquibase#3030]
## Environment

**Liquibase Version**:  Liquibase Pro 4.12.0

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: n/a

**Database Vendor & Version**: CockroachDB v22.1.2

**Operating System Type & Version**: Windows 10 client / Linux database server (Cockroach Cloud)

**Infrastructure Type/Provider**: AWS

## Description

The following change types report an incorrect error message for Cockroach DB :
 pro:createTrigger  
 pro:disableTrigger
 pro:dropTrigger
 pro:enableTrigger
 pro:markUnused
 pro:renameTrigger

Error is: 
  Change Type 'pro:createTrigger' is not allowed for PostgreSQL.

## Steps To Reproduce

Create a CockroachDB cluster
Create a liquibase sql user:
  create user liquibase with password <password>;
  grant all on database defaultdb to liquibase;

Configure liquibase.properties to connect to a CockroachDB cluster:

changelogfile: myChangeLog.xml
driver: org.postgresql.Driver
classpath: ../postgresql-42.2.14.jar
url: jdbc:postgresql://<IP>:26257/defaultdb?sslmode=require
username: liquibase
password: <password>
liquibaseProLicenseKey: <KEY>

Add the following changeset to myChangeLog.xml:

    <changeSet  author="liquibase-docs"  id="addTrigger-example">  
        <pro:createTrigger triggerName="test_trigger" tableName="department" path="my-logic.sql"/>
    </changeSet>

Run "liquibase update" on the command line

## Actual Behavior
liquibase update command fails with the following error:

     1 changes have validation failures
          Change Set ID: addTrigger-example Change Set Author: liquibase-docs
Change Type 'pro:createTrigger' is not allowed for PostgreSQL.

## Expected/Desired Behavior
Error message should be:
Change Type 'pro:createTrigger' is not allowed for CockroachDB.

**Comment by kataggart** [comment]
@alistair-roacher You mention using Liquibase Pro. Are you are a Liquibase Pro customer? If so, can you submit this to support@liquibase.com? There is a dedicated team over there and want to make sure you get the right support. Thanks!

**Comment by kataggart** [comment]
@alistair-roacher checking in to make sure you got the support you needed via the Pro Support? Thanks!

**Comment by FBurguer** [comment]
Closing this issue for now. You can always re-open it if you need anything else. Thanks!
