### ISSUE TITLE
Wrong documentation: contextFilter is not a valid attribute

### ISSUE THREAD

**Issue by danibs** [liquibase/liquibase#3052]
## Environment

**Liquibase Version**: 4.12.0

**Liquibase Integration & Version**: CLI

**Operating System Type & Version**: Ubuntu 20.04

## Description
In file dbchangelog (.xml, .sql, ...) you can use "context" like:
- `changeset foo:123-1 context:prod`
-  `<changeSet author="foo" id="123-1" context="prod">`

Then you can run command:
`liquibase update --contexts="prod"`

In documentation it is written "contextFilter", that is wrong.
https://docs.liquibase.com/concepts/changelogs/attributes/contexts.html

**Comment by TyAssis** [comment]
Hey, @molivasdat!

I think maybe the docs are wrong in other parts too.

I was facing this error when using `contextFilter` in my changeset: 

```cvc-complex-type.3.2.2: Attribute 'contextFilter' is not allowed to appear in element 'changeSet'```

After changing `contextFilter` for `context`, everything worked fine.

**Comment by kataggart** [comment]
@TyAssis sorry for this; docs should be updated soon. The contextFilter alias is going to be in a release very soon.

**Comment by kataggart** [comment]
note: keeping on the team board until docs PR is confirmed merged and built.

https://docs.liquibase.com/concepts/changelogs/attributes/contexts.html?Highlight=context
