### ISSUE TITLE
why docker liquibase，after run  liquibase，Cannot find Changelog.xml

### ISSUE THREAD

**Issue by lovecodeyou** [liquibase/liquibase#3066]
```sh
docker run --rm --volume /www/server/docker_liquibase/lrc_blog3:/liquibase/changelog liquibase/liquibase  --defaultsFile=/liquibase/changelog/liquibase.properties  update --contexts=lrc_blog3 --log-level=info

``` 

![image](https://user-images.githubusercontent.com/38997988/179179426-b9f1b50c-8baa-4cf4-be71-4a6d35cd4734.png)

**Comment by molivasdat** [comment]
Hi @lovecodeyou You are mapping the lrc_blog3 to the changelog directory in the container.
`--volume /www/server/docker_liquibase/lrc_blog3:/liquibase/changelog `
If you map lrc_blog/changeLogDir to the changelog inside the container your command should work and find the files.
`--volume /www/server/docker_liquibase/lrc_blog3/changelogDir:/liquibase/changelog `
You will also need to move lib directory and liquibase.properties file to the changelogDir on the filesystem.

Or you can change your properties file to use /liquibase/changelog/changelogDir/ as the path to the changelog file

**Comment by lovecodeyou** [comment]
hi @molivasdat , If you change according to what you said, is there a bug problem with Docker Liquibase? Because I have no problem with Linux Liquibase with my current file structure, but there is no problem with Windows Liquibase

**Comment by lovecodeyou** [comment]
I solved the problem，Docker Liquibase is really hard to use and it took a lot of trial and error to get it to work with my existing file structure，docker liquibase has Too restrictive，The user experience is poor

```sh
docker run --rm -v /www/server/liquibase/workspace/liquibase_multi_schema_old:/liquibase/changelog -v /www/server/liquibase/workspace/liquibase_multi_schema_old/lib:/liquibase/otherLib liquibase/liquibase  --classpath=/liquibase/changelog:/liquibase/otherLib/mysql-connector-java-8.0.25.jar   update-sql --defaultsFile=/liquibase/changelog/liquibase.properties --contexts=lrc_blog_test1
```
![2022-07-16_021428-tuya](https://user-images.githubusercontent.com/38997988/179287421-6427daf1-f6b8-4c38-9cde-9a0dcbadfaed.png)
