### ISSUE TITLE
Add Support for Snowflake HYBRID tables / SAP HANA Row & Column tables

### ISSUE THREAD

**Issue by MartinRied** [liquibase/liquibase#3067]
## Environment

**Liquibase Version**: 4.12.0

**Liquibase Integration & Version**: maven

**Liquibase Extension(s) & Version**: Snowflake

**Database Vendor & Version**: Snowflake

**Operating System Type & Version**: Windows 11

**Infrastructure Type/Provider**: local

## Description

Snowflake in introducing support for so-called "HYBRID" tables which are geared more towards transactional workloads.
This requires a specific CREATE TABLE syntax: `CREATE HYBRID TABLE ...`

SAP HANA follows a similar approach with ROW and COLUMN tables.

Liquibase currently does - to my knowledge - not support this kind of syntax.

## Steps To Reproduce

None - Liquibase createTable-changes simply cannot generate the SQL shown above for Snowflake.

## Actual Behavior

A createTable change always generates `CREATE TABLE schema.name`

## Expected/Desired Behavior

In my opinion it would make sense to introduce an additional attribute (`tableType`?) to the `createTable` change.
This attribute, if present, would then be included in the SQL generation.

I'm open for alternative suggestions on how to approach this and to implementing this change & creating a PR.

**Comment by FBurguer** [comment]
Hi! We discussed this issue with the team, the conclusion that we reach is that it is hard at this moment to make liquibase work on specific database features that change existing changetypes, we will look into how to improve this on the feature, for this case though we do have a workaround, you can use the tag `<modifySql>` to add HYBRID to the generated sql, more info in this docs [page ](https://docs.liquibase.com/workflows/liquibase-community/modify-sql.html). I hope this helps! Thanks

**Comment by MartinRied** [comment]
Hi @FBurguer ,

Thanks for the feedback - to be honest, I wasn't aware of the "modifySql" option - that should work just fine for my purpose, I'll give it a try to make sure.

Regards,
Martin
