### ISSUE TITLE
the database name is hardcoded into the StartH2CommandStep, why  not reading simply the liquibase.properties file after setting the values ?

### ISSUE THREAD

**Issue by jeejelly** [liquibase/liquibase#3077]
https://github.com/liquibase/liquibase/blame/c9ac055826235eeaad60504a5efe2ca01de16e31/liquibase-core/src/main/java/liquibase/command/core/StartH2CommandStep.java

WTF ?
    try (Connection devConnection = DriverManager.getConnection("jdbc:h2:mem:dev", username, password);
             Connection intConnection = DriverManager.getConnection("jdbc:h2:mem:integration", username, password)) {
             
             
             
             
             in properties files these props are set by the init project :  liquibase.command.url:jdbc:h2:tcp://localhost:8676/mem:mydatabase
             
             but not read by the start-h2 command
             
             while these arer read by start-h2 command but not set by init project : 
             
liquibase.command.init.startH2.bindAddress:localhost
liquibase.command.bindAddress:localhost
liquibase.command.init.startH2.dbPort:4646
liquibase.command.init.startH2.referenceUrl:mem/int
liquibase.command.dbPort:46464
liquibase.command.init.startH2.launchBrowser:on
liquibase.command.init.startH2.password:jee
liquibase.command.init.startH2.username:jee
liquibase.command.init.startH2.webPort:8088

             why not a consistent set of properties for all commands ?
             If the default properties file is set by the init project why all commands have their own set of variables ?

**Comment by kataggart** [comment]
@jeejelly My apologies for not responding sooner. Unfortunately, I am not following what you a.) were doing/use path/user steps, b.) what you were expecting to happen, and c.) what the actual results were that were not what you were expecting

Can you clarify the above so that I can make sure we address the issue? Thanks much!
