### ISSUE TITLE
Not able to connect MSSQL database server from the command line

### ISSUE THREAD

**Issue by premnath413** [liquibase/liquibase#3090]
## Environment

**Liquibase Version**: Starting Liquibase at 12:00:39 (version 4.6.1 #98 built at 2021-11-04 20:16+0000)
Liquibase Version: 4.6.1

**Liquibase Integration & Version**: Windows CMD

**Liquibase Extension(s) & Version**: 4.6.1

**Database Vendor & Version**: MSSQL

**Operating System Type & Version**: Windows 10

**Infrastructure Type/Provider**: windows server

## Description

I am unable to connect to the database server instance from the windows command command line to connect MSSQL remote server Database.

Command line command is :

liquibase --changelog-file=“liquibase\dbchangelog.xml” --driver=com.microsoft.sqlserver.jdbc.SQLServerDriver --url=jdbc:sqlserver://DBASTG001\DBASTG;databaseName=Positional_Data; --username=liquibase --password=liquibase update

I enabled inbound port also in the server UDP 1433, 1434

But I am getting below error:

Unexpected error running Liquibase: Connection could not be created to jdbc:sqlserver://DBASTG001\DBASTG;databaseName=Positional_Data; with driver com.microsoft.sqlserver.jdbc.SQLServerDriver. The connection to the host DBASTG001, named instance \dbastg failed. Error: “java.net.SocketTimeoutException: Receive timed out”. Verify the server and instance names and check that no firewall is blocking UDP traffic to port 1434. For SQL Server 2005 or later, verify that the SQL Server Browser Service is running on the host.

Also from the command line, I am not able to use liquibase --username=liquibase and --password=liquibase  as sql server authentication details.

it is a throwing error:

Unexpected error running Liquibase: Connection could not be created to jdbc:sqlserver://DBASTG001;instanceName=DBASTG;databaseName=Positional_Data;integratedSecurity=false; with driver com.microsoft.sqlserver.jdbc.SQLServerDriver.  Login failed for user 'liquibase'. ClientConnectionId:e90b2883-b07b-4119-a3ad-ce3a4671ebad

Appreciate help:-

**Comment by kataggart** [comment]
@premnath413 you may also want to post this on [the Liquibase Forum](https://forum.liquibase.org/ ) since at first glance it looks like something related to your specific configuration/set-up, not necessarily something in the software itself. Lots of Community folks hang out and help each other out on the Forum, so it's a good spot to also start for help.

**Comment by kataggart** [comment]
@premnath413 were you able to resolve this? Checking in to see if you are still facing the issue. Thanks.

**Comment by kataggart** [comment]
@premnath413 I am going to go ahead and close this and assume you were able to connect. If I am incorrect, and you are still facing the issue, please let me know and we will re-open it. Thanks much!

**Comment by premnath413** [comment]
Please Close this ticket. Ticket is resovled,
