### ISSUE TITLE
Liquibase no longer on the classpath with other libraries that rely on the Jakarta EE 8 version of jaxb-runtime?

### ISSUE THREAD

**Issue by kataggart** [liquibase/liquibase#3115]
With this change I believe that liquibase is now aligned with Jakarta EE 9 and can no longer be on the classpath with other libraries that rely on the Jakarta EE 8 version of jaxb-runtime, was that by design? See this [article](https://www.eclipse.org/community/eclipse_newsletter/2020/november/1.php) for the differences between EE 8 and 9 from a packaging perspective. In my case, if I were to pick up the latest liquibase version, everything that uses jaxb would break because the newer jaxb-runtime -> jaxb-core -> jakarta.xml.bind-api transitive dependency chain will result in the latest Jakarta EE 9 version being on the classpath which contains the wrong api classes.

_Originally posted by @cmuchinsky in https://github.com/liquibase/liquibase/issues/2964#issuecomment-1194677114_

**Comment by cmuchinsky** [comment]
Any thoughts on this issue, should we consider `4.13.0` the final release that supports EE 8?

**Comment by kataggart** [comment]
@cmuchinsky We haven't yet been able to review and confirm. Apologies, we are blessed with a very active user base and backlog :)

**Comment by kataggart** [comment]
This dependency is only used by our CLI, it is not an actual dependency of Liquibase. So you should be okay.. have you tried the newer versions of Liquibase? Thanks!

**Comment by cmuchinsky** [comment]
> This dependency is only used by our CLI, it is not an actual dependency of Liquibase. So you should be okay.. have you tried the newer versions of Liquibase? Thanks!

Thanks for the update, let me give it a try, as long as we don't have any transitive dependency on the CLI we should be OK

**Comment by cmuchinsky** [comment]
@kataggart looks like everything is fine if I stick to using the `liquibase-core` artifact, the update to the `jaxb-runtime` is not pulled in, thanks for the tip!
