### ISSUE TITLE
addDefaultValue fails for CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by baguilarq** [liquibase/liquibase#3117]
## Environment

**Liquibase Version**: 4.14.0

**Liquibase Integration & Version**: None

**Liquibase Extension(s) & Version**:  None

**Database Vendor & Version**: MySQL 5.6.51 (MySQL Community Server (GPL)) (from official Docker image mysql)

**Operating System Type & Version**: Manjaro 21.2.6 (Qonos)

**Infrastructure Type/Provider**: None

## Description

Using `CURRENT_TIMESTAMP` as default value produces incorrect SQL for `addDefaultValue`

## Steps To Reproduce
For an existing table I try to define a default value for a column of type `timestamp`.

```xml
<databaseChangeLog ...>
    <changeSet author="baguilar" id="1">
        <addDefaultValue columnDataType="timestamp" columnName="createdAt" defaultValueDate="CURRENT_TIMESTAMP()"
                         tableName="restrictions" />
    </changeSet>
</databaseChangeLog>
```

## Actual Behavior
The following error occurs:

```
Unexpected error running Liquibase: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NOW()' at line 1 [Failed SQL: (1064) ALTER TABLE app_db.restrictions ALTER createdAt SET DEFAULT NOW()]
```

## Expected/Desired Behavior
The column should have `CURRENT_TIMESTAMP` as default value.

**Comment by MalloD12** [comment]
Hi @baguilarq, 

Thanks for submitting this issue. We have just created a PR to fix this issue. One important thing to mention here is we have noticed is this behaviour is only allowed by MySQL only for version 8. 

Thanks,
Daniel.-
