### ISSUE TITLE
Fix CLI's ability to use logging extensions

### ISSUE THREAD

**Issue by kataggart** [liquibase/liquibase#3126]
## Environment

**Liquibase Version**:

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

**Operating System Type & Version**:

**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc>

## Description

CLI is coded to assume the java logger and will fail if users have custom logging extensions installed.

## Steps To Reproduce

List the steps to reproduce the behavior.
- Please be precise and ensure private information is redacted
- Include things like
  - Files used - sql scripts, changelog file(s), property file(s), config files, POM Files
  - Exact commands used - CLI, maven, gradle, spring boot, servlet, etc.

## Actual Behavior
A clear and concise description of what happens in the software with the **version used**.
- Include console output if relevant
- Include log files if available.

## Expected/Desired Behavior
A clear and concise description of what happens in the software **after** a fix is created and merged.

**Comment by StevenMassaro** [comment]
This was fixed here: https://github.com/liquibase/liquibase/pull/3518
