### ISSUE TITLE
ENUMs on MySQL 8 are returned in the wrong order

### ISSUE THREAD

**Issue by Tantalon** [liquibase/liquibase#3147]
## Environment
**Liquibase Version**: 4.14.0
**Liquibase Integration & Version**: CLI
**Liquibase Extension(s) & Version**: N/A
**Database Vendor & Version**: MySQL 8.0.28
**Operating System Type & Version**:
**Infrastructure Type/Provider**: AWS

## Description

I have a MySQL column from the MySQL employees sample database defined as:
`gender enum('M','F') NOT NULL`

Liquibase generate-changelog has the enum values in the wrong order:
`"type": "ENUM('F', 'M')"`

A diff between MySQL 5.7 and MySQL 8 failed.
On MySQL 5.7.12 they are in the correct order, on MySQL 8 they are in the wrong order.

I checked the [enum retrieval code](https://github.com/liquibase/liquibase/blob/4ab687bfbad3edbd5e4326ffe223602ecaed1577/liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java#L512) and it uses this pattern:
```
SELECT 1 + units.i + tens.i * 10 num
FROM (SELECT 0 AS i UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) units
CROSS JOIN (SELECT 0 AS i UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) tens;
```
On MySQL 5.7 this returns numbers in ascending order: 1, 2, 3, 4...
On MySQL 8 this returns numbers in this order: 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 20, 19, 18, 17...
It's easily fixed with `ORDER BY tens.i, units.i`.

## Steps To Reproduce

List the steps to reproduce the behavior.
- Using MySQL 8
- Create a table with an enum like `create table employees (gender enum('M','F') NOT NULL);`
- Use `liquibase generate-changelog` to a json file

## Actual Behavior
- changelog contains `"type": "ENUM('F', 'M')"`

## Expected/Desired Behavior
- changelog contains `"type": "ENUM('M', 'F')"`

**Comment by kataggart** [comment]
@Tantalon thanks for all the detail here and the PR!
