### ISSUE TITLE
Docker image for arm

### ISSUE THREAD

**Issue by s-titov** [liquibase/liquibase#3154]
Please add liquibase docker image for arm (mac m1) to [docker hub](https://hub.docker.com/r/liquibase/liquibase).

**Comment by kataggart** [comment]
HI @s-titov -- I also recommend you add this as a request to https://github.com/liquibase/docker

Thanks!

**Comment by s-titov** [comment]
@kataggart thanks, issue already exists https://github.com/liquibase/docker/issues/126
