### ISSUE TITLE
Issue with https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.6.xsd

### ISSUE THREAD

**Issue by jazeemilyas** [liquibase/liquibase#3183]
Hi,

All our instances using liquibase is failing to run suddenly in the past 24 hours with the below error. There are no changes done on our side

Error parsing line 4 column 301 of classpath:db.changelog/db.changelog-master.xml: schema_reference.4: Failed to read schema document 'https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.6.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not .

We faced a similar issue couple of months back and it was fixed on Liquibase end.

Please assist

**Comment by adamgolubowski** [comment]
We are experiencing the same issue with http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.9.xsd :
Our application throws error: `Server returned HTTP response code: 403 for URL: http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.9.xsd`
On the other hand I can download the file with my browser. It seems that access is refused from some hosts.

**Comment by davidpgg** [comment]
Is this a repeat of issue 2342?

https://github.com/liquibase/liquibase/issues/2342

**Comment by jazeemilyas** [comment]
I also tried with both http and https. Any solution or workaround ideas?

**Comment by sviluppopg** [comment]
We have the same issue with http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd
Please help :)

**Comment by molivasdat** [comment]
What version of Liquibase are you running? Later versions will find the xsd locally.

**Comment by sviluppopg** [comment]
Liquibase version 3.4.2

**Comment by molivasdat** [comment]
Hi @jazeemilyas @adamgolubowski @davidpgg @sviluppopg , We have fixed the issue.  Can you please try again?
We changed DNS last night.  As an aside another way to fix this issue from occurring in the future is to upgrade from the older version which will look locally for the XSDs too.
3.4.2 was released in 2015.  Glad you are still able to use 7 year old code though.
Changes in version 3.4.2 (2015.11.24)

**Comment by kataggart** [comment]
Thanks for suggestion for folks to upgrade, @molivasdat. Also good to upgrade because of security fixes since then as well.

**Comment by adamgolubowski** [comment]
I confirm that the issue no longer occurs. We can start the application without any errors. In our case we are using liquibase version with xsd files in the package. We found out that we have mismatched versions settings and that seem to cause liquibase to request xsd from the service.
Thank you for your support!

**Comment by sviluppopg** [comment]
Thank you! It works again!

**Comment by srinivasrk** [comment]
Seems to be fixed now. Thanks!

**Comment by kumari-akriti-veriforce** [comment]
Hi I can see this error message in liquibase step Help me resolve this please schema_reference.4: Failed to read schema document 'http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.: Server returned HTTP response code: 403 for URL: http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd -> [Help 1]

**Comment by sviluppopg** [comment]
We have again the same issue with http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd
Please help

**Comment by AlessandroArrigotti** [comment]
Same issue for our legacy server: 

Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd

EDIT: We downloaded the .xsd and pointed at it locally, this worked as a temp fix

**Comment by sviluppopg** [comment]
> Same issue for our legacy server:
> 
> Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd

Hi @AlessandroArrigotti, I wrote to you on LinkedIn. Best regards.
