### ISSUE TITLE
Add a functional test for the new searchPath option

### ISSUE THREAD

**Issue by kevin-atx** [liquibase/liquibase#3192]
As a community, we are doing a great job adding Unit and Integration tests.

However, when adding a new feature or capability, we need to start creating a higher-level functional test that ensures the capability continues to work as the codebase evolves.

This ticket is a request to add a functional test for the searchPath option.

**Comment by kataggart** [comment]
Test setting serarchPath using:
1. liquibase.properties `liquibase.searchPath: path/to/your/resource/root`
2. CLI 'liquibase --search-path=path/to/your/resource/root'   
3. POM.xml
4. ENV vars (for LB Pro) 'LIQUIBASE_SEARCH_PATH=path/to/your/resource/root' (Mac/Linux)
5. JAVA system property

- changelog present outside of working directory where commands are running, LIQUIBASE_HOME/lib, liquibase_libs, and any classpath settings
- run liquibase validate without setting searchPath
- expected result: error, cannot find changelog location
- add searchPath 
- run liquibase validate
- no errors in locating changelog

**Comment by MalloD12** [comment]
There are some existing `searchPath` scenarios already added in [SearchPathRegressionTests](https://github.com/liquibase/liquibase-pro-tests/blob/master/src/test/java/tests/regression/searchPath/SearchPathRegressionTests.java), but there some other from the requested ones here are not. We have created this [ticket](https://datical.atlassian.net/browse/DAT-16342) to keep track of that work.
