### ISSUE TITLE
Before/After/At change prevents adding a column in `FIRST` position on MySQL.

### ISSUE THREAD

**Issue by kataggart** [liquibase/liquibase#3195]
@nvoxland I think your change has prevented me from adding a column in `FIRST` position on MySQL. Previously this appeared to be possible by using `beforeColumn` although I appreciate that this was likely not working. I think there should be a way to specify the first column as that is supported - maybe using `position=0`?

_Originally posted by @mjaggard in https://github.com/liquibase/liquibase/issues/2943#issuecomment-1224219622_

**Comment by kataggart** [comment]
@mjaggard Can you provide a bit more detail regarding the steps you were taking before to get your desired end results and what is happening now? Many thanks!

**Comment by mjaggard** [comment]
> @mjaggard Can you provide a bit more detail regarding the steps you were taking before to get your desired end results and what is happening now? Many thanks!

Certainly. Previously we had a definition like this:
```
<addColumn tableName="my_table">
    <column name="id" type="CHAR(36)" beforeColumn="previous_first_column">
        <constraints nullable="false" primaryKey="true"/>
    </column>
</addColumn>
```

What that **actually** did in real life was create the column at the end of the table, but semantically I'd like to be able to specify the same concept in the definitions though for the future but maybe replacing `beforeColumn="previous_first_column"` with `first="true"` or `position="0"`?

**Comment by kataggart** [comment]
note: MySQL supports first and after column name

enhancement: add position=0 for MySQL resulting in first; only allow position = 0 for mySQL
