### ISSUE TITLE
CompareControl constructor handles input strings incorrectly

### ISSUE THREAD

**Issue by satorg** [liquibase/liquibase#3204]
## Environment

**Liquibase Version**: 4.15.0
**Liquibase Integration & Version**: `liquibase-core` library
**Liquibase Extension(s) & Version**: 
**Database Vendor & Version**: any (DB vendor independent)
**Operating System Type & Version**: any (OS version independent)
**Infrastructure Type/Provider**: JVM

## Description

When I try using this constructor with values like `"aaa.bbb"` for `referenceVsComparisonSchemas` parameter
```
public CompareControl(String[] referenceVsComparisonSchemas, Set<Class<? extends DatabaseObject>> compareTypes)
```
I get incorrect results because of these lines:
https://github.com/liquibase/liquibase/blob/cd2d6b0febfb5c254245b1110a93b679d8f2b5a6/liquibase-core/src/main/java/liquibase/diff/compare/CompareControl.java#L50-L53

In fact, `String.split` expects a **regex** in a first parameter, so calling
```
"aaa.bbb".split(".", 2)
```
results to `["", "aa.bbb"]` which is apparently incorrect.
A correct call would look like
```java
if (referenceSchemaName.contains(".")) {
    referenceCatalogName = referenceSchemaName.split("\\.", 2)[0];
    referenceSchemaName = referenceSchemaName.split("\\.", 2)[1];
}
```
(note double-backslashes before dots)

The same applies to the `comparisonSchemaName` variable handling below in the code.

## Steps To Reproduce

Call
```java
String[] schemas = {"aaa.bbb", "ccc.ddd"};
CompareControl result = new CompareControl(schemas, null);
```

## Actual Behavior

* `result.getSchemaComparisons()[0].getReferenceSchema().getCatalogName()` ==> `""`
* `result.getSchemaComparisons()[0].getReferenceSchema().getSchemaName()` ==> `"aa.bbb"`
* `result.getSchemaComparisons()[0].getComparisonSchema().getCatalogName()` ==> `""`
* `result.getSchemaComparisons()[0].getComparisonSchema().getSchemaName()` ==> `"cc.ddd"`

## Expected/Desired Behavior

* `result.getSchemaComparisons()[0].getReferenceSchema().getCatalogName()` ==> `"aaa"`
* `result.getSchemaComparisons()[0].getReferenceSchema().getSchemaName()` ==> `"bbb"`
* `result.getSchemaComparisons()[0].getComparisonSchema().getCatalogName()` ==> `"ccc"`
* `result.getSchemaComparisons()[0].getComparisonSchema().getSchemaName()` ==> `"ddd"`

## Screenshots (if appropriate)

N/A

## Additional Context

Nope

**Comment by filipelautert** [comment]
Thanks @satorg , this was really broken. Moving around with the fix.
