### ISSUE TITLE
We have alter command in sql : alter table table_name REMOVE PARTITIONING;  How to implement same in liquibase changeset ?

### ISSUE THREAD

**Issue by mpvineela** [liquibase/liquibase#3248]
## Environment

**Liquibase Version**:

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

**Operating System Type & Version**:

**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc>

## Description

A clear and concise description of the issue being addressed.
- Describe the actual problematic behavior.
- Ensure private information is redacted.

## Steps To Reproduce

List the steps to reproduce the behavior.
- Please be precise and ensure private information is redacted
- Include things like
  - Files used - sql scripts, changelog file(s), property file(s), config files, POM Files
  - Exact commands used - CLI, maven, gradle, spring boot, servlet, etc.

## Actual Behavior
A clear and concise description of what happens in the software with the **version used**.
- Include console output if relevant
- Include log files if available.

## Expected/Desired Behavior
A clear and concise description of what happens in the software **after** a fix is created and merged.

**Comment by kataggart** [comment]
@mpvineela Please complete the details requested in the template about Environment, Description, Steps to Reproduce, etc. Thanks
