### ISSUE TITLE
Not able to dynamically substitute value from liquibase.properties file in sql query  

### ISSUE THREAD

**Issue by anuj1366** [liquibase/liquibase#3249]
**Liquibase Version**: 4.15.0

**Database Vendor & Version**:  Auroa serverless v2

**Operating System Type & Version**:   linux

**Infrastructure Type/Provider**: AWS

## Description
Not able to dynamically substitute value from liquibase.properties file in sql query .

## Steps To Reproduce

```
main.changelog.xml
?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
        xmlns:pro="http://www.liquibase.org/xml/ns/pro"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
                http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
                http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd
                http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-latest.xsd">
        <changeSet  id="1"  author="nvoxland">
                <sql>
                          CREATE TABLE trap_config (pattern TEXT NOT NULL, notification_channel TEXT NOT NULL, autofix TEXT, epoch VARCHAR(30) NOT NULL, severity VARCHAR(10) NOT NULL, event_source VARCHAR(100), whitelist TEXT, blacklist TEXT, blacklist_autofix TEXT);
                </sql>
        </changeSet>

        <changeSet  id="2"  author="nvoxland">
                <sql>
                        CREATE USER 'apollo_trap_config_user'@'%' IDENTIFIED BY '${userPassword}' REQUIRE SSL;
                </sql>
        </changeSet>

        <changeSet  id="3"  author="nvoxland">
                <sql>
                        GRANT SELECT, UPDATE, INSERT, DELETE ON apollo.trap_config TO 'apollo_trap_config_user'@'%';
                </sql>
        </changeSet>
</databaseChangeLog>
```

```
liquibase.properties

userPassword=password@1234
```

## Actual Behavior
It is not replacing userPassword value present in properties file in SQL query.

## Expected/Desired Behavior
It should replace userPassword value present in properties file in SQL query.

**Comment by FBurguer** [comment]
We dont support currently the use case of setting a value from the properties file. I think I may know a solution to your problem. Did you try passing the variable in the cmd like `-DuserPassword="password@1234"` Something like this? If this do not fix your problem, we will add this issue as an enhancement request and try to work on it as soon as possible!

**Comment by ddorsett** [comment]
This just got me. The docs need to be fixed: [(https://docs.liquibase.com/concepts/changelogs/property-substitution.html)] definitely reads that property values can be defined in a properties file for substitution
