### ISSUE TITLE
Download URL wrong

### ISSUE THREAD

**Issue by mladenb** [liquibase/liquibase#3283]
On this page: https://www.liquibase.org/download
when you choose Mac/Linux and click on the download button, you'll eventually get redirected to this url:
https://github.com/liquibase/liquibase/releases/download/v4.16.0/liquibase-4.16.1.tar.gz

but, the correct download url is:
https://github.com/liquibase/liquibase/releases/download/v4.16.1/liquibase-4.16.1.tar.gz

(note the zero in the 1st url, instead of one)

**Comment by kataggart** [comment]
thanks for the heads up @mladenb !

**Comment by kataggart** [comment]
@mladenb all fixed! Let us know if you see any other issues. Thanks again for your help!
