### ISSUE TITLE
ChangeSet is not rolled back completely in case of an error for Db2z

### ISSUE THREAD

**Issue by MichaelKern-IVV** [liquibase/liquibase#3299]
## Environment

**Liquibase Version**: 4.15

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: DB2z

**Operating System Type & Version**: Windows 10 Pro

**Infrastructure Type/Provider**:

## Description

Assuming a ChangeSet consists of several steps, among others a CreateTable statement, and an error occurs during execution for any reason, then the entire ChangeSet is rolled back. However, this does not apply to the CreateTable statement and all previous parts of the ChangeSet, these are committed.

If the ChangeSet is executed again after the cause of the error has been corrected, then it fails because the table has already been created.

## Expected/Desired Behavior

The ChangeSet must be rolled back completely, this is not the case for DB2z.

In contrast, it works correctly for DB2luw, among others.

**Comment by nvoxland** [comment]
I see you referenced this in a commit that says it fixes this, @MichaelKern-IVV 

A few questions and comments:
1. You found that does fix it? If so, feel free to open a PR with it :) 
2. What that `supportsDDLInTransaction` flag controls is "are we able to have a transaction going when we try to do DDL?". Most databases are fine with that, even when the statement is auto-committing. But a few databases get angry with it. 
  a. If you are seeing it work for you, do you know if there are some DB2/z versions where it doesn't allow an active transaction during "create table" ? Or was that just incorrectly put in there at some point?

And as an overall question/comment, if you have a changeSet like:

```
<changeSet>
   <createTable tableName="A"...>
   <createTable tableName="B"...>
</changeSet>
```

Liquibase will try to run:
1. create table A
2. create table B
3. insert into databasechangelog

in a single transaction. (Your proposed fix corrects it so we are doing that normal behavior for db2/z).

But, for most databases, "create table" is auto-committing and so you actually end up with 3 transactions, and if B fails it can't roll back create table A, and there is nothing we can do about it.

I thought DB2 LUW followed that auto-commit logic, but you are seeing it not? And does DB2/Z not auto-commit createTable?

For that auto-commit reason, we generally recommend having only one DDL statement per changeSet to be most likely to work across all databases and so maybe even with your fix in place it may not quite work as you are hoping? But I'm still interested in knowing more about db2/z's transaction logic so we can have the behavior as correct as possible.

**Comment by MichaelKern-IVV** [comment]
@nvoxland I created the pull request. #3342

Without having checked it, I think that the behavior for DB2luw is the same as for DB2z 12. In other words, the implementation for DB2luw is correct.
