### ISSUE TITLE
BIGINT with precision doesn't work anymore with H2 database

### ISSUE THREAD

**Issue by MalloD12** [liquibase/liquibase#3300]
## Environment

**Liquibase Version**: `4.16.1`

**Liquibase Integration & Version**: `CLI`

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: `H2 2.1.214`

**Operating System Type & Version**:

**Infrastructure Type/Provider**: Mac OS Monterey 12.1

## Description

Liquibase doesn't translate `BIGINT` (`BOOLEAN`?) field to correct value in H2 database. 

## Steps To Reproduce

<Changelog/Changeset Example>

## Actual Behavior
A clear and concise description of what happens in the software with the **version used**.
- Include console output if relevant
- Include log files if available.

## Expected/Desired Behavior
Column with `BIGINT(xy)` (maybe `BOOLEAN` too) is correctly translated.

**Comment by TomBenjamins** [comment]
here is an example changeset that fails in the latest version of h2 and liquibase:

<changeSet id="CHANGE" author="SOMEONE">
        <createTable tableName="flow_state_variable">
            <column name="id" type="BIGINT(20)" autoIncrement="true">
                <constraints nullable="false" unique="true" primaryKey="true"/>
            </column>
            <column name="uuid" type="VARCHAR(36)">
                <constraints nullable="false" unique="true"/>
            </column>
            <column name="name" type="VARCHAR(60)">
                <constraints nullable="false" unique="true"/>
            </column>
            <column name="description" type="VARCHAR(255)">
                <constraints nullable="false" unique="true"/>
            </column>
        </createTable>
    </changeSet>

**Comment by TomBenjamins** [comment]
it gives the following error:

Reason: liquibase.exception.DatabaseException: Syntax error in SQL statement "CREATE TABLE PUBLIC.flow_state_variable (id BIGINT[*](20) GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid VARCHAR(36) NOT NULL, name VARCHAR(60) NOT NULL, description VARCHAR(255) NOT NULL, CONSTRAINT PK_FLOW_STATE_VARIABLE PRIMARY KEY (id), UNIQUE (id), UNIQUE (uuid), UNIQUE (name), UNIQUE (description))"; 

expected "ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; 

SQL statement:
CREATE TABLE PUBLIC.flow_state_variable (id BIGINT(20) GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid VARCHAR(36) NOT NULL, name VARCHAR(60) NOT NULL, description VARCHAR(255) NOT NULL, CONSTRAINT PK_FLOW_STATE_VARIABLE PRIMARY KEY (id), UNIQUE (id), UNIQUE (uuid), UNIQUE (name), UNIQUE (description)) 

[42001-214] [Failed SQL: (42001) CREATE TABLE PUBLIC.flow_state_variable (id BIGINT(20) GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid VARCHAR(36) NOT NULL, name VARCHAR(60) NOT NULL, description VARCHAR(255) NOT NULL, CONSTRAINT PK_FLOW_STATE_VARIABLE PRIMARY KEY (id), UNIQUE (id), UNIQUE (uuid), UNIQUE (name), UNIQUE (description))]

**Comment by TomBenjamins** [comment]
Please let me know if you need additional information.

greetings,

Tom

**Comment by bhuism** [comment]
+1

**Comment by MalloD12** [comment]
@TomBenjamins / @bhuism  Which Liquibase version are you guys using? I just tried above changeset and it was successfully deployed:

<img width="2279" alt="Screen Shot 2022-09-23 at 4 37 25 PM" src="https://user-images.githubusercontent.com/75833793/192044438-2252f0ef-3850-4c7c-851f-7f06e9870039.png">

**Comment by TomBenjamins** [comment]
Hello Daniel,

the liquibase version used is liquibase-core version 4.16.1 in spring boot, with h2 driver 2.1.214.
The database is an H2 in-memory database.  
As far as I can see on the picture this is a run of our changeset against a Postgres database, not an H2 v2 database.
Our experience is that it does work on mysql as well, but not on H2 v2.

greetings, 

Tom

**Comment by MalloD12** [comment]
Sorry, my bad. Didn't realised I haven't change the DB 😅 .
