### ISSUE TITLE
Liquibase tag command doesn't work properly for SQLite

### ISSUE THREAD

**Issue by AlexanderSashchenko** [liquibase/liquibase#3304]
## Environment

**Liquibase Version**: 4.6.2

**Liquibase Integration & Version**: CLI, test-harness

**Liquibase Extension(s) & Version**: na

**Database Vendor & Version**: 3.34.0

**Operating System Type & Version**: Windows 10

**Infrastructure Type/Provider**: locally  installed instance

## Description

Liquibase tag command tags all existing records in DATABASECHANGELOG table instead of tagging the last record as described in documentation: https://docs.liquibase.com/commands/maintenance/tag.html

## Steps To Reproduce

1) Run several changesets using Liquibase update command against SQLite database which will create several records in databasechangelog table.
2) Run Liquibase tag command against the database.

## Actual Behavior
As a result you will see that all records in databasechangelog table will be tagged.

## Expected/Desired Behavior
Only the last record  in databasechangelog table should be tagged

**Comment by kevin-atx** [comment]
We discussed this in ticket review. Nathan says that multiple DATABASECHANGELOG records can get set when they have the same timestamp (he believes the current time resolution is 1 second). He also says that while this is a bug, rollback by tag should still work correctly.

@AlexanderSashchenko - could you check your DATABASECHANGELOG table and see if that is the situation you're seeing?

**Comment by AlexanderSashchenko** [comment]
Hi @kevin-atx ! You're right. If I wait couple seconds before deploying of next changeset then "tag" command tags the last record in databasechangelog.
