### ISSUE TITLE
How to force the numeric type for the DATABASECHANGELOGLOCK.LOCKED column?

### ISSUE THREAD

**Issue by jigga** [liquibase/liquibase#3311]
I'd like to use liquibase with the [Kinetica database](https://www.kinetica.com/), which is currently unsupported. The problem I face is that this database does not support the BOOLEAN type natively, and I can't find a way to force liquibase to use numeric type for the values in the DATABASECHANGELOGLOCK.LOCKED column.

I'm getting errors as in the screenshot below:

![image](https://user-images.githubusercontent.com/333419/192455397-09e05332-b28c-48f7-b093-8f9dbd678d22.png)

The case is that even the [liquibase docs](https://docs.liquibase.com/concepts/tracking-tables/databasechangeloglock-table.html) for this table says that the standard data type for the LOCKED column is INT.

Kindly advise.

**Comment by FBurguer** [comment]
Hi, thanks for submitting this issue! Liquibase `DATABASECHANGELOGLOCK`.`LOCKED `column is bool by default, so if it doesnt recognize the database, like Kinetica database in this case, it fails, but we have cases like Oracle where the colum is type numeric.
The workaround to this issue is creating the table manually and setting the  `LOCKED` column type to `NUMERIC(1,0)` or something similar. I hope this helps! Im closing this issue, but let us know if this didnt work for you

**Comment by nvoxland** [comment]
You can maybe set the "liquibase.databaseClass" setting to `liquibase.database.core.OracleDatabase`.

That can be set via the cli argument --database-class or any number of other ways depending on how you call liquibase.

**Comment by jigga** [comment]
That did not help, unfortunately. 

I guess the right way to address the issue would be to create a new database class and have it selected automatically when Kinetica is the target database.

**Comment by nvoxland** [comment]
Yes, you can definitely go the custom Database route.

You would create a jar file with:
1. a KineticaDatabase class that extends OracleDatabase
 - have getPriority() return a PRIORITY_DATABASE
 - have isCorrectDatabaseImplementation() return true if it is a kinetica database
2. Create a META-INF/services/liquibase.database.Database file that lists your class's name

then add it to your LIQUIBASE_HOME/lib dir or the liquibase classpath if you are running liquibase in a different way.

**Comment by FBurguer** [comment]
Closing this issue. You can always re-open if you need too! Thanks
