### ISSUE TITLE
Question about "SafeToBuild" label

### ISSUE THREAD

**Issue by nilsreichardt** [liquibase/liquibase#3314]
I saw your security fix in 3278525eaf974daea20808926f9a6816aecd01a7 to prevent running unsafe pull requests. Now you have the solution that a pull request needs the "SafeToBuild" label.

But what is when the label is assigned and the contributor pushes some new changes? Is the "SafeToBuild" label removed? Because the contributor could have pushed some unsafe code, right?

**Comment by kevin-atx** [comment]
For now, we review new code before allowing the build to progress. Yes, we currently don't rebuild the contributor code until we've reviewed and put the label back on the PR. This is a temporary situation that we are in the process of resolving so this will not be needed in the future.

**Comment by nilsreichardt** [comment]
Ok, thanks 👍
