### ISSUE TITLE
Liquibase 4.8.0 breaks backwards compatibility for MS SQLServer timestamp columns

### ISSUE THREAD

**Issue by consultantleon** [liquibase/liquibase#3320]
Yesterday I found the next compatibility breaking change made in liquibase (somewhere after version 4.5.0, we're upgrading our application from liquibase 4.5 to 4.8).

Please consider the pain that such breaking changes cause to liquibase users/embedders and always try to provide a backwards compatibility option (e.g. some configuration option where you can set your desired compatibility level). Every time we upgrade liquibase we've lost significant amounts of time investigating why our schema management fell apart this time. As a result we try not to upgrade liquibase if we do not strictly have to (this time a 'high' whitesource score on all versions below 4.8.0 forced us to upgrade).

Tables previously created with 'timestamp' columns are created as datetime2 now instead of datetime2.

As we have all our tests and documentation based on using the jTDS driver (1.3.1), this causes issues as this driver does not handle the newer datetime2 column type. Instead of returning a long value when we query the column, now we get a detailes ISO formatted date/time string back!

Looking at the code, the following incompatible change is introduced in liquibase 4.8:

In liquibase 4.5.0 I find the following code in `TimestampType`: 

[ line 68 TimestampType.java ]
```java
        if (database instanceof MSSQLDatabase) {
            if (!GlobalConfiguration.CONVERT_DATA_TYPES.getCurrentValue()
                    && originalDefinition.toLowerCase(Locale.US).startsWith("timestamp")) {
                return new DatabaseDataType(database.escapeDataTypeName("timestamp"));
            }
            return new DatabaseDataType(database.escapeDataTypeName("datetime"));
        }
```

i.e. in our case the `if `yields false and `DatabaseDataType `'datetime' is used.

In liquibase 4.8.0 the type is changed to `datetime2 `- without any option to retain a backwards compatible behaviour (!?) : 

[ line 68 TimestampType.java ]
```java
        if (database instanceof MSSQLDatabase) {
            if (!GlobalConfiguration.CONVERT_DATA_TYPES.getCurrentValue()
                    && originalDefinition.toLowerCase(Locale.US).startsWith("timestamp")) {
                return new DatabaseDataType(database.escapeDataTypeName("timestamp"));
            }
            Object[] parameters = getParameters();
            if (parameters.length >= 1) {
                final int paramValue = Integer.parseInt(parameters[0].toString());
                // If the scale for datetime2 is the database default anyway, omit it.
                // If the scale is 8, omit it since it's not a valid value for datetime2
                if (paramValue > 7 || paramValue == (database.getDefaultScaleForNativeDataType("datetime2"))) {
                    parameters = new Object[0];

                }

            }
            return new DatabaseDataType(database.escapeDataTypeName("datetime2"), parameters);
        }
```

(`datetime2 `is returned as the standard type for timestamp columns).

I think I've mentioned it before, but I'm really appalled at the way this is coded. All the '_if specific database checks_' in the generic TimestampType class. Consider refactoring this using IoC pattern (database knows how to deal with the type conversion, not TimestampType ! [IoC](https://en.wikipedia.org/wiki/Inversion_of_control)

**Comment by consultantleon** [comment]
I created a class liquibase.datatype.TimestampTypeMSSQLPatch , with a higher priority and registered it for the service discovery. It seems to function as a good workaround for now. But having all these patches around makes liquibase upgrades even harder to manage, rather have liquibase respect upwards compatibility concerns in the first place.

```java
package liquibase.datatype;

import liquibase.database.Database;
import liquibase.database.core.MSSQLDatabase;
import liquibase.datatype.core.TimestampType;

@DataTypeInfo(name = "timestamp",
              aliases = {"java.sql.Types.TIMESTAMP", "java.sql.Types.TIMESTAMP_WITH_TIMEZONE",
                      "java.sql.Timestamp", "timestamptz"},
              minParameters = 0,
              maxParameters = 1,
              priority = LiquibaseDataType.PRIORITY_DEFAULT + 1)
public class TimestampTypeMSSQLPatch extends TimestampType {
    /**
     * For MSSQL, change the datetime2 datatype to datetime (making things backwards compatible with
     * the liquibase 4.5.0 and earlier behaviour, older JDBC drivers
     * such as jTDS 1.3.1 do not support the datetime2 type and there doesn't seem to be any
     * specific reason to always use datetime2 if no higher precision is needed)
     *
     * @param database database
     * @return either BOOLEAN or SMALLINT type depending on the specific DB2 database version
     */
    @Override
    public DatabaseDataType toDatabaseDataType(Database database) {
        final DatabaseDataType databaseDataType = super.toDatabaseDataType(database);
        final String datetime2TypeEscaped = database.escapeDataTypeName("datetime2");
        if (database instanceof MSSQLDatabase && databaseDataType.getType().equals(
                datetime2TypeEscaped) || databaseDataType.getType().startsWith(
                datetime2TypeEscaped + "(")) {
            final String updatedType = database.escapeDataTypeName("datetime") + databaseDataType
                    .getType()
                    .substring(datetime2TypeEscaped.length());
            databaseDataType.setType(updatedType);
        }
        return databaseDataType;
    }
}
```

**Comment by FBurguer** [comment]
Hi! Did you try upgrading to `4.16.1` our latest version?

**Comment by nvoxland** [comment]
I'm sure it is still behaving the same with 4.16.1. It's a bugfix we want to keep in, where the fix negatively impacted you. 

I understand your frustration in the behavior change, and the base problem is really around how to handle cross-database support. 

With XML tags like createTable, part of the goal is to provide database-independent ways to describe what you want to do vs. specifying the SQL directly yourself. That includes the clauses in the statement, but also what to do with the datatype. If we required people to put in timestamp2 for sqlserver, then when they try to run it against sqlite or something it fails with a "no timestamp2 type". 

So as part of the "tell us what you want and we figure out what you mean" approach createTable etc. takes, we let people specify a "normal" datatype like "timestamp" or "text" and we make sure we use the vendor recommended type for that. In the case of sqlserver, the recommended type is "timestamp2" which is great for the people that want the generic "timestamp" but not for people like you who are looking for specifically "timestamp". 

There are a few ways to better handle this, but it takes some work on how to balance and configure the options while preserving backwards compatibility so it's ended up on the backlog for a while unfortunately. 

Your custom extension is a great solution to it for you. You can also use <modifySql> to force it as well. 

I also created #3325 as the new spot to host discussion and track the larger effort if you'd like to follow that.

**Comment by FBurguer** [comment]
Closing because stale. Feel free to re-open if needed!
