### ISSUE TITLE
changeSet with context specified applies even when no context specified for update execution

### ISSUE THREAD

**Issue by mzatko** [liquibase/liquibase#3395]
## Environment

**Liquibase Version**: 4.7.0

**Liquibase Integration & Version**: 4.7.0

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: any

**Operating System Type & Version**: any

**Infrastructure Type/Provider**: any

## Description

changeSet with context specified applies even when update executed without any context specified

## Steps To Reproduce

specify databaseChangeLog with changeSets like:
```
<changeSet id="dummyId01" context="SpecifiedContext">....</changeSet>
<changeSet id="dummyId02">....</changeSet>
```
1. execute update without --contexts specified:
`liquibase update`

2. execute update with --contexts specified:
`liquibase --contexts="SpecifiedContext" update`

## Actual Behavior
1. both changeSets executed
2. both changeSets executed

## Expected/Desired Behavior
1. **only changeSet not requiring any context will be executed**, means changeSet id="dummyId02" in this case
2. both changeSets executed

## Documentation seems to be confusing on this
https://docs.liquibase.com/concepts/changelogs/attributes/contexts.html :
By default, a database update runs all changesets in the changelog, regardless of what you specify in the CLI. If you add a contextFilter to a changeset, it only runs when you specify that context in the CLI, but unmarked changesets still run. If you do not specify any contexts in the CLI at runtime, every changeset in your changelog runs, even if they have contextFilters attached.

Third sentence contradicts second sentence... Second sentence describes expected/intuitive behavior.

Lot of confusion comes from mixed use of both **context** and **contextFilter** xml attributes in documentation. Are these aliases?

**Comment by mzatko** [comment]
regarding this counter-intuitive behavior. Would it be possible to add some pseudo-context like **nocontext** (or similar name) to execution when no --contexts specified at runtime? So we'll be able to add a check to changeset's/changelog's context  expression?
something like `context="!nocontext AND specificcontext"`

**Comment by FBurguer** [comment]
@mzatko Thats a great idea! In that case, you should make another issue as enhancement request with the exact same thing you just said, so the team and community can give their input about it and look more into it.
