### ISSUE TITLE
VARBINARY datatype is wrongly created as BLOB on DB2 z/OS

### ISSUE THREAD

**Issue by mihaelaDev** [liquibase/liquibase#3408]
## Environment

**Liquibase Version**: 4.12.0

**Liquibase Integration & Version**:  Spring Boot 1.5.22.RELEASE

**Liquibase Extension(s) & Version**:  liquibase-slf4j 4.1.0

**Database Vendor & Version**:  DB2 z/OS 12

**Operating System Type & Version**: RHEL 7

**Infrastructure Type/Provider**: VM

## Description
Given a changeset that creates a new VARBINARY column, the column is created as BLOB although VARBINARY is a supported datatype by DB2 z/OS.
DB2 z/OS 12 reference: https://www.ibm.com/docs/en/db2-for-zos/12?topic=programs-data-types-columns
DB2 z/OS 11 reference: https://www.ibm.com/docs/en/db2-for-zos/11?topic=programs-data-types-columns

## Steps To Reproduce

Using spring boot and given the next change set:
```xml
<changeSet id="1" author="author">
        <createTable tableName="MyTable" tablespace="tableSpace">
            <column name="ID" type="VARCHAR(16)">
                <constraints nullable="false" primaryKey="true" primaryKeyName="PK_MyTable"/>
            </column>
            <column name="COLUMN_A" type="VARBINARY(4096)"/>
            <column name="COLUMN_B" type="VARBINARY(255)"/>
        </createTable>
</changeSet>
```

## Actual Behavior
COLUMN_A and COLUMN_B  columns are created in DB2 as BLOB datatype.
## Expected/Desired Behavior
COLUMN_A and COLUMN_B  columns are created in DB2 as VARBINARY datatype.

**Comment by tabbyf00** [comment]
> Hello, I would like to volunteer to work on this bug. I already started to do a fix on the BlobType class.

Hi there! Liquibase is open source and welcomes community developers!  Here's a link to our guide for how to contribute: https://www.liquibase.org/community/contribute/code

**Comment by mihaelaDev** [comment]
> > Hello, I would like to volunteer to work on this bug. I already started to do a fix on the BlobType class.
> 
> Hi there! Liquibase is open source and welcomes community developers! Here's a link to our guide for how to contribute: https://www.liquibase.org/community/contribute/code

Thanks!
