### ISSUE TITLE
liquibase changelog isuue-- unable to generate liquibase script.

### ISSUE THREAD

**Issue by neesha-panigrahi** [liquibase/liquibase#3409]
Liquibase Version: 4.14.0

Liquibase Integration & Version: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.> CLI- 4.14.0

Liquibase Extension(s) & Version:

Database Vendor & Version: cloudera(hive)-3.1.3000.7.1.7.0-551

Operating System Type & Version:

Infrastructure Type/Provider: <AWC, GCS, Azure, VM, etc>

Description
I tried to execute a liquibase script to create a table in a hive database.
Getting error 'errorMessage:Error while compiling statement: FAILED: SemanticException [Error 10099]: DATETIME type isn’t supported yet. Please use DATE or TIMESTAMP instead), Query: CREATE TABLE DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED datetime, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)).'

Seems the internal tables of liquibase are attempting to use an invalid datatype.

I tried to create DATABASECHANGELOGLOCK and DATABASECHANGELOG manually (replacing with hive valid datatype).
Nonetheless, it tries to recreate those tables and fails with the same error.

**Comment by FBurguer** [comment]
Hi! We already had reports for this kind of issues before. The suggestion I can give for you at this moment is on this [issue](https://github.com/liquibase/liquibase/issues/3311) and create a new database class. This is probably the fastest solution and we will very happy to recive any PR from the community! I hope this helps.

**Comment by FBurguer** [comment]
Hi! Im closing this issue for now. You can always re-open it if you want to adress it on the future! Thanks
