### ISSUE TITLE
Liquibase default value is not honoring for add column if column has nullable constraint for Microsoft Sql Server database

### ISSUE THREAD

**Issue by rajesh1110** [liquibase/liquibase#3417]
## Environment

**Liquibase Version**: 4.9.0 - 4.17.0

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 4.9.0 - 4.17.0

**Database Vendor & Version**: Microsoft SQL Server 2017 and 2019

**Operating System Type & Version**: linux x64

**Infrastructure Type/Provider**: VM

## Description

If we use addColumn to alter table in liquibase, Default value is not honoring and marking new column value in table as NULL. If not null constraint is not defined for the added column. Syntax for the same is as follows. This is only observed in Microsoft SQL Server 2017 and 2019 database.

<addColumn tableName="Student">
			<column name="Section" type="VARCHAR(30)" defaultValue="A" />
		</addColumn>

I observed that SQL being fired for the same is "ALTER TABLE Student ADD Section varchar(30) CONSTRAINT DF_Student DEFAULT 'A'"

Instead of 

ALTER TABLE Student ADD Section varchar(30) CONSTRAINT DF_Student DEFAULT 'A' WITH VALUES;

Microsoft will honor default values only if we provide "WITH VALUES" in case of not null constraint is not defined for column.
## Steps To Reproduce

For Microsoft SQL server 2017 and 2019 databse
Add changeset mentioned below in liquibase changelog.
<addColumn tableName="Student">
			<column name="Section" type="VARCHAR(30)" defaultValue="A" />
		</addColumn>
 Run liquibase CLI
Column will be added in table with values as NULL instead of defined default value.

## Actual Behavior

AddColumn is generating wrong SQL if column is not defined with not null constraint.
<addColumn tableName="Student">
			<column name="Section" type="VARCHAR(30)" defaultValue="A" />
		</addColumn>

ALTER TABLE Student ADD Section varchar(30) CONSTRAINT DF_Student DEFAULT 'A'
## Expected/Desired Behavior
ALTER TABLE Student ADD Section varchar(30) CONSTRAINT DF_Student DEFAULT 'A' WITH VAULES;

**Comment by FBurguer** [comment]
Hi! Thanks for submitting this issue. I wasnt able to reproduce this behavior with the steps provided. Can you share the changelog that is having this issue? Thanks

**Comment by FBurguer** [comment]
Closing this is issue for now. You are welcome to open it again if you need to.
