### ISSUE TITLE
Liquibase 4.0.* version - insert queries sequence and table schema names must be different

### ISSUE THREAD

**Issue by mozcan** [liquibase/liquibase#3437]
## Environment

**Liquibase Version**: 4.11.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

**Operating System Type & Version**:

**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc>

## Description

In insert queries, the table to be inserted and the sequence can be in different schemas . But after version 4.0.* , schemaName information is also used for sequence.

## Actual Behavior

changeSet id="sample-id" author="sample-author" failOnError="true">
        insert tableName="sampleTable" schemaName="SAMPLE_SCHEMA">
            column name="ID" valueSequenceNext="SAMPLE_SEQ"/>
       /insert>
/changeset>

## Expected/Desired Behavior

changeSet id="sample-id" author="sample-author" failOnError="true">
        insert tableName="sampleTable" schemaName="SAMPLE_SCHEMA">
            column name="ID" valueSequenceNext="ANOTHER_SEQ.SAMPLE_SEQ"/>
       /insert>
/changeset>

**Comment by FBurguer** [comment]
Hi! We dont support this feature anymore, that true. There is a workaround though. You can use modify sql to modify that. More info [here](https://docs.liquibase.com/workflows/liquibase-community/modify-sql.html). I hope this helps!
