### ISSUE TITLE
liquibase status different between liquibase/liquibase:4.17 and liquibase/liquibase:4.16 

### ISSUE THREAD

**Issue by wawaberry** [liquibase/liquibase#3442]
## Environment

Docker run liquibase to snowflake

## Steps To Reproduce

docker run -v ${PWD}:/liquibase/changelog liquibase/liquibase:4.17 liquibase status JDBC ARGS
vs

docker run -v ${PWD}:/liquibase/changelog liquibase/liquibase:4.16 liquibase status SAME JDBC ARGS
## Actual Behavior
in Version 4.17 all changesets are unapplied.  yet liquibase history log shows correct status of previously applied changesets
in Version 4.16 only unapplied changesets show in status
## Expected/Desired Behavior
Only unapplied changesets like 4.16 - with same ARGS passed to container

Starting Liquibase at 16:41:20 (version 4.16.1 #4594 built at 2022-09-14 15:27+0000)
Liquibase Version: 4.16.1
Liquibase Community 4.16.1 by Liquibase
[2022-11-04 16:41:23] INFO [liquibase.changelog] Reading from LIQUIBASE_META.DATABASECHANGELOG
3 changesets have not been applied to <<USER>>@jdbc:snowflake://<<ENDPOINT>>
Liquibase command 'status' was executed successfully

Starting Liquibase at 16:41:46 (version 4.17.2 #5255 built at 2022-11-01 18:07+0000)
Liquibase Version: 4.17.2
Liquibase Community 4.17.2 by Liquibase
[2022-11-04 16:41:51] INFO [liquibase.changelog] Reading from LIQUIBASE_META.DATABASECHANGELOG
55 changesets have not been applied to <<USER>>@jdbc:snowflake://<<ENDPOINT>>
Liquibase command 'status' was executed successfully.

**Comment by wawaberry** [comment]
When running with --log-level DEBUG changeset path is different -

4.17.0
changelog/releases/changelog/../v1.10/changesets/dbchangelog-v1.10.xml
4.16.1
changelog/releases/v1.10/changesets/dbchangelog-v1.10.xml

**Comment by kevin-atx** [comment]
We believe this will be addressed by #3413 that's currently in development.

**Comment by wawaberry** [comment]
@kevin-atx  https://github.com/liquibase/liquibase/pull/3355 this looks promising also

**Comment by wawaberry** [comment]
I confirmed this looks resolved in Liquibase Version: 4.18.0
