### ISSUE TITLE
Multithread build on maven fails with goal updateSQL

### ISSUE THREAD

**Issue by piotrwielgolaski-tomtom** [liquibase/liquibase#3446]
## Environment

**Liquibase Version**: 4.17.1

**Liquibase Integration & Version**: maven
**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: offline

**Operating System Type & Version**: Linux

**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc>

## Description

My app is composed of multi modules, I want to get build fast, so I use mvn with option `-T 1C`
When I run updateSQL goal on many modules it fails with errors like this

```
[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:4.17.1:updateSQL (liquibase-install-4-tests) on project xxx-liquibase: Cannot end scope ucuxobkxqd when currently at scope gdwnihdevm -> [Help 1]
[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:4.17.1:updateSQL (liquibase-install-4-tests) on projectyyy-liquibase: Cannot end scope xgzdkkhbwv when currently at scope psiywodkzr -> [Help 1]
```

## Actual Behavior
Fails to build project

## Expected/Desired Behavior
Work with option `-T 1C`

I wonder if using https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/ThreadLocalScopeManager.java would not help this.
I dont see any way in maven to control it.

**Comment by piotrwielgolaski-tomtom** [comment]
it is even more problematic, as when I want to skip liquidbase `-Dliquibase.skip=true` it is still failing

**Comment by piotrwielgolaski-tomtom** [comment]
@FBurguer  I could try to work on PR, but I wonder if you would be ok with changing ScopeManager by default or maybe it should be configuration option?

**Comment by nvoxland** [comment]
@piotrwielgolaski-tomtom I'd be OK with you changing the liquibase-maven-plugin to use the ThreadLocalScopeManager instead of SingletonScopeManager.

In the normal maven case, that shouldn't and in the multithreaded maven case I think the ThreadLocal setup should always make sense. If people find use cases where that doesn't make sense we can reconsider a config setting at that point.

Or, if you find that the way maven manages multi-threading makes more sense to have a different ScopeManager you can do that too.

Forcing ThreadLocalScopeManager (or a different one) on everyone which has otherwise not been used a lot is a bit of risk, but if there are problems it should be immediately obvious.

**Comment by piotrwielgolaski-tomtom** [comment]
I'm using offline DB in few modules and it would help a lot if I could run them in parallel.

**Comment by piotrwielgolaski-tomtom** [comment]
I started to look what it requires to make it work
here you can find my initial finding in form or working code (WIP)
https://github.com/piotrwielgolaski-tomtom/liquibase/commit/aceffa14e341d23fee6e4f77d0f2adde3407742d

in general scope manager requires small finetuning as it should not be forced to run with root scope, each thread should have own root scope otherwise it will idea (sharing root scope means conflicts)

the most challenging part is ChangeLogHistoryServiceFactory that is not scoped, in many places thread reset this factory and it breaks all setup. 
would you agree that first step to make this implementation correct is to make ChangeLogHistoryServiceFactory scoped similar as ExecutorService?

**Comment by piotrwielgolaski-tomtom** [comment]
@nvoxland I created PR only with this change https://github.com/liquibase/liquibase/pull/4023

**Comment by FBurguer** [comment]
Looks like this issue should be closed by the pr. So Im closing it. Thanks!
