### ISSUE TITLE
Mapping of CURRENCY datatype for the H2 database is missing precision and scale

### ISSUE THREAD

**Issue by patrickshaunscott** [liquibase/liquibase#3487]
As of H2 2.0.202, the DECIMAL datatype without parameters has scale 0, thus it cannot hold any value after the decimal point.

https://www.h2database.com/html/migration-to-v2.html

The Liquibase CURRENCY database is being mapped to a DECIMAL datatype with no precision and scale for H2, which causes the values to be stored a whole numbers rather than decimal numbers.

https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/datatype/core/CurrencyType.java

This was not an issue with H2 1.4.200

Using H2 1.4.200:
![image](https://user-images.githubusercontent.com/32497490/202811734-17206963-eb02-4a28-8e22-968ded2b7a3d.png)

Using H2 2.1.214:
![image](https://user-images.githubusercontent.com/32497490/202811763-39ff7096-6632-49a4-a4fa-d54b2fe90e65.png)

**Comment by FBurguer** [comment]
As it was explained in the description, `currency` translate to `decimal` on h2, and decimal doesn suit the `currency` behavior anymore for h2.

**Comment by jccampanero** [comment]
I would love to work on the issue if you don't mind.

Please,  which precision and scale do you consider appropriate for the data type in this case?

**Comment by jccampanero** [comment]
Please, excuse the late reply.

I started working on the issue last night.

I hope to be able to provide a PR soon.

Again, sorry for the late reply.

**Comment by jccampanero** [comment]
Sorry for the late reply, I wasn't able to start working on the issue until last night.

I have provided a possible solution for the problem and created an associated PR so we can discuss the changes made to the code.

Please let me know any additional work that needs to be done.

**Comment by FBurguer** [comment]
Hello! Thank you for your submittion! We will take a look and let you know

**Comment by jccampanero** [comment]
On the contrary, thank you for your excellent library.

I'm afraid I made few changes to the code: please don't hesitate to contact me again if more work is needed to resolve the issue.
