### ISSUE TITLE
Concurrency issue. Randomly supplanted `database` object.

### ISSUE THREAD

**Issue by Dasiu** [liquibase/liquibase#3492]
## Environment

**Liquibase Version**: 4.17.2 (Probably introduced in 3.10)

## Description

I upgraded Liquibase to 4.17.2 from 3.6.3 and stumbled upon what seems to be an issue when running Liquibase in concurrent setup. Migration failed due to exceptions being thrown randomly from within `StandardLockService#init`. Managed to determine based on logs and static analysis that `database` object consumed by `executor` is somehow different than the one used to build given `Liquibase` object in
[https://github.com/liquibase/liquibase/blob/c3c1a537f5ab6fae230b25f0143b899f76192978/liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java#L102](https://github.com/liquibase/liquibase/blob/c3c1a537f5ab6fae230b25f0143b899f76192978/liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java#L102)

I noticed that since 3.10 `ExecutorSerivce` relies on `identityHashCode`:

[https://github.com/liquibase/liquibase/blob/00084c37f8a64d2eebfdd07927e697a23ae9dc99/liquibase-core/src/main/java/liquibase/executor/ExecutorService.java#L36](https://github.com/liquibase/liquibase/blob/00084c37f8a64d2eebfdd07927e697a23ae9dc99/liquibase-core/src/main/java/liquibase/executor/ExecutorService.java#L36)

I suspect that `database` (specifically `Executor`  having different `database`) is supplanted due to hash collision.
## Steps To Reproduce

Intermittent issue. Can not reproduce it.

**Comment by FBurguer** [comment]
Hi! This can probably be solved by changing the scope manager to `ThreadLocalScopeManager`. Let me know if this helps!

**Comment by Dasiu** [comment]
Hi! Thanks for your response!

I used `ThreadLocalScopeManager` and registered it before the very first usage of Liquibase. It seems that `getSingleton` from `Scope.getCurrentScope().getSingleton(ExecutorService.class)` fetches `ExecutorService` from a parent scope first. Root scope is a shared parent to all thread specific scopes, thus instance of `ExecutorService` is shared between threads, thus collision of `System.identityHashCode(database)` may affect migration in concurrent setup :)

**Comment by nvoxland** [comment]
I think this is fixed by #3533
