### ISSUE TITLE
Change set id YAML parsing regression when upgrading to version >= 4.16.0

### ISSUE THREAD

**Issue by aesy** [liquibase/liquibase#3513]
I have a change log file in yaml format which contains a bunch of change sets with unquoted zero-padded id's like this:

```yml
databaseChangeLog:
  - changeSet:
      id: 001
      # ...
  - changeSet:
      id: 008
      # ...
```

In yaml, a number can be prefixed with a zero to be treated as an octal number. Prior to snakeyaml version `1.30`, `001` would be parsed as an `int` and anything with a leading zero and ending with `8` or `9` (which can't be parsed as an octal), such as `008`, would be parsed as a `float` instead resulting in a change set id of `8.0`.  After version `1.30`, `001` would continue to be parsed as an `int`, while `008` would instead be parsed as a `string` resulting in a change set id of `008`.

Liquibase [updated snakeyaml in `4.16.0`](https://github.com/liquibase/liquibase/commit/a3ecd351ae7788389f8063fc88a0a55112db5d5f), which means that when upgrading past `4.16.0` already ran migrations with id's such as `8.0` will no longer match the newer id of `008` which causes these migrations to run again.

A discussion about this regression in snakeyaml can be found [here](https://bitbucket.org/snakeyaml/snakeyaml/issues/550/regression-in-handling-number-like-strings#comment-64094880).

I have completely ignored to mention here that not quoting the id's here was a bad idea from the start :slightly_smiling_face: 

I'm not looking for help, I'm just creating this ticket in case others encounter the same problem and try to search for an existing ticket. Feel free to close this issue.

**Comment by FBurguer** [comment]
Thank you for posting this issue! The only thing I want to add, is that the best workaround, in case you found this kind of issues with snakeyml, is deleting the existing snakeyml jar from  the internal/lib directory and adding a snakeyml jar of the version you see more fit for your project.
