### ISSUE TITLE
Liquibase refused to connect to SQLOracleDB:  IO Error: could not resolve the connect identifier 

### ISSUE THREAD

**Issue by lanvnguyen** [liquibase/liquibase#3523]
## Environment

**Liquibase Version**: 4.17.1

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: SQL Oracle

**Operating System Type & Version**: Linux

**Infrastructure Type/Provider**: Prem Kubernetes

## Description

Liquibase refused to connect to Oracle Database. It was working fine for about 3 weeks. No new changes have been added.

It worked for some consistently with some database instances in our preprod environment but failed to resolve TNS in development and production environments despite matching conditions in each.

Network evaluation showed no traffic to target databases in failed attempts to connect

It appeared that the liquibase container could resolve TNS with some databases, but not others even though the config was the same and separate attempts with SQLplus were successful with the same TNS configuration

**Error code:**
liquibase.exception.DatabaseException:
SEVERE [liquibase.integration] Connection could not be created to jdbc:oracle:thin:wfobjects/@data_engineering_proxy with driver oracle.jdbc.OracleDriver. IO Error: could not resolve the connect identifier

## Steps To Reproduce
Roll back to version 4.2.2 (previous version)

**Comment by lanvnguyen** [comment]
Rolling back to the previous version (4.2.2) resolved the issue so it appears to be related to the current version and/or Oracle driver.

**Comment by FBurguer** [comment]
Hello, can you provide us with the full log output? If there is a lot of sensitive information, its undersatnable that you dont want to share it, but in case you can, you can also send it to my email fburguer@liquibase.com.

**Comment by FBurguer** [comment]
Im closing this issue for now. Feel free to re-open it. Thanks!
