### ISSUE TITLE
Snowflake Implements have error priority

### ISSUE THREAD

**Issue by Yogurt-lei** [liquibase/liquibase#3538]
## Environment

**Liquibase Version**: 4.17.2

**Liquibase Integration & Version**: gradle

**Liquibase Extension(s) & Version**:  hanadb-4.17.2

## Description

In version 4.12.0 support for Snowflake database has been moved from the external extension into the main Liquibase artifact.
but some implements like SequenceSnapshotGeneratorSnowflake , SchemaSnapshotGeneratorSnowflake  have a wrong priority
https://github.com/liquibase/liquibase/blob/256675bca43a089e32c940e10ed8ed7a5f9d66f6/liquibase-core/src/main/java/liquibase/snapshot/SnapshotGeneratorFactory.java#L76-L89

https://github.com/liquibase/liquibase/blob/93f3a7a828f0a683cdf9ead9feb7062358dbf43b/liquibase-snowflake/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGeneratorSnowflake.java#L13-L19

As you can see, **SequenceSnapshotGeneratorSnowflake** will add to **validGenerators** when we use hanadb (other db is ok)

Then when **getNextValidGenerator** we will get **SequenceSnapshotGeneratorSnowflake**

https://github.com/liquibase/liquibase/blob/9ee66e827221fb2a1138d70fe9ee7ceeef02bbac/liquibase-core/src/main/java/liquibase/snapshot/SnapshotGeneratorChain.java#L43

Then when call **getSelectSequenceSql**
https://github.com/liquibase/liquibase/blob/9ee66e827221fb2a1138d70fe9ee7ceeef02bbac/liquibase-core/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java#L43

Then will call **super.getSelectSequenceSql**

https://github.com/liquibase/liquibase/blob/93f3a7a828f0a683cdf9ead9feb7062358dbf43b/liquibase-snowflake/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGeneratorSnowflake.java#L27-L36

Then will throw this exception

https://github.com/liquibase/liquibase/blob/93f3a7a828f0a683cdf9ead9feb7062358dbf43b/liquibase-core/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java#L285

## Steps To Reproduce

Use liquibase version 4.17.2 and hana-ext 4.17.2, and use a liquibase changelog like
``` xml
<changeSet id="create-pkey-sequence" author="test">
        <createSequence sequenceName="tenant_lcm_event_seq" />
    </changeSet>
```

## Actual Behavior

Throw UnexpectedLiquibaseException("Don't know how to query for sequences on hana"); 

## Expected/Desired Behavior

Will create sequence successful

**Comment by FBurguer** [comment]
Hello! thanks for the great issue report, now that you have insight on the matter, can you create a pull request with suggested changes to fiz this issue? Also #3531 this issue may be releated to this.
