### ISSUE TITLE
Improve snapshot performance for DBAAS databases

### ISSUE THREAD

**Issue by nvoxland** [liquibase/liquibase#3546]
## Description

The snapshot process is never as fast as it could be, generally from making too many small queries when it could/should make less queries which each return more rows and/or more complete information.

For databases on a LAN that's not a big problem, but for cloud-based databases the network overhead is so much more it makes a very noticeable difference. For example, snapshotting the databasechangelog table takes about 30 seconds on bigquery.

There are work arounds in the code on when to do bulk queries and when to consider a snapshotted object "complete" but those are not extendable beyond what can be put directly into the code in liquibase-core and therefore cannot be leveraged by cloud-database extensions.

## Steps To Reproduce

Against a bigquery database:
- Run `liquibase update` with a changelog that doesn't have to execute anything
- Run `liquibase snapshot` against schemas of various sizes

## Expected/Desired Behavior

"Runs fast" is always a not-useful "expected behavior". As part of the investigation we need to figure out what can and should be fixed and likely come up with phases of improvement

## Additional Context

Columns are often times the biggest culprit because there are the most of those. From an initial poking around: do we keep re-snapshotting them because LIQUIBASE_COMPLETE is only true if it's not nullable (line 203)? If so, why is that setting based on nullable?

At some point, the whole system was designed more for single-object snapshotting and has gotten overly complex and hard to reason against due to trying to make it even vaguely performant on full-database snapshots. When does it make sense to do a larger overhaul that is more focused on performance and simplicity?

**Comment by filipelautert** [comment]
Reopening - closed incorrectly.
