### ISSUE TITLE
Exception in airgapped environments

### ISSUE THREAD

**Issue by pschrammel** [liquibase/liquibase#3557]
## Environment

**Liquibase Version**: 3.4.1

**Liquibase Integration & Version**: gradle

**Liquibase Extension(s) & Version**: liquibase-modify-column:3.1

**Database Vendor & Version**: postgresql 14.1

**Operating System Type & Version**: linux (debian/ubuntu)

**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc> 

## Description

On starting our service in an airgapped environment liquibase tries to resolve/contact www.liquibase.org, if that fails the server will not start.

## Steps To Reproduce

point www.liquibase.org to localhost

## Actual Behavior

throwing an exception

## Expected/Desired Behavior

don't know as I don't know why the library is calling "home". is this a license check? then it would be nice to give a warning und fall back to some kind of reduced open source functionality.

## Additional Context
Airgapped (even host resolution is limited), but if faking the hostname it would fail later on connection try.

**Comment by pschrammel** [comment]
![image002](https://user-images.githubusercontent.com/27882/206738876-6d769a35-6e7b-48f7-a1f5-0709b0ff0528.png)

**Comment by FBurguer** [comment]
Hello! This looks like it got fixed a few versions ago. Can you try upgrading to our latest version?

**Comment by pschrammel** [comment]
The solution was to use the "http" (with th s in "https") so a local / builtin lookup of the schema was possible.
