### ISSUE TITLE
LiquibaseHub: change log registered but update command still saying no changeID exists

### ISSUE THREAD

**Issue by kshkum** [liquibase/liquibase#3582]
## Environment: Windows 10 Enterprise x64

**Liquibase Version**: Liquibase Version: 4.17.2

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

**Operating System Type & Version**:

**Infrastructure Type/Provider**: 

## Description
Change log registered through 'register-changelog' command, but an 'update' command still shows " WARNING: An API key was configured, but no changelog ID exists. No operations will be reported."

## Steps To Reproduce

$ liquibase register-changelog
####################################################
####################################################
Starting Liquibase at 10:19:50 (version 4.17.2 #5255 built at 2022-11-01 18:07+0000)
Liquibase Version: 4.17.2
Liquibase Community 4.17.2 by Liquibase
Registering a changelog connects Liquibase operations to a Project for monitoring and reporting.
Register changelog changeLog/ChangeLog-Baseline.yml to an existing Project, or create a new one.
Please make a selection:
[c] Create new Project
[1] LBPOC                                    (Project ID:210bf39f-fe0a-4b03-aa2c-0774aexxxxxxxx) 2022-12-14 15:58:13.530106
[2] Project                         (Project ID:fd9cd159-a9fc-4a36-b715-f303xxxxxxxx) 2022-12-14 15:51:38.96449
[N] to not register this changelog right now.
You can still run Liquibase commands, but no data will be saved in your Liquibase Hub account for monitoring or reports.
 Learn more at https://hub.liquibase.com.
? [N]:
1
* Changelog file 'changeLog/ChangeLog-Baseline.yml' with changelog ID '75f47625-973a-47ab-9f1cxxxxxxxxxxxx' has been registered to Project LBPOC
Liquibase command 'register-changelog' was executed successfully.
-----------------
$ liquibase update
####################################################
####################################################
Starting Liquibase at 10:25:17 (version 4.17.2 #5255 built at 2022-11-01 18:07+0000)
Liquibase Version: 4.17.2
Liquibase Community 4.17.2 by Liquibase
WARNING: An API key was configured, but no changelog ID exists.
No operations will be reported. Register this changelog with Liquibase Hub to generate free deployment reports.
Learn more at https://hub.liquibase.com.
Running Changeset: changeLog/ChangeLog-Release-10.sql::DDL_0001::KK
Running Changeset: changeLog/ChangeLog-Release-10.sql::DDL_0002::KK
Running Changeset: changeLog/ChangeLog-Release-10.sql::DDL_0003::KK
Running Changeset: changeLog/ChangeLog-Release-10.sql::DDL_0004::KK
Running Changeset: changeLog/ChangeLog-Release-10-LogicObjects.yml::LOB_0001::KK
Liquibase command 'update' was executed successfully.

## Actual Behavior
change-log registered with project in Liquibase hub but information not being reported. Getting error: 
WARNING: An API key was configured, but no changelog ID exists.
No operations will be reported. Register this changelog with Liquibase Hub to generate free deployment reports.

## Expected/Desired Behavior
Liquibase to report the details of execution to Liquibase Hub.

**Comment by FBurguer** [comment]
Clossing this issue because hub has been decomission
