### ISSUE TITLE
Option to translate empty string values to null for loadData

### ISSUE THREAD

**Issue by awhitford-cip** [liquibase/liquibase#3627]
## Environment

**Liquibase Version**: 4.18

**Database Vendor & Version**:  Snowflake

**Operating System Type & Version**:  Linux

**Infrastructure Type/Provider**: GitHub Actions

## Description

When using [loadData](https://docs.liquibase.com/change-types/load-data.html) to load a `csv` file, empty values are loaded as an _empty_ string, rather than a _null_.

While I am aware that we could change the `csv` file to supply the value `NULL`, and then that will be converted to _null_, it seems odd to me that an _empty string_ is the default behavior.

Adding an extra optional property like `treatEmptyAsNull: true` would maintain backwards compatibility.

**Comment by jimduchek** [comment]
Odd.  I just now did an update to liquibase 4 (4.17.1), from some 3.X version.  For me, it is now treating empty values as nulls when it was _NOT_ before.  (though, on updateData, not loadData -- unsure if the two treat CSVs differently?).  Came across numerous threads (dating back 10+ years) about this... I definitely support having a property to explicitly state what to do with empties in a CSV.

**Comment by mickevrolijk-of** [comment]
As a variant, I need to insert string values 'NULL' (without quotes)  into a not nullable field, which are converted to NULL values.

**Comment by davidecavestro** [comment]
> As a variant, I need to insert string values 'NULL' (without quotes) into a not nullable field, which are converted to NULL values.

I'd be glad to contribute something like an additional attribute for [_LoadDataColumnConfig_](https://github.com/liquibase/liquibase/blob/v4.28.0/liquibase-standard/src/main/java/liquibase/change/core/LoadDataColumnConfig.java), i.e. `<column ... "nullPlaceholder"="myZeroCollisionsNullPlaceholder" />`

If set, any CSV cell having the placeholder value would be translated to a `NULL` value into the db, so leaving the `"null"`/`"NULL"` char sequence as plain text.

This approach could also cover the case of _empty string as null_, i.e. `<column ... "nullPlaceholder"="" />`

Probably changes could be limited to these lines
https://github.com/liquibase/liquibase/blob/43c3827b3d76bd90e971a358d76dd2a7b9e47a81/liquibase-standard/src/main/java/liquibase/change/core/LoadDataChange.java#L324-L334

**Comment by o3bvv** [comment]
Hello!

Is there any chance the support for the null placeholder will be added for `loadUpdateData` too?

Regards
