### ISSUE TITLE
primaryKeyExists precondition crashes when used with H2 2.x

### ISSUE THREAD

**Issue by teppok** [liquibase/liquibase#3643]
## Environment

**Liquibase Version**:

At least 4.9.1 through 4.18.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

Spring boot 2.7.7

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

H2 2.1.214

**Operating System Type & Version**:

Windows 10 20H2

**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc>

## Description

When using primaryKeyExists precondition without tableName attribute, with H2 2.1.214 database, H2 causes Liquibase to crash with an exception. 

## Steps To Reproduce

An example changelog:
```
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
        http://www.liquibase.org/xml/ns/dbchangelog
        http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.3.xsd">


    <changeSet id="test-1" author="tk">
        <createTable tableName="test">
            <column name="id" type="bigint">
                <constraints nullable="false"/>
            </column>
        </createTable>
    </changeSet>

    <changeSet id="test-2" author="tk">
        <preConditions onFail="MARK_RAN">
            <not>
                <primaryKeyExists
                        schemaName="public"
                        primaryKeyName="test_pkey"/>
                <!-- works:
                <primaryKeyExists
                        schemaName="public"
                        tableName="test"
                        primaryKeyName="test_pkey"/>
                -->

            </not>
        </preConditions>

        <addPrimaryKey
                tableName="test"
                schemaName="public"
                constraintName="test_pkey"
                columnNames="id"/>
    </changeSet>
</databaseChangeLog>
```

From the spec, it seems that this is valid pair of changesets, However, when ran on H2, this fails with
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration$LiquibaseConfiguration: Invocation of init method failed; nested exception is liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set db/changelog/changelog-master.xml::test-2::tk:
     Reason: 
          db/changelog/changelog-master.xml : liquibase.precondition.core.PrimaryKeyExistsPrecondition@27e2287c : Invalid value "null" for parameter "table" [90008-214]
```

The culprit seems to be when PrimaryKeyExistsPrecondition calls SnapshotGeneratorFactory, which in turn in the end calls org.h2.jdbc.JdbcDatabaseMetadata.getPrimaryKeys("DB1", "PUBLIC", null). 

It seems that the spec for DatabaseMetadata.getPrimaryKeys https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/DatabaseMetaData.html says that the third parameter shouldn't be null (the other parameters are explicitly said to be nullable), so in a sense H2 crashes because it's just doing what's in the spec. But for example Postgresql's own DatabaseMetadata implementation handles nulls on the third parameter (I guess correctly).

The implementation for getPrimaryKeys was different in H2 1.x, but it changed in 2.x and it crashes now. One solution for this would be to fix this as an improvement in H2.

A very simple spring boot application demonstrating the problem:
[demo.zip](https://github.com/liquibase/liquibase/files/10352230/demo.zip)

## Actual Behavior

[full log.txt](https://github.com/liquibase/liquibase/files/10352366/full.log.txt)

## Expected/Desired Behavior

I guess one of the following resolutions would be ok:
- Figure out the primary keys without using getPrimaryKeys that use null as the third parameter. I don't know if this is possible though. 
- This precondition always fails on databases which don't support the null as third parameter, but it wouldn't crash the migration run.
- Decide to not support this and add documentation to https://docs.liquibase.com/concepts/changelogs/preconditions.html and/or https://docs.liquibase.com/start/install/tutorials/h2.html that in some databases, also tableName is required.
- Assess that this should be fixed in H2 so a bug/improvement can be created there.

**Comment by FBurguer** [comment]
Hi! This is a bug indeed and im adding it to the list of  bugs to fix. It could take some time before we work on it, you can submit a PR if you want to speed up the process. Thanks for the submittion!

**Comment by filipelautert** [comment]
@teppok I create PR https://github.com/liquibase/liquibase/pull/5323 to display a better error message and I'll ask doc people to improve the documentation. Thanks for the issue!
