### ISSUE TITLE
StreamResourceAccessor Feature

### ISSUE THREAD

**Issue by tinakurian-pki** [liquibase/liquibase#3665]
## Environment

**Liquibase Version**:
4.18.0
**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
Maven
**Liquibase Extension(s) & Version**: 
liquibase-postgresql
**Database Vendor & Version**:
postgresql
**Operating System Type & Version**:
Macos Big Sur
**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc>
Running locally via mvn clean install.

## Description
In version 4.16.0, i was able to extend AbstractResourceAccessor in order to run liquibase with a changelog xml as a stream input. When upgrading to version 4.18.0, this no longer works and I get an exception mentioning that the file cannot be found on the search path. I noticed that in the release notes, this is mentioned as a breaking change. Is it possible to add support for having a StreamResourceAccessor?

Here is a copy of my (old and now broken) StreamResourceAccessor:

```
public class StreamResourceAccessor extends AbstractResourceAccessor {

    private String xml;

    public StreamResourceAccessor(String xml) {
        super();
        this.xml = xml;
    }

    @Override
    public InputStreamList openStreams(String relativeTo, String streamPath) {
        InputStreamList list = new InputStreamList();
        InputStream xmlBytesStream = new ByteArrayInputStream(this.xml.getBytes());
        list.add(URI.create(streamPath), xmlBytesStream);
        return list;
    }

    @Override
    public SortedSet<String> list(String relativeTo, String path, boolean recursive, boolean includeFiles,
            boolean includeDirectories) throws IOException {
        return new TreeSet<>();
    }

    @Override
    public List<Resource> search(String path, boolean recursive) throws IOException {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    public List<Resource> getAll(String path) throws IOException {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    public List<String> describeLocations() {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    public void close() throws Exception {
        // TODO Auto-generated method stub

    }
} 
```

**Comment by FBurguer** [comment]
Hello! This issue got stale, so I'm closing it for now. Feel free to re-open it if you need to. Thanks!
