### ISSUE TITLE
Re-enable possibility to copy ChangeLogParameters

### ISSUE THREAD

**Issue by bilak** [liquibase/liquibase#3689]
## Environment

**Liquibase Version**: 4.18.0 vs 4.9.1

## Description

In version 4.9.1 it was possible to copy changeLog parameters between database changeLogs. This was helpful when we wanted to do some comparisons. However this was prohibited with [this commit](https://github.com/liquibase/liquibase/commit/df623ecbb56a595f50bcf3d3526bc3af3767da62). Now the question is if that change was really necessary and if yes what is the approach to copy parameters between DatabaseChangeLogs?

## Steps To Reproduce

```java
final Liquibase liquibase = newLiquibase(changelog, targetDatabase);
if (variables != null) {
    final Liquibase changelogLiquibase = newLiquibase(this.variables, targetDatabase);
    final DatabaseChangeLog databaseChangeLog = changelogLiquibase.getDatabaseChangeLog();
    for (final ChangeLogParameters.ChangeLogParameter parameter
            : databaseChangeLog.getChangeLogParameters().getChangeLogParameters()) {
        liquibase.setChangeLogParameter(parameter.getKey(), parameter.getValue());
    }
}
```

so the for cycle doesn't work anymore. I know I can overcome this with reflection, but it would be nice to have an api to be able to copy parameters. 

## Actual Behavior
copying parameters between DatabaseChangeLog(s) doesn't work

## Expected/Desired Behavior
copying parameters between DatabaseChangeLog(s) works

**Comment by bilak** [comment]
And I guess that should have been an version `5.x` when there's backward incompatible change ;)

**Comment by bilak** [comment]
yes exactly the `setChangeLogParameter()` is missing.

**Comment by MalloD12** [comment]
Hi @bilak,

Where is this method (setChangeLogParameter()) missing? I can still see it available in Liquibase API, and ChangeLogParameters has a `set(key, value)` method to set a new parameter. If you can specify that to me, I think I can quickly fix this issue. 

Thanks,
Daniel.

**Comment by lbadam** [comment]
I'm going to close this issue. Please see [this comment ](https://github.com/liquibase/liquibase/issues/3689#issuecomment-1965253335), retest with a newer version of Liquibase (most recent is 4.29.2) and re-open if this is still an issue.
