### ISSUE TITLE
AddColumn is no longer working with H2 version 1.4.200 in 4.19

### ISSUE THREAD

**Issue by KarolyNevelos** [liquibase/liquibase#3708]
## Environment

**Liquibase Version**: 4.19.0

**Liquibase Integration & Version**: maven

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: H2 1.4.200

**Operating System Type & Version**: Windows 10

**Infrastructure Type/Provider**: VM

## Description

In Liquibase version 4.19.0 with H2 version 1.4.200, during the changelog execution the following error is thrown, when a new column is added: `Cannot add a primary key column`, even when the column is not defined to be a primary key

## Steps To Reproduce

List the steps to reproduce the behavior.
- Update temporarily the H2 version in the liquibase's root pom.xml to 1.4.200
- Execute the runYamlChangelog test of the H2IntegrationTest class

## Actual Behavior
The test fails with the error message:
```
liquibase.exception.ValidationFailedException: Validation Failed:
     1 changes have validation failures
          Cannot add a primary key column, changelogs/yaml/common.tests.changelog.yaml::add-column-test1::alan

```
## Expected/Desired Behavior
- The test is executed successfully even with H2 version 1.4.200
- In general: new columns could be added in case of this H2 version, as it was supported in version 4.18.0

**Comment by filipelautert** [comment]
This problem was introduced by PR https://github.com/liquibase/liquibase/pull/3372

**Comment by marcelhoeh** [comment]
Caused by a wrong check that no longer considers _statement.isPrimaryKey()_ flag for h2:
![image](https://user-images.githubusercontent.com/123158414/213660122-e32a3957-9243-418b-bf3e-6af18af28134.png)
