### ISSUE TITLE
Code Cleanup - Improve empty check style  by using isEmpty String method

### ISSUE THREAD

**Issue by MalloD12** [liquibase/liquibase#3718]
## Description

Improve empty string check by making use of isEmpty string method to make code more readable. Below is an example:

`!"".equals(clause.toString().trim())`

## Steps To Reproduce

This is a type enhancement issue, **NO** steps to reproduce here.

## Actual Behavior
Having comparisons like the one below in the code:
`!"".equals(clause.toString().trim())`

## Expected/Desired Behavior
Do string empty checks by doing something like `clause.toString().trim().isEmpty()`

## Screenshots (if appropriate)
- None

## Additional Context
- None

**Comment by Jeevananthammoorthy** [comment]
Hi  Mallo

I like to contribute to this bug and Am new to github opensource. Can you help me to kick start.

Thanks.

**Comment by MalloD12** [comment]
> Hi Mallo
> 
> I like to contribute to this bug and Am new to github opensource. Can you help me to kick start.
> 
> Thanks.

Hi @Jeevananthammoorthy, this is not really a bug it's an enhancement to improve a bit more readability of our code. If you are happy to take this enhancement you are more than welcome to do it. You can clone the repo, create your own branch (ideally name it with the issue id or a descriptive name), and then search and update all the occurrences we have in the code for a comparison like the one mentioned in this ticket.  

Thanks,
Daniel.

**Comment by Jeevananthammoorthy** [comment]
Hi @MalloD12  Sure, will raise the PR as early as possible.

**Comment by MalloD12** [comment]
> Hi @MalloD12 Sure, will raise the PR as early as possible.

Appreciate it.

**Comment by Jeevananthammoorthy** [comment]
@MalloD12  Kindly find the PR: https://github.com/liquibase/liquibase/pull/3804
Need your approval to pass the build check fir the below error
 `A member of Liquibase team needs to apply label 'SafeToBuild'! `

**Comment by Jeevananthammoorthy** [comment]
@MalloD12  Update the PR, Kindly do the review https://github.com/liquibase/liquibase/pull/3804

Thanks,
Jeevanantham.

**Comment by Jeevananthammoorthy** [comment]
@MalloD12  Updated the PR, Kindly do the review.

Thanks,
Jeevanantham.

**Comment by Jeevananthammoorthy** [comment]
@MalloD12  Gentle reminder, to review the PR.
Thanks,
Jeevanantham.

**Comment by Jeevananthammoorthy** [comment]
@MalloD12  I noticed, you've made additional changes. Not sure what went wrong on my changes. Can you help to understand?

Thanks,
Jeevanantham.

**Comment by MalloD12** [comment]
Yeap, as part of the review one of the team members pointed out we don't use `org.apache.commons.lang3.StringUtils`, we use `import liquibase.util.StringUtil`. So basically, I replaced `isEmpty()`, `isBlank()` and `isNotBlank()` calls to make use of our String methods and don't need to rely on another dependency. 

Also, as a heads up for some reason, there are some unit tests still failing and I need a bit more time to investigate this, but also have some other priorities. I'll do my best to resume this work during this sprint. 

Thanks,
Daniel.

**Comment by Jeevananthammoorthy** [comment]
@MalloD12  Thanks for the clarification, This is my first PR towards opensource, missed to notice on the stringUtil package . will learn things on the go. Let me know what should be my next step.

Thanks,
Jeevanantham
