### ISSUE TITLE
dbDoc failes with java.io.FileNotFoundException if the filed name in a table  includes an / in SQL server

### ISSUE THREAD

**Issue by ClaesCodePilot** [liquibase/liquibase#3753]
## Environment

**Liquibase Version** :4.16.1

**Liquibase Integration & Version**: Maven 3.8.6

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**:Microsoft SQL Server 2019

**Operating System Type & Version**: Windows 2012

**Infrastructure Type/Provider**: Windows

## Description
When Runnig maven goal dbDoc and one table has an filed name that includes an / the DB doc fails with  java.io.FileNotFoundException 

## Steps To Reproduce
Create a table in SQL server

CREATE TABLE DBDOCISSUE
(
[TheIssue/TheProblem] VARCHAR(5)
)

Run the maven goal
mvn liquibase:dbDoc  + the rest of parameters

The error will be:
[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:4.16.1:dbDoc (default-cli) on project fdp-db-adaptations-tcm:
[ERROR] Error setting up or running Liquibase:
[ERROR] java.io.FileNotFoundException: c:\temp\dbDoc\columns\dbo.dbdocissue.theissue\theproblem.html (The system cannot find the path specified)

I does not matter if the table creation script is in a change log or not. As long as the table exists in the database the error will come

## Actual Behavior
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  51.692 s
[INFO] Finished at: 2023-01-31T12:22:23+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:4.16.1:dbDoc (default-cli) on project fdp-db-adaptations-tcm:
[ERROR] Error setting up or running Liquibase:
[ERROR] java.io.FileNotFoundException: c:\temp\dbDoc\columns\dbo.dbdocissue.theissue\theproblem.html (The system cannot find the path specified)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

## Expected/Desired Behavior
The path should either remove the \ for the filed name so the file created is called something without this character
like maybe c:\temp\dbDoc\columns\dbo.dbdocissue.theissuetheproblem.html instead of c:\temp\dbDoc\columns\dbo.dbdocissue.theissue\theproblem.html

## Screenshots (if appropriate)
N/A

**Comment by FBurguer** [comment]
Hello! We did some changes to dbDoc on our latest versions, can you try upgrading and seeing if the issue continues to happen to you? Thanks!
