### ISSUE TITLE
Add precondition support for the SQL Dialect

### ISSUE THREAD

**Issue by awhitford-cip** [liquibase/liquibase#3767]
When using the SQL dialect, the only the **sqlCheck** precondition is available, like:
```
-- precondition-sql-check expectedResult:1 select count(*) from INFORMATION_SCHEMA.VIEWS where TABLE_NAME = 'MY_VIEW'
```

It would be great to be able to use other conditions like **viewExists**, **tableExists**, etc.

**Comment by FBurguer** [comment]
Hello, thanks for the submition. We will add it to our Feature Request queue, but it can take a while before we address it, you can always submit a pr with your ideas and we will be happy to help.

**Comment by JulienMa94** [comment]
@FBurguer @kevin-atx I would be happy to contribute to this enhancement. Are there any other preconditions than **viewExists** & **tableExists** which would be beneficial to look into. 

Thank you
Julien
