### ISSUE TITLE
mvn liquibase:diff fails to create change log file if not present in 4.17.x or later

### ISSUE THREAD

**Issue by pavankjadda** [liquibase/liquibase#3776]
## Environment

**Liquibase Version**: 4.17.x or later

**Liquibase Integration & Version**:
Maven plugin version 4.19.0

**Liquibase Extension(s) & Version**: 
liquibase-hibernate5: 4.19.0

**Database Vendor & Version**:
MySQL or SQL Server

**Operating System Type & Version**:
macOS 13

**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc>
VM

## Description
I upgraded liquibase from 4.16.1 to 4.19.0. When I run command
```
mvn liquibase:diff -Pdev -Dliquibase.url="jdbc:sqlserver://URL;encrypt=false" -Dliquibase.username="db-admin" -Dliquibase.password="PASSWORD" -Dliquibase.referenceUrl="jdbc:sqlserver://URL;encrypt=false" -Dliquibase.referenceUsername="sa" -Dliquibase.referencePassword="PASSWORD"
```
I get the error
```
[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:4.18.0:diff (default-cli) on project pres: 
[ERROR] Error setting up or running Liquibase:
[ERROR] liquibase.exception.CommandExecutionException: java.io.IOException: Cannot parse resource location: 'src/main/resources/db/changelog/dev/2022-12-17T01:09:39Z_changelog.xml
```
In 4.16.x or before liquibase creates change log file if not present and now it’s not creating it.

## Steps To Reproduce
Clone the repo https://github.com/pavankjadda/LiquibaseDemo/tree/4.19.0-bug and run the command
```
mvn liquibase:diff -Pdev -Dliquibase.url="jdbc:mysql://localhost:3306/liquibasedemo-dev?serverTimezone=UTC" -Dliquibase.username="root" -Dliquibase.password="Test@2020" -Dliquibase.referenceUrl="jdbc:mysql://localhost:3306/liquibasedemo?serverTimezone=UTC" -Dliquibase.referenceUsername="root" -Dliquibase.referencePassword="Test@2020"
```

## Actual Behavior
I see below error
```
[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:4.19.0:diff (default-cli) on project liquibasedemo: 
[ERROR] Error setting up or running Liquibase:
[ERROR] liquibase.exception.CommandExecutionException: java.io.IOException: Cannot parse resource location: 'src/main/resources/db/changelog/dev/2023-02-04T06:29:36Z_changelog.xml'
```

## Expected/Desired Behavior
It should create change log file with current timestamp

## Additional Context
I see this error in 4.17.x, 4.18.x and 4.19.0

**Comment by FBurguer** [comment]
Maybe its releated to #3762

**Comment by OduSamuel** [comment]
Maven timestamp by default produces an incompatible file name: **2022-12-17T01:09:39Z**

To change this you would have to add to your pom.xml:

```
<properties>
        <maven.build.timestamp.format>yyyyMMddHHmmss</maven.build.timestamp.format>
</properties>
```

**Comment by pavankjadda** [comment]
> Maven timestamp by default produces an incompatible file name: **2022-12-17T01:09:39Z**
> 
> To change this you would have to add to your pom.xml:
> 
> ```
> <properties>
>         <maven.build.timestamp.format>yyyyMMddHHmmss</maven.build.timestamp.format>
> </properties>
> ```

I am confused. I am using maven with 3.16.1 and 3.17.X or later with default format. Why is an issue now?

**Comment by pavankjadda** [comment]
@nvoxland Any plans to fix this in recent road map?

**Comment by kevin-atx** [comment]
@tati-qalified - could you retest this issue to see if it's still failing? Let me know if it is, and I'll add it to the next sprint for review. Thanks!

**Comment by pavankjadda** [comment]
> Hi @pavankjadda, thank you for reporting this issue. There are two things that are causing the error:
> 
> 1. What @OduSamuel mentioned about the incompatible file name.
> 2. In the project you provided, in your `pom.xml` file, the `diffChangeLogFile` location is set to `(...)/resources/db/changelog/${activeProfile}/${maven.build.timestamp}_changelog.xml`, however, there is no `changelog` directory under `db`, and no `dev` (or other profile) directory under that. Liquibase will create files if necessary, but it will not create directories.
> 
> In order to solve this issue, please add `<maven.build.timestamp.format>yyyyMMddHHmmss</maven.build.timestamp.format>` to your `<properties>` tag - using the format you'd prefer, but making sure it can be used for a file name. Also, set the `diffChangeLogFile` to an existing directory.
> 
> I'm attaching the updated project so you can verify that it works for all Liquibase versions since 4.16.1. If you have any other questions, feel free to let us know.
> 
> [LiquibaseDemo.zip](https://github.com/liquibase/liquibase/files/13513515/LiquibaseDemo.zip)
> 
> Thank you, Tatiana

Thanks. This works. The format **2022-12-17T01:09:39Z** used to work but no longer. Is there a specific reason?

**Comment by pavankjadda** [comment]
> @pavankjadda the `:` character is not valid for filenames in Windows, but it is valid in Linux and MacOS. By any chance have you changed your operating system?

No. I have been using macOS for several years

**Comment by tati-qalified** [comment]
In that case I'm not sure why it's failing, but it seems to be an issue with Maven or some other framework in the project, not with Liquibase. I'd recommend you to look into their documentation on filenames.
