### ISSUE TITLE
Prefer to have LIQUIBASE_HOME as a property so it can be passed on the commandline 

### ISSUE THREAD

**Issue by kdeenkhoorn** [liquibase/liquibase#3777]
https://github.com/liquibase/liquibase/blob/16337eee2f92e514ddc843064fc39bafcdd4e726/liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java#L33

Is it possible to change the LIQUIBASE_HOME OS variable to a property so it can be passed on the java -jar liquibase-core.jar as a -D option ?
We have a hard time making this change to our deployment scripting to switch from java -jar notation to a bash script.
The majority of options can be passed on the commandline except these ones from the LiquibaseLauncher.

**Comment by FBurguer** [comment]
Hello! Thanks for creating this issue! i modify the title becaue supporting it as an argument in the properties file wouldnt make much sense but adding it as a property to pass on the command line sounds like a cool feature! I will add it to our queue of Feature Requests, but it can take a while for it to be address, you can always submitt a pr and we would love to help you working through it with you.

**Comment by filipelautert** [comment]
This was implemented on https://github.com/liquibase/liquibase/pull/4104 .
