### ISSUE TITLE
Failed writes to databasechangelog do not rollback changeset changes

### ISSUE THREAD

**Issue by rdhzl** [liquibase/liquibase#3780]
## Environment

**Liquibase Version**: 4.19.0

**Liquibase Integration & Version**: Gradle

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: PostgreSQL 12

**Operating System Type & Version**: MacOS X 13.1

**Infrastructure Type/Provider**: N/A

## Description

Failing to write to databasechangelog during changeset operation does not appear to rollback changeset.

## Steps To Reproduce

Recently filed this issue around the ability to create duplicate tag values in databasechangelog: https://github.com/liquibase/liquibase/issues/3763

Because of this behavior I went about adding unique constraints to our databasechangelog table to stop developers from re-using changeset IDs and database tags. Similar to this:

```
    <!-- Unique constraint on id column of databasechangelog -->
    <changeSet id="API-123-unique-id" author="rdhzl">
        <addUniqueConstraint  schemaName="hzl"
                              tableName="databasechangelog"
                              columnNames="id"
                              constraintName="databasechangelog_id_key"/>
    </changeSet>
    <!-- Unique constraint on tag column of databasechangelog -->
    <changeSet id="API-456-unique-tag" author="rdhz1">
        <addUniqueConstraint  schemaName="hzl"
                              tableName="databasechangelog"
                              columnNames="tag"
                              constraintName="databasechangelog_tag_key"/>
    </changeSet>
```
After applying the above to a schema, in testing I've found that liquibase such as the following will execute changeset contents, fail on the write to databasechangelog (Expected), but then not rollback the changelog changes (Unexpected). 

```
    <changeSet id="API-111" author="rdhzl">
        <createTable tableName="tablename">
            <column name="column" type="VARCHAR(64)" defaultValue="unknown"></column>
        </createTable>
    </changeSet>
    <changeSet id="API-789" author="rdhzl">
        <addColumn tableName="tablename">
            <column name="column_one" type="VARCHAR(64)" defaultValue="unknown"></column>
        </addColumn>
    </changeSet>
    <changeSet id="API-789" author="djhzl">
        <addColumn tableName="tablename">
            <column name="column_two" type="VARCHAR(64)" defaultValue="unknown"></column>
        </addColumn>
    </changeSet>
```

## Actual Behavior
In the case above the same id/different author avoids Liquibase's preemptive validation, and allows these to run. Both columns are created and then when Liquibase goes to journal the change to databasechangelog, that write fails, but does not remove the newly created column_two.

## Expected/Desired Behavior
I would have expected that the entire changeset operation was transactional, and so if any part, including the write to databasechangelog failed that the entire transaction would be rolled back. I do recognize that in this case we've modified databasechangelog. Our rationale is we don't really want duplicate changeset IDs and we most certainly do not want duplicate tag values. It's too easy for developers to copy/paste existing changelog code and forget to change these IDs and so I'm trying to make this a little less easy of a thing to do.

## Additional Context
Running Changeset: db.changelog-v13.0.xml::API-123-unique-id::rdhzl 
[2023-02-06 09:49:51] INFO [liquibase.changelog] Unique constraint added to databasechangelog(id)
[2023-02-06 09:49:51] INFO [liquibase.changelog] ChangeSet db.changelog-v13.0.xml::API-123-unique-id::rdhzl ran successfully in 2ms
Running Changeset: db.changelog-v13.0.xml::API-456-unique-tag::rdhzl
[2023-02-06 09:49:51] INFO [liquibase.changelog] Unique constraint added to databasechangelog(tag)
[2023-02-06 09:49:51] INFO [liquibase.changelog] ChangeSet db.changelog-v13.0.xml::API-456-unique-tag::rdhzl ran successfully in 2ms
Running Changeset: db.changelog-v13.0.xml::API-111::rdhzl
[2023-02-06 09:49:51] INFO [liquibase.changelog] Table tablename created
[2023-02-06 09:49:51] INFO [liquibase.changelog] ChangeSet db.changelog-v13.0.xml::API-111::rdhzl ran successfully in 2ms
Running Changeset: db.changelog-v13.0.xml::API-789::rdhzl
[2023-02-06 09:49:51] INFO [liquibase.changelog] Columns column_one(VARCHAR(64)) added to tablename
[2023-02-06 09:49:51] INFO [liquibase.changelog] ChangeSet db.changelog-v13.0.xml::API-789::rdhzl ran successfully in 1ms
Running Changeset: db.changelog-v13.0.xml::API-789::djhzl
[2023-02-06 09:49:51] INFO [liquibase.changelog] Columns column_two(VARCHAR(64)) added to tablename
[2023-02-06 09:49:51] INFO [liquibase.changelog] ChangeSet db.changelog-v13.0.xml::API-789::djhzl ran successfully in 1ms
[2023-02-06 09:49:51] INFO [liquibase.lockservice] Successfully released change log lock
[2023-02-06 09:49:51] SEVERE [liquibase.integration] ERROR: duplicate key value violates unique constraint "databasechangelog_id_key"
  Detail: Key (id)=(API-789) already exists. [Failed SQL: (0) INSERT INTO hippo.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('API-789', 'djhzl', 'db.changelog-v13.0.xml', NOW(), 68, '8:b7d3400e7622c1dc81cfc770d3c75a00', 'addColumn tableName=tablename', '', 'EXECUTED', NULL, NULL, '4.19.0', '5694991310')]
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.DatabaseException: ERROR: duplicate key value violates unique constraint "databasechangelog_id_key"
  Detail: Key (id)=(API-789) already exists. [Failed SQL: (0) INSERT INTO hippo.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('API-789', 'djhzl', 'db.changelog-v13.0.xml', NOW(), 68, '8:b7d3400e7622c1dc81cfc770d3c75a00', 'addColumn tableName=tablename', '', 'EXECUTED', NULL, NULL, '4.19.0', '5694991310')]

**Comment by nvoxland** [comment]
Generally, the unique constraint shouldn't just be on id, since liquibase uses a combination of id + author + filename as the complete identifier. The reason we don't have just "id" be unique is that it can be hard for multiple authors (possibly across branches) coordinate unique IDs, but each author knows what they've used and can keep things globally unique. Especially since the filename is part of the identifier so they only have to remember what ids they have used in that particular file.

Maybe you have a setup that makes you want to have the ids be unique regardless of the author/file? But there is no liquibase-reason to have the constraint only on "id"

**Comment by nvoxland** [comment]
There's nothing wrong with them leaving the ID the same unless your ID has a specific meaning to you. Often times people just use an incrementing number and re-use is just fine. Liquibase's validation will fail if they forget to change either the id or author. 

But if you're id is meaningful, it can work to add that constraint. But, you may not like my next comment about fixing the problem you see with it...
