### ISSUE TITLE
Incorrect syntax while creating snapshot if using quotes for table names

### ISSUE THREAD

**Issue by Rumata42** [liquibase/liquibase#3825]
## Environment

**Liquibase Version**: 4.17.2
**Database Vendor & Version**: MS SQL server 2017
**Operating System Type & Version**: Ubuntu 20.04

## Description

Error "Incorrect syntax" occurs when I try to create a snapshot and have at least 4 tables with quotes in names

## Steps To Reproduce

1. Create 3 tables with quotes: 'sheet0', 'sheet1', 'sheet2', example of the script:
```
CREATE TABLE ['sheet0'] (
    id BIGINT NOT NULL
);
```
2. Create a snapshot:
`liquibase --url="jdbc:sqlserver://localhost:1433;database=sheetproblem;trustServerCertificate=true" --classpath=/home/workarea/jdbc/mssql-jdbc-11.2.3.jre11.jar --username=sa --password=123456 snapshot`
3. It works correctly
4. Create another table 'sheet3'
5. Try to create a snapshot again (same script)

## Actual Behavior
The exception occurs:
`Unexpected error running Liquibase: liquibase.exception.DatabaseException: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'sheet0'.`

## Expected/Desired Behavior
The snapshot created

**Comment by nvoxland** [comment]
Given that it's starting to fail in the 4+ table scenario, the bug is probably in the "get all the tables" query of JdbcDatabaseSnapshot

**Comment by FBurguer** [comment]
Hi! I tried to reproduce this on Liquibas `4.18.0`. But I didnt get any error. Can you try to upgrade to our latest version and try again or point us where you think the issue may be. Thanks!
