### ISSUE TITLE
generateChangeLog with liquibase.command.includeSchema=true doesn't create schemas

### ISSUE THREAD

**Issue by victorrodrigueznadq** [liquibase/liquibase#3844]
### Search first

- [X] I searched and no similar issues were found

### Description

Using generateChangeLog with liquibase.command.includeSchema=true doesn't generate change sets to create the schemas before referencing them.  Therefore, you get errors like the following:

```
liquibase.exception.DatabaseException: ERROR: schema "the_schema" does not exist
```

### Steps To Reproduce

generateChangeLog against a postgres database with at least one schema.  Use include schema true.  then try to run the change log against an empty database and observe the error about the schema not existing.

### Expected/Desired Behavior

a changeset to create the schema should be generated before any changesets that reference the schema are generated.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nvoxland** [comment]
Unfortunately that's not the reason for the `includeSchema` flag. Liquibase never tries to capture the schema creation statements during generateChanglog, only what is in the schema. The includeSchema flag specifies whether generateChangeLog should include the `schemaName` attribute for the default schema in the generated changelog or not.

What is generated by generateChangelog is best thought of as a starting point and you can always adjust it as needed. For example, if you need to create the schema you can add a changeset at the beginning of the file to create it and assign permissions as you need.

**Comment by victorrodrigueznadq** [comment]
@nvoxland unfortunately, this means that I have to add the create schema changeSets by hand after doing a generateChangeLog, which is a pain in the but.  I found a way to automate it, as follows, but still means that liquibase is an incomplete solution:

```
find . -mindepth 1 -maxdepth 1 -type d | sed -E 's:[^/]+/::g' | sort -u | sed 's:^:TAG:g' | sed 's \(.*\) \1\1\1 ' | sed -e 's:TAG:    <changeSet author="vicrod (generated)" id=":1' | sed 's:TAG:"><sql>CREATE SCHEMA :1' | sed 's:TAG:;GRANT ALL PRIVILEGES ON SCHEMA :1' | sed 's:$: TO rms;</sql></changeSet>:g' >> databaseChangeLog.master.xml
```

Perfection should be the goal; not being adequate.
