### ISSUE TITLE
generateChangeLog generates bad foreign keys

### ISSUE THREAD

**Issue by victorrodrigueznadq** [liquibase/liquibase#3845]
### Search first

- [X] I searched and no similar issues were found

### Description

generateChangeLog generates bad foreign keys.  See the example below, with rules_execution_id, repeated multiple times...

```
    <changeSet author="vicrod (generated)" id="1676920674006-17">
        <addForeignKeyConstraint baseColumnNames="rules_execution_id,rules_execution_id,rules_execution_id,rules_execution_id,rules_execution_id,rules_execution_id" baseTableName="non_transactional_billing_charge_old" baseTableSchemaName="nfx_rules" constraintName="non_transactional_billing_charge_rules_execution_id_fkey" deferrable="false" initiallyDeferred="false" onDelete="NO ACTION" onUpdate="NO ACTION" referencedColumnNames="rules_execution_id,rules_execution_id,rules_execution_id,rules_execution_id,rules_execution_id,rules_execution_id" referencedTableName="rules_execution" referencedTableSchemaName="nfx_rules" validate="true"/>
    </changeSet>
```

It's defined in redshift (postgres) as follows:

```
FOREIGN KEY (rules_execution_id) REFERENCES nfx_rules.rules_execution(rules_execution_id)
```

### Steps To Reproduce

run generate change log against a database that has foreign keys.  Observe that sometimes the foreign key is generated incorrecty.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nvoxland** [comment]
Does it help to include the liquibase-redshift extension in your `lib` directory? One fix in that extension is to remove the snapshot (and therefore generation) of foreign keys. The code comment says because `Redshift does not support calls to MetaData.getIncomingKeys() and doesn't really support FKs anyway`.

That extension should keep the addForeignKey from even showing in the generated changelog

**Comment by nvoxland** [comment]
Closing due to lack of response. If this is still an issue, feel free to reopen or comment.
