### ISSUE TITLE
Threading and memory issues caused by static 'addedMdcEntries' map in Scope

### ISSUE THREAD

**Issue by bvremmeinfor** [liquibase/liquibase#3915]
### Search first

- [X] I searched and no similar issues were found

### Description

Using Liquibase 4.19.1 in a multi-threaded environment throws NullPointerExecptions like this:
```Caused by: java.lang.NullPointerException
        at liquibase.Scope.removeMdcObjectWhenScopeExits(Scope.java:427)
        at liquibase.Scope.addMdcValue(Scope.java:417)
        at liquibase.Scope.addMdcValue(Scope.java:406)
        at liquibase.executor.jvm.ChangelogJdbcMdcListener.addSqlMdc(ChangelogJdbcMdcListener.java:63)
        at liquibase.executor.jvm.ChangelogJdbcMdcListener.execute(ChangelogJdbcMdcListener.java:30)
        at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:285)
        at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:2237)
        at liquibase.Liquibase$16.run(Liquibase.java:2309)
        at liquibase.Scope.lambda$child$0(Scope.java:187)
        at liquibase.Scope.child(Scope.java:196)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.Liquibase.runInScope(Liquibase.java:2714)
        ... 9 more
```

### Steps To Reproduce

Run a stress-test with multiple threads.
This can be used: https://github.com/bvremmeinfor/liquibase-threading-demo

### Actual Behavior

Liquibase fails with NullPointerExceptions, usually related to Scope.removeMdcObjectWhenScopeExits().

### Expected/Desired Behavior

Stable run without NullPointerExceptions

### Liquibase Version

4.19.1

### Database Vendor & Version

Any

### Additional Context

Please review changes in Scope [in this commit](https://github.com/liquibase/liquibase/pull/3574/files#diff-02cf9dc5731d4b4cab085adaefa3a0c592e2af76b14c0e0f781f4544c7153007).

* notice the static unsynchronized Map, when modified by multiple threads weird bugs will occur
* elements in map are never removed, looks like a memory leak (when used in long running JVMs)

Suggestions:
```java
  // Use ConcurrentHashMap for thread safety
  // Note: Lists in Map does not need synchronization, they belong to single Scope/thread
  private static final ConcurrentHashMap<String, List<MdcObject>> addedMdcEntries = new ConcurrentHashMap<>();
```

When clearing do not use get, _remove_ entry from the map (removes the memory leak):
```
  // clear the MDC values added in this scope
  final List<MdcObject> mdcObjects = addedMdcEntries.remove(currentScope.scopeId);
  for (MdcObject mdcObject : CollectionUtil.createIfNull(mdcObjects)) {
      mdcObject.close();
   }
```

Use computeIfAbsent to add entries in a thread-safe way:
``` 
private void removeMdcObjectWhenScopeExits(boolean removeWhenScopeExits, MdcObject mdcObject) {
        if (removeWhenScopeExits) {
            Scope currentScope = getCurrentScope();
            String scopeId = currentScope.scopeId;

            addedMdcEntries
                    .computeIfAbsent(scopeId, k -> new ArrayList<>())
                    .add(mdcObject);
        }
    }
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hherman1** [comment]
In our CI we had 700MB of liquibase.logging.mdc.MdcObject which triggered OOMs. After reverting to 4.19.0, the OOMs stopped.

**Comment by amrasarfeiniel** [comment]
Put up https://github.com/liquibase/liquibase/pull/3927 hoping to address this.  Not sure if this is sufficient or not.  Would be helpful to get this fixed and released as there is no released version of liquibase that does not have this issue and is compatible with snakeyaml 2.0.

**Comment by filipelautert** [comment]
So I executed @bvremmeinfor project a lot of times using branch from PR https://github.com/liquibase/liquibase/pull/3927 created by @amrasarfeiniel  and didn't get any error. When I executed it with master I was able to simulate the problem.
So thanks for the issue, sample project and PR!
