### ISSUE TITLE
executeCommand runs twice per changeSet

### ISSUE THREAD

**Issue by joserebelo** [liquibase/liquibase#3945]
### Search first

- [X] I searched and no similar issues were found

### Description

The `executeCommand` is being executed twice per changeSet, since Liquibase 4.19.1. This was working as expected on Liquibase 4.19.0.

We can see that the [ExecuteShellCommandChange](https://github.com/liquibase/liquibase/blob/63f445f85beda72e7aafc8bb18340713049ecc5c/liquibase-core/src/main/java/liquibase/change/core/ExecuteShellCommandChange.java#L122) uses the generateStatements function to execute the shell command conditionally. This seems to be now called [while reading the changesets](https://github.com/liquibase/liquibase/blob/63f445f85beda72e7aafc8bb18340713049ecc5c/liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java#L714), which will effectively execute the command prematurely.

A git bisect tracked the commit that introduced this erratic behavior to 005857b1aa387896acf9a6bb12a813fbb34281a0

### Steps To Reproduce

Run the following changeSet:

```xml
<changeSet id="shell command" author="joserebelo">
    <executeCommand executable="/bin/bash">
        <arg value="-c"/>
        <arg value="echo hi >> /tmp/liquibase_shell_out"/>
    </executeCommand>
</changeSet>
```

Notice that `/tmp/liquibase_shell_out` will actually contains 2 lines, since the executeCommand change ran twice.

### Expected/Desired Behavior

The executeCommand change should only be executed once per changeSet.

### Liquibase Version

4.19.1, also confirmed on master (fa6ecb783a6931cddce5f07773f40217b6c9d7c0)

### Database Vendor & Version

PostgreSQL 9.6

### Liquibase Integration

cli

### OS and/or Infrastructure Type/Provider

Ubuntu

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by joschi** [comment]
Same issue here with Liquibase 4.19.1 and 4.20.0.

Example: https://github.com/dropwizard/dropwizard/pull/6776

**Comment by filipelautert** [comment]
Hello - @wwillard7800 is working on a fix for that. Thanks for the reports!

**Comment by filipelautert** [comment]
Thanks for the comments @kristofdepypere . Seems the same issue, but the PR won't fix it. We will take a look at a more generic fix in this case.

**Comment by filipelautert** [comment]
Hello @kristofdepypere - could you share something about your setup? Are you running liquibase on spring/osgi/command line/something else?

**Comment by kristofdepypere** [comment]
Hi,
We are running liquibase in a spring application by extending the SpringLiquibase class. We were looking into upgrading liquibase but are clearly seeing our <customChange class="...."/> changes running twice. They are extending the liquibase.change.custom.CustomTaskChange class.  

They clearly run twice inside the same changeset in the same database transaction. First run all goes well, second run it fails (primary key violations) and all rolls back. 
Is there more information you need ?  We are using liquibase 4.19.0 and tested out immediately on 4.20.0.

**Comment by malikin** [comment]
Hi everyone! When should we expect a release with this fix? Thanks!

**Comment by filipelautert** [comment]
Hello @malikin ! We will release in 1-2 weeks .
