### ISSUE TITLE
generateChangeLog doesn't generate foreign keys for mariadb/mysql

### ISSUE THREAD

**Issue by victorrodrigueznadq** [liquibase/liquibase#3955]
### Search first

- [X] I searched and no similar issues were found

### Description

generateChangeLog doesn't generate foreign keys for mariadb/mysql.  I'm counting on having good integration testing and for this i'm using the change logs generated by generateChangeLog, but no foreign keys were generated although I have `export LIQUIBASE_COMMAND_DIFF_TYPES=tables,views,columns,indexes,foreignkeys,primarykeys,uniqueconstraints,checkconstraints,data` 

### Steps To Reproduce

run generatChangeLog against a mariadb/mysql database that has foreign keys and observe that the keys aren't in the generated change logs.

### Expected/Desired Behavior

Foreign keys generated.

### Liquibase Version

4.19

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nvoxland** [comment]
@victorrodrigueznadq, If you don't specify the diffTypes does it include the foreign keys? I know you need the diffTypes to get the data, but looking to troubleshoot where the problem is.

**Comment by victorrodrigueznadq** [comment]
@nvoxland I'll see if I have time.  For the moment, I've moved on from this and I'm using mysql dump for the db structure and for the liquibase tables.  I'm using liquibase only for the data.  This should be easy enough for you guys to test.  let me know.

**Comment by FBurguer** [comment]
Hello! I tried to reproduce this behavior on Liquibase 4.20.0 and didnt have that beahvior. Can you talk about your env a little more? That may help finding the issue. Thanks!

**Comment by FBurguer** [comment]
Closing this issue because it got stale. Feel free to re-open if needed! Thanks
