### ISSUE TITLE
SAP SQL Anywhere 17.0.11: Liquibase incorrectly reports that TIMESTAMP requested precision is longer than TIMESTAMP supported precision

### ISSUE THREAD

**Issue by mkarg** [liquibase/liquibase#3971]
### Search first

- [X] I searched and no similar issues were found

### Description

I am trying to `generateChangeLog` from a SAP SQL Anywhere 17.0.11 database which contains TIMESTAMP WITH TIME ZONE columns having a default of DEFAULT UTC TIMESTAMP.

Liquibase incorrectly complains that the supported precision is shorter than the requested precision:

```
liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: liquibase.exception.DatabaseIncapableOfOperation: Using a TIMESTAMP data type with a fractional precision of 33 is not supported on asany: A timestamp datatype with 33 fractional digits was requested, but SQL Anywhere only supports 9 digits.
```

The message was true for older versions of SQL Anywhere which did not support "WITH TIME ZONE", but since current versions support "WITH TIME ZONE" this message is wrong now.

### Steps To Reproduce

`generateChangeLog` using SQL Anywhere 17.0.11 having a column with the definition `TIMESTAMP WITH TIMEZONE DEFAULT UTC TIMESTAMP`.

### Expected/Desired Behavior

Successfully accepts both, the type `TIMESTAMP WITH TIMEZONE` and the default value `UTC TIMESTAMP`.

### Liquibase Version

latest

### Database Vendor & Version

SAP SQL Anywhere 17.0.11

### Liquibase Integration

Maven Plugin

### Liquibase Extensions

none

### OS and/or Infrastructure Type/Provider

Windows 10

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nvoxland** [comment]
Thanks for the issue. There is similar "timestamp with time zone" logic for postgresql that will need to be adapted to sap sql now that it supports it.

**Comment by mkarg** [comment]
>There is similar "timestamp with time zone" logic for postgresql that will need to be adapted to sap sql now that it supports it.

Does "that need to be adapted" mean that a committer will work on it, or does it mean that the project team expects the reported (me) to provide that fix?

**Comment by mkarg** [comment]
I have startet work in this issue in my private fork: https://github.com/mkarg/liquibase/tree/mkarg/sap-sql-anywhere-liquibase-3971. Comments very welcome! 😃

**Comment by MalloD12** [comment]
Hi @mkarg, thank you for reporting this issue and for creating a PR for it. Is there anything we can do to help you to move forward with this PR?

**Comment by mkarg** [comment]
> Hi @mkarg, thank you for reporting this issue and for creating a PR for it. Is there anything we can do to help you to move forward with this PR?

Thank you for this kind offer, I really appreciate it. @filipelautert is already supporting me. Unfortunately I do not see how you can help *right now*, as the next step is that I need to check the JDBC driver's *actual* behavior. Once that is known, we can decide how to work around.

**Comment by MalloD12** [comment]
> 

Yeah, I talked with Filipe after posting my comment. Cool, if there is anything I can help with please let me know.

Thanks,
Daniel.
