### ISSUE TITLE
Liquibase search for file config/liquibase/changelog/12 after update Liquibase 3.3.2 to 4.20.0

### ISSUE THREAD

**Issue by thebear45800** [liquibase/liquibase#4010]
### Search first

- [X] I searched and no similar issues were found

### Description

After update Liquibase to version 4.20.0 (I was in 3.3.2)
Now it crash by running changeSet with context="test", it seems to search file config/liquibase/changelog/12

`[ERROR] liquibase.changelog - ChangeSet config/liquibase/changelog/myFile.xml::99999999999999::jhipster encountered an exception.
[WARN] org.springframework.web.context.support.GenericWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [fr/myApp/common/config/DatabaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset config/liquibase/changelog/myFile.xml::99999999999999::jhipster:
     Reason: liquibase.exception.DatabaseException: The file config/liquibase/changelog/12 was not found in the configured search path:
    - Spring classpath
More locations can be added with the 'searchPath' parameter.
[ERROR] org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [fr/myApp/common/config/DatabaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset config/liquibase/changelog/myFile.xml::99999999999999::jhipster:
     Reason: liquibase.exception.DatabaseException: The file config/liquibase/changelog/12 was not found in the configured search path:
    - Spring classpath
More locations can be added with the 'searchPath' parameter.`

I never got this file before
Sorry for that only informations, I am begginer with liquibase.

### Steps To Reproduce

Having some changeset with context="test"

### Expected/Desired Behavior

No error

### Liquibase Version

4.20.0

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by thebear45800** [comment]
Thanks for responding :)

Actually the file "myFile.xml" looks like that : 

`<?xml version="1.0" encoding="utf-8"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">

	<property name="now" value="now()" dbms="mysql,h2" />
	<property name="now" value="current_timestamp" dbms="postgresql" />

	<changeSet id="99999999999999" author="jhipster" context="test">
			
		<loadData encoding="UTF-8" file="config/liquibase/csv/data.csv"
			separator=";" tableName="MY_TABLE">
			<column name="field1" type="boolean" />
			<column name="field2" type="timestamp" />
		</loadData>
                              
									

	</changeSet>
</databaseChangeLog>
`

I just wrote first <loadData) of this chageset but all the <loadData> is like this (referecing to a csv file, with correct path).

And I never had a file config/liquibase/changelog/12 in my all project (there is not even extension file to the "12" file searched by liquibase)

And this changeset was working fine in liquibase 3.3

**Comment by nvoxland** [comment]
Is there any type="blob" or type="clob" loadData columns in that changeset?

**Comment by thebear45800** [comment]
Possible yes, actually there is like 20 load data like this one : 

<loadData encoding="UTF-8" file="config/liquibase/csv/entity1.csv"
			separator=";" tableName="TABLE_ENTITY1" />
			
Directly binding with Java entity and spring entity.

But I try something : create the "12" file and now it ask for file "13"
I create with unix command 100 file like this one and actually it need file : 12 to 17.
Just empty file with no extension.

Now it start to process my xml other liquibase file. I think I can figure it out

**Comment by zfkang-talend** [comment]
I got the same issue, I upgrade the Lquibase from 4.8.0 to 4.20.0 and get the same error.
When I debug it. found some issues,
Request the class AbstractPathResourceAccessor.java#standardizePath()
```
private String standardizePath(String path) {
        try {
            //
            // Flip the separators to Linux-style and replace the first separator
            // If then root path is the absolute path for Linux or Windows then return that result
            //
            String rootPath = getRootPath().toString();
            String result = new File(path).toPath().normalize().toString().replace("\\", "/").replaceFirst("^/", "");
            if (rootPath.equals("/") || rootPath.equals("\\")) {
                return result;
            }

            //
            // Strip off any Windows drive prefix and return the result
            //
            return result.replaceFirst("^\\w:/","");
        } catch (InvalidPathException e) {
            Scope.getCurrentScope().getLog(getClass()).warning("Failed to standardize path " + path, e);
            return path;
        }
    }
```
The path is like the liunx style, such as _/config/liquibase/changelog/myFile.xml_, but after below line will replace the first separator: _config/liquibase/changelog/myFile.xml_
```
String result = new File(path).toPath().normalize().toString().replace("\\", "/").replaceFirst("^/", "");
```
so the path is changed, and when request the below code, the file doesn't exist:
```
Path finalPath = getRootPath().resolve(path);
```

If I change the path to a _/config/liquibase/changelog/myFile.xml_, it works.

**Comment by kevin-atx** [comment]
@tati-qalified This ticket needs a response pointing to the new searchPath documentation update you are working on.

**Comment by tati-qalified** [comment]
@thebear45800 from Liquibase version 4.13 onwards, in your liquibase.properties file, you can add the [**searchPath**](https://docs.liquibase.com/concepts/changelogs/how-liquibase-finds-files.html) property and point to the directory where your changelog file is. This will be prioritised over other locations.

Would you be able to try this and let us know if it worked? Thanks!
