### ISSUE TITLE
Unable to migrate database on Postgres with a schema containing dashes

### ISSUE THREAD

**Issue by Thodor12** [liquibase/liquibase#4014]
### Search first

- [X] I searched and no similar issues were found

### Description

In our environment, we use postgres databases containing dashes (name originates from git branches).
We found out that when running Liquibase on a Spring application hosted in JBoss that our deployment got stuck because it was failing to acquire a lock, after further debugging we found out that Liquibase is unable to handle schema names with dashes in them.

I have setup an example project which demonstrates the issue here: https://github.com/Thodor12/LiquibaseTest

Schema names with special characters aren't anything out of the ordinary, but they must be wrapped in double quotes in order for the query to be valid.

### Steps To Reproduce

- Checkout the application provided in the description
- Ensure you have Docker installed so you can create the database using compose (alternatively set it up with the identical configuration as in the project)
- Start the application
- Error appears on boot:

```
Caused by: liquibase.exception.LockException: liquibase.exception.DatabaseException: ERROR: syntax error at or near "-"
```

We solved the issue in our project by stripping every non-alphanumeric character from the schema in order to make it functional.
If this is the intended solution, is this mentioned anywhere in the documentation?

### Expected/Desired Behavior

The application can start fine and no errors appear

### Liquibase Version

4.19.0 (in project), 4.17.2 (in example)

### Database Vendor & Version

PostgreSQL 14.4

### Liquibase Integration

gradle

### Liquibase Extensions

N/A

### OS and/or Infrastructure Type/Provider

Windows 10 / CentOS 7.9

### Additional Context

N/A

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
Hello @Thodor12 
I found a workaround for that: you can set property "preserveSchemaCase=true" . It was meant to preserve schema case by surrounding it on quotes, but seems it fixes this case too.

**Comment by Thodor12** [comment]
In our project at work we already migrated away from special characters in schema names so it's not blocking us or anything.
If that workaround works I believe you, but we don't need it.
In the end I just wanted to let you know in case someone else runs into it in the future.

**Comment by XDelphiGrl** [comment]
Thanks for the example project, @Thodor12. I was quickly able to reproduce the bug and see if fixed with a branch build of [https://github.com/liquibase/liquibase/pull/4021](https://github.com/liquibase/liquibase/pull/4021).

**Comment by TiomanGally** [comment]
Hi 🙂 
May I ask when there is a new release containing this bug? 
Our customer database schema contains dashes and we are experiencing this bug and hope that this release will fix it

**Comment by XDelphiGrl** [comment]
@TiomanGally, hello! Liquibase Engineering is in the process of getting a release candidate for v4.22. We are targeting a release in the week of May 8th, 2023.

**Comment by TiomanGally** [comment]
@XDelphiGrl awesome! Thank you.

**Comment by XDelphiGrl** [comment]
You are very welcome, @TiomanGally. I hope you have a great day!
