### ISSUE TITLE
liquibase.exception.UnexpectedLiquibaseException: Resource does not exist

### ISSUE THREAD

**Issue by srikanthadapa249** [liquibase/liquibase#4029]
### Search first

- [X] I searched and no similar issues were found

### Description

Hi Team,

Need help in resolving this issue, recently we are planning to upgrade from 4.16.1 to 4.20.0 and we see below issue

Caused by: liquibase.exception.LiquibaseParseException: liquibase.exception.UnexpectedLiquibaseException: Resource does not exist
at liquibase.parser.core.yaml.YamlSnapshotParser.parse(YamlSnapshotParser.java:72)
at liquibase.database.OfflineConnection.(OfflineConnection.java:101)
… 16 more
Caused by: liquibase.exception.UnexpectedLiquibaseException: Resource does not exist
at liquibase.resource.ResourceAccessor$NotFoundResource.openInputStream(ResourceAccessor.java:224)
at liquibase.parser.core.yaml.YamlSnapshotParser.parse(YamlSnapshotParser.java:42)
… 17 more

Looks like the recent changes are done and its causing the issue. YamlSnapshotParser.java the way ResourceAccessor reads the file is different from way it was in 4.16.1.

resourceAccessor.openStream(null, path) - 4.16.1
resourceAccessor.get(path) - 4.20.0

### Steps To Reproduce

while calling the LiquibaseService..getOfflineDatabase() internally from the code.

### Expected/Desired Behavior

Should able to read the file from the path specified which is happening with the version 4.16.1

### Liquibase Version

4.20.0

### Database Vendor & Version

Oracle DB

### Liquibase Integration

Maven

### OS and/or Infrastructure Type/Provider

Windows

### Additional Context

<img width="551" alt="image" src="https://user-images.githubusercontent.com/61774704/227853443-72c1789f-7529-4b4b-a773-6439c7bc7a1e.png">

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nvoxland** [comment]
There has been some bugfixes/standardization/improvements in that code over the last few releases. 

The `FileSystemResourceAccessor` will have a set of directories and/or zip/jar files where it looks for the `scratch/../IBM/WebSphere/...` value in the `path. When you look at how that `resourceAccessor` object is configured, is the base directory/archive of your file in there correctly?

**Comment by srikanthadapa249** [comment]
File names mentioned are correct, and when using older versions, the files were picked correctly.

**Comment by srikanthadapa249** [comment]
Was the issue fixed in latest version of Liquibase? Can you please provide more details on this.

**Comment by hylkevds** [comment]
It seems to go wrong in 4.22.0 with a changelog at a relative path that starts with `../` with a changeset that contains `<sqlFile relativeToChangelogFile="true" ... />`. It seems it can't fine the sql file. Though with such a bad error message it's hard to say. That exception should at least contain WHICH resource it can't find, and at which path it is looking for said resource.
