### ISSUE TITLE
Unnecessary ALTER TABLE statements for PostgreSQL 15

### ISSUE THREAD

**Issue by gigi** [liquibase/liquibase#4047]
### Search first

- [x] I searched and no similar issues were found

### Description

Hello!

I use Liquibase to generate sql migrations for PostgreSQL 15.2
Since 4.19.1 there is unnecessary changes appears in migration files.

### Steps To Reproduce

```bash
git clone -b liquibase-4.19.1-issue git@github.com:gigi/gigi-spring-rest-skeleton.git && cd ./gigi-spring-rest-skeleton && ./gradlew composeUp && ./gradlew bootRun
```

We need `./gradlew bootRun` only to apply migrations because `./gradlew changelogSync` stopped working for me somewhere since 4.16.1 due `Caused by: liquibase.exception.ChangeLogParseException: classpath:/db/changelog.yaml does not exist` but it's another issue 

when migrations applied run

```bash
./gradlew diffChangelog 
```

new migration file will be created in `src/main/resources/db/migrations/DATETIME.sql`

Strange ALTER TABLE statements added
```
-- liquibase formatted sql

-- changeset gigi:1680029798172-1
ALTER TABLE public.post ALTER COLUMN content TYPE VARCHAR(255) USING (content::VARCHAR(255));

-- changeset gigi:1680029798172-2
ALTER TABLE public.post ALTER COLUMN created_at TYPE TIMESTAMP(6) WITHOUT TIME ZONE USING (created_at::TIMESTAMP(6) WITHOUT TIME ZONE);

-- changeset gigi:1680029798172-3
ALTER TABLE public.tag ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

-- changeset gigi:1680029798172-4
ALTER TABLE public."user" ALTER COLUMN nickname TYPE VARCHAR(255) USING (nickname::VARCHAR(255));

-- changeset gigi:1680029798172-5
ALTER TABLE public.post ALTER COLUMN title TYPE VARCHAR(100) USING (title::VARCHAR(100));

```

### Expected/Desired Behavior

Empty migration expected
```
-- liquibase formatted sql
```

### Liquibase Version

4.19.1

### Database Vendor & Version

PostgreSQL 15.2

### Liquibase Integration

Gradle plugin v2.2.0, spring boot 3

### OS and/or Infrastructure Type/Provider

Mac M1

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
Hello @gigi , thanks for the report! Did you test it with other postgresql versions? Just asking so we can reproduce the issue faster.

**Comment by gigi** [comment]
Hello, @filipelautert!

Rechecked with PostgreSQL 10.21 (Debian 10.21-1.pgdg90+1) + Liquibase Version 4.19.1.
Just changed version [here](https://github.com/gigi/gigi-spring-rest-skeleton/blob/main/docker-compose.yaml#L6).

The same issue is present

**Comment by adam-crowther** [comment]
Hi all,
Just to let you know that I am also having the same issue with 4.20.
I posted on the Liquibase forum with a lot more context information: https://forum.liquibase.org/t/diffchangelog-is-generating-redundant-modifydatatype-changes/8032
Postgres version is 15.2.
Rolled back to version 4.19.1 and same issue.  4.19.0 works fine.
Hope this helps.

**Comment by filipelautert** [comment]
Hmm thanks @amazing4u ! Release 4.21.0 must have fixed it , could you check if there still any issues please?

**Comment by gigi** [comment]
Hi. Tried the latest major versions 4.21.0 and 4.21.1.

Now It seems that unique index is not considered by the diff and generates this migration:

```sql
-- liquibase formatted sql

-- changeset gigi:1682329434228-1
ALTER TABLE public."user" DROP CONSTRAINT user_nickname_idx;
```

Here is the index declaration:
https://github.com/gigi/gigi-spring-rest-skeleton/blob/main/src/main/java/gigi/restskeleton/model/orm/UserEntity.java#L20


PS
By the way is it possible to fix `classpath:/db/changelog.yaml does not exist` somehow when running `./gradlew changelogSync`?
```
Caused by: liquibase.exception.ChangeLogParseException: classpath:/db/changelog.yaml does not exist
        at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:31)
        at liquibase.command.core.helpers.DatabaseChangelogCommandStep.getDatabaseChangeLog(DatabaseChangelogCommandStep.java:100)
        at liquibase.command.core.helpers.DatabaseChangelogCommandStep.run(DatabaseChangelogCommandStep.java:77)
        at liquibase.command.CommandScope.execute(CommandScope.java:212)
        ... 17 more
```

**Comment by filipelautert** [comment]
Hi! Seems it has been fixed for an year now, please reopen if the issue persists.
