### ISSUE TITLE
#1290 introduced a breaking change that cannot be fixed/

### ISSUE THREAD

**Issue by SandorArpa** [liquibase/liquibase#4053]
### Search first

- [X] I searched and no similar issues were found

### Description

https://github.com/liquibase/liquibase/pull/3397 has introduced a breaking change. There is no way to fix the break or do a workaround. Liquibase 4.20.0 contains a security update that we are unable to update to.
Having the author enforced means that we could not update to 4.19.0 and 4.20.0. See our existing migrations.xml:
https://github.com/alphagov/pay-connector/blob/master/src/main/resources/migrations.xml
We have never included the author, left it blank as it was not a requirement. Enforcing the author breaks the md5sum of the change set and thus Liquibase thinks it's a new one.
Exception:
`liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset`

### Steps To Reproduce

Run a [migrations.xml](https://github.com/alphagov/pay-connector/blob/master/src/main/resources/migrations.xml) with Liquibase version 4.18.0. Then update to version 4.20.0. Try to run the migrations set again. It will break, saying that:
`ChangeSet Author is empty, migrations.xml::build gateway table::`. Add an author to the ChangeSets, for example author="joe.bog". Run migrations again, it will try to run all ChangeSets as the md5sum does not match.

### Expected/Desired Behavior

Expected behaviour is either do not enforce author for already ran changesets, or have the option to ignore empty author field.

### Liquibase Version

4.19.0

### Database Vendor & Version

PostGres 11.5

### Liquibase Integration

dropwizard-migrations 2.1.4

### OS and/or Infrastructure Type/Provider

Ubuntu, MacOS

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
Hello @SandorArpa - thanks for the report. We are fixing it with https://github.com/liquibase/liquibase/pull/4044 that will be release with Liquibase 4.21 .

**Comment by SandorArpa** [comment]
> Hello @SandorArpa - thanks for the report. We are fixing it with #4044 that will be release with Liquibase 4.21 .

Thank you very much @filipelautert! We're really appreciate your unbelievable quick response 🙏
