### ISSUE TITLE
liquibase 4.20.0 ms sql server case sensitive issue with sys.extended_properties

### ISSUE THREAD

**Issue by steffb74** [liquibase/liquibase#4096]
### Search first

- [X] I searched and no similar issues were found

### Description

Hi there!

Looking at 

liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetTableRemarksGenerator.java

I can see in line 47 that SYS.EXTENDED_PROPERTIES is coded in upper case. MS SQL Server defines its internal schemas and tables in lower case

https://learn.microsoft.com/en-us/sql/relational-databases/system-catalog-views/extended-properties-catalog-views-sys-extended-properties

So when I create a table in liquibase with given remarks on a ms sql server database with case sensitive collation like Latin1_General_CS_AS I get the following error:

liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset my_changelog.xml::1::myuser:
     Reason: liquibase.exception.DatabaseException: Invalid object name 'SYS.EXTENDED_PROPERTIES'. [Failed SQL: (208) IF EXISTS(  SELECT extended_properties.value FROM SYS.EXTENDED_PROPERTIES WHERE major_id = OBJECT_ID('MYSCHEMA.MYTABLE') AND name = N'MS_DESCRIPTION' AND minor_id = 0 ) BEGIN  EXEC sys.sp_updateextendedproperty @name = N'MS_Description' , @value = N'My description' , @level0type = N'SCHEMA' , @level0name = N'MYSCHEMA' , @level1type = N'TABLE' , @level1name = N'MYTABLE' END  ELSE  BEGIN  EXEC sys.sp_addextendedproperty @name = N'MS_Description' , @value = N'My description' , @level0type = N'SCHEMA' , @level0name = N'MYSCHEMA' , @level1type = N'TABLE' , @level1name = N'MYTABLE' END]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:136)

Maybe someone could fix this.

Thank you for providing this library and greetings

steffb74

### Steps To Reproduce

Just create a changeset with createTable and a remarks in it and run it against a ms sql server case sensitive database.

### Expected/Desired Behavior

SYS.EXTENDED_PROPERTIES in liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetTableRemarksGenerator.java should be lower case

### Liquibase Version

4.20.0

### Database Vendor & Version

MS SQL Server

### Liquibase Integration

plain java

### OS and/or Infrastructure Type/Provider

Windows 10

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nvoxland** [comment]
Thanks, yes that needs to be fixed

**Comment by jccampanero** [comment]
@nvoxland Can I address this issue too?

**Comment by nvoxland** [comment]
@jccampanero That would be great! I don't know of anyone else looking at it currently

**Comment by jccampanero** [comment]
Thank you @nvoxland. I submitted a PR with a possible implementation.
