### ISSUE TITLE
TokenMgrError: Lexical error

### ISSUE THREAD

**Issue by Ourwlsg** [liquibase/liquibase#4107]
### Search first

- [X] I searched and no similar issues were found

### Description

When the sql statement field value contains Roman numerals II, an exception is thrown 【2023-04-10 11:17:30.424 [main] WARN  org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext | 559 | Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.util.grammar.TokenMgrError: Lexical error at line 8648, column 123.  Encountered: "\u2161" (8545), after : ""】

### Steps To Reproduce

INSERT INTO `std_standard_organization` VALUES (1, '001', 'Ⅱ', 'Ⅱ', 1, 9, b'1', '002', 99, 1640966400000, NULL, '/1/308/315/', b'0', 1679995673513, 1679995673513, 0);

### Expected/Desired Behavior

SQL statement field value can contain Roman numerals II

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by jccampanero** [comment]
@nvoxland I included the necessary Unicode ranges for both roman numerals and small roman numerals according to their definition in the ["Number Forms" Unicode block](https://www.compart.com/en/unicode/block/U+2150).

Probably the issue deserves the creation of some tests. Do you agree? How these tests should be performed? Do I need to define a new `changelog` with the appropriate offending insert statement for instance?
