### ISSUE TITLE
Enable Private Vulnerability Reporting

### ISSUE THREAD

**Issue by igibek** [liquibase/liquibase#4109]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by nvoxland** [comment]
Thanks for pointing out the private reporting link, we'll look into that.

In the mean time, our "new issue" page points to https://github.com/liquibase/liquibase/security/policy with the `infosec@liquibase.com` email you can use for the time being.

**Comment by filipelautert** [comment]
Hello @igibek ! Private vulnerability reporting has been enabled, thanks for  pointing out this feature.
