### ISSUE TITLE
Liquibase failed to start because no changelog

### ISSUE THREAD

**Issue by nikunjazilen** [liquibase/liquibase#4112]
### Search first

- [X] I searched and no similar issues were found

### Description

Please see the below details for issue.
**Runtime Error:**
**Description:**
Liquibase failed to start because no changelog could be found at 'classpath:/db/changelog/db.changelog-master.yaml'.
**Action:**
Make sure a Liquibase changelog is present at the configured path.

configure in application.properties.
#Liquibase config
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db.changelog/changelog-master.xml

Pom.xml
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.0</version>
        <relativePath/>
</parent>
<dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
 </dependency>
 <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-maven-plugin</artifactId>
            <version>4.3.2</version>
</dependency>

Build Success. But while run the app facing the issue. 
In source code, yaml is not available but still facing this issue. Tried so many solutions but not working at all.

Thanks for support the help in advance.

### Steps To Reproduce

Intellij IDEA Version: 2023.1

Build the project: mvn clean install -DskipTests

Run the project using Intellij IDEA IDE

### Expected/Desired Behavior

It should be run the application

### Liquibase Version

4.3.2

### Liquibase Integration

4.3.2

### OS and/or Infrastructure Type/Provider

MAC OS

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nvoxland** [comment]
At runtime, Spring Boot will look for your `db/changelog/db.changelog-master.yaml` in the application's classpath. 

I'd say to first double-check that `db/changelog/db.changelog-master.yaml` exists in the jar file. Sometimes there is something off on your build process and the file isn't getting correctly included there.

If the file does exist in the jar file, does it help to remove the `classpath:` prefix from the path? Liquibase should be ignoring that, but maybe something is not ignoring like it should be?

**Comment by Shmarkus** [comment]
The OP clearly marks that they are using XML configuration:
`spring.liquibase.change-log=classpath:db.changelog/changelog-master.xml`

I'm now having the same issue, that the change-log property has no effect on liquibase
