### ISSUE TITLE
Add Official Liquibase chocolatey package

### ISSUE THREAD

**Issue by nwcm** [liquibase/liquibase#4122]
### Search first

- [X] I searched and no similar issues were found

### Description

Chocolatey is a package manager widely used. There was someone maintaining the package of Liquibase on choco to make it available. https://community.chocolatey.org/packages/liquibase

This has seemingly been abandon. Could an official repo to support his be added to this community for maintenance? It could be automated on release.

I would be happy to assist getting this going https://docs.chocolatey.org/en-us/create/create-packages
 

### Steps To Reproduce

n/a

### Expected/Desired Behavior

n/a

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by FBurguer** [comment]
Hello! Thanks for creating this issue! We would really appreciate this contribution, how do you think we should proceed?

**Comment by lbadam** [comment]
I'm closing this out as Chocolatey is now supported and maintained as part of our regular release process.
