### ISSUE TITLE
RunAlways="true" still fails checksum errors

### ISSUE THREAD

**Issue by nvoxland** [liquibase/liquibase#4125]
### Search first

- [X] I searched and no similar issues were found

### Description

Currently, if you have just `runAlways="true"` on a changeSet it will always run, **_unless_** you change your changeset. When that happens, it throws a validation error. This is surprising to people, as they think saying `runAlways="true"` means to always run it regardless, and the reason they are often wanting it to always run it always is because they change it frequently.

See https://forum.liquibase.org/t/changelog-parameters-and-checksum-errors/639/6 as an example thread.

Currently it can be worked around by setting both `runAlways="true"` and `runOnChange="true"` but that should not be necessary.

### Steps To Reproduce

Create a changeset:

```   
 <changeSet id="1" author="example" runAlways="true">
        <outputMessage message="Hello World"/>
    </changeSet>
```
and `update` with it twice. It should output the message each time.

Change it to 
```   
 <changeSet id="1" author="example" runAlways="true">
        <outputMessage message="Hello To You"/>
    </changeSet>
```
and run `update` again. It fails with a validation error.

### Expected/Desired Behavior

The updated changeset should still run without validation error

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by jccampanero** [comment]
@nvoxland I proposed a possible solution and created a related PR. I hope it helps in the resolution of the issue.

**Comment by XDelphiGrl** [comment]
In all my nearly ten years at Liquibase, I never considered that needing to use `runOnChange=true` in conjunction with `runAlways=true` shouldn't be a requirement to leverage the `runAlways` functionality. My mind is blown!
