### ISSUE TITLE
can't find 4.21 on dockerhub

### ISSUE THREAD

**Issue by tooptoop4** [liquibase/liquibase#4134]
### Search first

- [X] I searched and no similar issues were found

### Description

can't find 4.21 on dockerhub

### Steps To Reproduce

na

### Expected/Desired Behavior

na

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by awhitford-cip** [comment]
Looks like the `github-action-generator` has not yet been updated:

https://github.com/liquibase/github-action-generator/blob/f6fac4ff945e5afe43191a62fd6604330374c912/.github/workflows/generate.yml#L7

Waiting for 4.21.1 now.

**Comment by awhitford-cip** [comment]
Liquibase GitHub Actions for version 4.21.1 are available now.
