### ISSUE TITLE
Bad link for Structured Logging documentation from Release Notes

### ISSUE THREAD

**Issue by awhitford-cip** [liquibase/liquibase#4139]
### Search first

- [X] I searched and no similar issues were found

### Description

The [Release Notes](https://github.com/liquibase/liquibase/releases/) for [v4.21.1](https://github.com/liquibase/liquibase/releases/tag/v4.21.1) and [v4.21.0](https://github.com/liquibase/liquibase/releases/tag/v4.21.0) have a link to https://docs.liquibase.com/structured-logging but that goes to a **404** page:
```
404 Not Found
 - Code: NoSuchKey
 - Message: The specified key does not exist.
 - Key: structured-logging
 - RequestId: XZ4CS9C5V44Z0NCR
 - HostId: XrDf3S/8gAsKh5t0U6HINJdu84svPykboGaTn2P7IqZDVwgDDZb84TYRL6n17+UTvSVwt97Q+q4=
An Error Occurred While Attempting to Retrieve a Custom Error Document
 - Code: NoSuchKey
 - Message: The specified key does not exist.
 - Key: 404.html
```

### Steps To Reproduce

Click on https://docs.liquibase.com/structured-logging

### Expected/Desired Behavior

Expect the link to not be broken.

### Liquibase Version

4.21.0

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
Hello @awhitford-cip - could you try again? The link is a redirect to https://docs.liquibase.com/tools-integrations/observability/structured-logging.html - "it works on my machine now"  :)

**Comment by awhitford-cip** [comment]
Works now.  Thanks!
