### ISSUE TITLE
MySQL generateChangeLog adds unnecessary precision for JSON types

### ISSUE THREAD

**Issue by OisinWard** [liquibase/liquibase#4141]
### Search first

- [X] I searched and no similar issues were found

### Description

When using generateChangelog for a MySQL database the MySQL JSON datatype is incorrectly generated as JSON(1073741824) this causes an error if you try to update with that value as it is invalid for MySQL

mysql server version 5.7.41
liquibase version: 4.20.0

Worth noting that this doesn't occur using a mariadb configured liquibase client on a MySQL server.

This is a follow on from a forum post I created: https://forum.liquibase.org/t/liquibase-generate-changelog-doesnt-work-with-mysql/8059

### Steps To Reproduce

Create the following table
```
CREATE TABLE `liquibase_example_table` (
    id INT(11) NOT NULL AUTO_INCREMENT,
    enum_column ENUM('option1', 'option2', 'option3') NOT NULL,
    json_column JSON NOT NULL,
    text_column TEXT NOT NULL,
    INDEX text_column_idx (text_column(100)),
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```
Run create changelog and the output will have the incorrect datatype.
```
-- liquibase formatted sql

-- changeset root:1681305995631-1
CREATE TABLE liquibase_example_table (id INT AUTO_INCREMENT NOT NULL, enum_column ENUM(7) NOT NULL, json_column JSON(1073741824) NOT NULL, text_column TEXT NOT NULL, CONSTRAINT PK_LIQUIBASE_EXAMPLE_TABLE PRIMARY KEY (id));

-- changeset root:1681305995631-2
CREATE INDEX text_column_idx ON liquibase_example_table(text_column);
```

### Expected/Desired Behavior

The generatedChangelog should be similar to the original create statement so:

```
-- liquibase formatted sql

-- changeset root:1681305995631-1
CREATE TABLE liquibase_example_table (id INT AUTO_INCREMENT NOT NULL, enum_column ENUM('option1', 'option2', 'option3') NOT NULL, json_column JSON NOT NULL, text_column TEXT NOT NULL, CONSTRAINT PK_LIQUIBASE_EXAMPLE_TABLE PRIMARY KEY (id));

-- changeset root:1681305995631-2
CREATE INDEX text_column_idx ON liquibase_example_table(text_column(100));
```

### Liquibase Version

liquibase version: 4.20.0

### Database Vendor & Version

MySQL server version 5.7.41

### Liquibase Integration

CLI

### Liquibase Extensions

none

### OS and/or Infrastructure Type/Provider

Ubuntu 20.04

### Additional Context

This is a follow on from a forum post I created: https://forum.liquibase.org/t/liquibase-generate-changelog-doesnt-work-with-mysql/8059

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by OisinWard** [comment]
I found this problem occurs when using a SQL changelog as well as a xml changelog.

**Comment by nwcm** [comment]
@OisinWard this is resolved in 4.21.0
https://github.com/liquibase/liquibase/pull/3849

**Comment by OisinWard** [comment]
I re-tested on version 4.21.1 and see that this is working. Thank you @nwcm

**Comment by nwcm** [comment]
If you are using liquibase and MySQL i've found these other crucial things to be aware of

https://github.com/liquibase/liquibase/issues/4123
and 
https://github.com/liquibase/liquibase/pull/4090

**Comment by OisinWard** [comment]
Thank you very much @nwcm this is helpful. I actually discovered your issue "on update" because I was going to raise my own. I didn't know the tinyint problem so I'll investigate that. 
I found a couple of other problems in generate changelog if you're interested.
Timestamps with precision aren't generated properly: #1494 
Index prefixes don't get generated correctly: #4144
