### ISSUE TITLE
MySQL generateChangeLog does not generate index prefixes

### ISSUE THREAD

**Issue by OisinWard** [liquibase/liquibase#4144]
### Search first

- [X] I searched and no similar issues were found

### Description

When using generateChangelog for a MySQL database the MySQL index prefixes are incorrectly generated as without the precision in combination with using a text column this causes an error if you try to update with that value as it is invalid for MySQL.

For example an index text_column_idx (text_column(100)) will be INDEX text_column_idx (text_column) instead.

mysql server version 5.7.41
liquibase version: 4.20.0

This is a follow on from a forum post I created: https://forum.liquibase.org/t/liquibase-generate-changelog-doesnt-work-with-mysql/8059

This also occurs with a mariadb configured liquibase client on a MySQL server.

### Steps To Reproduce

Create the following table

```
CREATE TABLE `liquibase_example_table` (
    id INT(11) NOT NULL AUTO_INCREMENT,
    enum_column ENUM('option1', 'option2', 'option3') NOT NULL,
    json_column JSON NOT NULL,
    text_column TEXT NOT NULL,
    INDEX text_column_idx (text_column(100)),
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

Run create changelog and the output will have the incorrect datatype.

```
-- liquibase formatted sql

-- changeset root:1681305995631-1
CREATE TABLE liquibase_example_table (id INT AUTO_INCREMENT NOT NULL, enum_column ENUM(7) NOT NULL, json_column JSON(1073741824) NOT NULL, text_column TEXT NOT NULL, CONSTRAINT PK_LIQUIBASE_EXAMPLE_TABLE PRIMARY KEY (id));

-- changeset root:1681305995631-2
CREATE INDEX text_column_idx ON liquibase_example_table(text_column);
```

### Expected/Desired Behavior

The generatedChangelog should be similar to the original create statement so:

```
-- liquibase formatted sql

-- changeset root:1681305995631-1
CREATE TABLE liquibase_example_table (id INT AUTO_INCREMENT NOT NULL, enum_column ENUM('option1', 'option2', 'option3') NOT NULL, json_column JSON NOT NULL, text_column TEXT NOT NULL, CONSTRAINT PK_LIQUIBASE_EXAMPLE_TABLE PRIMARY KEY (id));

-- changeset root:1681305995631-2
CREATE INDEX text_column_idx ON liquibase_example_table(text_column(100));
```

### Liquibase Version

liquibase version: 4.20.0

### Database Vendor & Version

MySQL server version 5.7.41

### Liquibase Integration

CLI

### Liquibase Extensions

none

### OS and/or Infrastructure Type/Provider

Ubuntu 20.04

### Additional Context

MySQL docs for index prefix: https://dev.mysql.com/doc/refman/5.7/en/column-indexes.html#column-indexes-prefix

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @OisinWard , I've looked into this using liquibase version 4.20, mySQL version 5.7.41 and the JDBC connector file in version 8.0. 
The enum type is being created correctly, though the index isn't specifying the amount of characters:
```
-- liquibase formatted sql

-- changeset user:abc-1
CREATE TABLE liquibase_example_table (id INT AUTO_INCREMENT NOT NULL, enum_column ENUM('option1', 'option2', 'option3') NOT NULL, json_column JSON NOT NULL, text_column TEXT NOT NULL, CONSTRAINT PK_LIQUIBASE_EXAMPLE_TABLE PRIMARY KEY (id));

-- changeset user:abc-2
CREATE INDEX text_column_idx ON liquibase_example_table(text_column);
```

What jdbc connector version are you using? If it's not the latest, maybe try updating it and see if it fixes the enum part for you.

As for the index part, I'll continue to look into it, though it does seem to be a bug.

**Comment by OisinWard** [comment]
Hi @tati-qalified ,

I noticed the enum issue was resolved on upgrading the liquibase client. 4.21.1 was the version I had success with.

Thanks

**Comment by tati-qalified** [comment]
@OisinWard I closed this issue as one of the two things was working correctly. I opened another ticket for the index prefix bug. [Here is the link](https://github.com/liquibase/liquibase/issues/4432) if you want to follow that issue.
