### ISSUE TITLE
Add dry run functionality

### ISSUE THREAD

**Issue by dbnex14** [liquibase/liquibase#4153]
### Search first

- [X] I searched and no similar issues were found

### Description

it would be good if I can run migration in a dry run mode before running it to do actual migration in database.

### Steps To Reproduce

n/a

### Expected/Desired Behavior

a dry run would ensure my change log is properly setup as it would validate it against the specified database without apply change to the database.

### Database Vendor & Version

all supported databases

### Liquibase Integration

maven, spring boot

### OS and/or Infrastructure Type/Provider

windows

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by jccampanero** [comment]
Please, be aware that you can use [update-sql](https://docs.liquibase.com/commands/update/update-sql.html) ([examples](https://docs.liquibase.com/workflows/liquibase-community/generate-sql-update-schemas.html)) to generate a SQL file with the commands that will be applied to the database, allowing the user to review the future changes. In a certain way it resembles the proposed dry run functionality.

**Comment by dbnex14** [comment]
> Please, be aware that you can use [update-sql](https://docs.liquibase.com/commands/update/update-sql.html) ([examples](https://docs.liquibase.com/workflows/liquibase-community/generate-sql-update-schemas.html)) to generate a SQL file with the commands that will be applied to the database, allowing the user to review the future changes. In a certain way it resembles the proposed dry run functionality.

Thank you, that is exactly what I need.

**Comment by nvoxland** [comment]
Thanks for the answer, @jccampanero. I'll close this as "not needed".

**Comment by jccampanero** [comment]
You are welcome @dbnex14 , I am happy to hear that the answer was helpful.

You are welcome @nvoxland, I am glad to help.
