### ISSUE TITLE
CreateProcedureChange checksum backwards compatibility is broken

### ISSUE THREAD

**Issue by kristofdepypere** [liquibase/liquibase#4156]
### Search first

- [X] I searched and no similar issues were found

### Description

In our project we encountered a checksum validation issue when running liquibase. The version we were using is `4.19.0` and the one we tried is the latest one version `4.21.1`.

Some of our changesets suddenly get different checksums. Nothing changes except the liquibase version.

After some digging I actually found the issue:

https://github.com/liquibase/liquibase/commit/21e893129a9295cc7070235a56271c5423b43c87#diff-aad74215535ad4b70696af6f88e9501cf1865ea42dac8fbb956562fe7cefeb20L113-L119

Basically when the `liquibase.change.core.CreateProcedureChange` is serialized using StringChangeLogSerializer the output string is different from before. It now starts with:

`createProcedure:[    procedureText=....` but it was `createProcedure:[    procedureBody=....` obviously resulting in a different checksum.

### Steps To Reproduce

The description contains the root cause and code changed that caused the issue already

### Expected/Desired Behavior

As described, we expect the checksum of a given version to be backwards compatible at all times.

### Liquibase Version

4.21.1

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by matus-gazo** [comment]
Same problem here, every changeset with <createProcedure dbms="postgresql"> fails CRC check now.
Reverting from 4.21.1 to 4.20.0 fixed the issue.

**Comment by filipelautert** [comment]
Oh I see @kristofdepypere ! The documentation update added parameter `serializationType = SerializationType.DIRECT_VALUE` that wasn't there before.  So just removing it would fix the issue. I can create a PR without that, would you be able to confirm then if it really fixes the issue?

**Comment by kristofdepypere** [comment]
Yes sure, I can easily run my test again to verify if it is fixed.

**Comment by filipelautert** [comment]
Thanks @kristofdepypere . The fix can be downloaded here -> https://github.com/liquibase/liquibase/actions/runs/4754506141?pr=4161 .

**Comment by kristofdepypere** [comment]
Tested: works perfectly.

**Comment by jdussouillez** [comment]
I just discovered this issue. Before that I made a small repo to reproduce the bug if anyone is interested: https://github.com/jdussouillez/liquibase-checksum-error

I came here from this forum post which will be closed with this bug fix: https://forum.liquibase.org/t/liquibase-4-21-x-introduces-changeset-validation-error/8081/

**Comment by XDelphiGrl** [comment]
@jdussouillez, thank you for the repository that reproduces the issue. I used your repo to validate the fix for your particular use case. Looks like all will be well for you with the release of Liquibase 4.22.0 (where we are fixing many checksum issues). 

-erzsebet (QA Engineer at Liquibase)

**Comment by eickler** [comment]
@XDelphiGrl Any hint on would we could do now that 4.22.0 has been pulled back? It looks like I can't go to neither 4.21.1 nor 4.20 (for different checksum issues). So I am kind of stuck.

**Comment by XDelphiGrl** [comment]
> @XDelphiGrl So 4.22.0 complains about using the "procedureBody" property in YAML ("Must specify either 'path' or a nested procedure text in createProcedure", but "procedureText" also does not work). 4.21.0/1 compute the checksum wrong. And I can't go back to 4.20, because then loads of checksum errors are logged.
> 
> Would you happen to have a pointer on what I could do next?

@eickler, hello!

First, my sincere apologies for the confusion and frustration we introduced with the 4.22.0 release. We do our best to prevent pain for our Community but failed with this release. We are working to correct the situation.

As for the checksums issue, I suggest the following:
* Run clear-checksums using 4.22.0.
* Revert to 4.20.
* Run changelog-sync to recalculate the checksums.

The `procedureBody` issue is a separate bug. Would you mind opening an issue describing what you are seeing?

-erzsebet

**Comment by XDelphiGrl** [comment]
Please let us know if you have additional questions. I hope you have a lovely day, @eickler!
