### ISSUE TITLE
4.21.1 breaks searchPath behavior when using `loadData` command

### ISSUE THREAD

**Issue by tdillon** [liquibase/liquibase#4165]
### Search first

- [X] I searched and no similar issues were found

### Description

When referencing a changelog file in a parent directory and using the `loadData` command, Liquibase `4.21.1` appears to incorrectly set the paths for the changelog and data file.  The [README](https://gitlab.com/tdillon/liquibase-4.21.1-bug/-/blob/master/README.md) for the repo I created to reproduce this issue contains a writeup to explain the [log output](https://gitlab.com/tdillon/liquibase-4.21.1-bug/-/jobs/4157733088) from the test pipeline.

### Steps To Reproduce

See https://gitlab.com/tdillon/liquibase-4.21.1-bug for a simple reproduction of this issue.

### Expected/Desired Behavior

Liquibase would correctly reference changelogs and data files when using the `loadData` command just like it did in version `4.20.0`.

### Liquibase Version

4.21.1

### Database Vendor & Version

H2, SQL Server

### Liquibase Integration

Gradle

### OS and/or Infrastructure Type/Provider

Windows 10, Linux

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
@tdillon you can download the jar files from here: https://github.com/liquibase/liquibase/suites/13630780978/artifacts/752310734 . They are using version 0-SNAPSHOT . That said, I really don't know if it's possible to make them work with the gradle plugin or how to reference them from gradle settings.

**Comment by tdillon** [comment]
I did my best to wire up your JAR with my [simple reproduction app](https://gitlab.com/tdillon/liquibase-4.21.1-bug).  As you've mentioned, my app uses the `org.liquibase.gradle` plugin.  Here's what I found.  I get the following error when I run my simple reproduction app **update** using your JAR.  For some reason it doesn't like the `searchPath` parameter.

```
SEVERE: Unexpected error running Liquibase: Unknown option: 'searchPath'
liquibase.exception.CommandLineParsingException: Unknown option: 'searchPath'
	at liquibase.integration.commandline.Main.parseOptionArgument(Main.java:1267)
	at liquibase.integration.commandline.Main.parseOptions(Main.java:1179)
	at liquibase.integration.commandline.Main$1.run(Main.java:283)
	at liquibase.integration.commandline.Main$1.run(Main.java:229)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.integration.commandline.Main.run(Main.java:229)
	at liquibase.integration.commandline.Main.main(Main.java:165)
```

If I remove the `searchPath './'` parameter from the plugin configuration in my build.gradle the **update** command appears to work.  Somehow it appears `searchPath` isn't needed.

We only added `searchPath` to our configuration when we started having issues with `4.21.1`.  Maybe it won't be needed with your fix, but it feels odd that is erroring when `searchPath` is included.

**Comment by filipelautert** [comment]
Thanks @tdillon ! I'll move the issue for qa review and hopefully it will get included in the next release.
