### ISSUE TITLE
Liquibase checksum no longer the same since 4.21.x

### ISSUE THREAD

**Issue by NielsBerghenEveresst** [liquibase/liquibase#4168]
### Search first

- [X] I searched and no similar issues were found

### Description

Since 4.21.0, a changeset that we're running for a while now, is now returning a different checksum.
The changeset looks like this (I've added X's instead of the real names):

```
<changeSet id="XXXX" author="XXX">
        <addAutoIncrement columnDataType="BIGINT"
                          columnName="ID"
                          startWith="1"
                          tableName="XXXXX"/>
</changeSet>
```

It looks like it's an issue specifically with addAutoIncrement, since other changeSets do not have this issue.
I've found a semi-similar issue, but that's for procedures specifically:
https://github.com/liquibase/liquibase/issues/4156

I've also found someone with the same issue who posted this in the general discussions:
https://forum.liquibase.org/t/liquibase-4-21-x-introduces-changeset-validation-error/8081
    
In 4.20.0, the checksum is still the same.

### Steps To Reproduce

Create a liquibase changeset:
```
<changeSet id="XXXX" author="XXX.">
        <addAutoIncrement columnDataType="BIGINT"
                          columnName="ID"
                          startWith="1"
                          tableName="XXXXX"/>
</changeSet>
```
    

The checksum will be different in 4.20.0 compared to 4.21.x

### Expected/Desired Behavior

The checksum should stay the same

### Liquibase Version

4.21.x

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by NielsBerghenEveresst** [comment]
Sorry, nvm this ticket. There was an issue on one of our devs laptop which caused it.
Closing this ticket.

**Comment by jdussouillez** [comment]
> There was an issue on one of our devs laptop which caused it.

@NielsBerghenEveresst I have a similar issue since I upgraded to v4.21.1. See https://forum.liquibase.org/t/liquibase-4-21-x-introduces-changeset-validation-error/8081/2

Do you have more information about the issue you had on that laptop?

**Comment by jdussouillez** [comment]
Ok so my coworkers have the same issue. Can we reopen the issue?

Here's a small project to reproduce: https://github.com/jdussouillez/liquibase-checksum-error

**Comment by jdussouillez** [comment]
Ok it seems it's reported here: https://github.com/liquibase/liquibase/issues/4156
