### ISSUE TITLE
CORE-3044 breaks automatic update of old-version checksums during update operations

### ISSUE THREAD

**Issue by jamey-clari** [liquibase/liquibase#4172]
### Search first

- [X] I searched and no similar issues were found

### Description

CORE-3044 added an isUpToDateFastCheck to the Liquibase.update(Contexts, LabelExpression, boolean) method:

https://github.com/liquibase/liquibase/commit/18d3a52c43e618e9f6e7d9b0b12563fec2d57194

This was overall a wonderful addition to the library and enhancing it's performance and concurrency by avoiding expensive locking unless necessary to actually perform work.  Unfortunately this seems to have broken the library's ability to automatically update older versions of changeset checksums to newer.

1) `isUpToDateFastCheck` calls `listUnrunChangeSets` with `checkLiquibaseTables` passed as `false`.  This will now skip the call to `checkLiquibaseTables` prior to validation.  Validation (`changeLog.validate`) now fails with a `ValidationFailedException` which is NOT a subclass of `DatabaseException` and thus isn't handled in `isUpToDateFastCheck` and has the effect of blowing-up the `update` call.  Prior to the introduction of the `isUpToDateFastCheck` I believe the `Liquibase.update` method would (unless `checkLiquibaseTables` were passed as false) call `checkLiquibaseTables` and, as a side-effect, update the checksums to the new version.

Now, this breakage has two sides:

1) Upgrading Liquibase libraries when the checksum algorithm has changed now fails unless somehow an external effort is made to ignore, null-out, or update the checksums in all databases (ouch).
2) Having multiple versions of the Liquibase library with different checksum versions supported now won't attempt to downgrade checksums.

The second point above is significant to us as deployment of components is not an atomic operation for us.  For example we are currently in the process of moving from Liquibase 3.5.4 (ancient, I know) to 4.20.0.  During the 10s of minutes it will take to deploy all of our components there will be multiple components with different Liquibase versions on them connecting to our DBs and we REALLY don't want them to fight over checksum version having the 4.2.0 ones updating the checksums to v8 and the as-yet-updated 3.5.4 ones reverting that change.  I would strongly advocate that the mechanism for checksum upgrade that existed prior to being broken by the introduction of `isUpToDateFastCheck` is itself broken as it allows for the silent downgrade of checksum version.  The library should make checksum upgrade possible (maybe not implicitly as before but rather via an API call or setting of a flag to permit implicit upgrade) but should likely prohibit checksum downgrade, at least by default and with the ability to control that distinct from upgrade. 

### Steps To Reproduce

1) Start with a clean DB and a simple changelog.xml file.

2) Create a new Liquibase with your changelog file and a DB connection and then execute `Liquibase.update(new Contexts())`.

3) Execute an update directly on your `databasechangelog` table to replace the prefixes of the values of the `md5sum` column with an older value (7 for example as 8 has been in use for some time).

4) Repeat step 2 again which should be a no-op but now errors-out.

### Expected/Desired Behavior

I would expect that checksum values would be recomputed upon library upgrade.  Making such implicit upgrade contingent upon a flag would also make some sense.

I would expect that checksum values WOULD NOT BE recomputed upon library downgrade though for testing or deployment rollback purposes such functionality could be provided in a way so as to be optionally allowed.  If the latter then it MUST be possible to preclude the downgrade of checksum versions while allowing only the upgrade.

### Liquibase Version

4.20.0

### Database Vendor & Version

PostgreSQL 12, 14 (AWS Aurora)

### Liquibase Integration

Java API

### OS and/or Infrastructure Type/Provider

Ubuntu, AWS

### Additional Context

I'm not unwilling to submit a PR but I'm not sure my knowledge of the Liquibase codebase is appropriate to being able to fix this how it should be fixed.  I'm also not sure about fixing this pre 4.21 vs. post where the update commands have been entirely re-implemented or about the intentions of the community WRT when checksum upgrade should be allowed vs. downgrade (if ever).

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
Hello @jamey-clari - we did a lot of improvements to checksum upgrades on Liquibase 4.23.0 , and it involved some work around isUpToDateFastCheck. Would you mind testing this version?

**Comment by lbadam** [comment]
I'm going to close this since it has been over a year without a response. I encourage you to test on a newer version of Liquibase (latest is 4.29.2) and reopen if this is still an issue. Thanks!
