### ISSUE TITLE
Test fails on non-English locales

### ISSUE THREAD

**Issue by mkarg** [liquibase/liquibase#4216]
### Search first

- [X] I searched and no similar issues were found

### Description
```
[ERROR] Failures:
[ERROR]   CommandLineUtilsTest.getBanner:17 Condition not satisfied:

banner.contains("Starting Liquibase at")
|      |
|      false
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ##
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ##
##                                                ##
####################################################
Starte Liquibase am 11:04:41 (Version [local build] #0, kompiliert am 2023-05-05 08:56+0000)

[ERROR]   CommandLineUtilsTest.getBanner with banner disabled:29 Condition not satisfied:

banner.contains("Starting Liquibase at")
|      |
|      false
Starte Liquibase am 11:04:41 (Version [local build] #0, kompiliert am 2023-05-05 08:56+0000)
```
### Steps To Reproduce

On a non-English (e. g. German) locale execute `mvn package`.

### Expected/Desired Behavior

Test succeeds.

### Liquibase Version

latest

### Database Vendor & Version

none

### Liquibase Integration

none

### Liquibase Extensions

none

### OS and/or Infrastructure Type/Provider

Windows 11

### Additional Context

Locale: DE_de

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by nvoxland** [comment]
Thanks! I did a quick PR for it

**Comment by mkarg** [comment]
> Thanks! I did a quick PR for it

Where can I pull it, I want to give it a test drive.

**Comment by mkarg** [comment]
Unfortunately there are more problems on foreign locales. Will you extend your PR to cover all of them?

**Comment by nvoxland** [comment]
That test was all I tried.  #4219 is has the branch I added it to. If you run the tests on there, what other failures do you get? And/or if you can send a patch for the other failures I can apply it to the PR

**Comment by mkarg** [comment]
Give me some days. I will try to extend your PR to cover *all* locale-specific fails.
