### ISSUE TITLE
BUG: Liquibase fails when YML changelog file has one row "databaseChangeLog:" only

### ISSUE THREAD

**Issue by TymofiiKritsak** [liquibase/liquibase#4223]
### Search first

- [X] I searched and no similar issues were found

### Description

This happens with YML changelogs only.
XML, SQL, JSON are handled fine.

### Steps To Reproduce

- Configure the database
- Configure liquibase project
- Create YML changelog file with one row only
  - `databaseChangeLog:`
- Execute `liquibase status`  

**Result:**
```
Starting Liquibase at 12:01:25 (version 4.21.1 #9070 built at 2023-04-13 20:56+0000)
Liquibase Version: 4.21.1
Liquibase Open Source 4.21.1 by Liquibase

Unexpected error running Liquibase: Could not find databaseChangeLog node

For more information, please use the --log-level flag
```

### Expected/Desired Behavior

Liquibase should not fail with `Could not find databaseChangeLog node` when YML changelog file contains `databaseChangeLog:` only.

### Test Criteria
Internal only: update `rollbackCountWithEmptyChangelogTest` to include the empty YML changelog.

### Liquibase Version

4.21.1

### Database Vendor & Version

ANY

### Liquibase Integration

NONE

### Liquibase Extensions

NONE

### OS and/or Infrastructure Type/Provider

Ubuntu

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by macorapci** [comment]
I want to solve this problem but i couldn't understand the expected behavior. Is expected behavior throwing another exception like  "databaseChangeLog node is empty" for this situation? My question may be nonsense, sorry :)

**Comment by TymofiiKritsak** [comment]
Hi @macorapci!

Liquibase status should be successful: `Liquibase command 'status' was executed successfully.`

I'm comparing the behavior of other changelog types.

You can test it yourself with **JSON** changelog:
```
{
  "databaseChangeLog": []
}
```

Or **SQL** changelog:
```
--liquibase formatted sql
```

Or **XML** changelog:
```
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog
  xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd"/>
```

Liquibase will not fail in such cases, while YML changelog gives an error.
CC @erz

**Comment by macorapci** [comment]
I did try to understand diffrence between xml and yml before opening pr. We did double check after your detailed answer. So thanks a lot @TymofiiKritsak
