### ISSUE TITLE
Console information leak

### ISSUE THREAD

**Issue by bmarwell** [liquibase/liquibase#4274]
### Search first

- [ ] I searched and no similar issues were found

### Summary

Reported as https://github.com/liquibase/liquibase/issues/2396

I beliebe not being able to have the loggers configured is a vulnerability, as it unexpectedly leaks information to system administrators. Personally, I want to send everything to logstash and have nothing on disk.

### Details

See my comment in https://github.com/liquibase/liquibase/issues/2396 when you introduced it.

### Impact

Everyone, see https://github.com/liquibase/liquibase/issues/2396.

### Steps To Reproduce

not needed - default in liquibase.

### Expected/Desired Behavior

no logs on  console

### Liquibase Version

any

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment]
@tati-qalified - please verify that this is still the behavior in the latest release, and let me know so I can pass it to development for guidance if it is.

**Comment by tati-qalified** [comment]
@bmarwell It seems like there's a PR currently in the works, but it has only been 3 days since it was submitted, so I believe the best option is to wait and see if it gets merged. I will let you know as soon as there's an update on this.

**Comment by KonradHoeffner** [comment]
The mentioned PR is merged now, does this mean this issue is resolved?

**Comment by tati-qalified** [comment]
Yes, the fix was released with the latest Liquibase version, 4.25.0. [Here's the documentation](https://docs.liquibase.com/parameters/ui-service.html) on how to change where the logs are stored. 
Let us know if you have any questions!
