### ISSUE TITLE
Typo in error output for rollback-one-changeset

### ISSUE THREAD

**Issue by PaulJulius** [liquibase/liquibase#4290]
### Search first

- [X] I searched and no similar issues were found

### Description

Using Liquibase Pro, when I execute `liquibase rollback-one-changeset --changelog-file dbchangelog.json` I get the following error:

`Error parsing command line: Invalid argument '--change-set-author': missing required argument`

If I follow those instructions and run `liquibase rollback-one-changeset --changelog-file dbchangelog.json --changeset-author PJ` I get the following error:

`Unexpected argument(s): --change-set-author, PJ`

And it tells me:

`Possible solutions: --change-exec-listener-class, --change-exec-listener-properties-file, --changelog-file, --changeset-author, --changeset-id, --changeset-path`

So, the first error should have told me that `--changeset-author` was missing, not `--change-set-author`.

### Steps To Reproduce

See the commands included above.

### Expected/Desired Behavior

`--changeset-author`  not `--change-set-author`

### Liquibase Version

4.22

### Database Vendor & Version

MongoDB Community

### Liquibase Integration

CLI

### Liquibase Extensions

mongo-db-pro

### OS and/or Infrastructure Type/Provider

Mac

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by PaulJulius** [comment]
And the same is true for 
`Invalid argument '--change-set-id': missing required argument`

That's wrong. It should be `--changeset-id`

**Comment by PaulJulius** [comment]
And the same is true for 
`Invalid argument '--change-set-path': missing required argument`

That's wrong, it should be `--changeset-path`

**Comment by tati-qalified** [comment]
Liquibase version 4.23.0 outputs the error `Invalid argument '--changeset-author': missing required argument`, and the same format for the changeset id and the changeset path. I'll be closing this issue.
