### ISSUE TITLE
Since 4.21.0, lock-improvements from PR #2190 are not effectively used anymore

### ISSUE THREAD

**Issue by troligsownder** [liquibase/liquibase#4312]
### Search first

- [X] I searched and no similar issues were found

### Description

In the PR #2190 very useful improvements to changeset locks have been made. With that, Locks are not meant to be created on each service start anymore, but instead only if changesets actually need to be executed. We've been long waiting for this and appreciate this improvement.

However, since version 4.21.0, these improvements are not effectively used anymore, because the codebase restructure of using `CommandStep`'s does now include a `LockServiceCommandStep` which doesn't contain the improvements from above mentioned PR. I believe during this code restructure, those changes where lost again. 

### Steps To Reproduce

Run deprecated `Liquibase.update()` or directly execute a `CommandScope`. The following command steps will be executed in this order: 
1. DbUrlConnectionCommandStep
2. ShowSummaryArgument
3. **LockServiceCommandStep**
4. DatabaseChangelogCommandStep
5. ChangeExecListenerCommandStep
6. **UpdateCommandStep**
7. LabelExpression

Step 3. will create a lock in any case. Step 6. does actually contain some logic to check if the changesets are up-to-date, but at this time the lock is already created by step 3.

### Expected/Desired Behavior

LockServiceCommandStep should only create locks in case UpdateCommandStep actually runs any changeset,

### Liquibase Version

4.21.0

### Database Vendor & Version

Postgres 14

### Liquibase Integration

Spring Boot

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nvoxland** [comment]
Thanks, @troligsownder . We've been refactoring some of the command code and perhaps the lock avoiding paths got lost in the new setup.

**Comment by kevin-atx** [comment]
@MalloD12 - could you inspect the code to verify the above issue? If true, how difficult would it be to return the code to the original state and correct the issue as described?

**Comment by MalloD12** [comment]
@kevin-atx We have been pair-programming with Filipe who has been more involved in the command refactoring where thse changes got lost looking at how it was the best option to come back to have a similar behavior we had with #2190. We came up with a different way, but we think it would end up with the same result. 

@troligsownder I'll push code changes in a bit. I would appreciate if you can pull these changes and test it in your project, before we move on with this issue.

**Comment by troligsownder** [comment]
Thanks @MalloD12, I have tested this PR and confirm that this issue is fixed for me with it. Thank you very much for the fast fixing!
