### ISSUE TITLE
Liquibase lib upgrade to 4.21.1 breaking code base previous working with 4.8.0

### ISSUE THREAD

**Issue by sachin234s** [liquibase/liquibase#4320]
### Search first

- [X] I searched and no similar issues were found

### Description

Hi Team,

Recently we had updated the liquibase library from 4.8.0 to 4.21.1 and we are noticing the below issue when we are executing liquibase.update on a single changeset which is present externally

Caused by: liquibase.exception.DatabaseException: Error creating configured table through liquibase, error liquibase.exception.ChangeLogParseException: The file **/var/opt/SIU/tracing_data_15.xml** was not found in the configured search path:

<lib_path>/commons-text-1.10.0.jar
<lib_path>/derbyclient-10.15.2.0.jar
<lib_path>/extension-1.0.1-SNAPSHOT-patched.jar
<lib_path>/liquibase-core-4.21.1.jar
<lib_path>/migratedb.jar
<lib_path>/opencsv-5.7.1.jar
<lib_path>/timesten-types-1.0.1-SNAPSHOT-patched.jar
The code is simple liquibase.update below which used to work with earlier version of library

conn = _dataSource.getConnection();
Database database = DatabaseFactory
.getInstance()
.findCorrectDatabaseImplementation(new JdbcConnection(conn));
ResourceAccessor resourceAccessor = new StreamResourceAccessor(Files.readString(path));
liquibase = new Liquibase(tracingFilePath, resourceAccessor, database);
liquibase.validate();
liquibase.update("");

could you please help me to proceed?

### Steps To Reproduce

1. In unix place the tracing_data_15.xml in /var/opt/SIU/ dir
2. place the lib with below code and dependencies in /opt/test directory
    conn = _dataSource.getConnection();
    Database database = DatabaseFactory
    .getInstance()
    .findCorrectDatabaseImplementation(new JdbcConnection(conn));
    ResourceAccessor resourceAccessor = new StreamResourceAccessor(Files.readString(path));
    liquibase = new Liquibase(tracingFilePath, resourceAccessor, database);
    liquibase.validate();
    liquibase.update("");

3. Running the above jar fails with liquibase 4.21.1 library with below exception
        Caused by: liquibase.exception.DatabaseException: Error creating configured table through liquibase, error liquibase.exception.ChangeLogParseException: The file **/var/opt/SIU/tracing_data_15.xml** was not found in the configured search path:
        
<lib_path>/commons-text-1.10.0.jar
<lib_path>/derbyclient-10.15.2.0.jar
<lib_path>/extension-1.0.1-SNAPSHOT-patched.jar
<lib_path>/liquibase-core-4.21.1.jar
<lib_path>/migratedb.jar
<lib_path>/opencsv-5.7.1.jar
<lib_path>/timesten-types-1.0.1-SNAPSHOT-patched.jar
        The code is simple liquibase.update below which used to work with earlier version of library

4. However the code succeeds with liquibase 4.8.0 library.

### Expected/Desired Behavior

our product code should work as expected and succeed with liquibase 4.21.1 library

### Liquibase Version

4.21.1

### Database Vendor & Version

mysql 8.0.23

### Liquibase Extensions

liquibase-core

### OS and/or Infrastructure Type/Provider

RHEL 8.7

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by nvoxland** [comment]
This may be fixed in 4.22.0 or master. We'll double check

**Comment by sachin234s** [comment]
we were able to overcome the above error and our application worked with 4.21.1 lib after implementing getAll method in a our custom accessor. Here is the snippet below which worked

conn = _dataSource.getConnection();
Database database = DatabaseFactory
.getInstance()
.findCorrectDatabaseImplementation(new JdbcConnection(conn));
**ResourceAccessor resourceAccessor = new StreamResourceAccessor(Files.readString(path));**
**resourceAccessor.getAll(tracingFilePath);**
liquibase = new Liquibase(tracingFilePath, resourceAccessor, database);
liquibase.validate();
liquibase.update("");


now in our custom accessor implementation overide getall mwthod

private class StreamResourceAccessor extends AbstractResourceAccessor {
        private String tracingChangeLog;
        public StreamResourceAccessor(String traceData) {
            super();
            this.tracingChangeLog = traceData;
        }
**@Override
        public List<Resource> getAll(String absPath) throws IOException {
            List<Resource> resources = new ArrayList<>();
            File file = new File(absPath);
            if (file.isFile()) {
                if(logger.isLoggable(Level.DEBUG4))
                    logger.logDebug4(String.format("getall adding [%s] to pathresource",file.getAbsolutePath()));
                Path path = Path.of(file.getAbsolutePath());
                resources.add(new PathResource(file.getAbsolutePath(),path));
            }

            if(logger.isLoggable(Level.DEBUG4))
                logger.logDebug4("final resource list : "+resources.size());
            return resources;
        }**
}


After implementing getAll , the custom changeset present in /var/opt/SIU/tracing_data_15.xml gets executed as expected.

Strange but seem to work for the moment

**Comment by filipelautert** [comment]
Hello @sachin234s ! There were some changes around Liquibase 4.14 , so I think you can resolve your issue by using `SearchPathResourceAccessor `instead of .`StreamResourceAccessor `.  Could you try the following:

```
SearchPathResourceAccessor resourceAccessor = new SearchPathResourceAccessor(
                new DirectoryResourceAccessor(Paths.get("/").toAbsolutePath().toFile()));
liquibase = new Liquibase(tracingFilePath, resourceAccessor, database);
```

Or to be more restrictive: 

```
tracingFilePath = "tracing_data_15.xml ";
SearchPathResourceAccessor resourceAccessor = new SearchPathResourceAccessor(
                new DirectoryResourceAccessor(Paths.get("/var/opt/SIU/").toAbsolutePath().toFile()));
liquibase = new Liquibase(tracingFilePath, resourceAccessor, database);
```

Or even maybe just `new SearchPathResourceAccessor("/"))` could work.

**Comment by sachin234s** [comment]
> Hello @sachin234s ! There were some changes around Liquibase 4.14 , so I think you can resolve your issue by using `SearchPathResourceAccessor `instead of .`StreamResourceAccessor `. Could you try the following:
> 
> ```
> SearchPathResourceAccessor resourceAccessor = new SearchPathResourceAccessor(
>                 new DirectoryResourceAccessor(Paths.get("/").toAbsolutePath().toFile()));
> liquibase = new Liquibase(tracingFilePath, resourceAccessor, database);
> ```
> 
> Or to be more restrictive:
> 
> ```
> tracingFilePath = "tracing_data_15.xml ";
> SearchPathResourceAccessor resourceAccessor = new SearchPathResourceAccessor(
>                 new DirectoryResourceAccessor(Paths.get("/var/opt/SIU/").toAbsolutePath().toFile()));
> liquibase = new Liquibase(tracingFilePath, resourceAccessor, database);
> ```
> 
> Or even maybe just `new SearchPathResourceAccessor("/"))` could work.

the suggested code snippet does seem to work and program succeeds, **however getting the same exception when rollback is executed**

For eG:

```
String tracingFilePath = "tracing_data_15.xml";
            SearchPathResourceAccessor resourceAccessor = new SearchPathResourceAccessor(
                    new DirectoryResourceAccessor(Paths.get("C:\\SIU_1011_RC3\\var\\").toAbsolutePath().toFile()));
            Liquibase liquibase = new Liquibase(tracingFilePath, resourceAccessor, database);
            liquibase.validate();
            liquibase.rollback("tracing_data_15_create", "");
```


when executed throws exception as below

Jun 20, 2023 3:31:28 PM liquibase
INFO: Parsed changelog file 'tracing_data_15.xml'
Jun 20, 2023 3:31:28 PM liquibase.changelog
INFO: Reading from siu20.DATABASECHANGELOG
Jun 20, 2023 3:31:29 PM liquibase.lockservice
INFO: Successfully acquired change log lock
Jun 20, 2023 3:31:29 PM liquibase.lockservice
INFO: Successfully released change log lock
Jun 20, 2023 3:31:29 PM liquibase.command
INFO: Command execution complete
Error updating database: liquibase.exception.ChangeLogParseException: The file tracing_data_15.xml was not found in the configured search path:
**More locations can be added with the 'searchPath' parameter.
liquibase.exception.CommandExecutionException: liquibase.exception.ChangeLogParseException: The file tracing_data_15.xml was not found in the configured search path:
More locations can be added with the 'searchPath' parameter.
	at liquibase.command.CommandScope.execute(CommandScope.java:235)
	at liquibase.Liquibase.rollback(Liquibase.java:734)
	at liquibase.Liquibase.rollback(Liquibase.java:717)
	at liquibase.Liquibase.rollback(Liquibase.java:712)
	at liquibase.Liquibase.rollback(Liquibase.java:696)
	at TestProg3.main(TestProg3.java:44)**
Caused by: liquibase.exception.ChangeLogParseException: The file tracing_data_15.xml was not found in the configured search path:
More locations can be added with the 'searchPath' parameter.
	at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:114)
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:15)
	at liquibase.command.core.helpers.DatabaseChangelogCommandStep.getDatabaseChangeLog(DatabaseChangelogCommandStep.java:100)
	at liquibase.command.core.helpers.DatabaseChangelogCommandStep.run(DatabaseChangelogCommandStep.java:77)
	at liquibase.command.CommandScope.execute(CommandScope.java:212)
	... 5 more


could you please help

**Comment by filipelautert** [comment]
Thanks ! I just posted on https://github.com/liquibase/liquibase/issues/4406 and I'll close this one so we can follow up there.
