### ISSUE TITLE
liquibase fails when changelog-lock-wait-time-in-minutes is set to 0 and no lock exists

### ISSUE THREAD

**Issue by jgarec** [liquibase/liquibase#4325]
### Search first

- [X] I searched and no similar issues were found

### Description

We want to fail immediately if a lock exists in the database, so we try to set : changelog-lock-wait-time-in-minutes to 0.

If there is a lock, it fails immediately which is the expected behaviour.
The problem is when the paramater is set to 0 and no lock exists in the database : it fails with an error : `Could not acquire change log lock.  Currently locked by UNKNOWN`

### Steps To Reproduce

Just set changelog-lock-wait-time-in-minutes to 0 and test on a database not locked

### Expected/Desired Behavior

If a lock is present => exit immediately
If a lock is not present => acquire the lock and continue

### Liquibase Version

4.22.0

### Liquibase Integration

CLI in docker

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by jgarec** [comment]
I can submit a PR similar to : https://github.com/liquibase/liquibase-mongodb/pull/375/files

**Comment by nvoxland** [comment]
Yes, if you could submit a PR we'd greatly appreciate it @jgarec ! Thanks
