### ISSUE TITLE
Remove 4.22.0 from homebrew

### ISSUE THREAD

**Issue by Ygilany** [liquibase/liquibase#4359]
### Search first

- [X] I searched and no similar issues were found

### Description

Since v4.22.0 is removed from the releases, you may need to revert back the release on [homebrew](https://formulae.brew.sh/formula/liquibase). It installed 4.22.0 by default

### Steps To Reproduce

installing liquibase from [homebrew](https://formulae.brew.sh/formula/liquibase)

### Expected/Desired Behavior

should receive the latest stable liquibase 4.21.1

### Liquibase Version

4.22.0 - 4.21.1

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment]
Homebrew now installs the latest version of Liquibase 4.24.0. Closing this issue.
