### ISSUE TITLE
liquibase tag is not working properly while using liquibase version 4.21.1

### ISSUE THREAD

**Issue by himanshu9891** [liquibase/liquibase#4366]
### Search first

- [X] I searched and no similar issues were found

### Description

liquibase tag is not working properly while use liquibase version 4.21.1

Scenario: Created new database and first time started deployment using liquibase tag command. Got below error. Then same scenario replicated with liquibase 4.18 that worked.

```
Starting Liquibase at 14:28:31 (version 4.21.1 #9070 built at 2023-04-13 20:56+0000)
Liquibase Version: 4.21.1
Liquibase Open Source 4.21.1 by Liquibase

Unexpected error running Liquibase: Expected single row from liquibase.statement.core.SelectFromDatabaseChangeLogLockStatement@61af1510 but got 0
  - Caused by: Empty result set, expected one row

For more information, please use the --log-level flag
```

### Steps To Reproduce

Scenario: Created new database and first time started deployment using liquibase tag command. Got below error. Then same scenario replicated with liquibase 4.18 that worked.

```
Starting Liquibase at 14:28:31 (version 4.21.1 #9070 built at 2023-04-13 20:56+0000)
Liquibase Version: 4.21.1
Liquibase Open Source 4.21.1 by Liquibase

Unexpected error running Liquibase: Expected single row from liquibase.statement.core.SelectFromDatabaseChangeLogLockStatement@61af1510 but got 0
  - Caused by: Empty result set, expected one row

For more information, please use the --log-level flag
```

### Expected/Desired Behavior

Databasechangelog and Databasechangeloglock should be created and apply the tag in databasechangelog table.

### Liquibase Version

4.21.1

### Database Vendor & Version

PostgreSQL

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nvoxland** [comment]
Thanks, it may be related to some refactoring we did in 4.21, moving the `tag` logic into a new location.

**Comment by tati-qalified** [comment]
Hello @himanshu9891 , how are you?
I wasn't able to replicate this bug. This is what I did:
- Created a PostgreSQL database
- In a directory containing a liquibase.properties file that is pointing to that database, executed the command `liquibase tag --tag=myTag`
- This was the output:  
<img width="477" alt="works" src="https://github.com/liquibase/liquibase/assets/135264316/756605b7-6527-4600-96f0-ae688c09d418">

Also, databasechangelog and databasechangeloglock tables were created, with the only recorded data being that tag command.
<img width="728" alt="dbchangelog" src="https://github.com/liquibase/liquibase/assets/135264316/d0561a67-290c-4946-9ef3-781c33be3108">

I'd suggest that you try again in a new directory and with a new properties file, just in case, and then let us know if it worked or didn't work for you.

Thank you!
