### ISSUE TITLE
Building from release tag on git fails (v4.21 -> v4.22.0)

### ISSUE THREAD

**Issue by millenialSpirou** [liquibase/liquibase#4374]
### Search first

- [X] I searched and no similar issues were found

### Description

[ERROR] Failures:
[ERROR]   ChangeLogRewriterTest.register changelog readonly:101 Condition not satisfied:

!result.success
||      |
||      true
|<liquibase.changelog.ChangelogRewriter$ChangeLogRewriterResult@60b4d35 message=* Changelog file 'registerChangelog-7317433299045292279.xml' has been updated with changelog ID '51dd2b36-d7e5-4180-8a21-8d6a3956f332'. success=true>
false

### Steps To Reproduce

git clone
git checkout v${version}
mvn package

### Expected/Desired Behavior

tests passing

### OS and/or Infrastructure Type/Provider

docker.io/debian:bullseye

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hello @millenialSpirou . Version 4.22 was deprecated, so I tested this using version 4.23.0.
When packaging the project, some tests fail, though looking at the logs and output files, those failures aren't severe, and seem to relate to file paths being different in the code than where the project was downloaded.

You can use `-Dmaven.test.failure.ignore=true`  to complete the build even though the tests fail. There, you'll see that the project builds correctly (as in, it's only the tests that are causing the build to fail).

I will be closing this ticket as I don't think it's blocking any functionalities, though feel free to reopen it if you're having problems with it.
Thanks,
Tatiana
