### ISSUE TITLE
Prevent database-specific subclasses to interfere with executions targeting other databases

### ISSUE THREAD

**Issue by fbiville** [liquibase/liquibase#4377]
### Search first

- [X] I searched and no similar issues were found

### Description

# Subclassing use cases

The Neo4j extensions subclasses existing core changes for different purposes.

One of the purpose is to "alias" an existing element name.
For instance, `liquibase.ext.neo4j.change.CypherChange` subclasses `liquibase.change.core.RawSQLChange` so that users can write `<neo4j:cypher>...</neo4j:cypher>` instead of `<sql>...</sql>` (since SQL does not make much sense in Neo4j context).

Similarly, subclassing is also used to "alias" existing attribute names.
`liquibase.ext.neo4j.change.InsertNodeChange` subclasses `liquibase.change.core.InsertDataChange` to introduce the `labelName` attribute, as an "alias" to the RDBMS-centric `tableName` attribute: users can write `<neo4j:insert labelName="Person">...` instead of `<insert tableName="Person">...`.

Finally, subclassing is used to give complete control to the extension over what gets executed.
This is the case of `liquibase.ext.neo4j.change.LoadGraphDataChange`, subclassing `liquibase.change.core.LoadDataChange`. Here, the core logic of serializing the CSV data remains in core, but the statement creation is completely customized in the extension for Neo4j.

# Extension interference issue

The actual issue was first reported [here](https://github.com/liquibase/liquibase-neo4j/issues/413).

The problem occurs when database-specific change subclasses are available on the classpath (with a `liquibase.servicelocator.PrioritizedService#PRIORITY_DATABASE` priority) and Liquibase runs against another database (without any `dbms` filter).

In the issue above, the Neo4j extension is in the classpath and the user wants to run Liquibase against an Oracle database.

The execution path is something like this:

1.  `liquibase.command.core.helpers.DatabaseChangelogCommandStep#getDatabaseChangeLog` - which resolves the change log and its change sets
2. `liquibase.changelog.DatabaseChangeLog#handleChildNode(liquibase.parser.core.ParsedNode, liquibase.resource.ResourceAccessor, java.util.Map<java.lang.String,java.lang.Object>)` - which handles the deserialization of change log elements (like change sets and their changes)
3. `liquibase.changelog.ChangeSet#toChange` which handles the creation of the change of a given change set
4. `liquibase.plugin.AbstractPluginFactory#getPlugin`

The last listed method sorts all possible classes compatible with the requested change type by their declared priority and picks the first one.

The problem is that approach is that the class selection does not consider the target database at all.

In the issue linked above, `liquibase.ext.neo4j.change.LoadGraphDataChange` is selected as the best candidate for running `<loadData>` against Oracle and this fails, given Oracle does not support Cypher statements ([at least for now](https://github.com/oracle/pgql-lang)).

A more subtle issue is that `liquibase.ext.neo4j.change.InsertNodeChange` is also selected for `<insert>` and this specific subclass defines (well, used to define) the extra attribute `labelName` with a non-null default value (`""` instead of `null`). 
This results in a different change checksum than the one that was persisted during the first run, since the persisted checksum was obtained through `liquibase.change.core.InsertDataChange`.

### Steps To Reproduce

Do something similar to https://github.com/liquibase/liquibase-neo4j/blob/98594d36e27ab4cf775304084410829425bdfe8b/src/test/groovy/liquibase/ext/neo4j/e2e/MySQLMigrationIT.groovy#L36-L64 with the Neo4j extension on the classpath (at version `4.22.0.1`).

### Expected/Desired Behavior

Once this is fixed, I expect database-specific changes to not interfere with executions that do not target the databases they support (as defined by `liquibase.change.Change#supports`).

### Liquibase Version

all

### Liquibase Integration

core

### Additional Context

I took a quick stab at the problem: https://github.com/liquibase/liquibase/pull/4364.
My approach consisted in propagating the `Database` object to `liquibase.plugin.AbstractPluginFactory#getPlugin` and pick the first class that actually supports the database.

This solved the problem but there is a major issue.

`liquibase.plugin.AbstractPluginFactory#getPlugin` is quite central to core, and adding a `Database` parameter there ends up requiring to spread that change to too many places, like [`liquibase.parser.ChangeLogParser#parse`](https://github.com/liquibase/liquibase/pull/4364/files#diff-c81f711b7d78cdbf5efc920189930dbe69baa82175d397601bc89ad486980f25R27).

Not only is it a breaking change, it is also not a desirable one. Change log parsers should not need to know anything about target databases. Their role is just to deserialize file representation of change log into their Java `ChangeLog` counterpart.

To quote @nvoxland on the topic, here is what he said on the approach that should likely be followed:

> The longer term fix is probably around a different separation between the database-independent logic in the change logic and the database-dependent logic elsewhere.
There are many ways to do that, and it will possibly be some level of breaking API changes in there. Like if the Change type really can't be based on the database, is it better to enforce that with having generateStatements not take a database call?  Or do we want Change to be selectable based on the database and so the ChangelogParser needs to parse out to ChangeDefintions or something which hold what the user asked for but isn't database specific? Or what will work best?
Maybe even should have more of a "pipeline" style API like we have for the Command classes where there isn't a specific Change implementation for each change at all, but instead ChangeSteps or something that attach themselves to the "loadData" change?
 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by fbiville** [comment]
I just noticed today that this also happens with custom `liquibase.sqlgenerator.SqlGenerator` subclasses.

**Comment by filipelautert** [comment]
Hey - just got here. We believe it was only a Mongodb extension issue and I'm implementing this fix here: https://github.com/liquibase/liquibase/pull/4476 . 
The main fix is being done on ChangeFactory where we verify it the change supports that database - we really didn't check for this before.  And the extension needs to say which database it supports as in https://github.com/liquibase/liquibase-mongodb/blob/46977b832b52873993c7ea2d3749e363d1a8fce3/src/main/java/liquibase/ext/mongodb/change/AbstractMongoChange.java#L42 .

I went to take a look on neo4j and found out that it already implements this method, for instance: https://github.com/liquibase/liquibase-neo4j/blob/9a186d5d0893fd57378c1749f12a1e02596a9ca2/src/main/java/liquibase/ext/neo4j/change/InsertNodeChange.java#L28C1-L31C6 .I think the only problem could be that `|| super() `. 

What do you think about this solution?

**Comment by fbiville** [comment]
>  I think the only problem could be that `|| super()`.

This was added specifically to work around the issue. 
In the reported issue, some of the Neo4j subclasses was interfering with change set executions against Oracle.

#4476 LGTM. Have you tried running `ChangeLogParser` with this change? You can run [this (imperfect) utility](https://github.com/liquibase/liquibase-neo4j/blob/main/src/test/java/liquibase/ext/neo4j/ChangeLogFormatConverter.java) for instance. Happy to do it myself if that's easier for you.

**Comment by filipelautert** [comment]
Just merged to master so it can make into 4.23.1 . But I haven't tried ChangeLogParser . Could you help to run it?

**Comment by fbiville** [comment]
Works just fine, thanks!
