### ISSUE TITLE
--show-summary=false does not work

### ISSUE THREAD

**Issue by ashleymercer** [liquibase/liquibase#4418]
### Search first

- [X] I searched and no similar issues were found

### Description

The `--show-summary` flag is documented on various commands e.g. here:
https://docs.liquibase.com/commands/update/update.html

However when using it like so:

```java
new LiquibaseCommandLine().execute({
  "update",
  "--changelog-file=(...path to changelog...)",
  "--show-banner=false",
  "--show-summary=false"
});
```

I get the the following error:

```
2023-06-21 17:27:38.181 ERROR l.i.c.LiquibaseCommandLine - Unknown option: '--show-summary=false'
picocli.CommandLine$UnmatchedArgumentException: Unknown option: '--show-summary=false'
	at picocli.CommandLine$Interpreter.validateConstraints(CommandLine.java:13604)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13556)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13501)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13396)
	at picocli.CommandLine.parseArgs(CommandLine.java:1552)
	at liquibase.integration.commandline.LiquibaseCommandLine.registerValueProviders(LiquibaseCommandLine.java:567)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:350)
```

We would like to be able to switch the summary off since it interferes with e.g. build servers which expect the output to be logged in the usual way (and formatted as such) rather than dumped to System.out.

### Steps To Reproduce

As above

### Expected/Desired Behavior

It should be possible to switch the changelog summary off with using the (documented) `--show-summary=false` setting.

Or, if this setting is not and never will be supported, the documentation should remove it.

### Liquibase Version

4.21.1

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ashleymercer** [comment]
After a bit of debugging / searching around the code I've also tried the following combinations, none of which seem to work either

```
--show-summary=OFF
--show-summary OFF
--showSummary=OFF
--showSummary OFF
```

**Comment by wwillard7800** [comment]
The allowable arguments for `--show-summary` are `OFF`, `SUMMARY`, and `VERBOSE`.  I added a note to our documentation system to get that updated.

I was able to execute update by doing this:

`        new LiquibaseCommandLine().execute(new String[] {
                "--show-banner=false",
                "update",
                "--changelog-file=test.xml",
                "--show-summary=OFF"
`
`--show-banner` is a global argument, so it needs to appear in the list before the command.

**Comment by wwillard7800** [comment]
Thanks for the suggestion, but it might be more confusing to the user to try to describe the positional behavior of the exceptions.  They are allowed on either side to support legacy behavior.

Basically, the arguments which are specific to the command should go to the right, and others to the left.
