### ISSUE TITLE
Docker tags 4.23.0/4.23/latest use version 4.21.1 instead

### ISSUE THREAD

**Issue by NisStrom** [liquibase/liquibase#4442]
### Search first

- [X] I searched and no similar issues were found

### Description

Starting liquibase as a docker container, the tags 4.23.0 / 4.23 / latest use version 4.21.1 instead. If I download the 4.23.0 release from here and execute it, the version is correct.

`docker run --rm liquibase/liquibase:4.23.0 -v`
> ####################################################
> [...]
> ####################################################
> Starting Liquibase at 09:53:27 (version 4.21.1 #9070 built at 2023-04-13 20:56+0000)
> Liquibase Home: /liquibase
> Java Home /opt/java/openjdk (Version 17.0.7)
> Libraries:
> - internal/lib/commons-collections4.jar: Apache Commons Collections 4.4.0 By The Apache Software Foundation
> - internal/lib/commons-lang3.jar: Apache Commons Lang 3.12.0 By The Apache Software Foundation
> - internal/lib/commons-text.jar: Apache Commons Text 1.10.0 By The Apache Software Foundation
> - internal/lib/h2.jar: H2 Database Engine 2.1.214 By H2 Group
> - internal/lib/jaxb-api.jar: jaxb-api 2.3.1 By Oracle Corporation
> - internal/lib/jaxb-core.jar: JAXB Core 4.0.2 By Eclipse Foundation
> - internal/lib/jaxb-runtime.jar: JAXB Runtime 4.0.2 By Eclipse Foundation
> - internal/lib/jaybird.jar: Jaybird 5.0.1.java8 (build: variant=jaybird tag=v5.0.1 date=202301311336) By Firebird project
> - internal/lib/jcc.jar: IBM JCC JDBC 4 Driver 1.4.0 By IBM
> - internal/lib/liquibase-commercial.jar: Commercial Liquibase Functionality 4.21.1 By Liquibase
> - internal/lib/mariadb-java-client.jar: mariadb-java-client 3.1.3 By mariadb.com
> - internal/lib/mssql-jdbc.jar: Microsoft JDBC Driver for SQL Server 12.2.0 By Microsoft Corporation
> - internal/lib/ojdbc8.jar: JDBC 21.9.0.0.0 By Oracle Corporation
> - internal/lib/opencsv.jar: opencsv 5.7.1
> - internal/lib/picocli.jar: picocli 4.7.1 By Remko Popma
> - internal/lib/postgresql.jar: PostgreSQL JDBC Driver 42.6.0 By PostgreSQL Global Development Group
> - internal/lib/snakeyaml.jar: SnakeYAML 2.0.0
> - internal/lib/snowflake-jdbc.jar: snowflake-jdbc 3.13.29
> - internal/lib/sqlite-jdbc.jar: SQLite JDBC 3.41.2.1
> 
> 
> Liquibase Version: 4.21.1
> Liquibase Open Source 4.21.1 by Liquibase

### Steps To Reproduce

Execute the following command: `docker run --rm liquibase/liquibase:4.23.0 -v`

### Expected/Desired Behavior

Version 4.23.0 is used. Output from my local 4.23.0:
`liquibase.bat -v`

> ####################################################
> [...] 
> ####################################################
> Starte Liquibase am 12:02:26 (Version 4.23.0 #10709, kompiliert am 2023-06-23 21:18+0000)
> Liquibase Home: [...]\liquibase
> Java Home [...]\jdk-17.0.5 (Version 17.0.5)
> Libraries:
> - internal\lib\commons-collections4.jar: Apache Commons Collections 4.4.0 By The Apache Software Foundation
> - internal\lib\commons-lang3.jar: Apache Commons Lang 3.12.0 By The Apache Software Foundation
> - internal\lib\commons-text.jar: Apache Commons Text 1.10.0 By The Apache Software Foundation
> - internal\lib\h2.jar: H2 Database Engine 2.1.214 By H2 Group
> - internal\lib\hsqldb.jar: HSQLDB 2.7.2 By The HSQL Development Group
> - internal\lib\jaxb-api.jar: jaxb-api 2.3.1 By Oracle Corporation
> - internal\lib\jaxb-core.jar: JAXB Core 4.0.2 By Eclipse Foundation
> - internal\lib\jaxb-runtime.jar: JAXB Runtime 4.0.2 By Eclipse Foundation
> - internal\lib\jaybird.jar: Jaybird 5.0.1.java8 (build: variant=jaybird tag=v5.0.1 date=202301311336) By Firebird project
> - internal\lib\jcc.jar: IBM JCC JDBC 4 Driver 1.4.0 By IBM
> - internal\lib\liquibase-commercial.jar: Commercial Liquibase Functionality 4.23.0 By Liquibase
> - internal\lib\mariadb-java-client.jar: mariadb-java-client 3.1.4 By mariadb.com
> - internal\lib\mssql-jdbc.jar: Microsoft JDBC Driver for SQL Server 12.2.0 By Microsoft Corporation
> - internal\lib\ojdbc8.jar: JDBC 23.2.0.0.0 By Oracle Corporation
> - internal\lib\opencsv.jar: opencsv 5.7.1
> - internal\lib\picocli.jar: picocli 4.7.4 By Remko Popma
> - internal\lib\postgresql.jar: PostgreSQL JDBC Driver 42.6.0 By PostgreSQL Global Development Group
> - internal\lib\snakeyaml.jar: SnakeYAML 2.0.0
> - internal\lib\snowflake-jdbc.jar: snowflake-jdbc 3.13.32
> - internal\lib\sqlite-jdbc.jar: SQLite JDBC 3.42.0.0
> 
> 
> Liquibase Version: 4.23.0
> Liquibase Open Source 4.23.0 by Liquibase

### Liquibase Version

4.23.0

### Database Vendor & Version

PostgreSQL 14.3

### Liquibase Integration

CLI

### Liquibase Extensions

none

### OS and/or Infrastructure Type/Provider

Windows 11

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by NisStrom** [comment]
Further research revealed that the sha256-Digests don't match between dockerhub and what is downloaded:

Local:
`docker images --digests | select-string "liquibase"`
> liquibase/liquibase 4.23 sha256:56635f4c171e839ba4312de576959d96ee87a65f243e3519687f26e2bbc6e247 2df04dcca305 17 hours ago 355MB

Dockerhub: DIGEST:sha256:45b57752ca04cf56f46c5aebdb64c406525f961ea1a6bc0e5b40a40d54219480
![image](https://github.com/liquibase/liquibase/assets/15994669/55562a2d-beb4-4e24-8dda-708e2f6a8f84)

**Comment by filipelautert** [comment]
Hello @NisStrom - latest now points to 4.23.0 , thanks for letting us know.

**Comment by kevin-atx** [comment]
@NisStrom - thank you for this ticket. The team fixed and released an updated docker container. Please reopen if your issue is not fully resolved. Thanks!

**Comment by NisStrom** [comment]
Thanks for your help @filipelautert and @kevin-atx. I have confirmed that the 4.23-Containers now work as expected 😃.
