### ISSUE TITLE
liquibase.integration.commandline.Main clearCheckSums does not observe LIQUIBASE_COMMAND_USERNAME/LIQUIBASE_COMMAND_PASSWORD

### ISSUE THREAD

**Issue by tbrantb** [liquibase/liquibase#4456]
### Search first

- [X] I searched and no similar issues were found

### Description

I'm leveraging the `liquibase.integration.commandline.Main` class from liquibase core 4.21.1 for integration of liquibase into a larger deploy process of a couple hundred projects. Previously it grabbed username/password from environment variables and replayed them as arguments to the above class invocation via the `--username` and `--password` arguments. Our internally used environment variables are now causing warnings from liquibase since they start with `LIQUIBASE_` but are not official environment variables recognized by the new environment variable handling behavior in liquibase 4.4+. I decided to refactor our process to start relying on the official `LIQUIBASE_COMMAND_USERNAME` and `LIQUIBASE_COMMAND_PASSWORD` environment variables. This worked great for the `update` command, but fails for the `clearCheckSums` command.

This works:
```
java -cp "/mydir/liquibase-4.21.1/internal/lib/*" liquibase.integration.commandline.Main --url="jdbc:postgresql://db.acme.com:5432/mydb?currentSchema=myschema" --driver=org.postgresql.Driver --changeLogFile=db.changelog-master.xml update
```

But this fails:
```
java -cp "/mydir/liquibase-4.21.1/internal/lib/*" liquibase.integration.commandline.Main --url="jdbc:postgresql://db.acme.com:5432/mydb?currentSchema=myschema" --driver=org.postgresql.Driver --changeLogFile=db.changelog-master.xml clearCheckSums
```

with error:
```
Unexpected error running Liquibase: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:postgresql://db.acme.com:5432/mydb?currentSchema=myschema with driver org.postgresql.Driver.  The server requested SCRAM-based authentication, but no password was provided.
```

Why won't the clearCheckSum command leverage the LIQUIBASE_COMMAND_USERNAME and LIQUIBASE_COMMAND_PASSWORD environment variables?

Thanks

### Steps To Reproduce

Set LIQUIBASE_COMMAND_USERNAME environment variable
Set LIQUIBASE_COMMAND_PASSWORD environment variable

Invoke the clearCheckSums command using the liquibase.integration.commandline.Main

With something like:
```
java -cp "/mydir/liquibase-4.21.1/internal/lib/*" liquibase.integration.commandline.Main --url="jdbc:postgresql://db.acme.com:5432/mydb?currentSchema=myschema" --driver=org.postgresql.Driver --changeLogFile=db.changelog-master.xml clearCheckSums
```

Witness it give an error like `The server requested SCRAM-based authentication, but no password was provided.`

### Expected/Desired Behavior

The `clearCheckSums` command should observe and leverage the LIQUIBASE_COMMAND_USER and LIQUIBASE_COMMAND_PASSWORD environment variables and succeed in connecting to the DB just like the `update` command does.

### Liquibase Version

4.21.1

### Database Vendor & Version

PostgreSQL 14.6

### Liquibase Integration

integration class (liquibase.integration.commandline.Main)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by MalloD12** [comment]
Hi @tbrantb, 

Thank you for reporting this issue to us. We think the reason for it is we missed this command when we implemented the command refactoring and that's why `update` is behaving as expected, but `clear-checksums` doesn't. I have already created a ticket for our dev team to work on this. 

Thanks,
Daniel.

**Comment by tbrantb** [comment]
I appreciate the reply. I can't read the ticket you linked, but I noticed many of the commands will not observe the environment variables when using that integration class. I later realized that class has been deprecated. I'm working to move from a custom set of gradle functions which use this class which was borrowed from old Tim Berglund code many years ago to instead leverage the [standard liquibase gradle plugin](https://github.com/liquibase/liquibase-gradle-plugin). That plugin seems to work with all the environment variables correctly.
