### ISSUE TITLE
Checksums are not actually upgraded when `FILENAME` starts with `classpath:`

### ISSUE THREAD

**Issue by hpoettker** [liquibase/liquibase#4460]
### Search first

- [X] I searched and no similar issues were found

### Description

When a plain vanilla Spring Boot + Liquibase app is used with a file `src/main/resources/db/changelog/db.changelog-master.yaml` that contains changesets, then the persisted `FILENAME` will be `classpath:/db/changelog/db.changelog-master.yaml`.

When upgrading to Liquibase 4.23.0, then Liquibase will log that it is going to upgrade the checksum and will also log that it has successfully done so. However, that's not actually the case. All rows in `DATABASECHANGELOG` with a `FILENAME` starting with `classpath:` will not actually be updated.

The problem is that the `UPDATE` statement generated by Liquibase contains the condition `FILENAME = 'db/changelog/db.changelog-master.yaml'` which lacks the `classpath:`.

That the number of affected rows of the `UPDATE` statement is not checked to be actually 1 could also be considered as a problem.

### Steps To Reproduce

I have a full reproducer here: [hpoettker/liquibase-reproducer](https://github.com/hpoettker/liquibase-reproducer)

It is a plain vanilla Spring Boot app with `src/main/resources/db/changelog/db.changelog-master.yaml` containing

```yaml
databaseChangeLog:
  - changeSet:
      id: 0
      author: me
      changes:
        - sql:
            sql: CREATE TABLE `some_table` (`id` BIGINT)
```

The problem can be reproduced by first starting the app with e.g. Liquibase 4.17.2 and then Liquibase 4.23.0.

### Expected/Desired Behavior

The expected behavior is that all checksum are actually upgraded.

Furthermore, I'd expect that Liquibase fails fast when it tries to upgrade a checksum but the corresponding update statement does not actually affect any row.

### Liquibase Version

4.23.0

### Database Vendor & Version

MySQL 8.0.33

### Liquibase Integration

Spring Boot

### OS and/or Infrastructure Type/Provider

Ubuntu

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by vuparkar** [comment]
I wonder if this is caused by https://github.com/liquibase/liquibase/pull/4210 now using the configured changelog path instead of the normalized one.
If that is so, maybe changing the configured spring.liquibase.change-log property in your application yaml to contain the classpath: in it should resolve this

**Comment by hpoettker** [comment]
In the reproducer (and also the actual app), I don't set the property and use Spring Boot's default value, which is `classpath:/db/changelog/db.changelog-master.yaml` and already has the prefix.

Overriding this with `spring.liquibase.change-log=db/changelog/db.changelog-master.yaml` seems to be kind of a workaround for this issue. The migration works as expected and also the upgrade. So users may be able to work around this by manually removing the `classpath:/` from `DATABASECHANGELOG` and overriding the property. But I don't think this is an ideal situation.

**Comment by kevin-atx** [comment]
@filipelautert - Since this is related to recent checksum updates, I want to have you review this issue to see if it's something we need to account for as part of the checksum upgrade.

**Comment by filipelautert** [comment]
Hello @vuparkar  - in fact https://github.com/liquibase/liquibase/pull/4210#pullrequestreview-1415075133 aimed to fix this problem as we started to use file path stored in the database instead of the one generated by liquibase. And by the testers comments seems it worked.. so something else may have been changed after 4.22 provoking this. Anyway that was a good catch to give us some insight about where the problem can be, thanks!

@hpoettker - based on the issue above, are you able to test it with 4.22.0 to see if it works? This may give us some direction to find the issue.

**Comment by hpoettker** [comment]
I tested some more with my reproducer: [hpoettker/liquibase-reproducer](https://github.com/hpoettker/liquibase-reproducer)

The problem does not occur with 4.22.0. But it's reproducible with 4.23.0, 4.23.1, and the current master.

With the change in #4762, the problem seems to be fixed.

The root cause of the issue seems to be that the `UpdateChangeSetChecksumGenerator` can no longer use the `storedFilePath` as of 4.23.0 as it is not set for the change sets. The PR passes the ran change sets to the `ChangeLogIterator` such that the field is filled as it was in 4.22.0 and before.
