### ISSUE TITLE
scripts executed in historic order rather than xml order

### ISSUE THREAD

**Issue by OverDrone** [liquibase/liquibase#4462]
### Search first

- [X] I searched and no similar issues were found

### Description

Scripts are executed in order they were createed, not in order they are mentioned in xml file.

### Steps To Reproduce

1. Create xml file main.xml, include file script2.sql:
`<include file="script2.sql"/>`
2. Run whole set. Result: script2.sql executed
3. Add file script1.sql BEFORE script2.sql in file main.xml:
`<include file="script1.sql"/>`
`<include file="script2.sql"/>`
5. Run whole set over db from step 2. Result: script1.sql executed (after script2.sql executed)
6. Clear database, run whole set over clean db. Result: first script1.sql executed then script2.sql executed

### Expected/Desired Behavior

Step 4 produces error because script1.sql added before already executed script2.sql.

### Liquibase Version

4.9.1

### Additional Context

It is convenient to have several parallel sequences of sql files (current liquibase behavior). for example when they work with unrelated table sets or schemas. But if scripts work with the same schema I want to make sure that scripts are executed exact same order as they are defined in xml file or error is reported. otherwise it may lead to unexpected behavior because outcome depends on how migrations were run historically. So I suggest adding some flag for xml file that says that all scripts (cascade) referenced from this file must be executed exactly in order they are listed in xml file, if some developer adds file at start of file and tries to execute migration, he must get error message. If this flag is false (by default), keep existing liquibase behavior: run scripts in order they listed in xml file unless they already applied to database.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment]
@OverDrone - one of the core assumptions of the liquibase is that changesets are executed in the order they are listed in the changelog.

If you want a mix of independent and dependent changes, I'd suggest putting dependent changes in the same changelog and independent changes in separate changelogs. One usage pattern is to create a changelog for each feature in development, commit the changelog into source control when it's working in development, and use the Liquibase includeAll attribute to detect the changelogs located in a specific folder and deploy them.

Does this sound like it would fit your use case?

**Comment by OverDrone** [comment]
main.xml - single change log. script1.sql, script2.sql - files in change log. What you mean "same changelog"?

**Comment by kevin-atx** [comment]
@tati-qalified  - could you provide the information @OverDrone requested?

**Comment by tati-qalified** [comment]
Hi @OverDrone, regarding this statement: 

> Run whole set over db from step 2. Result: script1.sql executed (after script2.sql executed)

This doesn't mean that scripts are executed in historic order. What is actually happening is that `script2.sql` has already been run, and so the `databasechangelog` table has logged the changesets inside that script. When running `liquibase update` for a second time, those changesets will not be re-run (unless explicitly specified). 
This means that, when you run script2 and then add script1, the next `update` will only run script1. No matter if the file is included before or after script2.

When you clear the database and run it again, there are no logs in the `databasechangelog` table, so the changesets are executed in the specified order.

To check whether some change has been applied before running a new changeset, preconditions are a useful tool.
Also, there are some changeset attributes that you might find helpful, such as [runAlways](https://docs.liquibase.com/concepts/changelogs/attributes/run-always.html), [runOnChange](https://docs.liquibase.com/concepts/changelogs/attributes/runonchange.html) and [runOrder](https://docs.liquibase.com/concepts/changelogs/attributes/run-order.html).

I hope this helps, let me know if you have any questions.
Thank you,
Tatiana

**Comment by OverDrone** [comment]
> This doesn't mean that scripts are executed in historic order. 
I'm not talking about internals of liquibase, how it stores state and checks conditions, I'm talking about end result if you treat whole liquibase engine as a black box. What you described above is exactly what I'm talking about when I say "historic order" which is opposite to "xml order". You just described WHY they executed in historic order. Again if I add script1.sql before script2.sql actual order of execution should never be script2.sql, script1.sql. It always must be script1.sql, script2.sql or in case when script1.sql added later than script2.sql liquibase must detect that (databasechangelog contains record about script2.sql and doesn't contain record about script1.sql) and throw exception.

**Comment by tati-qalified** [comment]
Currently Liquibase doesn't **automatically** detect if a changeset is added before an already-ran changeset. The way to control that is via [preconditions](https://docs.liquibase.com/concepts/changelogs/preconditions.html), and it's the expected behaviour, so this isn't a bug. 

As this is something you would find useful, you could create an extension in order to implement this functionality. [Here's](https://contribute.liquibase.com/extensions-integrations/extension-guides/) some information to guide you through that process.

Let me know if you have any other questions.
Thank you,
Tatiana

**Comment by OverDrone** [comment]
you're not planning to add behavior that competitor has out of the box? You don't even want to keep it open and consider adding in future? That's just sad.
