### ISSUE TITLE
PostgreSQL generated columns get incorrect syntax during diffChangeLog operation

### ISSUE THREAD

**Issue by LonwoLonwo** [liquibase/liquibase#4464]
### Search first

- [X] I searched and no similar issues were found

### Description

This is a continuation of this ticket: https://github.com/liquibase/liquibase/issues/3494

Now in the latest version, table comparison with DDL like:

```sql
CREATE TABLE people (
    height_cm numeric,
    height_in numeric GENERATED ALWAYS AS (height_cm / 2.54) STORED
);
```

works perfectly.

but this table with DDL

```sql
CREATE TABLE users (
	fullname text NOT NULL GENERATED ALWAYS AS ((surname || ', '::text) || forename) STORED,
	surname text NOT NULL,
	forename text NOT NULL,
	CONSTRAINT pk_users_2 PRIMARY KEY (fullname)
);
```

will be transformed during the diffChangeLog command to

```sql
CREATE TABLE users (
"fullname" TEXT 'GENERATED ALWAYS AS GENERATED ALWAYS AS ((surname || '''', ''''::text) || forename) STORED STORED' NOT NULL,
"surname" TEXT NOT NULL,
"forename" TEXT NOT NULL,
CONSTRAINT "pk_users_2" PRIMARY KEY ("fullname")
);
```

And this syntax is incorrect. Probably, the connection here is with the column type TEXT, not numeric, as in the "people" table.

### Steps To Reproduce

- Create two empty schemas.
- Create a table in the first schema:

```sql
CREATE TABLE users (
	fullname text NOT NULL GENERATED ALWAYS AS ((surname || ', '::text) || forename) STORED,
	surname text NOT NULL,
	forename text NOT NULL,
	CONSTRAINT pk_users_2 PRIMARY KEY (fullname)
);
```

- Compare two schemas.

### Expected/Desired Behavior

I want to see the original table syntax for generated columns in the comparison result.

### Liquibase Version

4.23

### Database Vendor & Version

PostgreSQL 12 and higher

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hello @LonwoLonwo , I was able to replicate this issue in Liquibase version 4.23, and I also verified that this is not a problem in version 4.21 (which is the previous version, as 4.22 was deprecated).
I will be forwarding this to the development team. Thanks for letting us know!

**Comment by LonwoLonwo** [comment]
Works well on the latest version!
