### ISSUE TITLE
Docs for "include"-Tag wrong errorIfMissingOrEmpty should be errorIfMissing

### ISSUE THREAD

**Issue by XiZoR82** [liquibase/liquibase#4468]
### Search first

- [X] I searched and no similar issues were found

### Description

Tried to use "errorIfMissingOrEmpty" with the "include"-Tag as described in the Docs:
https://docs.liquibase.com/change-types/include.html

Got the error 
`Unexpected error running Liquibase: Error parsing line 19 column 115 of master_changelog.xml: cvc-complex-type.3.2.2: Attribut 'errorIfMissingOrEmpty' darf nicht in Element 'include' vorkommen.`

Mangaged to get it working with "errorIfMissing" as found here:
https://github.com/liquibase/liquibase/pull/3901/files#diff-caad0cfe7f7e032bb89425ef845e930f1c613c7e88a9a65ad2748f99f2b6b1cdL497

### Steps To Reproduce

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
        http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
        http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd"
  objectQuotingStrategy="QUOTE_ONLY_RESERVED_WORDS">

    <preConditions onFail="WARN">
        <or>
            <dbms type="oracle" />
            <dbms type="postgresql" />
        </or>
    </preConditions>

    <include file="../test/demo.xml" relativeToChangelogFile="true" errorIfMissingOrEmpty="false"/>

</databaseChangeLog>
```

### Expected/Desired Behavior

No error, if included file is missing.

### Liquibase Version

4.23

### Liquibase Integration

CLI

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment]
@XiZoR82 - thank you for catching this one. The team made the doc change and released it.
