### ISSUE TITLE
generateChangelog creates invalid changelog

### ISSUE THREAD

**Issue by mkarg** [liquibase/liquibase#4482]
### Search first

- [X] I searched and no similar issues were found

### Description

Using latest Liquibase compiled from `master` I am running `generateChangelog`, directly followed by `validate`. The result looks like this:
```
Unexpected error running Liquibase: Validierung war nicht erfolgreich:
     894 Changes erfüllten die Anforderungen während der Validierung nicht
          initiallyDeferred is not allowed on asany, dbchangelog.xml::1689061476606-280::Quipsy (generated)
          deferrable is not allowed on asany, dbchangelog.xml::1689061476606-280::Quipsy (generated)
…
```
Apparently `generateChangelog` has a bug here, because it knows that it reads from asany, so it should not create something that is unsupported on asany.

### Steps To Reproduce

```bash
liquibase generateChangelog
liquibase validate
```

### Expected/Desired Behavior

Validation should not find any problems.

### Liquibase Version

master

### Database Vendor & Version

SAP SQL Anywhere 17.0.11

### Liquibase Integration

N/A

### Liquibase Extensions

N/A

### OS and/or Infrastructure Type/Provider

Windows 10 Pro (German)

### Additional Context

N/A

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @mkarg , how are you?
For clarification, are you doing anything with your environment before running generateChangelog? Do you have an existing database with tables or other configurations? Or are you running the command straight from the compiled code?
Thanks!

**Comment by mkarg** [comment]
Hi @tati-qalified! We are an SAP OEM Partner, and since few weeks I am working on making Liquibase *much more* compatible with SQL Anywhere with the kind support of @nvoxland and @filipelautert. The particular test that lead to this bug report is a huge database with multiple schemas that more or less makes use of any specials SQL Anywhere provides (so it is rather perfect to find more or less all existing bugs). In particular we want to see if the read-part and the write-part of the SQL Anywhere support are actually compatible, or if one side lacks support for something.

**Comment by mkarg** [comment]
(Started to work on a PR fixing this issue, I assume it will be ready to review today)
