### ISSUE TITLE
Upgrade to non-deprecated `update` method results in swallowed changeset failure

### ISSUE THREAD

**Issue by zero1zero** [liquibase/liquibase#4492]
### Search first

- [X] I searched and no similar issues were found

### Description

When upgrading the method of update when running Liquibase from the Java API (using Kotlin), the behavior changes from deprecated versions of `database.update()`.  Not clear if this is intentional and I'm incorrectly using the upgraded version, or if this an unintentional breakage. Either way, hopefully this saves others time as it caused some headache and latent issues.

Old call to upgrade:

```kotlin
        val database =
            DatabaseFactory.getInstance().findCorrectDatabaseImplementation(JdbcConnection(dataSource.connection))
        val liquibase = Liquibase("/changelog.sql", ClassLoaderResourceAccessor(), database)

        liquibase.update() //deprecated
```

Upgraded:

```kotlin
        val database =
            DatabaseFactory.getInstance().findCorrectDatabaseImplementation(JdbcConnection(dataSource.connection))
        val liquibase = Liquibase("/changelog.sql", ClassLoaderResourceAccessor(), database)

        liquibase.update(Contexts(), System.out.writer())
```

In the previous version, when there was an issue with the changelog sql, an exception would be thrown:

```
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset changelog.sql::2::zack:
     Reason: liquibase.exception.DatabaseException: ERROR: syntax error at or near "name"
<snip>
```

In the new version (what I would expect was a non-breaking upgrade, but I couldn't find docs with such warnings), the failure of the changelog is quietly swallowed. Even with debug logging, I couldn't see any error.  I see:

```
INFO: ChangeSet changelog.sql::2::zack ran successfully in 18ms
Jul 13, 2023 11:23:10 AM liquibase.command
```

Simply changing that one line causes one of the two outcomes listed above.

Am I using the upgraded API wrong or is this a bug in the new `liquibase.command.core.UpdateSqlCommandStep` that the new method uses (vs the older `liquibase.command.core.UpdateCommandStep`).  

### Steps To Reproduce

Upgrade calls to `liquibase.update()` with `liquibase.update(Contexts(), System.out.writer())`.  Errors in the sql changelog are swallowed.

### Expected/Desired Behavior

An exception thrown on changeset SQL execution failure

### Liquibase Version

4.23.0

### Database Vendor & Version

PostgreSQL 14.8

### Liquibase Integration

Java API

### Liquibase Extensions

None

### OS and/or Infrastructure Type/Provider

M1

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hello @zero1zero , I've tested this issue with the updated code you've provided, and I was able to get it to work as expected (getting an exception).
Here is the relevant part of the logs, where you can see the query:
<img width="541" alt="error" src="https://github.com/liquibase/liquibase/assets/135264316/b907c973-b8d5-4e3a-a95a-257fb74abb44">

Changesets with correct syntax were ran with no issues.

I'm using Liquibase version 4.23.0, Java 17 and Gradle 7.6.1
As this issue was opened right after the 4.23 release, there may have been something blocking this functionality, but maybe updating the .jar file will help.

Would you be able to try again and let us know how it goes?
Thanks!
Tatiana

**Comment by zero1zero** [comment]
> I've tested this issue with the updated code you've provided, and I was able to get it to work as expected (getting an exception).

I'm getting the same error on that version. Was this with a .sql file changelog (what I used)? I wonder if the changelog format makes a difference in reproducing.

**Comment by tati-qalified** [comment]
Yes, it was a .sql changelog. 
I tested it again just to make sure, but it's working as it should.
Maybe there could be differences with other versions of Java or Gradle, but regarding Liquibase, it doesn't seem to be an issue anymore
