### ISSUE TITLE
LiquibaseConfiguration multi database not update

### ISSUE THREAD

**Issue by zeje** [liquibase/liquibase#4501]
### Search first

- [X] I searched and no similar issues were found

### Description

LiquibaseConfiguration multi database not update

I have multi database in a project，so i init multi SpringLiquibase.

SpringLiquibase(baseLiquibase) Bean init first 
SpringLiquibase(codegenLiquibase) Bean init second

base database has no any update（or it has update）
codegen database has some update

then I debug the springboot application， codegen database not update.

after that，i delete the baseLiquibase Bean

then I debug again.

the  codegen database  updated.

### Steps To Reproduce

`package com.pig4cloud.pigx.db;

import com.baomidou.dynamic.datasource.provider.DynamicDataSourceProvider;
import liquibase.integration.spring.SpringLiquibase;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.DependsOn;
import org.springframework.core.io.DefaultResourceLoader;

import javax.sql.DataSource;
import java.util.List;

@Configuration
public class LiquibaseConfiguration {

    @Autowired
    private List<DynamicDataSourceProvider> providers;

    @Bean
    public SpringLiquibase baseLiquibase() {
        return buildLiquibase("base");
    }

    @Bean
    @DependsOn("baseLiquibase")
    public SpringLiquibase codegenLiquibase() {
        return buildLiquibase("codegen");
    }

    private SpringLiquibase buildLiquibase(String module) {
        DataSource dataSource = providers.get(0).loadDataSources().get(module);

        SpringLiquibase liquibase = new SpringLiquibase();
        // 模块Liquibase文件路径
        liquibase.setChangeLog("classpath:liquibase/" + module + "/db.changelog.xml");
        liquibase.setDataSource(dataSource);
        liquibase.setShouldRun(true);
        liquibase.setResourceLoader(new DefaultResourceLoader());
        // 覆盖Liquibase changelog表名
        liquibase.setDatabaseChangeLogTable(module + "_changelog_table");
        liquibase.setDatabaseChangeLogLockTable(module + "_changelog_lock_table");
        return liquibase;
    }
}`

### Expected/Desired Behavior

mutli SpringLiquibase @Bean can run normal.

### Liquibase Version

4.23.0

### Database Vendor & Version

MySql 8.x

### Liquibase Integration

spring boot

### OS and/or Infrastructure Type/Provider

windows 11

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
We're currently triaging our backlog to ensure we can focus on the issues that matter most. With a large number of open issues, it becomes difficult to give each one the attention it deserves.

This issue has been closed due to inactivity — there have been no updates for over 30 days. If this is still relevant to you, please feel free to reopen it or create a new issue with updated context. We appreciate your contribution!
