### ISSUE TITLE
v9 validCheckSum not used because database contains v8

### ISSUE THREAD

**Issue by mjaggard** [liquibase/liquibase#4513]
### Search first

- [X] I searched and no similar issues were found

### Description

I have recently upgraded my database connector and Liquibase. In doing that, I had to make some changes to the SQL code being generated and I added "validCheckSum" to all of the relevant changes. This has worked fine in my test and sandbox databases but unfortunately when I came to upgrade Production I had loads of errors like the below:

> resources/changelogs/billing.xml::1398464168231-1::root (generated) was: 8:43a80adf3ed091770545c6c327ad590a but is now: 8:232fa185ac096ce7c838b2ef8a4aa2d1

which I think is because in my billing.xml file I have added v9 checksums.

### Steps To Reproduce

Create a changelog and execute it with v4.14

```
<changeSet author="root (generated)" id="1398464168231-1">
        <createTable tableName="accounts">
            <column name="id" type="CHAR(36)">
                <constraints nullable="false" primaryKey="true"/>
            </column>
            <column defaultValueNumeric="0" name="deleted" type="BIT(1)">
                <constraints nullable="false"/>
            </column>
</changeSet>
```

Change the changelog and add a valid checksum using the new v9 checksum process (example checksum only below)

```
<changeSet author="root (generated)" id="1398464168231-1">
        <validCheckSum>9:c79d3f7ed8ecea5a2edb2394932d1c46</validCheckSum>
        <createTable tableName="accounts">
            <column name="id" type="CHAR(36)">
                <constraints nullable="false" primaryKey="true"/>
            </column>
            <column defaultValueNumeric="0" name="deleted" type="BIT">
                <constraints nullable="false"/>
            </column>
</changeSet>
```

Execute the change using v4.23

### Expected/Desired Behavior

The change should accept the new checksum is the same as provided in validCheckSum even though the database contains a v8 checksum.

### Liquibase Version

4.23

### Database Vendor & Version

MySQL 8.0.33

### Liquibase Integration

CLI

### Liquibase Extensions

N/A

### OS and/or Infrastructure Type/Provider

Ubuntu

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by mjaggard** [comment]
Whilst I think the behaviour above is incorrect (it should notice the version of checksum in `validCheckSum` when validating user-provided checksums), I have found a way around the issue.

I noticed that running the new version of Liquibase with ~~no~~ minimal other changes then the checksums get updated to the latest version.

I've split my upgrade into Liquibase and MySQL changes - the former including adding missing `id` values (no idea who wrote `id=""` and thought that was a good idea)

**Comment by kevin-atx** [comment]
@mjaggard - I'm glad things are working better with the latest release. As you stated in the second comment, the most recent version of Liquibase automatically updates the checksums to the latest version. You should no longer need to manually manage checksums for a checksum version upgrade.
