### ISSUE TITLE
Liquibase 4.23.1 complains about LIQUIBASE_COMMAND_CONTEXTS variable

### ISSUE THREAD

**Issue by joschug** [liquibase/liquibase#4663]
### Search first

- [X] I searched and no similar issues were found

### Description

After upgrading from 4.23.0 to 4.23.1, we're getting warnings about the environment variable LIQUIBASE_COMMAND_CONTEXTS:

```
[2023-08-11 14:37:24] WARNING [liquibase.configuration] Potentially ignored key(s) in file exists at path liquibase.properties
 - 'liquibase.hub.mode'
WARNING:

Liquibase detected the following invalid LIQUIBASE_* environment variables:

- LIQUIBASE_COMMAND_CONTEXTS

Find the list of valid environment variables at https://docs.liquibase.com/environment-variables

[2023-08-11 14:37:24] INFO [liquibase.ui] WARNING:

Liquibase detected the following invalid LIQUIBASE_* environment variables:

- LIQUIBASE_COMMAND_CONTEXTS

Find the list of valid environment variables at https://docs.liquibase.com/environment-variables

[2023-08-11 14:37:24] WARNING [liquibase.configuration]

Liquibase detected the following invalid LIQUIBASE_* environment variables:

- LIQUIBASE_COMMAND_CONTEXTS

Find the list of valid environment variables at https://docs.liquibase.com/environment-variables
```

According to the documentation at https://docs.liquibase.com/parameters/home.html, the variable is correct and valid. It used to work until the upgrade.

### Steps To Reproduce

- set enviroment variable LIQUIBASE_COMMAND_CONTEXTS
- run ``liquibase status``

### Expected/Desired Behavior

No warning about valid variables.

### Liquibase Version

4.23.1

### Liquibase Integration

CLI

### OS and/or Infrastructure Type/Provider

macOS/Linux

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment]
Thank you for submitting. We are reviewing this issue as a potential candidate for the next sprint. (internal: https://datical.atlassian.net/browse/DAT-15681)

**Comment by ownyrd** [comment]
Is that really fixed? I am facing the same issue w/ all versions I tested (>=4.23).
LIQUIBASE_COMMAND_CONTEXTS still seems to be an invalid env var.

**Comment by MalloD12** [comment]
Hi @ownyrd,

Would you mind reopening if you think the error you are getting is directly related to this original issue, or maybe open a new one with all the details you can provide? Then, someone from the team can have a look? Also, if you wish you can also open a PR for it, if you already know what could be the cause of it.

Thanks,
Daniel.
