### ISSUE TITLE
Allow to set older check sum versions for testing

### ISSUE THREAD

**Issue by fbiville** [liquibase/liquibase#4685]
### Search first

- [X] I searched and no similar issues were found

### Description

Currently, a few parts of Liquibase core hardcodes the latest check sum version to `liquibase.ChecksumVersion.latest()` such as `liquibase.changelog.ChangeSetStatus#ChangeSetStatus` and `liquibase.changelog.RanChangeSet#RanChangeSet(liquibase.changelog.ChangeSet, liquibase.changelog.ChangeSet.ExecType, liquibase.ContextExpression, liquibase.Labels)` 

This is an issue for extension maintainers that want to automatically test check sum upgrade scenarios.

The only possible way to perform such a test today is manually run an older version of Liquibase and record the check sums of each change set used in the test.

This workaround is not ideal as it basically forces the maintainer to freeze the test change set forever or re-run an older version of Liquibase every time a test change set changes.

### Expected/Desired Behavior

I expect most classes to read the check sum version from the current scope's value named `Attr.checksumVersion.name()`.

### Steps To Reproduce

Ideally, an integration test following these steps would likely be enough to prove the changes work?

1. define a scope with a the `Attr.checksumVersion.name()` set to v1 e.g.
2. run the update command within this scope
3. check that all stored check sums start with `1:`
4. run the update command outside a scope
5. check all stored check sum start with the prefix associated with `CheckSumVersion.latest()`

### Liquibase Version

4.23.0

### Liquibase Integration

core

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment]
@filipelautert - could you share your guidance on this ticket for @fbiville when you get a chance?

**Comment by StevenMassaro** [comment]
> Hi @fbiville,
> 
> Today, I was talking to @filipelautert maybe we could add a new global configuration (in GlobalConfiguration class) to allow control of the checksum version we want to use. Something like this:
> 
> ```
> CHECKSUM_VERSION = builder.define("checkSumVersion", ChecksumVersion.class)
>                 .setDescription("")
>                 .setDefaultValue(ChecksumVersion.latest())
>                 .setHidden(true)
>                 .build();
> ```
> 
> I'm thinking having this property and some logic to avoid using very old checksum versions might work, but to be honest I'm not sure whether I could be omitting some other detail here. @filipelautert @StevenMassaro do you guys think this could help?
> 
> Thanks, Daniel.

When @filipelautert and I worked on the V9 checksum work, I originally had a property like this. We ended up removing it, and I can't remember why we decided it shouldn't exist. That reason may no longer be valid, by the way. @filipelautert do you remember why we got rid of this?

**Comment by filipelautert** [comment]
> > Hi @fbiville,
> > Today, I was talking to @filipelautert maybe we could add a new global configuration (in GlobalConfiguration class) to allow control of the checksum version we want to use. Something like this:
> > ```
> > CHECKSUM_VERSION = builder.define("checkSumVersion", ChecksumVersion.class)
> >                 .setDescription("")
> >                 .setDefaultValue(ChecksumVersion.latest())
> >                 .setHidden(true)
> >                 .build();
> > ```
> > 
> > 
> > I'm thinking having this property and some logic to avoid using very old checksum versions might work, but to be honest I'm not sure whether I could be omitting some other detail here. @filipelautert @StevenMassaro do you guys think this could help?
> > Thanks, Daniel.
> 
> When @filipelautert and I worked on the V9 checksum work, I originally had a property like this. We ended up removing it, and I can't remember why we decided it shouldn't exist. That reason may no longer be valid, by the way. @filipelautert do you remember why we got rid of this?

@StevenMassaro if I remember right we removed it because we were afraid people would start to use it to stay on v8 checksums instead of upgrading. I don't see any problems of adding it now, I just think it should be a hidden parameter such as `LIQUIBASE_LAUNCHER_PARENT_CLASSLOADER`  and having comments that this should be used only for testing purpose.

**Comment by MalloD12** [comment]
@filipelautert do you mean logging a WARN message in case someone is not using latest version?

**Comment by filipelautert** [comment]
> @filipelautert do you mean logging a WARN message in case someone is not using latest version?

@MalloD12 logging a warn message and adding the info to the description here:

```
CHECKSUM_VERSION = builder.define("checkSumVersion", ChecksumVersion.class)
                .setDescription("Use only for testing purpose, may break Liquibase stability! Something really scary here ! We do not support it in production")
                .setDefaultValue(ChecksumVersion.latest())
                .setHidden(true)
                .build();
```

**Comment by StevenMassaro** [comment]
Throwing out an alternate idea here.

We could make use the factory pattern. Create a ChecksumVersionPatternFactory. The only implementation shipped with Liquibase will be one that returns `ChecksumVersion.latest()`. If someone wants to use an older version of the checksum they will need to register a new plugin with higher priority that returns the desired checksum version. This is a heavy handed solution, but would prevent anyone from accidentally using the older version of checksums in production, while still allowing tests to set the version.

**Comment by filipelautert** [comment]
> We could use the factory pattern. Create a ChecksumVersionPatternFactory. The only implementation shipped with Liquibase will be one that returns `ChecksumVersion.latest()`. If someone wants to use an older version of the checksum they will need to register a new plugin with higher priority that returns the desired checksum version. This is a heavy handed solution, but would prevent anyone from accidentally using the older version of checksums in production, while still allowing tests to set the version.

@StevenMassaro and if we want to use it on core we could implement it in our test classes. Makes sense!

**Comment by filipelautert** [comment]
Hello @fbiville ! could you review https://github.com/liquibase/liquibase/pull/5131 ?
