### ISSUE TITLE
liquibase 4.23.1 won't work on windows if there is no JAVA_HOME system variable set

### ISSUE THREAD

**Issue by rberezen** [liquibase/liquibase#4695]
### Search first

- [X] I searched and no similar issues were found

### Description

liquibase 4.23.1 won't work on windows if there is no JAVA_HOME system variable set
when run liquibase you get the error
`Files\liquibase\\jre"" was unexpected at this time.`
caused by https://github.com/liquibase/liquibase/pull/4306

### Steps To Reproduce

- install 4.23.1 on windows machine where JAVA_HOME system variable is not set
- run liquibase

### Expected/Desired Behavior

liquibase runs fine even when JAVA_HOME system variable is not set

### Liquibase Version

4.23.1

### OS and/or Infrastructure Type/Provider

Windows

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment]
@tati-qalified - please verify that this issue is addressed by Liquibase 4.23.1 where a related issue was fixed (https://github.com/liquibase/liquibase/pull/4306).

**Comment by kevin-atx** [comment]
Thank you for the update on this issue. I am adding this ticket to the next sprint per your comment.
