### ISSUE TITLE
liquibase generates boolean columns only in ibm db2 versions with fixpack version >= 1

### ISSUE THREAD

**Issue by haltenwe** [liquibase/liquibase#4723]
### Search first

- [X] I searched and no similar issues were found

### Description

IBM DB2 supports BOOLEAN type columns as of version 11.1.1.1. We are using IBM DB2 11.5.7.0, Liquibase continues to generate SMALLINT for the columns of type BOOLEAN. In IBM DB2 with a fix pack >= 1, the correct data type is generated by Liquibase.

	<changeSet context="create" author="xxx" id="create-table_with_boolean">
		<createTable tableName="TEST_TABLE">
			<column name="ID" type="VARCHAR(36)">
				<constraints nullable="false" primaryKey="true"
					primaryKeyName="TEST_TABLEPK"></constraints>
			</column>
			<column name="NUMBER_INT" type="INT" />
			<column name="NUMBER_SMALLINT" type="SMALLINT" />
			<column name="FLAG" type="BOOLEAN" />
		</createTable>
	</changeSet>

### Steps To Reproduce

Use the changeset above with two installations of IBM DB2. One of the Installations should have Fixpack 0.

### Expected/Desired Behavior

For all versions of IBM DB2 after 11.1.1.1, Liquibase also generates the corresponding database columns of type BOOLEAN for columns that are defined as BOOLEAN in the changesets.

### Liquibase Version

4.20.0

### Database Vendor & Version

IBM DB2 LUW 11.5.7.0

### Liquibase Integration

spring boot

### OS and/or Infrastructure Type/Provider

ubuntu, windows 10

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by haltenwe** [comment]
The change should by done in liquibase.database.core.DB2Database, rows 38, 39

return getDatabaseMajorVersion() > 11
  || getDatabaseMajorVersion() == 11 && ( getDatabaseMinorVersion() == 1 && fixPack.intValue() >= 1 || getDatabaseMinorVersion() > 1 );


By the way, now it is not possible to override DB2Database (without overriding StandardLockService as well), because in liquibase.lockservice.StandardLockService, row 162, the check database.getClass().isAssignableFrom(DB2Database.class)  should be done like DB2Database.class.isAssignableFrom( database.getClass() ).

**Comment by kevin-atx** [comment]
@haltenwe - Would you be willing to submit your fix as a PR? If you do so, we'll schedule it for review and integration in the next sprint.
