### ISSUE TITLE
Incorrect docker image for liquibase 4.23.1

### ISSUE THREAD

**Issue by tomaskodaj** [liquibase/liquibase#4731]
### Search first

- [ ] I searched and no similar issues were found

### Description

In docker hub https://hub.docker.com/r/liquibase/liquibase:

docker pull liquibase/liquibase:4.23.1-alpine
and/or (tried both)
docker pull liquibase/liquibase:4.23.1

inside the image, there is not updated liquibase - there is still old version 4.23.0 

### Steps To Reproduce

docker pull liquibase/liquibase:4.23.1-alpine
docker images (get image hash)
docker run -it --rm --entrypoint=bash <imageHash>
more changelog.txt

see changelog for 4.23.0

-----

run migration with this image, see logs:

Starting Liquibase at 05:18:46 (version 4.23.0 #10709 built at 2023-06-23 21:18+0000)

### Expected/Desired Behavior

in docker tag 4.23.1, 4.23, 4.23.1-alpine, 4.23-alpine, there is correct version of liquibase (4.23.1), not the old.

### Liquibase Version

4.23.1

### Database Vendor & Version

oracle 19

### Liquibase Integration

docker image

### Liquibase Extensions

none

### OS and/or Infrastructure Type/Provider

openshift

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hello @tomaskodaj, this issue has been fixed.
Thank you!
Tatiana

**Comment by tomaskodaj** [comment]
Hello, it happened again today with release of 4.23.2 :(

**Comment by tati-qalified** [comment]
It should be corrected now!
