### ISSUE TITLE
Optimise the logic for verifying if a table is empty

### ISSUE THREAD

**Issue by tati-qalified** [liquibase/liquibase#4734]
### Search first

- [X] I searched and no similar issues were found

### Description

Originally metioned [here](https://github.com/liquibase/liquibase/issues/1549).

Currently, to check if a table is empty, Liquibase is using `JdbcExecutor.queryForInt(..)`, which isn't efficient for tables with a large number of rows. Furthermore, if a table contains more rows than the maximum Integer number, the run will fail with an exception.

### Steps To Reproduce

Create a changeSet that includes the TableIsEmpty precondition, which will call the `check` function in the RowCountPrecondition class.

If the table that the changeSet is being applied to has over Integer.MAX_VALUE rows, the run will fail with an exception.

### Expected/Desired Behavior

The method for checking if a table is empty should be something similar to checking if there is a first row or not, instead of counting all of them and seeing if the number of rows is 0.

### Liquibase Version

All

### Database Vendor & Version

All

### Liquibase Integration

All

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment]
As this ticket generally affects performance, I'm including it in the next sprint review to see if it's something we want to address.
