### ISSUE TITLE
`LabelExpression` constructed with a collection of strings is not usable for `Liquibase.*(...)`

### ISSUE THREAD

**Issue by famod** [liquibase/liquibase#4763]
### Search first

- [X] I searched and no similar issues were found

### Description

The [`LabelExpression(Collection<String>)` constructor](https://github.com/liquibase/liquibase/blob/v4.23.1/liquibase-standard/src/main/java/liquibase/LabelExpression.java#L45-L51) is not setting the `originalString` member.
This member is crucial though, as the `liquibase.Liquibase` facade is using `labelExpression.getOriginalString()` everywhere.

So when you create an expression like that it's basically useless.

### Steps To Reproduce

- create a changelog with label `foo`
- instantiate a `LabelExpression` with a collection that contains only the label string `bar`
- run `Liquibase.update(...)` with that expression object
- witness the execution of the changelog, although it shouldn't

### Expected/Desired Behavior

Label strings from a collection are evaluated properly.

### Liquibase Version

4.23.1

### Database Vendor & Version

MariaDB

### Liquibase Integration

Quarkus

### Additional Context

I ran into this issue while updating Liquibase in Quarkus from 4.20.0 to 4.23.1.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by famod** [comment]
Seems broken since 4.21.0: https://github.com/liquibase/liquibase/commit/6f8a113ad887c7ccabc9f39f161a963e8b0ced60#diff-68544baf236f867c4abf85787c970ddf1aee4802dd2ffb663ea5be6de0a28c9aR247

**Comment by kevin-atx** [comment]
@filipelautert - I'm adding this ticket as a candidate for review in the next sprint. If this is an easy fix, it seems like it would be good to address this newly introduced bug.

**Comment by MalloD12** [comment]
Thank you, @famod for reporting this issue for us. I think I have fixed this issue with #4854. I have also applied the same logic for `ContextExpression`. If you wish you can pull the commits I added in the given PR and try again, or just wait until this goes into the review process and gets merged. Any feedback is more than welcome.

Thanks,
Daniel.

**Comment by famod** [comment]
Hi @MalloD12, thanks for fixing it! I'll check when the next Liquibase update hits Quarkus.
