### ISSUE TITLE
Poor performance of listUnrunChangeSets

### ISSUE THREAD

**Issue by stevejas** [liquibase/liquibase#4776]
### Search first

- [X] I searched and no similar issues were found

### Description

When executing the Liquibase.listUnrunChangeSets method using Liquibase 4.17.2, my application is hanging for more than 5 minutes.  I took several thread dumps during this time and they all had similar stack traces to this:

> "main" #1 prio=5 os_prio=0 cpu=188203.13ms elapsed=203.45s tid=0x0000021899268ad0 nid=0x46e0 runnable  [0x000000b269bfc000]
>    java.lang.Thread.State: RUNNABLE
> 	at java.util.regex.Pattern$BmpCharProperty.match(java.base@17.0.5/Pattern.java:3954)
> 	at java.util.regex.Pattern$Start.match(java.base@17.0.5/Pattern.java:3608)
> 	at java.util.regex.Matcher.search(java.base@17.0.5/Matcher.java:1728)
> 	at java.util.regex.Matcher.find(java.base@17.0.5/Matcher.java:745)
> 	at java.util.regex.Matcher.replaceAll(java.base@17.0.5/Matcher.java:1177)
> 	at liquibase.changelog.DatabaseChangeLog.normalizePath(DatabaseChangeLog.java:781)
> 	at liquibase.changelog.DatabaseChangeLog.getChangeSet(DatabaseChangeLog.java:239)
> 	at liquibase.changelog.DatabaseChangeLog.getChangeSet(DatabaseChangeLog.java:342)
> 	at liquibase.changelog.AbstractChangeLogHistoryService.upgradeChecksums(AbstractChangeLogHistoryService.java:68)
> 	at liquibase.changelog.StandardChangeLogHistoryService.upgradeChecksums(StandardChangeLogHistoryService.java:300)
> 	at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1955)
> 	at liquibase.Liquibase$16.run(Liquibase.java:2025)
> 	at liquibase.Scope.lambda$child$0(Scope.java:180)
> 	at liquibase.Scope$$Lambda$606/0x0000000801994bb0.run(Unknown Source)
> 	at liquibase.Scope.child(Scope.java:189)
> 	at liquibase.Scope.child(Scope.java:179)
> 	at liquibase.Scope.child(Scope.java:158)
> 	at liquibase.Liquibase.runInScope(Liquibase.java:2447)
> 	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:2018)
> 	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:2009)

The problem seems to be the performance of the **DatabaseChangeLog.getChangeSet** method.  It is calling the expensive normalizePath method way more often than necessary.  I checked the latest master code and the issue is still present.

This is the code in 4.17.2:
  ```
  public ChangeSet getChangeSet(String path, String author, String id) {
        for (ChangeSet changeSet : changeSets) {
            final String normalizedPath = normalizePath(changeSet.getFilePath());
            if (normalizedPath != null &&
                    normalizedPath.equalsIgnoreCase(normalizePath(path)) &&
                    changeSet.getAuthor().equalsIgnoreCase(author) &&
                    changeSet.getId().equalsIgnoreCase(id) &&
                    isDbmsMatch(changeSet.getDbmsSet())) {
                return changeSet;
            }
        }

        return null;
    }
```
    
I believe this modified code will have greatly improved performance as it only calls normalizePath() when necessary, and only the bare minimum of times:
```
    public ChangeSet getChangeSet(String path, String author, String id) {
        String normalizedPath = normalizePath(path);
        if (normalizedPath != null) {
            for (ChangeSet changeSet : changeSets) {
                if (changeSet.getId().equalsIgnoreCase(id) &&
                           changeSet.getAuthor().equalsIgnoreCase(author) &&
                           isDbmsMatch(changeSet.getDbmsSet()) &&
                           normalizedPath.equalsIgnoreCase(normalizePath(changeSet.getFilePath()))) {
                    return changeSet;
                }
            }
        }
        return null;
    }

```    
Can you please address this performance issue?

### Steps To Reproduce

Call the liquibase.Liquibase.listUnrunChangeSets() method when the database has a non-trivial (1000+) number of change sets present in the DATABASECHANGELOG table

### Expected/Desired Behavior

I expect that liquibase.Liquibase.listUnrunChangeSets will return within a few seconds at most, not five or more minutes.

### Liquibase Version

4.17.2

### Database Vendor & Version

SQL Server 2018

### Liquibase Integration

Direct java code integration

### Liquibase Extensions

none

### OS and/or Infrastructure Type/Provider

Windows 11

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
Hello @stevejas , thanks for the report! I created PR https://github.com/liquibase/liquibase/pull/4798 to implement your suggestions and also added an extra level of checks to prevent the second call to normalizePath when not required. Could you give this PR a try?

**Comment by stevejas** [comment]
Hey @filipelautert.  Thanks for the quick work on this issue!  I can confirm that with the changes in the PR my performance issue has been resolved.  Rather than taking 5+ minutes, the operation is now taking just a few seconds.

**Comment by filipelautert** [comment]
Thanks for the feedback @stevejas !
