### ISSUE TITLE
CreateIndex Change Type - Not Loading Values for associatedWith Property

### ISSUE THREAD

**Issue by spacepost** [liquibase/liquibase#4794]
### Search first

- [X] I searched and no similar issues were found

### Description

First off, I know this is an ancient defect from long ago, but I've got a vendor supplying me with thousands of changelogs from clear back on version 2.0 of liquibase and this issue is not present in that version. Due to company policies, I can't use version 2.0 to apply their changes.

The issue I'm running into is that at some point for what appears to have been done for documentation purposes per the commit message, in the CreateIndexChange.java file for the getAssociatedWith property accessor, the annotation:

    @DatabaseChangeProperty(isChangeProperty = false,
        description = "Index associations. Valid values: primaryKey, foreignKey, uniqueConstriant, none")

was added. The effect of this is that this causes the value to no longer be consumed from the xml definition.

### Steps To Reproduce

Create a changelog with the CreateIndex type and add associatedWith="primary/foreignKey" and run against an Oracle DB (which should ignore the index entirely, but doesn't because after parsing, associatedWith is null)

### Expected/Desired Behavior

Expected behavior, load property from xml definition.

### Liquibase Version

4.23.1

### Database Vendor & Version

Oracle 19c

### Additional Context

Based on my analysis, either setting the isChangeProperty to true or removing the annotation entirely should allow the property to be read from the xml definition.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hello @spacepost, thank you for submitting a PR! We've forwarded it to the PR review team, they'll update you on the status.
