### ISSUE TITLE
modifyDataType does not work with columnName thas is a keyword

### ISSUE THREAD

**Issue by pmvelkov** [liquibase/liquibase#4795]
### Search first

- [X] I searched and no similar issues were found

### Description

I have a table with column name LOB - which is a valid name in my scenario as LOB is Line Of Business. 
I am trying to extend the column size via modifyDataType, but the alter statement is invalid.

It seems that it currently tries to execute:
`ALTER TABLE LIQUI_TEST.TEST_TABLE MODIFY LOB VARCHAR2(20 CHAR)`
which is invalid Oracle alter.
However
`ALTER TABLE LIQUI_TEST.TEST_TABLE MODIFY (LOB VARCHAR2(20 CHAR))` (wrapping it with brackets)
or 
`ALTER TABLE LIQUI_TEST.TEST_TABLE MODIFY "LOB" VARCHAR2(20 CHAR)` (wrapping it with quotes)

Liquibase does not allow any "workaround" to use modifyDataType for such columnNames
I tried wrapping with  &+quot; and '"LOB"', but it adds a "strange" amount of double quotes:
`ALTER TABLE LIQUI_TEST.TEST_TABLE MODIFY """LOB""" VARCHAR2(20 CHAR)`

### Steps To Reproduce

- Have master changeLog with single include `<include file="db/LIQUI_TEST/Tables/TEST_TABLE.xml" />`
- Have the following databaseChangeLog - TEST_TABLE.xml
`     <changeSet author="test" logicalFilePath="db/LIQUI_TEST/Tables/TEST_TABLE.xml" id="1-1">  `
`         <createTable schemaName="LIQUI_TEST" tableName="TEST_TABLE">   `
`             <column name="LOB" type="VARCHAR2(10 CHAR)">     `
`                 <constraints nullable="false" primaryKey="true" primaryKeyName="TEST_TABLE_PK"/>  `
`             </column>          `
`             <column name="SOME_COLUMN" type="VARCHAR2(100 CHAR)"/>      `
`         </createTable>                                                   `
`     </changeSet>                                        `
`                                        `
`     <changeSet author="test" logicalFilePath="db/LIQUI_TEST/Tables/TEST_TABLE.xml" id="1-2">             `
`         <modifyDataType columnName="LOB" newDataType="VARCHAR2(20 CHAR)" schemaName="LIQUI_TEST" tableName="TEST_TABLE"/>   `
`     </changeSet>                      `

### Expected/Desired Behavior

Column LOB to be modified and extended.

### Liquibase Version

4.23.1

### Database Vendor & Version

Oracle Version 19.16.0.0

### OS and/or Infrastructure Type/Provider

Windows 10

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hello @pmvelkov, I was able to verify this bug with versions 4.20.0 to 4.23.1.
This issue needs to be reviewed in order to evaluate how to move forward.

**Comment by kevin-atx** [comment]
@pmvelkov - could you try setting the [objectQuotingStrategy](https://docs.liquibase.com/concepts/changelogs/attributes/objectquotingstrategy.html) attribute in your changelog file to either QUOTE_ONLY_RESERVED_WORDS or QUOTE_ALL_OBJECTS to see if that addresses your issue?

**Comment by pmvelkov** [comment]
Hello,
Thank you for your suggestion. 
On Oracle I was able to change the column when used QUOTE_ALL_OBJECTS on changeSet level. I was unable to do so when QUOTE_ONLY_RESERVED_WORDS as LOB is not recognized as reserved word (I am guessing).

However, I am aiming for agnostic solution as the changeSet should be executable on both Oracle and EDB. 

In EDB v15 QUOTE_ALL_OBJECTS does not work, as EDB/Postgresql take quotes too serious, meaning that It try to find schema "LIQUI_TEST" (with the quotes). But here QUOTE_ONLY_RESERVED_WORDS does the job, as LOB is recognized reserved word . I know that I can define different changeSet for each dbms, but I want to not split the codebase for such type of changes.

**Comment by tati-qalified** [comment]
Hi @pmvelkov, I've been trying to find a way to make one changeset work for both databases in the situation you've described, but unfortunately I don't think it's possible. As you've said, an option is to create two separate changesets and use preconditions to set the database type for which they will run.

Another option would be to create an extension so that you can add words to the `QUOTE_ONLY_RESERVED_WORDS` list, though that would take some coding on your part.

I'll be closing this ticket as it's not something we can fix. If you're willing to create a PR to add the functionality I mentioned, feel free to comment here so we can provide you with guidance.

Thank you,
Tatiana
