### ISSUE TITLE
Update does not change database

### ISSUE THREAD

**Issue by danielrwhite74** [liquibase/liquibase#4806]
### Search first

- [X] I searched and no similar issues were found

### Description

Upgrading liquibase to 4.23.1 and resolving the method calls that are now deprecated.

When performing a liquibase update using `update(Contexts contexts, LabelExpression labelExpression, Writer output)` the database is never updated. The SQL commands that should have been executed by the database are present in the `Writer` passed to the `update` method.

Changing the code that performs the update to call `update(Contexts contexts, LabelExpression labelExpression)` (which is now deprecated) results in the database successfully being updated.

### Steps To Reproduce

Unable to include actual files

### Expected/Desired Behavior

Database is updated.

### Liquibase Version

4.23.1

### Database Vendor & Version

Oracle 19c

### Liquibase Integration

java

### Liquibase Extensions

none

### OS and/or Infrastructure Type/Provider

windows

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by joaopaulosilvasimoes** [comment]
I have a similar issue, creating programmatically using "Spring Liquibase" and the "afterPropertiesSet" method.

New migrations are not being recognized, only when creating a new database, never when updating.

After many attempts I did an isolated test, I tested all releases from the most recent to the oldest.

And the correct operation happened in version 4.20.0 (March / 2023).

That is, from this one, at least, the error is (4.23.1, 4.23.0, 4.22.0, 4.21.1, 4.21.0).

I got to test the 4.8.0 (February / 2022) and it worked correctly too.

Hope this helps.

**Comment by tati-qalified** [comment]
Hello @danielrwhite74, thank you for submitting a ticket.

I haven't been able to reproduce this bug, using Spring Boot v3.1.3 and Liquibase v4.23.1. The `liquibase.update` function worked for me. 

It's important to note that the entire `.update()` section has been deprecated, not only the ones that take just the contexts and labelExpressions. [Here's](https://docs.liquibase.com/workflows/liquibase-community/using-liquibase-java-api.html) the documentation for the new way to update your database.

Would any of you be able to provide some sample code or steps to reproduce this bug?
Thank you
Tatiana

**Comment by danielrwhite74** [comment]
@tati-qalified,

Thanks for the info. I didn't realize that the update methods that take a writer should not be used (they don't have the Deprecated annotation).
I have switched my code over to using the Scope method (per the linked documentation) and everything appears to be working.

Thanks,
Daniel

**Comment by tati-qalified** [comment]
I'm glad it's working now! I'll let the team know that the documentation should be updated.
