### ISSUE TITLE
rollbackEndDelimiter functionality referenced in docs, but appears to be missing

### ISSUE THREAD

**Issue by rdhzl** [liquibase/liquibase#4821]
### Search first

- [X] I searched and no similar issues were found

### Description

I am leveraging Liquibase to replace a Postgres function like the following with a new version, using the XML DSL and the `<sql endDelimiter="/" >` tag:

```
        <sql endDelimiter="/" >
            <![CDATA[
                CREATE OR REPLACE FUNCTION db.nx(type_id bigint, shard_id bigint, seq_id bigint) RETURNS bigint
                    LANGUAGE plpgsql
                    AS $$
                    DECLARE
                    result BIGINT;
                    BEGIN
                    IF shard_id < 0 OR shard_id > ((1 << 10) - 1) THEN
                        SELECT nextval('db.sq_s_id') INTO shard_id;
                    END IF;
                    result := 0 | (type_id << (64 - 10));
                    result := result | (shard_id << (64 - 10 - 10));
                    result := result | (seq_id);
                    RETURN result;
                    END;
                $$;
                /
            ]]>
        </sql>
```

I have a similar `<rollback>` tag with the intent to undo the replacement by reverting to the prior version of the function. However the rollback fails because it doesn't know how to deal with the '$$': `liquibase.exception.DatabaseException: Unterminated dollar quote`

I see reference to `rollbackEndDelimiter` here in the [docs](https://docs.liquibase.com/change-types/enddelimiter-sql.html), here in the [code](https://github.com/search?q=repo%3Aliquibase%2Fliquibase%20rollbackEndDelimiter&type=code), and a few references on [SO](https://stackoverflow.com/search?q=rollbackEndDelimiter) however that property doesn't exist in the XSD.

~~Is this no longer supported and the docs are stale, or is there a miss? Open to suggestions as to how to accomplish what I'm trying to do otherwise.-~

**EDIT: It seems like this is perhaps a doc error and an error on my part. My rollback tag contained the raw function declaration we want to rollback to, not enclosed by `<sql>` tags. I just tried nesting that code in a `<sql>` tag with the `endDelimiter` property and seems to get me to where I want to be, ie: `<rollback><sql endDelimiter="/" >...</sql></rollback>`. I guess the `<rollback>` tag supports SQL content with/without the `<sql>` child node because we definitely have other, simpler, rollbacks defined that way.**

Thank you!

### Steps To Reproduce

N/A

### Expected/Desired Behavior

The ability to specify rollback SQL for complex/multiline functions.

### Liquibase Version

4.23

### Database Vendor & Version

PostgreSQL 15.4

### Liquibase Integration

Java

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hello @rdhzl, I'm glad you could find the source of the issue.
As you said, the `rollback` tag supports raw SQL code as well as a `sql` tag. However, if you check the `endDelimiter` documentation for xml files, the attribute needs to be specified inside the `sql` tag:

 ```
<changeSet author="your.name" id="sql-example">
    <sql dbms="mysql" endDelimiter="/">
          ****code here****
    </sql>
  </changeSet>
```

Let us know if you have any other questions or problems, we'll be happy to help.
Thanks!
Tatiana
