### ISSUE TITLE
Picocli dependency is not published as optional dependency of liquibase-core

### ISSUE THREAD

**Issue by mr-serjey** [liquibase/liquibase#4868]
### Search first

- [X] I searched and no similar issues were found

### Description

Despite the fact that `liquibase-core` incorporates `liquibase-cli` in a shaded jar, it doesn't export `liquibase-cli`'s dependency called `picocli` as optional. So the version of `picocli` that works with a particular version of `liquibase-core` is vanishes in published `liquibase-core` artifact. This makes hard to use CLI integration (`liquibase.integration.commandline` package of liquibase-core) in libraries and/or plugins.

Given the fact that exporting `picocli` dependency as part of `liquibase-core` has been already considered...
>It would be nice if it come through as an optional dependency, but maven doesn't easily do that...
see:https://github.com/liquibase/liquibase/blob/master/liquibase-core/pom.xml#L45

This can be done to remediate the problem and will help to unblock at least `liquibase-gradle-plugin` project...
- liquibase/liquibase-gradle-plugin#129

### Steps To Reproduce

1. Create application project with liquibase-core dependency (maven/gradle)
2. Add LiquibaseLauncher.main(cliArgs) into the application routine
3. Run the application 

Error: class def not found

### Expected/Desired Behavior

1. Create application project with liquibase-core dependency (maven/gradle)
2. Add LiquibaseLauncher.main(cliArgs) into the application routine
3. Run the application 

No error expected

### Liquibase Version

4.+

### Liquibase Integration

cli

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
Hello @mr-serjey  - I believe optional is fine. I created PR https://github.com/liquibase/liquibase/pull/5042 to implement this change.

**Comment by mr-serjey** [comment]
Great job @filipelautert!
