### ISSUE TITLE
Liquibase 4.18 with Spring boot 2.7 is throwing runtime error when trying to up the application

### ISSUE THREAD

**Issue by devendra-kumar1** [liquibase/liquibase#4872]
### Search first

- [X] I searched and no similar issues were found

### Description

Hi,
  I am upgrading my app with spring boot 2.7 and liquibase 4.18 liquibase core.  My past liquibase script which has include to sql file with below format causing application up failure. with below error

**Error parsing classpath:/db/liquibase-changeLog.yml: Unknown change type 'include'. Check for spelling or capitalization errors and missing extensions such as liquibase-commercial.**

Changset example:

databaseChangeLog:
  - changeSet:
      id: changeLog-1
      author: XYZ
      changes:
        - sqlFile:
            path: /db/changeLog1.sql

  - changeSet:
      id: changeLog-2
      author: XYZ4
      changes:
        - include:
            file: test1.sql
        - include:
            file: test2.sql
        - include:
            file: test3.sql
        - include:
            file: test4.sql

### Steps To Reproduce

Create a changelog master yaml with below format

databaseChangeLog:
  - changeSet:
      id: changeLog-1
      author: XYZ
      changes:
        - sqlFile:
            path: /db/changeLog1.sql

  - changeSet:
      id: changeLog-2
      author: XYZ4
      changes:
        - include:
            file: test1.sql
        - include:
            file: test2.sql
        - include:
            file: test3.sql
        - include:
            file: test4.sql

### Expected/Desired Behavior

Application should up without any error

### Liquibase Version

4.18.0

### Database Vendor & Version

Postgres 14

### Liquibase Integration

spring boot 

### OS and/or Infrastructure Type/Provider

Windows 11

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hello @devendra-kumar1, luckily there's an easy fix for this :)
If you check the [documentation](https://docs.liquibase.com/change-types/include.html), `include` shouldn't come after `changes:`. It goes one level "inside" `databaseChangeLog`. 

Hope this helps!
Tatiana
