### ISSUE TITLE
Oracle jdbc 23.2 has a bug causing incorrect host search order

### ISSUE THREAD

**Issue by doakd** [liquibase/liquibase#4903]
### Search first

- [X] I searched and no similar issues were found

### Description

If multiple hosts are listed in the ADDRESS_LIST section, the search order has been reversed, which causes an error for Data Gaurd configurations where the 2nd host listed is not an active instance.

I have an SR opened with Oracle, they informed me this is a bug.  They are working on a fix.

Would be preferrable to rollback to oracle jdbc 21.11 until the bug has been resolved by Oracle

### Steps To Reproduce

Attempt to deploy to Oracle using jdbc string with two hosts, 1 host primary instance, 2nd host Data-guard instance (mounted mode).  jdbc 23.2 will try the Data-Guard instance first.

### Expected/Desired Behavior

Oracle jdbc 21.11 is used

### Liquibase Version

23.1

### Database Vendor & Version

Oracle 19.9

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
Thanks @doakd ! I was able to reproduce your problem and will downgrade the driver.

**Comment by doakd** [comment]
Rolling back to Oracle 19 is too far.  Liquibase version 23.0 was using 21.9.

Bump ojdbc8 from 21.9.0.0 to 23.2.0.0 by https://github.com/dependabot in https://github.com/liquibase/liquibase/pull/4106

**Comment by filipelautert** [comment]
@doakd we tested with 21.11 , but then we keep on researching about drivers and found out some links from Oracle regarding the "LTS" status of 19c series. Driver 19.20 was released last month "together" with 21.11 (https://mvnrepository.com/artifact/com.oracle.database.jdbc/ojdbc8) , so they are keeping it up to date too and it should be supported for a longer time (and we also got scared of the name "Innovation Release" 😨 )

**Comment by doakd** [comment]
ok, sounds good.  Do you have an ETA for when will the new 19.2 driver be packaged in a version?

**Comment by filipelautert** [comment]
@doakd hopefully we may have a release by next week! By now you can grab the driver and add it to lib directory then it should override the current one in internal/lib directory. And thanks again for finding this out.
