### ISSUE TITLE
Mac installer does not update PATH

### ISSUE THREAD

**Issue by jcollum-nutrien** [liquibase/liquibase#4933]
### Search first

- [X] I searched and no similar issues were found

### Description

Downloaded the mac installer today. Checked "yes" to the add to path option. When I start a new terminal (zsh) liquibase is not in my path. 

At the very least I'd like the installer to tell me that adding to the path failed and give me an easy to copy line to update my shell profile with. 

### Steps To Reproduce

Covered above. 

### Expected/Desired Behavior

liquibase executable should be in path 

### Liquibase Version

4.23.2 (2023.09.11)

### Database Vendor & Version

na

### Liquibase Integration

cli

### Liquibase Extensions

na

### OS and/or Infrastructure Type/Provider

Mac Ventura 13.5

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @jcollum-nutrien, sorry for the late response.
The macOS installer doesn't currently have an "add to path" button, and what should be configured is the `LIQUIBASE_HOME` variable.

This is working as expected, so I'll be closing this issue. Feel free to leave a comment if the problem persists.

Thank you,
Tatiana
