### ISSUE TITLE
There is no way to pass synthetic or in-memory files into the new CommandScope-style commands

### ISSUE THREAD

**Issue by jetpacktuxedo** [liquibase/liquibase#4955]
### Search first

- [X] I searched and no similar issues were found

### Description

The new CommandScope api for executing liquibase commands from the java bindings doesn't seem to allow for the (very useful) ResourceAccessor behavior of the now-deprecated api.

### Steps To Reproduce

Construct a synthetic directory using `liquibase.sdk.resource.MockResourceAccessor`

```kotlin
        const val CHANGELOG_FILE_ROOT = "changelogs.yml"
        const val CHANGELOG_FILE_ZERO = "changelogs/0.yml"

        const val ROOT_MIGRATION = """
            databaseChangeLog:
              - includeAll:
                  path: changelogs/
                  relativeToChangelogFile: True
            """

        const val BASIC_MIGRATION = """
            databaseChangeLog:
              -  changeSet:
                  id: 0
                  changes:
                    -  createTable:
                        tableName: test
                        columns:
                          -  column:
                              name: id
                              type: int
                              autoIncrement: true
                              constraints:
                                primaryKey: true
                                nullable: false
                          -  column:
                              name: test
                              type: varchar(50)
            """

    val testMigration = mapOf(
        CHANGELOG_FILE_ROOT to ROOT_MIGRATION,
        CHANGELOG_FILE_ZERO to BASIC_MIGRATION,
    )

    val resourceAccessor = MockResourceAccessor(testMigration)
```

When creating a liquibase object this can be passed in
```kotlin
    val liquibase = Liquibase(changelog, resourceAccessor, database)
```

When you then run an update with `liquibase.update(Contexts())` it will successfully read your synthetic directory and apply that changeset.

### Expected/Desired Behavior

Some way to pass an `ArgumentValue` containing a function or class that can be used to define how files are accessed in a way that would allow for similar behavior to the old `ResourceAccessor` behavior.

### Liquibase Version

4.23.2

### Database Vendor & Version

sqlite 3.39.5

### Liquibase Integration

Java API

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by jetpacktuxedo** [comment]
Relatedly, the `ResourceAccessor` behavior even on the deprecated class has been broken specifically for `revert()` calls since 4.20.0 (someone else mentioned this in a [mostly-unrelated thread](https://github.com/liquibase/liquibase/issues/4406#issuecomment-1652426704) ), though it continues to work for update.

**Comment by MalloD12** [comment]
Hi @jetpacktuxedo,

I think you can try something like this:

```
        def scopeSettings = [
                (Scope.Attr.resourceAccessor.name()): resourceAccessor
        ]
        Scope.child(scopeSettings, {
            CommandScope commandScope = new CommandScope(UpdateCommandStep.COMMAND_NAME)
            commandScope.addArgumentValue(DbUrlConnectionCommandStep.URL_ARG, db.getConnectionUrl())
            commandScope.addArgumentValue(DbUrlConnectionCommandStep.USERNAME_ARG, db.getUsername())
            commandScope.addArgumentValue(DbUrlConnectionCommandStep.PASSWORD_ARG, db.getPassword())
            commandScope.addArgumentValue(UpdateCommandStep.CHANGELOG_FILE_ARG, changelogFile)
            commandScope.addArgumentValue(ShowSummaryArgument.SHOW_SUMMARY, UpdateSummaryEnum.SUMMARY)
            commandScope.execute()
        } as Scope.ScopedRunnerWithReturn<Void>)
}
```
 First, create your resource accessor type.

Can you try something like this for your use case and let us know?

Thanks,
Daniel.

**Comment by jetpacktuxedo** [comment]
Yeah, I can give that a shot and report back 👍

**Comment by jetpacktuxedo** [comment]
The method described in [this comment above](https://github.com/liquibase/liquibase/issues/4955#issuecomment-1751395518) resolves the issue
