### ISSUE TITLE
code changes suggested seem to fail with latest liquibase 4.24.0 library

### ISSUE THREAD

**Issue by sachin234s** [liquibase/liquibase#5029]
The below seem to fail when we upgrade liquibase to to 4.24.0 with the same error as stated in https://github.com/liquibase/liquibase/issues/4406#issue-1765213118

please help             

               Hello @sachin234s ! There were some changes around Liquibase 4.14 , so I think you can resolve your issue by using `SearchPathResourceAccessor `instead of .`StreamResourceAccessor `.  Could you try the following:

```
SearchPathResourceAccessor resourceAccessor = new SearchPathResourceAccessor(
                new DirectoryResourceAccessor(Paths.get("/").toAbsolutePath().toFile()));
liquibase = new Liquibase(tracingFilePath, resourceAccessor, database);
```

Or to be more restrictive: 

```
tracingFilePath = "tracing_data_15.xml ";
SearchPathResourceAccessor resourceAccessor = new SearchPathResourceAccessor(
                new DirectoryResourceAccessor(Paths.get("/var/opt/SIU/").toAbsolutePath().toFile()));
liquibase = new Liquibase(tracingFilePath, resourceAccessor, database);
```

Or even maybe just `new SearchPathResourceAccessor("/"))` could work.

_Originally posted by @filipelautert in https://github.com/liquibase/liquibase/issues/4320#issuecomment-1593179611_

with liquibase 4.24.0 the exception is as below

Caused by: liquibase.exception.ChangeLogParseException: The file tracing_data_15.xml was not found in the configured search path:
More locations can be added with the 'searchPath' parameter.
	at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:114)
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:15)
	at liquibase.command.core.helpers.DatabaseChangelogCommandStep.lambda$getDatabaseChangeLog$0(DatabaseChangelogCommandStep.java:129)
	at liquibase.Scope.child(Scope.java:193)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.command.core.helpers.DatabaseChangelogCommandStep.getDatabaseChangeLog(DatabaseChangelogCommandStep.java:128)
	at liquibase.command.core.helpers.DatabaseChangelogCommandStep.run(DatabaseChangelogCommandStep.java:87)
	at liquibase.command.CommandScope.execute(CommandScope.java:214)

**Comment by kevin-atx** [comment]
@filipelautert - could you provide guidance here?

**Comment by filipelautert** [comment]
Hello @sachin234s ! Was it working with 4.23.2 ? And both options were working or just the first one?
Thanks

**Comment by sachin234s** [comment]
Hello @filipelautert , the behaviour is same with the 4.23.2 lib as well.

**Currently i have tried the below which seem to be failing**
```
tracingFilePath = "tracing_data_15.xml ";
SearchPathResourceAccessor resourceAccessor = new SearchPathResourceAccessor(
                new DirectoryResourceAccessor(Paths.get("/var/opt/SIU/").toAbsolutePath().toFile()));
liquibase = new Liquibase(tracingFilePath, resourceAccessor, database);

```

Could you please guide me how to proceed?

**Comment by sachin234s** [comment]
> Hello @sachin234s ! Was it working with 4.23.2 ? And both options were working or just the first one? Thanks

Hello @filipelautert , the behaviour is same with the 4.23.2 lib as well.

Currently i have tried the below which seem to be failing

tracingFilePath = "tracing_data_15.xml ";
SearchPathResourceAccessor resourceAccessor = new SearchPathResourceAccessor(
                new DirectoryResourceAccessor(Paths.get("/var/opt/SIU/").toAbsolutePath().toFile()));
liquibase = new Liquibase(tracingFilePath, resourceAccessor, database);

Could you please guide me how to proceed?

**Comment by sachin234s** [comment]
@filipelautert @kevin-atx  :could you please help as its affecting our product

**Comment by filipelautert** [comment]
Hi @sachin234s , sorry for the delay to answer. 
I see that another user proposed this [PR](https://github.com/liquibase/liquibase/pull/4591) that we already merged, but now reviewing it the fix is only for parameters and not for search path. So I'm creating Pr https://github.com/liquibase/liquibase/pull/5078 to fix this.  Would you be able to test the build artifacts to confirm it fixes your problem?

Meanwhile, using the code below should work: 

```
SearchPathResourceAccessor resourceAccessor = new SearchPathResourceAccessor(
                new DirectoryResourceAccessor(Paths.get("/var/opt/SIU/").toAbsolutePath().toFile()));

        Map<String, Object> scopeObjects = new HashMap<>();
        scopeObjects.put(Scope.Attr.database.name(), myDatabase);
        scopeObjects.put(Scope.Attr.resourceAccessor.name(), resourceAccessor);

        Scope.child(scopeObjects, () -> {
            new CommandScope(RollbackCommandStep.COMMAND_NAME)
                .addArgumentValue(DbUrlConnectionCommandStep.DATABASE_ARG, Liquibase.this.getDatabase())
                .addArgumentValue(DatabaseChangelogCommandStep.CHANGELOG_FILE_ARG, changeLogFile)
                .addArgumentValue(DatabaseChangelogCommandStep.CONTEXTS_ARG, (contexts != null? contexts.toString() : null))
                .addArgumentValue(DatabaseChangelogCommandStep.LABEL_FILTER_ARG, (labelExpression != null ? labelExpression.getOriginalString() : null))
                .addArgumentValue(ChangeExecListenerCommandStep.CHANGE_EXEC_LISTENER_ARG, changeExecListener)
                .addArgumentValue(RollbackCommandStep.TAG_ARG, tagToRollBackTo)
                .addArgumentValue(RollbackCommandStep.ROLLBACK_SCRIPT_ARG, rollbackScript)
                .execute();
        });
```

**Comment by sachin234s** [comment]
@filipelautert : thanks for sharing your feedback, post making the changes, i was able to resolve the issue.

Additionally , we have similar issue as above in `validate` method implantation as well. I was able to resolve with a similar fix as above.

**Comment by filipelautert** [comment]
Hello @sachin234s ! thanks, fixing here -> https://github.com/liquibase/liquibase/pull/5122
