### ISSUE TITLE
Version 4.7.0 release notes omits a breaking change

### ISSUE THREAD

**Issue by k4pran** [liquibase/liquibase#5033]
### Search first

- [ ] I searched and no similar issues were found

### Description

In the version 4.7.0 release notes there is a breaking change mentioned in the liquibase docs https://docs.liquibase.com/start/release-notes/home.html

Breaking Changes
[[PR#2228](https://github.com/liquibase/liquibase/pull/2228)] [[Nathan Voxland](https://github.com/nvoxland)] Handle the fact that FK names are not always unique. Fixes [PR#2227](https://github.com/liquibase/liquibase/issues/2227). When using the foreignKeyConstraintExists precondition, you must now specify foreignKeyTableName. See also: [PR#2565](https://github.com/liquibase/liquibase/pull/2565) fixing [#2389](https://github.com/liquibase/liquibase/issues/2389). in 4.11.0.

This breaking change seems to be omitted in the github release notes.

### Steps To Reproduce

View this github release notes at https://github.com/liquibase/liquibase/releases?page=3

### Expected/Desired Behavior

Breaking changes in other releases are highlighted in other releases, I think adding this breaking change to the 4.7.0 release notes in github would be helpful as we missed it until we began getting errors.

### Liquibase Version

4.7.0

### Additional Context

N/A

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by adrian-velonis1** [comment]
Thanks @k4pran for the report.

Inconsistency caused by https://datical.atlassian.net/browse/PD-3157.

Created https://datical.atlassian.net/browse/PD-3841 to track this ticket internally. [CE_Sprint_63]

**Comment by adrian-velonis1** [comment]
Updated https://github.com/liquibase/liquibase/releases/tag/v4.7.0
