### ISSUE TITLE
weird filename in DATABASECHANGELOG after migrating from liquibase 4.23.0 to 4.24.0

### ISSUE THREAD

**Issue by mzatko** [liquibase/liquibase#5114]
### Search first

- [X] I searched and no similar issues were found

### Description

running liguibase update with version 4.24.0 is trying to run already ran changesets again
It is probably caused by not normalized filename of changeset in version 4.24.0

Until version 4.23.0 it used normalized filename like "db/objects/T-XXXXX-create.xml"
version 4.24.0 doesn't normalize filename and it looks like "db/bundles/../objects/T-XXXXX-create.xml"

### Steps To Reproduce

dbchangelog.xml
```xml
<databaseChangeLog>
    <include file="bundles/ISSUE-XXXXX.xml" relativeToChangelogFile="true" />
</databaseChangeLog>
```
bundles/ISSUE-XXXXX.xml
```xml
<databaseChangeLog>
    <include file="../objects/T-XXXXX-create.xml" relativeToChangelogFile="true"/>
</databaseChangeLog>
```
objects/T-XXXXX-create.xml
```xml
<databaseChangeLog>
    <changeSet id="20231024-122624-01" author="miroslav.zatko">
        <createTable tableName="xxxxx">
            <column name="id" type="java.sql.Types.BIGINT" />
        </createTable>
    </changeSet>
</databaseChangeLog>
```

first run with liquibase 4.23.0, everything is OK, changeset applied
run with liquibase 4.24.0, FAILED, tries to apply changeset again

### Expected/Desired Behavior

run with liquibase 4.24.0, doesn't try to apply changeset again and finishes successfully

In DATABASECHANGELOG use normalized filename with "dots" and "double dots" directories resolved correctly

### Liquibase Version

4.24.0

### Database Vendor & Version

any

### Liquibase Integration

tested on CLI and maven

### OS and/or Infrastructure Type/Provider

ubuntu

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
Hello @tati-qalified @mzatko ! Thanks for the report. I created PR https://github.com/liquibase/liquibase/pull/5141 to fix it. Could you test using the artifacts from this build and confirm if it fixes your problem?
