### ISSUE TITLE
update-sql command does not generate a deployment_id

### ISSUE THREAD

**Issue by josh-smartx** [liquibase/liquibase#5121]
### Search first

- [X] I searched and no similar issues were found

### Description

When using the `update-sql` command, the insert statements for the DATABASECHANGELOG table set the DEPLOYMENT_ID to null

### Steps To Reproduce

Run the 'liquibase update-sql' command with pending changes waiting to be inserted to the databasechangelog table. Observe in the Insert statements that the `Deployment_id` is null

### Expected/Desired Behavior

The `update-sql` command should generate a deployment_id for the insert statements

### Liquibase Version

4.24.0

### Database Vendor & Version

SQL Server 2019

### OS and/or Infrastructure Type/Provider

Windows 11

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by josh-smartx** [comment]
I believe `setDBLock(false);` needs to be added [here]( https://github.com/liquibase/liquibase/blob/b39aefffc7828eedd2161cd57c6e477d2881a680/liquibase-standard/src/main/java/liquibase/command/core/UpdateSqlCommandStep.java#L60), but I don't have a java environment set up to test this hypothesis

**Comment by tati-qalified** [comment]
Hi @josh-smartx, thank you for reporting this issue.
I've confirmed that this is happening, and has been since Liquibase version 4.23.1. It worked in versions 4.23.0 and prior.
I'll be forwarding this to the development team so they can evaluate how to move forward.
Thanks,
Tatiana

**Comment by josh-smartx** [comment]
This appears to be fixed with release 4.25
