### ISSUE TITLE
UpdateCommand  failed on OSGI framework

### ISSUE THREAD

**Issue by npreisner** [liquibase/liquibase#5142]
### Search first

- [X] I searched and no similar issues were found

### Description

Hi,

We are trying to upgrade our liquibase dependency to the latest. (4.24.0)
Our application use OSGI framework.

The UpdateCommand run this code in AbstractUpdateCommandStep

```
 if(!isDBLocked) {
                LockServiceFactory.getInstance().getLockService(database).waitForLock();
                // waitForLock resets the changelog history service, so we need to rebuild that and generate a final deploymentId.
                ChangeLogHistoryService changeLogHistoryService = Scope.getCurrentScope().getSingleton(ChangeLogHistoryServiceFactory.class).getChangeLogService(database);
                changeLogHistoryService.generateDeploymentId();
            } 
```

The waitForLock() reset the services list and among the rest removing the instances list:

```
  protected synchronized void removeInstance(T instance) {
        if (this.allInstances == null) {
            return;
        }
        this.allInstances.remove(instance);
    }
```

Back to AbstractUpdateCommandStep :
Line after the waitForLock() we have the getChangeLogService(database) which reach the getPlugin() method in the AbstractPluginFactory. 

Line 62: 
```
 for (T plugin : findAllInstances()) {
            if (getPriority(plugin, args) >= 0) {
                applicable.add(plugin);
            }
        }
```

```
protected synchronized Collection<T> findAllInstances() {
        if (this.allInstances == null) {
            this.allInstances = new ArrayList<>();

            ServiceLocator serviceLocator = Scope.getCurrentScope().getServiceLocator();
            this.allInstances.addAll(serviceLocator.findInstances(getPluginClass()));
        }

        return this.allInstances;
    }
```
The issue is with the findAllInstnces() method: Like you can see since the allInstances is empty and not null (in our scenario) ServiceLocator is not called and allInstances will remain empty and we catch this exception:
`liquibase.exception.UnexpectedLiquibaseException: Cannot find ChangeLogHistoryService for postgresql`

ServiceLocator is a must for us since we use OSGi and we need to find the class in the osgi bundle.

Thank you,
 #Natan

 

### Steps To Reproduce

-

### Expected/Desired Behavior

Services should be loaded

### Liquibase Version

4.24.0

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by yairogen** [comment]
@filipelautert this is related to https://github.com/liquibase/liquibase/issues/3660
we are now completely blocked on this small issue.
when is the next planned release? it is very urgent.
maybe we can add to the if a check on empty:

```
if (this.allInstances == null || this.allInstances.isEmpty()) {
            this.allInstances = new ArrayList<>();

            ServiceLocator serviceLocator = Scope.getCurrentScope().getServiceLocator();
            this.allInstances.addAll(serviceLocator.findInstances(getPluginClass()));
}
```

**Comment by filipelautert** [comment]
Thanks @yairogen  @npreisner ! Let's jump to PR https://github.com/liquibase/liquibase/pull/5143 to confirm tht it fixes this issue 👍
