### ISSUE TITLE
Spring resource URLs are not decoded

### ISSUE THREAD

**Issue by Ayrossi** [liquibase/liquibase#5155]
### Search first

- [X] I searched and no similar issues were found

### Description

Using liquibase as a standalone program works with spaces in the filenames ( for changelogs ). However it does not work for files with spaces in their filenames when using it integrated with Spring.

Liquibase internally uses the following class for the integration with Spring: [FileSystemResource](https://github.com/spring-projects/spring-framework/blob/main/spring-core/src/main/java/org/springframework/core/io/FileSystemResource.java).

More specifically it uses the following method getURL on the resource.
This method did not encode spaces in old versions of Spring which is why the integration with liquibase was working.

This behaviour has been modified a long time ago after this issue: https://github.com/spring-projects/spring-framework/issues/8580

Liquibase did not adapt the code to decode this URL, hence this is blocking for legacy projects that have spaces in their filenames. Although I agree that spaces in file name should always be avoided, I do think that this should not be a blocking issue.

### Steps To Reproduce

Add one changelog with a space in the filename and try to run liquibase with Spring. 
The easiest way to reproduce this is to generate a Spring Boot project with the minimal required dependencies and one changelog with the space.

### Expected/Desired Behavior

I expect that after the fix it is possible to run liquibase with Spring Boot even for files with spaces in their filenames.

### Database Vendor & Version

All

### Liquibase Integration

Spring Boot

### OS and/or Infrastructure Type/Provider

All

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @Ayrossi
I wasn't able to replicate this bug. I didn't get any errors with filenames with spaces, no matter the position of the space. 
Did you come across this issue with Liquibase 4.24.0?
Could you provide me with the stack trace of the error?

Thank you,
Tatiana

**Comment by Ayrossi** [comment]
Hi @tati-qalified 

I have added a repository with a minimal reproducible example:

https://github.com/Ayrossi/liquibase-bug.git

Just update the java version to the one you use ( >= 17 ), install with maven and run the application. 
You will have the error during startup.
