### ISSUE TITLE
Labels defined in Include tag are not taken into account when filtering

### ISSUE THREAD

**Issue by abelrodriguez** [liquibase/liquibase#5175]
### Search first

- [X] I searched and no similar issues were found

### Description

When I define a label in a Include tag, then I can't filter by them from the terminal with the modifier "@".

### Steps To Reproduce

I have two files:

File: 000-changelog-root.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.24.xsd">

    <changeSet id="TAG-v1.3.0" author="dev-team">
        <tagDatabase tag="v1.3.0"/>
    </changeSet>
    <include file="000_create-table.xml" relativeToChangelogFile="true" labels="JIRA-1"/>

</databaseChangeLog>
```

File: 000_create-table.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.24.xsd">

    <changeSet id="001" author="dev-team">
        <createTable tableName="book">
            <column name="id" type="bigint">
                <constraints nullable="false" primaryKey="true" primaryKeyName="pk_book"/>
            </column>
            <column name="name" type="varchar(255)"/>
        </createTable>
    </changeSet>
</databaseChangeLog>
```

Note: JIRA-1 label is defined in the <include...> of file `000-changelog-root.xml`.

When I execute the command `liquibase update`, the rows of DATABASECHANGELOG has defined correctly this value in the field `LABELS`.

The problem is when you want to use the atributte `--labels` or `--label-filter`.

If you run `liquibase update --labels="@JIRA-1"` or `liquibase rollback --labels="@JIRA-1"` no changesets are found.

If instead of define the label in the tag `<include...>` you define the label in every changeSet (`<changeSet id="001" author="dev-team" label="JIRA-1">`) the commands are executed correctly.

### Expected/Desired Behavior

The commands should make the same if the label is defined in `<include...>` tag or in `<changeSet...>` tag.

### Liquibase Version

4.24.0

### Database Vendor & Version

any

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @abelrodriguez, thank you for reporting this issue. 
I've found an inconsistency with how labels are processed, and that is the source of the problem you're experiencing.

For a workaround, when you want to filter by labels that are set in the `include` tag, use `--labels="myLabel"`, **with no `@` sign**. Please try it and let me know if it works for you.

I'll describe the inconsistency now for the development team.

- When using labels in any changeset, both `--labels="@myLabel"` and `--labels="myLabel"` will filter successfully.
- When using labels in an `include` tag, the syntax with an `@` sign does not filter the change. It works as expected if written without an `@` sign. 
- This is true for .yml, .xml and .json changelog files.
- This is true for Liquibase versions 4.24.0 and 4.25.0

**Comment by MalloD12** [comment]
Hi @abelrodriguez, 
 
There were some labels related PRs that we have recently merged (in the last couple of releases), and it seems that the original issue reported here has been fixed. Worth to mention that we changes made if you want to have tag changeset deployed, you will need to specifiy `JIRA-1` label on it. Otherwise because of using `@` in the filter it will result in a mismatch in the case of the changelog provided here.

I'll close this issue, if you still see any related problem please feel free to open a new issue or reopen this is one if are still experiencing the same behaviour. 

Thanks,
Daniel.
