### ISSUE TITLE
ColumnExistsPrecondition throws error when table is missing

### ISSUE THREAD

**Issue by Januson** [liquibase/liquibase#5271]
### Search first

- [X] I searched and no similar issues were found

### Description

In Liquibase version `4.24.0` precondition `columnExists` evaluated as false when the target table was missing. In version `4.25.0` the precondition throws PreconditionErrorException. Documentation of [columnExists](https://docs.liquibase.com/concepts/changelogs/preconditions.html) doesn't specify this behavior and [4.25.0 release notes](https://docs.liquibase.com/start/release-notes/liquibase-release-notes/liquibase-4.25.0.html) do not mention any changes to it so I suppose it wasn't intentional.

### Steps To Reproduce

Run any changeset with a precondition `columnExists` targeting a table that does not exist.

Reproducer: https://github.com/Januson/liquibase-error

### Expected/Desired Behavior

Precondition should not fail and instead should evaluate as false.

### Liquibase Version

4.25.0

### Database Vendor & Version

HSQLDB

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by MalloD12** [comment]
Thanks, @Januson for raising this issue. We have planned to review #5246 soon which I think could be related. Would you be keen on submitting a PR to fix it? We can provide any guidance/details you need.

Thanks,
Daniel.

**Comment by Januson** [comment]
@MalloD12 Sure, I can submit a PR.

**Comment by tati-qalified** [comment]
Hi @Januson and @MalloD12, I looked into this issue (as well as #5246 ) and I found that it's database-specific, and only the `columnExists` precondition is failing. Similar preconditions such as `tableExists` work with no issues.

This **is** reproducible using H2 and HyperSQL databases

It is **not** reproducible using:
- PostgreSQL
- MySQL
- MSSQL
- Oracle
- DB2

Analysing the error logs, here's the **output for PostgreSQL**:
```
Unexpected error running Liquibase: Migration failed for changeset changelog.xml::2::testing:
     Reason:
          changelog.xml : Column public.thisDoesNotExist.column1 does not exist
  - Caused by: Preconditions Failed
```
Note that it says "Preconditions **Failed**".
This is the same output as for MySQL, MSSQL, etc.



**Now, for H2**:
```
Unexpected error running Liquibase: Migration failed for changeset changelog.xml::2::testing:
     Reason:
          changelog.xml : liquibase.precondition.core.ColumnExistsPrecondition@6b3f6585 : Table "THISDOESNOTEXIST" not found; SQL statement:
select t.column1 from PUBLIC.thisDoesNotExist t where 0=1 [42102-224]
  - Caused by: Precondition Error
  - Caused by: Table "THISDOESNOTEXIST" not found; SQL statement:
select t.column1 from PUBLIC.thisDoesNotExist t where 0=1 [42102-224]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
        at org.h2.message.DbException.get(DbException.java:223)
        at org.h2.message.DbException.get(DbException.java:199)
....
```
In this case, it says "Precondition **Error**".



**And for HyperSQL:**
```
Unexpected error running Liquibase: Migration failed for changeset changelog.xml::2::testinga:
     Reason:
          changelog.xml : liquibase.precondition.core.ColumnExistsPrecondition@3dd818e8 : user lacks privilege or object not found: THISDOESNOTEXIST in statement [select t.column1 from PUBLIC.thisDoesNotExist t where 0=1]
  - Caused by: Precondition Error
```
Also outputs  "Precondition **Error**".
