### ISSUE TITLE
CustomTaskChange execute method runs twice

### ISSUE THREAD

**Issue by kristofdepypere** [liquibase/liquibase#5314]
### Search first

- [X] I searched and no similar issues were found

### Description

We noticed that after update from liquibase 4.24.x to 4.25.0 we are encountering duplicate key issues during our liquibase upgrade.

I dove in the code and was able to pinpoint what changed. Basically we have multiple `CustomTaskChange` implementations that do custom logic (which actually ends up being committed to the database).

The following change is the root cause: https://github.com/liquibase/liquibase/commit/6e0a4c607322607a17918f0ea6e24b9231668591

You'll see that a check `shouldExecuteChange(database)` was removed. However now when triggering https://github.com/liquibase/liquibase/blame/b91ae06921f86c86b1be4f0091616a65614728d4/liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java#L741 `addSqlMdc` it will actually completely execute the `CustomTaskChange` only to execute again during https://github.com/liquibase/liquibase/blame/b91ae06921f86c86b1be4f0091616a65614728d4/liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java#L744.

Why would we ever execute a `CustomTaskChange` to render a sql statement for logging that is always empty.. This doesn't seem right. 

On the other hand, our `CustomTaskChange` implementation really smells to begin with. It might as well be a `CustomSqlChange` as we are actually doing sql changes, so we might change that anyway. I think this will actually fix the issue too, however isn't it dangerous to trigger a CustomTaskChange execute method twice, and for no reason at all ?

### Steps To Reproduce

Create any `CustomTaskChange` implementation. It will execute twice.

### Expected/Desired Behavior

We should not trigger the `execute` method of `CustomTaskChange` at all for logging purposes.

### Liquibase Version

4.25.0

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Alf-Melmac** [comment]
I've noticed the same issue while updating and created a minimal reproducible example: https://github.com/Alf-Melmac/liquibase-issue-custom-task-change
This may also be related to the (already fixed) issue #3945

**Comment by Sumitkrchaudhary** [comment]
@filipelautert execute runs twice per changeSet customChange class in 4.25. Is there a fix or workaround?

**Comment by Sumitkrchaudhary** [comment]
A simple test case of using a table without primary key show row inserted twice that leads to Reason: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.CustomChangeException: ORA-00001: unique constraint violated

**Comment by Sumitkrchaudhary** [comment]
Is this problem only to execute changeSet customChange or impacting other areas as well?

**Comment by cmuchinsky** [comment]
@filipelautert I work with @kristofdepypere and took the liberty of trying out the fix, I can report back that it did resolve the issue my team was seeing, thank you for the quick turnaround!

**Comment by Alf-Melmac** [comment]
Can confirm, works for me too. Thanks!

**Comment by brandonfl** [comment]
Working on my side too by upgrading liquibase to `v4.25.1` :+1:

**Comment by marianomerlo** [comment]
Hey guys, this issue is still happening but when doing rollback. I've forked @Alf-Melmac project and added the rollback operation to reproduce it: https://github.com/marianomerlo/liquibase-issue-custom-task-change

Should I open a new issue for this?

**Comment by Sumitkrchaudhary** [comment]
@filipelautert it is working fine with V4.25.1 release. Thanks

**Comment by Sumitkrchaudhary** [comment]
@filipelautert it worked for the reported problem but there is new error seen in v4.25.1 if anyone is aware and reported already-
Running Changeset: changelogs/base/scripts/table_comments.xml::2::safety-base
UPDATE SUMMARY
Run:                      30751
Previously run:            1160
Filtered out:               181
-------------------------------
Total change sets:        32092
FILTERED CHANGE SETS SUMMARY
Context mismatch:           181
Unexpected error running Liquibase: Lexical error at line 6314, column 70.  Encountered: '\ufffd' (65533),
For more information, please use the --logLevel flag
[2024-01-11 11:41:28] SEVERE [liquibase.integration] Unexpected error running Liquibase: Lexical error at line 6314, column 70.  Encountered: '\ufffd' (65533),
liquibase.util.grammar.TokenMgrError: Lexical error at line 6314, column 70.  Encountered: '\ufffd' (65533),
	at liquibase.util.grammar.SimpleSqlGrammarTokenManager.getNextToken(SimpleSqlGrammarTokenManager.java:1410)

**Comment by filipelautert** [comment]
> liquibase.util.grammar.TokenMgrError: Lexical error at line 6314, column 70. Encountered: '\ufffd' (65533),

@Sumitkrchaudhary seems there is an old discussion with the similar error message and a proposed 'fix': https://forum.liquibase.org/t/fails-to-create-db-objects-having-specific-symbols-like-yen-plus-sign-and-japanese-characters-on-the-table/6164/4

**Comment by filipelautert** [comment]
Hello @mo-radwan1 - please see PR https://github.com/liquibase/liquibase/pull/5524 that should fix this. Thanks @Alf-Melmac !
