### ISSUE TITLE
untracked files in `liquibase-standard/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets` after tests

### ISSUE THREAD

**Issue by rursprung** [liquibase/liquibase#5335]
### Search first

- [X] I searched and no similar issues were found

### Description

after running `maven install` (probably `maven test` would be enough) on a fresh clone of the repo git reports a lot of untracked files in `liquibase-standard/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/`.

### Steps To Reproduce

run `maven test` (i just ran `maven install` which includes this)

### Expected/Desired Behavior

since other files in there are checked in but they also get generated on the fly i'm not sure what your intention is:
* either they're always generated and don't need to be checked in, then you should remove them and add that folder to `.gitignore`
* or they should be checked in, in this case you need to add all the missing ones and commit them (and ensure that they're always being committed every time the underlying things (i don't know what's generating them) change

### Liquibase Version

commit 2abd351ab (current HEAD at time of build)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by MalloD12** [comment]
Thanks @rursprung for submitting this issue. This is something sometimes I feel a bit annoying when having to commit some changes and I have to navigate through a big list of files to select which files I want to commit. We will prioritize this issue later so we work on it the soon future.

FYI: Today I asked Nathan (Liquibase creator) why we keep generating these files and why we cannot add them to gitignore file as suggested by @rursprung and his answer was:

>It's because all those files are actually supposed to be tracked. Their job is to be the "golden master" for the tests of different databases in order to catch regressions and/or verify new behavior.

>As part of the test execution, if an expected "golden master" is not there it creates the file for you to look at to ensure it's right before committing it to git so that future tests ensure they are correct. Part of that process can include adding fuzzy matching options for things in the generated file that are expected to be different each time.

>But, there are a couple of new database types where we kept putting off that "is the results correct?" project and so the files just keep getting generated.

>The actual solution is to take the relatively small amount of time to look through those newly generated files for the new databases and get them committed to git so that the tests do what they are supposed to be.

**Comment by filipelautert** [comment]
@MalloD12 I got it, but I would say that `standard/src/test/java/liquibase` is not the correct place for that and this can be confusing people. I believe that at least those files should be in a place like `standard/src/test/saved_state/etc....` as they are just sql files and not java classes. And of course then the missing ones should be added here.
 What do you think?

**Comment by MalloD12** [comment]
> @MalloD12 I got it, but I would say that `standard/src/test/java/liquibase` is not the correct place for that and this can confuse people. I believe that at least those files should be in a place like `standard/src/test/saved_state/etc....` as they are just sql files and not java classes. And of course the missing ones should be added too. What do you think?

@filipelautert I agree does not make any sense it's in the `java` directory as there is no code for these tests. Maybe we can move it to a `saved_state` directory as you mentioned in the `standard/src/test/` path or maybe place the `saved_state` directory into the resources bundle.

**Comment by filipelautert** [comment]
@MalloD12 that would be great!
