### ISSUE TITLE
Starting with 4.23.1 liquibase fails to aquire lock on derby database in Pax Exam integration test

### ISSUE THREAD

**Issue by steinarb** [liquibase/liquibase#5357]
### Search first

- [X] I searched and no similar issues were found

### Description

I maintain a [karaf feature for liquibase](https://github.com/steinarb/liquibase-karaf-feature)

The karaf feature has [a pax exam integration test](https://github.com/steinarb/liquibase-karaf-feature/blob/master/liquibase-integration-test/karaf.liquibase.tests/src/test/java/no/priv/bang/karaf/liquibase/tests/LiquibaseKarafFeatureIntegrationTest.java#L55) that loads the feature in karaf, creates a simple schema in a derby database, and does some simple operations to verify that the database works (adds a new account and verify that the account is added).

Starting with liquibase 4.23.1 the test started failing:

1. Liquibase fails to aquire a change log lock
2. Liquibase hangs for 5 minutes and then times out and the test fails

This problem doesn't occur outside of OSGi and it also does not occur when loading the karaf feature in [apache karaf](https://karaf.apache.org) (where I could debug it).

The problem only occurs in the pax exam integration test.

I worked around the problem with switching from derby to h2 in the integration test so I'm not blocked in releasing new releases of the liquibase karaf feature.

But I still think this error should be found and fixed.

### Steps To Reproduce

Procdure:

1. Clone the liquibase-karaf-feature
   ```
   git clone https://github.com/steinarb/liquibase-karaf-feature.git
   ```
2. Check out the branch using liquibase 4.23.0 with derby in the integration test and build it
   ```
   cd liquibase-karaf-feature
   git checkout derby-pax-exam-changelog-lock-failure-4230
   mvn clean install
   ```
3. The maven build succeeds
4. Check out the branch using liquibase 4.23.1 with derby in the integration test and build it
   ```
   cd liquibase-karaf-feature
   git checkout derby-pax-exam-changelog-lock-failure-4231
   mvn clean install
   ```
5. The build will hang for 5 minutes and then time out and fail

The detailed output from liquibase can be found in
```
liquibase-karaf-feature/liquibase-integration-test/karaf.liquibase.tests/target/exam/<some-hash>/data/log/karaf.log
```

### Expected/Desired Behavior

That the integration test for the liquibase-karaf-feature using derby can be used for liquibase 4.23.1 and later

### Liquibase Version

4.23.1

### Database Vendor & Version

derby 10.14.2.0

### Liquibase Integration

java 17.0.9

### OS and/or Infrastructure Type/Provider

debian 12.3 amd64, and whatever runs in github actions

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by steinarb** [comment]
Here are some karaf.log files for the various situations:

1. Failing with liquibase 4.23.1
    1. [creating the schema fails here](https://gist.github.com/steinarb/7e6429d78ac30aa24b8228feb4ac814e#file-karaf-log-L333) (after a 5 minute time out)
    2.  [immediately after giving up, liquibase reports that it was able to aquire a lock](https://gist.github.com/steinarb/7e6429d78ac30aa24b8228feb4ac814e#file-karaf-log-L550) (but at this time the train has left the station)
2. Succeeding with liquibase 4.23.1 on a load from the apache karaf 4.4.4 command line
    1. [first liquibase aquires the lock](https://gist.github.com/steinarb/5e6b57c7426fb5e2d5d07c35e3edb45e#file-karaf-log-L264)
    2. [then liquibase starts setting up the schema](https://gist.github.com/steinarb/5e6b57c7426fb5e2d5d07c35e3edb45e#file-karaf-log-L265)

**Comment by filipelautert** [comment]
Hello @steinarb ! The lock error message comes from derby - https://stackoverflow.com/questions/15582682/a-lock-could-not-obtained-within-the-time-requested-issue , probably generated by a prior error as you highlighted. 

I tried to run your test code using liquibase 4.25.1 but got a service load error., then using the attached PR it started to work for me again. Could you give it a try?

**Comment by steinarb** [comment]
@filipelautert I tried but I had problems building liquibase locally, which I have to do to test the PR.

I am trying a plain "mvn clean install" from the top of the latest liquibase master, on debian 12.4 "bookworm", amd64, maven 3.8.7, java 17.0.9, and get the following error:
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java:[50,1] cannot find symbol
  symbol:   static REGISTERED_VALUE_PROVIDERS_KEY
  location: class liquibase.configuration.LiquibaseConfiguration
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java:[681,61] cannot find symbol
  symbol:   variable LOG_FORMAT
  location: class liquibase.integration.commandline.LiquibaseCommandLineConfiguration
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java:[682,28] cannot find symbol
  symbol:   variable REGISTERED_VALUE_PROVIDERS_KEY
  location: class org.liquibase.maven.plugins.AbstractLiquibaseMojo
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java:[688,31] cannot find symbol
  symbol:   method setFormatterOnHandler(liquibase.logging.LogService,java.util.logging.Handler)
  location: class liquibase.logging.core.JavaLogService
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java:[986,65] cannot find symbol
  symbol:   method getExisting(java.lang.String)
  location: interface liquibase.resource.ResourceAccessor
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseGenerateChangeLogMojo.java:[169,34] cannot find symbol
  symbol:   method setReplaceIfExistsSet(boolean)
  location: variable diffOutputControl of type liquibase.diff.output.DiffOutputControl
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseGenerateChangeLogMojo.java:[181,33] no suitable method found for doGenerateChangeLog(java.lang.String,liquibase.database.Database,liquibase.CatalogAndSchema[],java.lang.String,java.lang.String,java.lang.String,java.lang.String,liquibase.diff.output.DiffOutputControl,boolean,java.lang.String,java.lang.String)
    method liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(java.lang.String,liquibase.database.Database,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,liquibase.diff.output.DiffOutputControl) is not applicable
      (actual and formal argument lists differ in length)
    method liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(java.lang.String,liquibase.database.Database,liquibase.CatalogAndSchema[],java.lang.String,java.lang.String,java.lang.String,java.lang.String,liquibase.diff.output.DiffOutputControl) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseUpdate.java:[71,18] cannot find symbol
  symbol:   method setShowSummary(liquibase.UpdateSummaryEnum)
  location: variable liquibase of type liquibase.Liquibase
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseUpdate.java:[72,18] cannot find symbol
  symbol:   method setShowSummaryOutput(liquibase.UpdateSummaryOutputEnum)
  location: variable liquibase of type liquibase.Liquibase
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java:[290,42] cannot find symbol
  symbol:   method setReplaceIfExistsSet(boolean)
  location: variable diffOutputControl of type liquibase.diff.output.DiffOutputControl
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java:[292,37] no suitable method found for doDiffToChangeLog(java.lang.String,liquibase.database.Database,liquibase.database.Database,java.lang.String,liquibase.diff.output.DiffOutputControl,liquibase.diff.output.ObjectChangeFilter,java.lang.String,liquibase.diff.compare.CompareControl.SchemaComparison[],java.lang.String,java.lang.String)
    method liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(java.lang.String,liquibase.database.Database,liquibase.database.Database,liquibase.diff.output.DiffOutputControl,liquibase.diff.output.ObjectChangeFilter,java.lang.String) is not applicable
      (actual and formal argument lists differ in length)
    method liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(java.lang.String,liquibase.database.Database,liquibase.database.Database,liquibase.diff.output.DiffOutputControl,liquibase.diff.output.ObjectChangeFilter,java.lang.String,liquibase.diff.compare.CompareControl.SchemaComparison[]) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java:[304,66] cannot find symbol
  symbol:   variable FORMAT_ARG
  location: class liquibase.command.core.DiffCommandStep
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java:[312,112] cannot find symbol
  symbol:   method parseSnapshotTypes(java.lang.String)
  location: class liquibase.command.core.DiffCommandStep
[INFO] 13 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Liquibase Parent 0-SNAPSHOT:
[INFO] 
[INFO] Liquibase Parent ................................... FAILURE [ 26.016 s]
[INFO] liquibase-standard ................................. SKIPPED
[INFO] liquibase-cli ...................................... SKIPPED
[INFO] liquibase-snowflake ................................ SKIPPED
[INFO] Liquibase .......................................... SKIPPED
[INFO] liquibase-maven-plugin ............................. SKIPPED
[INFO] liquibase-cdi-jakarta .............................. SKIPPED
[INFO] liquibase-cdi ...................................... SKIPPED
[INFO] liquibase-extension-testing ........................ SKIPPED
[INFO] liquibase-integration-tests ........................ SKIPPED
[INFO] liquibase-dist ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  26.627 s
[INFO] Finished at: 2024-01-23T18:29:03+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.12.1:compile (default-compile) on project liquibase-maven-plugin: Compilation failure: Compilation failure: 
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java:[50,1] cannot find symbol
[ERROR]   symbol:   static REGISTERED_VALUE_PROVIDERS_KEY
[ERROR]   location: class liquibase.configuration.LiquibaseConfiguration
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java:[681,61] cannot find symbol
[ERROR]   symbol:   variable LOG_FORMAT
[ERROR]   location: class liquibase.integration.commandline.LiquibaseCommandLineConfiguration
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java:[682,28] cannot find symbol
[ERROR]   symbol:   variable REGISTERED_VALUE_PROVIDERS_KEY
[ERROR]   location: class org.liquibase.maven.plugins.AbstractLiquibaseMojo
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java:[688,31] cannot find symbol
[ERROR]   symbol:   method setFormatterOnHandler(liquibase.logging.LogService,java.util.logging.Handler)
[ERROR]   location: class liquibase.logging.core.JavaLogService
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java:[986,65] cannot find symbol
[ERROR]   symbol:   method getExisting(java.lang.String)
[ERROR]   location: interface liquibase.resource.ResourceAccessor
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseGenerateChangeLogMojo.java:[169,34] cannot find symbol
[ERROR]   symbol:   method setReplaceIfExistsSet(boolean)
[ERROR]   location: variable diffOutputControl of type liquibase.diff.output.DiffOutputControl
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseGenerateChangeLogMojo.java:[181,33] no suitable method found for doGenerateChangeLog(java.lang.String,liquibase.database.Database,liquibase.CatalogAndSchema[],java.lang.String,java.lang.String,java.lang.String,java.lang.String,liquibase.diff.output.DiffOutputControl,boolean,java.lang.String,java.lang.String)
[ERROR]     method liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(java.lang.String,liquibase.database.Database,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,liquibase.diff.output.DiffOutputControl) is not applicable
[ERROR]       (actual and formal argument lists differ in length)
[ERROR]     method liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(java.lang.String,liquibase.database.Database,liquibase.CatalogAndSchema[],java.lang.String,java.lang.String,java.lang.String,java.lang.String,liquibase.diff.output.DiffOutputControl) is not applicable
[ERROR]       (actual and formal argument lists differ in length)
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseUpdate.java:[71,18] cannot find symbol
[ERROR]   symbol:   method setShowSummary(liquibase.UpdateSummaryEnum)
[ERROR]   location: variable liquibase of type liquibase.Liquibase
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseUpdate.java:[72,18] cannot find symbol
[ERROR]   symbol:   method setShowSummaryOutput(liquibase.UpdateSummaryOutputEnum)
[ERROR]   location: variable liquibase of type liquibase.Liquibase
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java:[290,42] cannot find symbol
[ERROR]   symbol:   method setReplaceIfExistsSet(boolean)
[ERROR]   location: variable diffOutputControl of type liquibase.diff.output.DiffOutputControl
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java:[292,37] no suitable method found for doDiffToChangeLog(java.lang.String,liquibase.database.Database,liquibase.database.Database,java.lang.String,liquibase.diff.output.DiffOutputControl,liquibase.diff.output.ObjectChangeFilter,java.lang.String,liquibase.diff.compare.CompareControl.SchemaComparison[],java.lang.String,java.lang.String)
[ERROR]     method liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(java.lang.String,liquibase.database.Database,liquibase.database.Database,liquibase.diff.output.DiffOutputControl,liquibase.diff.output.ObjectChangeFilter,java.lang.String) is not applicable
[ERROR]       (actual and formal argument lists differ in length)
[ERROR]     method liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(java.lang.String,liquibase.database.Database,liquibase.database.Database,liquibase.diff.output.DiffOutputControl,liquibase.diff.output.ObjectChangeFilter,java.lang.String,liquibase.diff.compare.CompareControl.SchemaComparison[]) is not applicable
[ERROR]       (actual and formal argument lists differ in length)
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java:[304,66] cannot find symbol
[ERROR]   symbol:   variable FORMAT_ARG
[ERROR]   location: class liquibase.command.core.DiffCommandStep
[ERROR] /home/sb/workspaces/liquibase/liquibase/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java:[312,112] cannot find symbol
[ERROR]   symbol:   method parseSnapshotTypes(java.lang.String)
[ERROR]   location: class liquibase.command.core.DiffCommandStep
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :liquibase-maven-plugin
sb@lorenzo:~/workspaces/liquibase/liquibase$
```

**Comment by filipelautert** [comment]
Hello @steinarb ! that's strange.. maybe you need to activate some profiles like:
```
mvn clean install -DskipTests -P non-jdk-8,!liquibase-commercial
```

Or you can use the package generated by the build. You would need to change liquibase version to:
```
<dependency>
  <groupId>org.liquibase</groupId>
  <artifactId>liquibase-core</artifactId>
  <version>0b101bb9fd0465a7876835e21a0cf00a870fb942-SNAPSHOT</version>
</dependency>
```
And follow the instructions from the followijng link to set up authentication to gpm mirror: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry

**Comment by steinarb** [comment]
@filipelautert I got the same error with the above profile selection.

However I can verify that running the test with the snapshot works for me.
Platform: debian 12.4 "bookworm", amd64, maven 3.8.7, java 17.0.9

Here is what I did to verify:
1. First switched to the branch https://github.com/steinarb/liquibase-karaf-feature/tree/derby-pax-exam-changelog-lock-failure-4230 and built with "make clean install", as expected the build went without error (just did this to establish a baseline)
2. Then to verify I still could reproduce the error, I switched to branch https://github.com/steinarb/liquibase-karaf-feature/tree/derby-pax-exam-changelog-lock-failure-4231 and built with "mvn clean install" and got the expected error
3. Then I created a new branch https://github.com/steinarb/liquibase-karaf-feature/tree/derby-pax-exam-changelog-lock-failure-4231 off derby-pax-exam-changelog-lock-failure-4231 and set liquibase version to 4.25.1 and built with "mvn clean install" which got the same error as with liquibase 4.23.1
4. Then I added the following to ~/.m2/settings.xml
   ```
   <settings>
    <servers>
     <server>
      <id>liquibase-github</id>
      <username>steinarb</username>
      <password><access-token></password>
     </server>
    </servers>
    <profiles>
     <profile>
      <id>allow-liquibase-github</id>
      <activation><activeByDefault>true</activeByDefault></activation>
      <repositories>
       <repository>
        <id>liquibase-github</id>
        <url>https://maven.pkg.github.com/liquibase/liquibase</url>
        <snapshots><enabled>true</enabled></snapshots>
       </repository>
      </repositories>
     </profile>
    </profiles>
   </settings>
   ```
5. Then I switched liquibase version to 0b101bb9fd0465a7876835e21a0cf00a870fb942-SNAPSHOT and built with "mvn clean install" and that build went through without an error

**Comment by filipelautert** [comment]
Hello @steinarb ! currently liquibase doesn't have any real OSGI tests, that's why we break the integration so often. Do you think we can use project https://github.com/steinarb/liquibase-karaf-feature.git to test it? Or would we be able to create a simpler one that would meet the requirement of validating liquibase OSGI integration?

**Comment by steinarb** [comment]
@filipelautert I will be overjoyed if you use that repository for testing.

I don't think it is possible to simplify it because the repo is actually three things:

1. [A karaf feature for liquibase](https://github.com/steinarb/liquibase-karaf-feature/blob/master/liquibase-core-karaf/src/main/feature/feature.xml#L15)
2. [A minimal sample karaf feature that relies on the karaf feature and uses it to create a schema in a provided DataSource](https://github.com/steinarb/liquibase-karaf-feature/blob/master/liquibase-integration-test/karaf.liquibase.sample/src/main/feature/feature.xml#L15) (note: at the current time of writing this uses h2 on master, but I'll switch back to derby when I can)
3. [A pax exam test that loads the sample karaf feature and inserts and extracts data from a table in the schema created from liquibase (to prove that the loaded feature actually works)](https://github.com/steinarb/liquibase-karaf-feature/blob/master/liquibase-integration-test/karaf.liquibase.tests/src/test/java/no/priv/bang/karaf/liquibase/tests/LiquibaseKarafFeatureIntegrationTest.java#L41)

Even if you just want the test in 3, you still need the feature created in 2 which requires the feature in 1.

(there are more OSGi bundles under [liquibase-integration-test](https://github.com/steinarb/liquibase-karaf-feature/tree/master/liquibase-integration-test) but the above feature dependencies are what makes it difficult to simplify the test)

A karaf feature is the leaf node of an OSGi dependency graph in apache karaf and make OSGi bundles easy to load and OSGi dependencies easy to resolve (the things that used to be really hard in OSGi).

I use the metaphor that comparing loading features to loading OSGi bundles, is like using APT instead of installing individual .deb packages in debian/ubuntu/etc.

(And if you want to take official ownership of the karaf feature in 1 I would be overjoyed! (but not something I expect to happen if you don't use apache karaf 😄  ))

**Comment by steinarb** [comment]
@filipelautert In the snapshot I tried things worked, but when I tried 4.26.0 (which as far as can tell has the merge of the fix in its commit list) it unfortunately fails in the same way as before https://github.com/steinarb/liquibase-karaf-feature/tree/derby-pax-exam-changelog-lock-failure-4260

Did I need to do something more than bumping the liquibase version when I tested? I can't remember and the above comments doesn't give me a clue.

**Comment by filipelautert** [comment]
@steinarb man, it works on my machine. Am I doing something wrong? `mvn clean install` output:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for liquibase-core karaf feature parent 4.24.1-SNAPSHOT:
[INFO] 
[INFO] liquibase-core karaf feature parent ................ SUCCESS [  0.066 s]
[INFO] liquibase-core karaf feature ....................... SUCCESS [  0.225 s]
[INFO] liquibase karaf feature BOM ........................ SUCCESS [  0.003 s]
[INFO] Liqubase karaf feature integration tests parent .... SUCCESS [  0.278 s]
[INFO] Liqubase karaf feature sample OSGi services ........ SUCCESS [  1.526 s]
[INFO] Liqubase karaf feature sample usage ................ SUCCESS [  3.131 s]
[INFO] Liqubase karaf feature sample datasource receiver .. SUCCESS [  0.671 s]
[INFO] Liquibase karaf feature karaf integration tests .... SUCCESS [  6.114 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.626 s
[INFO] Finished at: 2024-03-04T17:44:10-03:00
[INFO] ------------------------------------------------------------------------
filipe@noctis:~/code/liquibase/demos/liquibase-karaf-feature$ grep -R liquibase.version *.xml
        <liquibase.version>4.26.0</liquibase.version>
filipe@noctis:~/code/liquibase/demos/liquibase-karaf-feature$ git status
On branch derby-pax-exam-changelog-lock-failure-4260
Your branch is up to date with 'origin/derby-pax-exam-changelog-lock-failure-4260'.
```

**Comment by steinarb** [comment]
Hm... am I doing something wrong? Am I fooling myself? 

This is what I'm using for the build:
```
sb@marquez:~/workspaces/liquibase-karaf-feature$ mvn --version
Apache Maven 3.8.7
Maven home: /usr/share/maven
Java version: 17.0.10, vendor: Debian, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.1.0-18-amd64", arch: "amd64", family: "unix"
sb@marquez:~/workspaces/liquibase-karaf-feature$
```

**Comment by steinarb** [comment]
@filipelautert I just thought of something that could be different between your machine and mine:

What does this look like on your machine?
```
ls -al ~/.m2/repository/org/liquibase/liquibase-core/
```

And what does this look like?
```
ls -al ~/.m2/repository/no/priv/bang/karaf/liquibase-karaf-feature/
```

The pax exam integration test uses the maven version LATEST, rather than versionAsInProject() to load the karaf feature.

Using LATEST can be a little fragile and has bitten me from time to time, but using versionAsInProject() breaks when doing releases with maven-release-plugin, but LATEST work with releases so I've stayed with that.

**Comment by filipelautert** [comment]
@steinarb I removed everything from those locations and tried again, but it worked :/
And for the sake of tooling, I'm also on Debian 12 using default maven.

```
filipe@noctis:~/code/liquibase/demos/liquibase-karaf-feature$ ls -al ~/.m2/repository/no/priv/bang/karaf/liquibase-karaf-feature/
total 16
drwxr-xr-x  3 filipe filipe 4096 mar  5 08:22 .
drwxr-xr-x 10 filipe filipe 4096 mar  5 08:22 ..
drwxr-xr-x  2 filipe filipe 4096 mar  5 08:22 4.24.1-SNAPSHOT
-rw-r--r--  1 filipe filipe  302 mar  5 08:22 maven-metadata-local.xml
filipe@noctis:~/code/liquibase/demos/liquibase-karaf-feature$ ls -al ~/.m2/repository/org/liquibase/liquibase-core/
total 12
drwxr-xr-x  3 filipe filipe 4096 mar  5 08:22 .
drwxr-xr-x 17 filipe filipe 4096 mar  5 08:22 ..
drwxr-xr-x  2 filipe filipe 4096 mar  5 08:22 4.26.0
filipe@noctis:~/code/liquibase/demos/liquibase-karaf-feature$ mvn --version
Apache Maven 3.8.7
Maven home: /usr/share/maven
Java version: 17.0.10, vendor: Debian, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.1.0-18-amd64", arch: "amd64", family: "unix"
```

What is the error that you are facing, could you share the stack trace?

**Comment by steinarb** [comment]
Here is the build log: https://gist.github.com/steinarb/779f4fcb43a26482f81536307a596c69

WTF...? That build was successful? This was "mvn -B clean install" with redirect to a file.
Doing the same command just before with "mvn clean install" failed, but I redid it with "-B" to get a cleaner formatting.

I tried doing "mvn clean install" from the command line, without redirect to a file and that failed with messages like:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running no.priv.bang.karaf.liquibase.tests.LiquibaseKarafFeatureIntegrationTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Port 1099 not available, trying next one
Port 44444 not available, trying next one
Port 8101 not available, trying next one
WARNING: package org.apache.karaf.specs.locator not in java.base

LiquibaseKarafFeatureIntegrationTest: testLoadFeature
ERROR: Exception Details
ERROR: Exception Primary Class:  StandardException
ERROR: Exception Primary Reason: Table/View 'DATABASECHANGELOG' already exists in Schema 'APP'.
ERROR: Exception Primary Source: Apache Derby 10.14.2.0 - (1828579)
ERROR: Exception Details
ERROR: Exception Primary Class:  StandardException
ERROR: Exception Primary Reason: A lock could not be obtained within the time requested
ERROR: Exception Primary Source: Apache Derby 10.14.2.0 - (1828579)
```

Is there a touchy timing issue here, I wonder? Feels like it..

Tried "mvn -B clean install" without redirect to a file and that also failed, with the same error as above.

Here is the karaf.log of the latest failing test: https://gist.github.com/steinarb/3a7eab9e96326bcf3b84e33001c26b69

**Comment by steinarb** [comment]
The first stack trace in the karaf.log file with the integration test failing, is here: https://gist.github.com/steinarb/3a7eab9e96326bcf3b84e33001c26b69#file-karaf-log-L340

**Comment by steinarb** [comment]
I've run "mvn clean install" 7 times now today. 6 times it failed and one time it succeeded. 

So I don't think it has anything to do with the use of the -B flag.

Also I think the stack trace looks different: I believe this is something other than the old one. 

This is clearly something to do with ServiceLoader.

**Comment by steinarb** [comment]
This is the problem: liquibase.change.Change: liquibase.change.core.LoadDataChange Unable to get public no-arg constructor

 liquibase.change.core.LoadDataChange has no constructor defined, which I take to mean it has an implicit no-args constructor...? 

Do services loaded by the ServiceLoader need to have an explicit constructor defined?

**Comment by steinarb** [comment]
Hm... no. In this case "Unable to get public no-arg constructor" was caused a ClassNotFoundException: https://stackoverflow.com/a/59646172

And the current stack trace is also caused by a ClassNotFoundException: https://gist.github.com/steinarb/3a7eab9e96326bcf3b84e33001c26b69#file-karaf-log-L561

But in my case I can't understand if the ClassNotFoundException caused by a missing dependency, since then it should always fail, but for me it has succeeded once.

**Comment by filipelautert** [comment]
@steinarb seems the same as https://github.com/liquibase/liquibase/issues/5604 ?

**Comment by steinarb** [comment]
I don't have a library as such.

I have created a karaf feature which is basically is just a list of bundles to load at runtime, using maven coordinates to identify the bundes to load.

Do the two liquibase-core.jar files contain the same stuff? Or do they contain different stuff?

**Comment by steinarb** [comment]
These are the dependencies I added. The may also help with the ClassNotFoundException of https://github.com/liquibase/liquibase/issues/5604 ?
```
diff --git a/liquibase-integration-test/karaf.liquibase.sample/pom.xml b/liquibase-integration-test/karaf.liquibase.sample/pom.xml
index ca696749c..e6ad39c7b 100644
--- a/liquibase-integration-test/karaf.liquibase.sample/pom.xml
+++ b/liquibase-integration-test/karaf.liquibase.sample/pom.xml
@@ -37,6 +37,36 @@
             <type>xml</type>
             <classifier>features</classifier>
         </dependency>
+        <dependency>
+            <groupId>com.opencsv</groupId>
+            <artifactId>opencsv</artifactId>
+            <version>5.9</version>
+        </dependency>
+        <dependency>
+            <groupId>commons-beanutils</groupId>
+            <artifactId>commons-beanutils</artifactId>
+            <version>1.9.4</version>
+        </dependency>
+        <dependency>
+            <groupId>org.apache.commons</groupId>
+            <artifactId>commons-lang3</artifactId>
+            <version>3.14.0</version>
+        </dependency>
+        <dependency>
+            <groupId>org.apache.commons</groupId>
+            <artifactId>commons-text</artifactId>
+            <version>1.11.0</version>
+        </dependency>
+        <dependency>
+            <groupId>commons-collections</groupId>
+            <artifactId>commons-collections</artifactId>
+            <version>3.2.2</version>
+        </dependency>
+        <dependency>
+            <groupId>org.apache.commons</groupId>
+            <artifactId>commons-collections4</artifactId>
+            <version>4.4</version>
+        </dependency>
         <dependency>
             <groupId>org.junit.jupiter</groupId>
             <artifactId>junit-jupiter-api</artifactId>
```

**Comment by steinarb** [comment]
I have moved to 4.27.0 and the issue is more present here than before.

It is possible this is because the derby version used is kinda antiquated. It's from 2018: https://db.apache.org/derby/derby_downloads.html#For+Java+8+and+Higher+%28releases+which+support+lambda+expressions%29

The reason I'm using it is because it is the version supported by pax jdbc-config https://github.com/ops4j/org.ops4j.pax.jdbc?tab=readme-ov-file#pax-jdbc

And the reason it is stuck there is, I'm guessing, that it is the last version built with Java 8 and that they are still trying to preserve backwards compatibility...?

[pax jdbc-config lets me create a Datasource from config](https://steinar.bang.priv.no/2019/11/30/rewriting-applications-to-use-pax-jdbc-config-and-liquibase/). Unfortunately the docs aren't really up to speed.

**Comment by filipelautert** [comment]
Hy @steinarb! I ran mvn clean install using java 11/17 and all build fine. What issues are you facing?

**Comment by steinarb** [comment]
Note that the master of my liquibase-karaf-feature now uses h2 instead of derby in the integration test to work around the issue.

But anyway: after 4.27.0 the problem has migrated to my other projects see, e.g. this broken gitlab actions build:
 https://github.com/steinarb/ukelonn/actions/runs/8587662577/job/23531592006
(the build got stuck in the failed pax exam test and never terminated by its own. Was killed by gitlab actions after 6h looks like).

I _think_ the problem is a race condition in Embedded Derby.

I _hope_ the problem can be fixed by upgrading the derby version used by pax-jdbc-config (see https://github.com/ops4j/org.ops4j.pax.jdbc/issues/364 for more on this).

**Comment by filipelautert** [comment]
@steinarb ok, let's hope it get upgraded soon. Otherwise we can test with one of your other projects and try to find a way to isolate derby driver issue.
