### ISSUE TITLE
Regression: multiple createProcedure changes in one changeSet with different dbms values causes "not a supported DB" error

### ISSUE THREAD

**Issue by dhsmith1001** [liquibase/liquibase#5371]
### Search first

- [X] I searched and no similar issues were found

### Description

We have multiple changeSets that worked in Liquibase 3.5.1 that contain three createProcedure changes, each with a unique dbms value (mssql, oracle, postgresql). When run with 4.25.0, they produce errors like below:

Unexpected error running Liquibase: Validation Failed:
     2 changes have validation failures
          oracle is not a supported DB, src/test/resources/TestChangelogOld.xml::100::test
          mssql is not a supported DB, src/test/resources/TestChangelogOld.xml::100::test

The error message is misleading as oracle and mssql are valid values for dbms.

Splitting the changeSet into three changeSets, each with the unique dbms value at the changeSet level works around the problem.
[TestChangelogs.zip](https://github.com/liquibase/liquibase/files/13662520/TestChangelogs.zip)

### Steps To Reproduce

Unzip the attached zip file. Edit TestCreateProcedure.sh as needed for jar file paths, then execute.

The first Liquibase execution will fail with the above errors. The second execution should succeed.

### Expected/Desired Behavior

A changeSet with multiple createProcedure changes should be supported, especially if each createProcedure element has a unique dbms value.

### Liquibase Version

4.25.0

### Liquibase Integration

CLI

### OS and/or Infrastructure Type/Provider

Ubuntu 23.10

### Additional Context

PostgreSQL
15.5 (Ubuntu 15.5-0ubuntu0.23.10.1)
PostgreSQL JDBC Driver
42.2.5

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
Hello @dhsmith1001! We were trying to reproduce it using your example and i failed as expected.
But we noticed that we can remove run parameter `--databaseClass=liquibase.database.core.PostgresDatabase` and then it will start working. In fact database class is not required/necessary anymore, so you can get rid of that. Would it work for you?

Anyway, we acknowledge that when `dbms` value is used within `createProcedure` it has a different behavior than when used in the `changeSet` element and we should fix this.

**Comment by dhsmith1001** [comment]
Same error with multiple <sql> changes in one changeSet.

**Comment by dhsmith1001** [comment]
> Same error with multiple changes in one changeSet.

That was wrong, it's when a changeSet has dbms with > 1 value:  dbms="postgresql,mssql". Error is mssql is "mssql is not a supported DB"

**Comment by dhsmith1001** [comment]
See https://github.com/liquibase/liquibase/pull/5397

**Comment by filipelautert** [comment]
Fixed by https://github.com/liquibase/liquibase/pull/5397
