### ISSUE TITLE
When upgrading from Liquibase 4.18.0 to 4.19.1, the checksum for PL/SQL that has been run against the db does not match anymore resulting in a failed deployment

### ISSUE THREAD

**Issue by fmavb** [liquibase/liquibase#5395]
### Search first

- [X] I searched and no similar issues were found

### Description

When running a liquibase deployment after upgrading to 4.19.1, the changesets checksums that have already been deployed for PL/SQL are not recomputed correctly. Hence, it is not possible to update to the latest version.

Output is:
Validation Error: 
     26 changesets have changed since they were ran against the database

Reverting back to 4.18.0 version of liquibase resolves the issue. We have tried updating to 4.25.0 with the same result of badly recomputed checksums.

### Steps To Reproduce

1. Run a PL/SQL deployment using the liquibase version 4.18.0, use the following command to run it:
`/etc/alternatives/jre_1.8.0/bin/java -cp "liquibase-commercial-4.17.2.jar:liquibase-core-4.18.0.jar:$ORACLE_HOME/jdbc/lib/ojdbc8.jar" liquibase.integration.commandline.Main --defaultSchemaName=$DB_SCHEMA --changeLogFile=$CHANGE_LOG/changeLog.oracle.xml --url=jdbc:oracle:oci:/@$DB_TNS --contexts="$CONTEXTS" --logfile=$OUTPUT_FOLDER/output.log --loglevel=$LOG_LEVEL update >> $OUTPUT_FOLDER/stdout.log 2>&1`

Changeset xml:
`<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:pro="http://www.liquibase.org/xml/ns/pro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-4.6.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.6.xsd">
    <changeSet author="me" id="test-create" context="DEV" runWith="sqlplus">
        <comment>Create test table with sqlplus</comment>
        <sqlFile path="create_test_table.sql" relativeToChangelogFile="true"/>
    </changeSet>
    <changeSet author="me" id="test-drop" context="DEV" runWith="sqlplus">
        <comment>Drop test table with sqlplus</comment>
        <sqlFile path="drop_test_table.sql" relativeToChangelogFile="true"/>
    </changeSet>
</databaseChangeLog>`

create_test_table.sql
`CREATE TABLE SCHEMA.LIQUIBASE_TEST (
    TEST_COLUMN VARCHAR2(50) NULL
)
/`

drop_test_table.sql
`DROP TABLE SCHEMA.LIQUIBASE_TEST
/`

3. Update the liquibase version to 4.19.1
4. Rerun the deployment using this command:
`/etc/alternatives/jre_1.8.0/bin/java -cp "liquibase-commercial-4.19.1.jar:liquibase-core-4.19.1.jar:$ORACLE_HOME/jdbc/lib/ojdbc8.jar" liquibase.integration.commandline.Main --defaultSchemaName=$DB_SCHEMA --changeLogFile=$CHANGE_LOG/changeLog.oracle.xml --url=jdbc:oracle:oci:/@$DB_TNS --contexts="$CONTEXTS" --logfile=$OUTPUT_FOLDER/output.log --loglevel=$LOG_LEVEL update >> $OUTPUT_FOLDER/stdout.log 2>&1`

### Expected/Desired Behavior

Checksums should be the same between the different liquibase versions.

### Liquibase Version

4.19.1

### Database Vendor & Version

Oracle 19c

### OS and/or Infrastructure Type/Provider

RHEL 8.8

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @fmavb, I ran `calculate-checksum` on your changesets for both Liquibase versions 4.18.0 and 4.19.1, and the output is the same. The checksums did not change.
However, they will change if something around them is modified, such as the filepath. Can you confirm if the files have remained unchanged?

**Comment by gbisset** [comment]
Hi,

It appears that @fmavb may have over simplified the example but it could also be that calculate-checksum and update appear to be generating different checksums.

Our structure is actually as follows:

```
TEST/
    changeLog.xml
    TEST_INNER/
        changeLog.oracle.xml
        create_test_table.sql
        drop_test_table.sql
```

TEST/changeLog.oracle.xml
==================
```xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:pro="http://www.liquibase.org/xml/ns/pro" xmlns:xsi=
"http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.li
quibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-4.6.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.6.xsd">
    <include file="TEST/TEST_INNER/changeLog.oracle.xml"/>
</databaseChangeLog>
```

TEST/TEST_INNER/changeLog.xml
======================
```xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:pro="http://www.liquibase.org/xml/ns/pro" xmlns:xsi=
"http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.li
quibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-4.6.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.6.xsd">
    <changeSet author="me" id="TEST-create" context="DEV" runWith="sqlplus">
        <comment>TEST - create</comment>
        <sqlFile path="create_test_table.sql" relativeToChangelogFile="true"/>
    </changeSet>

    <changeSet author="me" id="TEST-drop" context="DEV" runWith="sqlplus">
        <comment>TEST - drop</comment>
        <sqlFile path="drop_test_table.sql" relativeToChangelogFile="true"/>
    </changeSet>
</databaseChangeLog>
```

Focusing on TEST-create changeset...

calculate-checksum does not seem to work for this changeset on 4.18.0, it gives error "Unexpected error running Liquibase: Resource does not exist"

When I run calculate-checksum on both 4.19.1 and 4.25.0, both give the same checksum that was stored in databasechangelog table by 4.18.0:

> Starting Liquibase at 23:32:05 (version 4.19.1 #7641 built at 2023-02-28 18:08+0000)
> 8:a021c4a64bbd4bbb56df5e573b155615
> Liquibase command 'calculateChecksum' was executed successfully.

> Starting Liquibase at 23:32:07 (version 4.25.0 #3966 built at 2023-11-10 23:07:29 UTC)
> 8:a021c4a64bbd4bbb56df5e573b155615
> Liquibase command 'calculateChecksum' was executed successfully.

However, running an update command on these versions generates a different checksum and fails!

> Starting Liquibase at 23:24:21 (version 4.19.1 #7641 built at 2023-02-28 18:08+0000)
> Validation Error: 
>      2 changesets have changed since they were ran against the database
>           TEST/TEST_INNER/changeLog.oracle.xml::TEST-create::me was: 8:a021c4a64bbd4bbb56df5e573b155615 but is now: 8:0202c5f32b2e815ef473e89fe1d1d8b1
>           TEST/TEST_INNER/changeLog.oracle.xml::TEST-drop::me was: 8:c7cce31e701fb9a72bc88dad3513cea7 but is now: 8:c03c3b6d5134daa285c24dfd51072d79

> Starting Liquibase at 23:30:17 (version 4.25.0 #3966 built at 2023-11-10 23:07:29 UTC)
> Validation Error: 
>      2 changesets have changed since they were ran against the database
>           TEST/TEST_INNER/changeLog.oracle.xml::TEST-create::me was: 8:a021c4a64bbd4bbb56df5e573b155615 but is now: 8:0202c5f32b2e815ef473e89fe1d1d8b1
>           TEST/TEST_INNER/changeLog.oracle.xml::TEST-drop::me was: 8:c7cce31e701fb9a72bc88dad3513cea7 but is now: 8:c03c3b6d5134daa285c24dfd51072d79

I can confirm that nothing was changed in the changesets between these examples, only the liquibase command itself

**Comment by filipelautert** [comment]
Before 4.22.0 we had a bunch of checksums issues, but since it we bumped checksums version and we are being more careful about it. So this issue is gone now and we are doing our best to do not cause others like this one.
