### ISSUE TITLE
Regression: changeSet with multiple comma separated dbms results in error

### ISSUE THREAD

**Issue by dhsmith1001** [liquibase/liquibase#5396]
### Search first

- [X] I searched and no similar issues were found

### Description

A changeSet with dbms="postgresql,mssql" throws error "mssql is not a supported DB". If the changeSet is split into two, each with a single dbms value, it works.

Attached is a zip file containing a test change log, shell script to run it and the output.
[TestMultipleDbms.zip](https://github.com/liquibase/liquibase/files/13686435/TestMultipleDbms.zip)

### Steps To Reproduce

Unzip the attached file and execute included sh file.

### Expected/Desired Behavior

The changeSet with dbms="postgresql,mssql" should validate successfully and execute when either of those database types is the target.

### Liquibase Version

4.25.0

### Liquibase Integration

CLI

### OS and/or Infrastructure Type/Provider

Ubuntu 23.10

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR (Thank you!)

**Comment by dhsmith1001** [comment]
Note: this can be worked around by not specifying --databaseClass when running Liquibase. The issue is that the DatabaseFactory contains only the database instance specified by the databaseClass parameter in its "implementedDatabases" HashMap instead of all available databases when the parameter is used.

**Comment by dhsmith1001** [comment]
See https://github.com/liquibase/liquibase/pull/5397

**Comment by filipelautert** [comment]
Fixed by https://github.com/liquibase/liquibase/pull/5397
