### ISSUE TITLE
CustomTask ROLLBACK executed twice

### ISSUE THREAD

**Issue by marianomerlo** [liquibase/liquibase#5422]
### Search first

- [X] I searched and no similar issues were found

### Description

This is very similar to what was reported here: https://github.com/liquibase/liquibase/issues/5314 but for the rollback command instead of the update. 

I've gone through all the conversation in there, forked the project used to reproduce #5314 and added the rollback operation to give you a minimal project to reproduce the rollback issue as well: 

https://github.com/marianomerlo/liquibase-issue-custom-task-change

The latest working release for the rollback seems to be 4.19.0. 

### Steps To Reproduce

1. Create any custom change with rollback.
2. Perform a liquibase update
3. Perform a liquibase rollback

### Expected/Desired Behavior

Rollback operation should be executed once

### Liquibase Version

4.25.1

### Database Vendor & Version

PostgresSQL 13.11

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @marianomerlo, thank you for reporting this issue. I was able to replicate it with Liquibase version 4.25.1.

I'll forward this to the development team so they can look into it. If you have any suggestions on how to fix it, you can create a PR and we'll guide you when necessary.

Thank you,
Tatiana

**Comment by momosetkn** [comment]
this problem was solved by 4.30.0
