### ISSUE TITLE
command "unexpectedChangesets" always reports at least 1 unexpected changeset with initial tag in database

### ISSUE THREAD

**Issue by afigur** [liquibase/liquibase#5442]
### Search first

- [X] I searched and no similar issues were found

### Description

Performing "tag" on an empty database creates a "liquibase-internal" changeset.
"unexpectedChangesets" fails to disregard this changeset and always reports at least 1 unexpected changeset.

### Steps To Reproduce

Step 1: start with empty database
Step 2: tag "mytag"
Step 3: execute 1 changeset
Step 4: run "unexpectedChangesets" with no changes made after step 3
Step 5: get 1 unexpected changeset reported back

### Expected/Desired Behavior

get **no** unexpected changeset reported back

### Liquibase Version

4.25.1

### Database Vendor & Version

Oracle

### Liquibase Integration

-core lib in java project

### Liquibase Extensions

- none -

### OS and/or Infrastructure Type/Provider

Win 11

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @afigur, as there's a PR in the works that's supposed to fix this issue (#5446 ), I'd suggest you to subscribe to it so you can get updates on its progress.
