### ISSUE TITLE
liquibase 4.24.0 is unable to find the databasechangelog table only when initializing on a fresh mysql database

### ISSUE THREAD

**Issue by romitojoseph-95** [liquibase/liquibase#5450]
### Search first

- [X] I searched and no similar issues were found

### Description

I am trying to update the database using liquibase version 4.24.0 on an fresh database.
My liquibase-start.sh file commands are given below,

         liquibase --url="$url" --username="$username" --password="$password" --changeLogFile=$changelogfile --logLevel=info --driver=com.mysql.jdbc.Driver clearCheckSums
         liquibase --url="$url" --username="$username" --password="$password" --changeLogFile=$changelogfile --logLevel=info --driver=com.mysql.jdbc.Driver update

I got below error from logs.

**liquibase.exception.CommandExecutionException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Table 'test_databse.databasechangelog' doesn't exist [Failed SQL: (1146) UPDATE test_databse.databasechangelog SET MD5SUM = NULL]**

I am not able to fix this.

### Steps To Reproduce

1. Create a new database
2. Run a liquibase script  using given commands

          liquibase --url="$url" --username="$username" --password="$password" --changeLogFile=$changelogfile --logLevel=info --driver=com.mysql.jdbc.Driver clearCheckSums
          liquibase --url="$url" --username="$username" --password="$password" --changeLogFile=$changelogfile --logLevel=info --driver=com.mysql.jdbc.Driver update
           
If you can suggest what to test to find out why liquibase does not work in our case I'd be thankful.

### Expected/Desired Behavior

4.24.0 being able to start with empty db.

### Liquibase Version

4.24.0

### Database Vendor & Version

mysql:5.7

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @romitojoseph-95, this is luckily an easy fix :)
Running `clearCheckSums` requires the `databasechangelog` table to exist, as it works by updating the values in that table.

Considering that the database is fresh, and contains no data, there's no reason to run `clearCheckSums` at this time. Run only the second command and it will work as expected.

 [Here's](https://docs.liquibase.com/commands/maintenance/clear-checksums.html) some more info on the command, including which scenarios could require its usage.

**Comment by romitojoseph-95** [comment]
Hi ,
I tried using Liquibase version 4.23.2 on a fresh database with the
following commands. It worked as expected on a fresh database, and the
'databasechangelog' table was created automatically.

  liquibase --url="$url" --username="$username" --password="$password"
--changeLogFile=$changelogfile --logLevel=info
--driver=com.mysql.jdbc.Driver clearCheckSums
  liquibase --url="$url" --username="$username" --password="$password"
--changeLogFile=$changelogfile --logLevel=info
--driver=com.mysql.jdbc.Driver update
However, it is not working in Liquibase 4.24.0 on a fresh database.

Are there any changes made in Liquibase version 4.24.0 and beyond that
could be affecting this functionality? Could you please provide
clarification on this matter?

**Comment by tati-qalified** [comment]
Probably #4762, as it's the only PR for v4.24.0 that involves checksums.
Is it necessary for your workflow to run `clearChecksums` at that point? Is this change creating problems?

**Comment by romitojoseph-95** [comment]
Facing the same problem from version 4.25.0. My current image is kilna/liquibase-mysql, and the MD5SUM format is 7:f3a0bdf8113b4be613d9d40068f24120. I tried to upgrade Liquibase to version 4.25.0, but got an issue with 'clearCheckSums' on a fresh database. The same problem occurs in version 4.24.0.

If I do not use the clearCheckSums command, I got the following error during the update command:

       Unexpected error running Liquibase: Validation Failed:
      1 changesets check sum
      upgrade was:7:f3a0bdf8113b4be613d9d40068f24120 but is now: 7:f3a0bdf8113b4be61356576868

Then tried to downgrade the version to v4.23.2. Then it is working fine.

**Comment by tati-qalified** [comment]
Could you share your changelog?

**Comment by romitojoseph-95** [comment]
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
                   xmlns:pro="http://www.liquibase.org/xml/ns/pro"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro liquibase-pro-3.8.xsd http://www.liquibase.org/xml/ns/dbchangelog dbchangelog-3.8.xsd"
                   logicalFilePath="changelog.xml">
    <changeSet author="Test (generated)" id="test_id">
        <createTable tableName="test_master">
            <column autoIncrement="true" name="id" type="INT">
                <constraints nullable="false" primaryKey="true"/>
            </column>
            <column name="updated_on" type="datetime"/>
        </createTable>
    </changeSet>
    <changeSet author="Test (generated)" id="test_id1">
        <addForeignKeyConstraint baseColumnNames="test_id" baseTableName="test_db" constraintName="fk_test_cat_id" deferrable="false" initiallyDeferred="false" onDelete="RESTRICT" onUpdate="RESTRICT" referencedColumnNames="id" referencedTableName="test_master" validate="true"/>
    </changeSet>
    <changeSet author="Test (generated)" id="test_id2">
        <sql>
            UPDATE tabale_name SET is_deleted=0 WHERE id=1;
         </sql>
    </changeSet>     
</databaseChangeLog>
