### ISSUE TITLE
Context-Filter is not working with logical expressions

### ISSUE THREAD

**Issue by MalloD12** [liquibase/liquibase#5458]
### Search first

- [X] I searched and no similar issues were found

### Description

When using a logical expressions AND/OR in the context filter field of a changeset is not working. 

### Steps To Reproduce

Having a changeset like the one below:

```
<changeSet id="TAG-v1.3.0" author="dev-team" contextFilter="(JIRA-1 or TEST)">
        <tagDatabase tag="v1.3.0"/>
    </changeSet>
    <include file="reference_create-table.xml" relativeToChangelogFile="true" contextFilter="(JIRA-1 or TEST)"/>
```

and then executing the below command:

```
liquibase update --context-filter="JIRA"
```

Actual Result: context filtering is not working and both changesets are deployed.

### Expected/Desired Behavior

According to documentation:
```
In Liquibase 4.23.0+, you can specify a context using @ in addition to AND, OR, !, and parentheses in the changesets. This requires you to designate a context or label explicitly when Liquibase is run for the changeset to run. The attribute context: @test causes a changeset to not run if Liquibase runs without any contexts provided.
```

context filtering should filter both changesets and not deploy any of them.

Docs Ref: https://docs.liquibase.com/concepts/changelogs/attributes/contexts.html

### Liquibase Version

4.25.1

### Liquibase Integration

CLI

### Additional Context

None

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nvoxland** [comment]
I think this is behaving as expected?

The context-filter attribute is setting the expression to filter contexts, but on the CLI you're specifying a context-filter too not a context. If you run `liquibase update --context=JIRA` does it work?

**Comment by MalloD12** [comment]
> I think this is behaving as expected?
> 
> The context-filter attribute is setting the expression to filter contexts, but on the CLI you're specifying a context-filter too not a context. If you run `liquibase update --context=JIRA` does it work?

Hi @nvoxland,


Sorry for my late response, I missed your response on this issue. No, running `liquibase update --context=JIRA` didn't work and that's why I raised this issue. If I didn't get it wrong the command execution you mentioned should work with the changeset example I provided on this issue. 

Thanks,
Daniel.

**Comment by filipelautert** [comment]
Hi @MalloD12 - I'm testing this one and seems it's working now. I'm using the example above and running using parameters ` "--contexts=JIRA" update-sql` and nothing gets executed. If I change to JIRA-1 then both changes are executed as expected. Maybe with latest changes to those methods it was fixed?

**Comment by MalloD12** [comment]
Hey @filipelautert,

I created this issue because it complained about using context expressions like `contextFilter="(JIRA-1 or TEST)`.  So, if any of them are later specified as a command argument then the given changeset should be processed. 

Thanks,
Daniel.

**Comment by filipelautert** [comment]
Moving discussion to https://github.com/liquibase/liquibase/issues/1813 as it has a nice description of the issue.
