### ISSUE TITLE
Liquibase 4.25.1 complains about a certain UTF-8 character in PL/SQL code

### ISSUE THREAD

**Issue by mk-github-77** [liquibase/liquibase#5483]
### Search first

- [X] I searched and no similar issues were found

### Description

I assume it is related to https://github.com/liquibase/liquibase/pull/5474

When deploying our codebase with the help of Liquibase, an error is currently occurring with a certain package. The package can no longer be deployed and Liquibase terminates with an error message:

[2024-01-19 11:58:17] HEAVILY [liquibase.integration] Lexical error at line 489, column 73. Encountered: '\u00f7' (247),
liquibase.util.grammar.TokenMgrError: Lexical error at line 489, column 73. Encountered: '\u00f7' (247),
	at liquibase.util.grammar.SimpleSqlGrammarTokenManager.getNextToken(SimpleSqlGrammarTokenManager.java:1410)

Unexpected error running Liquibase: Lexical error at line 489, column 73. Encountered: '\u00f7' (247),

liquibase.util.grammar.TokenMgrError: Lexical error at line 489, column 73. Encountered: '\u00f7' (247),
	at liquibase.util.grammar.SimpleSqlGrammarTokenManager.getNextToken(SimpleSqlGrammarTokenManager.java:1410)

There were no problems with this package in the previous version. There have been no changes to this package since the last Liquibase version.

### Steps To Reproduce

The following ChangeSets should reproduce the error:

-- changeset.xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">

    <changeSet id="murks" runOnChange="true">
        <sqlFile path="murks.pks" relativeToChangelogFile="true" endDelimiter="\n/" />
        <sqlFile path="murks.pkb" relativeToChangelogFile="true" endDelimiter="\n/" />
    </changeSet>

</databaseChangeLog>

-- file: murks.pks - utf-8
create or replace package murks as

  procedure foobar;

end murks;
/

-- file: murks.pkb - utf-8
create or replace package body murks as

  procedure foobar
  is
    l_pat varchar2(200) := q'[-~+±_–—/\‚,(){}[]<>‹.#&''"`´’!?¿:;*|²³½¾^÷@¯£=$Þ°§·¦¢…%¶]';
    l_rep varchar2(200) := q'[                                                        ]';
  begin
    -- do nothing;
    null;
  end foobar;

end murks;
/

-- This char should be be the problem: ÷

### Expected/Desired Behavior

No errors when providing correct code with UTF-8 strings.

### Liquibase Version

4.25.1

### Database Vendor & Version

Oracle 19c

### Liquibase Integration

CLI

### OS and/or Infrastructure Type/Provider

MacOS 14.2.1 - Sonoma / Linux

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
But I found out something else: I created a simple PR that adds 3 new tests to the parser :

```
"This has a symbol ≤ (u2264) but no backslash"  
"This has a \\ and symbol ≤ (u2264)"    
"This ≤ (u2264) is before the \\" 
```

And the 3 are failing:
```
Error:    SimpleSqlGrammarTest.test:16 » TokenMgr Lexical error at line 1, column 19.  Encountered: '\u2264' (8804),
Error:    SimpleSqlGrammarTest.test:16 » TokenMgr Lexical error at line 1, column 25.  Encountered: '\u2264' (8804),
Error:    SimpleSqlGrammarTest.test:16 » TokenMgr Lexical error at line 1, column 6.  Encountered: '\u2264' (8804),
```

https://github.com/liquibase/liquibase/actions/runs/7658028804/job/20870094617?pr=5506

And if I add those tests to 4.25.0 or 4.24.0 they also fail. To make it work I need to add those unicode intervals to the tokens inside SimpleSqlGrammar class. So now I'm in doubt if it was really caused by the mentioned PR or if was something else related to encoding loading.

**Comment by Lunatix01** [comment]
Same problem here, An Arabic number causes the error on `4.25.1`

**Comment by filipelautert** [comment]
Hello! Are you able to give PR https://github.com/liquibase/liquibase/pull/5506 a try and see if it fixes your problems? 

Liquibase ZIP file is available at https://github.com/liquibase/liquibase/actions/runs/7815163784/artifacts/1226985137 .

Or you can use the package as a maven dependency, using 

<dependency>
  <groupId>org.liquibase</groupId>
  <artifactId>liquibase-core</artifactId>
  <version>51888f3d62e63b10abe952042e4d1af3ddfb9f80-SNAPSHOT</version>
</dependency>

To use it you'll need to set up a github and a token as specified in https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry .
