### ISSUE TITLE
MariaDB: Liquibase 4.25.1 is creating `boolean` columns as `TINYINT` instead of `BIT(1)` or at least `TINYINT(1)`

### ISSUE THREAD

**Issue by famod** [liquibase/liquibase#5489]
### Search first

- [X] I searched and no similar issues were found

### Description

While trying to update my Quarkus application form Quarkus 3.6 to 3.7.0.CR1 (which includes Liquibase 4.24.0 -> 4.25.1) I'm seeing the following db validation errors via Hibernate:
> org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [is_public] in table [`catalog_value_metadata`]; found [tinyint (Types#TINYINT)], but expecting [bit (Types#BOOLEAN)]

To rule out other dependency jumps that are contained in that Quarkus upgrade (like Hibernate 6.2 -> 6.4), I reduced the updates involved to just Liquibase 4.24.0 -> 4.25.1 and I could still reproduce the error.

It think this is a combination of:
- #4090, which already in 4.24.0 changed `BIT(1)` to `TINYINT(1)` but for MariaDB/Hibernate that seems to be equivalent, hence no error here
- #5130 built on top of #4090 in 4.25.1 and changed `TINYINT(1)` to `TINYINT` which now isn't considered equivalent to BIT/BOOLEAN anymore (which kinda makes sense)

I have to say I don't fully get the reasoning behind #4090 but I'm under the impression that his change doesn't make a lot of sense for MariaDB (especially with #5130 on top).

I can work around by setting e.g. `<column ... type="BIT(1)" ...` instead of `type="boolean"` but that doesn't feel right (also because I'd then need to fiddle around with valid checksums).

### Steps To Reproduce

Define something like:
> <column name="is_public" type="boolean" defaultValueBoolean="false"\>

on MariaDB and check the type of the column.

### Expected/Desired Behavior

Not sure which of `BOOLEAN`, `BIT(1)` or `TINYINT(1)` is best, but at least don't generate just `TINYINT` anymore (for MariaDB).

See also:
- https://mariadb.com/kb/en/boolean/
- https://mariadb.com/kb/en/sql_language-data_types-tinyint/
- https://mariadb.com/kb/en/boolean/

### Liquibase Version

4.25.1

### Database Vendor & Version

MariaDB 10.6.16

### Liquibase Integration

Quarkus

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by MalloD12** [comment]
Hi @famod,

 The purpose of #4090 was to adapt Liquibase to what MySQL documentation refers on its Data Type usage (see [this](https://dev.mysql.com/doc/refman/8.0/en/other-vendor-data-types.html)), which originally refers to use `TinyInt(1)` instead of  BIT(1) which was used before when specifying a boolean column. Later, with this MySQL [change](https://dev.mysql.com/worklog/task/?id=13127) this was refined to be returned just as `TinyInt`. I think if this change introduced in MySQL `8.0.17` is not applicable for MariaDB your proposed code should be like:

```diff
diff --git a/liquibase-standard/src/main/java/liquibase/datatype/core/BooleanType.java b/liquibase-standard/src/main/java/liquibase/datatype/core/BooleanType.java
index e50b4e3f0..674c25de7 100644
--- a/liquibase-standard/src/main/java/liquibase/datatype/core/BooleanType.java
+++ b/liquibase-standard/src/main/java/liquibase/datatype/core/BooleanType.java
@@ -40,7 +40,7 @@ public class BooleanType extends LiquibaseDataType {
             if (originalDefinition.toLowerCase(Locale.US).startsWith("bit")) {
                 return new DatabaseDataType("BIT", getParameters());
             }
-            return new DatabaseDataType("TINYINT");
+            return database instanceof MariaDBDatabase ? new DatabaseDataType("TINYINT(1)") : new DatabaseDataType("TINYINT");
         } else if (database instanceof OracleDatabase) {
             try {
                 if (database.getDatabaseMajorVersion() >= OracleDatabase.ORACLE_23C_MAJOR_VERSION) {
```

Since at the end when defining a boolean column in a changelog it will be deployed as a `TinyInt(1)` in the DB.

Thanks,
Daniel.

**Comment by famod** [comment]
Hi @MalloD12,

thanks for your reply.

I'm fine with `TINYINT(1)` instead of `BOOLEAN`. I'll send a PR in the next few days.

**Comment by MalloD12** [comment]
> Hi @MalloD12,
> 
> thanks for your reply.
> 
> I'm fine with `TINYINT(1)` instead of `BOOLEAN`. I'll send a PR in the next few days.

Hi @famod,

Awesome, thank you!

**Comment by famod** [comment]
PR created: #5522
