### ISSUE TITLE
Performance degradation when switching from v3.6.3 to v4.25.1

### ISSUE THREAD

**Issue by Dasiu** [liquibase/liquibase#5507]
### Description

Using the same changelogs and database/schema liquibase after upgrade to version 4.25.1 is a few times slower, e.g. 33 minutes instead of 8 minutes.

* First I waited for checksums upgrade, then I executed liquibase once again without any new migrations in version 4.25.1 to compare performance between liquibase versions.
* In my setup multiple Liquibase objects are executed in parallel migrating different DB schemas and DB hosts.
* ThreadLocalScopeManager is registered before starting migration.

I managed to profile liquibase 4.25.1 and I have two observations:
* There are a lot of calls to AbstractMapConfigurationValueProvider#getProvidedValue. Threads are waiting on a lock. In this critical section, among other things, EnvironmentValueProvider is called and it looks like computing hash of its map may be time consuming, which may be relevant in the context of multiple other threads waiting.
* There are child scopes spawned in high numbers. Scope initialization takes time, mainly scope id generation.

Could you take a look at this problem?

### Expected/Desired Behavior

No performance degradation.

### Liquibase Version

3.6.3 => 4.25.1

### Database Vendor & Version

MySQL

### Liquibase Integration

Called directly, programmatically. 

### Liquibase Extensions

-

### OS and/or Infrastructure Type/Provider

Linux

**Comment by kevin-atx** [comment]
@tati-qalified, could you send them information on running the profiler built into Liquibase?

**Comment by sebastian-jansson** [comment]
> @tati-qalified, could you send them information on running the profiler built into Liquibase?

[--monitor-performance](https://docs.liquibase.com/parameters/monitor-performance.html)

**Comment by tati-qalified** [comment]
@Dasiu as Sebastian said, the `--monitor-performance` parameter creates a file containing all information about the execution of Liquibase code.

If you could provide us with that file, as well as some information about the approximate number of Liquibase instances and changesets being executed, we'll look into this.

Thank you,
Tatiana

**Comment by Dasiu** [comment]
Unfortunatley JFR file can contain potentially sensitive information, I would like to be judicious and abstain from providing it.

More context:
* ~1300 changesets already persisted in DATABASECHANGELOG table.
* Hundreds of similar DB schemas are migrated on the same DB host on multiple DB hosts.
* No new changesets executed -- just "dry run".
* 4 Liquibase instances migrating simultaneously. Total number of Liquibase instances created ~1100.

More observations:
* Liquibase 4.25.1 executes more SQL queries than 3.6.3. Screenshots compare queries executed for just one DB schema (GRANT and CREATE SCHEMA queries are not issued by Liquibase directly).
* Own execution time reveals that apart from DB communication, significant time is devoted to scope id generation: "Arrays.copyOfRange", "SecureRandom", "RandomIO" are all back tracing to scope id generation.
![liquibase-3 6 3-queries](https://github.com/liquibase/liquibase/assets/1692309/aab8dda1-8725-4d75-867a-8bec37210fd7)
![liquibase-4 25 1-queries](https://github.com/liquibase/liquibase/assets/1692309/e1fd4f9a-94b1-49d5-945d-a206468046e4)
![method-list-total-time-own-execution](https://github.com/liquibase/liquibase/assets/1692309/596fe8f7-d7ce-471b-af2c-7dbd7b5ca5e1)
![liquibase-4 25-scope-id-generation-back-trace](https://github.com/liquibase/liquibase/assets/1692309/ab32a2d9-a45d-47e7-9707-24a4e6dc86a4)

**Comment by tati-qalified** [comment]
@Dasiu I understand that uploading the JFR publically is not ideal, but without it we won't be able to find the source of the issue. 
To ensure more privacy, we can provide a channel between you and our team, and limit the amount of people that have access to the file. 
Let me know if this works for you.

**Comment by Dasiu** [comment]
https://github.com/Dasiu/liquibase-performance-degradation/tree/main Here is code which reproduces the issue. Its profile reveals the issues/observations I mentioned.

To summarize what I found earlier.
* Looks like more queries are executed per schema in newer version of Liquibase. The question is why more queries are executed and whether something could be done to alleviate performance drop.
* Scope id generation in its current form is CPU consuming.

**Comment by filipelautert** [comment]
@Dasiu  Seems you are right! In my tests changing how we generate the scope id improved the performance in ~30%! 

Hi - could you give my fix a try? You can download the zip file [here](https://github.com/liquibase/liquibase/actions/runs/8193299148/artifacts/1307053597) or obtain it using GPM [(gradle](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry#using-a-published-package) 


```
implementation("org.liquibase:liquibase-core:5a353215241fed56653538be52673262abb3bca1-SNAPSHOT")
```

**Comment by Dasiu** [comment]
Great, thank you! I'll try to verify new version in coming days.

**Comment by filipelautert** [comment]
@Dasiu If there is something else that we can improve please let us know!

**Comment by Dasiu** [comment]
Ok, after a couple of weeks I can safely say that I managed to upgrade to 4.28 and it has been working fine. No concurrency issues observed. Performance is now almost on par with 3.6.3. Thank you very much.

Side remarks:
* I additionally switched off "show summary" `UpdateSummaryEnum.OFF`. I had an impression based on logs that it led to excessive amount of new Scopes being created which still created some overhead.
* The biggest optimization potential I see now (for my parallel setup) is to cache safely parsed XML changelogs. Currently parsed changelogs are not thread-safe judging by my code inspection.

**Comment by filipelautert** [comment]
Thanks for the feedback @Dasiu , that's great to hear!
Do you mind opening an issue (or even better 2 issues) for the other 2 optimization points?
