### ISSUE TITLE
Few checksums duplicated on databasechangelog, even using clear-schecksums results in duplication and validation errors on updating database

### ISSUE THREAD

**Issue by MarcioMonego** [liquibase/liquibase#5535]
### Search first

- [X] I searched and no similar issues were found

### Description

I started to receive checksum errors on same changesets even not changing them
I used clear-checksums and can uptate database, but sequentially using liquibase status the same not changed changesets fail on checksum validation
I then noted that that changesets were with the same MD5 on databasechangelog, even after clear-checksums + liquibase update over and over 

### Steps To Reproduce

I don't found a way to reproduce it, I just stucked on liquibase generating the same md5 to 4 changesets only.

### Expected/Desired Behavior

Even if changing changets, after using clear-chechsums and update the error was gone

### Liquibase Version

4.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by MarcioMonego** [comment]
Lost some info

**Comment by kevin-atx** [comment]
closing this issue, per your request
