### ISSUE TITLE
Few checksums duplicated on databasechangelog, even using clear-schecksums results in duplication and validation errors on updating database

### ISSUE THREAD

**Issue by MarcioMonego** [liquibase/liquibase#5536]
### Search first

- [X] I searched and no similar issues were found

### Description

I started to receive checksum errors on same changesets even not changing them
I used clear-checksums and can uptate database, but sequentially using liquibase status the same not changed changesets fail on checksum validation
I then noted that that changesets were with the same MD5 on databasechangelog, even after clear-checksums + liquibase update over and over

### Steps To Reproduce

I don't found a way to reproduce it, I just stucked on liquibase generating the same md5 to 4 changesets only.

### Expected/Desired Behavior

Even if changing changets, after using clear-chechsums and update the error was gone

### Liquibase Version

4.25.1

### Database Vendor & Version

MySQL 5.7

### Liquibase Integration

CLI

### OS and/or Infrastructure Type/Provider

Windows 11

### Additional Context

**From log:**
     4 changesets check sum
          changelogs/NormalizacoesIniciais.xml::000000019::marcio.monego was: 9:d41d8cd98f00b204e9800998ecf8427e but is now: 9:af7cbc3f01f74e15e79bb5f115733834
          changelogs/NormalizacoesIniciais.xml::000000020::marcio.monego was: 9:d41d8cd98f00b204e9800998ecf8427e but is now: 9:7e4c3a0b1c0ee181564bacdc4dca687f
          changelogs/NormalizacoesIniciais.xml::000000021::marcio.monego was: 9:d41d8cd98f00b204e9800998ecf8427e but is now: 9:7f0ae63086211a95fe731e8bd2252113
          changelogs/NormalizacoesIniciais.xml::000000022::marcio.monego was: 9:d41d8cd98f00b204e9800998ecf8427e but is now: 9:0f99f5012de21d835ecdf20398eaaca8

**The body of changesets:**
	<changeSet author="marcio.monego" id="000000019">
		<sql dbms="mysql">
			<![CDATA[
			insert into itensservicos
			(Id_Orçamento, Hst, Deslocamento, Qtde_deslocamento, Valor_deslocamento)
			select Id_Orçamento, Hst, InstalacaoRede, Qtde_Inst, Valor_Inst
			from itensservicos
			where Qtde_Inst > 0;]]>
		</sql>
		<comment>Migrar pontos de rede</comment>
	</changeSet>
	<changeSet author="marcio.monego" id="000000020">
		<sql dbms="mysql">
			<![CDATA[
			insert into itensservicos
			(Id_Orçamento, Hst, Deslocamento, Qtde_deslocamento, Valor_deslocamento)
			select Id_Orçamento, Hst, Plantao, Qtde_Plantao, Valor_Plantao
			from itensservicos
			where Qtde_Plantao > 0;]]>
		</sql>
		<comment>Migrar plantões</comment>
	</changeSet>
	<changeSet author="marcio.monego" id="000000021">
		<sql dbms="mysql">
			<![CDATA[
			insert into itensservicos
			(Id_Orçamento, Hst, Deslocamento, Qtde_deslocamento, Valor_deslocamento)
			select Id_Orçamento, Hst, Estadia_Alim, Qtde_Estadia, Valor_Estadia
			from itensservicos
			where Qtde_Estadia > 0;]]>
		</sql>
		<comment>Migrar estadias</comment>
	</changeSet>
	<changeSet author="marcio.monego" id="000000022">
		<comment>Migrar backups</comment>
		<sql dbms="mysql">
			<![CDATA[
			insert into itensservicos
			(Id_Orçamento, Hst, Deslocamento, Qtde_deslocamento, Valor_deslocamento)
			select Id_Orçamento, Hst, `BackUp`, Qtde_BackUp, Valor_BackUp
			from itensservicos
			where Qtde_BackUp > 0;]]>
		</sql>
	</changeSet>

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by MarcioMonego** [comment]
Reviewing these changesets I saw that they are the only I had specified the DBMS with dbms attribute, all other changesets are without dbms attribute.
Hope it can help on identifying the issue.
As it's very boring clearing over and over the checksums I added the validCheckSum tag and it stopped the checksum error for now.

**Comment by tati-qalified** [comment]
Hi @MarcioMonego, it looks like the changesets weren't copied correctly. Could you re-send them?
Thank you,
Tatiana

**Comment by MarcioMonego** [comment]
If you want the entire changesets i can pick them up, but with 4.26.0 the problem has gone!
The initial text i submitted has only the error showing that there are more than one changeset with exactly same checksum, even with sql change been different and changeset id also, as were not a duplicated changeset id validation.

**Comment by tati-qalified** [comment]
I'm glad it was resolved with 4.26! 
I'll be closing this issue, then. Feel free to reach out again if you come across this problem again.
