### ISSUE TITLE
Liquibase executing incomplete "create view" ddl and failing with "ORA-00923: FROM keyword not found where expected"

### ISSUE THREAD

**Issue by skb877** [liquibase/liquibase#5541]
### Search first

- [X] I searched and no similar issues were found

### Description

1> Generated xml using "lb genobject" for a view.
2> Trying to create the view using "lb update" and it's failing with "ORA-00923: FROM keyword not found where expected".

Further investigation showed that it's not executing the complete create view statement though the generated xml file have the complete statement.

### Steps To Reproduce

SQL> lb genobject -type view -name SWC_HR_GENERIC_EMP_V -replace
--Starting Liquibase at 15:59:41 (version 4.9.1 #0 built at 2022-05-03 17:23+2221)

Action successfully completed please review created file swc_hr_generic_emp_v_view.xml

SQL> lb update -changelog swc_hr_generic_emp_v_view.xml

Error report -
ORA-00923: FROM keyword not found where expected
00923. 00000 -  "FROM keyword not found where expected"
*Cause:
*Action:

### Expected/Desired Behavior

lb update command should have been successful and the view should have been created.

### Liquibase Version

--Starting Liquibase at 00:17:33 (version 4.9.1 #0 built at 2022-05-03 17:23+2221)   Liquibase version:    4.9.1 #0 built at 2022-05-03 17:23+2221 Extension Version:   22.2.1.0

### Database Vendor & Version

Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production Version 19.22.0.1.0

### Liquibase Integration

CLI

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment]
@skb877 - It looks like you are using Oracle's SQLcl for Liquibase. Please contact their support team for any issues/questions with this extension - https://docs.oracle.com/en/database/oracle/sql-developer-command-line/19.2/sqcug/preface.html#GUID-70DFC9AC-E321-43FF-B283-23A60A942B0F
