### ISSUE TITLE
loadUpdateData generates DELETE statements with null id

### ISSUE THREAD

**Issue by pshakhov** [liquibase/liquibase#5547]
### Search first

- [X] I searched and no similar issues were found

### Description

Case: initial fulfillment for dictionary table.

Tried 'loadData' and 'loadUpdateData'.

2nd is preferable cause it should generate DELETE statements (for rollback).

### Steps To Reproduce

1. Create table:
```databaseChangeLog:
  - changeSet:
      id: v1.0_create_item_table
      author: myself
      changes:
        - tagDatabase:
            tag: '1.0'
        - createTable:
            tableName: item
            columns:
              - column:
                  name: id
                  type: uuid
                  defaultValueComputed: gen_random_uuid()
                  constraints:
                    primaryKey: true
                    primaryKeyName: item_id_pkey
              - column:
                  name: description
                  type: text
                  constraints:
                    nullable: false
              - column:
                  name: code
                  type: varchar(50)
                  constraints:
                    nullable: false
                    unique: true
```

2. Load data: 
```databaseChangeLog:
  - changeSet:
      id: 'v1.1_init_handbooks'
      author: myself
      context: data
      changes:
        - tagDatabase:
            tag: '1.1'
        # - rollback: {}
        - loadUpdateData:
            file: 'handbooks/item_handbook.csv'
            relativeToChangelogFile: true
            tableName: channel
            columns:
              - column:
                  name: id
              - column:
                  name: code
                  header: code
              - column:
                  name: description
                  header: description
                  type: string
```
[item_handbook.csv](https://github.com/liquibase/liquibase/files/14130546/item_handbook.csv) (code, description (no id))

3. Explicitly call
```update``` and then 
```rollback``` (to previous (1.0) tag)
on Liquibase in Kotlin code; use 
```
val writer = StringWriter()
futureRollbackSQL(writer)
``` 
to check DELETE statements.

5. DELETE FROM item WHERE id is null.

### Expected/Desired Behavior

DELETE FROM item WHERE id is ${gen_random_uuid()}

How can i use this functionality in proper way?

### Liquibase Version

4.9.1

### Database Vendor & Version

PostgreSQL 15

### Liquibase Integration

gradle, spring boot (run by testcontainers in tests but not spring)

### OS and/or Infrastructure Type/Provider

macOS

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @pshakhov
The `id` column is defined with the default value `gen_random_uuid()`. When running `update`, Liquibase has no way of knowing what the generated value was. Because of this, when trying to roll back the data insertion, no `id` can be specified.

I'd recommend changing your approach, maybe [creating your own rollback statements](https://docs.liquibase.com/workflows/liquibase-community/automatic-custom-rollbacks.html).

I'll be closing this ticket, but feel free to let me know if you have any questions.
Thank you,
Tatiana
