### ISSUE TITLE
NullPointerException instead of the LockException

### ISSUE THREAD

**Issue by peter-broszeit** [liquibase/liquibase#5550]
### Search first

- [X] I searched and no similar issues were found

### Description

I would like to report a (potential) bug for
```
<!-- https://mvnrepository.com/artifact/org.liquibase/liquibase-core -->
<dependency>
    <groupId>org.liquibase</groupId>
    <artifactId>liquibase-core</artifactId>
    <version>4.25.1</version>
</dependency>

```
In the class `AbstractUpdateCommandStep `exists a line (133) which leads to a null pointer exception:
```
        } catch (Exception e) {
            DatabaseChangeLog databaseChangeLog = (DatabaseChangeLog) commandScope.getDependency(DatabaseChangeLog.class);
            addChangelogFileToMdc(getChangelogFileArg(commandScope), databaseChangeLog);
            logDeploymentOutcomeMdc(changeExecListener, false, updateReportParameters);
            **updateReportParameters.getOperationInfo().setException(e.getCause().getMessage());**
            resultsBuilder.addResult("statusCode", 1);
            throw e;
        } finally {

```

The problem ist in the Throwable class:
```
    public synchronized Throwable getCause() {
        return (cause==this ? null : cause);
    }
```

You see that the result can be null when cause and this are the same object.
In case of a LockException this is true and in my application I got the NullPointerException istead of the LockException.

In version 4.25.0 the line is missing and everything works fine.

### Steps To Reproduce

Set a lock in corresponding table like the following:
**INSERT INTO public.databasechangeloglock (id, locked, lockgranted, lockedby) VALUES (1, true, '2023-10-28 10:53:53.811', 'DESKTOP-4711 (192.168.1.1)');**

Start the application build with Liquibase 4.25.1

### Expected/Desired Behavior

Make sure that a LockException is thrown and NOT a NullPointerException.
For example like this in line 133:
`updateReportParameters.getOperationInfo().setException(e.getCause() == null ? e.getMessage() : e.getCause().getMessage());`

### Liquibase Version

4.25.1

### Database Vendor & Version

All

### Liquibase Integration

maven

### OS and/or Infrastructure Type/Provider

All

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
@peter-broszeit thanks for the detailed issue! PR https://github.com/liquibase/liquibase/pull/5606/files should fix it.
