### ISSUE TITLE
Feature Request: Add changeset execution time to database changelog table

### ISSUE THREAD

**Issue by jasonlyle88** [liquibase/liquibase#5577]
### Search first

- [X] I searched and no similar issues were found

### Description

I believe it would be beneficial to developers to be able to identify changesets that take a long time to run. To this end, I think a new column should be added to the database change log table that is execution_milliseconds.

In looking at liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java, a startTime and stopTime are already grabbed and used to display the execution time in milliseconds in the log.

So this change would be minimal in just exposing that data through the class and logging it in the database changeset tabl (and adding a column to the table to hold the information).

I am happy to do a PR, just wanted to make sure this sounded acceptable to the team before I did the actual coding!

### Steps To Reproduce

N/A, feature request

### Expected/Desired Behavior

Described above

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by MarcioMonego** [comment]
Nice ideia. +1

**Comment by MalloD12** [comment]
Hi @jasonlyle88,

Glad to see you around again. Hope you and your family are doing very well. How's the baby? 

I think this could be beneficial for us when we start addressing some performance issues we still have in our backlog. So I would be keen if we move forward with this. Just out of curiosity is there any use case you have in mind or something in some project you are working on that motivates you to have something like this?

On the other hand, I guess you might see it as well but I was wondering whether we can make use of `dateexecuted` value we are already storing in the `databachangelog` table. However, I think it would make changeset execution time calculation more complex.

**Comment by jasonlyle88** [comment]
Hey @MalloD12!

Thanks! My wife and baby girl are doing wonderful, thanks for asking! My daughter is so close to getting ready to walk... so I have a feeling life is about to get a lot more interesting 🤣

For my motives, we've notice a slow down in a project install that is run by liquibase. There are several factors we are taking into account (such as a recent hardware architecture change). But it made me want to have some hard data on times for our changesets. Allowing us to see if any individual change sets are taking more time than others, are table creations/package creations/etc all comparable times within a given object type or does something specific stand out? In the day to day... probably not a super useful metric. But, I have a feeling when it is useful, it could be very useful!

As fare as the `dateexecuted` field, It could be used. However, the first changeset to execute and the last changeset to execute would not have a good method based on the `dateexecuted` data available in the table. It would also, as you said, be slightly more difficult to do (have to go back to the previous record inserted after every execution to be able to figure out the delta). Also, calculating via the delta in `dateexecuted` across records introduces time it takes from the end of the previous changeset's execution and everything liquibase does to start the next execution.

For all of these reasons, I decided it would be a better process to record a stop and start instant based on the actual execution starting and stopping in the Java code.

And, as you pointed out, internally this gives you a better resource to access the execution time!

I've actually already fully implemented my solution in MR #5595, and overall it is pretty simple!

**Comment by MalloD12** [comment]
Glad to know everything is going well and the baby is growing up very well. Seeing she is almost walking makes me see we haven't talked for a very while. Definitely things will start being much more fun soon :D.
 
Cool, that makes sense and I agree with you. Just wanted to know what was your motivation for raising this issue and implementing the fix for it. 

Yeah, I saw the code changes and at first glance, they look well to me. We will be looking at it in more detail next sprint (which it could be next week).

Thanks,
Daniel.
