### ISSUE TITLE
Feature Request: Expose changelog/changeset execution information for use in changes

### ISSUE THREAD

**Issue by jasonlyle88** [liquibase/liquibase#5578]
### Search first

- [X] I searched and no similar issues were found

### Description

It would be useful to have execution information available to to developers so that installation logging could be done in the database as changesets execute.

I would think giving developers access to the DEPLOYMENT_ID, CHANGESET_FILE, CHANGESET_ID, and CHANGESET_AUTHOR would be very useful in this regard.

I was thinking that this information could be exposed as properties that the Liquibase program automatically sets on execution. However, I am  open to other methods of doing this and would love to hear some feedback from the team in this regard.

I imagine this being able to be used in SQL statements so that it could be used in the projects own logging mechanisms.

### Steps To Reproduce

N/A, feature request

### Expected/Desired Behavior

Described above

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by wwillard7800** [comment]
The `ChangeExecListener` interface seems like it would give you a place to do logging.

**Comment by jasonlyle88** [comment]
That does in fact look like it would do the job. However, that requires separate development in Java. What I would like to implement is a way for developers to be able to do this in the changeset changes directly (xml, yaml, json, or sql). 

This theory is similar to adding the `minDepth`, `maxDepth`, and `endsWithFilter` attributes on the [includeAll](https://docs.liquibase.com/change-types/includeall.html) element even though those types of filters could have all been accomplished with a custom Java class provided with the `filter` attribute
