### ISSUE TITLE
Link to liquibase download still points do old version, the text on page are already updated with 4.26, only the links were forgotten

### ISSUE THREAD

**Issue by MarcioMonego** [liquibase/liquibase#5582]
### Search first

- [X] I searched and no similar issues were found

### Description

I don't know if the link change was forgotten or if you need more time to change to new release, but the text on the page and other areas of docs are already changed

### Steps To Reproduce

Just access the download page
https://www.liquibase.com/download

### Expected/Desired Behavior

That the links points to new release

### Liquibase Version

4.26

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment]
Thank you for the heads up. We just moved the www.liquibase.com website to a new provider, and are working through a few issues.

In the meantime, you can access Liquibase 4.26.0 here: https://github.com/liquibase/liquibase/releases/tag/v4.26.0

**Comment by MarcioMonego** [comment]
Thank you @kevin-atx !
