### ISSUE TITLE
valueSequenceNext changes the checksum value

### ISSUE THREAD

**Issue by aburakc** [liquibase/liquibase#5594]
### Search first

- [X] I searched and no similar issues were found

### Description

In Postgresql database (I haven't tried in other databases), changesets containing valueSequenceNext generate different checksums in the first run and the second run. It gives "Validation Failed" error in second run.

Caused by: liquibase.exception.ValidationFailedException: Validation Failed:
     1 changesets check sum
          liquibase/test/changelog.xml::02::test was: 8:7cf5d7dac0749ef229d1198ef909b806 but is now: 8:2d9ff891f8c6135718a326694184e23c

### Steps To Reproduce

First create a schema named test. 

`create schema test`

Sample changesets to repreduce: 

    <changeSet id="01" author="test">
        <createTable tableName="test" schemaName="test">
            <column name="id" type="bigint"/>
            <column name="date_col" type="timestamp"/>
        </createTable>

        <createSequence sequenceName="test_seq" schemaName="test" startValue="1" />
    </changeSet>

    <changeSet id="02" author="test">
        <insert tableName="test" schemaName="test">
            <column name="id" valueSequenceNext="test_seq"/>
        </insert>
    </changeSet>

Also I created a sample Spring Boot application to demostrate the problem. Github address : https://github.com/aburakc/liquibase-checksum-problem

### Expected/Desired Behavior

There is no changeset change so Liquibase should not throw the ValidationFailedException.

### Liquibase Version

4.20.0  4.21.0 4.22.0 4.26.0 

### Database Vendor & Version

PostgreSQL 13.1

### Liquibase Integration

Spring Boot

### OS and/or Infrastructure Type/Provider

Windows 11, Ubuntu 22.04

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @aburakc, thank you for reporting this issue. I've been able to replicate it with the CLI, so it's a liquibase-core bug.

I'll be leaving this ticket open for the community to propose a fix. Our development team will be available to provide guidance to whoever submits a PR.

In the meantime, a workaround is to use the [validCheckSum](https://docs.liquibase.com/concepts/changelogs/changeset-checksums.html) tag.

Thank you,
Tatiana

**Comment by asashour** [comment]
Just a hint, when not using the `test` schema, (by removing it from the `application.properties` and `changelog.xml`), the issue isn't reproducible.

**Comment by asashour** [comment]
The reason seems to be:

- On initial db creation, the schema of `SequenceNextValueFunction` is set in [InsertDataChange.generateStatements()](https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/change/core/InsertDataChange.java#L139)
- On the second run, `generateStatements()` isn't called, and so the `SequenceNextValueFunction` doesn't have the schema, so the checksum varies.

I am not sure how best to fix this.

**Comment by hel1e** [comment]
We encountered the same issue in Oracle database. Just a note on the proposed workaround:

> In the meantime, a workaround is to use the [validCheckSum](https://docs.liquibase.com/concepts/changelogs/changeset-checksums.html) tag.

No, this is not a viable workaround. The sequence value will change each time you select nextvalue from the sequence, so the third time you would need to add another validchecksum. And in our case, the sequence value you get may differ for different customer databases.

A workaround which actually works for us, is to use a sql changeset instead, and write the insert-statement using something like this:

`insert into myschema.mytable (mycolumn) values (myschema.mytable_seq.nextval);`

**Comment by tati-qalified** [comment]
@hel1e thank you for providing other possible workarounds. 
Regarding your comment:
> The sequence value will change each time you select nextvalue from the sequence, so the third time you would need to add another validchecksum

The idea with `validchecksum` is to use the first calculated checksum, that was inserted into the `databasechangelog` table. So, when you get the error message
```
Unexpected error running Liquibase: Validation Failed:
     1 changesets check sum
          changelog.xml::02::test was: 9:firstCheckSum but is now: 9:newChecksum
```
You can add the line `<validCheckSum>9:firstCheckSum</validCheckSum>` to your changeset, and Liquibase will accept the checksum that it has already recorded.
