### ISSUE TITLE
Semicolon added to end of SQL Server stored procedure when running.

### ISSUE THREAD

**Issue by mtagliaf** [liquibase/liquibase#5603]
### Search first

- [X] I searched and no similar issues were found

### Description

this started in  

### Steps To Reproduce

The zip contains a trivial example of a single stored procedure, a changelog.json containing that file, and the powershell script to deploy the changelog to a SQL Server database
[LBSemicolonError.zip](https://github.com/liquibase/liquibase/files/14319068/LBSemicolonError.zip)

You will have to change the powershell script to include a valid username, password, database name.

### Expected/Desired Behavior

The script looks like the following, there is no semicolon defined at the end. 

```
-- liquibase formatted sql
--changeset mtagliaf:procedures.App.TestProcedure.20240129 runOnChange:true stripComments:false splitStatements:true endDelimiter:;;;;;
create or alter procedure App.TestProcedure
as
    select top 5 *
        from
            dbo.CustomerMaster
        where
            TerritoryID = 2
            and IsActive = 1
;;;;;
```
When the script is deployed, there is a semicolon added at the end of the last line in the SQL Server definition of the procedure

### Liquibase Version

4.26

### Database Vendor & Version

SQL Server 2019

### Liquibase Integration

CLI

### OS and/or Infrastructure Type/Provider

Windows 11

### Additional Context

This is a problem with our initial deployment because when we deploy our scripts to an empty database to compare with our production database, the added semicolon means that every view/procedure/function comes up as different from production.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @mtagliaf.
I have been able to replicate what you're reporting: running `liquibase update` with the code you've provided creates a procedure that's defined as follows:
```
create   procedure dbo.TestProcedure
as
    select top 5 *
        from
            dbo.CustomerMaster
        where
            TerritoryID = 2
            and IsActive = 1;
```

Changing the end delimiter from `;;;;;` to anything else, for example `aaa`, generates the same procedure, so I can confirm that this is not related to the fact that the end delimiter contains semicolons.

This doesn't seem to be a bug, but I understand why it might not be the desired behaviour in some cases. A workaround is to first run `liquibase update-sql` and manually remove the semicolon from the generated SQL script.

If you or anyone else in the community would like to propose another solution, feel free to submit a PR. Our development team will be available to provide guidance if needed.

Thank you,
Tatiana

**Comment by MalloD12** [comment]
Hi @mtagliaf,

I found this behaviour has been  introduced with #4202. Just out of curiosity the diff you are executing is it a `liquibase diff` command or are you using a different tool?  The added semicolon you can face on the diff output is it just on the mentioned types of change objects (view/procedure/function/etc)?

Thanks,
Daniel.

**Comment by mtagliaf** [comment]
We are using Redgate SQL Compare. I don’t recall the types of objects it appeared on, I’m guessing everything but tables On Apr 2, 2024, at 4:39 PM, Daniel Mallorga ***@***.***> wrote:﻿
Hi @mtagliaf,
I found this behaviour has been  introduced with #4202. Just out of curiosity the diff you are executing is it a liquibase diff command or are you using a different tool?  The added semicolon you can face on the diff output is it just on the mentioned types of change objects (view/procedure/function/etc)?
Thanks,
Daniel.
