### ISSUE TITLE
Liquibase 4.26.0 changeset execution fails for oracle DB with dbms='timesten'

### ISSUE THREAD

**Issue by sachin234s** [liquibase/liquibase#5625]
### Search first

- [X] I searched and no similar issues were found

### Description

Hi Team,

While trying to execute below changeset connecting to oracle DB, we are getting an exception

```
<changeSet author="eIUM" id="syzygy-timers-1" dbms="!timesten">
        <preConditions onFail="MARK_RAN">
            <not>
                <tableExists tableName="FSM"/>
            </not>
        </preConditions>
        <createTable tableName="FSM">
            <column autoIncrement="true" name="ID" type="BIGINT">
                <constraints primaryKey="true"/>
            </column>
            <column name="FT_EXP" type="VARCHAR(100)"/>
            <column name="ENTITY_ID" type="VARCHAR(100)"/>
            <column name="ENTITY_TYPE" type="VARCHAR(100)"/>
        </createTable>
    </changeSet>
	
	**<changeSet author="eIUM" id="syzygy-timers-1-tt" dbms="timesten">**
**        <preConditions onFail="MARK_RAN">**
**            <not>**
**                <tableExists tableName="FSM"/>**
**            </not>**
**        </preConditions>**
**        <createTable tableName="FSM">**
**            <column name="ID" type="BIGINT">**
**                <constraints primaryKey="true"/>**
**            </column>**
**            <column name="FT_EXP" type="VARCHAR(100)"/>**
**            <column name="ENTITY_ID" type="VARCHAR(100)"/>**
**            <column name="ENTITY_TYPE" type="VARCHAR(100)"/>**
**        </createTable>**
**    </changeSet>**
<changeSet author="eIUM" id="syzygy" dbms="oracle,timesten">
         <preConditions onFail="MARK_RAN">
            <not>
                <sequenceExists sequenceName="FSM_SEQ"/>
            </not>
        </preConditions>
        <createSequence
                incrementBy="1"
                sequenceName="FSM_TIMER_SEQ"
                startValue="1"/>
    </changeSet>
```
however facing below issue during execution

```
Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.ValidationFailedException: Validation Failed:
     1 changes have validation failures
          timesten is not a supported DB
 
	at liquibase.command.CommandScope.execute(CommandScope.java:237)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:222)
	at liquibase.Scope.lambda$child$0(Scope.java:184)
	at liquibase.Scope.child(Scope.java:193)
	at liquibase.Scope.child(Scope.java:183)
	at liquibase.Scope.child(Scope.java:162)
	at liquibase.Liquibase.runInScope(Liquibase.java:1371)
```

this changeset was working on earlier version of liquibase : 4.8.0.

Could you help me with resolution

### Steps To Reproduce

execution the above changeset with oracle db throws the above error with liquibase 4.26.0

### Expected/Desired Behavior

the changeset execution should not fail with 
`timesten is not a supported DB`

when the underlying db is oracle

### Liquibase Version

4.26.0

### Database Vendor & Version

oracle 18.3

### Liquibase Extensions

liquibase-core

### OS and/or Infrastructure Type/Provider

rhel-8.x

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @sachin234s, thank you for reporting this issue.
Are you running Liquibase through the CLI, with Docker or with any other extensions?

**Comment by sachin234s** [comment]
we are invoking the changeset during our java application startup. its supposed to work when the underlying db is oracle. We are not facing similar issue with mysql db

**Comment by sachin234s** [comment]
> I can confirm that this is as issue when running with Oracle, but not with other databases (PostgreSQL, MySQL).
> 
> Looking at the code, it seems to be stemming from the `validateDefinition` function at `liquibase/database/DatabaseList.java#104`.
> 
> I'll be forwarding this to the development team so they can guide you for the PR submission process. Feel free to ask any questions you may have.
> 
> Thank you, Tatiana

Thanks for the details shared. However could you also confirm if this changeset will work when the underlying database is (oracle timesten)?

**Comment by tati-qalified** [comment]
@sachin234s timesten is not currently a supported database. 
However, looking further into the issue, I found that it's not actually an Oracle problem, but an edge case of the database validation workflow.

I'll try to explain it clearly:
If the changeset has `dbms="supportedDB, nonSupportedDB"`, two things can happen:
1.  You are executing the changeset with either of those databases, supported or not. **This will generate the error.**
2. You are using a different database. This will work fine.

What's happening here is that the `dbms` attribute is a filter, so the changeset won't be run if the database used isn't specified there. 
The way Liquibase is validating this currently, it's first looking through the list of databases in the `dbms` attribute. If the current database does not match any of them, it skips the changeset altogether. 

If the current database **does** match one of them, then it will check for the validity of all specified DBs.

This means that, even if the DB you're using **is** supported, if you've specified one non-supported DB, the changeset will be marked as invalid and won't be executed.

I hope this gives you some more insight into the source of the bug.
@MalloD12 is looking into this, and he's available to guide you through the PR process.

Let us know if you have any more questions.
Thank you,
Tatiana

**Comment by MalloD12** [comment]
Hi @sachin234s,

We have been looking into this issue earlier with Tatiana some other from the team, and this is working as designed. Whenever you specify an invalid dbms execution will end up with a validation error message. With an invalid dbms I mean something that's not included in the list of maintained DBs you can find [here](https://docs.liquibase.com/start/tutorials/home.html). If you are keen to implement what we can do is to add a new configuration into the `ChangeLogParserConfiguration` and this way use that flag to control whether you want to disabled this validation or not for a case like the one you use in one of your changesets:

```
<changeSet author="eIUM" id="syzygy" dbms="oracle,timesten">
```

Thanks,
Daniel.

**Comment by sachin234s** [comment]
Thanks @MalloD12 , @tati-qalified  for detailing, 

For the moment, We are planning to proceed as below
```
<changeSet author="eIUM" id="syzygy" dbms="oracle">// replacing dbms="oracle,timesten"
         <preConditions onFail="MARK_RAN">
            <not>
                <sequenceExists sequenceName="FSM_SEQ"/>
            </not>
        </preConditions>
        <createSequence
                incrementBy="1"
                sequenceName="FSM_TIMER_SEQ"
                startValue="1"/>
    </changeSet>
```
