### ISSUE TITLE
Contribute link is broken on homepage

### ISSUE THREAD

**Issue by fatso83** [liquibase/liquibase#5627]
### Search first

- [X] I searched and no similar issues were found

### Description

I wanted to start fixing a bug, so followed the link in the README leading me to the homepage, which ultimately lead me to https://www.liquibase.org/community/contribute/code. This is unfortunately a 404, so obviously a bug.

### Steps To Reproduce

1. Go to https://www.liquibase.org/community-contributors/community-developers
2. Click the button "Contribute code"
3. Observe that you are on https://www.liquibase.org/community/contribute/code and that the text reads "Oops! You broke it :(
Error 404"

### Expected/Desired Behavior

Some page with content describing how to contribute		

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment]
Thank you for opening this ticket. The team is in the process of redirecting the links to the new website site.

In the meantime, here is the new [Liquibase Contributor website](https://contribute.liquibase.com) for instructions on participation. And, here is the link on how to [Contribute Code to Liquibase](https://contribute.liquibase.com/code/).
