### ISSUE TITLE
The maxDepth and minDepth attributes of includeall don't work as documented

### ISSUE THREAD

**Issue by stevesaliman** [liquibase/liquibase#5654]
### Search first

- [X] I searched and no similar issues were found

### Description

The documentation states that the depth parameters should indicate the distance from the included path, but the actual behavior is to calculate depth relative to the search path.  For example, if you had Liquibase code in `src/main/resources/liquibase`, and you wanted to include files in `src/main/resources/liquibase/include` to a maxDepth of 0 to exclude further subdirectories, no changes would be included because the calculated depth of the files in the included path would be 5, which is more than the specified max of 0.

I've traced the issue to ApbstractPathResourceAccessor's meetsSearchCriteria method, which is supposed to look at an included file to see if it should be processed.  There seems to be 3 issues in the code:
1.  "depth" is calculated as the file's parent's name count - the root name count.  It should be the file's parent's name count - the included path's name count.  This would cause depth to be relative to the path and not the working directory, as documented.
2. The `depth < minDepth` comparison should be `depth <= minDepth`
3. I don't see any code that compares the file's depth to the maxDepth, so I think that attribute might not work at all.

### Steps To Reproduce

I don't have a current reproduction - I see the problem in the unit tests for the Liquibase Groovy DSL as I try to get it working in newer versions of Liquibase.

### Expected/Desired Behavior

I expect the depth to be relative to the included path, as documented.  I think the documentation makes sense, and is the desired behavior, especially when you have changelogs in src/main/resources, and mix running Liquibase on the comand line (or via a build tool plugin) and having Spring Boot run it via the classpath. 

### Liquibase Version

4.21+

### Database Vendor & Version

All

### Liquibase Integration

All

### OS and/or Infrastructure Type/Provider

All

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
@MalloD12 could you take a look at this issue?

**Comment by filipelautert** [comment]
Hi @jasonlyle88 ! if I'm right you contributed this code... could you add your view about it? Steve is the maintainer of the groovy extension and is updating it to use latest liquibase version and stumbled upon this issue.

**Comment by jasonlyle88** [comment]
I'll find some time to take a look at this.

First thoughts is I know this is working to an extent... because I'm using it. However, that doesn't mean all implementations are working correctly.

Addressing the issues raised just based on memory and a cursory glance at related code:

1. I'll have to actually dig into this one.
2. This is very possible. This behavior was changed right after my wife had her baby and I didn't dig too much into it. It could be that one implementation works one way and another implementation works another.
3. The `maxDepth` does work, it is actually handled by the `walkFileTree` method that uses the `fileVisitor` that contains the code in question. For that reason, the `fileVisitor` doesn't need to handle the `maxDepth`. The `maxDepth` in this case is based off the `basePath`/`startPath`, making a plausible argument that issue 1 is truly and issue and needs to be addressed.

I'm actually using the last two weeks of my parental leave right now before my daughter turns 1 (have NO idea where the time has gone!) so I'm not sure if I'll get around to this right away.

**Comment by filipelautert** [comment]
Thanks @jasonlyle88 ! I'll be on PTO until next week but did not want to let Steve waiting anymore.

**Comment by jasonlyle88** [comment]
@stevesaliman Sorry for the wait on this one! There were definitely some depth calculation issues as you mentioned. I have a PR that fixes issues and jacks up the amount of testing here. Hopefully we will have this fixed for you before too long!

**Comment by stevesaliman** [comment]
Unfortunately PR #5883 does not appear to have fixed the bug :-(  

I use the following directories in my test:
src/test/changelog/tmp - the directory that has the changeset.
src/test/changelog/tmp/include - has some files to include
src/test/changelog/tmp/include/subdir - has some more.

In my test case, I do an "includeAll" for the "include" directory, with minDepth set to 1.  According to the documentation, "If minDepth=0, search starts from the directory in path. If minDepth=1, search starts from subdirectories of path." This means that in my example, only the files in subdir should be found.  So I should only see the file in the subdir.

But AbstractPathResourceAccessor line 116, adds one to the depth it calculates, so depth of the "include" directory becomes 1 instead of 0, which is not less than minDepth, so we process the directory instead of skipping it and only processing "include/subdir".

MaxDepth is also broken.  I see code in ResourceAccessor that looks at both minDepth and maxDepth, but AbstractPathResourceAccessor overrides the search method with something that doesn't use maxDepth at all as far as I can tell.

**Comment by MalloD12** [comment]
Hi @jasonlyle88,

Could you please take a look at Steven's comment and fix it if you have some available time?

Thanks,
Daniel.

**Comment by stevesaliman** [comment]
I think I finally figured out what is going on.  While minDepth is handled by Liquiabse, maxDepth is handled by the walkFileTree method in Java itself, which is why I didn't see it in the liquibase code.  The walkFileTree method makes maxDepth effectively 1-based.  By adding 1 at line 116, you've effectively made minDepth 1-based as well to keep things consistent.    The way I'm thinking about it is that we include **files** at the various levels, though and not **directories**.  For example, if maxDepth is 1, we only include files in the specified directory, we ignore directories.

So, if we want to leave the behavior the way it is - which makes sense for the reasons you've given, but also because the behavior is consistent with `Files.walkFileTree`, then I propose changing the documentation to something like this:

`maxDepth`: Allows you to control the maximum depth of recursion applied by includeAll, starting from the directory in **path**. If maxDepth=1, only files in **path** will be included and no subdirectories are searched. Values are inclusive. If maxDepth < minDepth, Liquibase returns an error. Default: Integer.MAX_VALUE. 

minDepth: Allows you to control the minimum depth of recursion applied by includeAll. If minDepth=1, search includes files from the directory in **path**. If minDepth=2, search excludes files from the directory in **path** and starts from subdirectories of path. Values are inclusive. Default: 1.

I know that technically the default is 0, and that a value of 0 behaves the same as 1, but for clarity, I'd document it as if it was a 1.

**Comment by MalloD12** [comment]
Hi guys,

Thank you both for your clarifications, I just created an [internal ticket](https://datical.atlassian.net/browse/PD-5073) so the docs team can make the expected updates on the docs.

Thanks,
Daniel.
