### ISSUE TITLE
High Level API

### ISSUE THREAD

**Issue by 987Nabil** [liquibase/liquibase#5663]
### Search first

- [X] I searched and no similar issues were found

### Description

The `Liquibase#update` methods are deprecated. The recommended alternative is too low level and is based on an  inconvenient and hard to read/discover API.

See discussions in #5066

### Steps To Reproduce

Use Liquibase java api

### Expected/Desired Behavior

There should be a high level API.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment]
@987Nabil - thank you for opening this ticket. I will bring this up internally to see what we can do to simplify the Java API experience.
