### ISSUE TITLE
Check for equality on ran statement breaks when changelog has "classpath:" as logicalFilePath

### ISSUE THREAD

**Issue by Alf-Melmac** [liquibase/liquibase#5681]
### Search first

- [X] I searched and no similar issues were found

### Description

The changes from #5141 changed the way changeset paths are checked for equality. Due to the newly introduced compatibility for older versions, there is an edge case that throws an InvalidPathException.

### Steps To Reproduce

Let the RanChangeSet receive a filePath that is different (even normalised) from the changelog and contains "classpath:"
See: https://github.com/Alf-Melmac/liquibase-issue-changeset-with-classpath
`java.nio.file.InvalidPathException: Illegal char <:> at index 9: classpath:/db/file.log`

### Expected/Desired Behavior

There is no exception thrown while starting the application with logical file paths containing a classpath definition

### Liquibase Version

Starting 4.25.0 up to 4.26.0

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by jgarec** [comment]
Hello !
I have another issue around the same code #5724 
So I try to see what's wrong in your issue. But I can't reproduce with your test repository

mvn liquibase:dropAll
mvn liquibase:update
```
UPDATE SUMMARY
Run:                          1
Previously run:               0
Filtered out:                 0
-------------------------------
Total change sets:            1
```
update databasechangelog set filename = 'classpath:test/changelog.xml';
```
postgres=# update databasechangelog set filename = 'classpath:test/changelog.xml';
UPDATE 1
```
mvn liquibase:update
```
UPDATE SUMMARY
Run:                          1
Previously run:               0
Filtered out:                 0
-------------------------------
Total change sets:            1


liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset classpath:changelog.xml::1::test:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "test_table" already exists [Failed SQL: (0) CREATE TABLE test_table (test_id INTEGER NOT NULL, test_column VARCHAR, CONSTRAINT test_table_pkey PRIMARY KEY (test_id))]
```

and the result in my case is that liquibase want to replay this changelog.

I miss something ?

**Comment by Alf-Melmac** [comment]
Superseded by #5727

**Comment by Alf-Melmac** [comment]
Oops, wanted to close the pr
