### ISSUE TITLE
Release timing of 4.26.1 for critical CVE

### ISSUE THREAD

**Issue by jeremycohen** [liquibase/liquibase#5693]
### Search first

- [X] I searched and no similar issues were found

### Description

When should we expect 4.26.1 to be released, both here and in Docker hub? Asking as https://github.com/pgjdbc/pgjdbc/security/advisories/GHSA-24rp-q3w6-vc56 is still a critical CVE in the Docker image.

Looks like this will be fixed in https://github.com/liquibase/liquibase/pull/5613, pending a new release.

### Steps To Reproduce

N/A

### Expected/Desired Behavior

N/A

### Liquibase Version

4.26.0

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment]
The next release is expected by the end of this week.

**Comment by jhancock93** [comment]
I assume there will be a corresponding release of the docker images as well?

**Comment by sagiru** [comment]
> I assume there will be a corresponding release of the docker images as well?
Hopefully, we are waiting for it too.
