### ISSUE TITLE
Error when installing on RedHat 8

### ISSUE THREAD

**Issue by mwalsh-etiometry** [liquibase/liquibase#5697]
### Search first

- [X] I searched and no similar issues were found

### Description

Following the instructions at https://docs.liquibase.com/start/install/liquibase-linux-redhat-centos.html to install liquibase on Redhat fails with error:

Downloading Packages:
[MIRROR] liquibase-4.26.0-1.noarch.rpm: Interrupted by header callback: Server reports Content-Length: 106766358 but expected size is: 106766368                                                                                                                          
[MIRROR] liquibase-4.26.0-1.noarch.rpm: Interrupted by header callback: Server reports Content-Length: 106766358 but expected size is: 106766368                                                                                                                          
[MIRROR] liquibase-4.26.0-1.noarch.rpm: Interrupted by header callback: Server reports Content-Length: 106766358 but expected size is: 106766368                                                                                                                          
[MIRROR] liquibase-4.26.0-1.noarch.rpm: Interrupted by header callback: Server reports Content-Length: 106766358 but expected size is: 106766368                                                                                                                          
[FAILED] liquibase-4.26.0-1.noarch.rpm: No more mirrors to try - All mirrors were already tried without success                                                                                                                                                           

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Error: Error downloading packages:
  liquibase-4.26.0-1.noarch: Cannot download, all mirrors were already tried without success

### Steps To Reproduce

Working from a RedHat 8 machine, run the commands:

- sudo rpm --import https://repo.liquibase.com/liquibase.asc
- sudo yum-config-manager --add-repo https://repo.liquibase.com/repo-liquibase-com.repo
- sudo yum install liquibase

### Expected/Desired Behavior

Expected behavior is liquibase would be installed.

Actual behavior is the following error:
Downloading Packages:
[MIRROR] liquibase-4.26.0-1.noarch.rpm: Interrupted by header callback: Server reports Content-Length: 106766358 but expected size is: 106766368                                                                                                                          
[MIRROR] liquibase-4.26.0-1.noarch.rpm: Interrupted by header callback: Server reports Content-Length: 106766358 but expected size is: 106766368                                                                                                                          
[MIRROR] liquibase-4.26.0-1.noarch.rpm: Interrupted by header callback: Server reports Content-Length: 106766358 but expected size is: 106766368                                                                                                                          
[MIRROR] liquibase-4.26.0-1.noarch.rpm: Interrupted by header callback: Server reports Content-Length: 106766358 but expected size is: 106766368                                                                                                                          
[FAILED] liquibase-4.26.0-1.noarch.rpm: No more mirrors to try - All mirrors were already tried without success                                                                                                                                                           

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Error: Error downloading packages:
  liquibase-4.26.0-1.noarch: Cannot download, all mirrors were already tried without success

### Liquibase Version

4.26.0

### Database Vendor & Version

Postgresql 14

### Liquibase Integration

CLI

### Liquibase Extensions

n/a

### OS and/or Infrastructure Type/Provider

RedHat 8.9

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
@mwalsh-etiometry we are working on that. We need to update our key that expired + some indexes, and it takes a while. We will let you know once done, and thanks for letting us know!

**Comment by jandroav** [comment]
Hey @mwalsh-etiometry It is now fixed. Could you please double-check?
![image](https://github.com/liquibase/liquibase/assets/67458478/faf05547-81d7-451f-ad4f-ca39520d7817)

**Comment by filipelautert** [comment]
Hello @mwalsh-etiometry  - I'm closing this one, feel free to reopen if the issue persists.
