### ISSUE TITLE
Unknown Column Error caused by precondition in addColumn changeSet

### ISSUE THREAD

**Issue by noahwenck** [liquibase/liquibase#5708]
### Search first

- [X] I searched and no similar issues were found

### Description

We are having issues with the following log being thrown when running our changeSets: `Error: 1054-42S22: Unknown column 't.EXAMPLE_COLUMN' in 'field list'`. This is given a `WARN` log level, but we see one of these logs for every `columnExists` preconditions in an `addColumn ` changeSet that we have, and they fill up our logs. Our preconditions do pass, so this doesn't break anything, but these logs are a nuisance. Not sure if `addColumn` preconditions have a hard time with the `<not><columnExists/></not>` or what. Some extra information is that we use mariaDB, and configure our liquibase changelogs using XML.

Looks like this exact log was added in Liquibase 3.4.1 (`[Core-2408] - Unknown column 'LABELS' in 'field list'` from `changelog.txt`).

### Steps To Reproduce

*We are using Spring Boot (projects on 2.x and 3.1.x both have this issue, with liquibase versions 4.9.x and 4.25.x both seeing this issue)

1. Start with a blank database, so that liquibase changelogs will run
2. Have a `createTable `changeSet that creates a table, say `EXAMPLE_TABLE`
3. In a later changeSet, have a `addColumn `changeSet (`EXAMPLE_COLUMN`) that adds a column to `EXAMPLE_TABLE`. Give this changeSet a precondition that checks if `EXAMPLE_COLUMN `already exists in `EXAMPLE_TABLE`, with the returned being not. Like this:

`<preConditions onFail="MARK_RAN">`
`<not><columnExists tablename="EXAMPLE_TABLE" columnname="EXAMPLE_COLUMN"/></not>`
`</preConditions>`

4. Run the changelogs by running the project, look at logs

### Expected/Desired Behavior

These logs should not be thrown when a precondition passes.

### Liquibase Version

4.9.1 and 4.25.0

### Liquibase Integration

spring boot

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by mpvvliet** [comment]
Apparently, the logging comes from this [line of code](https://github.com/mariadb-corporation/mariadb-connector-j/blob/master/src/main/java/org/mariadb/jdbc/message/server/ErrorPacket.java#L43) in the MariaDB JDBC driver.

To prevent this, my guess is you'll need to configure logging for the logger `org.mariadb.jdbc.message.server` to `ERROR` or higher.

**Comment by tati-qalified** [comment]
@noahwenck could you confirm if @mpvvliet's suggestion fixes the problem? Thanks!

**Comment by noahwenck** [comment]
The suggestion does block the logs, but that is not a solution I would like to use. This does make me worry that this might not necessarily be a liquibase issue (considering I can't find in liquibase any mention this kind of error), but the solution to these undesirable logs should not be blocking all mariaDB JDBC driver error logs. 

My hope would be to prevent these errors from being thrown in the first place

**Comment by tati-qalified** [comment]
Hi @noahwenck, I can confirm that Liquibase doesn't have any say in the logs that come from external JDBC drivers. You will probably get those logs even with `log-level=FINE`. 
I would suggest you consult with the MariaDB team, and they might be able to help you solve this.

Thank you,
Tatiana
