### ISSUE TITLE
Duplicated dependency `commons-text` - liquibase-core

### ISSUE THREAD

**Issue by marwin1991** [liquibase/liquibase#5826]
### Search first

- [X] I searched and no similar issues were found

### Description

Hello, I think `commons-text` dependecy is duplicated, its included in liquibase core and in `com.opencsv:opencsv` 

Good thing that its the same version, but in the future it can cause Jar hell.  

### Steps To Reproduce

`mvn dependency:tree`

### Expected/Desired Behavior

no duplicated deps

### Liquibase Version

4.27.0

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by MalloD12** [comment]
Hi @marwin1991,

If you see it duplicated yes I agree we should get rid off one of them. I can see `org.apache.commons:commons-text` is included by `com.opencsv`:
<img width="698" alt="Screenshot 2024-05-07 at 12 21 27 AM" src="https://github.com/liquibase/liquibase/assets/75833793/587663a4-5f2f-477f-8a42-08a9fd031044">

I don't see commons-text as a sole dependency of core. If you don't mind could you please share where are you seeing both duplicates?

Thanks,
Daniel.

**Comment by marwin1991** [comment]
@MalloD12 
sorry for westing your time, I don't know why i thouth it is

i've tested it with:
```
mvn
      --batch-mode
      validate
      org.apache.maven.plugins:maven-enforcer-plugin:3.4.1:enforce
      -Denforcer.rules=banDuplicatePomDependencyVersions,dependencyConvergence
```

and it looks okay.

output of mvn dependecy:tree for me looks a bit diffrent:

![image](https://github.com/liquibase/liquibase/assets/25181517/efec481b-5b45-4a08-a2f1-7b1160af00ec)

And it looks like here core contains commons-text and opencsv

**Comment by MalloD12** [comment]
Hi @marwin1991,

I can see now what you mean. I've been talking with one other member of the team and he pointed me out to the generated [pom file](https://repo1.maven.org/maven2/org/liquibase/liquibase-core/4.27.0/liquibase-core-4.27.0.pom) and I can see what you were pointing out there. 

Maybe we should add `common-text` as a core dependency to avoid this being included as an inherited dependency, same with `commons-collections4`. Do you have any other proposal to fix this?

Thanks,
Daniel.

**Comment by marwin1991** [comment]
@MalloD12 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.4.1:enforce (default-cli) on project hermesms: 
[ERROR] Rule 1: org.apache.maven.enforcer.rules.dependency.DependencyConvergence failed with message:
[ERROR] Failed while enforcing releasability.
[ERROR] 
[ERROR] Dependency convergence error for org.apache.commons:commons-text:jar:1.11.0 paths to dependency are:
[ERROR] +-pl.com.aaaaa:vvvvvv:jar:1.0.3-SNAPSHOT
[ERROR]   +-org.liquibase:liquibase-core:jar:4.27.0:compile
[ERROR]     +-com.opencsv:opencsv:jar:5.9:compile
[ERROR]       +-org.apache.commons:commons-text:jar:1.11.0:compile
[ERROR] and
[ERROR] +-pl.com.aaaaa:vvvvvv:jar:1.0.3-SNAPSHOT
[ERROR]   +-org.liquibase:liquibase-core:jar:4.27.0:compile
[ERROR]     +-org.apache.commons:commons-text:jar:1.11.0:compile
[ERROR] and
[ERROR] +-pl.com.aaaaa:vvvvvv:jar:1.0.3-SNAPSHOT
[ERROR]   +-org.apache.commons:commons-text:jar:1.12.0:compile
[ERROR] -> [Help 1]
````

**Comment by filipelautert** [comment]
Hi @marwin1991 - this will be fixed in https://github.com/liquibase/liquibase/pull/6021 . Thanks for the report!

**Comment by filipelautert** [comment]
> com.opencsv:opencsv:jar:5.9:compile

@marwin1991 are you using csv files? If not you can exclude this dependency to get it fixed.

**Comment by marwin1991** [comment]
@filipelautert thank you and happy new year!

Shouldn't you exclude `commons-text` when you import `opencsv` ?

**Comment by marwin1991** [comment]
When I exclude i got error:

```
Caused by: java.lang.NoClassDefFoundError: com/opencsv/exceptions/CsvMalformedLineException
```

But application starterd

**Comment by marwin1991** [comment]
```
[ERROR] Dependency convergence error for org.apache.commons:commons-text:jar:1.11.0 paths to dependency are:
[ERROR] +-aaa.aaa.aaa:aaaa:jar:1.1.1
[ERROR]   +-org.liquibase:liquibase-core:jar:4.29.2:compile
[ERROR]     +-com.opencsv:opencsv:jar:5.9:compile
[ERROR]       +-org.apache.commons:commons-text:jar:1.11.0:compile
[ERROR] and
[ERROR] +-aaa.aaa.aaa:aaaa:jar:1.1.1
[ERROR]   +-org.liquibase:liquibase-core:jar:4.29.2:compile
[ERROR]     +-org.apache.commons:commons-text:jar:1.12.0:compile
```
