### ISSUE TITLE
Update Teradata Driver Version in Docs

### ISSUE THREAD

**Issue by mpstadler** [liquibase/liquibase#5858]
### Search first

- [X] I searched and no similar issues were found

### Description

In your Docs about [Teradata](https://contribute.liquibase.com/extensions-integrations/directory/database-tutorials/teradata/) you mention that it only supports Databases of version 17.20 and 17.10.
And you have an example that references the old Teradata JDBC Driver:
```xml
<dependency>
    <groupId>com.teradata.jdbc</groupId>
    <artifactId>terajdbc4</artifactId>
    <version>17.10.00.27</version>
</dependency>
```
However lately the teradata drivers are also available on maven central, as noted on the [driver page](https://downloads.teradata.com/download/connectivity/jdbc-driver), and there are also much newer versions of the driver that are also compatible with the supported database versions:
```xml
<dependency>
    <groupId>com.teradata.jdbc</groupId>
    <artifactId>terajdbc</artifactId>
    <version>20.00.00.19</version>
</dependency>
```
Using the newer Driver seems to work fine (so far).
So maybe it you could update the documentation to mention that also the newer drivers are supported and drop the sentence that says that there is no such driver in maven central:
> If you use Maven, note that this database does not provide its driver JAR on a public Maven repository, so you must install a local copy and [add it as a dependency](https://docs.liquibase.com/tools-integrations/maven/using-liquibase-and-maven-pom-file.html) to your pom.xml file.
Also if you have a decent test setup it would be nice to include tests against the new driver version if such tests exist.

### Steps To Reproduce

1. Open the [Teradata Docs](https://contribute.liquibase.com/extensions-integrations/directory/database-tutorials/teradata/) and read it.
2. Convert an existing Teradata Project to use the new Driver and verify that still everything works as expected:
```xml
<dependency>
    <groupId>com.teradata.jdbc</groupId>
    <artifactId>terajdbc</artifactId>
    <version>20.00.00.19</version>
</dependency>
```

### Expected/Desired Behavior

1. The Documentation is up to date.
2. No problems when running liquibase-teradata with the newer driver from maven central.

### Liquibase Version

4.27.0

### Database Vendor & Version

Teradata 17.20.03.20

### Liquibase Integration

maven

### Liquibase Extensions

liquibase-teradata

### OS and/or Infrastructure Type/Provider

MacOS

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by adrian-velonis1** [comment]
Thanks @mpstadler for opening this issue.

INTERNAL DOCS TICKET: https://datical.atlassian.net/browse/PD-4526

**Comment by filipelautert** [comment]
@mpstadler thanks for the report, docs have been updated: https://contribute.liquibase.com/extensions-integrations/directory/database-tutorials/teradata/
