### ISSUE TITLE
UniqueConstaintExistsPrecondition ignores liquibaseSchema property

### ISSUE THREAD

**Issue by bostandyksoft** [liquibase/liquibase#5907]
### Search first

- [X] I searched and no similar issues were found

### Description

Our Postgres instance database several schemas with same structure, so there are many objects with same name in different schemas. 
I found, that when UniquieConstraintExistsPrecondition performs search constraint, it dont use liquibaseSchema property to strict query to found objects only in working schema. 
I'm not sure about other preconditions, but it looks like that DatabaseSnapshot dont use this property at all

PS I've researched TableExistsPrecondition. DatabaseSnapshot also dont use this propery. But somewhere SnapshotGenerator adds restriction on 
```
FROM pg_catalog.pg_namespace n
...
WHERE ... n.nspname LIKE '<my_scheme>'
```

### Steps To Reproduce

Initialize Postgres database with 2 schemas. 
One schema contains uniqueconstraint, another does not contain.
Roll changeset with UniqueConstaintExistsPrecondition

### Expected/Desired Behavior

UniqueConstaintExistsPrecondition ignores uniqueconstraint from another schema

### Liquibase Version

4.27.0

### Database Vendor & Version

Postgres 12.5

### Liquibase Integration

spring boot

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR (Thank you!)

**Comment by bostandyksoft** [comment]
I'm not sure - send me please a link to manual for PR. I've found that there is need to add following code to UniqueConstraintSnapshotGenerator

`CatalogAndSchema catalogAndSchema = new CatalogAndSchema(schema.getCatalogName(), schema.getSchema().getName()).customize(database)`

to line 146 and use this object to build query below

**Comment by kevin-atx** [comment]
Here are the instructions for submitting a PR - https://contribute.liquibase.com/code/get-started/create-pr/.

Let us know if you have any other questions. Thanks for the PR!

**Comment by mpvvliet** [comment]
I've recently contributed a fix in https://github.com/liquibase/liquibase/pull/5783 which looks like it might fix this issue in another way.

**Comment by bostandyksoft** [comment]
> I've recently contributed a fix in #5783 which looks like it might fix this issue in another way.

Hi. Yes you are right, it looks like this PR should help.

**Comment by kevin-atx** [comment]
@bostandyksoft—@mpvvliet's fix has been merged and is expected to be included in the next release (which is planned to be released within the next several days). Please test to see if the fix addresses your issue and let us know.

**Comment by kevin-atx** [comment]
@bostandyksoft and @mpvvliet - have either of you had a chance to test Liquibase 4.28.0 to see if it addresses the issues you were having?

**Comment by bostandyksoft** [comment]
> @bostandyksoft and @mpvvliet - have either of you had a chance to test Liquibase 4.28.0 to see if it addresses the issues you were having?

I've checked it now - it is working now correctly. I saw all of my lost unique constraints

**Comment by kevin-atx** [comment]
That's great news. I'll close this ticket as fixed. Thanks!
