### ISSUE TITLE
diffChangeLog on 4.28.0 doesn´t add changesets comparing to 4.27.0

### ISSUE THREAD

**Issue by rafaeljpc** [liquibase/liquibase#5943]
### Search first

- [X] I searched and no similar issues were found

### Description

I upgraded the version of the liquibase-core library to 4.28.0 and the diffChangeLog stopped to recognize the changesets.
The diff command show the difference correctly but the diffChangeLog doesn't. When I rollback the versio to 4.27.0 it worked fine.

### Steps To Reproduce

Using gradle liquibase plugin

`
liquibase {
    activities.register("diffLog") {
        this.arguments = mapOf(
            "changelogFile" to "${layout.buildDirectory.get()}/tmp/diff-changelog.xml",
            "classpath" to sourceSets.main.get().output.resourcesDir?.absolutePath,
            "url" to "jdbc:${props["DATABASE_URL"]}",
            "username" to props["DATABASE_USER"],
            "password" to props["DATABASE_PASSWORD"],
            "referenceUrl" to "hibernate:spring:myproject.entity?" +
                    "dialect=org.hibernate.dialect.PostgreSQLDialect&" +
                    "hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy&" +
                    "hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy",
            "defaultSchemaName" to "myproject",
            "logLevel" to "debug",
        )
    }
}

tasks.named<LiquibaseTask>("diffChangelog") {
    doFirst {
        liquibase.setProperty("runList", "diffLog")
    }
}
`

then run
> gradle diffChangeLog

### Expected/Desired Behavior

I expected that at <project>/build/tmp was a file diff-changelog.xml with the changesets generated by de difference at hibernate and the source database

### Liquibase Version

4.28.0

### Database Vendor & Version

Postgres 16

### Liquibase Integration

gradle

### OS and/or Infrastructure Type/Provider

Any

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Pyenb** [comment]
Is there any update on this? I am currently facing the same problem, using Liquibase 4.28 with Maven. Downgrading to 4.27.0 instantly made the generation work again.

**Comment by KleinerHacker** [comment]
We see the same problem in our project. A downgrade to Version 4.27.0 fix it.

**Comment by gigi** [comment]
Hi!
I have the same issue after the update. Here is the setup that works properly with version 4.27.0.
https://github.com/gigi/gigi-spring-rest-skeleton/blob/main/build.gradle#L10-L12

**Comment by jasperjanuar** [comment]
We're experiencing the same issue with 4.28

**Comment by filipelautert** [comment]
Hi`! The diff command show the difference correctly but the diffChangeLog doesn't.`  Does any of you face a warning message like `Diff changelog command failed`.... ?  The one from this PR -> https://github.com/liquibase/liquibase/pull/5828/files ? Ie:

**Comment by filipelautert** [comment]
This has been fixed by https://github.com/liquibase/liquibase-hibernate/pull/717, and wil be released with Liquibase 4.30.0 later this month.
