### ISSUE TITLE
defaultValueComputed inside addColumn producing bad SQL with PostgreSQL 16.2

### ISSUE THREAD

**Issue by micopiira** [liquibase/liquibase#6016]
### Search first

- [X] I searched and no similar issues were found

### Description

When using defaultValueComputed inside addColumn I get bad SQL

If I place a column with the defaultValueComputed inside a createTable change it works correctly, so it seems that defaultValueComputed is not handled correctly when used inside addColumn, atleast with PostgreSQL 16.2.

The error I get:

```
 Migration failed for changeset db/changelog/2024/06/17-02-changelog.xml::1718630821674::Spring Data Relational:
     Reason: liquibase.exception.DatabaseException: ERROR: syntax error at or near "ALWAYS"
  Position: 56 [Failed SQL: (0) ALTER TABLE public.test ADD foo TEXT DEFAULT GENERATED ALWAYS AS (value->>'foo') STORED]
```

### Steps To Reproduce

When using following changelog:

```XML
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
				   xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
				   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">
	<changeSet author="Spring Data Relational"
			   id="1718630821674"
			   objectQuotingStrategy="LEGACY">
		<createTable tableName="test">
			<column name="id" type="text">
				<constraints primaryKey="true"/>
			</column>
                         <column name="value" type="jsonb"/>
		</createTable>
		<addColumn schemaName="public" tableName="test">
			<column defaultValueComputed="GENERATED ALWAYS AS (value-&gt;&gt;'foo') STORED"
					name="foo"
					type="TEXT"/>
		</addColumn>
	</changeSet>
</databaseChangeLog>
```

I tried liquibase 4.25.1, 4.27.0 and 4.28.0.

### Expected/Desired Behavior

Looking at the source code for `AddColumnGenerator` it seems there is already a check for OracleDatabase that skips the "DEFAULT" keyword as follows:

`if ((database instanceof OracleDatabase) && defaultValue.toString().startsWith("GENERATED ALWAYS ")) {`

Maybe the same check should be added for Postgres?

### Liquibase Version

4.28.0

### Database Vendor & Version

PostgreSQL 16.2

### Liquibase Integration

spring boot

### OS and/or Infrastructure Type/Provider

Mac

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @micopiira, thank you for reporting this issue.

I can confirm that this bug is still happening with Liquibase version 4.28.0 and that it can probably be fixed with what you're suggesting. Would you be willing to submit a PR?

Thank you,
Tatiana

**Comment by micopiira** [comment]
@tati-qalified I opened PR #6083

**Comment by clayly** [comment]
Hi everyone. Is it really fixed? Updated to liquibase-core:4.29.2, code from PR is here, but still same error.

**Comment by tati-qalified** [comment]
Hi @clayly, I've re-tested this with 4.29.2, and it is working for me. Could you provide more information about what you're running that causes the error to appear? 
Thank you,
Tatiana

**Comment by micopiira** [comment]
I can confirm this issue was fixed for me. Must be something different for @clayly 🤔

**Comment by clayly** [comment]
@tati-qalified @micopiira Seems like issue is that Liquibase code sensitive to whitespaces. So this formatting doesn't work:

```
<column
        name="foo"
        type="BIGINT"
        defaultValueComputed="
        GENERATED ALWAYS AS
        (
           10 - 5
        )
        STORED
        "
/>
```

And leads to addition of incorrect DEFAULT word to SQL.

While this works fine:

```
<column
        name="foo"
        type="BIGINT"
        defaultValueComputed="GENERATED ALWAYS AS
        (
           10 - 5
        )
        STORED
        "
/>
```

**Comment by filipelautert** [comment]
So I believe that just adding a `trim()` [here ](https://github.com/liquibase/liquibase/pull/6083/files#diff-ca15a15a336be0f23a87413dd71b0458f2ec3830eeb8e8e01e80bc4e8c013589R284) before `startsWith` would fix it.
