### ISSUE TITLE
OSGi dependency on Apache Commons IO is declared incorrectly

### ISSUE THREAD

**Issue by malachyb** [liquibase/liquibase#6020]
### Search first

- [X] I searched and no similar issues were found

### Description

According to Maven, Liquibase 4.28.0 has a dependency on commons-io:2.16.1, but in the manifest file we can see `Import-Package: org.apache.commons.io;resolution:=optional;version="[1.4,2)`. This causes issues when running an application using OSGi, as it is declared as optional. Additionally, it is the incorrect version of commons-io.

Because of this, when running this on an OSGi application it causes this error to occur.
```
java.lang.NoClassDefFoundError: org/apache/commons/io/FilenameUtils
	at liquibase.changelog.DatabaseChangeLog.normalizePath(DatabaseChangeLog.java:1090)
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:20)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:281)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:266)
```

### Steps To Reproduce

Run the Liquibase library using OSGi and attempt any operation that uses a class from commons-io like `DatabaseChangeLog.normalizePath()`

### Expected/Desired Behavior

Liquibase manifest declares hard dependency on the correct version of commons-io.

### Liquibase Version

4.28.0

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by a1flecke** [comment]
We are impacted by this as well
