### ISSUE TITLE
CustomTaskRollback rollback method runs twice

### ISSUE THREAD

**Issue by ThePersonThat** [liquibase/liquibase#6061]
### Search first

- [X] I searched and no similar issues were found

### Description

I have exactly the same issue as described here: https://github.com/liquibase/liquibase/issues/5314, but with rollback. 
As far as I investigated the fix has not been added for rollback logic: https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/change/custom/CustomChangeWrapper.java#L197. Rollback logic is ran twice (while executing "addSqlMdc" and "executeStatements" methods)

### Steps To Reproduce

Create any CustomTaskRollback implementation. It will execute twice.

### Expected/Desired Behavior

Rollback logic must be executed only once

### Liquibase Version

4.26.0

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @ThePersonThat, thank you for reporting this issue.
I found that it had been reported before: #5422. Would you be willing to submit a PR to fix the bug? Our development team is available to provide guidance if necessary.

Thank you!
Tatiana

**Comment by momosetkn** [comment]
this problem was solved by [4.30.0](https://github.com/liquibase/liquibase/releases/tag/v4.30.0)
