### ISSUE TITLE
ReadDataType for Mysql datetime

### ISSUE THREAD

**Issue by diqksrk** [liquibase/liquibase#6069]
### Search first

- [X] I searched and no similar issues were found

### Description

`CommandScope commandScope = new CommandScope("diffChangeLog");`

When executing this code to create a changeset.xml file by comparing two database tables and applying the file, the following error occurs:
```
Caused by: liquibase.exception.DatabaseException: Invalid default value for 'reg_ymdt' [Failed SQL: (1067) CREATE TABLE create_ssht (reg_ymdt datetime DEFAULT CURRENT_TIMESTAMP(3) on update CURRENT_TIMESTAMP(3) NULL)]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:476)
```

Upon checking, it seems that the issue arises because the actual MySQL type is `datetime(3)`, but the changeset.xml is created as follows. `type="datetime`
```
<createTable tableName="create_ssht">
    <column defaultValueComputed="CURRENT_TIMESTAMP(3) on update CURRENT_TIMESTAMP(3)" name="reg_ymdt" type="datetime"/>
</createTable>
```

#### Step 1:
Create the schema with mysql database
```
CREATE TABLE `create_ssht` (
   `reg_ymdt` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

#### Step 2:
`CommandScope commandScope = new CommandScope("snapshot");`
Generate changeset.xml file with the given command.

#### Step 3:
`CommandScope updateScope = new CommandScope("update");`
Apply the changeset.xml file to the MySQL database using the following command.

### Expected/Desired Behavior

It should be type="datetime(3)" instead of type="datetime".

### Liquibase Version

4.28.0

### Database Vendor & Version

Mysql & 8.0.35

### Liquibase Integration

gradle, spring boot

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by lbadam** [comment]
@tati-qalified could you please prioritize reproducing this issue by Friday? There is a corresponding PR that we would like to try and get in the next sprint.

**Comment by tati-qalified** [comment]
@lbadam this is replicable with Liquibase version 4.28.0 when generating a changelog with any format, including .sql.
