### ISSUE TITLE
Calling liquibase CLI programmatically from different threads is broken by ThreadLocal changes in Scope

### ISSUE THREAD

**Issue by ashleymercer** [liquibase/liquibase#6076]
### Search first

- [X] I searched and no similar issues were found

### Description

Since 4.27.0+ we've been seeing several errors like:

```
2024-07-05 14:10:55.416 ERROR l.i.c.LiquibaseCommandLine - Unknown option: '--show-summary=OFF'
picocli.CommandLine$UnmatchedArgumentException: Unknown option: '--show-summary=OFF'
	at picocli.CommandLine$Interpreter.validateConstraints(CommandLine.java:13662)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13614)
	at picocli.CommandLine$Interpreter.processSubcommand(CommandLine.java:13904)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:13800)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13591)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13559)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13454)
	at picocli.CommandLine.parseArgs(CommandLine.java:1552)
	at liquibase.integration.commandline.LiquibaseCommandLine.registerValueProviders(LiquibaseCommandLine.java:605)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:361)
```

I think I've managed to track the problem down to pull #5617 and specifically this change:

```java
// Old code
private static ScopeManager scopeManager;

// New code
private static final ThreadLocal<ScopeManager> scopeManager = new ThreadLocal<>();
```

For non-singleton instances I suspect this isn't an issue (else surely there would have been other regressions or bug reports by now!) but it does significantly change the behaviour of `Scope.getSingleton`: previously this would return a *global* singleton instance (assuming we were using the default setup) where now it only returns a *thread-local* singleton - so it's possible for two different threads to see two different "singleton" instances. This in turn breaks any code which both:

1. relies on `Scope.getSingleton`, AND
2. might call liquibase from different threads

The specific bug above manifests because some static initialisers rely on `Scope.getSingleton`: for example the static initialiser for `ShowSummaryArgument` ultimately calls `CommandArgumentDefinition.build()` which contains this line:

```java
Scope.getCurrentScope().getSingleton(CommandFactory.class).register(commandName, newCommandArgument);
```

Previously this would effectively register the `showSummary` option(s) globally for the whole JVM; but now the registration only happens for the `CommandFactory` singleton *tied to this thread*. And because static initialisers are only run once by the JVM (assuming no classloader shenanigans) that means that any other thread that comes along will get a different instance of `CommandFactory` which does not have these options registered - hence complaining about "Unknown option".

### Steps To Reproduce

1. call `new LiquibaseCommandLine().execute("liquibase update --show-summary=OFF")` from thread A
2. wait for completion
3. call `new LiquibaseCommandLine().execute("liquibase update --show-summary=OFF")` from thread B

### Expected/Desired Behavior

It should be possible to call into liquibase CLI multiple times inside the JVM from different threads, and have it not crash.

### Liquibase Version

4.27

### Database Vendor & Version

H2

### Liquibase Integration

CLI

### Additional Context

We run liquibase inside the Play web framework which provides a development mode with hot reload: this is extremely useful since it allows developers to edit changelogs while the webserver is running, have it reload, and any liquibase changes will automatically be applied with `liquibase update`. In order to support this it might end up running its hotswap code (including, in our case, liquibase) from different threads at different times.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
Hello @ashleymercer ! Thanks for the detailed ticket. Based on your findings I created PR  https://github.com/liquibase/liquibase/pull/6222 . 
The added test was failing , but after that static was added to CommandFactory class it started to pass. And in fact it's a caching issue: we are re-reading static allocated parameters to an instance object. By changing it to static we use the caching and nothing is missed.

It the test now behaving as expected?

**Comment by ashleymercer** [comment]
Hi @filipelautert - thanks for picking this one up! I'll wait for the next release and then test it again on my end

**Comment by reflection-agent** [comment]
Assignment acknowledged. I'm starting work on this issue.
If you'd like, you can track progress at the [Reflection Agent dashboard](https://agent-dashboard-dev.reflectionai.dev/session/ee62e584-388b-4aaf-963c-2369b784dad9).

**Comment by reflection-agent** [comment]
API reports session failed: {'id': 'ee62e584-388b-4aaf-963c-2369b784dad9', 'status': 'STATUS_FAILED', 'error': {'code': 'ERROR_INTERNAL', 'message': 'failed to execute repository clone script: failed to execute script: command execution failed: command terminated with exit code 1 (status: -1, output: )'}} Re-assign to me if you'd like me to try again.
