### ISSUE TITLE
Changeset hash is calculated using comments following the command.

### ISSUE THREAD

**Issue by timendez** [liquibase/liquibase#6104]
### Search first

- [X] I searched and no similar issues were found

### Description

I get the following error:
```
Caused by: liquibase.exception.ValidationFailedException: Validation Failed:
     1 change sets check sum
          db-changelogs/inventory.sql::1::tim was: 8:d44e2311b2da45086f580f028fb3378f but is now: 8:cc69d03bb1c01a76df70d58f59d30b32
```
when attempting to write a comment after a statement/before another statement in my changelog SQL.

### Steps To Reproduce

Run this changelog:
```sql
--changeset tim:1
CREATE TABLE `inventory` (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `bytes` BLOB,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB
```

then update the changelog to be:
```sql
--changeset tim:1
CREATE TABLE `inventory` (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `bytes` BLOB,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB

-- Nifty comment explaining this changeset
--changeset tim:2
ALTER TABLE `inventory` MODIFY COLUMN `bytes` MEDIUMBLOB;
```

Outcome:
```
liquibase.exception.ValidationFailedException: Validation Failed:
     1 change sets check sum
          db-changelogs/inventory.sql::1::tim was: 8:d44e2311b2da45086f580f028fb3378f but is now: 8:cc69d03bb1c01a76df70d58f59d30b32
```

### Expected/Desired Behavior

I expect comments to not influence the hash of the changeset

### Liquibase Version

v4.28.0

### Database Vendor & Version

MySQL 8

### OS and/or Infrastructure Type/Provider

Windows, AL2023 Linux both reproduce issue

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lbadam** [comment]
@timendez thanks for filing this issue. I see two things going on:

1. In your example you changed `BLOB` to `blob` which will definitely affect the checksum. You can try re-running with those same values.

2. Even when you re-run, Liquibase does include comments in the checksum calculation, so I believe this is working as expected from the product side.

**Comment by timendez** [comment]
1. Sorry, didn't directly copy-paste due to removing sensitive information. I've updated the comment.
2. Perhaps it would make sense to ignore comments in the checksum since the behavior is the same?

**Comment by lbadam** [comment]
@timendez we're not planning to update the checksum behavior to ignore comments. If more requests come in for that behavior, we will definitely consider it.

In light of that, I'm going to close this issue. If there is something broken or not working as described in our documentation, please reopen.

**Comment by timendez** [comment]
Ok, thank you!
