### ISSUE TITLE
[bug] Duplicate homebrew PRs

### ISSUE THREAD

**Issue by chenrui333** [liquibase/liquibase#6135]
### Search first

- [X] I searched and no similar issues were found

### Description

Duplicate homebrew PRs

- https://github.com/Homebrew/homebrew-core/pull/178440
- https://github.com/Homebrew/homebrew-core/pull/178447
- https://github.com/Homebrew/homebrew-core/pull/178460
- https://github.com/Homebrew/homebrew-core/pull/178462
- https://github.com/Homebrew/homebrew-core/pull/178463

**Comment by chenrui333** [comment]
I actually cannot find the ref for this

```
Created by https://github.com/mislav/bump-homebrew-formula-action
```

**Comment by p-linnane** [comment]
I've had to ban @liquibot from interacting with Homebrew on GitHub until this is resolved, as we're getting more PR's still.

**Comment by sayaliM0412** [comment]
@p-linnane : we had some issues with our `4.29.0` Liquibase Release and therefore there were multiple PR's created by automation.

**Comment by p-linnane** [comment]
Has the issue been resolved?

**Comment by chenrui333** [comment]
I dont think so, https://github.com/liquibase/liquibase/actions/workflows/release-published.yml

**Comment by chenrui333** [comment]
it would be good to test out the release jobs separately and then put them together before spamming the downstream.

**Comment by sayaliM0412** [comment]
@chenrui333 @p-linnane : manually created a PR here: https://github.com/Homebrew/homebrew-core/pull/178571
We have resolved the issues and would like to request to unblock the @liquibot user for future PR's.

**Comment by jnewton03** [comment]
@sayaliM0412 once your manual PR has been merged and the liquibot user has been unbanned please close this issue.

@chenrui333 @p-linnane here is the change we are proposing on our side to avoid the duplicate PRs in the future:
https://github.com/liquibase/build-logic/pull/232

**Comment by p-linnane** [comment]
I've unbanned @liquibot. @chenrui333 left a comment on the manual PR that needs to be addressed before we merge. Then this can be closed out.

**Comment by sayaliM0412** [comment]
> I've unbanned @liquibot. @chenrui333 left a comment on the manual PR that needs to be addressed before we merge. Then this can be closed out.

changes addressed : https://github.com/Homebrew/homebrew-core/pull/178571/files

**Comment by sayaliM0412** [comment]
Bug addressed with this PR : https://github.com/Homebrew/homebrew-core/pull/178571. Closing this issue
