### ISSUE TITLE
Oracle primary key size based on version

### ISSUE THREAD

**Issue by m4tt30c91** [liquibase/liquibase#6142]
### Search first

- [X] I searched and no similar issues were found

### Description

The `OracleDatabase::generatePrimaryKeyName` method is always truncating the auto generated primary key name to 30 characters.
It should instead make use of the `OracleDatabase::getIdentifierMaximumLength` method to get the right lenght for the identifier, something like this:

```
@Override
public String generatePrimaryKeyName(String tableName) {
	int maximumLength = getIdentifierMaximumLength();
	String primaryKeyName = "PK_" + tableName.toUpperCase(Locale.US);
	if (primaryKeyName.length() > maximumLength) {
		return primaryKeyName.substring(0, maximumLength);
	} else {
		return primaryKeyName;
	}
}
```

Would it be ok if I raise a PR to address this?

### Steps To Reproduce

To reproduce this, you can run liquibase against an Oracle version grater than 12, with a long enough `databaseChangeLogLockTableName`, something longer than 30 characters.
The primary key name will be truncated to 30 characters.

### Expected/Desired Behavior

Having Oracle version grater than 12 and a long enough `databaseChangeLogLockTableName`, the primary key name should be truncated to 128 characters.

### Database Vendor & Version

Oracle version grater than 12

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by m4tt30c91** [comment]
Hi @tati-qalified 

Thank you for the feedback, actually this is kind of strange.
Anyway I can replicate the scenario using liquibase 4.25.1

Thanks,
Matteo.

**Comment by wwillard7800** [comment]
Would you be able to share your changelog file, or at least a snippet of it?  Thanks.

**Comment by m4tt30c91** [comment]
Actually it is not a matter of changelog; this happens whenever I run liquibase update with a custom, long enough `databaseChangeLogLockTableName` (let's say something like `SOME_TABLE_WITH_NAME_LONGER_THAN_30_CHARACTERS`).
In this scenario, instead of generating the table with a PK constraint with name `PK_SOME_TABLE_WITH_NAME_LONGER_THAN_30_CHARACTERS`, liquibase generate the table with the given name, while the constraint name will be `PK_SOME_TABLE_WITH_NAME_LONGER`.

**Comment by tati-qalified** [comment]
My bad, I hadn't read the part about the auto-generated PK names. I was testing with manually created names.

I can confirm that all auto-generated PK names are truncated at 30 characters, both for 4.25.1 and for 4.29.0
