### ISSUE TITLE
Discrepancy in docs

### ISSUE THREAD

**Issue by freakynit** [liquibase/liquibase#6161]
### Search first

- [X] I searched and no similar issues were found

### Description

In blog post: https://www.liquibase.com/blog/using-liquibase-in-kubernetes, the created config-map name should be `liquibase-changelog`, not `changelog-volume`

### Steps To Reproduce

Just read the blog

### Expected/Desired Behavior

The blog post should be correct

### Liquibase Version

any

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lbadam** [comment]
@freakynit thanks for letting us know. We will get the blog post updated!
