### ISSUE TITLE
`calculate-checksum` result is written to the stderr instead of stdout

### ISSUE THREAD

**Issue by Ishad-M-I-M** [liquibase/liquibase#6191]
### Search first

- [X] I searched and no similar issues were found

### Description

The calculated checksum value from the `liquibase calculate-checksum` is written to the stderr instead of stdout. This also cause empty string result in liquibase libraries for the checksum calculation function. (Checked in liquibase npm library).

### Steps To Reproduce

Execute following command and inspect the stdout and stderr.
```sh
liquibase calculate-checksum --url=<url> --username=<name> --password=<pass> --changelog-file=<changelog-file-path> --changeset-id=<id> --changeset-author=<author> --changeset-path=<changelog-file-path>
```
If I redirect the stdout(using `>`) to a file it is empty.
If I redirect the stderr(using `2>`) to a file the complete output is there along with the calculated checksum as below.
```
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ## 
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ## 
##                                                ##
####################################################
Starting Liquibase at 15:07:01 using Java 21.0.4 (version 4.29.0 #3278 built at 2024-07-24 22:00+0000)
Liquibase Version: 4.29.0
Liquibase Open Source 4.29.0 by Liquibase
9:14b6abef8f6c6d8d93b9c0c0adb0d48e
Liquibase command 'calculate-checksum' was executed successfully.
```

### Expected/Desired Behavior

The calculated checksum should written to the stdout buffer

### Liquibase Version

4.29.0

### Database Vendor & Version

PostgreSQL 16.3

### Liquibase Integration

CLI

### OS and/or Infrastructure Type/Provider

fedora 40

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @Ishad-M-I-M, thank you for reporting this issue. I've been able to replicate it with the latest Liquibase version.

I see you're willing to submit a PR, thank you!
You can go ahead and submit it, and our development team will be available for any questions you might have.

Thanks again,
Tatiana

**Comment by MalloD12** [comment]
Hi @Ishad-M-I-M,

If I'm not wrong this is not an issue and the command framework is working as designed. By default `calculate-checksum` command is printing its output on the console as you can see in L198 from `CalculateChecksumCommandStep`:

```java
Scope.getCurrentScope().getUI().sendMessage(checkSum.toString());
``` 

I think if you follow the same approach as mentioned in this [comment](https://github.com/liquibase/liquibase/issues/6139#issuecomment-2305549752). @filipelautert please correct me if I'm wrong and this is a different issue.

Thanks,
Daniel.

**Comment by Ishad-M-I-M** [comment]
> Hi @Ishad-M-I-M,
> 
> If I'm not wrong this is not an issue and the command framework is working as designed. By default `calculate-checksum` command is printing its output on the console as you can see in L198 from `CalculateChecksumCommandStep`:
> 
> ```java
> Scope.getCurrentScope().getUI().sendMessage(checkSum.toString());
> ```
> 
> I think if you follow the same approach as mentioned in this [comment](https://github.com/liquibase/liquibase/issues/6139#issuecomment-2305549752). @filipelautert please correct me if I'm wrong and this is a different issue.
> 
> Thanks, Daniel.

Hi @MalloD12 ,
Actually this is a root cause for an issue I faced while using [liquibase npm library](https://github.com/liquibase/node-liquibase) where `calculateCheckSum` function always returned an empty string. 
The result for the functions in npm library is from the stdout of the liquibase cli. Check this file: [https://github.com/liquibase/node-liquibase/blob/master/src/util/command-handler.ts](https://github.com/liquibase/node-liquibase/blob/master/src/util/command-handler.ts).

PS: I have used the `executeSql` function in  npm library and it returned the correct value as required, Because it writes the results to the stdout buffer. Check: [https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/command/core/ExecuteSqlCommandStep.java#L100](https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/command/core/ExecuteSqlCommandStep.java#L100). IMO, I think it's better to be consistent in writing results to the output buffers. i.e. Liquibase decorations to `stderror` and the intended output to `stdout`.
