### ISSUE TITLE
Liquibase throws unchecked exception in afterPropertiesSet() since 4.25 (introduced by #4584)

### ISSUE THREAD

**Issue by jetip** [liquibase/liquibase#6196]
### Search first

- [x] I searched and no similar issues were found

### Description

We're calling SpringLiquibase.afterPropertiesSet() by ourselves in a multi tenancy application. For whatever reason we had mismatching changeset checksums in a tenant database. Before 4.25, a LiquibaseException has been thrown in that case. Since 4.25 an UnexpectedLiquibaseException is thrown instead, which is a breaking change in my point of view. Our code is catching LiquibaseException and is now not able to handle that problem properly.

### Steps To Reproduce

* write a small Spring Boot application that uses Liquibase
* Create arbitrary changelog with some changesets
* Write a component calling SpringLiquibase.afterPropertiesSet() to let Liquibase do its work
* start application
* manually change one or more of the generated checksums within the changelog table
* restart application, exception due to mismatch will not be caught

### Expected/Desired Behavior

SpringLiquibase.afterPropertiesSet() should not throw an unchecked exception. It must be possible to catch a checksum mismatch exception using the signature's exception class.

### Liquibase Version

4.27

### Liquibase Integration

spring boot

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @jetip, thank you for reporting this issue. I can see that the reason for this behaviour is that, prior to PR #4584, the method `afterPropertiesSet()` only handled `SQLException`s, so the mismatched checksum error was being caught by the parent method.

We will be fixing this soon.
Thank you,
Tatiana

**Comment by jetip** [comment]
Thanks a lot for the quick response.

**Comment by filipelautert** [comment]
@jetip welcome! Just note that this is going into liquibase 4.30.0 , and not in 4.29.2 that is going t be release next week .
