### ISSUE TITLE
generate-changelog doesn't support --output-schemas as documented

### ISSUE THREAD

**Issue by trung** [liquibase/liquibase#6229]
### Search first

- [X] I searched and no similar issues were found

### Description

`--output-schemas` is documented but not supported when running `generate-changelog` command

### Steps To Reproduce

```
$ docker run --rm liquibase:4.29 --output-schemas=abc --schemas=xyz generate-changelog

Unexpected argument(s): --output-schemas=abc

For detailed help, try 'liquibase --help' or 'liquibase <command-name> --help'

Possible solutions: --output-file, --output-file-encoding, --output-line-separator
```

### Expected/Desired Behavior

`--output-schemas` is supported as in the documentation

### Liquibase Version

4.29

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by trung** [comment]
Looking at the code, should the right flag be `--output-schemas-as`?

**Comment by trung** [comment]
Sorry for the confusion. It turned out that the params have to be AFTER the command name.

The following works as expected

```
docker run --rm liquibase:4.29 generate-changelog --output-schemas=abc --schemas=xyz
```

**Comment by lbadam** [comment]
@trung no problem at all. Yes, since it's not global that param would need to come _after_ the command.
