### ISSUE TITLE
Useless warning log at startup

### ISSUE THREAD

**Issue by deblockt** [liquibase/liquibase#6230]
### Search first

- [X] I searched and no similar issues were found

### Description

Using liquibase spring integration I have this warning at startup: 
```
Schemas not defined, using defaultSchema only
```

I want to use the default schema, I don't understand why this log is a warning, can not be an info log? 

### Steps To Reproduce

Create a spring project using `MultiTenantSpringLiquibase` without set the `schemas` property.

### Expected/Desired Behavior

Have no warn logs at startup and use defaultSchema. 

### Liquibase Version

4.27.0

### Database Vendor & Version

Postgres 15

### Liquibase Integration

spring

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lbadam** [comment]
@deblockt thanks for filing this issue. Would you be willing to submit a PR to make this message log appropriately? We can provide guidance if you need.

**Comment by lbadam** [comment]
@deblockt thank you! We will take a look and review it.
