### ISSUE TITLE
includeAll not working when used on Wildfly EAR

### ISSUE THREAD

**Issue by Tirocigno** [liquibase/liquibase#6302]
### Search first

- [X] I searched and no similar issues were found

### Description

I have found a maybe similar issues(https://github.com/liquibase/liquibase/issues/6264), but I think this might be different due to the use of the JBoss Virtual File System(VFS) used inside Wildlfy to access resources

I am currently trying to run liquibase(the current version available on maven 4.29.1) from a JAR inside an EAR bundle deployed on a Wildfly server, as soon as I launch liquibase update command, i got the following error:
```
Caused by: java.io.IOException: Could not find/read changelogs from patches/ directory
 	at deployment.MyEAR.ear//liquibase.changelog.DatabaseChangeLog.findResources(DatabaseChangeLog.java:871)
 	... 76 more
 Caused by: java.io.IOException: Cannot parse resource location: 'vfs:/D:/wses02/MyEAR/scripts/content/MyEAR.ear/lib/Doc-1.0.0.jar/'
 	at deployment.MyEAR.ear//liquibase.resource.ClassLoaderResourceAccessor.search(ClassLoaderResourceAccessor.java:113)
 	at deployment.MyEAR.ear//liquibase.changelog.DatabaseChangeLog.findResources(DatabaseChangeLog.java:868)
 	... 76 more
 Caused by: java.io.IOException: Cannot parse resource location: 'vfs:/D:/wses02/MyEAR/scripts/content/MyEAR.ear/lib/Doc-1.0.0.jar/'
 	at deployment.MyEAR.ear//liquibase.resource.PathHandlerFactory.getResourceAccessor(PathHandlerFactory.java:35)
 	at deployment.MyEAR.ear//liquibase.resource.ClassLoaderResourceAccessor.search(ClassLoaderResourceAccessor.java:110)
 	... 77 more
```

The changelog.xml file and the changelists are available inside the Doc-1.0.0.jar, jar loaded inside the classpath(those file are available when accessed via ClassLoader.getResource() method)

My changelog.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
      http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.1.xsd">
    <includeAll path="patches/" relativeToChangelogFile="true" errorIfMissingOrEmpty="true"/>
</databaseChangeLog>
```
I've tried changing the path value with each possible combination of slashes(no slash, slash at start, slash at the end. both of them, set relativeToChangelogFile to false) but I am unable to find a workaround
The only workaround i was able to find was use the `include ` tag instead of `includeAll`, in that case liquibase run smoothly, but that tag works only on a single file and I must include a lot of them

Finally the structure of my resource folder(added to the classpath of the EJB Jar that launches liquibase)

```
Doc
└── src
  └── main
    └── resources
        ├── changelog.xml
        └── patches
          ├── 00001.0
            ├── patch0.sql
            └── patch1.sql
          ├── 00002.0
EJB
└── src
  └── main
    ├── java
      └──LiquibaseLauncher.java
    └── resources
```

### Steps To Reproduce

This is currently the block of java code that I run to launch liquibase from the EJB jar:

```
private void launchLiquibase() throws Exception {
        Database database = null;
        try {
            Connection connection = DriverManager.getConnection(
                    "jdbc:postgresql://localhost:5435/MY_DB", "username", "password");
            database = DatabaseFactory.getInstance()
                    .findCorrectDatabaseImplementation(new JdbcConnection(connection));
            String changeLogFile = "changelog.xml";
            URL changeLogURL = AppInitializer.class.getClassLoader().getResource(changeLogFile);

            if(changeLogURL != null) {
                ClassLoaderResourceAccessor classLoaderResources = new ClassLoaderResourceAccessor();
                Liquibase liquibase = new Liquibase(changeLogFile, classLoaderResources, database);
                liquibase.update(new Contexts(), new LabelExpression());
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (database != null && database.getConnection() != null) {
                database.close();
            }
        }
    }
```

### Expected/Desired Behavior

I expect to be able to run liquibase on a VFS based file system and use the `includeAll `tag inside the changelog.xml file.
Searching on Github/liquibase forum I've found of a couple of similar issues, but no one is specific to my problem with the current/recent version of the library.
I'm also wondering if I'm doing something wrong and if that's the case, how can I fix my code
Thanks a lot

### Liquibase Version

4.29.1, but tried also on older version, like for example 3.6.3

### Database Vendor & Version

Postgres 13.1

### Liquibase Integration

maven library call form java code

### Liquibase Extensions

liquibase-core

### OS and/or Infrastructure Type/Provider

Windows, Wildfly 22.0.0, Java 11.10.0

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lbadam** [comment]
@Tirocigno thanks for filing this issue. I'm not sure this repo is the best place to get the answer though. We don't know the specifics of Wildfly or what its requirements are. I would recommend asking this question in StackOverflow or filing an issue directly with Wildfly - https://issues.redhat.com/projects/WFLY/issues/WFLY-19709?filter=allopenissues. There are actually a handful of Liquibase-related issues already in their issue queue - https://issues.redhat.com/browse/HAWKULAR-171?jql=text%20~%20%22liquibase%22
