### ISSUE TITLE
ORACLE inconsistent datatypes: expected NUMBER got BOOLEAN

### ISSUE THREAD

**Issue by khaledhnAbusair** [liquibase/liquibase#6313]
### Search first

- [X] I searched and no similar issues were found

### Description

After upgrading Liquibase from version 3 to 4.29.1, the existing changeset for Oracle no longer works with the "BOOLEAN" datatype. When running the Spring application, the following error occurs: "inconsistent datatypes: expected NUMBER got BOOLEAN."

Note: I cannot change anything in the old changeset because those are supported multiple database types.

### Steps To Reproduce

Run this script in oracle 

`   <changeSet id="20211010" author="test">
        <sql dbms="mssql"> SET IDENTITY_INSERT mpay_jvtypes ON;</sql>
        <loadData file="/db/changelog/core/common/newdata/mpay_jvtypes_20211010.csv" separator=";"
                  tableName="mpay_jvtypes">
            <column name="id" type="NUMERIC"/>
            <column name="z_archive_on" type="DATE"/>
            <column name="z_archive_queued" type="DATE"/>
            <column name="z_archive_status" type="STRING"/>
            <column name="z_assigned_group" type="NUMERIC"/>
            <column name="z_assigned_user" type="NUMERIC"/>
            <column name="z_created_by" type="STRING"/>
            <column name="z_creation_date" type="DATE"/>
            <column name="z_deleted_by" type="STRING"/>
            <column name="z_deleted_flag" type="BOOLEAN"/>
            <column name="z_deleted_on" type="DATE"/>
            <column name="z_editable" type="BOOLEAN"/>
            <column name="z_locked_by" type="STRING"/>
            <column name="z_locked_until" type="DATE"/>
            <column name="z_org_id" type="NUMERIC"/>
            <column name="z_tenant_id" type="STRING"/>
            <column name="z_updated_by" type="STRING"/>
            <column name="z_updating_date" type="DATE"/>
            <column name="z_workflow_id" type="NUMERIC"/>
            <column name="z_ws_token" type="STRING"/>
            <column name="z_draft_status" type="STRING"/>
            <column name="code" type="STRING"/>
            <column name="description" type="STRING"/>
            <column name="name" type="STRING"/>
            <column name="z_draft_id" type="NUMERIC"/>
            <column name="z_status_id" type="NUMERIC"/>
        </loadData>
        <sql dbms="mssql"> SET IDENTITY_INSERT mpay_jvtypes OFF;</sql>
    </changeSet>`Oracle

### Expected/Desired Behavior

The scripts should run properly without any errors.

### Liquibase Version

4.29.1

### Database Vendor & Version

ojdbc11 v23.5.0.24.07

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @khaledhnAbusair, thank you for reporting this issue.

Could you send us the table structure and the logs produced by the error?

Thank you,
Tatiana

**Comment by khaledhnAbusair** [comment]
Thank you @tati-qalified  for trying to help me, 

This is the table structure 

`-- auto-generated definition
create table MPAY_JVTYPES
(
    ID               NUMBER(38) generated as identity
        constraint MPAY_JVTYPES_PKEY
            primary key,
    Z_ARCHIVE_ON     TIMESTAMP(6),
    Z_ARCHIVE_QUEUED TIMESTAMP(6),
    Z_ARCHIVE_STATUS VARCHAR2(255),
    Z_ASSIGNED_GROUP NUMBER(38),
    Z_ASSIGNED_USER  NUMBER(38),
    Z_CREATED_BY     VARCHAR2(255),
    Z_CREATION_DATE  TIMESTAMP(6),
    Z_DELETED_BY     VARCHAR2(255),
    Z_DELETED_FLAG   NUMBER(1),
    Z_DELETED_ON     TIMESTAMP(6),
    Z_EDITABLE       NUMBER(1),
    Z_LOCKED_BY      VARCHAR2(255),
    Z_LOCKED_UNTIL   TIMESTAMP(6),
    Z_ORG_ID         NUMBER(38),
    Z_TENANT_ID      VARCHAR2(255),
    Z_UPDATED_BY     VARCHAR2(255),
    Z_UPDATING_DATE  TIMESTAMP(6),
    Z_WORKFLOW_ID    NUMBER(38),
    Z_WS_TOKEN       VARCHAR2(255),
    Z_DRAFT_STATUS   VARCHAR2(255),
    CODE             VARCHAR2(255) not null,
    DESCRIPTION      VARCHAR2(255),
    NAME             VARCHAR2(255) not null,
    Z_DRAFT_ID       NUMBER(38)
        constraint FK_85KN4UIWFYRA69I8TJBEFR62G
            references JFW_DRAFTS,
    Z_STATUS_ID      NUMBER(38)
        constraint FK_3T1Q730504PVCJFCCXYM9DQEH
            references JFW_WF_STATUS,
    constraint UK_KENPH39KFWSQ4VGC6AXOPNL2R
        unique (NAME, Z_TENANT_ID),
    constraint UK_QB59JIHR6FMO5DNEBIK1HNBER
        unique (CODE, Z_TENANT_ID)
)
/

`

and this is the logs

[liquibase-error.txt](https://github.com/user-attachments/files/17085469/liquibase-error.txt)

**Comment by tati-qalified** [comment]
@khaledhnAbusair I haven't been able to replicate this issue.

I have three questions that might help me test this more effectively:
1. Are you using Java code inside your SpringBoot app to run Liquibase? 
2. Did you update your Oracle version **after** having created the table?
3. Did you update your Liquibase version after your Oracle version, or before?

**Comment by khaledhnAbusair** [comment]
Dear @tati-qalified any advice please?

**Comment by tati-qalified** [comment]
Hi @khaledhnAbusair, the main issue here is that the upgrade is nearly a 5-year jump, including a major version change (from 3.x to 4.x), so many things have changed in Liquibase code. We have managed to find the most likely cause of the error that you're experiencing: [this PR](https://github.com/liquibase/liquibase/pull/4579) changed the expected datatype from `NUMBER(1)` to `BOOLEAN` for Liquibase versions 4.24+ and Oracle versions 23c+.

There are three possible solutions that don't involve major refactoring on your end:
1. Add a changeset with a `<sql>` change type to update your columns of type `NUMBER(1)` to `BOOLEAN`. You can limit the scope of the changeset with the `dbms` [precondition](https://docs.liquibase.com/concepts/changelogs/preconditions.html)
2. Downgrade Liquibase to version 4.23.0, and keep your Oracle version at 23.5
3. Keep your Liquibase version at 4.29.1, and downgrade Oracle to version 22

Any of those should effectively solve the problem. I'll be closing this issue, but feel free to comment if you have any questions or if the problem persists.
Thank you,
Tatiana
