### ISSUE TITLE
Wrong documentation? contextFilter is not a valid attribute in <include>

### ISSUE THREAD

**Issue by caio303** [liquibase/liquibase#6338]
### Search first

- [X] I searched and no similar issues were found

### Description

Documentation says `<include>` tags allows `contextFilter` attribute for filtering contexts, but it's not being accepted with spring-boot/mvn integration

Error Message: `Attribute 'contextFilter' is not allowed to appear in element 'include'`

Version: liquibase-core-4.26.0

Is this really correct? Have I misunderstood it?

Tried using `context` too:
`Attribute 'context' is not allowed to appear in element 'include'.`

### Steps To Reproduce

Spring Properties file:
```properties
...

spring.liquibase.contexts=dev

...
```

Liquibase Changelog XML:
```xml
...

<include file="/path/to/file.xml" contextFilter="dev"/>

...
```

### Expected/Desired Behavior

`contextFilter` (or `context`) attribute should be allowed in `<include>` tags
![image](https://github.com/user-attachments/assets/e72a920d-4514-44a3-ac9a-30a9c9f4e599)

### Liquibase Version

liquibase-core-4.26.0

### Liquibase Integration

spring boot

### Are you willing to submit a PR?

I can take a look at it, but don't have any code already

**Comment by lbadam** [comment]
@caio303 thanks for filing this. Just to check - did you also try `context`?

**Comment by lbadam** [comment]
Ok. Thanks for that info. We will take a look and see what the issue is.

**Comment by wwillard7800** [comment]
This changelog works for me in the CLI integration:

`<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:pro="http://www.liquibase.org/xml/ns/pro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-latest.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">
    <include file="sqlFiles/postgres_create_table.sql" context="myContext"/>
    <include file="sqlFiles/postgres_create_table_next.sql" contextFilter="myContext"/>
</databaseChangeLog>
`

**Comment by wwillard7800** [comment]
And this changelog works for me with Spring Boot:

```
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">
  <changeSet id="1" author="wesley" context="first">
    <createTable tableName="processed_mail">
      <column name="messageid" type="varchar(100)">
        <constraints primaryKey="true" nullable="false"/>
      </column>
      <column name="issued" type="varchar(100)"/>
      <column name="author" type="varchar(100)"/>
      <column name="summary" type="varchar(512)"/>
    </createTable>
  </changeSet>
  <include file="sql/oracle_create_one_table.sql" context="myContext"/>
</databaseChangeLog>
```

**Comment by caio303** [comment]
Thank you for the examples @wwillard7800 !

It worked, the 
`xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd"`
was pointing to `dbchangelog-3.1.xsd` instead of `latest`
