### ISSUE TITLE
GenerateChangelogCommandStep always reports having written a Changelog file

### ISSUE THREAD

**Issue by catull** [liquibase/liquibase#6340]
### Search first

- [X] I searched and no similar issues were found

### Description

If you have an empty table or your includeObjects/excludeObjects result in no matches - because of a typo, there is no result set to generate a changelog file.
This is both true for SQL ans XML changelog generation.
Haven't tried a JSON variant.

### Steps To Reproduce

Perform a `generateChangeLog` on an empty table.

In the console, you will see

```
Generated changelog written to mytable.oracle.sql
```

But there is no such file.

This is not Oracle-specific.

### Expected/Desired Behavior

If no changelog file was produced, do not state it was generated.

### Liquibase Version

4.29.2

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by catull** [comment]
This bug is due to only checking if the a changelog file is defined, without checking its existance, see [here](https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java#L161).

```java
            if (StringUtil.trimToNull(changeLogFile) != null) {
                Scope.getCurrentScope().getUI().sendMessage("Generated changelog written to " + changeLogFile);
            }
```

**Comment by lbadam** [comment]
@catull thanks for filing this and pointing out where it occurs. We should definitely not show this message if nothing was generated.

**Comment by MalloD12** [comment]
Hi @catull,

Yes, you are right this is an issue in the IF block you have highlighted in your last [comment](https://github.com/liquibase/liquibase/issues/6340#issuecomment-2363014047). I think we should change that `IF` block to something like:

```java
if (!changeLogWriter.generateChangeSets().isEmpty()) {
                Scope.getCurrentScope().getUI().sendMessage("Generated changelog written to " + changeLogFile);
            }
            else {
                Scope.getCurrentScope().getUI().sendMessage(String.format("Changelog not created. There are not changesets to write to %s changelog", changeLogFile));
            }
```
Are you keen to implement these changes?  It would be nice to also add some tests to validate these scenarios, could you also do that?

Thanks,
Daniel.

**Comment by catull** [comment]
Dear @MalloD12 

Yes, I can implement the change, and add some test cases along with it.

Reagrds,
--
@catull
