### ISSUE TITLE
Liquibase Output change executed twice

### ISSUE THREAD

**Issue by jasonlyle88** [liquibase/liquibase#6342]
### Search first

- [X] I searched and no similar issues were found

### Description

When using a change type of `output`, the string to be output gets output twice instead of once.

It appears that with the output type, since it isn't actually a database change it is handled slightly differently than other change types. The `addSqlMdc` function of change generates the change to be done, but this triggers actually writing the output to the screen.

The actual execution of the change then occurs, and output the information a second time.

The `addSqlMdc` should not actually be executing the output.

### Steps To Reproduce

Create a changelog with an output change type

### Expected/Desired Behavior

Output only shows up once

### Liquibase Version

4.29.2

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by lbadam** [comment]
@jasonlyle88 thanks for filing this issue and for the PR. We will take a look at it 👍

**Comment by jasonlyle88** [comment]
Thanks, happy to help!

**Comment by wwillard7800** [comment]
@jasonlyle88 the fix for this is here, right?

https://github.com/liquibase/liquibase/pull/6343

**Comment by jasonlyle88** [comment]
> @jasonlyle88 the fix for this is here, right?
> 
> #6343

Yup, thats the PR for this
