### ISSUE TITLE
[V4.29.2] Diff Changelog does not include @Embedded changes in output file

### ISSUE THREAD

**Issue by amazing4u** [liquibase/liquibase#6344]
### Search first

- [X] I searched and no similar issues were found

### Description

Hi,

i want to inform you about a bug, which i found in version 4.28.0 - 4.29.2 and hibernate6 when adding an @Embedded - Type in Java Spring Boot Application.

The problem is in the liquibase-maven-plugin in version 4.28.0 - 4.29.2! The diff file will not include the changes.
 In Version 4.27.0 it worked!

### Steps To Reproduce

You can reproduce it with this example

pom.xml: use version 4.28.0 - 4.29.2:
```
<plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <version>4.29.2</version>
...
```

```
@Entity
@Table(name = "restaurants")
public class RestaurantEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Embedded
    private FavIcons favIcons;
}
```

```
@Embeddable
public record FavIcons(
        @Column(name="favicon32_url")
        String favicon32Url,

        @Column(name="favicon48_url")
        String favicon48Url
) {}
```

-> mvn liquibase:diff
```
...
[INFO] Found column favicon32_url varchar(255)
[INFO] Found column favicon48_url varchar(255)
...
[INFO] Creating snapshot
[INFO] Diff command completed
[INFO] BEST PRACTICE: The changelog generated by diffChangeLog/generateChangeLog should be inspected for correctness and completeness before being deployed. Some database objects and their dependencies cannot be represented automatically, and they may need to be manually updated before being deployed.
[INFO] changeSets count: 0
[INFO] No changesets to add to the changelog output.
[INFO] Diff changelog command succeeded
[INFO] Command execution complete
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.307 s
```

### Expected/Desired Behavior

The diff output file should include the added properties of the @Embedded class as it worked in version 4.27.0!

### Liquibase Version

4.29.2

### Database Vendor & Version

PostgreSQL 15

### Liquibase Integration

maven

### Liquibase Extensions

liquibase-maven-plugin

### OS and/or Infrastructure Type/Provider

Windows 11

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
This has been fixed by https://github.com/liquibase/liquibase-hibernate/pull/717, and wil be released with Liquibase 4.30.0 later this month.
