### ISSUE TITLE
Enhancement: Report which code-point in character set is causing XML generate-changelog to fail

### ISSUE THREAD

**Issue by catull** [liquibase/liquibase#6372]
### Search first

- [X] I searched and no similar issues were found

### Description

If a string column contains certain "characters", the `generate-changelog` with XML output fails with a generic error that is not helpful.

```
Unexpected error running Liquibase: Invalid string encoding on column.value. To resolve, remove the invalid character on the database and try again in changeSet TEST.oracle.xml::1727703198497-1::gugus (generated). To resolve, remove the invalid character on the database and try again
```

This experience could be improved by pointing out which code-point is causing it.

If the error were ....

```
Unexpected error running Liquibase: Invalid string encoding with **codePoint 25** on column.value. To resolve, remove the invalid character on the database and try again in changeSet TEST.oracle.xml::1727702701426-1::gugus (generated). To resolve, remove the invalid character on the database and try again
```

.... that would have saved me 4 hours of work.

### Steps To Reproduce

We have some very old data in the database, that have "invisible" characters in them, such as ASCII character 25, 26, 28 and 30.

In this case, the table data can be exported with `generate-changelog` to a file named "TEST.oracle.sql".

Exporting it to "TEST.oracle.xml" fails, because anyone of the codes mentioned cause this Exception, thrown [here](https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/serializer/core/xml/XMLChangeLogSerializer.java#L295)

The change is trivial

```
diff --git a/liquibase-standard/src/main/java/liquibase/serializer/core/xml/XMLChangeLogSerializer.java b/liquibase-standard/src/main/java/liquibase/serializer/core/xml/XMLChangeLogSerializer.java
index 6248857f6..351d0d4a7 100644
--- a/liquibase-standard/src/main/java/liquibase/serializer/core/xml/XMLChangeLogSerializer.java
+++ b/liquibase-standard/src/main/java/liquibase/serializer/core/xml/XMLChangeLogSerializer.java
@@ -292,7 +292,7 @@ public class XMLChangeLogSerializer implements ChangeLogSerializer {
                     ) {
                 //ok
             } else {
-                throw new UnexpectedLiquibaseException(INVALID_STRING_ENCODING_MESSAGE);
+                throw new UnexpectedLiquibaseException(INVALID_STRING_ENCODING_MESSAGE + " with codePoint " + codePoint);
             }
         }
```

After more than 4 hours, and with this change, I was able to pin-point 2 dozens of cases that needed to be cleaned-up.
Now, the export runs smoothly.

However, a code change is highly recommended.

### Expected/Desired Behavior

Better reporting to assist problem resolution.

### Liquibase Version

4.29.2

### Database Vendor & Version

any

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by lbadam** [comment]
@catull thank you for submitting this. I had one question - is `codePoint` something that's generally understood with regards to XML? Is there documentation on that specific reference and how users leverage it to debug?

**Comment by catull** [comment]
Hello @lbadam 

I am afraid I do not understand your question.

Here's my limited understanding.


The concept of `code point` is an Unicode thing.
It is an index into a map of so-called `grapheme`s.

During XML serialisation LiquiBase rejects a String if it contains some Characters based on their codepoints.
This happens when you generate a changelog of data to XML.

The alternative would be to embed the String into a [CDATA](https://en.wikipedia.org/wiki/CDATA) element, i.e. 
```xml
<![CDATA[String with suspicious graphemes]]>
```
.

However, we do not have enhanced XML serialisation right now.
I may bring this issue up separately.

The next best thing is to at least have better error reporting point out which `codePoint` is not acceptable.

**Comment by catull** [comment]
Hello @lbadam 


I am afraid I do not understand your question.

All I am suggesting is to guide the user, starting with printing the offending `code point`.


Here's my limited understanding.

The concept of `code point` is an Unicode thing.
It is an index into a map of so-called `grapheme`s.

During XML serialisation LiquiBase rejects a String if it contains some Characters based on their codepoints.
This happens when you generate a changelog of data to XML.

The alternative would be to embed the String into a [CDATA](https://en.wikipedia.org/wiki/CDATA) element, i.e. 
```xml
<![CDATA[String with suspicious graphemes]]>
```
.

However, we do not have enhanced XML serialisation right now.
I may bring this issue up separately.

The next best thing is to at least have better error reporting pointing out which `code point` is not acceptable.

**Comment by lbadam** [comment]
@catull thank you for the explanation and for the PR. We will review #6373 and get it in a future release.
