### ISSUE TITLE
Formatted SQL changeset labels are not picked up if spaces present

### ISSUE THREAD

**Issue by pbartoszek** [liquibase/liquibase#6390]
### Search first

- [x] I searched and no similar issues were found

### Description

I noticed that when label filter is set to `!MANUAL` and formatted sql changeset labels contains space i.e `labels: MANUAL`, filter doesn't work and changeset is applied. After removing space after : ie. `labels:MANUAL` filter works as expected.

### Steps To Reproduce

Example showing incorrect behaviour.

```
-- liquibase formatted sql

-- changeset pawel:10 labels: MANUAL

DROP TABLE IF EXISTS pawel;
```

I invoke code as 
```
     new CommandScope("updateSql")
                        ....
                        .addArgumentValue(LABEL_FILTER_ARG, "!MANUAL")
                        .execute();
```

### Expected/Desired Behavior

 label filter doesn't depend on spaces when defining `labels:`

### Liquibase Version

4.27.0

### Database Vendor & Version

MySQL 8

### Liquibase Integration

API

### OS and/or Infrastructure Type/Provider

Windows 11

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR (Thank you!)

**Comment by pbartoszek** [comment]
Ok I take a challenge to come up with a PR! Towards the end of week I will take a look at this.

**Comment by pbartoszek** [comment]
Parsing logic for changeset labels is based on regex `.*labels:(".*?"|\S*).*`. If labels parameter is wrapped in `""` regex will match it. However in following case labels:a, b regex would only match a, and b would be skipped. 

I think the problem is the way AbstractFormattedChangeLogParser works. Parsing is based on regex expressions which silently ignore any not matched strings.  

For example this doesn't throw any erorr
```
-- changeset pawel:11 context-xxx as sdav sdf dfs dfsdf (labels:a, b)
```
I am thinking that maybe better would be to use javacc grammars for parsing ?

**Comment by tati-qalified** [comment]
@pbartoszek yes, that may be a good idea. If you'll be modifying the abstract class, please make sure that you include tests for other changelog formats.
Thank you!

**Comment by lbadam** [comment]
@pbartoszek thanks for filing this and for your thoughts on it. We discussed this issue internally, and have decided that we will not fix this issue as described. 

The reasoning for that is:

- it is working as expected according to existing documentation and best practices
- adding validation for spaces this way would introduce too many other possibilities with the need to update every parameter plus all documentation

If there is documentation that needs to be updated where spaces are allowed, please put a link and we can make sure to update it.

Thanks again.

**Comment by pbartoszek** [comment]
@lbadam thanks for info. Maybe next time the communication could be improved. If I raised PR earlier (I haven't put any effort into it thankfully) my effort would be lost.

**Comment by lbadam** [comment]
@pbartoszek I understand, and thank you for bringing that up. Sorry for the delay on this decision.
