### ISSUE TITLE
Support dataType in createSequence for more DBMS

### ISSUE THREAD

**Issue by Alienmario** [liquibase/liquibase#6421]
### Search first

- [x] I searched and no similar issues were found

### Description

It seems that a "data type" parameter for sequence creation is available more broadly than liquibase [currently supports](https://docs.liquibase.com/change-types/create-sequence).

I have checked HSQLDB and MSSQL, both appear to support it.

Related to #3328, which added such support for DB2LUW.

### Steps To Reproduce

Run on HSQLDB or MSSQL

```<createSequence sequenceName="MY_SEQUENCE" dataType="BIGINT" startValue="1" incrementBy="1"/>```

### Expected/Desired Behavior

No validation failures

### Liquibase Version

4.28.0

### Database Vendor & Version

hsqldb 2.7.2

### Liquibase Integration

maven

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lbadam** [comment]
@Alienmario thanks for filing this issue. To clarify, are you suggesting that we need to update the `dataType` documentation [here](https://docs.liquibase.com/change-types/create-sequence.html) to add additional supported DBs?

![Image](https://github.com/user-attachments/assets/626120a6-8473-4147-80a9-6e5fc2b2d2e9)

**Comment by Alienmario** [comment]
No, I am asking to implement/allow specifying dataType for additional databases, similiar to mentioned PR.

**Comment by lbadam** [comment]
@Alienmario ok. If a DB has support for dataType it should automatically work unless it's in [this list](https://github.com/liquibase/liquibase/blob/45501b0529af8d68979a6883ee0323b732aac5f0/liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java#L53). That list does include HSQLDB and MSSQL so we can start by rechecking those and removing them from the list.

Are you open to submitting a PR for those changes?

**Comment by Alienmario** [comment]
@lbadam Sure, I can have a try at it.

Browsing the CreateSequenceGenerator code, i'm noticing additional discrepancies between databases:

- The ["IF NOT EXISTS"](https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java#L69) keyword automatically appended in Postgres is also available at least in [HSQLDB](https://hsqldb.org/doc/guide/databaseobjects-chapt.html). Would it be desirable to have it added?
- For databases **HsqlDatabase** and **Db2zDatabase** ["AS BIGINT"](https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java#L76) is currently forced, ignoring the specified datatype. I'm assuming this is because these databases default to INTEGER data type, if not specified. However, since both support specifying dataType, I would like to change this behavior to only run when no dataType is specified in liquibase. 
- I would also add "normal" **DB2Database** to the above as it also defaults to INTEGER for sequences. [1](https://www.ibm.com/docs/en/i/7.4?topic=statements-create-sequence), [2](https://www.ibm.com/docs/en/db2/11.5?topic=statements-create-sequence) 
- The ["cacheSize"](https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java#L100) parameter support does not correspond with documentation. However, that can be handled in another issue.
