### ISSUE TITLE
Announcement: Scheduled Maintenance October 19, 2024

### ISSUE THREAD

**Issue by lbadam** [liquibase/liquibase#6423]
### Search first

- [x] I searched and no similar issues were found

### Description

A scheduled maintenance window is planned for Saturday, October 19, 2024 starting at 8am CEST / 2am EDT / 1am CDT. During this time, access to services such as Liquibase websites and XSDs (for users on older versions of Liquibase) may be affected.

Any disruptions should be temporary, and are expected to resolve quickly.

### Steps To Reproduce

--

### Expected/Desired Behavior

--

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by jnewton03** [comment]
Maintenance is complete.  If you experience any issues please reply here.
