### ISSUE TITLE
defaultValueBoolean does not work on oracle

### ISSUE THREAD

**Issue by janzanda** [liquibase/liquibase#6447]
### Search first

- [x] I searched and no similar issues were found

### Description

defaultValueBoolean="false" puts "false" into sql when assigning property value, which causes SQL error ORA-01722 Invalid Number. 
(oracle boolean is in real number(1) )

### Steps To Reproduce

create changeset with table, which any column has defaultValueBoolean="false" or "true" set.  Run on oracle DB. 

### Expected/Desired Behavior

defaultValueBoolean should be translated to db specific format when parsed to sql query. In this case, false=0, true=1. 

### Liquibase Version

4.9.1

### Database Vendor & Version

oracle/database:19.3.0-ee

### Liquibase Integration

spring boot

### OS and/or Infrastructure Type/Provider

macos 15, ubuntu, windows 11

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lbadam** [comment]
@janzanda thank you for filing the issue. Are you able to test this on a more recent version of Liquibase? Latest is 4.29.2. 

Also, can you let us know what commands you're trying to run when you have this problem?

**Comment by janzanda** [comment]
I am unable to elevate to 4.29.2, due to other factors in our project. I would have to refactor dozens of change requests to meet this version validation requirements.  

Here is the xml changeset we use (redacted of several columns not related to the issue):
~~~
  <changeSet id="create_table_gapless" author="janzanda">
        <createTable tableName="gapless">
            <column name="id" type="${type.bigint}"
                    autoIncrement="false"
                    defaultValueSequenceNext="gapless_seq">
                <constraints primaryKey="true"/>
             </column>
             <column name="cycle" type="${type.boolean}" defaultValueBoolean="false">
                   <constraints nullable="false"/>
             </column>
        </createTable>
</changeset>
~~~

this is behind the ${type.boolean} definition:

~~~
    <property name="type.boolean" value="BOOLEAN" dbms="h2"/>
    <property name="type.boolean" value="BOOLEAN" dbms="postgresql"/>
    <property name="type.boolean" value="BIT" dbms="mssql"/>
    <property name="type.boolean" value="NUMBER(1)" dbms="oracle"/>
~~~

**Comment by tati-qalified** [comment]
Hi @janzanda, thank you for reaching out to us. I've tested this using the changeset you've provided and Liquibase version 4.9.1 and I was able to replicate it. It's not replicable with 4.29.2, so it has been fixed at some point since then.

Considering that you're unable to update your Liquibase version, an easy way to work around this issue is to use the `modifySql` change type as follows:
```
    <changeSet id="create_table_gapless" author="janzanda">
        <createTable tableName="gapless">
            <column name="id" type="int"
                autoIncrement="false">
                <constraints primaryKey="true" />
            </column>
            <column name="cycle" type="${type.boolean}" defaultValueBoolean="false">
                <constraints nullable="false" />
            </column>
        </createTable>
        <modifySql>
            <replace replace="false" with="0" />
        </modifySql>
    </changeSet>
```

You can find more information about this change type [here](https://docs.liquibase.com/change-types/modify-sql.html).

I'll be closing this issue as it has been fixed, but feel free to comment if you have any other questions or concerns.
Thank you,
Tatiana

**Comment by janzanda** [comment]
Thanks! We will look into upgrading next iteration. The workaround is good enough. 

Jan
