### ISSUE TITLE
includeAll doesn't take into account file extension during sorting

### ISSUE THREAD

**Issue by pbartoszek** [liquibase/liquibase#6450]
### Search first

- [x] I searched and no similar issues were found

### Description

I noticed that file ordering is based on file name plus extension which might lead to confusing behaviour. 
For example given two files `01.main.sql` and `01.main-101.sql` Liquibase would pick up `01.main-101.sql` first because standard comparator https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java#L1145 looks at file path as a string and `.` character comes later than `-` in ascii table ie.
01.main`-`101.sql
01.main`.`sql

### Steps To Reproduce

create master change log
```
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
  xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">

  <includeAll path="sql" relativeToChangelogFile="true" />

</databaseChangeLog>
```
and put files `01.main.sql` and `01.main-101.sql` inside sql directory.

### Expected/Desired Behavior

default comparator should skip .extension part of the filename or there should be extension skipping comparator available in Liquibase to configure using `resourceComparator`

### Liquibase Version

4.27.0

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @pbartoszek, thank you for reaching out to us.
File sorting algorithms change from application to application, for example Windows' File Explorer and VSCode:
![Image](https://github.com/user-attachments/assets/d9c300be-c723-4c30-be80-9e404785e84d) ![Image](https://github.com/user-attachments/assets/083282b0-f446-47e4-8fe6-f0260ec4114f)

Liquibase sorts files considering the entire name as a string. Changing this behaviour would be a big breaking change, as scripts or changelogs would be run in different order, and changing the file names would create different checksums for the changesets.

I'll be closing this issue as it's not something we're planning on changing, but we encourage users to leave a comment if they would also want this modification.

Thank you,
Tatiana
