### ISSUE TITLE
Migrations Reapplying on Upgrade to 4.30.0 Causing Boot Errors

### ISSUE THREAD

**Issue by rduboismyca** [liquibase/liquibase#6507]
### Search first

- [x] I searched and no similar issues were found

### Description

After upgrading from Liquibase 4.29.2 to 4.30.0, it attempts to reapply changesets that have already been executed, leading to errors like "table already exists."

Here’s a log excerpt showing the error when running Liquibase 4.30.0:

2024-11-08 08:40:32,088 INFO l.util [restartedMain] UPDATE SUMMARY
2024-11-08 08:40:32,088 INFO l.util [restartedMain] Run:                          0
2024-11-08 08:40:32,088 INFO l.util [restartedMain] Previously run:              36
2024-11-08 08:40:32,088 INFO l.util [restartedMain] Filtered out:                 0
2024-11-08 08:40:32,088 INFO l.util [restartedMain] -------------------------------
2024-11-08 08:40:32,088 INFO l.util [restartedMain] Total change sets:           96
2024-11-08 08:40:32,089 INFO l.util [restartedMain] Update summary generated

### Steps To Reproduce

- Spring boot : 3.3.5
- Gradle : 8.10.2
- Java 21
- Liquibase: 4.30.0, no specific configuration
- Migration scripts: SQL format

1. Start with Liquibase version 4.29.2 and a set of applied migration files.
2. Upgrade to Liquibase 4.30.0.
3. Run the application

Note : 
Rollbacking to 4.29.2 causes no issues and the application runs as expected

### Expected/Desired Behavior

Liquibase should detect the migrations that were already applied and only apply new changesets.

### Liquibase Version

4.30.0

### Database Vendor & Version

MySQL 8.1.0

### Liquibase Integration

Spring boot, Gradle

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @rduboismyca, thank you for reporting this issue.
Could you upgrade to v4.30.0, run update-sql and provide the output?
Thank you

**Comment by filipelautert** [comment]
@stevequindo could you share the changeset that you are facing this issue? Then we can reproduce it here to track and fix this issue. Thanks!

**Comment by filipelautert** [comment]
> filename: 26-a-script-that's-already-executed.sql
> 
> ALTER TABLE custom_resource ADD COLUMN existing-coloumn TEXT DEFAULT NULL;

sorry, I mean the include tag, like :    ` <include  file="changelogs/sql/raw-file.sql" />`

Cause using this simple include works for me - 4.30.0 is not re-running it. But maybe other flags that you can be using are affecting it.

**Comment by tati-qalified** [comment]
@stevequindo @rduboismyca  I've tested this with the CLI as well as with Gradle + Spring Boot, but I can't replicate it. The old id format is being recognised and the changesets aren't being run again.

Are you using `logicalFilePath`? Or are there any other configurations that might be affecting the checksum calculation?

**Comment by SheheryarAamir** [comment]
I have the same problem in my project. DATACAHNGELOG table contains `raw` as ID and after upgrade to 4.30.0 liquibase reapplying the migration because 4.30.0 has a different strategy for generating an ID and generates `raw` + <<FILE_NAME>> as ID.

**Comment by filipelautert** [comment]
@tati-qalified seems that @wwillard7800  found out how to reproduce it, the key is to have a forward slash starting the include` file="/apps/myFile.sql"` . Could you try to reproduce it now?

Here is a proposed fix: https://github.com/liquibase/liquibase/pull/6529

**Comment by rduboismyca** [comment]
Apologies for the delayed response—I was on vacation.

I was previously using the following path:
`<include file="classpath:database/migration/V1_Create_Users_Table.sql"/>`

However, I removed the "classpath:" prefix and tested it again with version 4.30.0. It now seems to work as expected.
