### ISSUE TITLE
liquibase drops logs of raise notices when used with postgresql upgrade

### ISSUE THREAD

**Issue by thehealer15** [liquibase/liquibase#6508]
### Search first

- [x] I searched and no similar issues were found

### Description

i have setup liquibase + postgresql 
liquibase drops the raise notice/msg/info/exception/log/message if its in given as <sqlFile> 

basically changelog is like
<changelog label .... > 
   <sqlFile> --> going to postgrsql file 
<syhntax complete> whatever we give in raise syntaxes will be dropeed 

### Steps To Reproduce

simply write a changelog with sqlfile changeset 
and give raise notice' messsssage' 

or any raise syntax
that gets dropped 

### Expected/Desired Behavior

raise should get directed to default log feli

### Liquibase Version

4.2.19

### Database Vendor & Version

postgresql 14.3

### OS and/or Infrastructure Type/Provider

rhel

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @thehealer15, thank you for reaching out to us.
The message will be displayed when Liquibase's log level is set to the equivalent of the raised message's level. So, `RAISE EXCEPTION` will always be displayed (and will stop the execution), and `WARNING, INFO` and `NOTICE` will be displayed with Liquibase's `log-level=warn`.

For `LOG` and `DEBUG`, make sure to set `log_min_messages` and `client_min_messages` to the appropriate values, and they will be shown with Liquibase's `log-level=info` or `log-level=fine`.

I will be closing this issue as it isn't a bug, but feel free to leave a comment if the problem persists.

Thank you,
Tatiana
