### ISSUE TITLE
Spring 3.4.0 compatibility broken

### ISSUE THREAD

**Issue by AlessioDiFazio** [liquibase/liquibase#6534]
### Search first

- [x] I searched and no similar issues were found

### Description

The class `org.springframework.boot.autoconfigure.liquibase.LiquibaseProperties` in spring 3.4.0 returns lists for the `getContexts()` and `getLabelFilter()`, but the class `liquibase.integration.spring.SpringLiquibase` does not support this yet (still using simple String). This breaks the spring boot compatibility and integration

### Steps To Reproduce

Use Spring-Boot dependency `org.springframework.boot:spring-boot-autoconfigure:3.4.0` and `liquibase-core:4.30.0`

### Expected/Desired Behavior

Methods should be compatible

### Liquibase Version

4.30.0

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by AlessioDiFazio** [comment]
This can be closed. It was an issue on my side.

**Comment by vitalii-crm** [comment]
what was the issue? did I understood correctly that need to use `liquibase.setContexts(StringUtils.collectionToCommaDelimitedString(liquibaseProperties.getContexts()));` ?

**Comment by artursemenenko-nag** [comment]
@vitalii-crm 

Damn, thanks for this suggestion. It fixed the problem. I had the same problem migrating from spring 3.3
It seems to me that noone mentioned this adaptation anywhere in release logs after changing this behaviour! :)`

Did you have the same issue with `get/setLabelFilter` ?
